#!/usr/bin/env python3
"""Generate the 21-lesson PHP deep curriculum for the 100xsystems registry.

Uses the shared gen_lib.py template. Produces:
  - static-data/knowledge/languages/php/php-*.md (21 lesson files)
  - updated index.json lessons array (categories preserved)
  - removes stale skeleton files
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_lib import main as run_gen  # noqa: E402

LANGUAGE = 'php'
BASE = 'static-data/knowledge/languages/php'

LESSONS = [
    dict(slug='php-01-getting-started', title='Getting Started with PHP',
         desc='Install PHP, run scripts from the CLI, and understand the request lifecycle.',
         dur='45 min', diff='beginner', prereq=[],
         objs=['Install PHP and run your first script',
               'Use echo, print, and var_dump for output',
               'Understand the CLI vs web SAPIs',
               'Configure php.ini essentials'],
         refs=[dict(title='PHP Manual — Installation', url='https://www.php.net/manual/en/install.php'),
               dict(title='PHP Manual — CLI SAPI', url='https://www.php.net/manual/en/features.commandline.php'),
               dict(title='PHP The Right Way', url='https://phptherightway.com/')]),
    dict(slug='php-02-variables-types', title='Variables and Data Types',
         desc='Scalar types, arrays, type juggling, and strict typing.',
         dur='60 min', diff='beginner', prereq=['PHP-01'],
         objs=['Declare variables and understand the eight data types',
               'Use type juggling and explicit casts',
               'Enforce strict_types in modern PHP',
               'Work with constants and null'],
         refs=[dict(title='PHP Manual — Types', url='https://www.php.net/manual/en/language.types.php'),
               dict(title='PHP Manual — Variables', url='https://www.php.net/manual/en/language.variables.php'),
               dict(title='PHP 8 Type System Overview', url='https://php.watch/articles/php-type-system')]),
    dict(slug='php-03-numbers-math', title='Numbers and Math',
         desc='Integers, floats, integer overflow, and math functions.',
         dur='50 min', diff='beginner', prereq=['PHP-02'],
         objs=['Use int and float with their limits',
               'Handle precision loss and overflow',
               'Use bcmath for exact decimal arithmetic',
               'Generate random numbers safely'],
         refs=[dict(title='PHP Manual — Integers', url='https://www.php.net/manual/en/language.types.integer.php'),
               dict(title='PHP Manual — Floating Point', url='https://www.php.net/manual/en/language.types.float.php'),
               dict(title='PHP Manual — Math Functions', url='https://www.php.net/manual/en/ref.math.php')]),
    dict(slug='php-04-strings', title='Strings and String Functions',
         desc='String literals, interpolation, and the string function toolbox.',
         dur='60 min', diff='beginner', prereq=['PHP-02'],
         objs=['Write strings with single/double quotes, heredoc, and nowdoc',
               'Interpolate variables safely',
               'Manipulate strings with built-in functions',
               'Work with multibyte strings via mbstring'],
         refs=[dict(title='PHP Manual — Strings', url='https://www.php.net/manual/en/language.types.string.php'),
               dict(title='PHP Manual — String Functions', url='https://www.php.net/manual/en/ref.strings.php'),
               dict(title='PHP Manual — mbstring', url='https://www.php.net/manual/en/book.mbstring.php')]),
    dict(slug='php-05-control-flow', title='Control Flow',
         desc='Conditionals, match expressions, and loops.',
         dur='50 min', diff='beginner', prereq=['PHP-02'],
         objs=['Use if/elseif/else and ternary conditions',
               'Replace switch with the match expression',
               'Iterate with for, foreach, while, and do-while',
               'Break, continue, and goto responsibly'],
         refs=[dict(title='PHP Manual — Control Structures', url='https://www.php.net/manual/en/language.control-structures.php'),
               dict(title='PHP Manual — match', url='https://www.php.net/manual/en/control-structures.match.php'),
               dict(title='PHP Manual — foreach', url='https://www.php.net/manual/en/control-structures.foreach.php')]),
    dict(slug='php-06-arrays', title='Arrays',
         desc='Indexed and associative arrays, array functions, and sorting.',
         dur='60 min', diff='beginner', prereq=['PHP-05'],
         objs=['Build indexed and associative arrays',
               'Add, remove, and look up elements',
               'Use array_* functions for transformation',
               'Sort arrays with stable comparators'],
         refs=[dict(title='PHP Manual — Arrays', url='https://www.php.net/manual/en/language.types.array.php'),
               dict(title='PHP Manual — Array Functions', url='https://www.php.net/manual/en/ref.array.php'),
               dict(title='PHP Manual — Sorting Arrays', url='https://www.php.net/manual/en/array.sorting.php')]),
    dict(slug='php-07-functions', title='Functions',
         desc='Declarations, parameters, variadics, and return types.',
         dur='60 min', diff='beginner', prereq=['PHP-05'],
         objs=['Define functions with typed parameters and returns',
               'Use default values and named arguments',
               'Collect extra args with variadics',
               'Pass by reference and by value correctly'],
         refs=[dict(title='PHP Manual — User-Defined Functions', url='https://www.php.net/manual/en/functions.user-defined.php'),
               dict(title='PHP Manual — Function Arguments', url='https://www.php.net/manual/en/functions.arguments.php'),
               dict(title='PHP Manual — Returning Values', url='https://www.php.net/manual/en/functions.returning-values.php')]),
    dict(slug='php-08-oop-classes', title='Classes and Objects',
         desc='Properties, methods, constructors, and object semantics.',
         dur='75 min', diff='intermediate', prereq=['PHP-07'],
         objs=['Define classes with typed properties and methods',
               'Use constructors, promotion, and readonly properties',
               'Understand objects as references',
               'Use visibility, static, and const members'],
         refs=[dict(title='PHP Manual — Classes and Objects', url='https://www.php.net/manual/en/language.oop5.php'),
               dict(title='PHP Manual — Properties', url='https://www.php.net/manual/en/language.oop5.properties.php'),
               dict(title='PHP 8.2 Readonly Classes', url='https://www.php.net/manual/en/language.oop5.properties.php')]),
    dict(slug='php-09-namespaces-autoloading', title='Namespaces and Autoloading',
         desc='Namespaces, use statements, and PSR-4 autoloading with Composer.',
         dur='60 min', diff='intermediate', prereq=['PHP-08'],
         objs=['Organize code with namespaces',
               'Import symbols with use',
               'Register an autoloader',
               'Follow PSR-4 conventions'],
         refs=[dict(title='PHP Manual — Namespaces', url='https://www.php.net/manual/en/language.namespaces.php'),
               dict(title='PHP-FIG — PSR-4 Autoloading', url='https://www.php-fig.org/psr/psr-4/'),
               dict(title='Composer Autoloading', url='https://getcomposer.org/doc/01-basic-usage.md#autoloading')]),
    dict(slug='php-10-inheritance-traits', title='Inheritance and Traits',
         desc='extends, abstract classes, interfaces, and trait composition.',
         dur='75 min', diff='intermediate', prereq=['PHP-08'],
         objs=['Extend classes and override methods',
               'Design with abstract classes and interfaces',
               'Compose behavior with traits',
               'Use final and prevent misuse'],
         refs=[dict(title='PHP Manual — Inheritance', url='https://www.php.net/manual/en/language.oop5.inheritance.php'),
               dict(title='PHP Manual — Interfaces', url='https://www.php.net/manual/en/language.oop5.interfaces.php'),
               dict(title='PHP Manual — Traits', url='https://www.php.net/manual/en/language.oop5.traits.php')]),
    dict(slug='php-11-errors-exceptions', title='Errors and Exceptions',
         desc='Throwables, try/catch/finally, and custom exceptions.',
         dur='60 min', diff='intermediate', prereq=['PHP-07'],
         objs=['Distinguish Error from Exception',
               'Catch and handle exceptions with try/catch/finally',
               'Throw typed exceptions',
               'Set a global error handler'],
         refs=[dict(title='PHP Manual — Exceptions', url='https://www.php.net/manual/en/language.exceptions.php'),
               dict(title='PHP Manual — Throwable', url='https://www.php.net/manual/en/class.throwable.php'),
               dict(title='PHP Manual — Error Handling', url='https://www.php.net/manual/en/book.errorfunc.php')]),
    dict(slug='php-12-files-streams', title='Files and Streams',
         desc='Reading and writing files, streams, and JSON.',
         dur='60 min', diff='intermediate', prereq=['PHP-07'],
         objs=['Read and write files safely',
               'Use stream wrappers',
               'Encode and decode JSON',
               'Handle binary data'],
         refs=[dict(title='PHP Manual — Filesystem', url='https://www.php.net/manual/en/book.filesystem.php'),
               dict(title='PHP Manual — Streams', url='https://www.php.net/manual/en/book.stream.php'),
               dict(title='PHP Manual — JSON Functions', url='https://www.php.net/manual/en/ref.json.php')]),
    dict(slug='php-13-databases-pdo', title='Databases with PDO',
         desc='PDO, prepared statements, and safe database access.',
         dur='75 min', diff='intermediate', prereq=['PHP-12'],
         objs=['Connect with PDO and DSNs',
               'Use prepared statements to prevent SQL injection',
               'Fetch data in different modes',
               'Manage transactions'],
         refs=[dict(title='PHP Manual — PDO', url='https://www.php.net/manual/en/book.pdo.php'),
               dict(title='PHP Manual — PDO::prepare', url='https://www.php.net/manual/en/pdo.prepare.php'),
               dict(title='PHP Manual — PDO Transactions', url='https://www.php.net/manual/en/pdo.transactions.php')]),
    dict(slug='php-14-web-basics', title='Web Basics: HTTP, Forms, Sessions',
         desc='Superglobals, HTTP headers, form handling, and sessions.',
         dur='75 min', diff='intermediate', prereq=['PHP-13'],
         objs=['Read requests via superglobals',
               'Send responses with headers',
               'Validate and sanitize form input',
               'Manage state with sessions'],
         refs=[dict(title='PHP Manual — Superglobals', url='https://www.php.net/manual/en/language.variables.superglobals.php'),
               dict(title='PHP Manual — Sessions', url='https://www.php.net/manual/en/book.session.php'),
               dict(title='PHP Manual — Header Function', url='https://www.php.net/manual/en/function.header.php')]),
    dict(slug='php-15-functional', title='Functional PHP',
         desc='Closures, arrow functions, and higher-order helpers.',
         dur='60 min', diff='intermediate', prereq=['PHP-07'],
         objs=['Create closures and bind state with use',
               'Write concise arrow functions',
               'Use array_map, array_filter, array_reduce',
               'Leverage first-class callable syntax'],
         refs=[dict(title='PHP Manual — Anonymous Functions', url='https://www.php.net/manual/en/functions.anonymous.php'),
               dict(title='PHP Manual — Arrow Functions', url='https://www.php.net/manual/en/functions.arrow.php'),
               dict(title='PHP Manual — array_map', url='https://www.php.net/manual/en/function.array-map.php')]),
    dict(slug='php-16-datetime', title='Dates and Time',
         desc='DateTime, DateTimeImmutable, and timezone handling.',
         dur='50 min', diff='intermediate', prereq=['PHP-07'],
         objs=['Work with DateTime and DateTimeImmutable',
               'Format and parse dates',
               'Handle timezones correctly',
               'Calculate intervals and differences'],
         refs=[dict(title='PHP Manual — DateTimeImmutable', url='https://www.php.net/manual/en/class.datetimeimmutable.php'),
               dict(title='PHP Manual — DateTimeInterface', url='https://www.php.net/manual/en/class.datetimeinterface.php'),
               dict(title='PHP Manual — Date and Time Functions', url='https://www.php.net/manual/en/book.datetime.php')]),
    dict(slug='php-17-regex', title='Regular Expressions',
         desc='PCRE patterns, preg_match, and replacement.',
         dur='50 min', diff='intermediate', prereq=['PHP-07'],
         objs=['Write PCRE patterns',
               'Match with preg_match and preg_match_all',
               'Replace and split with preg_ functions',
               'Use capture groups and modifiers'],
         refs=[dict(title='PHP Manual — PCRE', url='https://www.php.net/manual/en/book.pcre.php'),
               dict(title='PHP Manual — preg_match', url='https://www.php.net/manual/en/function.preg-match.php'),
               dict(title='PCRE Patterns Syntax', url='https://www.php.net/manual/en/reference.pcre.pattern.syntax.php')]),
    dict(slug='php-18-composer', title='Composer and Packages',
         desc='Composer.json, dependency management, and Packagist.',
         dur='60 min', diff='intermediate', prereq=['PHP-09'],
         objs=['Initialize a composer project',
               'Add and manage dependencies',
               'Understand version constraints',
               'Publish and consume packages'],
         refs=[dict(title='Composer Documentation', url='https://getcomposer.org/doc/'),
               dict(title='Packagist', url='https://packagist.org/'),
               dict(title='Composer Versions Guide', url='https://getcomposer.org/doc/articles/versions.md')]),
    dict(slug='php-19-testing', title='Testing with PHPUnit',
         desc='Unit tests, assertions, and data providers.',
         dur='60 min', diff='intermediate', prereq=['PHP-18'],
         objs=['Write PHPUnit test classes',
               'Use assertions and expectations',
               'Structure tests with data providers',
               'Run the test suite from the CLI'],
         refs=[dict(title='PHPUnit Documentation', url='https://docs.phpunit.de/en/11.5/index.html'),
               dict(title='PHPUnit Writing Tests', url='https://docs.phpunit.de/en/11.5/writing-tests-for-phpunit.html'),
               dict(title='PHPUnit Data Providers', url='https://docs.phpunit.de/en/11.5/attributes.html')]),
    dict(slug='php-20-generators-fibers', title='Generators and Fibers',
         desc='yield generators, iterators, and cooperative concurrency with Fibers.',
         dur='75 min', diff='advanced', prereq=['PHP-15'],
         objs=['Create generators with yield',
               'Stream large datasets lazily',
               'Suspend and resume with Fibers',
               'Compare coroutines to blocking code'],
         refs=[dict(title='PHP Manual — Generators', url='https://www.php.net/manual/en/language.generators.php'),
               dict(title='PHP Manual — Fiber', url='https://www.php.net/manual/en/class.fiber.php'),
               dict(title='PHP 8.1 Fibers RFC', url='https://wiki.php.net/rfc/fibers')]),
    dict(slug='php-21-security-performance', title='Security and Performance',
         desc='Injection defense, escaping, opcache, and profiling.',
         dur='75 min', diff='advanced', prereq=['PHP-14'],
         objs=['Prevent SQL injection and XSS',
               'Use password hashing correctly',
               'Leverage OPcache for speed',
               'Profile with Xdebug and identify hotspots'],
         refs=[dict(title='PHP Manual — Security', url='https://www.php.net/manual/en/security.php'),
               dict(title='PHP Manual — OPcache', url='https://www.php.net/manual/en/book.opcache.php'),
               dict(title='PHP Manual — Xdebug', url='https://www.php.net/manual/en/ref.xdebug.php')]),
]

CODE = {
    1: [
        '<?php\n// hello.php — run with: php hello.php\necho "Hello, 100x Systems!\\n";\nprint "Another way to output.\\n";\nvar_dump(42);          // int(42)\nvar_dump("php");       // string(3) "php"',
        '<?php\n// CLI arguments\nvar_dump($argv);        // [0] script path, [1..] user args\n$name = $argv[1] ?? "world";\necho "Hello, $name\\n";',
        '<?php\n// SAPI check\nif (PHP_SAPI === "cli") {\n    echo "Running on the CLI\\n";\n} else {\n    echo "Running under a web server\\n";\n}\nprintf("PHP %s on %s\\n", PHP_VERSION, PHP_OS);',
        '<?php\n// php.ini essentials visible at runtime\necho "display_errors: " . ini_get("display_errors") . "\\n";\necho "memory_limit: " . ini_get("memory_limit") . "\\n";\n// set for this process only\nini_set("memory_limit", "256M");',
    ],
    2: [
        '<?php\ndeclare(strict_types=1);  // strict mode: no silent coercion\n$i = 42;        // int\n$f = 3.14;      // float\n$s = "hello";   // string\n$b = true;      // bool\n$n = null;      // null\nvar_dump($i, $f, $s, $b, $n);',
        '<?php\n// type juggling (loose mode default)\nvar_dump("42" + 8);        // int(50)  — numeric string coerced\nvar_dump("5 apples" * 2);  // int(10)  — leading numeric part\nvar_dump((int)"3.99");     // int(3)   — explicit cast\nvar_dump((string)100);     // string(3) "100"',
        '<?php\ndeclare(strict_types=1);\nfunction add(int $a, int $b): int {\n    return $a + $b;\n}\n// In strict mode this throws TypeError, not coercion:\ntry {\n    add("5", 3);\n} catch (TypeError $e) {\n    echo "TypeError: " . $e->getMessage() . "\\n";\n}',
        '<?php\ndefine("APP_NAME", "100x");   // global constant\nconst VERSION = "1.0";         // compile-time constant\n$value = null;\n$result = $value ?? "default";  // null coalescing\nvar_dump(APP_NAME, VERSION, $result);',
    ],
    3: [
        '<?php\n// integer limits\n$max = PHP_INT_MAX;      // 9223372036854775807 (64-bit)\n$min = PHP_INT_MIN;\n$big = $max + 1;         // becomes float (silent overflow)\nvar_dump($max, $min, $big);\necho PHP_INT_SIZE . " bytes\\n";',
        '<?php\n// float precision pitfall\n$a = 0.1;\n$b = 0.2;\nvar_dump($a + $b);           // float(0.30000000000000004)\nvar_dump($a + $b === 0.3);    // bool(false)\n// use an epsilon comparison\necho abs(($a + $b) - 0.3) < 1e-9 ? "close enough\\n" : "not close\\n";',
        '<?php\n// bcmath: arbitrary precision for money\n$a = "0.1";\n$b = "0.2";\n$sum = bcadd($a, $b, 2);      // "0.30"\necho $sum . "\\n";\necho bcmul("12.50", "3", 2) . "\\n";  // "37.50"',
        '<?php\n// safe random numbers (CSPRNG)\n$roll = random_int(1, 6);          // unbiased int\necho "d6: $roll\\n";\necho bin2hex(random_bytes(8)) . "\\n";  // 16 hex chars\n// deterministic pseudo-random for games\nmt_srand(42);\necho mt_rand(1, 10) . "\\n";',
    ],
    4: [
        '<?php\n// string literals\n$single = \'It costs $5\\n\';       // no interpolation, literal \\n\n$double = "Total: $5\\n";          // interpolation attempted\n$name = "Alice";\n$interp = "Hi $name, welcome!";   // simple interpolation\n$braced = "Hi {$name}s, welcome!"; // brace to disambiguate\necho $single . $interp . "\\n" . $braced . "\\n";',
        '<?php\n// heredoc (interpolates) and nowdoc (does not)\n$name = "Bob";\n$heredoc = <<<TXT\nHello $name,\nmulti-line string here.\nTXT;\n$nowdoc = <<<\'TXT\'\nHello $name,\nliteral $name here.\nTXT;\necho $heredoc . "\\n" . $nowdoc;',
        '<?php\n// the string toolbox\n$s = "  Hello, World  ";\necho strlen($s) . "\\n";            // 16\necho strtoupper(trim($s)) . "\\n"; // HELLO, WORLD\necho substr($s, 2, 5) . "\\n";     // Hello\necho str_replace("World", "PHP", $s) . "\\n";\necho str_contains($s, "World") ? "yes\\n" : "no\\n";',
        '<?php\n// multibyte safety with mbstring\n$utf8 = "héllo wörld";\necho strlen($utf8) . " " . mb_strlen($utf8) . "\\n";  // 12 11\n$emoji = "🚀 rocket";\necho mb_strlen($emoji) . "\\n";     // 7 (not 8 bytes)\necho mb_strtoupper($utf8) . "\\n";  // HÉLLO WÖRLD',
    ],
    5: [
        '<?php\n$score = 85;\nif ($score >= 90) {\n    echo "A\\n";\n} elseif ($score >= 80) {\n    echo "B\\n";\n} else {\n    echo "C\\n";\n}\n// ternary + null coalescing\n$grade = $score >= 50 ? "pass" : "fail";\necho $grade . "\\n";',
        '<?php\n// match is an expression: returns a value, strict ===\n$status = 404;\n$message = match ($status) {\n    200, 204 => "ok",\n    404     => "not found",\n    500     => "server error",\n    default => "unknown",\n};\necho $message . "\\n";  // not found',
        '<?php\n// loops\nfor ($i = 0; $i < 5; $i++) { echo $i; }       // 01234\necho "\\n";\n$items = ["a", "b", "c"];\nforeach ($items as $k => $v) { echo "$k:$v "; } // 0:a 1:b 2:c\necho "\\n";\n$n = 0;\nwhile ($n < 3) { echo $n++; }                  // 012\necho "\\n";',
        '<?php\n// break/continue\nfor ($i = 1; $i <= 10; $i++) {\n    if ($i % 3 === 0) continue;   // skip multiples of 3\n    if ($i === 8) break;\n    echo $i;\n}\necho "\\n";  // 12457',
    ],
    6: [
        '<?php\n// indexed and associative arrays\n$fruits = ["apple", "banana", "cherry"];\n$user = [\n    "name" => "Alice",\n    "age" => 30,\n    "admin" => true,\n];\n$fruits[] = "date";            // append\nunset($user["age"]);           // remove\necho count($fruits) . "\\n";    // 4\necho $user["name"] . "\\n";',
        '<?php\n// array key/array functions\n$nums = [3, 1, 4, 1, 5];\nvar_dump(in_array(4, $nums, true));  // bool(true) strict\necho array_search(5, $nums) . "\\n"; // index 4\necho max($nums) . " " . min($nums) . "\\n";\necho array_sum($nums) . "\\n";       // 14',
        '<?php\n// transform and filter\n$nums = [1, 2, 3, 4, 5];\n$doubled = array_map(fn($n) => $n * 2, $nums);\n$evens   = array_filter($nums, fn($n) => $n % 2 === 0);\n$sum     = array_reduce($nums, fn($c, $n) => $c + $n, 0);\nvar_dump($doubled, array_values($evens), $sum);',
        '<?php\n// sorting\n$words = ["pear", "apple", "Mango", "banana"];\nsort($words);                    // in-place, case-sensitive\nvar_dump($words);\n$users = [["name" => "Bob", "age" => 40], ["name" => "Amy", "age" => 25]];\nusort($users, fn($a, $b) => $a["age"] <=> $b["age"]);\nvar_dump(array_column($users, "name"));  // Amy Bob',
    ],
    7: [
        '<?php\n// typed functions\ndeclare(strict_types=1);\nfunction greet(string $name, int $times = 1): string {\n    return str_repeat("Hi $name! ", $times);\n}\necho greet("Alice") . "\\n";          // Hi Alice!\necho greet("Bob", 2) . "\\n";         // Hi Bob! Hi Bob!\n// named arguments (PHP 8+)\necho greet(times: 3, name: "Cal") . "\\n";',
        '<?php\n// variadics collect extra args\nfunction sum(...$nums): int {\n    return array_sum($nums);\n}\necho sum(1, 2, 3, 4) . "\\n";   // 10\n// spread to unpack\n$args = [5, 6];\necho sum(...$args) . "\\n";     // 11',
        '<?php\n// union types and nullable\nfunction parse(mixed $value): int|float {\n    return is_numeric($value) ? $value + 0 : 0;\n}\nfunction maybe(?string $s): string {\n    return $s ?? "empty";\n}\nvar_dump(parse("3.5"), parse(7), maybe(null));',
        '<?php\n// by-reference and by-value\nfunction byValue(int $n): int { $n++; return $n; }\nfunction byRef(int &$n): void { $n++; }\n$x = 10;\necho byValue($x) . "\\n";  // 11\nbyRef($x);\necho $x . "\\n";           // 11',
    ],
    8: [
        '<?php\n// basic class with typed properties\nclass Product {\n    public function __construct(\n        public readonly string $name,\n        public readonly float $price,\n        public int $stock = 0,\n    ) {}\n    public function summary(): string {\n        return "{$this->name} — \\${$this->price} (stock: {$this->stock})";\n    }\n}\n$p = new Product("Keyboard", 49.99, 12);\necho $p->summary() . "\\n";',
        '<?php\n// objects are references\nclass Counter { public int $n = 0; }\n$a = new Counter();\n$b = $a;              // $b points to the SAME object\n$b->n = 5;\necho $a->n . "\\n";   // 5\necho ($a === $b ? "same instance\\n" : "different\\n");',
        '<?php\n// visibility\nclass Bank {\n    private int $balance = 0;\n    protected string $owner;\n    public function __construct(string $owner) { $this->owner = $owner; }\n    public function deposit(int $amount): void { $this->balance += $amount; }\n    public function balance(): int { return $this->balance; }\n}\n$acc = new Bank("Alice");\n$acc->deposit(100);\n// $acc->balance = 999;  // Fatal: cannot access private\n// use the accessor instead\necho $acc->balance() . "\\n";',
        '<?php\n// static members\nclass MathHelper {\n    public const PI = 3.14159;\n    private static int $calls = 0;\n    public static function square(int $n): int {\n        self::$calls++;\n        return $n * $n;\n    }\n    public static function calls(): int { return self::$calls; }\n}\necho MathHelper::PI . "\\n";\necho MathHelper::square(9) . "\\n";\necho MathHelper::calls() . "\\n";',
    ],
    9: [
        '<?php\n// file: src/Acme/Logger.php\nnamespace Acme;\nclass Logger {\n    public function log(string $msg): void { echo "[LOG] $msg\\n"; }\n}',
        '<?php\n// file: src/Acme/User.php\nnamespace Acme;\nclass User { public function __construct(public string $name) {} }',
        '<?php\n// consuming namespaces\nuse Acme\\Logger;\nuse Acme\\User as Account;\n$logger = new Logger();\n$logger->log("startup");\n$user = new Account("Alice");\necho $user->name . "\\n";',
        '<?php\n// simple autoloader + PSR-4 flavor\nspl_autoload_register(function (string $class): void {\n    $prefix = "Acme\\\\";\n    if (str_starts_with($class, $prefix)) {\n        $rel = substr($class, strlen($prefix));\n        $file = __DIR__ . "/src/" . str_replace("\\\\", "/", $rel) . ".php";\n        if (is_file($file)) require $file;\n    }\n});\n// composer does this for you: require __DIR__ . \'/vendor/autoload.php\';\n$logger = new \\Acme\\Logger();\n$logger->log("autoloaded");',
    ],
    10: [
        '<?php\n// inheritance\nclass Animal {\n    public function __construct(protected string $name) {}\n    public function speak(): string { return "..."; }\n}\nclass Dog extends Animal {\n    public function speak(): string { return "Woof!"; }\n}\n$d = new Dog("Rex");\necho $d->speak() . "\\n";  // Woof!',
        '<?php\n// abstract class\nabstract class Shape {\n    abstract public function area(): float;\n    public function describe(): string {\n        return "Area: " . $this->area();\n    }\n}\nclass Circle extends Shape {\n    public function __construct(private float $r) {}\n    public function area(): float { return pi() * $this->r ** 2; }\n}\necho (new Circle(2))->describe() . "\\n";',
        '<?php\n// interface + multiple via composition\ninterface Loggable {\n    public function toLog(): string;\n}\nclass Order implements Loggable {\n    public function __construct(private int $id) {}\n    public function toLog(): string { return "order:$this->id"; }\n}\nforeach ([new Order(1), new Order(2)] as $o) {\n    echo $o->toLog() . "\\n";\n}',
        '<?php\n// traits compose behavior without inheritance\ntrait Timestampable {\n    private \\DateTimeImmutable $createdAt;\n    public function touch(): void {\n        $this->createdAt = new \\DateTimeImmutable();\n    }\n    public function createdAt(): string {\n        return $this->createdAt->format("Y-m-d H:i:s");\n    }\n}\nclass Post { use Timestampable; }\n$post = new Post();\n$post->touch();\necho $post->createdAt() . "\\n";',
    ],
    11: [
        '<?php\n// try/catch/finally\nfunction risky(int $n): int {\n    if ($n < 0) throw new InvalidArgumentException("negative!");\n    if ($n === 0) throw new RuntimeException("zero!");\n    return 100 / $n;\n}\ntry {\n    echo risky(0) . "\\n";\n} catch (InvalidArgumentException $e) {\n    echo "bad input: " . $e->getMessage() . "\\n";\n} catch (RuntimeException $e) {\n    echo "runtime: " . $e->getMessage() . "\\n";\n} finally {\n    echo "always runs\\n";\n}',
        '<?php\n// Throwable covers both Error and Exception\nfunction fail(): void {\n    throw new TypeError("wrong type");\n}\ntry {\n    fail();\n} catch (Throwable $t) {\n    echo get_class($t) . ": " . $t->getMessage() . "\\n";\n}',
        '<?php\n// custom exception types\nclass PaymentFailed extends RuntimeException {}\nclass InsufficientFunds extends PaymentFailed {}\nfunction charge(float $amount): void {\n    if ($amount > 100) throw new InsufficientFunds("limit exceeded");\n}\ntry {\n    charge(500);\n} catch (PaymentFailed $e) {   // catches the subtype too\n    echo "payment error: " . $e->getMessage() . "\\n";\n}',
        '<?php\n// global error handler + throw on error\nset_error_handler(function (int $severity, string $msg, string $file, int $line): bool {\n    if (!(error_reporting() & $severity)) return false;\n    throw new ErrorException($msg, 0, $severity, $file, $line);\n});\n// now a PHP warning becomes an exception\ntry {\n    $fp = fopen("/nonexistent/file", "r");\n} catch (ErrorException $e) {\n    echo "caught warning as exception: " . $e->getMessage() . "\\n";\n}',
    ],
    12: [
        '<?php\n// reading and writing\n$content = file_get_contents("data.txt");\nfile_put_contents("out.txt", strtoupper($content));\n// line by line\n$lines = file("data.txt", FILE_IGNORE_NEW_LINES);\nforeach ($lines as $line) { echo "> $line\\n"; }',
        '<?php\n// JSON round-trip\n$data = ["name" => "Alice", "skills" => ["php", "sql"], "active" => true];\n$json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);\necho $json . "\\n";\n$back = json_decode($json, true);       // associative array\nvar_dump($back["skills"]);\nif (json_last_error() !== JSON_ERROR_NONE) {\n    echo "JSON error: " . json_last_error_msg() . "\\n";\n}',
        '<?php\n// stream wrappers\n$url = "https://example.com/";\n$html = @file_get_contents($url);\n// php:// memory stream\n$fp = fopen("php://memory", "w+");\nfwrite($fp, "buffered");\nrewind($fp);\necho stream_get_contents($fp) . "\\n";  // buffered\nfclose($fp);',
        '<?php\n// binary + fgetcsv\n$csv = "name,age\\nAlice,30\\nBob,25\\n";\n$fp = fopen("php://memory", "r+");\nfwrite($fp, $csv);\nrewind($fp);\nwhile (($row = fgetcsv($fp)) !== false) {\n    echo implode("|", $row) . "\\n";\n}\nfclose($fp);',
    ],
    13: [
        '<?php\n// PDO connection (SQLite for the demo)\n$pdo = new PDO("sqlite::memory:");\n$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);\n$pdo->exec("CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, age INT)");\n// prepared statement protects against injection\n$stmt = $pdo->prepare("INSERT INTO users (name, age) VALUES (?, ?)");\n$stmt->execute(["Alice", 30]);\n$stmt->execute(["Bob", 25]);',
        '<?php\n// named placeholders\n$pdo = new PDO("sqlite::memory:");\n$pdo->exec("CREATE TABLE t (name TEXT, city TEXT)");\n$stmt = $pdo->prepare("INSERT INTO t (name, city) VALUES (:name, :city)");\n$stmt->execute([":name" => "Alice", ":city" => "Paris"]);\n$stmt->execute([":name" => "Bob", ":city" => "London"]);\necho $pdo->query("SELECT COUNT(*) FROM t")->fetchColumn() . "\\n";  // 2',
        '<?php\n// fetch modes\n$pdo = new PDO("sqlite::memory:");\n$pdo->exec("CREATE TABLE t (id INTEGER, name TEXT)");\n$pdo->exec("INSERT INTO t VALUES (1, \'Alice\'), (2, \'Bob\')");\n$rows = $pdo->query("SELECT * FROM t")->fetchAll(PDO::FETCH_ASSOC);\nvar_dump($rows);\n// as objects\nclass Row {}\n$objs = $pdo->query("SELECT * FROM t")->fetchAll(PDO::FETCH_CLASS, Row::class);\necho $objs[0]->name . "\\n";',
        '<?php\n// transactions\n$pdo = new PDO("sqlite::memory:");\n$pdo->exec("CREATE TABLE accounts (id INTEGER PRIMARY KEY, balance INT)");\n$pdo->exec("INSERT INTO accounts VALUES (1, 100), (2, 0)");\n$pdo->beginTransaction();\ntry {\n    $pdo->exec("UPDATE accounts SET balance = balance - 50 WHERE id = 1");\n    $pdo->exec("UPDATE accounts SET balance = balance + 50 WHERE id = 2");\n    $pdo->commit();\n} catch (Throwable $e) {\n    $pdo->rollBack();\n    throw $e;\n}\nforeach ($pdo->query("SELECT * FROM accounts") as $row) {\n    echo $row["id"] . ":" . $row["balance"] . " ";\n}\necho "\\n";  // 1:50 2:50',
    ],
    14: [
        '<?php\n// superglobals\n// $_GET["q"] — query string (?q=php)\n// $_POST["name"] — form body\n// $_SERVER["REQUEST_METHOD"] — GET/POST/...\n$q = $_GET["q"] ?? "default";\necho "query: " . htmlspecialchars($q) . "\\n";\necho "method: " . $_SERVER["REQUEST_METHOD"] . "\\n";',
        '<?php\n// sending HTTP headers\nheader("Content-Type: application/json");\nheader("Cache-Control: no-store");\nhttp_response_code(200);\n$payload = ["ok" => true, "items" => [1, 2, 3]];\necho json_encode($payload);',
        '<?php\n// form validation + sanitization\n$email = filter_input(INPUT_POST, "email", FILTER_VALIDATE_EMAIL);\n$age   = filter_input(INPUT_POST, "age", FILTER_VALIDATE_INT);\nif ($email === false) { echo "invalid email\\n"; }\n$clean = htmlspecialchars((string) ($_POST["name"] ?? ""), ENT_QUOTES);\n// ALWAYS escape on output to prevent XSS\necho "<p>Hello, $clean</p>\\n";',
        '<?php\n// sessions\nsession_start();\n$_SESSION["user_id"] = 42;\n$_SESSION["cart"] = ["kbd", "mouse"];\n// on later requests the same session is resumed\necho "user_id: " . ($_SESSION["user_id"] ?? "none") . "\\n";\nsession_destroy();  // careful: clears the session',
    ],
    15: [
        '<?php\n// closures capture state with use\n$factor = 2;\n$multiply = function (int $n) use ($factor): int {\n    return $n * $factor;\n};\necho $multiply(21) . "\\n";  // 42\n// closures are objects: can bind\n$greet = function (): string { return "Hi " . $this->name; };\n$bound = $greet->bindTo((object) ["name" => "Alice"]);\necho $bound() . "\\n";',
        '<?php\n// arrow functions are compact and capture automatically\n$tax = 0.2;\n$prices = [10, 20, 30];\n$withTax = array_map(fn(int $p): float => $p * (1 + $tax), $prices);\nvar_dump($withTax);',
        '<?php\n// higher-order helpers\n$people = [\n    ["name" => "Alice", "age" => 30],\n    ["name" => "Bob", "age" => 17],\n    ["name" => "Cal", "age" => 25],\n];\n$adults = array_filter($people, fn($p) => $p["age"] >= 18);\n$names = array_map(fn($p) => $p["name"], $adults);\nsort($names);\nvar_dump($names);  // Alice Cal',
        '<?php\n// first-class callable syntax (PHP 8.1+)\n$toUpper = strtoupper(...);\n$words = ["php", "100x"];\nvar_dump(array_map($toUpper, $words));\n// invoke any callable\necho is_callable($toUpper) ? "callable\\n" : "no\\n";',
    ],
    16: [
        '<?php\n// DateTime basics\n$now = new DateTime();\necho $now->format("Y-m-d H:i:s") . "\\n";\n$date = new DateTime("2026-07-29 10:30:00", new DateTimeZone("UTC"));\necho $date->format("D, d M Y") . "\\n";',
        '<?php\n// DateTimeImmutable: never mutates\ntry {\n    $d = new DateTimeImmutable("2026-07-29");\n    $plus = $d->modify("+10 days");\n    echo $d->format("Y-m-d") . "\\n";     // unchanged\n    echo $plus->format("Y-m-d") . "\\n";  // 2026-08-08\n} catch (Exception $e) {\n    echo "parse error: " . $e->getMessage() . "\\n";\n}',
        '<?php\n// timezone handling\n$zones = ["UTC", "America/New_York", "Asia/Kolkata"];\n$utc = new DateTime("2026-07-29 12:00:00", new DateTimeZone("UTC"));\nforeach ($zones as $z) {\n    $local = clone $utc;\n    $local->setTimezone(new DateTimeZone($z));\n    echo $z . ": " . $local->format("H:i") . "\\n";\n}',
        '<?php\n// intervals and differences\n$a = new DateTimeImmutable("2026-01-01");\n$b = new DateTimeImmutable("2026-07-29");\n$diff = $a->diff($b);\necho $diff->days . " days\\n\";\necho $diff->format("%y years %m months %d days") . "\\n\";',
    ],
    17: [
        '<?php\n// preg_match captures\n$text = "Order #12345 placed on 2026-07-29";\npreg_match("/#(\\d+)/", $text, $m);\necho $m[1] . "\\n\";  // 12345\npreg_match("/(\\d{4})-(\\d{2})-(\\d{2})/", $text, $d);\necho "$d[1]/$d[2]/$d[3]\\n\";',
        '<?php\n// preg_match_all\n$log = "GET /api 200\\nPOST /api 201\\nGET / 404";\npreg_match_all("#(\\w+) /\\S* (\\d{3})#", $log, $rows, PREG_SET_ORDER);\nforeach ($rows as $r) { echo $r[1] . " -> " . $r[2] . "\\n"; }',
        '<?php\n// replace and split\n$s = "  Trim   me   please  ";\n$clean = preg_replace("/\\s+/", " ", trim($s));\necho $clean . "\\n\";  // Trim me please\n$parts = preg_split("/[,\\s]+/", "apple, banana cherry");\nvar_dump($parts);',
        '<?php\n// modifiers and validation\n$email = "alice@example.com";\n$pattern = "/^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$/i";\necho preg_match($pattern, $email) ? "valid\\n" : "invalid\\n\";\n// non-capturing groups + lookahead\npreg_match("/(?:\\d{3}-)?\\d{4}/", "555-1234", $m);\necho $m[0] . "\\n\";',
    ],
    18: [
        '<?php\n// composer.json (minimal)\n// {\n//   "require": { "php": ">=8.2", "monolog/monolog": "^3.0" }\n// }\n// commands:\n//   composer init   — create composer.json\n//   composer install — install from lockfile\n//   composer require monolog/monolog — add + install\n//   composer update  — update within constraints',
        '<?php\n// using a dependency\nrequire __DIR__ . "/vendor/autoload.php";\nuse Monolog\\Logger;\nuse Monolog\\Handler\\StreamHandler;\n$log = new Logger("app");\n$log->pushHandler(new StreamHandler(__DIR__ . "/app.log", Logger::DEBUG));\n$log->info("booted", ["pid" => getmypid()]);',
        '<?php\n// version constraints\n// "monolog/monolog": "^3.0"   — >=3.0.0 <4.0.0 (major locked)\n// "psr/log": "~1.0"           — >=1.0.0 <1.1.0\n// "guzzlehttp/guzzle": "*"    — any (avoid in production)\n// exact: "1.2.3"  |  range: ">=1.0 <2.0"\n// the lockfile (composer.lock) pins exact versions for reproducibility',
        '<?php\n// scripts in composer.json\n// {\n//   "scripts": {\n//     "test": "phpunit",\n//     "lint": "php -l src",\n//     "post-install-cmd": ["@php artisan migrate"]\n//   }\n// }\n// run: composer test   (composer run-script test)\n// $COMPOSER_VENDOR_DIR and env vars control behaviour',
    ],
    19: [
        '<?php\n// phpunit test class\nuse PHPUnit\\Framework\\TestCase;\nfinal class CalculatorTest extends TestCase {\n    public function testAddition(): void {\n        $calc = new Calculator();\n        $this->assertSame(4, $calc->add(2, 2));\n    }\n}\n// run: ./vendor/bin/phpunit --testdox',
        '<?php\n// data providers\nuse PHPUnit\\Framework\\Attributes\\DataProvider;\nuse PHPUnit\\Framework\\TestCase;\nfinal class MulTest extends TestCase {\n    #[DataProvider("pairs")]\n    public function testMul(int $a, int $b, int $expected): void {\n        $this->assertSame($expected, $a * $b);\n    }\n    public static function pairs(): array {\n        return [[2, 3, 6], [0, 9, 0], [-1, 5, -5]];\n    }\n}',
        '<?php\n// expectations (PHPUnit 10+)\nuse PHPUnit\\Framework\\TestCase;\nfinal class OrderTest extends TestCase {\n    public function testChargeThrowsOnNegative(): void {\n        $order = new Order();\n        $this->expectException(InvalidArgumentException::class);\n        $this->expectExceptionMessage("negative");\n        $order->charge(-5);\n    }\n}',
        '<?php\n// test doubles\nuse PHPUnit\\Framework\\TestCase;\nfinal class NotifierTest extends TestCase {\n    public function testSendsOnSignup(): void {\n        $mailer = $this->createMock(Mailer::class);\n        $mailer->expects($this->once())\n               ->method("send")\n               ->with($this->stringContains("Welcome"));\n        $service = new SignupService($mailer);\n        $service->signup("alice@example.com");\n    }\n}',
    ],
    20: [
        '<?php\n// generator yields lazily\nfunction squares(int $n): Generator {\n    for ($i = 1; $i <= $n; $i++) {\n        yield $i * $i;\n    }\n}\nforeach (squares(5) as $s) { echo "$s "; }\necho "\\n";  // 1 4 9 16 25\n// nothing runs until iteration starts — lazy!',
        '<?php\n// yield with keys + delegating with yield from\nfunction pairs(): Generator {\n    yield "a" => 1;\n    yield "b" => 2;\n}\nfunction all(): Generator {\n    yield 0;\n    yield from pairs();\n    yield 99;\n}\nforeach (all() as $k => $v) { echo "$k=>$v "; }\necho "\\n";  // 0=>0 a=>1 b=>2 99=>99',
        '<?php\n// streaming a huge file\nfunction readLines(string $path): Generator {\n    $fp = fopen($path, "r");\n    while (($line = fgets($fp)) !== false) {\n        yield rtrim($line, "\\r\\n");\n    }\n    fclose($fp);\n}\nforeach (readLines("big.log") as $n => $line) {\n    if ($n > 2) break;   // memory stays flat\n    echo $line . "\\n";\n}',
        '<?php\n// Fiber: cooperative multitasking (PHP 8.1+)\n$fiber = new Fiber(function (): void {\n    $value = Fiber::suspend("waiting...");\n    echo "resumed with: $value\\n";\n});\necho $fiber->start() . "\\n\";  // waiting...\n$fiber->resume("payload");      // resumed with: payload\n// yields control without blocking — foundation of async libraries',
    ],
    21: [
        '<?php\n// SQL injection defense: parameterized queries only\n$pdo = new PDO("sqlite::memory:");\n$pdo->exec("CREATE TABLE t (id INTEGER, name TEXT)");\n$userInput = "Alice\'; DROP TABLE t; --";\n$stmt = $pdo->prepare("INSERT INTO t (name) VALUES (?)");\n$stmt->execute([$userInput]);  // stored literally, harmless\necho $pdo->query("SELECT COUNT(*) FROM t")->fetchColumn() . "\\n";',
        '<?php\n// XSS defense: escape on output\n$user = "<script>alert(1)</script>";\necho htmlspecialchars($user, ENT_QUOTES, "UTF-8") . "\\n";\n// never: echo $user;  — raw injection into HTML',
        '<?php\n// password hashing\n$hash = password_hash("s3cret!", PASSWORD_DEFAULT);\n$ok = password_verify("s3cret!", $hash);\necho $ok ? "verified\\n" : "failed\\n\";\n// never store plain text; never md5/sha1 for passwords\n// PASSWORD_DEFAULT auto-upgrades as PHP evolves',
        '<?php\n// OPcache + profiling\n// php.ini: opcache.enable=1, opcache.memory_consumption=128\nif (function_exists("opcache_get_status")) {\n    $s = opcache_get_status(false);\n    echo "cached scripts: " . $s["opcache_statistics"]["num_cached_scripts"] . "\\n\";\n}\n// profile with Xdebug: xdebug.mode=profile\n$start = hrtime(true);\nusleep(1000);   // simulate work\necho "elapsed ms: " . ((hrtime(true) - $start) / 1e6) . "\\n\";',
    ],
}


if __name__ == '__main__':
    run_gen(LANGUAGE, 'php', LESSONS, CODE, BASE)
