#!/usr/bin/env python3
"""Generate the 21-lesson Dart deep curriculum for the 100xsystems registry.

Uses the shared gen_lib.py template. Produces:
  - static-data/knowledge/languages/dart/dart-*.md (21 lesson files)
  - updated index.json lessons array (categories preserved)
  - removes stale skeleton files
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_lib import main as run_gen  # noqa: E402

LANGUAGE = 'dart'
BASE = 'static-data/knowledge/languages/dart'

LESSONS = [
    dict(slug='dart-01-getting-started', title='Getting Started with Dart',
         desc='Install Dart, run scripts, and meet the Dart VM.',
         dur='45 min', diff='beginner', prereq=[],
         objs=['Install Dart and run your first program',
               'Use print and string interpolation',
               'Pass command-line arguments',
               'Understand the Dart VM and compilation modes'],
         refs=[dict(title='Dart — Get Started', url='https://dart.dev/get-started'),
               dict(title='Dart — Language Tour', url='https://dart.dev/language'),
               dict(title='DartPad', url='https://dartpad.dev/')]),
    dict(slug='dart-02-variables-types', title='Variables and Data Types',
         desc='var, final, const, and the core built-in types.',
         dur='60 min', diff='beginner', prereq=['DART-01'],
         objs=['Declare variables with var and typed forms',
               'Use final and const for immutability',
               'Work with int, double, String, bool, and lists',
               'Use dynamic and Object judiciously'],
         refs=[dict(title='Dart — Variables', url='https://dart.dev/language/variables'),
               dict(title='Dart — Built-in Types', url='https://dart.dev/language/built-in-types'),
               dict(title='Dart — Final and Const', url='https://dart.dev/language/variables#final-and-const')]),
    dict(slug='dart-03-numbers-math', title='Numbers and Math',
         desc='int, double, num, and the dart:math library.',
         dur='50 min', diff='beginner', prereq=['DART-02'],
         objs=['Use int, double, and the num supertype',
               'Convert between numeric types',
               'Use dart:math functions',
               'Generate random numbers'],
         refs=[dict(title='Dart — Numbers', url='https://dart.dev/language/built-in-types#numbers'),
               dict(title='Dart — dart:math Library', url='https://api.dart.dev/stable/dart-math/dart-math-library.html'),
               dict(title='Dart — Numbers API', url='https://api.dart.dev/stable/dart-core/num-class.html')]),
    dict(slug='dart-04-strings', title='Strings and String Manipulation',
         desc='String literals, interpolation, and the string API.',
         dur='60 min', diff='beginner', prereq=['DART-02'],
         objs=['Write single, double, and triple-quoted strings',
               'Interpolate with $ and ${}',
               'Manipulate strings with the standard library',
               'Handle multi-line and raw strings'],
         refs=[dict(title='Dart — Strings', url='https://dart.dev/language/built-in-types#strings'),
               dict(title='Dart — String API', url='https://api.dart.dev/stable/dart-core/String-class.html'),
               dict(title='Dart — String Methods', url='https://api.dart.dev/stable/dart-core/String-class.html#instance-methods')]),
    dict(slug='dart-05-control-flow', title='Control Flow',
         desc='if, switch, and loops.',
         dur='50 min', diff='beginner', prereq=['DART-02'],
         objs=['Use if and else conditionals',
               'Match with modern switch expressions',
               'Iterate with for, for-in, and while',
               'Use break, continue, and labels'],
         refs=[dict(title='Dart — Control Flow', url='https://dart.dev/language/control-flow'),
               dict(title='Dart — Switch Statements', url='https://dart.dev/language/branches#switch'),
               dict(title='Dart — Loops', url='https://dart.dev/language/loops')]),
    dict(slug='dart-06-collections', title='Collections',
         desc='Lists, sets, maps, and collection operators.',
         dur='60 min', diff='beginner', prereq=['DART-05'],
         objs=['Build and mutate lists',
               'Store unique values in sets',
               'Map keys to values',
               'Transform with map, where, and fold'],
         refs=[dict(title='Dart — Collections', url='https://dart.dev/language/collections'),
               dict(title='Dart — List API', url='https://api.dart.dev/stable/dart-core/List-class.html'),
               dict(title='Dart — Iterable Operations', url='https://dart.dev/codelabs/iterables')]),
    dict(slug='dart-07-functions', title='Functions',
         desc='Declarations, optional parameters, and lambdas.',
         dur='60 min', diff='beginner', prereq=['DART-05'],
         objs=['Declare functions with return types',
               'Use named and positional optional parameters',
               'Write arrow functions and closures',
               'Use higher-order functions'],
         refs=[dict(title='Dart — Functions', url='https://dart.dev/language/functions'),
               dict(title='Dart — Parameters', url='https://dart.dev/language/functions#parameters'),
               dict(title='Dart — Closures', url='https://dart.dev/language/functions#lexical-scope')]),
    dict(slug='dart-08-classes', title='Classes and Objects',
         desc='Classes, constructors, fields, and methods.',
         dur='75 min', diff='intermediate', prereq=['DART-07'],
         objs=['Define classes with fields and methods',
               'Use initializing and named constructors',
               'Use getters and setters',
               'Understand cascade notation'],
         refs=[dict(title='Dart — Classes', url='https://dart.dev/language/classes'),
               dict(title='Dart — Constructors', url='https://dart.dev/language/constructors'),
               dict(title='Dart — Cascade Notation', url='https://dart.dev/language/classes#cascade-notation')]),
    dict(slug='dart-09-inheritance-interfaces', title='Inheritance and Interfaces',
         desc='extends, implements, mixins, and abstract classes.',
         dur='75 min', diff='intermediate', prereq=['DART-08'],
         objs=['Extend classes and override members',
               'Implement interfaces implicitly',
               'Compose behavior with mixins',
               'Design with abstract classes'],
         refs=[dict(title='Dart — Inheritance', url='https://dart.dev/language/extend'),
               dict(title='Dart — Mixins', url='https://dart.dev/language/mixins'),
               dict(title='Dart — Abstract Classes', url='https://dart.dev/language/classes#abstract-classes')]),
    dict(slug='dart-10-null-safety', title='Null Safety',
         desc='Nullable types, sound null safety, and the ?. operators.',
         dur='50 min', diff='beginner', prereq=['DART-02'],
         objs=['Declare nullable types with ?',
               'Use ?., !!, and ?? operators',
               'Promote types after null checks',
               'Use late for delayed initialization'],
         refs=[dict(title='Dart — Null Safety', url='https://dart.dev/null-safety'),
               dict(title='Dart — Null Safety Tour', url='https://dart.dev/null-safety/understanding-null-safety'),
               dict(title='Dart — Late Variables', url='https://dart.dev/null-safety#late-variables')]),
    dict(slug='dart-11-exceptions', title='Exceptions and Error Handling',
         desc='throw, try-catch, finally, and custom exceptions.',
         dur='60 min', diff='intermediate', prereq=['DART-10'],
         objs=['Throw exceptions with throw',
               'Catch with try-catch and rethrow',
               'Run cleanup with finally',
               'Define custom exception types'],
         refs=[dict(title='Dart — Error Handling', url='https://dart.dev/language/error-handling'),
               dict(title='Dart — Exceptions API', url='https://api.dart.dev/stable/dart-core/Exception-class.html'),
               dict(title='Dart — Error Class', url='https://api.dart.dev/stable/dart-core/Error-class.html')]),
    dict(slug='dart-12-generics', title='Generics',
         desc='Generic functions, classes, and bounds.',
         dur='60 min', diff='intermediate', prereq=['DART-09'],
         objs=['Write generic functions and classes',
               'Constrain type parameters',
               'Use collection literals with generics',
               'Understand reification limits'],
         refs=[dict(title='Dart — Generics', url='https://dart.dev/language/generics'),
               dict(title='Dart — Generic Functions', url='https://dart.dev/language/generics#using-generic-methods'),
               dict(title='Dart — Type Literals', url='https://dart.dev/language/generics#reified-generics')]),
    dict(slug='dart-13-async', title='Asynchronous Programming',
         desc='Future, async, await, and async* generators.',
         dur='75 min', diff='intermediate', prereq=['DART-12'],
         objs=['Create and await Futures',
               'Handle errors in async code',
               'Run tasks concurrently with Future.wait',
               'Yield values with Streams'],
         refs=[dict(title='Dart — Async Programming', url='https://dart.dev/language/async'),
               dict(title='Dart — Future API', url='https://api.dart.dev/stable/dart-async/Future-class.html'),
               dict(title='Dart — Asynchronous Codelab', url='https://dart.dev/codelabs/async-await')]),
    dict(slug='dart-14-file-io', title='File I/O and dart:io',
         desc='Reading and writing files, and environment access.',
         dur='60 min', diff='intermediate', prereq=['DART-11'],
         objs=['Read and write text files',
               'Read lines asynchronously',
               'Work with directories',
               'Access environment variables and args'],
         refs=[dict(title='Dart — dart:io Library', url='https://api.dart.dev/stable/dart-io/dart-io-library.html'),
               dict(title='Dart — File Class', url='https://api.dart.dev/stable/dart-io/File-class.html'),
               dict(title='Dart — Command-Line Apps', url='https://dart.dev/tutorials/server/cmdline')]),
    dict(slug='dart-15-streams', title='Streams and Reactive Data',
         desc='Streams, broadcast streams, and stream operators.',
         dur='75 min', diff='advanced', prereq=['DART-13'],
         objs=['Listen to single-subscription streams',
               'Use broadcast streams for fan-out',
               'Transform with map, where, and fold',
               'Control backpressure'],
         refs=[dict(title='Dart — Streams', url='https://dart.dev/libraries/async/streams'),
               dict(title='Dart — Stream API', url='https://api.dart.dev/stable/dart-async/Stream-class.html'),
               dict(title='Dart — Streams Codelab', url='https://dart.dev/codelabs/async-await')]),
    dict(slug='dart-16-isolates', title='Isolates and Concurrency',
         desc='Isolates, message passing, and parallel execution.',
         dur='75 min', diff='advanced', prereq=['DART-15'],
         objs=['Spawn isolates for parallel work',
               'Send and receive messages',
               'Use Isolate.run for one-off tasks',
               'Share memory patterns safely'],
         refs=[dict(title='Dart — Concurrency', url='https://dart.dev/language/concurrency'),
               dict(title='Dart — Isolate Class', url='https://api.dart.dev/stable/dart-isolate/Isolate-class.html'),
               dict(title='Dart — Isolates Codelab', url='https://dart.dev/codelabs/isolates')]),
    dict(slug='dart-17-testing', title='Testing with Dart',
         desc='Unit tests, matchers, and test organization.',
         dur='60 min', diff='intermediate', prereq=['DART-16'],
         objs=['Write unit tests with the test package',
               'Use matchers for readable assertions',
               'Test async code',
               'Run tests with the Dart CLI'],
         refs=[dict(title='Dart — Testing', url='https://dart.dev/libraries/testing'),
               dict(title='test package — GitHub', url='https://github.com/dart-lang/test'),
               dict(title='Dart — Test API', url='https://pub.dev/documentation/test/latest/')]),
    dict(slug='dart-18-packages', title='Packages and Pub',
         desc='pubspec.yaml, dependencies, and the pub ecosystem.',
         dur='60 min', diff='intermediate', prereq=['DART-01'],
         objs=['Create a package with pubspec.yaml',
               'Add and manage dependencies',
               'Understand version constraints',
               'Publish and consume packages'],
         refs=[dict(title='Dart — Pub', url='https://dart.dev/tools/pub'),
               dict(title='Dart — Packages', url='https://dart.dev/guides/packages'),
               dict(title='pub.dev', url='https://pub.dev/')]),
    dict(slug='dart-19-isolates-advanced', title='Advanced Isolates and Compute',
         desc='Worker pools, message ports, and CPU-bound work.',
         dur='75 min', diff='advanced', prereq=['DART-16'],
         objs=['Build worker pools with SendPort and ReceivePort',
               'Stream results back to the main isolate',
               'Offload CPU-heavy work',
               'Avoid blocking the event loop'],
         refs=[dict(title='Dart — ReceivePort API', url='https://api.dart.dev/stable/dart-isolate/ReceivePort-class.html'),
               dict(title='Dart — SendPort API', url='https://api.dart.dev/stable/dart-isolate/SendPort-class.html'),
               dict(title='Dart — Concurrency Patterns', url='https://dart.dev/language/concurrency#isolates')]),
    dict(slug='dart-20-metaprogramming', title='Annotations and Metaprogramming',
         desc='Annotations, code generation, and build_runner.',
         dur='75 min', diff='advanced', prereq=['DART-18'],
         objs=['Define and use annotations',
               'Set up code generation with build_runner',
               'Use json_serializable for models',
               'Understand source generation limits'],
         refs=[dict(title='Dart — Metadata', url='https://dart.dev/language/metadata'),
               dict(title='build_runner — pub.dev', url='https://pub.dev/packages/build_runner'),
               dict(title='json_serializable — pub.dev', url='https://pub.dev/packages/json_serializable')]),
    dict(slug='dart-21-performance', title='Performance and Best Practices',
         desc='Event loop, allocation, profiling, and idiomatic code.',
         dur='75 min', diff='advanced', prereq=['DART-20'],
         objs=['Understand the event loop model',
               'Minimize allocations in hot paths',
               'Apply idiomatic best practices',
               'Profile with the Dart VM tools'],
         refs=[dict(title='Dart — Event Loop', url='https://dart.dev/articles/archive/event-loop'),
               dict(title='Dart — Performance', url='https://dart.dev/tools/dart-devtools'),
               dict(title='Dart — Effective Dart', url='https://dart.dev/effective-dart')]),
]

CODE = {
    1: [
        '// hello.dart — run: dart run hello.dart\nvoid main() {\n  print("Hello, 100x Systems!");\n  var name = "Dart";\n  print("Welcome to $name!");\n}',
        '// command-line arguments\nvoid main(List<String> args) {\n  print("args: $args");\n  var who = args.isNotEmpty ? args[0] : "world";\n  print("Hello, $who");\n}\n// dart run hello.dart alice -> args: [alice]',
        '// compilation modes\n// JIT: dart run (fast startup, used in dev)\n// AOT: dart compile exe (native, fast runtime)\n// Wasm: dart compile wasm\n// JS: dart compile js\nvoid main() {\n  print("VM ready");\n}',
        '// package layout\n// my_app/\n//   pubspec.yaml\n//   bin/main.dart     -> executable\n//   lib/              -> public library\n//   test/             -> tests\nvoid main() {\n  print("standard layout");\n}',
    ],
    2: [
        '// var vs final vs const\nvoid main() {\n  var score = 42;        // inferred int\n  final name = "Dart";   // set once at runtime\n  const pi = 3.14159;    // compile-time constant\n  // score = "x";        // error: int\n  // name = "Java";      // error: final\n  print("$score $name $pi");\n}',
        '// explicit types\nvoid main() {\n  int count = 10;\n  double ratio = 0.5;\n  String greeting = "hi";\n  bool ok = true;\n  List<int> nums = [1, 2, 3];\n  print("$count $ratio $greeting $ok $nums");\n}',
        '// dynamic and Object\nvoid main() {\n  dynamic anything = 42;\n  anything = "now a string";     // allowed\n  Object obj = 42;\n  // obj = "x";                   // allowed (Object is a supertype)\n  // obj.round();                 // error: Object has no round()\n  print(anything is String);      // true\n  print(obj is int);              // true\n}',
        '// type conversion\nvoid main() {\n  var n = int.parse("42");\n  var d = double.parse("3.14");\n  var s = 42.toString();\n  var b = double.tryParse("x") ?? 0.0;\n  print("$n $d $s $b");\n}',
    ],
    3: [
        '// num, int, double\nvoid main() {\n  int whole = 42;\n  double frac = 3.14;\n  num either = 42;      // num is the supertype\n  either = 3.14;        // still fine\n  print("$whole $frac $either");\n}',
        '// conversions and precision\nvoid main() {\n  var sum = 0.1 + 0.2;            // 0.30000000000000004\n  print(sum);\n  var asInt = sum.toInt();        // 0\n  var rounded = sum.round();      // 0\n  var str = 3.14159.toStringAsFixed(2);  // "3.14"\n  print("$asInt $rounded $str");\n}',
        '// dart:math\nimport \'dart:math\';\nvoid main() {\n  print(sqrt(16));            // 4.0\n  print(pow(2, 10));          // 1024\n  print(max(3, 7));           // 7\n  print(min(3, 7));           // 3\n}',
        '// randomness\nimport \'dart:math\';\nvoid main() {\n  var rng = Random();\n  print(rng.nextInt(6) + 1);        // 1..6\n  print(rng.nextDouble());          // 0..1\n  print(rng.nextBool());\n  var seeded = Random(42);          // reproducible\n  print(seeded.nextInt(100));\n}',
    ],
    4: [
        '// literals and interpolation\nvoid main() {\n  var name = "Alice";\n  var age = 30;\n  var msg = "$name is $age years old";\n  var expr = "double: ${age * 2}";\n  var dollar = "cost: \\$5";        // escaped dollar\n  print(msg);\n  print(expr);\n  print(dollar);\n}',
        '// multi-line and raw strings\nvoid main() {\n  var multiline = """\nLine one\nLine two\n""";\n  var raw = r"C:\\Users\\name";      // raw string\n  print(multiline);\n  print(raw);\n}',
        '// string operations\nvoid main() {\n  var s = "Hello, World";\n  print(s.toUpperCase());\n  print(s.toLowerCase());\n  print(s.startsWith("Hello"));\n  print(s.split(","));\n  print(s.replaceAll("World", "Dart"));\n  print(s.substring(0, 5));\n  print(s.length);\n}',
        '// builders and joins\nvoid main() {\n  var sb = StringBuffer();\n  for (var i = 0; i < 3; i++) {\n    sb.write("line$i; ");\n  }\n  print(sb.toString());\n  print(["a", "b", "c"].join(" | "));\n  print("hello".padLeft(10));\n}',
    ],
    5: [
        '// if and else\nvoid main() {\n  var score = 85;\n  if (score >= 90) {\n    print("A");\n  } else if (score >= 80) {\n    print("B");\n  } else {\n    print("C");\n  }\n  var pass = score >= 50 ? "pass" : "fail";\n  print(pass);\n}',
        '// switch expression (Dart 3)\nvoid main() {\n  var status = 404;\n  var message = switch (status) {\n    200 || 204 => "ok",\n    404 => "not found",\n    500 => "server error",\n    >= 400 && < 500 => "client error",\n    _ => "unknown",\n  };\n  print(message);\n}',
        '// loops\nvoid main() {\n  for (var i = 0; i < 5; i++) { print(i); }\n  var items = ["a", "b", "c"];\n  for (var item in items) { print(item); }\n  var n = 0;\n  while (n < 3) { n++; }\n  print(n);\n}',
        '// break and continue\nvoid main() {\n  for (var i = 1; i <= 10; i++) {\n    if (i % 3 == 0) continue;\n    if (i == 8) break;\n    print(i);\n  }\n  // 1 2 4 5 7\n}',
    ],
    6: [
        '// lists\nvoid main() {\n  var fruits = ["apple", "banana", "cherry"];\n  fruits.add("date");\n  fruits.insert(0, "fig");\n  fruits.removeAt(1);\n  print(fruits);\n  print(fruits[0]);\n  print(fruits.length);\n}',
        '// sets and maps\nvoid main() {\n  var tags = <String>{"dart", "web", "server"};\n  tags.add("flutter");\n  print(tags.contains("dart"));\n  var user = {"name": "Alice", "age": 30};\n  user["admin"] = true;\n  user.remove("age");\n  print(user);\n}',
        '// transform\nvoid main() {\n  var nums = [1, 2, 3, 4, 5];\n  var doubled = nums.map((n) => n * 2).toList();\n  var evens = nums.where((n) => n.isEven).toList();\n  var sum = nums.fold(0, (acc, n) => acc + n);\n  print("$doubled $evens $sum");\n}',
        '// sorting\nvoid main() {\n  var people = [\n    {"name": "Zoe", "age": 30},\n    {"name": "Amy", "age": 25},\n    {"name": "Bo", "age": 40},\n  ];\n  people.sort((a, b) => (a["age"]! as int).compareTo(b["age"]! as int));\n  print(people.map((p) => p["name"]).toList());\n}',
    ],
    7: [
        '// function basics\nString greet(String name, {int times = 1}) {\n  return "Hi $name! " * times;\n}\nvoid main() {\n  print(greet("Alice"));\n  print(greet("Bob", times: 2));\n}',
        '// optional parameters\nvoid show({String? title, List<String> tags = const []}) {\n  print("title: ${title ?? "untitled"}");\n  print("tags: $tags");\n}\nvoid main() {\n  show(tags: ["a", "b"]);\n  show();\n}',
        '// arrow functions and closures\nvoid main() {\n  int square(int n) => n * n;\n  var counter = 0;\n  int increment() => ++counter;   // closure over counter\n  print(square(9));               // 81\n  print(increment());             // 1\n  print(increment());             // 2\n}',
        '// higher-order functions\nvoid main() {\n  var names = ["Zoe", "Amy"];\n  var upper = names.map((n) => n.toUpperCase()).toList();\n  print(upper);\n  var evens = [1, 2, 3, 4].where((n) => n.isEven).toList();\n  print(evens);\n  var total = [1, 2, 3].reduce((a, b) => a + b);\n  print(total);\n}',
    ],
    8: [
        '// class basics\nclass Product {\n  final String name;\n  final double price;\n  int stock;\n  Product(this.name, this.price, {this.stock = 0});\n  String summary() => "$name — \\$$price (stock: $stock)";\n}\nvoid main() {\n  var p = Product("Keyboard", 49.99, stock: 12);\n  print(p.summary());\n}',
        '// named and factory constructors\nclass Point {\n  final double x, y;\n  Point(this.x, this.y);\n  Point.origin() : x = 0, y = 0;\n  factory Point.fromList(List<double> v) => Point(v[0], v[1]);\n}\nvoid main() {\n  print(Point.origin().x);\n  print(Point.fromList([1, 2]).y);\n}',
        '// getters and setters\nclass Thermostat {\n  double _celsius = 20;\n  double get fahrenheit => _celsius * 9 / 5 + 32;\n  set fahrenheit(double f) => _celsius = (f - 32) * 5 / 9;\n}\nvoid main() {\n  var t = Thermostat();\n  print(t.fahrenheit);  // 68.0\n  t.fahrenheit = 77;\n  print(t.fahrenheit);  // 77.0\n}',
        '// cascade notation\nvoid main() {\n  var sb = StringBuffer()\n    ..write("Hello ")\n    ..write("Dart!")..write(" ");\n  var list = <int>[]\n    ..add(1)\n    ..add(2)\n    ..add(3);\n  print(sb.toString());\n  print(list);\n}',
    ],
    9: [
        '// inheritance\nclass Animal {\n  final String name;\n  Animal(this.name);\n  String speak() => "...";\n}\nclass Dog extends Animal {\n  Dog(String name) : super(name);\n  @override\n  String speak() => "Woof!";\n}\nvoid main() {\n  print(Dog("Rex").speak());\n}',
        '// abstract classes + interfaces\nabstract class Shape {\n  double area();\n  String describe() => "area = ${area()}";\n}\nclass Circle extends Shape {\n  final double r;\n  Circle(this.r);\n  @override\n  double area() => 3.14159 * r * r;\n}\nvoid main() {\n  print(Circle(2).describe());\n}',
        '// mixins\nmixin Timestampable {\n  DateTime? createdAt;\n  void touch() => createdAt = DateTime.now();\n}\nclass Post with Timestampable {\n  final String title;\n  Post(this.title);\n}\nvoid main() {\n  var post = Post("Hello");\n  post.touch();\n  print(post.createdAt != null);\n}',
        '// sealed classes (Dart 3)\nsealed class HttpResult {}\nclass Ok extends HttpResult {\n  final String body;\n  Ok(this.body);\n}\nclass Err extends HttpResult {\n  final int code;\n  Err(this.code);\n}\nString describe(HttpResult r) => switch (r) {\n  Ok(:var body) => "ok: $body",\n  Err(:var code) => "err: $code",\n};\nvoid main() {\n  print(describe(Ok("data")));\n}',
    ],
    10: [
        '// nullable basics\nvoid main() {\n  String? maybe = "hello";\n  print(maybe);\n  maybe = null;\n  print(maybe?.length);   // null\n  print(maybe ?? "empty"); // "empty"\n}',
        '// safe call chains\nclass Address {\n  final String city;\n  Address(this.city);\n}\nclass Person {\n  final Address? address;\n  Person(this.address);\n}\nvoid main() {\n  var p = Person(Address("Paris"));\n  print(p.address?.city);              // Paris\n  var none = Person(null);\n  print(none.address?.city ?? "unknown");  // unknown\n}',
        '// promotion and !!\nvoid main() {\n  String? raw = "42";\n  if (raw != null) {\n    print(raw.length);    // promoted to String\n  }\n  var n = raw!.length;   // force unwrap\n  print(n);\n  raw = null;\n  // print(raw.length);   // error: String? has no length\n  print(raw ?? "null");\n}',
        '// late variables\nvoid main() {\n  late String heavy;\n  // heavy not yet initialized\n  heavy = "computed later";\n  print(heavy);\n  late final int cached = _expensive();\n  print(cached);  // computed once\n  print(cached);  // cached\n}\nint _expensive() {\n  print("computing...");\n  return 42;\n}',
    ],
    11: [
        '// try-catch\nvoid main() {\n  try {\n    var n = int.parse("abc");\n    print(n);\n  } on FormatException catch (e) {\n    print("bad number: $e");\n  }\n}',
        '// catch all + finally\nvoid main() {\n  try {\n    throw StateError("boom");\n  } catch (e, st) {\n    print("caught: $e");\n    print("stack: ${st.toString().split("\\n").first}");\n  } finally {\n    print("cleanup");\n  }\n}',
        '// custom exceptions + rethrow\nclass PaymentFailed implements Exception {\n  final String message;\n  PaymentFailed(this.message);\n  @override\n  String toString() => "PaymentFailed: $message";\n}\nvoid charge(double amount) {\n  if (amount > 100) throw PaymentFailed("limit exceeded");\n}\nvoid main() {\n  try {\n    charge(500);\n  } on PaymentFailed catch (e) {\n    print(e);\n  }\n}',
        '// run-time errors\nvoid main() {\n  try {\n    var list = <int>[];\n    print(list.first);\n  } on RangeError catch (e) {\n    print("range: $e");\n  } on StateError catch (e) {\n    print("state: $e");\n  }\n}',
    ],
    12: [
        '// generic functions\nT identity<T>(T value) => value;\nvoid main() {\n  print(identity(42));\n  print(identity("text"));\n  print(identity<List<int>>([1, 2]));\n}',
        '// generic classes\nclass Stack<T> {\n  final List<T> _items = [];\n  void push(T item) => _items.add(item);\n  T? pop() => _items.isEmpty ? null : _items.removeLast();\n  int get size => _items.length;\n}\nvoid main() {\n  var s = Stack<int>();\n  s.push(1);\n  s.push(2);\n  print(s.pop());\n  print(s.size);\n}',
        '// bounds\nT maxOf2<T extends Comparable<T>>(T a, T b) => a.compareTo(b) > 0 ? a : b;\nvoid main() {\n  print(maxOf2(3, 7));\n  print(maxOf2("cat", "dog"));\n}\n// note: int implements Comparable<num>, so T infers to num here —\n// returns num, not int (fine for comparisons)',
        '// generic with collections\nvoid main() {\n  var nums = <int>[1, 2, 3];\n  var labels = <String, int>{"a": 1};\n  T? firstOrNull<T>(List<T> items) => items.isEmpty ? null : items.first;\n  print(firstOrNull(nums));\n  print(firstOrNull(<int>[]));\n  print(labels);\n}',
    ],
    13: [
        '// Future + async/await\nFuture<String> fetchUser() async {\n  await Future.delayed(Duration(milliseconds: 100));\n  return "Alice";\n}\nFuture<void> main() async {\n  var user = await fetchUser();\n  print("user: $user");\n}',
        '// async error handling\nFuture<int> parse(String raw) async {\n  if (raw.isEmpty) throw FormatException("empty");\n  return int.parse(raw);\n}\nFuture<void> main() async {\n  try {\n    print(await parse("42"));\n  } on FormatException catch (e) {\n    print("err: $e");\n  }\n}',
        '// Future.wait\nFuture<int> fetch(int id) async {\n  await Future.delayed(Duration(milliseconds: 10));\n  return id * id;\n}\nFuture<void> main() async {\n  var results = await Future.wait([fetch(3), fetch(4)]);\n  print(results);         // [9, 16]\n  print(results.fold(0, (a, b) => a + b));  // 25\n}',
        '// async* generator\nStream<int> countdown(int from) async* {\n  for (var i = from; i > 0; i--) {\n    yield i;\n    await Future.delayed(Duration(milliseconds: 10));\n  }\n}\nFuture<void> main() async {\n  await for (var n in countdown(3)) {\n    print(n);   // 3 2 1\n  }\n}',
    ],
    14: [
        '// write and read text\nimport \'dart:io\';\nvoid main() {\n  var file = File("data.txt");\n  file.writeAsStringSync("line one\\nline two\\n");\n  var text = file.readAsStringSync();\n  var lines = file.readAsLinesSync();\n  print(text);\n  print(lines);\n}',
        '// async file I/O\nimport \'dart:io\';\nFuture<void> main() async {\n  var file = File("data.txt");\n  await file.writeAsString("async write\\n");\n  var lines = await file.readAsLines();\n  print(lines);\n  await file.delete();\n}',
        '// directories\nimport \'dart:io\';\nvoid main() {\n  var dir = Directory(".");\n  var entries = dir.listSync(recursive: false);\n  for (var e in entries.take(3)) {\n    print(e.path);\n  }\n  print("cwd: ${Directory.current.path}");\n}',
        '// env + args\nimport \'dart:io\';\nvoid main(List<String> args) {\n  print("args: $args");\n  print("HOME: ${Platform.environment["HOME"] ?? "unknown"}");\n  print("OS: ${Platform.operatingSystem}");\n}',
    ],
    15: [
        '// single-subscription stream\nimport \'dart:async\';\nFuture<void> main() async {\n  var stream = Stream.fromIterable([1, 2, 3]);\n  await for (var n in stream) {\n    print(n);\n  }\n}',
        '// broadcast stream\nimport \'dart:async\';\nFuture<void> main() async {\n  var controller = StreamController<int>.broadcast();\n  controller.stream.listen((n) => print("a: $n"));\n  controller.stream.listen((n) => print("b: $n"));\n  controller.add(1);\n  controller.add(2);\n  await controller.close();\n}',
        '// stream operators\nimport \'dart:async\';\nFuture<void> main() async {\n  var squares = Stream.fromIterable([1, 2, 3, 4])\n      .map((n) => n * n)\n      .where((n) => n.isEven);\n  await for (var n in squares) {\n    print(n);  // 4 16\n  }\n}',
        '// stream from future and manual control\nimport \'dart:async\';\nFuture<void> main() async {\n  var fromFuture = Stream.fromFuture(Future.value("done"));\n  await for (var v in fromFuture) {\n    print(v);\n  }\n  var periodic = Stream.periodic(\n    const Duration(milliseconds: 10),\n    (i) => i * i,\n  ).take(3);\n  await for (var n in periodic) {\n    print(n);  // 0 1 4\n  }\n}',
    ],
    16: [
        '// Isolate.run (one-off work)\nimport \'dart:isolate\';\nFuture<void> main() async {\n  var result = await Isolate.run(() {\n    var sum = 0;\n    for (var i = 1; i <= 1000000; i++) {\n      sum += i;\n    }\n    return sum;\n  });\n  print(result);  // runs on another isolate\n}',
        '// spawn with SendPort\nimport \'dart:isolate\';\nvoid worker(SendPort port) {\n  port.send("hello from isolate");\n}\nFuture<void> main() async {\n  var receive = ReceivePort();\n  await Isolate.spawn(worker, receive.sendPort);\n  var msg = await receive.first;\n  print(msg);\n  receive.close();\n}',
        '// two-way messaging\nimport \'dart:isolate\';\nvoid worker(SendPort replyTo) {\n  var receive = ReceivePort();\n  replyTo.send(receive.sendPort);   // hand back our port\n  receive.listen((msg) {\n    replyTo.send("echo: $msg");\n  });\n}\nFuture<void> main() async {\n  var control = ReceivePort();\n  await Isolate.spawn(worker, control.sendPort);\n  var workerPort = await control.first as SendPort;\n  workerPort.send("ping");\n  print(await control.first);   // echo: ping\n  control.close();\n}',
        '// event loop note\nvoid main() {\n  print("1: sync");\n  Future(() => print("2: event"));\n  Future.microtask(() => print("3: microtask first"));\n  scheduleMicrotask(() => print("4: microtask"));\n  print("5: sync end");\n}\n// order: 1, 5, 3, 4, 2 (microtasks FIFO, then events)',
    ],
    17: [
        '// unit test basics\nimport \'package:test/test.dart\';\nvoid main() {\n  test("addition works", () {\n    expect(2 + 2, equals(4));\n  });\n}',
        '// matchers\nimport \'package:test/test.dart\';\nvoid main() {\n  test("matchers", () {\n    expect("hello", contains("ell"));\n    expect([1, 2, 3], hasLength(3));\n    expect(3.14, closeTo(3.1, 0.1));\n    expect(() => throw StateError("x"), throwsStateError);\n  });\n}',
        '// async tests\nimport \'package:test/test.dart\';\nFuture<String> fetch() async => "data";\nvoid main() {\n  test("async result", () async {\n    expect(await fetch(), "data");\n  });\n}',
        '// groups\nimport \'package:test/test.dart\';\nvoid main() {\n  group("Calculator", () {\n    test("adds", () {\n      expect(2 + 2, 4);\n    });\n    test("multiplies", () {\n      expect(3 * 3, 9);\n    });\n  });\n}\n// run: dart test',
    ],
    18: [
        '// pubspec.yaml\n// name: my_app\n// description: A sample Dart app\n// environment:\n//   sdk: ^3.4.0\n// dependencies:\n//   http: ^1.2.0\nvoid main() {\n  print("pubspec ready");\n}',
        '// adding dependencies\n// dart pub add http\n// dart pub add dev:test\n// dart pub upgrade\n// dart pub get (after editing pubspec)\nvoid main() {\n  print("dependency workflow");\n}',
        '// version constraints\n// ^1.2.0    -> >=1.2.0 <2.0.0 (caret)\n// >=1.0.0 <2.0.0  -> explicit range\n// 1.2.3     -> exact\n// any       -> avoid in production\n// pubspec.lock pins resolved versions\nvoid main() {\n  print("semver constraints");\n}',
        '// consuming a package\n// import \'package:http/http.dart\' as http;  // used in the commented call below\nFuture<void> main() async {\n  // var res = await http.get(Uri.parse("https://example.com"));\n  // print(res.statusCode);\n  print("http package ready");\n}',
    ],
    19: [
        '// worker pool pattern\nimport \'dart:isolate\';\nFuture<int> computeSum(int n) async {\n  return Isolate.run(() {\n    var sum = 0;\n    for (var i = 1; i <= n; i++) {\n      sum += i;\n    }\n    return sum;\n  });\n}\nFuture<void> main() async {\n  var results = await Future.wait([computeSum(100), computeSum(200)]);\n  print(results);  // both offloaded\n}',
        '// streaming results\nimport \'dart:isolate\';\nvoid produce(SendPort port) async {\n  for (var i = 1; i <= 5; i++) {\n    await Future.delayed(const Duration(milliseconds: 10));\n    port.send(i * i);\n  }\n}\nFuture<void> main() async {\n  var receive = ReceivePort();\n  await Isolate.spawn(produce, receive.sendPort);\n  await for (var v in receive.take(5)) {\n    print(v);\n  }\n  receive.close();\n}',
        '// CPU-bound offload\nimport \'dart:isolate\';\nFuture<void> main() async {\n  var before = DateTime.now();\n  var heavy = await Isolate.run(() {\n    var primes = <int>[];\n    for (var n = 2; primes.length < 5000; n++) {\n      var isPrime = true;\n      for (var d = 2; d * d <= n; d++) {\n        if (n % d == 0) {\n          isPrime = false;\n          break;\n        }\n      }\n      if (isPrime) primes.add(n);\n    }\n    return primes.last;\n  });\n  print("last prime: $heavy");\n  print("took: ${DateTime.now().difference(before)}");\n}',
        '// never block the event loop\nimport \'dart:io\';\nvoid main() {\n  // File.readAsStringSync() blocks — prefer async in servers\n  // Future.forEach + async reads keep the loop responsive\n  print("sync vs async I/O");\n}',
    ],
    20: [
        '// annotations\nclass Immutable {\n  const Immutable();\n}\n@Immutable()\nclass Point {\n  final int x, y;\n  const Point(this.x, this.y);\n}\nvoid main() {\n  print(Point(1, 2));\n}',
        '// build_runner setup\n// pubspec.yaml:\n// dependencies:\n//   json_annotation: ^4.9.0\n// dev_dependencies:\n//   build_runner: ^2.4.0\n//   json_serializable: ^6.8.0\nvoid main() {\n  print("codegen setup ready");\n}',
        '// json_serializable model\nimport \'package:json_annotation/json_annotation.dart\';\npart \'user.g.dart\';\n@JsonSerializable()\nclass User {\n  final String name;\n  final int age;\n  User({required this.name, required this.age});\n  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);\n  Map<String, dynamic> toJson() => _$UserToJson(this);\n}',
        '// generating\n// terminal:\n//   dart run build_runner build\n// generates user.g.dart with the serialization code\n// then: User.fromJson({"name": "Alice", "age": 30})\nvoid main() {\n  print("run: dart run build_runner build");\n}',
    ],
    21: [
        '// event loop model\nimport \'dart:async\';\nvoid main() {\n  print("start");\n  Future.delayed(Duration.zero, () => print("event"));\n  scheduleMicrotask(() => print("microtask"));\n  print("end");\n}\n// start, end, microtask, event',
        '// avoid allocations in hot paths\nvoid main() {\n  // reuse buffers in loops\n  var sb = StringBuffer();\n  for (var i = 0; i < 1000; i++) {\n    sb..write(i)..write(", ");\n  }\n  print(sb.length);\n  // prefer growable=false when size is known\n  var list = List<int>.filled(3, 0, growable: false);\n  print(list);\n}',
        '// idiomatic code\nvoid main() {\n  var nums = [1, 2, 3, 4];\n  // cascade + spread + collection if\n  var result = [\n    ...nums.where((n) => n.isEven),\n    if (nums.length > 2) 99,\n  ];\n  print(result);  // [2, 4, 99]\n  // null-aware operators\n  String? name;\n  var shown = name?.toUpperCase() ?? "anonymous";\n  print(shown);\n}',
        '// profiling\n// dart run --observe bin/app.dart\n// opens VM Service for CPU + memory profiling\n// dart devtools          -> DevTools UI\n// dart run --profile     -> AOT-ish profiling mode\nvoid main() {\n  print("devtools: dart devtools");\n}',
    ],
}


if __name__ == '__main__':
    run_gen(LANGUAGE, 'dart', LESSONS, CODE, BASE)
