#!/usr/bin/env python3
"""Generate the 21-lesson Swift deep curriculum for the 100xsystems registry.

Uses the shared gen_lib.py template. Produces:
  - static-data/knowledge/languages/swift/swift-*.md (21 lesson files)
  - updated index.json lessons array (categories preserved)
  - removes stale skeleton files
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_lib import main as run_gen  # noqa: E402

LANGUAGE = 'swift'
BASE = 'static-data/knowledge/languages/swift'

LESSONS = [
    dict(slug='swift-01-getting-started', title='Getting Started with Swift',
         desc='Install Swift, run scripts, and understand the SwiftPM workflow.',
         dur='45 min', diff='beginner', prereq=[],
         objs=['Install Swift and run your first script',
               'Use print and string interpolation',
               'Work with CommandLine arguments',
               'Understand the SwiftPM project layout'],
         refs=[dict(title='Swift.org — Getting Started', url='https://www.swift.org/getting-started/'),
               dict(title='Swift Book — A Swift Tour', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/guidedtour/'),
               dict(title='Swift Package Manager', url='https://www.swift.org/package-manager/')]),
    dict(slug='swift-02-variables-types', title='Variables and Data Types',
         desc='Constants, variables, type inference, and the core value types.',
         dur='60 min', diff='beginner', prereq=['SWIFT-01'],
         objs=['Declare variables with var and constants with let',
               'Let the compiler infer types',
               'Work with Int, Double, String, Bool, and Character',
               'Convert between types safely'],
         refs=[dict(title='Swift Book — The Basics', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/'),
               dict(title='Swift Book — Basic Operators', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/basicoperators/'),
               dict(title='Apple — Swift Data Types', url='https://developer.apple.com/documentation/swift/data-types')]),
    dict(slug='swift-03-numbers-math', title='Numbers and Math',
         desc='Integer types, floating point, overflow behavior, and math.',
         dur='50 min', diff='beginner', prereq=['SWIFT-02'],
         objs=['Use Int, Int32, Int64, and UInt appropriately',
               'Handle Double vs Float precision',
               'Use overflow operators deliberately',
               'Leverage the Foundation math functions'],
         refs=[dict(title='Swift Book — Integers', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/#Integer-Bounds'),
               dict(title='Swift Book — Numeric Literals', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/#Numeric-Literals'),
               dict(title='Apple — Double', url='https://developer.apple.com/documentation/swift/double')]),
    dict(slug='swift-04-strings', title='Strings and String Manipulation',
         desc='String literals, interpolation, Unicode, and the string API.',
         dur='60 min', diff='beginner', prereq=['SWIFT-02'],
         objs=['Build strings with literals and interpolation',
               'Understand String as a collection of Characters',
               'Manipulate strings with the standard API',
               'Handle Unicode and substrings safely'],
         refs=[dict(title='Swift Book — Strings and Characters', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/stringsandcharacters/'),
               dict(title='Apple — String', url='https://developer.apple.com/documentation/swift/string'),
               dict(title='Swift Book — Substrings', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/stringsandcharacters/#Substrings')]),
    dict(slug='swift-05-control-flow', title='Control Flow',
         desc='Conditionals, switch, and loops.',
         dur='50 min', diff='beginner', prereq=['SWIFT-02'],
         objs=['Use if/else and ternary conditions',
               'Write exhaustive switch statements',
               'Iterate with for-in, while, and repeat-while',
               'Use break, continue, and labeled statements'],
         refs=[dict(title='Swift Book — Control Flow', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/'),
               dict(title='Swift Book — Switch', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/#Switch'),
               dict(title='Swift Book — For-In Loops', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/#For-In-Loops')]),
    dict(slug='swift-06-collections', title='Collections: Array, Dictionary, Set',
         desc='The three collection types and their algorithms.',
         dur='60 min', diff='beginner', prereq=['SWIFT-05'],
         objs=['Build and mutate arrays',
               'Look up and store data in dictionaries',
               'Use sets for membership and uniqueness',
               'Apply map, filter, and reduce'],
         refs=[dict(title='Swift Book — Collection Types', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/collectiontypes/'),
               dict(title='Apple — Array', url='https://developer.apple.com/documentation/swift/array'),
               dict(title='Swift Book — Higher-Order Functions', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/collectiontypes/#Iterating-Over-a-Dictionary')]),
    dict(slug='swift-07-functions-closures', title='Functions and Closures',
         desc='Function declarations, labels, and closure capture.',
         dur='60 min', diff='beginner', prereq=['SWIFT-05'],
         objs=['Define functions with labels and defaults',
               'Pass functions as values',
               'Write closures and capture context',
               'Use trailing closure syntax'],
         refs=[dict(title='Swift Book — Functions', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/functions/'),
               dict(title='Swift Book — Closures', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/closures/'),
               dict(title='Swift Book — Capture Lists', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/closures/#Capturing-Values')]),
    dict(slug='swift-08-structs', title='Structs and Value Semantics',
         desc='Structures, properties, methods, and copy-on-write behavior.',
         dur='60 min', diff='intermediate', prereq=['SWIFT-07'],
         objs=['Define structs with stored and computed properties',
               'Use memberwise initializers',
               'Mutate values with mutating methods',
               'Reason about value semantics and COW'],
         refs=[dict(title='Swift Book — Structures and Classes', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/structuresandclasses/'),
               dict(title='Swift Book — Properties', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/properties/'),
               dict(title='Swift Book — Methods', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/methods/')]),
    dict(slug='swift-09-classes', title='Classes and Reference Semantics',
         desc='Classes, inheritance, and reference behavior.',
         dur='60 min', diff='intermediate', prereq=['SWIFT-08'],
         objs=['Define classes with properties and methods',
               'Understand reference semantics',
               'Override methods and use super',
               'Use access control with private and internal'],
         refs=[dict(title='Swift Book — Classes', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/structuresandclasses/#Classes-Are-Reference-Types'),
               dict(title='Swift Book — Inheritance', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/inheritance/'),
               dict(title='Swift Book — Access Control', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/accesscontrol/')]),
    dict(slug='swift-10-enums-patterns', title='Enums and Pattern Matching',
         desc='Enumerations with associated values and pattern matching.',
         dur='75 min', diff='intermediate', prereq=['SWIFT-06'],
         objs=['Define enums with raw and associated values',
               'Match with switch and if case',
               'Use Optionals through pattern matching',
               'Write recursive enums'],
         refs=[dict(title='Swift Book — Enumerations', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/enumerations/'),
               dict(title='Swift Book — Patterns', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/patterns/'),
               dict(title='Swift Book — Optional Binding', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/#Optional-Binding')]),
    dict(slug='swift-11-protocols-extensions', title='Protocols and Extensions',
         desc='Protocols, conformances, and extension-driven design.',
         dur='75 min', diff='intermediate', prereq=['SWIFT-09'],
         objs=['Define and conform to protocols',
               'Compose requirements with protocol inheritance',
               'Extend types with protocols and methods',
               'Provide default implementations'],
         refs=[dict(title='Swift Book — Protocols', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/protocols/'),
               dict(title='Swift Book — Extensions', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/extensions/'),
               dict(title='Swift Book — Protocol-Oriented Programming', url='https://developer.apple.com/videos/play/wwdc2015/408/')]),
    dict(slug='swift-12-optionals', title='Optionals and Optional Chaining',
         desc='Optional values, binding, chaining, and nil coalescing.',
         dur='50 min', diff='beginner', prereq=['SWIFT-05'],
         objs=['Wrap and unwrap optional values',
               'Use if-let and guard-let binding',
               'Chain optionals safely',
               'Apply nil coalescing and force unwrapping responsibly'],
         refs=[dict(title='Swift Book — Optionals', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/thebasics/#Optionals'),
               dict(title='Swift Book — Optional Chaining', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/optionalchaining/'),
               dict(title='Swift Book — Error Handling with Optionals', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling/#Converting-Errors-to-Optional-Values')]),
    dict(slug='swift-13-error-handling', title='Error Handling',
         desc='Throwing functions, do-catch, and error propagation.',
         dur='60 min', diff='intermediate', prereq=['SWIFT-12'],
         objs=['Define error types conforming to Error',
               'Throw and catch errors',
               'Propagate errors with try',
               'Clean up with defer'],
         refs=[dict(title='Swift Book — Error Handling', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling/'),
               dict(title='Apple — Error Protocol', url='https://developer.apple.com/documentation/swift/error'),
               dict(title='Swift Book — Defer', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling/#Specifying-Cleanup-Actions')]),
    dict(slug='swift-14-generics', title='Generics',
         desc='Generic functions, types, and constraints.',
         dur='75 min', diff='advanced', prereq=['SWIFT-11'],
         objs=['Write generic functions',
               'Design generic types',
               'Constrain with protocol requirements',
               'Use associated types and where clauses'],
         refs=[dict(title='Swift Book — Generics', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/generics/'),
               dict(title='Swift Book — Associated Types', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/generics/#Associated-Types'),
               dict(title='Swift Book — Where Clauses', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/generics/#Generic-Where-Clauses')]),
    dict(slug='swift-15-concurrency', title='Concurrency: async/await',
         desc='Async functions, tasks, and structured concurrency.',
         dur='75 min', diff='advanced', prereq=['SWIFT-14'],
         objs=['Mark functions async and await results',
               'Run work in parallel with async-let',
               'Group tasks with TaskGroup',
               'Understand the MainActor context'],
         refs=[dict(title='Swift Book — Concurrency', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/'),
               dict(title='Apple — Task', url='https://developer.apple.com/documentation/swift/task'),
               dict(title='Swift Book — Structured Concurrency', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/#Structured-Concurrency')]),
    dict(slug='swift-16-actors-sendable', title='Actors and Sendable',
         desc='Actor isolation, Sendable, and safe shared state.',
         dur='75 min', diff='advanced', prereq=['SWIFT-15'],
         objs=['Isolate mutable state with actors',
               'Call actor methods with await',
               'Annotate types with Sendable',
               'Avoid data races by design'],
         refs=[dict(title='Swift Book — Actors', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/#Actors'),
               dict(title='Apple — Sendable', url='https://developer.apple.com/documentation/swift/sendable'),
               dict(title='Swift Book — Sendable Conformance', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/concurrency/#Sendable')]),
    dict(slug='swift-17-arc-memory', title='Memory Management and ARC',
         desc='Automatic Reference Counting, strong cycles, and weak references.',
         dur='60 min', diff='advanced', prereq=['SWIFT-09'],
         objs=['Understand how ARC manages class instances',
               'Break strong reference cycles with weak',
               'Use unowned references carefully',
               'Avoid closure capture cycles'],
         refs=[dict(title='Swift Book — Automatic Reference Counting', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/'),
               dict(title='Swift Book — Resolving Cycles', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/automaticreferencecounting/#Resolving-Strong-Reference-Cycles-Between-Class-Instances'),
               dict(title='Apple — Memory Safety', url='https://developer.apple.com/documentation/swift/memory-safety')]),
    dict(slug='swift-18-codable-files', title='Codable and File I/O',
         desc='Codable, JSON encoding/decoding, and the file system.',
         dur='60 min', diff='intermediate', prereq=['SWIFT-12'],
         objs=['Conform types to Codable',
               'Encode and decode JSON',
               'Read and write files with FileManager',
               'Handle dates and custom keys'],
         refs=[dict(title='Apple — Codable', url='https://developer.apple.com/documentation/swift/codable'),
               dict(title='Apple — JSONEncoder', url='https://developer.apple.com/documentation/foundation/jsonencoder'),
               dict(title='Apple — FileManager', url='https://developer.apple.com/documentation/foundation/filemanager')]),
    dict(slug='swift-19-package-manager', title='Swift Package Manager',
         desc='Package.swift, dependencies, and building libraries.',
         dur='60 min', diff='intermediate', prereq=['SWIFT-01'],
         objs=['Declare packages and products',
               'Add and resolve dependencies',
               'Build executables and libraries',
               'Share packages with the ecosystem'],
         refs=[dict(title='Swift Package Manager — Getting Started', url='https://www.swift.org/getting-started/package-manager/'),
               dict(title='Swift Package Manager — PackageDescription', url='https://docs.swift.org/package-manager/PackageDescription/index.html'),
               dict(title='Swift Package Index', url='https://swiftpackageindex.com/')]),
    dict(slug='swift-20-testing', title='Testing with XCTest and Swift Testing',
         desc='Unit tests, assertions, and test organization.',
         dur='60 min', diff='intermediate', prereq=['SWIFT-19'],
         objs=['Write XCTest test classes',
               'Use Swift Testing macros',
               'Structure tests with setup and teardown',
               'Run tests from the command line'],
         refs=[dict(title='Apple — XCTest', url='https://developer.apple.com/documentation/xctest'),
               dict(title='Swift Testing — Documentation', url='https://developer.apple.com/documentation/testing'),
               dict(title='Swift Package Manager — Testing', url='https://www.swift.org/getting-started/testing/')]),
    dict(slug='swift-21-performance', title='Performance and Optimization',
         desc='Value semantics, COW, profiling, and measurement.',
         dur='75 min', diff='advanced', prereq=['SWIFT-17'],
         objs=['Optimize value type copying with COW',
               'Use lazy properties and caching',
               'Measure with continuous benchmarks',
               'Profile with Instruments'],
         refs=[dict(title='Apple — Swift Performance WWDC', url='https://developer.apple.com/videos/play/wwdc2016/416/'),
               dict(title='Swift Book — Lazy Stored Properties', url='https://docs.swift.org/swift-book/documentation/the-swift-programming-language/properties/#Lazy-Stored-Properties'),
               dict(title='Apple — Continuous Benchmarking', url='https://developer.apple.com/documentation/xcode/improving-your-app-s-performance')]),
]

CODE = {
    1: [
        '// hello.swift — run with: swift hello.swift\nprint("Hello, 100x Systems!")\nlet name = "Swift"\nprint("Welcome to \\(name)!")',
        '// CommandLine arguments\nfor arg in CommandLine.arguments {\n    print("arg: \\(arg)")\n}\n// swift hello.swift alice bob -> prints script path + args',
        'import Foundation\nlet info = ProcessInfo.processInfo\nprint("OS: \\(info.operatingSystemVersionString)")\nprint("PID: \\(info.processIdentifier)")\nlet env = info.environment\nprint("HOME: \\(env["HOME"] ?? "unknown")")',
        '// SwiftPM layout\n// Package.swift at root:\n//   swift build   -> .build/debug/\n//   swift run     -> run the executable\n//   swift test    -> run tests\n// Sources/MyLib/ and Tests/MyLibTests/ mirror each other.',
    ],
    2: [
        '// var vs let\nvar score = 42          // inferred Int\nlet maxScore = 100      // constant\nscore += 1\n// maxScore = 101       // error: cannot assign to let\nprint(score, maxScore)',
        '// type inference\nlet count = 10                 // Int\nlet pi = 3.14                  // Double\nlet greeting = "hi"            // String\nlet ok = true                  // Bool\nlet ch: Character = "A"        // explicit annotation\nprint(type(of: count), type(of: pi))',
        '// explicit types and conversion\nlet a: Int = 5\nlet b: Double = 2.5\nlet sum = Double(a) + b        // 7.5\nlet text = String(sum)         // "7.5"\nlet rounded = Int(b)           // 2 (truncates)\nprint(sum, text, rounded)',
        '// type safety — no implicit conversions\nvar x = 3\nvar y = 0.14\n// let z = x + y   // error: Binary operator + cannot be applied\nlet z = Double(x) + y\nprint(z)  // 3.14',
    ],
    3: [
        '// integer types\nlet small: Int8 = 127        // -128...127\nlet big: Int64 = 9_223_372_036_854_775_807\nlet unsigned: UInt = 42\nprint(Int8.min, Int8.max, Int64.max)\nprint(big)',
        '// floating point\nlet d: Double = 0.1 + 0.2     // 0.30000000000000004\nprint(d)\nlet f: Float = 0.1 + 0.2\nprint(f)\n// compare with tolerance\nprint(abs(d - 0.3) < 1e-9 ? "close" : "not close")',
        '// overflow operators\nvar max = Int8.max           // 127\n// max += 1                   // traps: arithmetic overflow\nlet wrapped = Int8.max &+ 1  // -128 (deliberate)\nprint(wrapped)',
        'import Foundation\nlet r = sqrt(16.0)              // 4.0\nlet p = pow(2.0, 10.0)          // 1024.0\nlet rnd = Int.random(in: 1...6) // inclusive range\nprint(r, p, rnd)',
    ],
    4: [
        '// string literals and interpolation\nlet name = "Alice"\nlet age = 30\nlet msg = "\\(name) is \\(age) years old"\nlet multiline = """\nLine one\nLine two\n"""\nprint(msg, multiline)',
        '// strings are collections of Characters\nlet s = "héllo"\nprint(s.count)          // 5 (graphemes, not bytes)\nfor ch in s { print(ch, terminator: " ") }\nprint()',
        '// common operations\nvar s = "Hello, World"\nprint(s.uppercased())          // HELLO, WORLD\nprint(s.lowercased())\nprint(s.hasPrefix("Hello"))    // true\nprint(s.split(separator: ",")) // ["Hello", " World"]\nprint(s.replacingOccurrences(of: "World", with: "Swift"))',
        '// substrings share storage\nlet full = "The quick brown fox"\nlet first = full.prefix(3)      // Substring "The"\nlet word = String(first)        // convert to String to keep\nprint(word, full.count, first.count)',
    ],
    5: [
        '// if / else if / else\nlet score = 85\nif score >= 90 {\n    print("A")\n} else if score >= 80 {\n    print("B")\n} else {\n    print("C")\n}\nlet pass = score >= 50 ? "pass" : "fail"\nprint(pass)',
        '// switch must be exhaustive\nlet status = 404\nswitch status {\ncase 200, 204: print("ok")\ncase 404:      print("not found")\ncase 500:      print("server error")\ncase let code where code >= 400:\n    print("client error \\(code)")\ndefault:        print("unknown")\n}',
        '// loops\nfor i in 0..<5 { print(i, terminator: "") }\nprint()\nvar n = 0\nwhile n < 3 { n += 1 }\nprint(n)\nrepeat {\n    print("once")\n} while false',
        '// break, continue, labels\nouter: for i in 1...5 {\n    for j in 1...5 {\n        if j == 2 { continue }\n        if i == 3 { break outer }\n        print("(\\(i),\\(j))", terminator: " ")\n    }\n}\nprint()',
    ],
    6: [
        '// arrays\nvar fruits = ["apple", "banana", "cherry"]\nfruits.append("date")\nfruits.insert("fig", at: 0)\nfruits.remove(at: 1)\nprint(fruits)\nprint(fruits[0], fruits.count)',
        '// dictionaries\nvar user: [String: Any] = ["name": "Alice", "age": 30]\nuser["admin"] = true\nuser["age"] = nil        // removes the key\nif let name = user["name"] as? String {\n    print("hello \\(name)")\n}',
        '// sets\nvar tags: Set = ["swift", "ios", "server"]\ntags.insert("vapor")\nlet swift = tags.contains("swift")     // true\nlet a: Set = [1, 2, 3]\nlet b: Set = [2, 3, 4]\nprint(a.union(b))        // [1, 2, 3, 4]\nprint(a.intersection(b)) // [2, 3]',
        '// higher-order functions\nlet nums = [1, 2, 3, 4, 5]\nlet doubled = nums.map { $0 * 2 }\nlet evens = nums.filter { $0 % 2 == 0 }\nlet sum = nums.reduce(0, +)\nprint(doubled, evens, sum)',
    ],
    7: [
        '// function declarations\nfunc greet(name: String, times: Int = 1) -> String {\n    return String(repeating: "Hi \\(name)! ", count: times)\n}\nprint(greet(name: "Alice"))        // default times\nprint(greet(name: "Bob", times: 2))\nprint(greet(name: "Cal", times: 3))',
        '// argument labels and _\nfunc add(_ a: Int, _ b: Int) -> Int { a + b }\nfunc distance(from x: Int, to y: Int) -> Int { abs(x - y) }\nprint(add(2, 3))\nprint(distance(from: 1, to: 10))',
        '// variadic and inout\nfunc sum(_ numbers: Int...) -> Int {\n    numbers.reduce(0, +)\n}\nprint(sum(1, 2, 3, 4))\nfunc increment(_ value: inout Int) {\n    value += 1\n}\nvar n = 41\nincrement(&n)\nprint(n)  // 42',
        '// closures and trailing syntax\nlet names = ["Zoe", "Amy", "Bo"]\nlet sorted = names.sorted { $0 < $1 }\nlet mapped = names.map { $0.uppercased() }\nprint(sorted, mapped)\n// capture context\nvar counter = 0\nlet incrementer = { counter += 1 }\nincrementer(); incrementer()\nprint(counter)  // 2',
    ],
    8: [
        '// struct with stored + computed properties\nstruct Rectangle {\n    var width: Double\n    var height: Double\n    var area: Double { width * height }\n}\nlet r = Rectangle(width: 3, height: 4)\nprint(r.area)  // 12.0',
        'import Foundation\n// memberwise init + custom init\nstruct Point {\n    var x: Double\n    var y: Double\n    init(x: Double) { self.x = x; self.y = 0 }\n    func distance(to other: Point) -> Double {\n        hypot(x - other.x, y - other.y)\n    }\n}\nlet p = Point(x: 3)\nprint(p.distance(to: Point(x: 0, y: 4)))',
        '// mutating methods\nstruct Counter {\n    private(set) var count = 0\n    mutating func increment() { count += 1 }\n    mutating func reset() { count = 0 }\n}\nvar c = Counter()\nc.increment(); c.increment()\nprint(c.count)  // 2',
        '// value semantics — copies are independent\nvar a = [1, 2, 3]\nvar b = a\nb.append(4)\nprint(a)  // [1, 2, 3]\nprint(b)  // [1, 2, 3, 4] (COW keeps memory efficient)',
    ],
    9: [
        '// class with reference semantics\nclass Person {\n    var name: String\n    init(name: String) { self.name = name }\n    func greet() { print("Hi, I am \\(name)") }\n}\nlet alice = Person(name: "Alice")\nlet copy = alice       // SAME instance\ncopy.name = "Alicia"\nprint(alice.name)      // "Alicia" — shared state!',
        '// inheritance\nclass Animal {\n    let name: String\n    init(name: String) { self.name = name }\n    func speak() -> String { "..." }\n}\nclass Dog: Animal {\n    override func speak() -> String { "Woof!" }\n}\nlet rex = Dog(name: "Rex")\nprint(rex.speak())  // Woof!',
        '// deinit and lifecycle\nclass Logger {\n    let tag: String\n    init(tag: String) { self.tag = tag; print("\\(tag) created") }\n    deinit { print("\\(tag) destroyed") }\n    func log(_ s: String) { print("\\(tag): \\(s)") }\n}\nvar lg: Logger? = Logger(tag: "app")\nlg?.log("boot")\nlg = nil  // triggers deinit',
        '// access control\nclass Bank {\n    private var balance: Int = 0\n    internal var owner: String\n    init(owner: String) { self.owner = owner }\n    func deposit(_ amount: Int) { balance += amount }\n    func currentBalance() -> Int { balance }\n}\nlet acc = Bank(owner: "Alice")\nacc.deposit(100)\nprint(acc.currentBalance())',
    ],
    10: [
        '// enums with raw values\nenum Direction: String {\n    case north, south, east, west\n}\nlet d = Direction.north\nprint(d.rawValue)          // "north"\nprint(Direction(rawValue: "east")!)  // .east',
        '// associated values\nenum Result {\n    case success(Int)\n    case failure(String)\n}\nlet r = Result.success(200)\nswitch r {\ncase .success(let code): print("ok \\(code)")\ncase .failure(let msg):  print("err \\(msg)")\n}',
        '// if case and guard case\nlet value: Result = .failure("timeout")\nif case .failure(let msg) = value {\n    print("failed: \\(msg)")\n}\nfunc describe(_ r: Result) -> String {\n    if case .success(let code) = r, code >= 200, code < 300 {\n        return "successful request"\n    }\n    return "other"\n}\nprint(describe(value))',
        '// recursive enums\nindirect enum Expression {\n    case number(Int)\n    case add(Expression, Expression)\n    case multiply(Expression, Expression)\n}\nlet e = Expression.add(.number(2), .multiply(.number(3), .number(4)))\nfunc eval(_ ex: Expression) -> Int {\n    switch ex {\n    case .number(let n): return n\n    case .add(let a, let b): return eval(a) + eval(b)\n    case .multiply(let a, let b): return eval(a) * eval(b)\n    }\n}\nprint(eval(e))  // 14',
    ],
    11: [
        '// protocol + conformance\nprotocol Describable {\n    var summary: String { get }\n}\nstruct Order: Describable {\n    let id: Int\n    var summary: String { "order #\\(id)" }\n}\nlet o = Order(id: 42)\nprint(o.summary)',
        '// protocol inheritance\nprotocol Named {\n    var name: String { get }\n}\nprotocol Greetable: Named {\n    func greet() -> String\n}\nextension Greetable {\n    func greet() -> String { "Hello, \\(name)!" }\n}\nstruct User: Greetable {\n    let name: String\n}\nprint(User(name: "Alice").greet())',
        '// extensions add behavior\nprotocol Togglable {\n    mutating func toggle()\n}\nextension Bool: Togglable {\n    mutating func toggle() { self = !self }\n}\nvar flag = true\nflag.toggle()\nprint(flag)  // false',
        '// default implementations + collections of protocols\nprotocol Shape {\n    var area: Double { get }\n    func describe() -> String\n}\nextension Shape {\n    func describe() -> String { "area = \\(area)" }\n}\nstruct Circle: Shape { let r: Double; var area: Double { .pi * r * r } }\nlet shapes: [any Shape] = [Circle(r: 2)]\nfor s in shapes { print(s.describe()) }',
    ],
    12: [
        '// optional basics\nvar maybe: Int? = 42\nprint(maybe)          // Optional(42)\nmaybe = nil\nprint(maybe ?? 0)     // 0 — nil coalescing',
        '// if-let binding\nlet dict = ["name": "Alice", "age": "30"]\nif let name = dict["name"], let age = dict["age"] {\n    print("\\(name) is \\(age)")\n} else {\n    print("missing keys")\n}',
        '// guard-let early exit\nfunc parseAge(_ raw: String) -> Int {\n    guard let value = Int(raw), value > 0 else {\n        print("invalid age: \\(raw)")\n        return 0\n    }\n    return value\n}\nprint(parseAge("30"))   // 30\nprint(parseAge("abc"))  // 0 + message',
        '// optional chaining\nstruct Address { var city: String }\nstruct User { var address: Address? }\nlet user = User(address: Address(city: "Paris"))\nprint(user.address?.city ?? "unknown")  // Paris\nlet empty = User(address: nil)\nprint(empty.address?.city ?? "unknown") // unknown',
    ],
    13: [
        '// define + throw + catch\nenum FileError: Error {\n    case notFound\n    case unreadable(String)\n}\nfunc loadFile(_ path: String) throws -> String {\n    guard path != "" else { throw FileError.notFound }\n    if path.hasSuffix(".txt") { return "contents of \\(path)" }\n    throw FileError.unreadable(path)\n}\ndo {\n    let text = try loadFile("notes.txt")\n    print(text)\n} catch FileError.notFound {\n    print("no such file")\n} catch {\n    print("other error: \\(error)")\n}',
        '// propagating with try\ntypealias FileLoader = (String) throws -> String\nfunc safeLoad(_ path: String, using loader: FileLoader) -> String? {\n    try? loader(path)   // converts error to nil\n}\nlet result = safeLoad("a.txt", using: loadFile)\nprint(result ?? "failed")',
        '// try? and try!\nlet a = try? loadFile("missing.txt")  // nil\n// let b = try! loadFile("")            // crashes if it throws\nprint(a ?? "nil from try?")',
        '// defer for cleanup\nfunc process(_ path: String) throws {\n    print("open resource")\n    defer { print("close resource") }\n    let data = try loadFile(path)\n    print("got \\(data.count) chars")\n}\ntry? process("data.txt")',
    ],
    14: [
        '// generic functions\nfunc swapValues<T>(_ a: inout T, _ b: inout T) {\n    let tmp = a; a = b; b = tmp\n}\nvar x = 1, y = 2\nswapValues(&x, &y)\nprint(x, y)  // 2 1\nvar s1 = "a", s2 = "b"\nswapValues(&s1, &s2)\nprint(s1, s2)',
        '// generic types\nstruct Stack<Element> {\n    private var items: [Element] = []\n    mutating func push(_ e: Element) { items.append(e) }\n    mutating func pop() -> Element? { items.popLast() }\n    var count: Int { items.count }\n}\nvar stack = Stack<Int>()\nstack.push(1); stack.push(2)\nprint(stack.pop() ?? 0, stack.count)  // 2 1',
        '// constraints\nfunc largest<T: Comparable>(_ a: T, _ b: T) -> T {\n    a > b ? a : b\n}\nprint(largest(3, 7))        // 7\nprint(largest("cat", "dog")) // "dog"',
        '// associated types + where\nprotocol Container {\n    associatedtype Item\n    mutating func append(_ item: Item)\n    var count: Int { get }\n}\nextension Array: Container {}\nfunc firstElement<C: Container>(_ c: C) -> C.Item? {\n    guard c.count > 0, let items = c as? [C.Item] else { return nil }\n    return items[0]\n}\nlet arr = [10, 20, 30]\nprint(firstElement(arr) ?? 0)  // 10',
    ],
    15: [
        'import Foundation\n// async function\nfunc fetchUser() async -> String {\n    try? await Task.sleep(nanoseconds: 100_000_000)\n    return "Alice"\n}\n// top-level entry point\nfunc main() async {\n    let user = await fetchUser()\n    print("user: \\(user)")\n}\nawait main()',
        '// async-let for parallel work\nfunc fetch(_ id: Int) async -> Int { id * id }\nfunc main2() async {\n    async let a = fetch(3)\n    async let b = fetch(4)\n    let sum = await a + await b\n    print("parallel sum: \\(sum)")  // 25\n}\nawait main2()',
        '// TaskGroup\nfunc sumAll(_ nums: [Int]) async -> Int {\n    await withTaskGroup(of: Int.self) { group in\n        for n in nums {\n            group.addTask { n * n }\n        }\n        var total = 0\n        for await v in group { total += v }\n        return total\n    }\n}\nfunc main3() async {\n    print(await sumAll([1, 2, 3, 4]))  // 30\n}\nawait main3()',
        '// MainActor isolation\nimport Foundation\n@MainActor\nfinal class ViewModel {\n    private(set) var items: [String] = []\n    func load() async {\n        try? await Task.sleep(nanoseconds: 10_000_000)\n        items = ["a", "b"]\n    }\n}\nfunc main4() async {\n    let vm = ViewModel()\n    await vm.load()\n    print(await vm.items)\n}\nawait main4()',
    ],
    16: [
        '// actor isolation\nactor BankAccount {\n    private var balance = 0\n    func deposit(_ amount: Int) { balance += amount }\n    func withdraw(_ amount: Int) -> Bool {\n        guard balance >= amount else { return false }\n        balance -= amount\n        return true\n    }\n    func currentBalance() -> Int { balance }\n}\nfunc main5() async {\n    let acc = BankAccount()\n    await acc.deposit(100)\n    print(await acc.currentBalance())  // 100\n}\nawait main5()',
        '// Sendable value types\nstruct Invoice: Sendable {\n    let id: Int\n    let total: Double\n}\n// structs of value types are automatically Sendable\nfunc process(_ invoice: Invoice) { print(invoice.id) }\nlet inv = Invoice(id: 1, total: 99.0)\nprocess(inv)',
        '// global actors\nimport Foundation\n@globalActor\nstruct MyActor {\n    static let shared = MyActor()\n}\n@MyActor\nfunc isolatedWork() { print("on MyActor") }\nfunc main6() async {\n    await isolatedWork()\n}\nawait main6()',
        '// data race prevention with actors\nactor Counter2 {\n    private var value = 0\n    func increment() -> Int {\n        value += 1\n        return value\n    }\n}\nfunc main7() async {\n    let c = Counter2()\n    await withTaskGroup(of: Int.self) { group in\n        for _ in 0..<10 {\n            group.addTask { await c.increment() }\n        }\n        for await v in group { print(v, terminator: " ") }\n    }\n}\nawait main7()  // 1...10 — no race',
    ],
    17: [
        '// ARC tracks references\nclass Token {\n    let id: String\n    init(id: String) { self.id = id }\n    deinit { print("token \\(id) freed") }\n}\nvar t: Token? = Token(id: "a1")\nvar t2 = t          // +1 strong ref\nt = nil\nprint("still alive") // t2 holds it\nt2 = nil            // now deinit fires',
        '// strong reference cycle\nclass Owner {\n    var pet: Pet?\n    deinit { print("owner gone") }\n}\nclass Pet {\n    weak var owner: Owner?   // weak breaks the cycle\n    deinit { print("pet gone") }\n}\nvar owner: Owner? = Owner()\nvar pet: Pet? = Pet()\nowner?.pet = pet\npet?.owner = owner\nowner = nil\npet = nil  // both deinit now (with weak)',
        '// unowned — assume the other is alive\nclass Client {\n    var card: CreditCard?\n    deinit { print("client gone") }\n}\nclass CreditCard {\n    unowned let client: Client\n    init(client: Client) { self.client = client }\n    deinit { print("card gone") }\n}\nvar alice: Client? = Client()\nalice?.card = CreditCard(client: alice!)\nalice = nil  // both deinit',
        '// closure capture cycles\nclass Downloader {\n    var progress: ((Double) -> Void)?\n    func start() {\n        progress = { [weak self] p in\n            print("progress \\(p)")\n            _ = self   // weak self avoids the cycle\n        }\n    }\n}\nvar dl: Downloader? = Downloader()\ndl?.start()\ndl = nil',
    ],
    18: [
        'import Foundation\n// Codable conformance\nstruct User: Codable {\n    let name: String\n    let age: Int\n    let tags: [String]\n}\nlet user = User(name: "Alice", age: 30, tags: ["swift", "ios"])',
        'import Foundation\n// encode to JSON\nlet encoder = JSONEncoder()\nencoder.outputFormatting = [.prettyPrinted, .sortedKeys]\nlet data = try encoder.encode(user)\nprint(String(data: data, encoding: .utf8)!)',
        'import Foundation\n// decode from JSON\nlet json = #"{"name":"Bob","age":25,"tags":["server"]}"#\nlet decoder = JSONDecoder()\nlet decoded = try decoder.decode(User.self, from: Data(json.utf8))\nprint(decoded.name, decoded.tags)',
        'import Foundation\n// continues from sample 2 (data + path)\n// file I/O\nlet dir = FileManager.default.temporaryDirectory\nlet path = dir.appendingPathComponent("user.json")\ntry data.write(to: path)                    // write\ntry? FileManager.default.removeItem(at: path)  // cleanup\nprint(path.path)',
    ],
    19: [
        '// swift package init --type executable\n// Package.swift:\n//   // swift-tools-version: 5.10\n//   import PackageDescription\n//   let package = Package(\n//       name: "MyLib",\n//       targets: [.executableTarget(name: "MyLib")]\n//   )\nprint("package created")',
        '// adding dependencies\n// Package.swift:\n//   dependencies: [\n//       .package(url: "https://github.com/apple/swift-algorithms.git",\n//                from: "1.2.0")\n//   ],\n//   targets: [.executableTarget(name: "MyLib",\n//               dependencies: [.product(name: "Algorithms",\n//                               package: "swift-algorithms")])]',
        'import Algorithms\n// after adding the Algorithms dependency\nlet array = [1, 2, 3, 4]\nfor chunk in array.chunks(ofCount: 2) {\n    print(chunk, terminator: " ")\n}\nprint()',
        '// command-line workflow\n// swift build       -> compile\n// swift run         -> execute\n// swift test        -> run tests\n// swift package update   -> refresh deps\n// swift package dump-package\nprint("build, run, test, update")',
    ],
    20: [
        'import XCTest\nfinal class CalculatorTests: XCTestCase {\n    func testAddition() {\n        XCTAssertEqual(2 + 2, 4)\n        XCTAssertTrue(2 + 2 == 4)\n    }\n    func testOptional() {\n        let value: Int? = 7\n        XCTAssertNotNil(value)\n        XCTAssertEqual(value, 7)\n    }\n}',
        'import Testing\n// Swift Testing (Xcode 16+) uses @Test instead of classes\n@Test func arithmetic() {\n    #expect(3 * 3 == 9)\n}\n@Test(arguments: [1, 2, 3])\nfunc tableDriven(n: Int) {\n    #expect(n > 0)\n}',
        'import XCTest\nfinal class SetupTests: XCTestCase {\n    var values: [Int] = []\n    override func setUp() {\n        super.setUp()\n        values = [1, 2, 3]\n    }\n    func testCount() {\n        XCTAssertEqual(values.count, 3)\n    }\n}',
        'import XCTest\n// performance measurement\nfinal class PerfTests: XCTestCase {\n    func testSortPerformance() {\n        let data = (0..<10_000).shuffled()\n        measure {\n            _ = data.sorted()\n        }\n    }\n}',
    ],
    21: [
        '// value types are cheap thanks to COW\nvar large = Array(repeating: 0, count: 1_000_000)\nvar copy = large            // shares storage — O(1)\ncopy[0] = 1                 // only now does it copy\nprint(large[0], copy[0])    // 0 1',
        '// lazy properties compute once\nstruct Report {\n    let rows: [Int]\n    lazy var total: Int = rows.reduce(0, +)\n    init(rows: [Int]) { self.rows = rows }\n}\nvar rep = Report(rows: [1, 2, 3])\nprint(rep.total)  // computed now, cached after',
        '// prefer value types for performance\nstruct ValueBox { var x: Int; var y: Int }\nlet boxes = (0..<100).map { ValueBox(x: $0, y: $0 * 2) }\nprint(boxes.count, MemoryLayout<ValueBox>.size)  // 16 bytes',
        '// benchmarking a function\nimport Foundation\nlet start = DispatchTime.now()\nlet sum = (0..<1_000_000).reduce(0, +)\nlet elapsed = DispatchTime.now().uptimeNanoseconds - start.uptimeNanoseconds\nprint("sum=\\(sum) in \\(Double(elapsed) / 1e6) ms")',
    ],
}


if __name__ == '__main__':
    run_gen(LANGUAGE, 'swift', LESSONS, CODE, BASE)
