#!/usr/bin/env python3
"""Generate the 21-lesson Kotlin deep curriculum for the 100xsystems registry.

Uses the shared gen_lib.py template. Produces:
  - static-data/knowledge/languages/kotlin/kotlin-*.md (21 lesson files)
  - updated index.json lessons array (categories preserved)
  - removes stale skeleton files
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_lib import main as run_gen  # noqa: E402

LANGUAGE = 'kotlin'
BASE = 'static-data/knowledge/languages/kotlin'

LESSONS = [
    dict(slug='kotlin-01-getting-started', title='Getting Started with Kotlin',
         desc='Install the compiler, run scripts, and meet the Kotlin playground.',
         dur='45 min', diff='beginner', prereq=[],
         objs=['Install Kotlin and run your first program',
               'Use println and string templates',
               'Compile with kotlinc or run with kotlin',
               'Understand the JVM/JS/Native targets'],
         refs=[dict(title='Kotlin — Getting Started', url='https://kotlinlang.org/docs/getting-started.html'),
               dict(title='Kotlin — Basic Syntax', url='https://kotlinlang.org/docs/basic-syntax.html'),
               dict(title='Kotlin Playground', url='https://play.kotlinlang.org/')]),
    dict(slug='kotlin-02-variables-types', title='Variables and Data Types',
         desc='val, var, type inference, and the core types.',
         dur='60 min', diff='beginner', prereq=['KOTLIN-01'],
         objs=['Declare values with val and var',
               'Let the compiler infer types',
               'Work with Int, Long, Double, String, Boolean',
               'Use nullable types with ?'],
         refs=[dict(title='Kotlin — Basic Types', url='https://kotlinlang.org/docs/basic-types.html'),
               dict(title='Kotlin — Null Safety', url='https://kotlinlang.org/docs/null-safety.html'),
               dict(title='Kotlin — Type Checks and Casts', url='https://kotlinlang.org/docs/typecasts.html')]),
    dict(slug='kotlin-03-numbers-math', title='Numbers and Math',
         desc='Integer types, floating point, overflow, and math APIs.',
         dur='50 min', diff='beginner', prereq=['KOTLIN-02'],
         objs=['Use Int, Long, Float, and Double',
               'Understand overflow and ranges',
               'Use the kotlin.math API',
               'Format numbers for output'],
         refs=[dict(title='Kotlin — Numbers', url='https://kotlinlang.org/docs/numbers.html'),
               dict(title='Kotlin — Math Functions', url='https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.math/'),
               dict(title='Kotlin — Ranges and Progressions', url='https://kotlinlang.org/docs/ranges.html')]),
    dict(slug='kotlin-04-strings', title='Strings and String Templates',
         desc='String literals, templates, and the string API.',
         dur='60 min', diff='beginner', prereq=['KOTLIN-02'],
         objs=['Write strings and raw triple-quoted strings',
               'Interpolate with templates',
               'Manipulate strings with the standard library',
               'Work with multi-line and formatted output'],
         refs=[dict(title='Kotlin — Strings', url='https://kotlinlang.org/docs/strings.html'),
               dict(title='Kotlin — String Templates', url='https://kotlinlang.org/docs/basic-syntax.html#string-templates'),
               dict(title='Kotlin — Regex', url='https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/-regex/')]),
    dict(slug='kotlin-05-control-flow', title='Control Flow',
         desc='if expressions, when, and loops.',
         dur='50 min', diff='beginner', prereq=['KOTLIN-02'],
         objs=['Use if as an expression',
               'Match with when (Kotlin\'s switch)',
               'Iterate with for and while',
               'Use break, continue, and labels'],
         refs=[dict(title='Kotlin — Control Flow', url='https://kotlinlang.org/docs/control-flow.html'),
               dict(title='Kotlin — When Expression', url='https://kotlinlang.org/docs/control-flow.html#when-expression'),
               dict(title='Kotlin — For Loops', url='https://kotlinlang.org/docs/control-flow.html#for-loops')]),
    dict(slug='kotlin-06-collections', title='Collections',
         desc='Lists, sets, maps, and collection operators.',
         dur='60 min', diff='beginner', prereq=['KOTLIN-05'],
         objs=['Build lists, sets, and maps',
               'Distinguish mutable and read-only views',
               'Transform with map, filter, and reduce',
               'Use sorting and searching helpers'],
         refs=[dict(title='Kotlin — Collections Overview', url='https://kotlinlang.org/docs/collections-overview.html'),
               dict(title='Kotlin — List', url='https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/list/'),
               dict(title='Kotlin — Collection Operations', url='https://kotlinlang.org/docs/collection-operations.html')]),
    dict(slug='kotlin-07-functions', title='Functions',
         desc='Function declarations, default args, and lambdas.',
         dur='60 min', diff='beginner', prereq=['KOTLIN-05'],
         objs=['Declare functions with named and default arguments',
               'Use single-expression functions',
               'Write lambdas and higher-order functions',
               'Use extension functions'],
         refs=[dict(title='Kotlin — Functions', url='https://kotlinlang.org/docs/functions.html'),
               dict(title='Kotlin — Lambdas', url='https://kotlinlang.org/docs/lambdas.html'),
               dict(title='Kotlin — Extension Functions', url='https://kotlinlang.org/docs/extensions.html')]),
    dict(slug='kotlin-08-classes', title='Classes and Objects',
         desc='Classes, constructors, properties, and data classes.',
         dur='75 min', diff='intermediate', prereq=['KOTLIN-07'],
         objs=['Define classes with primary and secondary constructors',
               'Use properties and backing fields',
               'Write data classes for value holders',
               'Use object declarations and companion objects'],
         refs=[dict(title='Kotlin — Classes', url='https://kotlinlang.org/docs/classes.html'),
               dict(title='Kotlin — Properties', url='https://kotlinlang.org/docs/properties.html'),
               dict(title='Kotlin — Data Classes', url='https://kotlinlang.org/docs/data-classes.html')]),
    dict(slug='kotlin-09-inheritance-interfaces', title='Inheritance and Interfaces',
         desc='open classes, abstract classes, and interfaces.',
         dur='75 min', diff='intermediate', prereq=['KOTLIN-08'],
         objs=['Extend open classes and override members',
               'Design with abstract classes',
               'Implement interfaces and delegation',
               'Use sealed classes for hierarchies'],
         refs=[dict(title='Kotlin — Inheritance', url='https://kotlinlang.org/docs/inheritance.html'),
               dict(title='Kotlin — Interfaces', url='https://kotlinlang.org/docs/interfaces.html'),
               dict(title='Kotlin — Sealed Classes', url='https://kotlinlang.org/docs/sealed-classes.html')]),
    dict(slug='kotlin-10-null-safety', title='Null Safety',
         desc='Nullable types, safe calls, and the Elvis operator.',
         dur='50 min', diff='beginner', prereq=['KOTLIN-02'],
         objs=['Declare nullable types with ?',
               'Use safe calls and the Elvis operator',
               'Force-unwrap deliberately',
               'Use let, also, and other scope functions'],
         refs=[dict(title='Kotlin — Null Safety', url='https://kotlinlang.org/docs/null-safety.html'),
               dict(title='Kotlin — Scope Functions', url='https://kotlinlang.org/docs/scope-functions.html'),
               dict(title='Kotlin — Idioms (Elvis)', url='https://kotlinlang.org/docs/idioms.html#elvis-operator')]),
    dict(slug='kotlin-11-exceptions', title='Exceptions and Error Handling',
         desc='Throwables, try-catch, and custom exceptions.',
         dur='60 min', diff='intermediate', prereq=['KOTLIN-10'],
         objs=['Throw and catch exceptions',
               'Use try as an expression',
               'Define custom exception types',
               'Run cleanup with finally'],
         refs=[dict(title='Kotlin — Exceptions', url='https://kotlinlang.org/docs/exceptions.html'),
               dict(title='Kotlin — try/catch', url='https://kotlinlang.org/docs/exceptions.html#try-catch-expressions'),
               dict(title='Kotlin — runCatching', url='https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/run-catching.html')]),
    dict(slug='kotlin-12-generics', title='Generics',
         desc='Generic types, variance, and reified types.',
         dur='75 min', diff='advanced', prereq=['KOTLIN-09'],
         objs=['Write generic functions and classes',
               'Use type parameters with bounds',
               'Understand in and out variance',
               'Use reified type parameters'],
         refs=[dict(title='Kotlin — Generics', url='https://kotlinlang.org/docs/generics.html'),
               dict(title='Kotlin — Variance', url='https://kotlinlang.org/docs/generics.html#variance'),
               dict(title='Kotlin — Reified Types', url='https://kotlinlang.org/docs/inline-functions.html#reified-type-parameters')]),
    dict(slug='kotlin-13-coroutines', title='Coroutines and Flow',
         desc='suspend functions, coroutine scopes, and cold flows.',
         dur='75 min', diff='advanced', prereq=['KOTLIN-12'],
         objs=['Launch coroutines with launch and async',
               'Write suspend functions',
               'Manage concurrency with coroutine scopes',
               'Consume and build Flows'],
         refs=[dict(title='Kotlin — Coroutines Guide', url='https://kotlinlang.org/docs/coroutines-guide.html'),
               dict(title='Kotlin — coroutineScope', url='https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/coroutine-scope.html'),
               dict(title='Kotlin — Flow Guide', url='https://kotlinlang.org/docs/flow.html')]),
    dict(slug='kotlin-14-file-io', title='File I/O and Serialization',
         desc='Reading and writing files, and kotlinx.serialization.',
         dur='60 min', diff='intermediate', prereq=['KOTLIN-11'],
         objs=['Read and write text files',
               'Work with the java.io and java.nio APIs',
               'Serialize with kotlinx.serialization',
               'Handle binary data'],
         refs=[dict(title='Kotlin — Serialization', url='https://kotlinlang.org/docs/serialization.html'),
               dict(title='Kotlinx Serialization — GitHub', url='https://github.com/Kotlin/kotlinx.serialization'),
               dict(title='Java — File I/O Guide', url='https://docs.oracle.com/javase/tutorial/essential/io/')]),
    dict(slug='kotlin-15-collections-advanced', title='Advanced Collections',
         desc='Sequences, grouping, and lazy evaluation.',
         dur='60 min', diff='intermediate', prereq=['KOTLIN-06'],
         objs=['Use sequences for lazy pipelines',
               'Group and associate elements',
               'Zip and pair collections',
               'Use windows and chunked operations'],
         refs=[dict(title='Kotlin — Sequences', url='https://kotlinlang.org/docs/sequences.html'),
               dict(title='Kotlin — Grouping', url='https://kotlinlang.org/docs/collection-grouping.html'),
               dict(title='Kotlin — Collection Operations', url='https://kotlinlang.org/docs/collection-operations.html')]),
    dict(slug='kotlin-16-functional', title='Functional Kotlin',
         desc='Higher-order functions, immutability, and DSLs.',
         dur='60 min', diff='intermediate', prereq=['KOTLIN-07'],
         objs=['Compose functions and use let/run/with/apply',
               'Build small DSLs with lambdas with receivers',
               'Prefer immutability with val and copy',
               'Use standard functional helpers'],
         refs=[dict(title='Kotlin — Scope Functions', url='https://kotlinlang.org/docs/scope-functions.html'),
               dict(title='Kotlin — Lambdas with Receivers', url='https://kotlinlang.org/docs/lambdas.html#function-literals-with-receiver'),
               dict(title='Kotlin — Idioms', url='https://kotlinlang.org/docs/idioms.html')]),
    dict(slug='kotlin-17-testing', title='Testing with Kotlin',
         desc='Unit tests, JUnit, assertions, and test doubles.',
         dur='60 min', diff='intermediate', prereq=['KOTLIN-16'],
         objs=['Write JUnit 5 tests in Kotlin',
               'Use assertions and assume',
               'Parameterize tests',
               'Run tests with Gradle'],
         refs=[dict(title='Kotlin — Testing Guide', url='https://kotlinlang.org/docs/testing.html'),
               dict(title='JUnit 5 Documentation', url='https://junit.org/junit5/docs/current/user-guide/'),
               dict(title='Kotlin — Test Fixtures', url='https://kotlinlang.org/docs/testing.html#test-fixtures')]),
    dict(slug='kotlin-18-coroutines-channels', title='Channels and Structured Concurrency',
         desc='Channels, select, and structured concurrency patterns.',
         dur='75 min', diff='advanced', prereq=['KOTLIN-13'],
         objs=['Build pipelines with Channels',
               'Select across multiple suspending sources',
               'Cancel and handle timeouts',
               'Understand structured concurrency rules'],
         refs=[dict(title='Kotlin — Channels Guide', url='https://kotlinlang.org/docs/channels.html'),
               dict(title='Kotlin — select Expression', url='https://kotlinlang.org/docs/select-expression.html'),
               dict(title='Kotlin — Composing Suspending Functions', url='https://kotlinlang.org/docs/composing-suspending-functions.html')]),
    dict(slug='kotlin-19-gradle-build', title='Gradle and Build Tooling',
         desc='Project structure, dependencies, and build scripts.',
         dur='60 min', diff='intermediate', prereq=['KOTLIN-01'],
         objs=['Create a Gradle Kotlin project',
               'Declare dependencies and plugins',
               'Build JARs and run tasks',
               'Publish to Maven repositories'],
         refs=[dict(title='Kotlin — Gradle with Kotlin DSL', url='https://kotlinlang.org/docs/gradle-configure-project.html'),
               dict(title='Gradle — Getting Started', url='https://docs.gradle.org/current/userguide/getting_started_eng.html'),
               dict(title='Kotlin — Publishing', url='https://kotlinlang.org/docs/maven-publish.html')]),
    dict(slug='kotlin-20-dsl-reflection', title='DSLs, Reflection, and Metaprogramming',
         desc='Type-safe builders, reflection, and annotation processing.',
         dur='75 min', diff='advanced', prereq=['KOTLIN-19'],
         objs=['Build type-safe DSLs',
               'Inspect types with reflection',
               'Use annotation processing',
               'Write compiler plugins conceptually'],
         refs=[dict(title='Kotlin — Type-Safe Builders', url='https://kotlinlang.org/docs/type-safe-builders.html'),
               dict(title='Kotlin — Reflection', url='https://kotlinlang.org/docs/reflection.html'),
               dict(title='Kotlin — Annotations', url='https://kotlinlang.org/docs/annotations.html')]),
    dict(slug='kotlin-21-performance', title='Performance and Best Practices',
         desc='Inline functions, allocations, and idiomatic performance.',
         dur='75 min', diff='advanced', prereq=['KOTLIN-20'],
         objs=['Use inline functions to avoid overhead',
               'Minimize allocations in hot paths',
               'Apply idiomatic best practices',
               'Profile and benchmark Kotlin code'],
         refs=[dict(title='Kotlin — Inline Functions', url='https://kotlinlang.org/docs/inline-functions.html'),
               dict(title='Kotlin — Performance Best Practices', url='https://kotlinlang.org/docs/best-practices.html'),
               dict(title='Kotlin — JavaScript/Wasip Performance', url='https://kotlinlang.org/docs/js-performance.html')]),
]

CODE = {
    1: [
        '// hello.kt — compile: kotlinc hello.kt -include-runtime -d hello.jar\n// run: java -jar hello.jar\nfun main() {\n    println("Hello, 100x Systems!")\n    val name = "Kotlin"\n    println("Welcome to $name!")\n}',
        '// script mode: kotlinc -script hello.kts\nfun main(args: Array<String>) {\n    println("args = ${args.joinToString()}")\n    val who = args.firstOrNull() ?: "world"\n    println("Hello, $who")\n}\nmain()',
        '// multiple targets\nprintln("JVM: ${System.getProperty("java.version")}")\n// Native -> standalone binary\n// JS     -> browser/server code\n// Wasm   -> WebAssembly\nprintln("targets: JVM, Native, JS, Wasm")',
        '// command-line tools\n// kotlinc file.kt            -> compile to .class\n// kotlinc -script x.kts      -> run as script\n// kotlin file.kt             -> run directly\n// kotlinc-jvm                -> JVM compiler\nprintln("toolchain ready")',
    ],
    2: [
        '// val vs var\nfun main() {\n    val name = "Kotlin"   // immutable\n    var score = 42        // mutable\n    score += 1\n    // name = "Java"      // error: val cannot be reassigned\n    println("$name: $score")\n}',
        '// type inference\nfun main() {\n    val count = 10            // Int\n    val pi = 3.14             // Double\n    val greeting = "hi"       // String\n    val ok = true             // Boolean\n    val big = 9_000_000_000L  // Long (L suffix)\n    println("$count $pi $greeting $ok $big")\n}',
        '// explicit types and conversion\nfun main() {\n    val a: Int = 5\n    val b: Double = 2.5\n    val sum = a + b.toInt()   // 7\n    val text = sum.toString() // "7"\n    val asLong = a.toLong()\n    println("$sum $text $asLong")\n}',
        '// nullable types\nfun main() {\n    var maybe: String? = "hello"\n    maybe = null             // allowed on nullable\n    val len = maybe?.length  // safe call -> null\n    println(len ?: 0)        // 0 via Elvis\n}',
    ],
    3: [
        '// integer types\nfun main() {\n    val byte: Byte = 127\n    val short: Short = 32767\n    val int = 2_147_483_647\n    val long = 9_223_372_036_854_775_807L\n    println("$byte $short $int $long")\n}',
        '// floating point + overflow\nfun main() {\n    val d = 0.1 + 0.2            // Double\n    println(d)                   // 0.30000000000000004\n    val f = 0.1f + 0.2f          // Float\n    println(f)\n    val max = Int.MAX_VALUE\n    // val boom = max + 1        // overflow wraps silently in Kotlin!\n    println("$max overflow wraps to ${max + 1}")\n}',
        '// kotlin.math\nimport kotlin.math.*\nfun main() {\n    println(sqrt(16.0))         // 4.0\n    println(pow(2.0, 10.0))     // 1024.0\n    println(round(3.5))         // 4.0\n    println(abs(-7))            // 7\n}',
        '// ranges\nfun main() {\n    val dice = (1..6).random()\n    println("d6 = $dice")\n    for (i in 1..5) print(i)   // 12345\n    println()\n    for (i in 10 downTo 1 step 3) print("$i ") // 10 7 4 1\n    println()\n    println(3 in 1..5)         // true\n}',
    ],
    4: [
        '// literals and templates\nfun main() {\n    val name = "Alice"\n    val age = 30\n    val msg = "$name is $age years old"\n    val expr = "double: ${age * 2}"\n    val dollar = "cost: \\$5"     // escaped dollar\n    println(msg)\n    println(expr)\n    println(dollar)\n}',
        '// raw triple-quoted strings\nfun main() {\n    val raw = """\n        Line one\n        Line two\n        """.trimIndent()\n    println(raw)\n    val withVars = """\n        name: Alice\n        age: 30\n    """.trimIndent()\n    println(withVars)\n}',
        '// string operations\nfun main() {\n    val s = "Hello, World"\n    println(s.uppercase())         // HELLO, WORLD\n    println(s.lowercase())\n    println(s.startsWith("Hello")) // true\n    println(s.split(","))          // [Hello,  World]\n    println(s.replace("World", "Kotlin"))\n    println(s.substring(0, 5))     // Hello\n}',
        '// builders and formats\nfun main() {\n    val sb = StringBuilder()\n    repeat(3) { i -> sb.append("line$i; ") }\n    println(sb)\n    println("pi = %.2f".format(3.14159))  // pi = 3.14\n    val csv = listOf("a", "b", "c").joinToString(" | ")\n    println(csv)\n}',
    ],
    5: [
        '// if as expression\nfun main() {\n    val score = 85\n    val grade = if (score >= 90) "A" else if (score >= 80) "B" else "C"\n    println(grade)\n    val pass = if (score >= 50) "pass" else "fail"\n    println(pass)\n}',
        '// when expression\nfun main() {\n    val status = 404\n    val message = when (status) {\n        200, 204 -> "ok"\n        404 -> "not found"\n        500 -> "server error"\n        in 400..499 -> "client error"\n        else -> "unknown"\n    }\n    println(message)  // not found\n}',
        '// loops\nfun main() {\n    for (i in 0 until 5) print(i)   // 01234\n    println()\n    val items = listOf("a", "b", "c")\n    for ((idx, v) in items.withIndex()) print("$idx:$v ")\n    println()\n    var n = 0\n    while (n < 3) { n++ }\n    println(n)\n}',
        '// break, continue, labels\nfun main() {\n    outer@ for (i in 1..5) {\n        for (j in 1..5) {\n            if (j == 2) continue\n            if (i == 3) break@outer\n            print("($i,$j) ")\n        }\n    }\n    println()\n}',
    ],
    6: [
        '// lists\nfun main() {\n    val fruits = mutableListOf("apple", "banana")\n    fruits.add("cherry")\n    fruits.removeAt(0)\n    println(fruits)          // [banana, cherry]\n    val readOnly: List<String> = fruits  // view\n    println(readOnly[0])\n}',
        '// sets and maps\nfun main() {\n    val tags = mutableSetOf("kotlin", "jvm")\n    tags.add("android")\n    println("kotlin" in tags)      // true\n    val user = mutableMapOf("name" to "Alice", "age" to 30)\n    user["admin"] = true\n    user.remove("age")\n    println(user)\n}',
        '// transform\nfun main() {\n    val nums = listOf(1, 2, 3, 4, 5)\n    val doubled = nums.map { it * 2 }\n    val evens = nums.filter { it % 2 == 0 }\n    val sum = nums.sum()\n    val product = nums.reduce { acc, n -> acc * n }\n    println("$doubled $evens $sum $product")\n}',
        '// sort and search\nfun main() {\n    val people = listOf("Zoe" to 30, "Amy" to 25, "Bo" to 40)\n    val sorted = people.sortedBy { it.second }\n    println(sorted.map { it.first })  // [Amy, Zoe, Bo]\n    println(people.maxByOrNull { it.second })  // (Bo, 40)\n    println(listOf(1, 2, 3).contains(2))      // true\n}',
    ],
    7: [
        '// default + named arguments\nfun greet(name: String, times: Int = 1): String =\n    "Hi $name! ".repeat(times)\nfun main() {\n    println(greet("Alice"))\n    println(greet("Bob", times = 2))\n}',
        '// single-expression + local functions\nfun square(n: Int) = n * n\nfun main() {\n    fun local(x: Int) = x + 1\n    println(square(9))     // 81\n    println(local(41))     // 42\n}',
        '// lambdas and higher-order\nfun main() {\n    val add: (Int, Int) -> Int = { a, b -> a + b }\n    val triple: (Int) -> Int = { it * 3 }\n    println(add(2, 3))        // 5\n    println(triple(14))       // 42\n    val names = listOf("Zoe", "Amy")\n    println(names.map { it.uppercase() })\n}',
        '// extension functions\nfun String.shout(): String = "$this!!".uppercase()\nfun main() {\n    println("hello".shout())       // HELLO!!\n    println(listOf(1, 2, 3).sum()) // 6\n    fun Int.isEven() = this % 2 == 0\n    println(4.isEven())            // true\n}',
    ],
    8: [
        '// class with constructor + properties\nclass Product(\n    val name: String,\n    val price: Double,\n    var stock: Int = 0,\n) {\n    fun summary(): String = "$name — $$price (stock: $stock)"\n}\nfun main() {\n    val p = Product("Keyboard", 49.99, 12)\n    println(p.summary())\n}',
        '// init blocks and secondary constructors\nclass Counter {\n    var count: Int\n    init { count = 0 }          // runs on construction\n    constructor(start: Int) { count = start }\n    fun increment() { count++ }\n}\nfun main() {\n    val c = Counter(10)\n    c.increment()\n    println(c.count)  // 11\n}',
        '// data classes\ndata class User(val name: String, val age: Int)\nfun main() {\n    val a = User("Alice", 30)\n    val b = a.copy(age = 31)     // immutable copy\n    println(a)                   // User(name=Alice, age=30)\n    println(a == User("Alice", 30))  // true — structural\n    println(b)\n}',
        '// object + companion\nobject Config {\n    val version = "1.0"\n}\nclass Service {\n    companion object {\n        const val NAME = "svc"\n    }\n}\nfun main() {\n    println(Config.version)\n    println(Service.NAME)\n}',
    ],
    9: [
        '// open + override\nopen class Animal(val name: String) {\n    open fun speak(): String = "..."\n}\nclass Dog(name: String) : Animal(name) {\n    override fun speak(): String = "Woof!"\n}\nfun main() {\n    println(Dog("Rex").speak())  // Woof!\n}',
        '// abstract classes\nabstract class Shape {\n    abstract fun area(): Double\n    fun describe(): String = "area = ${area()}"\n}\nclass Circle(val r: Double) : Shape() {\n    override fun area(): Double = Math.PI * r * r\n}\nfun main() {\n    println(Circle(2.0).describe())\n}',
        '// interfaces + delegation\ninterface Logger {\n    fun log(msg: String)\n}\nclass ConsoleLogger : Logger {\n    override fun log(msg: String) = println("[log] $msg")\n}\nclass App : Logger by ConsoleLogger()\nfun main() {\n    App().log("booted")  // delegated\n}',
        '// sealed hierarchies\nsealed class HttpResult {\n    data class Ok(val body: String) : HttpResult()\n    data class Err(val code: Int) : HttpResult()\n}\nfun describe(r: HttpResult): String = when (r) {\n    is HttpResult.Ok -> "ok: ${r.body}"\n    is HttpResult.Err -> "err: ${r.code}"\n}\nfun main() {\n    println(describe(HttpResult.Ok("data")))\n}',
    ],
    10: [
        '// nullable basics\nfun main() {\n    var maybe: String? = "hello"\n    println(maybe)            // hello\n    maybe = null\n    println(maybe?.length)    // null\n    println(maybe ?: 0)       // 0\n}',
        '// safe call chains\nclass Address(val city: String)\nclass Person(val address: Address?)\nfun main() {\n    val p = Person(Address("Paris"))\n    println(p.address?.city)       // Paris\n    val none = Person(null)\n    println(none.address?.city ?: "unknown")  // unknown\n}',
        '// let + safe call\nfun main() {\n    val name: String? = "Alice"\n    name?.let {\n        println("hello $it")     // runs only if non-null\n    }\n    val result = name?.uppercase() ?: "N/A"\n    println(result)\n}',
        '// !! and smart casts\nfun main() {\n    var raw: String? = "42"\n    val n = raw!!.toInt()       // deliberate unwrap\n    println(n)\n    raw = null\n    if (raw != null) {\n        // smart cast: raw is String here\n        println(raw.length)\n    } else {\n        println("null")\n    }\n}',
    ],
    11: [
        '// try-catch\nfun main() {\n    try {\n        val n = "abc".toInt()\n        println(n)\n    } catch (e: NumberFormatException) {\n        println("bad number: ${e.message}")\n    }\n}',
        '// try as expression\nfun parse(raw: String): Int = try {\n    raw.toInt()\n} catch (e: NumberFormatException) {\n    0\n}\nfun main() {\n    println(parse("42"))  // 42\n    println(parse("x"))   // 0\n}',
        '// custom exceptions + finally\nclass PaymentFailed(message: String) : Exception(message)\nfun charge(amount: Double) {\n    if (amount > 100.0) throw PaymentFailed("limit exceeded")\n}\nfun main() {\n    try {\n        charge(500.0)\n    } catch (e: PaymentFailed) {\n        println("payment: ${e.message}")\n    } finally {\n        println("cleanup done")\n    }\n}',
        '// runCatching\nfun main() {\n    val result = runCatching { "7x".toInt() }\n    result.onSuccess { println("parsed $it") }\n    result.onFailure { println("failed: ${it.message}") }\n    val n = result.getOrDefault(0)\n    println(n)\n}',
    ],
    12: [
        '// generic functions\nfun <T> identity(value: T): T = value\nfun main() {\n    println(identity(42))\n    println(identity("text"))\n}',
        '// generic classes\nclass Stack<T> {\n    private val items = mutableListOf<T>()\n    fun push(item: T) { items.add(item) }\n    fun pop(): T? = items.removeLastOrNull()\n    val size get() = items.size\n}\nfun main() {\n    val s = Stack<Int>()\n    s.push(1); s.push(2)\n    println(s.pop())  // 2\n}',
        '// bounds\nfun <T : Comparable<T>> maxOf2(a: T, b: T): T = if (a > b) a else b\nfun main() {\n    println(maxOf2(3, 7))\n    println(maxOf2("cat", "dog"))\n}',
        '// reified + inline\ninline fun <reified T> typeName(): String = T::class.simpleName ?: "?"\nfun main() {\n    println(typeName<String>())  // String\n    println(typeName<Int>())      // Int\n}',
    ],
    13: [
        '// coroutine basics\nimport kotlinx.coroutines.*\nfun main() = runBlocking {\n    val job = launch {\n        delay(100)\n        println("world")\n    }\n    println("hello")\n    job.join()\n}\n// hello then world',
        '// async + await\nimport kotlinx.coroutines.*\nfun main() = runBlocking {\n    val a = async { fetch(3) }\n    val b = async { fetch(4) }\n    println("sum = ${a.await() + b.await()}")  // 25\n}\nsuspend fun fetch(n: Int): Int {\n    delay(10)\n    return n * n\n}',
        '// scopes and cancellation\nimport kotlinx.coroutines.*\nfun main() = runBlocking {\n    val scope = CoroutineScope(Dispatchers.Default)\n    val job = scope.launch {\n        repeat(100) {\n            delay(50)\n            println(it)\n        }\n    }\n    delay(120)\n    job.cancel()          // stops the coroutine\n    println("cancelled")\n}',
        '// flow\nimport kotlinx.coroutines.*\nimport kotlinx.coroutines.flow.*\nfun main() = runBlocking {\n    val squares = (1..5).asFlow()\n        .map { it * it }\n        .filter { it % 2 == 0 }\n    squares.collect { println(it) }  // 4 16\n}',
    ],
    14: [
        '// reading and writing files\nimport java.io.File\nfun main() {\n    File("data.txt").writeText("line one\\nline two\\n")\n    val text = File("data.txt").readText()\n    val lines = File("data.txt").readLines()\n    println(text)\n    println(lines)\n}',
        '// paths with java.nio\nimport java.nio.file.Files\nimport java.nio.file.Path\nfun main() {\n    val p = Path.of("data.txt")\n    Files.writeString(p, "hello nio")\n    println(Files.readString(p))\n    Files.deleteIfExists(p)\n}',
        '// serialization setup\n// build.gradle.kts:\n//   plugins { kotlin("plugin.serialization") version "2.0.0" }\n//   dependencies { implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.0") }\nimport kotlinx.serialization.Serializable\n@Serializable\ndata class User(val name: String, val age: Int)',
        '// JSON round-trip\nimport kotlinx.serialization.Serializable\nimport kotlinx.serialization.json.Json\n@Serializable\ndata class Item(val id: Int, val title: String)\nfun main() {\n    val json = Json.encodeToString(Item(1, "keyboard"))\n    println(json)                     // {"id":1,"title":"keyboard"}\n    val back = Json.decodeFromString<Item>(json)\n    println(back.title)\n}',
    ],
    15: [
        '// sequences — lazy\nfun main() {\n    val result = (1..1_000_000).asSequence()\n        .filter { it % 2 == 0 }\n        .map { it * it }\n        .take(3)\n        .toList()\n    println(result)  // [4, 16, 36] — lazy evaluation\n}',
        '// grouping and associating\nfun main() {\n    val words = listOf("apple", "apricot", "banana", "berry")\n    val byFirst = words.groupBy { it.first() }\n    println(byFirst.keys)  // [a, b]\n    val lenMap = words.associateWith { it.length }\n    println(lenMap)\n}',
        '// zip and pairs\nfun main() {\n    val names = listOf("Alice", "Bob")\n    val ages = listOf(30, 25)\n    val paired = names.zip(ages)\n    println(paired)                      // [(Alice, 30), (Bob, 25)]\n    val map = names.zip(ages).toMap()\n    println(map)\n}',
        '// windows and chunked\nfun main() {\n    val nums = (1..7).toList()\n    println(nums.chunked(3))   // [[1, 2, 3], [4, 5, 6], [7]]\n    println(nums.windowed(3, step = 2))  // [[1,2,3],[3,4,5],[5,6,7]]\n    println(nums.windowed(2))  // adjacent pairs\n}',
    ],
    16: [
        '// let, run, with, apply, also\nfun main() {\n    val name = "Alice"\n    name?.let { println("let: $it") }\n    val len = run { name.length }\n    val text = with(name) { "with: $this" }\n    val applied = StringBuilder().apply {\n        append("a"); append("b")\n    }.toString()\n    val also = mutableListOf(1).also { it.add(2) }\n    println("$len $text $applied $also")\n}',
        '// immutability\nfun main() {\n    data class Point(val x: Int, val y: Int)\n    val p = Point(1, 2)\n    val q = p.copy(y = 5)   // never mutate, always copy\n    println(q)\n    val arr = listOf(1, 2, 3)  // read-only view\n    println(arr)\n}',
        '// function composition\nfun main() {\n    fun String.prep(): String = trim().lowercase()\n    fun List<String>.unique(): List<String> = distinct().sorted()\n    val cleaned = listOf("  B ", "a", "A ")\n        .map { it.prep() }\n        .unique()\n    println(cleaned)  // [a, b]\n}',
        '// lambdas with receivers (mini-DSL)\nfun buildString(builder: StringBuilder.() -> Unit): String {\n    val sb = StringBuilder()\n    sb.builder()\n    return sb.toString()\n}\nfun main() {\n    val s = buildString {\n        append("Hello ")\n        append("DSL!")\n    }\n    println(s)\n}',
    ],
    17: [
        '// JUnit 5 basics\nimport org.junit.jupiter.api.Test\nimport org.junit.jupiter.api.Assertions.*\nclass CalculatorTest {\n    @Test\n    fun `adds two numbers`() {\n        assertEquals(4, 2 + 2)\n        assertTrue(2 + 2 == 4)\n    }\n}',
        '// parameterized tests\nimport org.junit.jupiter.params.ParameterizedTest\nimport org.junit.jupiter.params.provider.ValueSource\nclass ParseTest {\n    @ParameterizedTest\n    @ValueSource(strings = ["1", "2", "3"])\n    fun `parses positive ints`(raw: String) {\n        assertTrue(raw.toInt() > 0)\n    }\n}',
        '// assertions and assumptions\nimport org.junit.jupiter.api.Test\nimport org.junit.jupiter.api.Assertions.*\nclass CalcTest {\n    @Test\n    fun `throws on bad input`() {\n        assertThrows<NumberFormatException> {\n            "abc".toInt()\n        }\n        assertNotEquals(5, 2 + 2)\n    }\n}',
        '// gradle test run\n// build.gradle.kts:\n//   dependencies { testImplementation(kotlin("test")) }\n//   tasks.test { useJUnitPlatform() }\n// run: ./gradlew test --tests \"com.example.*\"\nfun main() {\n    println("tests: ./gradlew test")\n}',
    ],
    18: [
        '// channels\nimport kotlinx.coroutines.*\nimport kotlinx.coroutines.channels.*\nfun main() = runBlocking {\n    val ch = Channel<Int>(capacity = 3)\n    launch { for (x in 1..5) ch.send(x) }\n    repeat(5) { println(ch.receive()) }  // 1..5\n}',
        '// producer-consumer pipeline\nimport kotlinx.coroutines.*\nimport kotlinx.coroutines.channels.*\nfun main() = runBlocking {\n    val ch = Channel<String>()\n    launch { ch.send("job-1"); ch.send("job-2"); ch.close() }\n    for (job in ch) {\n        println("processing $job")\n    }\n}',
        '// select\nimport kotlinx.coroutines.*\nimport kotlinx.coroutines.channels.*\nimport kotlinx.coroutines.selects.*\nfun main() = runBlocking {\n    val a = Channel<Int>(1)\n    val b = Channel<Int>(1)\n    launch { delay(50); a.send(1) }\n    launch { delay(10); b.send(2) }\n    val winner = select<Int> {\n        a.onReceive { it }\n        b.onReceive { it }\n    }\n    println("first: $winner")  // 2 (b is faster)\n}',
        '// timeout and structured concurrency\nimport kotlinx.coroutines.*\nfun main() = runBlocking {\n    val result = withTimeoutOrNull(100) {\n        delay(50)\n        "done in time"\n    }\n    println(result)  // done in time\n    // coroutineScope waits for children before returning\n    coroutineScope {\n        launch { delay(10); println("child done") }\n    }\n}',
    ],
    19: [
        '// gradle project layout\n// project/\n//   build.gradle.kts\n//   settings.gradle.kts\n//   src/main/kotlin/Main.kt\n//   src/test/kotlin/MainTest.kt\n// build.gradle.kts:\n//   plugins { kotlin("jvm") version "2.0.0" }\n//   repositories { mavenCentral() }\nfun main() {\n    println("gradle layout ready")\n}',
        '// dependencies\n// build.gradle.kts:\n//   dependencies {\n//       implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")\n//       testImplementation(kotlin("test"))\n//   }\n//   application { mainClass.set("MainKt") }\nprintln("dependencies declared")',
        '// running tasks\n// ./gradlew build      -> compile + test + jar\n// ./gradlew run        -> run the application\n// ./gradlew test       -> run tests\n// ./gradlew clean      -> delete build outputs\n// ./gradlew tasks      -> list all tasks\nprintln("task runner ready")',
        '// publishing\n// build.gradle.kts:\n//   publishing {\n//       publications {\n//           create<MavenPublication>("maven") {\n//               from(components["java"])\n//           }\n//       }\n//   }\n// ./gradlew publishToMavenLocal\nprintln("publish to maven local")',
    ],
    20: [
        '// type-safe builder DSL\nclass HtmlBuilder {\n    private val parts = mutableListOf<String>()\n    fun p(text: String) { parts.add("<p>$text</p>") }\n    fun h1(text: String) { parts.add("<h1>$text</h1>") }\n    override fun toString(): String = parts.joinToString("\\n")\n}\nfun html(builder: HtmlBuilder.() -> Unit): String {\n    val b = HtmlBuilder()\n    b.builder()\n    return b.toString()\n}\nfun main() {\n    val page = html {\n        h1("Title")\n        p("Body text")\n    }\n    println(page)\n}',
        '// reflection\nfun main() {\n    data class User(val name: String)\n    val props = User::class.members.map { it.name }\n    println(props.contains("name"))\n    val klass = "hello".let { it.javaClass }\n    println(klass.simpleName)\n}',
        '// annotations\n@Target(AnnotationTarget.FUNCTION)\n@Retention(AnnotationRetention.RUNTIME)\nannotation class RateLimit(val limit: Int)\n@RateLimit(100)\nfun apiCall() = println("calling api")\nfun main() {\n    val ann = ::apiCall.annotations.firstOrNull()\n    println(ann)\n}',
        '// kotlin.test assertions\nimport kotlin.test.*\nfun main() {\n    assertEquals(4, 2 + 2)\n    assertContains(listOf(1, 2), 2)\n    assertTrue("abc".length == 3)\n    println("kotlin.test works")\n}',
    ],
    21: [
        '// inline functions avoid lambda allocation\ninline fun measure(block: () -> Unit) {\n    val start = System.nanoTime()\n    block()\n    println("took ${(System.nanoTime() - start) / 1e6} ms")\n}\nfun main() {\n    measure { println("work") }\n}',
        '// avoid allocations in hot paths\nfun main() {\n    // prefer primitive loops over heavy mapping in tight loops\n    var sum = 0L\n    for (i in 1..1_000_000) sum += i\n    println(sum)\n    // useIntArray etc. to avoid boxing\n    val arr = IntArray(100) { it }\n    println(arr.sum())\n}',
        '// idiomatic best practices\nfun main() {\n    // prefer val over var\n    val config = mapOf("debug" to false)\n    // prefer data classes for DTOs\n    data class Config(val debug: Boolean)\n    // use scope functions sparingly\n    val msg = config["debug"]?.let { "debug on" } ?: "debug off"\n    println(msg)\n}',
        '// benchmarking\nfun main() {\n    val n = 1_000_000\n    val start = System.nanoTime()\n    val sum = (1..n).sumOf { it.toLong() }\n    val elapsedMs = (System.nanoTime() - start) / 1e6\n    println("sum=$sum in ${elapsedMs} ms")\n}',
    ],
}


if __name__ == '__main__':
    run_gen(LANGUAGE, 'kotlin', LESSONS, CODE, BASE)
