"""Curriculum specs for the Deep Learning and Computer Vision AI courses."""

SPECS = [
    # ────────────────────────────────────────────────────────────────
    # DEEP LEARNING
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'deep-learning',
        'code_lang': 'python',
        'refs': [
            ('PyTorch Documentation', 'https://pytorch.org/docs/stable/index.html', 'The official reference for the deep-learning framework used across this course.'),
            ('Deep Learning — Goodfellow, Bengio & Courville', 'https://www.deeplearningbook.org/', 'The canonical textbook on deep learning (free HTML).'),
            ('Dive into Deep Learning (d2l.ai)', 'https://d2l.ai/', 'Interactive deep-learning textbook with code in PyTorch.'),
            ('Practical Deep Learning — fast.ai', 'https://course.fast.ai/', 'A top-down course that gets you training models quickly.'),
            ('Attention Is All You Need', 'https://arxiv.org/abs/1706.03762', 'The paper that introduced the Transformer architecture.'),
        ],
        'lessons': [
            {
                'slug': 'dl-01-what-is-deep-learning',
                'title': 'What Is Deep Learning?',
                'desc': 'Why deep learning took over AI: representation learning, scale, and the hardware that made it possible.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': ['ML-01: What Is Machine Learning?'],
                'objs': [
                    'Define deep learning and representation learning',
                    'Explain why depth helps learn complex functions',
                    'Trace the hardware and data drivers of the deep learning boom',
                    'Identify tasks where deep learning excels',
                ],
                'samples': [
                    'import numpy as np\n\n# A deep net = many simple layers composed\nx = np.array([2.0])\nw1, b1 = 1.5, 0.1\nw2, b2 = 0.8, -0.2\nh = np.maximum(0, w1 * x + b1)   # hidden layer + ReLU\nout = w2 * h + b2                # output layer\nprint("output:", out)',
                    'tasks = ["image classification", "speech recognition", "language modeling", "game playing"]\nfor t in tasks:\n    print(f"- deep learning dominates: {t}")',
                    'import numpy as np\n\n# GPUs: thousands of cores, one instruction many data (SIMD)\nX = np.random.default_rng(0).normal(size=(1024, 1024))\nY = X @ X.T   # matrix multiply — the heart of neural nets\nprint("matmul shape:", Y.shape)',
                    'def why_deep():\n    return {"representation_learning": True, "scale": True, "compute": True}\n\nprint(why_deep())',
                ],
            },
            {
                'slug': 'dl-02-perceptron-and-linear-units',
                'title': 'The Perceptron & Linear Units',
                'desc': 'Start with the neuron: linear combination, threshold, and the step up to learnable weights.',
                'dur': '45 min', 'diff': 'beginner', 'prereq': ['DL-01: What Is Deep Learning?'],
                'objs': [
                    'Describe a perceptron as a weighted sum plus threshold',
                    'Implement a perceptron in NumPy',
                    'Explain the XOR limitation of a single layer',
                    'Motivate multiple layers',
                ],
                'samples': [
                    'import numpy as np\n\ndef perceptron(x, w, b):\n    return 1 if np.dot(x, w) + b > 0 else 0\n\nw = np.array([1.0, 1.0])\nprint("AND(1,1):", perceptron([1, 1], w, -1.5))\nprint("AND(1,0):", perceptron([1, 0], w, -1.5))',
                    'import numpy as np\n\n# Learning rule for a single neuron\nX = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])\ny = np.array([0, 0, 0, 1])   # AND\nw = np.zeros(2)\nb = 0.0\nfor _ in range(10):\n    for xi, yi in zip(X, y):\n        pred = 1 if np.dot(xi, w) + b > 0 else 0\n        w += (yi - pred) * xi\n        b += (yi - pred)\nprint("learned weights:", w, "bias:", b)',
                    'import numpy as np\n\n# XOR is not linearly separable — no single line works\nX = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])\ny = np.array([0, 1, 1, 0])\nprint("XOR needs hidden layers (nonlinearity)")',
                    'import numpy as np\n\n# Two-layer XOR solution\nw_hidden = np.array([[1.0, 1.0], [1.0, 1.0]])\nb_hidden = np.array([-0.5, -1.5])\nw_out = np.array([1.0, -2.0])\nb_out = 0.0\nh = np.maximum(0, X @ w_hidden.T + b_hidden)\nout = (h @ w_out + b_out > 0).astype(int)\nprint("XOR solved:", out)',
                ],
            },
            {
                'slug': 'dl-03-activation-functions',
                'title': 'Activation Functions',
                'desc': 'Nonlinearity is what makes deep networks expressive — sigmoid, tanh, ReLU and friends.',
                'dur': '50 min', 'diff': 'beginner', 'prereq': ['DL-02: The Perceptron & Linear Units'],
                'objs': [
                    'Explain why activation functions must be nonlinear',
                    'Compare sigmoid, tanh and ReLU',
                    'Understand the dying-ReLU problem',
                    'Pick activations for hidden versus output layers',
                ],
                'samples': [
                    'import numpy as np\n\nz = np.linspace(-5, 5, 5)\nprint("sigmoid:", np.round(1 / (1 + np.exp(-z)), 3))\nprint("tanh:", np.round(np.tanh(z), 3))\nprint("relu:", np.round(np.maximum(0, z), 3))',
                    'import numpy as np\n\n# ReLU sparsity: negative inputs become exactly zero\nz = np.array([-2.0, -0.5, 0.0, 1.0, 3.0])\nprint(np.maximum(0, z))',
                    'import numpy as np\n\n# Dying ReLU: a large negative bias can kill a unit forever\nz = np.array([-100.0, -99.0])\nprint("outputs:", np.maximum(0, z))  # gradient will be 0 too',
                    'import numpy as np\n\n# Output activations: softmax for classification\nlogits = np.array([2.0, 1.0, 0.1])\nexp = np.exp(logits - logits.max())\nprobs = exp / exp.sum()\nprint("softmax:", probs.round(3))',
                ],
            },
            {
                'slug': 'dl-04-forward-propagation',
                'title': 'Forward Propagation',
                'desc': 'Push data through the network layer by layer and understand the shapes at every step.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['DL-03: Activation Functions'],
                'objs': [
                    'Trace activations through a small network',
                    'Write a NumPy forward pass for a 2-layer net',
                    'Verify tensor shapes with matrix multiplication rules',
                    'Explain the role of the final layer per task',
                ],
                'samples': [
                    'import numpy as np\n\ndef relu(x):\n    return np.maximum(0, x)\n\nX = np.array([[0.5, 0.2]])          # (1, 2)\nW1 = np.array([[0.4, -0.2, 0.1], [0.3, 0.1, -0.5]])\nb1 = np.array([0.0, 0.0, 0.0])\nh = relu(X @ W1 + b1)              # (1, 3)\nprint("hidden:", h)',
                    'import numpy as np\n\nW2 = np.array([[0.6], [-0.4], [0.2]])\nb2 = np.array([0.0])\nout = h @ W2 + b2                  # (1, 1)\nprint("output:", out)',
                    'import numpy as np\n\n# Shape checklist\nprint("X:", X.shape, "W1:", W1.shape, "-> h:", h.shape)\nprint("W2:", W2.shape, "-> out:", out.shape)',
                    'import numpy as np\n\n# Batched forward pass: many examples at once\nXb = np.random.default_rng(0).normal(size=(32, 2))\nhb = relu(Xb @ W1 + b1)\nprint("batched hidden:", hb.shape)',
                ],
            },
            {
                'slug': 'dl-05-backpropagation',
                'title': 'Backpropagation',
                'desc': 'The chain rule in action: propagate errors backward to compute gradients for every weight.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['DL-04: Forward Propagation'],
                'objs': [
                    'Explain the chain rule as gradient routing',
                    'Derive the local gradients for common layers',
                    'Implement backprop for a 2-layer net',
                    'Use autograd instead of hand-written derivatives',
                ],
                'samples': [
                    'import numpy as np\n\n# Chain rule: dL/dw = dL/dy * dy/dh * dh/dw\nx = np.array([1.0])\ny_true = np.array([0.0])\nw = np.array([0.5])\ny_pred = w * x\nloss = 0.5 * (y_pred - y_true) ** 2\ndL_dy = y_pred - y_true\ndL_dw = dL_dy * x\nprint("gradient:", dL_dw)',
                    'import numpy as np\n\n# Full 2-layer backprop (regression)\nX = np.array([[0.2, 0.5]])\ny = np.array([[0.8]])\nW1 = np.random.default_rng(0).normal(size=(2, 3)) * 0.5\nW2 = np.random.default_rng(1).normal(size=(3, 1)) * 0.5\nh = np.maximum(0, X @ W1)\nout = h @ W2\ndL_dout = out - y\ndL_dW2 = h.T @ dL_dout\ndL_dh = dL_dout @ W2.T\ndL_dW1 = X.T @ (dL_dh * (h > 0))\nprint("dW2:", dL_dW2.ravel().round(3))\nprint("dW1:", dL_dW1.round(3))',
                    'import torch\n\n# Autograd does the chain rule for you\nw = torch.tensor([0.5], requires_grad=True)\nx = torch.tensor([1.0])\ny = torch.tensor([0.0])\nloss = 0.5 * (w * x - y) ** 2\nloss.backward()\nprint("autograd dL/dw:", w.grad)',
                    'import torch\n\nx = torch.randn(4, 2, requires_grad=True)\ny = (x ** 2).sum()\ny.backward()\nprint("grad shape:", x.grad.shape)',
                ],
            },
            {
                'slug': 'dl-06-loss-functions',
                'title': 'Loss Functions',
                'desc': 'Pick the right objective: MSE for regression, cross-entropy for classification, and why it matters.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['DL-04: Forward Propagation'],
                'objs': [
                    'Compute MSE and MAE for regression',
                    'Explain cross-entropy for classification',
                    'Understand why cross-entropy pairs with softmax',
                    'Handle class imbalance in the loss',
                ],
                'samples': [
                    'import torch\nimport torch.nn.functional as F\n\npred = torch.tensor([2.5, 0.0, 2.0])\ntarget = torch.tensor([2.0, 0.0, 2.0])\nprint("MSE:", F.mse_loss(pred, target))',
                    'import torch\nimport torch.nn.functional as F\n\nlogits = torch.tensor([[2.0, 1.0, 0.1]])\ntarget = torch.tensor([0])\nprint("CE:", F.cross_entropy(logits, target))',
                    'import torch\nimport torch.nn.functional as F\n\n# Why cross-entropy: log softmax is numerically stable\nlogits = torch.tensor([[1000.0, 0.0]])\nprint("stable probs:", torch.softmax(logits, dim=-1))',
                    'import torch\nimport torch.nn.functional as F\n\n# Class weights push the model to care about rare classes\nlogits = torch.tensor([[1.0, -1.0]])\ntarget = torch.tensor([1])\nprint("weighted CE:", F.cross_entropy(logits, target, weight=torch.tensor([1.0, 5.0])))',
                ],
            },
            {
                'slug': 'dl-07-optimizers',
                'title': 'Optimizers: SGD, Momentum & Adam',
                'desc': 'From plain SGD to Adam — how optimizers navigate loss landscapes and converge faster.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DL-05: Backpropagation'],
                'objs': [
                    'Implement an SGD update step',
                    'Explain momentum',
                    'Use Adam and understand its adaptive rates',
                    'Tune learning rate and weight decay',
                ],
                'samples': [
                    'import torch\nimport torch.nn as nn\n\nparam = nn.Parameter(torch.tensor([2.0]))\nopt = torch.optim.SGD([param], lr=0.1)\nloss = (param - 1.0) ** 2\nloss.backward()\nopt.step()\nprint("after step:", param.item())',
                    'import torch\n\nparam = nn.Parameter(torch.tensor([2.0]))\nopt = torch.optim.SGD([param], lr=0.1, momentum=0.9)\nfor _ in range(5):\n    opt.zero_grad()\n    ((param - 1.0) ** 2).backward()\n    opt.step()\nprint("with momentum:", round(param.item(), 3))',
                    'import torch\n\nparam = nn.Parameter(torch.tensor([2.0]))\nopt = torch.optim.Adam([param], lr=0.05)\nfor _ in range(20):\n    opt.zero_grad()\n    ((param - 1.0) ** 2).backward()\n    opt.step()\nprint("adam converged:", round(param.item(), 3))',
                    'import torch\nimport torch.nn as nn\n\nmodel = nn.Linear(4, 2)\nopt = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=0.01)\nprint("param groups:", len(opt.param_groups), "| lr:", opt.param_groups[0]["lr"])',
                ],
            },
            {
                'slug': 'dl-08-pytorch-tensors-and-autograd',
                'title': 'PyTorch Tensors & Autograd',
                'desc': 'The PyTorch fundamentals: tensors, dtypes, devices, and the autograd graph.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DL-05: Backpropagation'],
                'objs': [
                    'Create and manipulate tensors',
                    'Move tensors between CPU and GPU',
                    'Explain the autograd computation graph',
                    'Control gradient tracking with no_grad',
                ],
                'samples': [
                    'import torch\n\nx = torch.arange(12).reshape(3, 4)\nprint(x)\nprint("dtype:", x.dtype, "device:", x.device)',
                    'import torch\n\nif torch.cuda.is_available():\n    x = torch.ones(3).cuda()\n    print("on GPU:", x.device)\nelse:\n    print("CUDA unavailable — CPU only")',
                    'import torch\n\nx = torch.tensor([1.0, 2.0], requires_grad=True)\ny = (x ** 2).sum()\ny.backward()\nprint("grads:", x.grad)  # 2 * x',
                    'import torch\n\nx = torch.randn(1000, 1000, requires_grad=True)\nwith torch.no_grad():\n    y = x * 2   # no graph, fast, no memory\nprint("requires_grad:", y.requires_grad)',
                ],
            },
            {
                'slug': 'dl-09-building-an-mlp-in-pytorch',
                'title': 'Building an MLP in PyTorch',
                'desc': 'Assemble a multi-layer perceptron with nn.Module, layers and activations — the skeleton of every modern net.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DL-08: PyTorch Tensors & Autograd'],
                'objs': [
                    'Define a model with nn.Module',
                    'Stack Linear layers and activations',
                    'Understand parameter registration',
                    'Build a classifier for a small dataset',
                ],
                'samples': [
                    'import torch\nimport torch.nn as nn\n\nclass MLP(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Sequential(\n            nn.Linear(784, 128),\n            nn.ReLU(),\n            nn.Linear(128, 10),\n        )\n    def forward(self, x):\n        return self.net(x)\n\nmodel = MLP()\nprint(model)',
                    'import torch\n\nx = torch.randn(8, 784)\nprint("logits:", model(x).shape)  # (8, 10)',
                    'import torch\n\nprint("params:", sum(p.numel() for p in model.parameters()))',
                    'import torch\nimport torch.nn as nn\n\nclass DeepMLP(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.stack = nn.Sequential(\n            nn.Linear(64, 256), nn.ReLU(), nn.Dropout(0.2),\n            nn.Linear(256, 256), nn.ReLU(), nn.Dropout(0.2),\n            nn.Linear(256, 1),\n        )\n    def forward(self, x):\n        return self.stack(x)\n\nprint("deep net ready")',
                ],
            },
            {
                'slug': 'dl-10-the-training-loop',
                'title': 'The Training Loop',
                'desc': 'Write the loop that every training run shares: batches, forward, loss, backward, step.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DL-09: Building an MLP in PyTorch'],
                'objs': [
                    'Write a complete training loop',
                    'Create DataLoaders with shuffling and batching',
                    'Track loss per epoch',
                    'Evaluate on a validation set',
                ],
                'samples': [
                    'import torch\nimport torch.nn as nn\nfrom torch.utils.data import DataLoader, TensorDataset\n\nX = torch.randn(200, 4)\ny = torch.randint(0, 2, (200,))\ndl = DataLoader(TensorDataset(X, y), batch_size=32, shuffle=True)\nprint("batches:", len(dl))',
                    'import torch\nimport torch.nn as nn\n\nmodel = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 2))\nopt = torch.optim.Adam(model.parameters(), lr=1e-3)\nloss_fn = nn.CrossEntropyLoss()\nfor epoch in range(3):\n    for xb, yb in dl:\n        opt.zero_grad()\n        loss = loss_fn(model(xb), yb)\n        loss.backward()\n        opt.step()\n    print(f"epoch {epoch}: loss {loss.item():.3f}")',
                    'import torch\n\n# Shuffling matters: keep order from leaking into the model\nfrom torch.utils.data import DataLoader\nprint("shuffle=True -> unbiased batches")',
                    'import torch\nimport torch.nn as nn\n\n# Validation: no_grad + eval mode\nmodel = nn.Sequential(nn.Linear(4, 2))\nmodel.eval()\nwith torch.no_grad():\n    acc = (model(X[:16]).argmax(1) == y[:16]).float().mean()\nprint("val accuracy:", round(acc.item(), 3))',
                ],
            },
            {
                'slug': 'dl-11-regularization-for-deep-learning',
                'title': 'Regularization for Deep Learning',
                'desc': 'Dropout, weight decay, early stopping and data augmentation — fight overfitting without shrinking capacity.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-10: The Training Loop'],
                'objs': [
                    'Explain dropout as ensemble-like averaging',
                    'Apply weight decay (L2) with AdamW',
                    'Use early stopping honestly',
                    'Compare regularization techniques',
                ],
                'samples': [
                    'import torch.nn as nn\n\nmodel = nn.Sequential(\n    nn.Linear(64, 128), nn.ReLU(), nn.Dropout(0.5),\n    nn.Linear(128, 10),\n)\nprint("dropout applied after first hidden layer")',
                    'import torch\n\nparam = torch.nn.Parameter(torch.tensor([1.0]))\nopt = torch.optim.AdamW([param], lr=1e-3, weight_decay=0.01)\nprint("AdamW weight_decay:", opt.param_groups[0]["weight_decay"])',
                    'import torch\n\nbest = float("inf")\npatience, wait = 5, 0\nfor epoch in range(50):\n    val_loss = 0.5 + 0.05 * epoch   # placeholder: worsening after overfit\n    if val_loss < best:\n        best, wait = val_loss, 0\n    else:\n        wait += 1\n        if wait >= patience:\n            print(f"early stop at epoch {epoch}")\n            break',
                    'from torchvision import transforms\n\n# Data augmentation: cheap regularization for images\naug = transforms.Compose([\n    transforms.RandomHorizontalFlip(),\n    transforms.RandomRotation(10),\n    transforms.ToTensor(),\n])\nprint("augmentation pipeline ready")',
                ],
            },
            {
                'slug': 'dl-12-convolutional-networks',
                'title': 'Convolutional Networks',
                'desc': 'Why convolutions beat dense layers for images: local structure, weight sharing, and translation invariance.',
                'dur': '60 min', 'diff': 'intermediate', 'prereq': ['DL-10: The Training Loop'],
                'objs': [
                    'Explain convolution and pooling',
                    'Build a CNN with nn.Conv2d',
                    'Compute output shapes',
                    'Train a small CNN on MNIST',
                ],
                'samples': [
                    'import torch\nimport torch.nn as nn\n\nconv = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3, padding=1)\nx = torch.randn(4, 1, 28, 28)\nprint("conv out:", conv(x).shape)   # (4, 16, 28, 28)',
                    'import torch.nn as nn\n\npool = nn.MaxPool2d(2)\nprint("pooled:", pool(torch.randn(4, 16, 28, 28)).shape)  # 14x14',
                    'import torch\nimport torch.nn as nn\n\nclass TinyCNN(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.features = nn.Sequential(\n            nn.Conv2d(1, 16, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n            nn.Conv2d(16, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n        )\n        self.head = nn.Linear(32 * 7 * 7, 10)\n    def forward(self, x):\n        return self.head(self.features(x).flatten(1))\n\nmodel = TinyCNN()\nprint(model(torch.randn(2, 1, 28, 28)).shape)',
                    'import torch.nn as nn\n\n# Pooling gives local translation invariance\nprint("MaxPool2d(2) halves spatial dims, keeps channels")',
                ],
            },
            {
                'slug': 'dl-13-cnn-architectures',
                'title': 'Classic CNN Architectures',
                'desc': 'LeNet, VGG, ResNet — the ideas (depth, skip connections) that shaped modern vision models.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-12: Convolutional Networks'],
                'objs': [
                    'Trace LeNet and VGG design patterns',
                    'Explain residual/skip connections',
                    'Understand why depth needs ResNets',
                    'Load a pretrained ResNet from torchvision',
                ],
                'samples': [
                    'import torchvision.models as models\n\nresnet = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)\nprint(resnet)',
                    'import torch\n\nx = torch.randn(2, 3, 224, 224)\nprint("resnet out:", resnet(x).shape)  # (2, 1000)',
                    'import torch.nn as nn\n\n# A residual block: y = F(x) + x\nclass ResidualBlock(nn.Module):\n    def __init__(self, dim):\n        super().__init__()\n        self.f = nn.Sequential(nn.Conv2d(dim, dim, 3, padding=1), nn.ReLU(), nn.Conv2d(dim, dim, 3, padding=1))\n    def forward(self, x):\n        return nn.functional.relu(self.f(x) + x)',
                    'import torchvision.models as models\n\nvgg = models.vgg16(weights=models.VGG16_Weights.DEFAULT)\nprint("vgg conv layers:", len(list(vgg.features)))',
                ],
            },
            {
                'slug': 'dl-14-transfer-learning',
                'title': 'Transfer Learning',
                'desc': 'Stand on the shoulders of pretrained models: freeze features, swap the head, and fine-tune.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-13: Classic CNN Architectures'],
                'objs': [
                    'Explain feature reuse across tasks',
                    'Freeze layers and replace the classifier head',
                    'Fine-tune with a low learning rate',
                    'Avoid catastrophic forgetting',
                ],
                'samples': [
                    'import torchvision.models as models\nimport torch.nn as nn\n\nbackbone = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)\nbackbone.fc = nn.Linear(backbone.fc.in_features, 2)  # swap head\nprint(backbone.fc)',
                    'import torch\n\nfor p in backbone.parameters():\n    p.requires_grad = False\nfor p in backbone.fc.parameters():\n    p.requires_grad = True\nprint("frozen except head")',
                    'import torch\n\n# Fine-tune with a small learning rate\nopt = torch.optim.Adam(filter(lambda p: p.requires_grad, backbone.parameters()), lr=1e-4)\nprint("trainable params:", sum(p.numel() for p in backbone.parameters() if p.requires_grad))',
                    'import torch\n\n# Progressive unfreezing: start with head, then thaw blocks\nprint("fine-tune strategy: head first, then last blocks")',
                ],
            },
            {
                'slug': 'dl-15-recurrent-networks',
                'title': 'Recurrent Neural Networks',
                'desc': 'Process sequences with a hidden state that carries context through time.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-10: The Training Loop'],
                'objs': [
                    'Explain the recurrent hidden state',
                    'Build an RNN cell in PyTorch',
                    'Describe backpropagation through time',
                    'Know why plain RNNs struggle with long sequences',
                ],
                'samples': [
                    'import torch.nn as nn\n\nrnn = nn.RNN(input_size=8, hidden_size=16, batch_first=True)\nx = torch.randn(4, 10, 8)   # batch=4, seq=10, feat=8\nout, h = rnn(x)\nprint("outputs:", out.shape, "final hidden:", h.shape)',
                    'import torch\n\n# Hidden state is passed step by step — a rolling memory\nh = torch.zeros(1, 4, 16)\nfor t in range(10):\n    _, h = rnn(x[:, t:t+1], h)\nprint("final hidden after 10 steps:", h.shape)',
                    'import torch.nn as nn\n\nclass SimpleRNN(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.rnn = nn.RNN(8, 16, batch_first=True)\n        self.head = nn.Linear(16, 1)\n    def forward(self, x):\n        out, _ = self.rnn(x)\n        return self.head(out[:, -1])   # use last step',
                    'import torch\n\n# Vanishing gradients: repeated tanh shrinks signal\nimport math\nh = 1.0\nfor _ in range(20):\n    h = math.tanh(h)\nprint("after 20 steps:", h)',
                ],
            },
            {
                'slug': 'dl-16-lstm-and-gru',
                'title': 'LSTM & GRU',
                'desc': 'Gated memory cells that actually remember — the fixes that made sequence modeling practical.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['DL-15: Recurrent Neural Networks'],
                'objs': [
                    'Explain the LSTM cell (forget, input, output gates)',
                    'Use nn.LSTM and nn.GRU',
                    'Bidirectional processing',
                    'Choose RNN variants by task',
                ],
                'samples': [
                    'import torch.nn as nn\n\nlstm = nn.LSTM(input_size=8, hidden_size=32, batch_first=True)\nx = torch.randn(4, 12, 8)\nout, (h, c) = lstm(x)\nprint("out:", out.shape, "hidden:", h.shape, "cell:", c.shape)',
                    'import torch.nn as nn\n\ngru = nn.GRU(input_size=8, hidden_size=32, batch_first=True)\nout, h = gru(torch.randn(4, 12, 8))\nprint("gru out:", out.shape)',
                    'import torch.nn as nn\n\nbi = nn.LSTM(8, 16, bidirectional=True, batch_first=True)\nout, _ = bi(torch.randn(4, 12, 8))\nprint("bidirectional out:", out.shape)  # 2 * hidden',
                    'import torch.nn as nn\n\nclass LSTMClassifier(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.lstm = nn.LSTM(16, 32, batch_first=True)\n        self.head = nn.Linear(32, 2)\n    def forward(self, x):\n        out, _ = self.lstm(x)\n        return self.head(out[:, -1])\n\nprint("LSTM classifier ready")',
                ],
            },
            {
                'slug': 'dl-17-transformers',
                'title': 'Transformers',
                'desc': 'The architecture behind modern AI: self-attention, positional encoding, and parallelized sequence processing.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['DL-16: LSTM & GRU'],
                'objs': [
                    'Explain self-attention in one sentence',
                    'Compute attention weights with scaled dot products',
                    'Understand multi-head attention and position encodings',
                    'Use nn.TransformerEncoder',
                ],
                'samples': [
                    'import torch\nimport torch.nn.functional as F\n\nQ = torch.randn(4, 8)   # 4 tokens, 8-dim\nK = torch.randn(4, 8)\nV = torch.randn(4, 8)\nscores = Q @ K.T / (8 ** 0.5)\nweights = F.softmax(scores, dim=-1)\nout = weights @ V\nprint("attention out:", out.shape)',
                    'import torch\n\n# Scaled dot-product: scale prevents softmax saturation\nimport math\nlogits = torch.randn(10, 10)\nprint("scaled:", (logits / math.sqrt(10)).std().round(3))',
                    'import torch.nn as nn\n\nencoder = nn.TransformerEncoderLayer(d_model=64, nhead=4, batch_first=True)\nx = torch.randn(2, 20, 64)   # batch, seq, dim\nprint("encoded:", encoder(x).shape)',
                    'import torch.nn as nn\n\nclass TinyTransformer(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.emb = nn.Embedding(100, 64)\n        self.layers = nn.TransformerEncoder(nn.TransformerEncoderLayer(64, 4, batch_first=True), num_layers=2)\n        self.head = nn.Linear(64, 100)\n    def forward(self, ids):\n        return self.head(self.layers(self.emb(ids)))\n\nprint("tiny transformer:", TinyTransformer()(torch.randint(0, 100, (2, 10))).shape)',
                ],
            },
            {
                'slug': 'dl-18-attention-mechanisms',
                'title': 'Attention Mechanisms',
                'desc': 'Query-key-value attention, multi-head splits, and how attention replaced recurrence.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-17: Transformers'],
                'objs': [
                    'Explain Q, K, V roles',
                    'Implement multi-head attention',
                    'Read attention maps as interpretability',
                    'Describe the attention-memory analogy',
                ],
                'samples': [
                    'import torch\nimport torch.nn as nn\n\nmha = nn.MultiheadAttention(embed_dim=64, num_heads=4, batch_first=True)\nx = torch.randn(2, 12, 64)\nout, attn = mha(x, x, x)\nprint("out:", out.shape, "attention map:", attn.shape)',
                    'import torch\n\n# Attention as soft lookup: weights sum to 1 per query\nattn = torch.softmax(torch.randn(12, 12), dim=-1)\nprint("row sums ~ 1:", attn.sum(-1).round(3)[:3])',
                    'import torch.nn as nn\n\n# Head splitting: each head attends to different patterns\nprint("num_heads=4 -> 4 parallel attention subspaces")',
                    'import torch\n\n# Causal mask: tokens can only attend to the past\nmask = torch.triu(torch.ones(8, 8), diagonal=1).bool()\nprint("causal mask row 3 sees:", (~mask[3]).nonzero().flatten().tolist())',
                ],
            },
            {
                'slug': 'dl-19-training-at-scale',
                'title': 'Training at Scale',
                'desc': 'GPUs, mixed precision, data loaders and distributed training — the practical side of big models.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-17: Transformers'],
                'objs': [
                    'Move training to GPU with .to(device)',
                    'Use mixed precision (AMP)',
                    'Speed up data loading with DataLoader workers',
                    'Explain data parallelism across GPUs',
                ],
                'samples': [
                    'import torch\n\ndevice = "cuda" if torch.cuda.is_available() else "cpu"\nmodel = model.to(device)\nxb = xb.to(device)\nprint("training on:", device)',
                    'import torch\n\n# Mixed precision: fp16 forward, fp32 master weights\nscaler = torch.amp.GradScaler("cuda")\nprint("AMP scaler ready")',
                    'from torch.utils.data import DataLoader\n\ndl = DataLoader(dataset, batch_size=64, num_workers=4, pin_memory=True, shuffle=True)\nprint("workers:", dl.num_workers)',
                    'import torch.nn as nn\n\nmodel = nn.DataParallel(model)\nprint("data-parallel:", len(model.device_ids), "GPUs")',
                ],
            },
            {
                'slug': 'dl-20-evaluating-deep-models',
                'title': 'Evaluating Deep Learning Models',
                'desc': 'Accuracy is not enough: confusion matrices, calibration, and failure-case analysis for neural nets.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['DL-14: Transfer Learning'],
                'objs': [
                    'Evaluate classifiers with precision/recall per class',
                    'Inspect failure cases systematically',
                    'Check calibration of probabilities',
                    'Track experiments with metrics logging',
                ],
                'samples': [
                    'from sklearn.metrics import classification_report\n\nimport torch\npreds = torch.randint(0, 3, (100,))\ntrue = torch.randint(0, 3, (100,))\nprint(classification_report(true.numpy(), preds.numpy(), target_names=["a", "b", "c"]))',
                    'import torch\n\n# Find the worst failures for human review\nprobs, idx = torch.topk(torch.rand(50, 10), k=2, dim=-1)\nprint("top-2 per sample (for error analysis)")',
                    'from sklearn.calibration import calibration_curve\n\nprint("calibration: bins of predicted prob vs observed freq")',
                    'import torch\n\n# Log everything: each run becomes comparable\nrun = {"model": "resnet18", "acc": 0.93, "val_loss": 0.31}\nprint(run)',
                ],
            },
            {
                'slug': 'dl-21-roadmap',
                'title': 'Deep Learning Roadmap',
                'desc': 'Synthesize the course: choose a specialization (vision, NLP, generative), and plan real training projects.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['DL-20: Evaluating Deep Learning Models'],
                'objs': [
                    'Choose a deep learning specialization path',
                    'Plan projects that require real GPUs',
                    'Connect to computer vision and NLP courses',
                    'Track new architectures responsibly',
                ],
                'samples': [
                    'paths = {\n    "vision": "next: Computer Vision course",\n    "text": "next: NLP course",\n    "generative": "next: Generative AI course",\n}\nfor area, next_step in paths.items():\n    print(f"{area:10} -> {next_step}")',
                    'project_plan = {\n    1: "train MNIST from scratch",\n    2: "fine-tune a pretrained model on custom data",\n    3: "reproduce one paper result",\n}\nprint(project_plan)',
                    'import torch\n\nprint("torch", torch.__version__, "| cuda", torch.cuda.is_available())',
                    'reading_list = ["d2l.ai", "papers with code", "distill", "fast.ai"]\nprint("follow:", ", ".join(reading_list))',
                ],
            },
        ],
    },

    # ────────────────────────────────────────────────────────────────
    # COMPUTER VISION
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'computer-vision',
        'code_lang': 'python',
        'refs': [
            ('OpenCV Documentation', 'https://docs.opencv.org/4.x/index.html', 'The reference for classic image processing in Python.'),
            ('PyTorch Vision Docs', 'https://pytorch.org/vision/stable/index.html', 'Datasets, transforms and model zoo for vision.'),
            ('Stanford CS231n', 'http://cs231n.stanford.edu/', 'The classic university course on CNNs for visual recognition.'),
            ('YOLO Papers & Implementations', 'https://docs.ultralytics.com/', 'Real-time object detection with YOLOv8 (Ultralytics).'),
            ('Torchvision Models', 'https://pytorch.org/vision/stable/models.html', 'Pretrained model catalog for transfer learning.'),
        ],
        'lessons': [
            {
                'slug': 'cv-01-what-is-computer-vision',
                'title': 'What Is Computer Vision?',
                'desc': 'The field, the tasks, and the datasets that drive progress in visual intelligence.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': ['DL-01: What Is Deep Learning?'],
                'objs': [
                    'Define computer vision and its core tasks',
                    'List the landmark datasets and benchmarks',
                    'Contrast classic and deep approaches',
                    'Identify real-world vision applications',
                ],
                'samples': [
                    'tasks = {\n    "classification": "what is in the image?",\n    "detection": "where are the objects?",\n    "segmentation": "which pixels belong to what?",\n    "pose": "where is the person\'s skeleton?",\n}\nfor task, q in tasks.items():\n    print(f"{task:14} {q}")',
                    'from torchvision import datasets\n\nprint("MNIST classes:", len(datasets.MNIST("data", download=True, train=True).classes))',
                    'import torch\n\n# Images are tensors: (C, H, W) in torch\nimg = torch.zeros(3, 224, 224)\nprint("channels, height, width:", img.shape)',
                    'apps = ["self-driving", "medical imaging", "retail checkout", "phone camera", "AR filters"]\nfor a in apps:\n    print(f"- {a}")',
                ],
            },
            {
                'slug': 'cv-02-image-representation',
                'title': 'Image Representation',
                'desc': 'Pixels, channels, color spaces and the tensor layouts every vision library uses.',
                'dur': '50 min', 'diff': 'beginner', 'prereq': ['CV-01: What Is Computer Vision?'],
                'objs': [
                    'Describe an image as a tensor of pixels',
                    'Understand RGB and grayscale channels',
                    'Convert between HWC and CHW layouts',
                    'Normalize images for model input',
                ],
                'samples': [
                    'import numpy as np\n\nimg = np.zeros((4, 4, 3), dtype=np.uint8)  # HWC\nimg[1, 1] = [255, 0, 0]  # a red pixel\nprint("pixel (1,1):", img[1, 1])',
                    'import cv2\n\ngray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)\nprint("grayscale shape:", gray.shape)',
                    'import torch\n\nx = torch.tensor(img)  # (H, W, C)\nchw = x.permute(2, 0, 1)  # (C, H, W)\nprint("torch layout:", chw.shape)',
                    'from torchvision import transforms\n\nt = transforms.Compose([\n    transforms.ToTensor(),\n    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),\n])\nprint("normalization pipeline ready")',
                ],
            },
            {
                'slug': 'cv-03-image-processing',
                'title': 'Image Processing Fundamentals',
                'desc': 'Convolutions, blur, edges and thresholds — the classic toolbox that still powers pipelines today.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['CV-02: Image Representation'],
                'objs': [
                    'Explain 2D convolution on images',
                    'Apply blur and sharpening filters',
                    'Detect edges with Sobel/Canny',
                    'Threshold and morph images',
                ],
                'samples': [
                    'import cv2\nimport numpy as np\n\nimg = np.full((8, 8), 50, dtype=np.uint8)\nimg[3:5, 3:5] = 200\nblurred = cv2.GaussianBlur(img, (3, 3), 0)\nprint("blurred center:", blurred[3:5, 3:5])',
                    'import cv2\n\n# Edge detection\nedges = cv2.Canny(img, 50, 150)\nprint("edges shape:", edges.shape)',
                    'import cv2\n\n# Simple box blur via convolution\nkernel = np.ones((3, 3), np.float32) / 9\nbox = cv2.filter2D(img, -1, kernel)\nprint("box-blurred:", box)',
                    'import cv2\n\n# Thresholding for masks\n_, mask = cv2.threshold(img, 100, 255, cv2.THRESH_BINARY)\nprint("mask unique values:", np.unique(mask))',
                ],
            },
            {
                'slug': 'cv-04-image-augmentation',
                'title': 'Image Augmentation',
                'desc': 'Synthesize training variety: flips, rotations, crops and color jitter to make models robust.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['CV-02: Image Representation'],
                'objs': [
                    'Explain why augmentation regularizes vision models',
                    'Apply geometric and photometric transforms',
                    'Build a torchvision augmentation pipeline',
                    'Avoid augmentations that break label meaning',
                ],
                'samples': [
                    'from torchvision import transforms\n\nt = transforms.Compose([\n    transforms.RandomHorizontalFlip(),\n    transforms.RandomRotation(15),\n    transforms.ColorJitter(brightness=0.2, contrast=0.2),\n    transforms.ToTensor(),\n])\nprint("augmentation pipeline ready")',
                    'from torchvision import transforms\n\ncrop = transforms.RandomResizedCrop(224, scale=(0.7, 1.0))\nprint("random-resized-crop for scale invariance")',
                    'import torchvision.transforms.functional as F\nimport torch\n\nx = torch.rand(3, 32, 32)\nflipped = F.hflip(x)\nprint("flip keeps shape:", flipped.shape)',
                    'from torchvision import transforms\n\n# Label-preserving: never flip text or digits that flip meaning\nprint("rule: think about what the label means under each transform")',
                ],
            },
            {
                'slug': 'cv-05-image-classification',
                'title': 'Image Classification',
                'desc': 'The canonical vision task: train a classifier on MNIST/CIFAR and read the results.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DL-12: Convolutional Networks'],
                'objs': [
                    'Load a vision dataset with torchvision',
                    'Train a CNN classifier',
                    'Report per-class accuracy',
                    'Inspect misclassified examples',
                ],
                'samples': [
                    'from torchvision import datasets, transforms\n\ntrain = datasets.CIFAR10(\n    "data", train=True, download=True,\n    transform=transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))]),\n)\nprint("classes:", train.classes)',
                    'import torch\nimport torch.nn as nn\n\nmodel = nn.Sequential(\n    nn.Conv2d(3, 16, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n    nn.Conv2d(16, 32, 3, padding=1), nn.ReLU(), nn.MaxPool2d(2),\n    nn.Flatten(), nn.Linear(32 * 8 * 8, 10),\n)\nprint(model)',
                    'import torch\n\nx = torch.randn(4, 3, 32, 32)\nprint("logits:", model(x).shape)',
                    'import torch\n\n# Per-class accuracy matters more than a single number\npreds = torch.randint(0, 10, (1000,))\ntrue = torch.randint(0, 10, (1000,))\nacc = (preds == true).float().mean()\nprint("overall:", round(acc.item(), 3))',
                ],
            },
            {
                'slug': 'cv-06-cnns-for-vision',
                'title': 'CNNs for Vision',
                'desc': 'Architecture patterns that win on images: receptive fields, pooling, and depth.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['CV-05: Image Classification'],
                'objs': [
                    'Explain receptive fields',
                    'Stack conv-pool blocks deliberately',
                    'Use batch normalization',
                    'Tune for compute-bounded devices',
                ],
                'samples': [
                    'import torch.nn as nn\n\nblock = nn.Sequential(\n    nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),\n    nn.Conv2d(64, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(),\n    nn.MaxPool2d(2),\n)\nprint(block)',
                    'import torch\n\nx = torch.randn(2, 32, 32, 32)\nprint("block out:", block(x).shape)',
                    'import torch.nn as nn\n\n# Receptive field grows with depth and kernel size\nprint("3x3 stacks: deeper == wider effective view")',
                    'import torch.nn as nn\n\n# Global average pooling: robust spatial summary\ngap = nn.AdaptiveAvgPool2d(1)\nprint("GAP:", gap(torch.randn(2, 64, 8, 8)).shape)',
                ],
            },
            {
                'slug': 'cv-07-transfer-learning-for-vision',
                'title': 'Transfer Learning for Vision',
                'desc': 'Pretrained backbones are the default starting point — swap the head, keep the features.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-14: Transfer Learning'],
                'objs': [
                    'Load a torchvision backbone',
                    'Replace the classifier for custom classes',
                    'Fine-tune features selectively',
                    'Use augmentation with pretrained pipelines',
                ],
                'samples': [
                    'import torchvision.models as models\nimport torch.nn as nn\n\nm = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)\nm.fc = nn.Linear(m.fc.in_features, 3)\nprint(m.fc)',
                    'import torch\n\nfor p in m.parameters():\n    p.requires_grad = False\nfor p in m.fc.parameters():\n    p.requires_grad = True\nprint("head-only training")',
                    'from torchvision import transforms\n\n# Pretrained models expect ImageNet normalization\npre = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\nprint("use ImageNet stats")',
                    'import torch\n\n# Two-stage: train head, then unfreeze and fine-tune\nopt1 = torch.optim.Adam(m.fc.parameters(), lr=1e-3)\nprint("stage 1 optimizer ready")',
                ],
            },
            {
                'slug': 'cv-08-object-detection',
                'title': 'Object Detection',
                'desc': 'Bounding boxes and classes: two-stage detectors, single-shot detectors, and YOLO in practice.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['CV-07: Transfer Learning for Vision'],
                'objs': [
                    'Frame detection as boxes + classes',
                    'Explain anchor boxes and IoU',
                    'Compare two-stage and single-shot designs',
                    'Run YOLO with the Ultralytics library',
                ],
                'samples': [
                    'import torch\n\n# Detection output: (boxes, scores, class_ids)\nboxes = torch.tensor([[10, 10, 40, 40], [5, 5, 30, 30]])\nscores = torch.tensor([0.9, 0.4])\nprint("keep:", scores > 0.5)',
                    'import torch\n\ndef iou(a, b):\n    x1 = max(a[0], b[0]); y1 = max(a[1], b[1])\n    x2 = min(a[2], b[2]); y2 = min(a[3], b[3])\n    inter = max(0, x2 - x1) * max(0, y2 - y1)\n    area_a = (a[2] - a[0]) * (a[3] - a[1])\n    area_b = (b[2] - b[0]) * (b[3] - b[1])\n    return inter / (area_a + area_b - inter)\n\nprint("IoU:", round(iou((0, 0, 10, 10), (5, 5, 15, 15)), 2))',
                    'from ultralytics import YOLO\n\nmodel = YOLO("yolov8n.pt")   # pretrained nano\nprint("yolo model ready")',
                    'import torch\n\n# Non-max suppression removes duplicate boxes\nfrom torchvision.ops import nms\nboxes = torch.tensor([[10, 10, 40, 40], [12, 12, 42, 42], [80, 80, 120, 120]])\nscores = torch.tensor([0.9, 0.85, 0.7])\nkeep = nms(boxes, scores, iou_threshold=0.5)\nprint("kept boxes:", keep)',
                ],
            },
            {
                'slug': 'cv-09-semantic-segmentation',
                'title': 'Semantic Segmentation',
                'desc': 'Label every pixel: FCNs, U-Net, and the encoder-decoder design for pixel-level tasks.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['CV-08: Object Detection'],
                'objs': [
                    'Define semantic segmentation',
                    'Explain encoder-decoder architectures',
                    'Build a U-Net-style model',
                    'Evaluate with pixel accuracy and IoU',
                ],
                'samples': [
                    'import torch\n\n# Input (B, C, H, W) -> output (B, num_classes, H, W)\nx = torch.randn(2, 3, 128, 128)\nlogits = torch.randn(2, 5, 128, 128)\nprint("per-pixel class logits:", logits.shape)',
                    'import torch.nn as nn\n\n# Encoder-decoder: down then up, with skip connections\nprint("U-Net pattern: contract -> expand -> concatenate skips")',
                    'import torch\n\n# Pixel accuracy is easy to game; IoU is honest\npred = torch.randint(0, 2, (256, 256))\ntrue = torch.zeros(256, 256, dtype=torch.long)\ninter = ((pred == true) & (pred == 1)).sum()\nunion = ((pred == 1) | (true == 1)).sum()\nprint("IoU:", round(inter.item() / union.item(), 3))',
                    'from torchvision.models.segmentation import fcn_resnet50\n\nm = fcn_resnet50(weights=None, num_classes=3)\nprint(m)',
                ],
            },
            {
                'slug': 'cv-10-instance-segmentation',
                'title': 'Instance Segmentation',
                'desc': 'Separate each object, not just each class: Mask R-CNN and the mask-head idea.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['CV-09: Semantic Segmentation'],
                'objs': [
                    'Distinguish semantic from instance segmentation',
                    'Explain the Mask R-CNN two-stage design',
                    'Load a pretrained instance segmentation model',
                    'Evaluate masks with mask IoU',
                ],
                'samples': [
                    'from torchvision.models.detection import maskrcnn_resnet50_fpn\n\nm = maskrcnn_resnet50_fpn(weights=None, num_classes=91)\nprint("mask r-cnn ready")',
                    'import torch\n\n# Output: boxes, labels, scores, masks per instance\nout = {"boxes": torch.zeros(3, 4), "masks": torch.zeros(3, 1, 32, 32)}\nprint("per-instance masks:", out["masks"].shape)',
                    'import torch\n\n# Panoptic: semantic + instance merged into one label per pixel\nprint("panoptic segmentation unifies both tasks")',
                    'import torch\n\ndef mask_iou(a, b):\n    inter = (a & b).sum()\n    union = (a | b).sum()\n    return inter / union\n\na = torch.tensor([[True, True], [False, False]])\nb = torch.tensor([[True, False], [False, False]])\nprint("mask IoU:", round(mask_iou(a, b).item(), 2))',
                ],
            },
            {
                'slug': 'cv-11-pose-estimation',
                'title': 'Pose Estimation',
                'desc': 'Detect body keypoints and skeletons with heatmap-based and regression approaches.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['CV-09: Semantic Segmentation'],
                'objs': [
                    'Define keypoint detection and skeletons',
                    'Explain heatmap-based keypoint prediction',
                    'Use a pretrained pose model',
                    'Evaluate with PCK and OKS',
                ],
                'samples': [
                    'import torch\n\n# Keypoints as (x, y, visibility) per joint\nkps = torch.rand(17, 3)\nprint("COCO skeleton: 17 keypoints")',
                    'import torch\n\n# Heatmap: a Gaussian peak marks each joint location\nh = torch.zeros(64, 64)\nh[30, 40] = 1.0\nprint("heatmap peak at (30, 40)")',
                    'from torchvision.models.detection import keypointrcnn_resnet50_fpn\n\nm = keypointrcnn_resnet50_fpn(weights=None, num_classes=2)\nprint("keypoint R-CNN ready")',
                    'import torch\n\n# OKS: scale-aware keypoint similarity\nscale = 150.0\ndist = 5.0\noks = torch.exp(-(dist ** 2) / (2 * (scale * 0.05) ** 2))\nprint("OKS:", round(oks.item(), 3))',
                ],
            },
            {
                'slug': 'cv-12-opencv-fundamentals',
                'title': 'OpenCV Fundamentals',
                'desc': 'The industrial workhorse: reading, writing, resizing, drawing, and real-time camera capture.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['CV-03: Image Processing Fundamentals'],
                'objs': [
                    'Read and write images with OpenCV',
                    'Resize, crop and rotate images',
                    'Draw boxes and text for visualization',
                    'Capture frames from a webcam',
                ],
                'samples': [
                    'import cv2\n\nimg = cv2.imread("photo.jpg")\nprint("loaded:", None if img is None else img.shape)',
                    'import cv2\n\nsmall = cv2.resize(img, (640, 480))\nprint("resized:", small.shape)',
                    'import cv2\n\n# BGR ordering in OpenCV, RGB elsewhere\nprint("OpenCV uses BGR; convert with cvtColor")',
                    'import cv2\n\n# Draw a detection box\nimg = cv2.rectangle(img.copy(), (10, 10), (100, 100), (0, 255, 0), 2)\nprint("box drawn")',
                ],
            },
            {
                'slug': 'cv-13-feature-detection',
                'title': 'Feature Detection & Matching',
                'desc': 'Keypoints and descriptors: SIFT, ORB, and how image matching enables stitching and localization.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['CV-12: OpenCV Fundamentals'],
                'objs': [
                    'Explain keypoints and descriptors',
                    'Detect and match SIFT/ORB features',
                    'Filter matches with ratio tests',
                    'Use homography for alignment',
                ],
                'samples': [
                    'import cv2\n\nsift = cv2.SIFT_create()\nkp, des = sift.detectAndCompute(img, None)\nprint("keypoints:", len(kp), "descriptor dim:", des.shape)',
                    'import cv2\n\norb = cv2.ORB_create()\nkp2, des2 = orb.detectAndCompute(img, None)\nprint("ORB keypoints:", len(kp2))',
                    'import cv2\n\nbf = cv2.BFMatcher(cv2.NORM_L2)\nmatches = bf.knnMatch(des, des2, k=2)\ngood = [m for m, n in matches if m.distance < 0.75 * n.distance]\nprint("good matches:", len(good))',
                    'import cv2\n\n# Homography aligns matched points between two views\nprint("findHomography -> 3x3 transform for stitching")',
                ],
            },
            {
                'slug': 'cv-14-image-registration-and-stitching',
                'title': 'Image Registration & Stitching',
                'desc': 'Combine overlapping images into panoramas and align images across time or sensors.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['CV-13: Feature Detection & Matching'],
                'objs': [
                    'Explain registration as a geometric alignment problem',
                    'Match features across images',
                    'Estimate a homography with RANSAC',
                    'Warp and blend into a panorama',
                ],
                'samples': [
                    'import cv2\n\n# RANSAC rejects outlier matches\nH, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)\nprint("inliers:", mask.sum())',
                    'import cv2\n\n# Warp perspective of image A into image B\'s plane\nwarped = cv2.warpPerspective(img_a, H, (w, h))\nprint("warped:", warped.shape)',
                    'import cv2\n\n# Blend seam with feathering to hide edges\nprint("blend: weighted average along the seam")',
                    'import cv2\n\nstitcher = cv2.Stitcher_create()\nstatus, pano = stitcher.stitch([img_a, img_b])\nprint("stitch status:", status)',
                ],
            },
            {
                'slug': 'cv-15-video-analysis',
                'title': 'Video Analysis & Tracking',
                'desc': 'Optical flow, frame differencing, and object tracking across video streams.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['CV-12: OpenCV Fundamentals'],
                'objs': [
                    'Compute optical flow between frames',
                    'Detect motion with background subtraction',
                    'Track objects with trackers',
                    'Process video frames in a loop',
                ],
                'samples': [
                    'import cv2\n\ncap = cv2.VideoCapture(0)\nok, frame = cap.read()\nprint("frame:", frame.shape if ok else None)',
                    'import cv2\n\n# Sparse optical flow (Lucas-Kanade)\nflow = cv2.calcOpticalFlowFarneback(prev, cur, None, 0.5, 3, 15, 3, 5, 1.2, 0)\nprint("dense flow:", flow.shape)',
                    'import cv2\n\nsubtractor = cv2.createBackgroundSubtractorMOG2()\nfg = subtractor.apply(frame)\nprint("foreground mask unique:", set(fg.flatten().tolist()))',
                    'import cv2\n\ntracker = cv2.TrackerKCF_create()\nprint("tracker initialized; update per frame")',
                ],
            },
            {
                'slug': 'cv-16-face-recognition',
                'title': 'Face Detection & Recognition',
                'desc': 'Detect faces, embed them into vectors, and recognize identity — and respect the ethics of it.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['CV-07: Transfer Learning for Vision'],
                'objs': [
                    'Detect faces with cascades or deep detectors',
                    'Explain face embeddings',
                    'Compare identities with cosine similarity',
                    'Discuss privacy and bias considerations',
                ],
                'samples': [
                    'import cv2\n\ncascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")\nfaces = cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5)\nprint("faces found:", len(faces))',
                    'import numpy as np\n\ndef cosine_sim(a, b):\n    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))\n\na = np.array([1.0, 0.0])\nb = np.array([0.95, 0.05])\nprint("similarity:", round(cosine_sim(a, b), 3))',
                    'import torch\n\n# Face embedding: model outputs a fixed-size vector per face\nembedding = torch.randn(512)\nprint("embedding dim:", embedding.shape)',
                    'ethics = ["consent", "bias across demographics", "surveillance risk", "retention limits"]\nfor e in ethics:\n    print(f"- {e}")',
                ],
            },
            {
                'slug': 'cv-17-ocr-and-document-ai',
                'title': 'OCR & Document AI',
                'desc': 'Turn images of text into machine-readable text: Tesseract, PaddleOCR, and layout understanding.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['CV-03: Image Processing Fundamentals'],
                'objs': [
                    'Explain the OCR pipeline',
                    'Run Tesseract via pytesseract',
                    'Handle document layout and tables',
                    'Pair OCR with downstream NLP',
                ],
                'samples': [
                    'import pytesseract\nfrom PIL import Image\n\ntext = pytesseract.image_to_string(Image.open("receipt.png"))\nprint(text[:200])',
                    'import pytesseract\n\ndata = pytesseract.image_to_data(Image.open("page.png"), output_type=pytesseract.Output.DICT)\nprint("words:", len(data["text"]))',
                    'import cv2\n\n# Preprocessing helps OCR: grayscale + threshold\ngray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n_, th = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)\nprint("otsu threshold applied")',
                    'import pytesseract\n\nprint("OCR -> structured fields via regex or NLP")',
                ],
            },
            {
                'slug': 'cv-18-3d-vision',
                'title': '3D Vision',
                'desc': 'Depth, point clouds and stereo: how cameras recover the third dimension.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['CV-13: Feature Detection & Matching'],
                'objs': [
                    'Explain depth from stereo disparity',
                    'Read depth maps and point clouds',
                    'Use camera intrinsics for projection',
                    'Explore LiDAR fusion',
                ],
                'samples': [
                    'import numpy as np\n\n# Disparity: closer objects shift more between left/right\nfocal, baseline = 500.0, 0.12\ndisparity = 20.0\ndepth = focal * baseline / disparity\nprint("depth (m):", round(depth, 2))',
                    'import numpy as np\n\n# Project 3D point to pixel with intrinsics\nK = np.array([[500, 0, 320], [0, 500, 240], [0, 0, 1]])\npt3d = np.array([1.0, 2.0, 5.0])\npix = K @ pt3d / pt3d[2]\nprint("pixel:", pix[:2].round(1))',
                    'import open3d as o3d\n\npcd = o3d.geometry.PointCloud()\nprint("point cloud object ready")',
                    'import numpy as np\n\n# Depth maps as 2D arrays of distances\ndepth = np.zeros((240, 320))\nprint("depth map:", depth.shape)',
                ],
            },
            {
                'slug': 'cv-19-vision-transformers',
                'title': 'Vision Transformers (ViT)',
                'desc': 'Patch the image into tokens and let attention do the rest — the modern alternative to CNNs.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-17: Transformers'],
                'objs': [
                    'Explain patch embedding',
                    'Add position embeddings to patches',
                    'Use pretrained ViT models',
                    'Compare ViT and CNN trade-offs',
                ],
                'samples': [
                    'import torch\n\n# Image -> sequence of patches\nx = torch.randn(2, 3, 224, 224)\npatches = x.unfold(2, 16, 16).unfold(3, 16, 16)\nprint("patch grid:", patches.shape)',
                    'import torch.nn as nn\n\nproj = nn.Conv2d(3, 768, kernel_size=16, stride=16)\ntokens = proj(torch.randn(2, 3, 224, 224)).flatten(2).transpose(1, 2)\nprint("tokens:", tokens.shape)  # (2, 196, 768)',
                    'import torchvision.models as models\n\nvit = models.vit_b_16(weights=models.ViT_B_16_Weights.DEFAULT)\nprint(vit)',
                    'import torch\n\nprint("ViT: needs lots of data, excels at scale; CNNs win small-data")',
                ],
            },
            {
                'slug': 'cv-20-evaluating-vision-models',
                'title': 'Evaluating Vision Models',
                'desc': 'Benchmarks, metrics and failure analysis: accuracy, mAP, and per-class audits.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['CV-08: Object Detection'],
                'objs': [
                    'Compute mean average precision (mAP)',
                    'Audit per-class performance',
                    'Build confusion matrices for vision',
                    'Review failure cases systematically',
                ],
                'samples': [
                    'import torch\n\n# AP: area under the precision-recall curve per class\nprint("mAP = mean AP over classes and IoU thresholds")',
                    'import torch\n\ndef ap_at(preds, true):\n    # simplified AP: precision at rank where recall hits 1\n    return 1.0 if preds.sum() == true.sum() else 0.0\n\nprint("AP:", ap_at(torch.tensor([1, 0, 1]), torch.tensor([1, 1, 1])))',
                    'from sklearn.metrics import confusion_matrix\n\npred = torch.randint(0, 10, (500,)).numpy()\ntrue = torch.randint(0, 10, (500,)).numpy()\nprint("confusion matrix shape:", confusion_matrix(true, pred).shape)',
                    'import torch\n\n# Collect the worst mistakes for a human review slice\nmistakes = torch.where(pred != true)[0]\nprint("review these indices:", mistakes[:5])',
                ],
            },
            {
                'slug': 'cv-21-roadmap',
                'title': 'Computer Vision Roadmap',
                'desc': 'Synthesize the course into a plan: pick a specialization, build portfolio projects, and keep shipping.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['CV-20: Evaluating Vision Models'],
                'objs': [
                    'Choose a vision specialization (detection, segmentation, 3D)',
                    'Plan GPU-backed portfolio projects',
                    'Connect vision to generative AI and multimodal systems',
                    'Keep up with the field responsibly',
                ],
                'samples': [
                    'plan = {\n    1: "reimplement YOLO-style training on a custom dataset",\n    2: "deploy a segmentation model as an API",\n    3: "next: Generative AI for diffusion and VLMs",\n}\nprint(plan)',
                    'projects = ["car damage detection", "plant disease classifier", "document parser"]\nprint("portfolio:", ", ".join(projects))',
                    'import torch\n\nprint("torchvision", torch.__version__)\nprint("GPU available:", torch.cuda.is_available())',
                    'sources = ["paperswithcode", "CVPR", "Ultralytics docs", "Roboflow blog"]\nprint("follow:", ", ".join(sources))',
                ],
            },
        ],
    },
]
