"""Curriculum specs for the Data Science and Machine Learning AI courses."""

SPECS = [
    # ────────────────────────────────────────────────────────────────
    # DATA SCIENCE
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'data-science',
        'code_lang': 'python',
        'refs': [
            ('Python for Data Analysis — Wes McKinney', 'https://wesmckinney.com/book/', 'The definitive guide to pandas, NumPy and the PyData stack.'),
            ('Pandas User Guide', 'https://pandas.pydata.org/docs/user_guide/index.html', 'Official documentation for the pandas data-analysis library.'),
            ('The Elements of Statistical Learning', 'https://hastie.su.domains/ElemStatLearn/', 'The classic statistical-learning reference (free PDF).'),
            ('Kaggle Learn — Data Science', 'https://www.kaggle.com/learn', 'Hands-on micro-courses covering pandas, EDA and modeling.'),
            ('scikit-learn User Guide', 'https://scikit-learn.org/stable/user_guide.html', 'Authoritative guide to the Python machine-learning toolbox.'),
        ],
        'lessons': [
            {
                'slug': 'ds-01-what-is-data-science',
                'title': 'What Is Data Science?',
                'desc': 'Define data science, understand its core disciplines, and map the roles and workflow of a modern data team.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': [],
                'objs': [
                    'Define data science and contrast it with data analysis and statistics',
                    'Identify the roles in a modern data science team',
                    'Describe the data science workflow at a high level',
                    'Recognize the core tools and languages used across the field',
                ],
                'samples': [
                    'import numpy as np\nimport pandas as pd\n\nusers = pd.DataFrame({\n    "cohort": ["free", "pro", "team"],\n    "signups": [1200, 340, 95],\n    "revenue": [0.0, 19.99, 49.99],\n})\nprint(users)',
                    'pipeline = {\n    1: "ask the question",\n    2: "collect data",\n    3: "clean and wrangle",\n    4: "explore and visualize",\n    5: "model and evaluate",\n    6: "communicate results",\n}\nfor step, task in pipeline.items():\n    print(f"{step}. {task}")',
                    'def describe_role(role: str) -> str:\n    return f"{role} turns questions into data-driven decisions"\n\nprint(describe_role("data scientist"))\nprint(describe_role("ML engineer"))\nprint(describe_role("analytics engineer"))',
                    'import sys\nimport numpy as np\nimport pandas as pd\n\nprint(f"Python {sys.version_info.major}.{sys.version_info.minor}")\nprint(f"NumPy {np.__version__} | pandas {pd.__version__}")',
                ],
            },
            {
                'slug': 'ds-02-the-data-science-pipeline',
                'title': 'The Data Science Pipeline',
                'desc': 'Walk through the six stages of a data science project and learn where real projects fail — and why iteration matters.',
                'dur': '45 min', 'diff': 'beginner', 'prereq': ['DS-01: What Is Data Science?'],
                'objs': [
                    'Identify the six stages of the data science pipeline',
                    'Explain why iteration beats a linear flow',
                    'Map real project tasks onto pipeline stages',
                    'Anticipate the most common failure points',
                ],
                'samples': [
                    'stages = ["ask", "collect", "clean", "explore", "model", "communicate"]\n\n# A pipeline is a loop, not a line:\nfor stage in stages:\n    print(f"-> {stage}")\nprint("(then go back to the question and refine)")',
                    'import pandas as pd\n\nraw = pd.DataFrame({"id": [1, 2, 3], "price": ["9.99", "oops", "29.99"]})\n# Cleaning stage: coerce to numeric, keep track of what failed\nraw["price"] = pd.to_numeric(raw["price"], errors="coerce")\nprint(raw)',
                    'from sklearn.model_selection import train_test_split\n\nX = pd.DataFrame({"a": range(100), "b": range(100, 200)})\ny = pd.Series([i % 2 for i in range(100)])\nX_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)\nprint(f"train={len(X_tr)} test={len(X_te)}")',
                    'def estimate_hours(stage: str, data_quality: float) -> int:\n    """Stage effort grows when data is messy."""\n    base = {"collect": 2, "clean": 1, "model": 3}.get(stage, 1)\n    return int(base * (1 + (1 - data_quality)))\n\nprint("clean stage:", estimate_hours("clean", data_quality=0.4), "days")',
                ],
            },
            {
                'slug': 'ds-03-python-for-data-science',
                'title': 'Python for Data Science',
                'desc': 'The Python fundamentals every data scientist leans on: collections, comprehensions, file I/O, and reproducible notebooks.',
                'dur': '50 min', 'diff': 'beginner', 'prereq': ['DS-01: What Is Data Science?'],
                'objs': [
                    'Use lists, dicts and comprehensions fluently',
                    'Read and write CSV data with the standard library',
                    'Structure analysis code for reproducibility',
                    'Profile a small script to find slow operations',
                ],
                'samples': [
                    'prices = [9.99, 19.99, 29.99, 49.99]\ndoubled = [p * 2 for p in prices if p > 15]\ncounts = {p: prices.count(p) for p in set(prices)}\nprint(doubled)\nprint(counts)',
                    'import csv\nfrom io import StringIO\n\nrows = [["day", "users"], ["mon", 120], ["tue", 210]]\nbuf = StringIO()\nwriter = csv.writer(buf)\nwriter.writerows(rows)\nprint(buf.getvalue())\nreader = list(csv.reader(StringIO(buf.getvalue())))\nprint(reader[1])',
                    '# Reproducible structure: keep transforms in functions\nimport pandas as pd\n\ndef load(path: str) -> pd.DataFrame:\n    df = pd.read_csv(path)\n    df.columns = [c.strip().lower() for c in df.columns]\n    return df\n\n# load("users.csv")  # every analysis starts from one clean entry point',
                    'import time\n\ndef slow(n: int) -> int:\n    total = 0\n    for i in range(n):\n        total += i ** 2\n    return total\n\nt0 = time.perf_counter()\nslow(1_000_000)\nprint(f"took {time.perf_counter() - t0:.3f}s")',
                ],
            },
            {
                'slug': 'ds-04-numpy-arrays',
                'title': 'NumPy: Arrays & Vectorization',
                'desc': 'Master ndarrays, broadcasting and vectorized math — the engine under every serious data workflow.',
                'dur': '55 min', 'diff': 'beginner', 'prereq': ['DS-03: Python for Data Science'],
                'objs': [
                    'Create and reshape NumPy arrays',
                    'Use vectorized math instead of Python loops',
                    'Apply broadcasting rules correctly',
                    'Index, slice and mask arrays efficiently',
                ],
                'samples': [
                    'import numpy as np\n\na = np.arange(12).reshape(3, 4)\nprint(a)\nprint("shape:", a.shape, "dtype:", a.dtype)',
                    'import numpy as np\n\nvals = np.random.default_rng(42).normal(size=1_000_000)\n# Vectorized: one pass over the buffer, no Python loop\nmean = vals.mean()\nstd = vals.std()\nprint(f"mean={mean:.3f} std={std:.3f}")',
                    'import numpy as np\n\ncol = np.array([[1], [2], [3]])   # (3, 1)\nrow = np.array([10, 20, 30])     # (3,)\nresult = col + row                # broadcasts to (3, 3)\nprint(result)',
                    'import numpy as np\n\nx = np.linspace(0, 1, 100)\nmask = (x > 0.25) & (x < 0.75)\nprint("kept:", x[mask].size, "of", x.size)\nprint("first 5 kept:", x[mask][:5])',
                ],
            },
            {
                'slug': 'ds-05-pandas-dataframes',
                'title': 'Pandas: DataFrames & Series',
                'desc': 'Load, inspect, filter, group and merge tabular data with the most important library in data science.',
                'dur': '60 min', 'diff': 'beginner', 'prereq': ['DS-04: NumPy: Arrays & Vectorization'],
                'objs': [
                    'Load tabular data into a DataFrame',
                    'Inspect, filter and sort rows and columns',
                    'Group by and aggregate with split-apply-combine',
                    'Join datasets on keys',
                ],
                'samples': [
                    'import pandas as pd\n\ndf = pd.read_csv(\n    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"\n)\nprint(df.shape)\nprint(df.head(3))',
                    'import pandas as pd\n\ndf = pd.DataFrame({"species": ["A", "B", "A", "B"], "score": [1, 2, 3, 4]})\nprint(df[df["score"] > 2])\nprint(df.sort_values("score", ascending=False))',
                    'import pandas as pd\n\norders = pd.DataFrame({\n    "region": ["east", "west", "east", "west", "east"],\n    "revenue": [10, 20, 30, 40, 50],\n})\nsummary = orders.groupby("region")["revenue"].agg(["sum", "mean", "count"])\nprint(summary)',
                    'import pandas as pd\n\nusers = pd.DataFrame({"user_id": [1, 2, 3], "name": ["a", "b", "c"]})\norders = pd.DataFrame({"user_id": [2, 3, 4], "total": [50, 75, 100]})\njoined = users.merge(orders, on="user_id", how="left")\nprint(joined)',
                ],
            },
            {
                'slug': 'ds-06-data-cleaning',
                'title': 'Data Cleaning & Wrangling',
                'desc': 'Handle missing values, duplicates, inconsistent types and outliers — the unglamorous 80% of real data work.',
                'dur': '60 min', 'diff': 'intermediate', 'prereq': ['DS-05: Pandas: DataFrames & Series'],
                'objs': [
                    'Detect and handle missing values deliberately',
                    'Remove duplicates and enforce consistent types',
                    'Standardize text and categorical values',
                    'Find and treat outliers with domain-aware rules',
                ],
                'samples': [
                    'import pandas as pd\n\ndf = pd.DataFrame({"a": [1, None, 3], "b": ["x", "y", None]})\nprint(df.isna().sum())\n# Fill numeric with a sensible value, drop the rest\ncleaned = df.assign(a=df["a"].fillna(df["a"].median())).dropna(subset=["b"])\nprint(cleaned)',
                    'import pandas as pd\n\nraw = pd.DataFrame({"date": ["2024-01-01", "2024-01-02"], "amt": ["$12.5", "$7.00"]})\nraw["date"] = pd.to_datetime(raw["date"])\nraw["amt"] = raw["amt"].str.replace("$", "").astype(float)\nprint(raw.dtypes)',
                    'import pandas as pd\n\nlabels = pd.Series(["  New York ", "new york", "NYC", "los angeles"])\nnormalized = labels.str.strip().str.lower().str.replace("nyc", "new york")\nprint(normalized.tolist())',
                    'import numpy as np\nimport pandas as pd\n\nx = pd.Series([1, 2, 3, 100, 4, 5])\nq1, q3 = x.quantile([0.25, 0.75])\niqr = q3 - q1\noutliers = x[(x < q1 - 1.5 * iqr) | (x > q3 + 1.5 * iqr)]\nprint("outliers:", outliers.tolist())',
                ],
            },
            {
                'slug': 'ds-07-exploratory-data-analysis',
                'title': 'Exploratory Data Analysis',
                'desc': 'Systematically explore a dataset before modeling: distributions, group differences, and the questions they surface.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DS-06: Data Cleaning & Wrangling'],
                'objs': [
                    'Run a systematic EDA checklist on any table',
                    'Summarize distributions with descriptive statistics',
                    'Compare groups with group-by analysis',
                    'Form hypotheses from visual and numeric evidence',
                ],
                'samples': [
                    'import pandas as pd\n\ndf = pd.DataFrame({"age": [23, 45, 31, None, 67], "income": [40, 120, 65, 90, 150]})\nprint(df.describe(percentiles=[0.25, 0.5, 0.75, 0.9]))',
                    'import pandas as pd\n\ndf = pd.DataFrame({"segment": ["a"] * 5 + ["b"] * 5, "value": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})\ngroups = df.groupby("segment")["value"].agg(["mean", "median", "std"])\nprint(groups)',
                    'import pandas as pd\n\nsales = pd.DataFrame({\n    "month": ["jan", "feb", "mar", "apr"],\n    "revenue": [120, 140, 135, 175],\n})\nsales["growth"] = sales["revenue"].pct_change()\nprint(sales)',
                    'import pandas as pd\n\n# Quick distribution check without a plot\ns = pd.Series([1, 1, 2, 3, 3, 3, 4])\nprint(s.value_counts(normalize=True).sort_index())',
                ],
            },
            {
                'slug': 'ds-08-data-visualization',
                'title': 'Data Visualization',
                'desc': 'Choose the right chart, encode data honestly, and tell a story with matplotlib and seaborn.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DS-07: Exploratory Data Analysis'],
                'objs': [
                    'Pick the right chart for the question',
                    'Build line, bar and scatter plots with matplotlib',
                    'Add grouping with seaborn',
                    'Avoid common misleading-visualization traps',
                ],
                'samples': [
                    'import matplotlib.pyplot as plt\n\nx = [1, 2, 3, 4]\ny = [10, 24, 18, 32]\nplt.figure(figsize=(6, 4))\nplt.plot(x, y, marker="o")\nplt.title("Revenue by quarter")\nplt.xlabel("Q")\nplt.ylabel("Revenue")\nplt.tight_layout()\nplt.show()',
                    'import matplotlib.pyplot as plt\n\ncats = ["free", "pro", "team"]\nvals = [1200, 340, 95]\nplt.bar(cats, vals, color="#572EFF")\nplt.title("Signups by plan")\nplt.show()',
                    'import seaborn as sns\n\npenguins = sns.load_dataset("penguins")\nsns.scatterplot(data=penguins.dropna(), x="bill_length_mm", y="bill_depth_mm", hue="species")\nplt.title("Bill shape by species")\nplt.show()',
                    'import matplotlib.pyplot as plt\n\n# A fixed y-axis so small differences are not exaggerated\ncats = ["A", "B"]\nvals = [100, 102]\nplt.bar(cats, vals, color="#572EFF")\nplt.ylim(0, 120)   # honest scale\nplt.show()',
                ],
            },
            {
                'slug': 'ds-09-statistics-fundamentals',
                'title': 'Statistics Fundamentals',
                'desc': 'Mean, variance, standard error, and the sampling ideas that let you reason from data to conclusions.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DS-07: Exploratory Data Analysis'],
                'objs': [
                    'Compute and interpret central tendency and spread',
                    'Distinguish population parameters from sample statistics',
                    'Explain the standard error and the central limit theorem',
                    'Use confidence intervals to quantify uncertainty',
                ],
                'samples': [
                    'import numpy as np\n\nx = np.array([23, 41, 30, 67, 52])\nprint("mean:", x.mean())\nprint("var (sample):", x.var(ddof=1))\nprint("std (sample):", x.std(ddof=1))',
                    'import numpy as np\n\nrng = np.random.default_rng(7)\npop = rng.normal(100, 15, size=100_000)\nfor n in [10, 100, 1000]:\n    means = [rng.choice(pop, size=n).mean() for _ in range(500)]\n    print(f"n={n}: sd of sample means = {np.std(means):.2f}")',
                    'import numpy as np\n\nx = np.array([23, 41, 30, 67, 52])\nn = x.size\nse = x.std(ddof=1) / np.sqrt(n)\n# 95% CI for the mean (approx, z=1.96)\nlo, hi = x.mean() - 1.96 * se, x.mean() + 1.96 * se\nprint(f"95% CI: [{lo:.1f}, {hi:.1f}]")',
                    'import numpy as np\n\na = np.array([1, 2, 3, 4, 5])\nb = np.array([2, 4, 6, 8, 10])\nprint("corr:", np.corrcoef(a, b)[0, 1])',
                ],
            },
            {
                'slug': 'ds-10-probability-distributions',
                'title': 'Probability Distributions',
                'desc': 'The distributions that show up everywhere in data work — normal, binomial, Poisson and uniform — and how to sample from them.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DS-09: Statistics Fundamentals'],
                'objs': [
                    'Explain the normal distribution and the 68-95-99.7 rule',
                    'Model counts with binomial and Poisson distributions',
                    'Compute probabilities with scipy.stats',
                    'Choose a distribution that matches the data-generating process',
                ],
                'samples': [
                    'import numpy as np\nfrom scipy import stats\n\nx = np.linspace(-4, 4, 200)\npdf = stats.norm.pdf(x, loc=0, scale=1)\nprint("pdf at 0:", round(pdf[100], 4))',
                    'from scipy import stats\n\n# P(X <= 3) for X ~ Binomial(n=10, p=0.5)\nprint("P(X<=3):", round(stats.binom.cdf(3, n=10, p=0.5), 4))\n# P(X = 2) for X ~ Poisson(lambda=3)\nprint("P(X=2):", round(stats.poisson.pmf(2, mu=3), 4))',
                    'import numpy as np\n\nrng = np.random.default_rng(0)\nsamples = rng.normal(loc=0, scale=1, size=100_000)\nwithin_1 = np.mean(np.abs(samples) <= 1)\nwithin_2 = np.mean(np.abs(samples) <= 2)\nprint(f"within 1 sd: {within_1:.3f} (expect 0.68)")\nprint(f"within 2 sd: {within_2:.3f} (expect 0.95)")',
                    'from scipy import stats\n\n# Events per hour ~ Poisson(5); probability of <= 3 events\nprint("P(<=3):", round(stats.poisson.cdf(3, mu=5), 4))',
                ],
            },
            {
                'slug': 'ds-11-hypothesis-testing',
                'title': 'Hypothesis Testing',
                'desc': 'Null hypotheses, p-values, t-tests and the judgment calls that separate rigorous analysis from pattern-chasing.',
                'dur': '60 min', 'diff': 'intermediate', 'prereq': ['DS-10: Probability Distributions'],
                'objs': [
                    'State a null and alternative hypothesis clearly',
                    'Run t-tests and chi-square tests with scipy',
                    'Interpret p-values and effect sizes correctly',
                    'Recognize multiple-comparison and p-hacking traps',
                ],
                'samples': [
                    'import numpy as np\nfrom scipy import stats\n\ncontrol = np.array([12, 15, 14, 16, 13])\ntreated = np.array([17, 19, 18, 21, 16])\nt, p = stats.ttest_ind(control, treated)\nprint(f"t={t:.2f} p={p:.3f}")',
                    'from scipy import stats\n\n# Observed vs expected counts\nobserved = [42, 58]\nexpected = [50, 50]\nchi2, p = stats.chisquare(observed, expected)\nprint(f"chi2={chi2:.2f} p={p:.3f}")',
                    'import numpy as np\n\n# Effect size: Cohen\'s d (signal relative to noise)\na = np.array([12, 15, 14, 16, 13])\nb = np.array([17, 19, 18, 21, 16])\npooled = np.sqrt((a.var(ddof=1) + b.var(ddof=1)) / 2)\nd = (b.mean() - a.mean()) / pooled\nprint(f"Cohen\'s d = {d:.2f}")',
                    'import numpy as np\nfrom scipy import stats\n\n# Multiple comparisons: correct with Bonferroni\npvals = np.array([0.04, 0.02, 0.6])\ncorrected = np.minimum(pvals * len(pvals), 1.0)\nprint("corrected:", corrected)',
                ],
            },
            {
                'slug': 'ds-12-correlation-and-causation',
                'title': 'Correlation & Causation',
                'desc': 'Measure association, then reason carefully about whether an intervention actually causes the effect.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['DS-11: Hypothesis Testing'],
                'objs': [
                    'Compute Pearson and Spearman correlations',
                    'Explain why correlation does not imply causation',
                    'Identify confounding variables and selection bias',
                    'Describe when a randomized experiment is needed',
                ],
                'samples': [
                    'import numpy as np\nfrom scipy import stats\n\nx = np.array([1, 2, 3, 4, 5])\ny = np.array([2, 4, 6, 8, 10])\nr, p = stats.pearsonr(x, y)\nprint(f"Pearson r={r:.3f} (p={p:.3f})")',
                    'from scipy import stats\n\nx = np.array([1, 2, 3, 4, 5, 100])\ny = np.array([2, 4, 6, 8, 10, 1])\nprint("Pearson:", round(stats.pearsonr(x, y)[0], 3))\nprint("Spearman:", round(stats.spearmanr(x, y)[0], 3))',
                    'import numpy as np\n\n# Confounder: ice cream sales & drowning both rise with temperature\ntemp = np.array([20, 22, 25, 28, 30])\nice = temp * 10 + np.random.default_rng(0).normal(0, 5, 5)\nprint("spurious r:", round(np.corrcoef(temp, ice)[0, 1], 2))',
                    'import numpy as np\n\n# Randomized assignment breaks the confounder link\nrng = np.random.default_rng(1)\ntreatment = rng.choice([0, 1], size=100)\noutcome = 2.0 * treatment + rng.normal(0, 1, 100)\nprint("ATE estimate:", round(outcome[treatment == 1].mean() - outcome[treatment == 0].mean(), 2))',
                ],
            },
            {
                'slug': 'ds-13-feature-engineering',
                'title': 'Feature Engineering',
                'desc': 'Turn raw columns into features that models can actually learn from: encodings, transforms, dates and domain knowledge.',
                'dur': '60 min', 'diff': 'intermediate', 'prereq': ['DS-12: Correlation & Causation'],
                'objs': [
                    'Encode categorical variables appropriately',
                    'Create date, ratio and interaction features',
                    'Scale numeric features for distance-based models',
                    'Decide when a transform helps versus adds noise',
                ],
                'samples': [
                    'import pandas as pd\n\ndf = pd.DataFrame({"color": ["red", "blue", "red", "green"]})\nprint(pd.get_dummies(df, columns=["color"]))',
                    'import pandas as pd\n\ndf = pd.DataFrame({"total": [100, 200, 50], "users": [10, 25, 5]})\ndf["revenue_per_user"] = df["total"] / df["users"]\ndf["is_high_value"] = df["revenue_per_user"] > 10\nprint(df)',
                    'from sklearn.preprocessing import StandardScaler\nimport numpy as np\n\nX = np.array([[1, 1000], [2, 2000], [3, 1500]])\nscaled = StandardScaler().fit_transform(X)\nprint(scaled.round(2))',
                    'import pandas as pd\n\norders = pd.DataFrame({"ts": pd.to_datetime(["2024-01-01 09:00", "2024-01-01 21:00"])})\norders["hour"] = orders["ts"].dt.hour\norders["weekday"] = orders["ts"].dt.dayofweek\norders["is_evening"] = orders["hour"] >= 18\nprint(orders)',
                ],
            },
            {
                'slug': 'ds-14-train-test-split',
                'title': 'Train/Test Splits & Validation',
                'desc': 'The disciplined way to estimate model quality: hold out data, avoid leakage, and validate like it matters.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['DS-13: Feature Engineering'],
                'objs': [
                    'Split data into train, validation and test sets',
                    'Prevent target leakage in preprocessing',
                    'Explain why test data must stay untouched',
                    'Handle time-series splits correctly',
                ],
                'samples': [
                    'from sklearn.model_selection import train_test_split\nimport numpy as np\n\nX = np.arange(100).reshape(50, 2)\ny = np.arange(50)\nX_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)\nprint(X_tr.shape, X_te.shape)',
                    'from sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\n\nX = [[1, 10], [2, 20], [3, 30], [4, 40], [5, 50], [6, 60]]\ny = [0, 0, 1, 1, 0, 1]\nX_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.33, random_state=0)\n# Fit the scaler on TRAIN ONLY, then transform both\nscaler = StandardScaler().fit(X_tr)\nprint(scaler.transform(X_te).round(2))',
                    'import numpy as np\n\n# Time series: never shuffle across time\ndates = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])\ntrain, test = dates[:7], dates[7:]\nprint("train:", train, "test:", test)',
                    'from sklearn.model_selection import train_test_split\nimport pandas as pd\n\ndf = pd.DataFrame({"x": [1, 2, 3, 4, 5, 6], "y": [0, 0, 1, 1, 1, 0]})\n# Stratify keeps class proportions in both splits\ntr, te = train_test_split(df, test_size=0.33, random_state=0, stratify=df["y"])\nprint(te)',
                ],
            },
            {
                'slug': 'ds-15-regression-models',
                'title': 'Regression Models',
                'desc': 'Predict numbers with linear and regularized regression, and read the coefficients like an analyst.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DS-14: Train/Test Splits & Validation'],
                'objs': [
                    'Fit and interpret a linear regression',
                    'Handle multiple predictors and interactions',
                    'Use Ridge/Lasso for stability',
                    'Report error metrics such as RMSE and R²',
                ],
                'samples': [
                    'from sklearn.linear_model import LinearRegression\nimport numpy as np\n\nX = np.array([[1], [2], [3], [4], [5]])\ny = np.array([2, 4, 6, 8, 10])\nmodel = LinearRegression().fit(X, y)\nprint("slope:", model.coef_[0], "intercept:", model.intercept_)',
                    'from sklearn.linear_model import LinearRegression\nfrom sklearn.metrics import mean_squared_error\nimport numpy as np\n\nX = np.array([[1, 3], [2, 5], [3, 7], [4, 9]])\ny = np.array([2, 4, 6, 8])\nm = LinearRegression().fit(X, y)\npred = m.predict(X)\nprint("RMSE:", round(mean_squared_error(y, pred, squared=False), 3))\nprint("R2:", round(m.score(X, y), 3))',
                    'from sklearn.linear_model import Ridge, Lasso\n\nX = [[1, 10], [2, 20], [3, 30], [4, 40]]\ny = [1, 2, 3, 4]\nfor name, model in [("ridge", Ridge(alpha=1.0)), ("lasso", Lasso(alpha=0.1))]:\n    model.fit(X, y)\n    print(name, "coefs:", model.coef_.round(2))',
                    'import numpy as np\n\n# Residuals: the story the model did not capture\nactual = np.array([3, 5, 7, 9])\npred = np.array([3.2, 4.8, 7.5, 8.6])\nresiduals = actual - pred\nprint("residuals:", residuals)\nprint("largest miss:", residuals[np.abs(residuals).argmax()])',
                ],
            },
            {
                'slug': 'ds-16-classification-models',
                'title': 'Classification Models',
                'desc': 'Predict categories with logistic regression and neighbors, and learn what decision boundaries really mean.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DS-15: Regression Models'],
                'objs': [
                    'Frame a business question as a classification task',
                    'Fit and interpret logistic regression',
                    'Use k-NN and understand decision boundaries',
                    'Read probability outputs, not just labels',
                ],
                'samples': [
                    'from sklearn.linear_model import LogisticRegression\nimport numpy as np\n\nX = np.array([[1, 2], [2, 3], [3, 1], [8, 8], [9, 9], [7, 10]])\ny = np.array([0, 0, 0, 1, 1, 1])\nmodel = LogisticRegression().fit(X, y)\nprint("accuracy:", round(model.score(X, y), 2))\nprint("class prob:", model.predict_proba([[4, 5]]).round(2))',
                    'from sklearn.linear_model import LogisticRegression\n\nX = [[1, 2], [2, 3], [3, 1], [8, 8], [9, 9], [7, 10]]\ny = [0, 0, 0, 1, 1, 1]\nmodel = LogisticRegression().fit(X, y)\nprint("coefs:", model.coef_.round(3), "intercept:", round(model.intercept_[0], 3))',
                    'from sklearn.neighbors import KNeighborsClassifier\n\nX = [[0, 0], [0, 1], [5, 5], [6, 5]]\ny = [0, 0, 1, 1]\nfor k in [1, 3]:\n    m = KNeighborsClassifier(n_neighbors=k).fit(X, y)\n    print(f"k={k}: pred for (2,2) ->", m.predict([[2, 2]])[0])',
                    'from sklearn.linear_model import LogisticRegression\n\nX = [[1], [2], [3], [10], [11], [12]]\ny = [0, 0, 0, 1, 1, 1]\nm = LogisticRegression().fit(X, y)\nfor point in [[2], [6], [10]]:\n    print(f"x={point[0]} -> P(class=1) = {m.predict_proba(point)[0][1]:.2f}")',
                ],
            },
            {
                'slug': 'ds-17-clustering',
                'title': 'Clustering',
                'desc': 'Find structure without labels: k-means, distance metrics, and choosing the number of clusters honestly.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['DS-16: Classification Models'],
                'objs': [
                    'Explain unsupervised learning and clustering goals',
                    'Run k-means with scikit-learn',
                    'Choose k with the elbow and silhouette methods',
                    'Scale features before computing distances',
                ],
                'samples': [
                    'from sklearn.cluster import KMeans\nimport numpy as np\n\nX = np.array([[1, 1], [1, 2], [2, 1], [8, 8], [9, 9], [8, 9]])\nkm = KMeans(n_clusters=2, n_init=10, random_state=0).fit(X)\nprint("labels:", km.labels_)\nprint("centers:", km.cluster_centers_)',
                    'import numpy as np\nfrom sklearn.cluster import KMeans\n\nX = np.random.default_rng(0).normal(size=(200, 2))\ninertias = [KMeans(n_clusters=k, n_init=10, random_state=0).fit(X).inertia_ for k in range(1, 7)]\nprint("inertia by k:", [round(i, 1) for i in inertias])',
                    'from sklearn.cluster import KMeans\nfrom sklearn.metrics import silhouette_score\nimport numpy as np\n\nX = np.random.default_rng(1).normal(size=(100, 2))\nfor k in [2, 3, 4]:\n    labels = KMeans(n_clusters=k, n_init=10, random_state=0).fit_predict(X)\n    print(f"k={k} silhouette={silhouette_score(X, labels):.3f}")',
                    'from sklearn.preprocessing import StandardScaler\nfrom sklearn.cluster import KMeans\n\n# Scale first: distance in raw units misleads\nX = [[1, 1000], [2, 2000], [3, 1500], [50, 5000]]\nXs = StandardScaler().fit_transform(X)\nprint(KMeans(n_clusters=2, n_init=10, random_state=0).fit_predict(Xs))',
                ],
            },
            {
                'slug': 'ds-18-model-evaluation',
                'title': 'Model Evaluation Metrics',
                'desc': 'Accuracy is a trap. Learn precision, recall, F1, ROC curves, and the confusion matrix inside out.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['DS-16: Classification Models'],
                'objs': [
                    'Read a confusion matrix correctly',
                    'Compute precision, recall and F1',
                    'Explain the precision-recall trade-off',
                    'Use ROC-AUC for ranking quality',
                ],
                'samples': [
                    'from sklearn.metrics import confusion_matrix\n\ny_true = [0, 1, 1, 0, 1, 0]\ny_pred = [0, 1, 0, 0, 1, 1]\nprint(confusion_matrix(y_true, y_pred))',
                    'from sklearn.metrics import precision_score, recall_score, f1_score\n\ny_true = [0, 1, 1, 0, 1, 0]\ny_pred = [0, 1, 0, 0, 1, 1]\nprint("precision:", round(precision_score(y_true, y_pred), 2))\nprint("recall:", round(recall_score(y_true, y_pred), 2))\nprint("F1:", round(f1_score(y_true, y_pred), 2))',
                    'from sklearn.metrics import roc_auc_score\n\ny_true = [0, 1, 1, 0, 1, 0]\ny_prob = [0.1, 0.9, 0.4, 0.2, 0.8, 0.7]\nprint("ROC-AUC:", round(roc_auc_score(y_true, y_prob), 3))',
                    'import numpy as np\n\n# Threshold sweep: raising the bar boosts precision, cuts recall\nscores = np.array([0.2, 0.5, 0.7, 0.9])\nlabels = np.array([0, 1, 0, 1])\nfor t in [0.3, 0.6, 0.8]:\n    preds = (scores >= t).astype(int)\n    tp = ((preds == 1) & (labels == 1)).sum()\n    fp = ((preds == 1) & (labels == 0)).sum()\n    fn = ((preds == 0) & (labels == 1)).sum()\n    prec = tp / (tp + fp) if tp + fp else 0\n    rec = tp / (tp + fn) if tp + fn else 0\n    print(f"t={t}: precision={prec:.2f} recall={rec:.2f}")',
                ],
            },
            {
                'slug': 'ds-19-communicating-results',
                'title': 'Communicating Results',
                'desc': 'The analysis only matters if it changes decisions. Learn to write, present and defend findings clearly.',
                'dur': '45 min', 'diff': 'intermediate', 'prereq': ['DS-18: Model Evaluation Metrics'],
                'objs': [
                    'Structure a findings memo for decision-makers',
                    'Pair every claim with its uncertainty',
                    'Design a clean, honest dashboard',
                    'Answer objections with pre-registered evidence',
                ],
                'samples': [
                    'memo = {\n    "question": "Does the new onboarding increase activation?",\n    "finding": "Activation +4.2pp (95% CI [1.9, 6.5])",\n    "caveat": "Early adopters only; revisit at 8 weeks",\n    "next_step": "Roll out to 25% and monitor churn",\n}\nfor k, v in memo.items():\n    print(f"{k}: {v}")',
                    'import numpy as np\n\n# Report uncertainty, not just point estimates\nlift = np.array([0.02, 0.05, 0.06, 0.03, 0.04])\nprint(f"mean lift {lift.mean()*100:.1f}pp +/- {1.96*lift.std(ddof=1)/np.sqrt(lift.size)*100:.1f}pp")',
                    'import pandas as pd\n\n# A dashboard starts with a clear metric definition\nmetrics = {\n    "activation_rate": "activated / signed_up (7d)",\n    "retention_w4": "active at week 4 / signed_up",\n    "nps": "promoters - detractors (0-10 scale)",\n}\nprint(pd.DataFrame(metrics.items(), columns=["metric", "definition"]))',
                    'def pre_register(question, hypothesis, metric, analysis):\n    return {"question": question, "hypothesis": hypothesis, "metric": metric, "analysis": analysis}\n\nplan = pre_register(\n    "Does X move retention?", "Retention +1pp", "retention_w4", "two-sample t-test, alpha=0.05"\n)\nprint(plan)',
                ],
            },
            {
                'slug': 'ds-20-end-to-end-project',
                'title': 'An End-to-End Data Science Project',
                'desc': 'Assemble everything into one reproducible project: ask, fetch, clean, explore, model, evaluate, and ship the notebook.',
                'dur': '75 min', 'diff': 'advanced', 'prereq': ['DS-19: Communicating Results'],
                'objs': [
                    'Structure a reproducible project layout',
                    'Chain cleaning, EDA and modeling into one pipeline',
                    'Evaluate and select a model with held-out data',
                    'Package conclusions with code and artifacts',
                ],
                'samples': [
                    'project = {\n    "data/raw": "original download",\n    "data/processed": "cleaned tables",\n    "notebooks/": "analysis",\n    "src/": "reusable functions",\n    "reports/": "findings",\n}\nfor d, purpose in project.items():\n    print(f"{d:22} {purpose}")',
                    'import pandas as pd\n\ndef clean_pipeline(df: pd.DataFrame) -> pd.DataFrame:\n    df = df.drop_duplicates()\n    df["price"] = pd.to_numeric(df["price"], errors="coerce")\n    df = df.dropna(subset=["price"])\n    df["price"] = df["price"].clip(lower=0)\n    return df\n\ndf = pd.DataFrame({"price": ["9.99", None, "oops", "5.00"]})\nprint(clean_pipeline(df))',
                    'from sklearn.model_selection import train_test_split\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import accuracy_score\nimport pandas as pd\n\ndf = pd.DataFrame({"a": range(20), "b": [i % 2 for i in range(20)], "y": [1 if i % 3 == 0 else 0 for i in range(20)]})\nX = df[["a", "b"]]\ny = df["y"]\nX_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.25, random_state=0)\nm = LogisticRegression().fit(X_tr, y_tr)\nprint("test accuracy:", round(accuracy_score(y_te, m.predict(X_te)), 2))',
                    'import json\n\n# Every run logs its metrics for later comparison\nrun = {"model": "LogisticRegression", "test_accuracy": 0.75, "features": ["a", "b"]}\nwith open("run.json", "w") as fh:\n    json.dump(run, fh, indent=2)\nprint("saved run.json")',
                ],
            },
            {
                'slug': 'ds-21-roadmap',
                'title': 'Beyond the Basics: Your Data Science Roadmap',
                'desc': 'Synthesize the course into a study roadmap, connect it to machine learning and deep learning, and plan real projects.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['DS-20: An End-to-End Data Science Project'],
                'objs': [
                    'Map the course to a personal study plan',
                    'Connect data science to ML and deep learning next steps',
                    'Choose portfolio projects that prove skills',
                    'Find communities and sources for continuous learning',
                ],
                'samples': [
                    'roadmap = {\n    1: "solidify stats & probability",\n    2: "next: Machine Learning course",\n    3: "then: Deep Learning course",\n    4: "build 2 portfolio projects",\n}\nfor step, goal in roadmap.items():\n    print(f"{step}. {goal}")',
                    'import pandas as pd\n\n# Portfolio projects should span the whole pipeline\nprojects = pd.DataFrame({\n    "project": ["customer churn", "housing prices", "news topic model"],\n    "skill": ["classification", "regression", "nlp"],\n})\nprint(projects)',
                    'checklist = ["clean data", "EDA", "baseline model", "evaluate", "document", "ship"]\nremaining = [c for c in checklist if c != "ship"]\nprint("focus next:", remaining)',
                    'def weekly_plan(hours: int):\n    return {"theory": int(hours * 0.4), "coding": int(hours * 0.4), "reading": max(1, int(hours * 0.2))}\n\nprint(weekly_plan(10))',
                ],
            },
        ],
    },

    # ────────────────────────────────────────────────────────────────
    # MACHINE LEARNING
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'machine-learning',
        'code_lang': 'python',
        'refs': [
            ('scikit-learn User Guide', 'https://scikit-learn.org/stable/user_guide.html', 'The authoritative guide to the Python ML toolbox.'),
            ('The Elements of Statistical Learning', 'https://hastie.su.domains/ElemStatLearn/', 'The classic statistical-learning reference (free PDF).'),
            ('Hands-On Machine Learning — Aurélien Géron', 'https://github.com/ageron/handson-ml3', 'Practical ML with scikit-learn, Keras and TensorFlow.'),
            ('Andrew Ng — Machine Learning Specialization', 'https://www.coursera.org/specializations/machine-learning-introduction', 'The most popular introductory ML course in the world.'),
            ('Kaggle Learn — Intro to Machine Learning', 'https://www.kaggle.com/learn/intro-to-machine-learning', 'Hands-on micro-course for the fundamentals.'),
        ],
        'lessons': [
            {
                'slug': 'ml-01-what-is-machine-learning',
                'title': 'What Is Machine Learning?',
                'desc': 'Define machine learning, contrast it with rules-based programming, and survey where ML wins in production.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': [],
                'objs': [
                    'Define machine learning and its core components',
                    'Contrast ML with hand-written rules',
                    'Name the main families of ML tasks',
                    'Identify good first problems for ML',
                ],
                'samples': [
                    'import numpy as np\nfrom sklearn.linear_model import LinearRegression\n\n# Rules: if x > 3: y = 1. Learned: fit a line to data\nX = np.array([[1], [2], [3], [4], [5]])\ny = np.array([2, 4, 6, 8, 10])\nmodel = LinearRegression().fit(X, y)\nprint("learned slope:", round(model.coef_[0], 2))',
                    'task = {\n    "supervised": "learn from labeled examples",\n    "unsupervised": "find structure in unlabeled data",\n    "reinforcement": "learn from rewards and actions",\n}\nfor name, desc in task.items():\n    print(f"{name:14} {desc}")',
                    'candidates = ["spam filter", "fraud detection", "product ranking", "sensor anomaly detection"]\nfor c in candidates:\n    print(f"- {c}")',
                    'import numpy as np\n\n# Even a dumb baseline matters: predict the majority class\nlabels = np.array([0, 0, 0, 1, 1])\nbaseline = labels.mean() > 0.5\nprint("majority-class baseline:", int(baseline))',
                ],
            },
            {
                'slug': 'ml-02-types-of-learning',
                'title': 'Types of Learning',
                'desc': 'Supervised, unsupervised and reinforcement learning — and the sub-tasks that fall under each.',
                'dur': '45 min', 'diff': 'beginner', 'prereq': ['ML-01: What Is Machine Learning?'],
                'objs': [
                    'Distinguish supervised, unsupervised and reinforcement learning',
                    'Identify regression versus classification tasks',
                    'Recognize clustering, anomaly detection and dimensionality reduction',
                    'Choose the right learning type for a problem',
                ],
                'samples': [
                    'learning_types = {\n    "supervised": ["regression", "classification"],\n    "unsupervised": ["clustering", "anomaly detection", "dim reduction"],\n    "reinforcement": ["policy learning"],\n}\nfor kind, tasks in learning_types.items():\n    print(f"{kind:14} -> {', '.join(tasks)}")',
                    'from sklearn.datasets import load_iris\nfrom sklearn.linear_model import LogisticRegression\n\niris = load_iris()\nm = LogisticRegression(max_iter=200).fit(iris.data, iris.target)\nprint("classification accuracy:", round(m.score(iris.data, iris.target), 2))',
                    'from sklearn.cluster import KMeans\n\nX = [[0, 0], [0, 1], [1, 0], [10, 10], [10, 11]]\nlabels = KMeans(n_clusters=2, n_init=10, random_state=0).fit_predict(X)\nprint("cluster labels:", labels)',
                    'def choose(kind: str, has_labels: bool) -> str:\n    return "supervised" if has_labels else "unsupervised"\n\nprint(choose("churn", has_labels=True))\nprint(choose("segmentation", has_labels=False))',
                ],
            },
            {
                'slug': 'ml-03-the-learning-problem',
                'title': 'The Learning Problem',
                'desc': 'Formalize what a model learns: features, targets, hypotheses and loss — the vocabulary of every ML paper.',
                'dur': '50 min', 'diff': 'beginner', 'prereq': ['ML-02: Types of Learning'],
                'objs': [
                    'Define features, targets and hypothesis space',
                    'Explain loss functions as learning signals',
                    'Describe the train-evaluate loop',
                    'Frame overfitting and underfitting intuitively',
                ],
                'samples': [
                    'problem = {\n    "features": ["age", "income", "region"],\n    "target": "churn (0/1)",\n    "loss": "log loss",\n    "model_family": "logistic regression",\n}\nprint(problem)',
                    'import numpy as np\n\ndef mse(y_true, y_pred):\n    return np.mean((np.array(y_true) - np.array(y_pred)) ** 2)\n\nprint("MSE:", mse([1, 2, 3], [1.1, 1.9, 3.2]))',
                    'import numpy as np\n\n# The learning loop: predict, measure, update\nfor epoch in range(3):\n    loss = 1 / (epoch + 1)  # placeholder decreasing loss\n    print(f"epoch {epoch}: loss={loss:.3f}")',
                    'import numpy as np\n\n# Underfit: high bias. Overfit: high variance.\nsimple = np.polyfit([0, 1, 2, 3], [0, 1, 4, 9], deg=1)\ncomplex = np.polyfit([0, 1, 2, 3], [0, 1, 4, 9], deg=3)\nprint("linear fit coefs:", simple.round(2))\nprint("cubic fit coefs:", complex.round(2))',
                ],
            },
            {
                'slug': 'ml-04-python-ml-stack',
                'title': 'The Python ML Stack',
                'desc': 'Get fluent with scikit-learn: estimators, fit/predict, pipelines, and the dataset zoo used everywhere.',
                'dur': '50 min', 'diff': 'beginner', 'prereq': ['ML-03: The Learning Problem'],
                'objs': [
                    'Use scikit-learn estimators with fit and predict',
                    'Build pipelines that compose transforms and models',
                    'Load built-in datasets for practice',
                    'Inspect model parameters and hyperparameters',
                ],
                'samples': [
                    'from sklearn.datasets import load_diabetes\nfrom sklearn.linear_model import LinearRegression\n\nX, y = load_diabetes(return_X_y=True)\nm = LinearRegression().fit(X, y)\nprint("R2:", round(m.score(X, y), 3))',
                    'from sklearn.pipeline import make_pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\npipe = make_pipeline(StandardScaler(), LogisticRegression(max_iter=300))\npipe.fit(X, y)\nprint("pipeline accuracy:", round(pipe.score(X, y), 3))',
                    'from sklearn.datasets import load_iris\n\niris = load_iris()\nprint("features:", iris.feature_names)\nprint("targets:", iris.target_names)',
                    'from sklearn.ensemble import RandomForestClassifier\n\nm = RandomForestClassifier(n_estimators=100, max_depth=4, random_state=0)\nprint("defaults ->", m.get_params()["n_estimators"], "trees")',
                ],
            },
            {
                'slug': 'ml-05-linear-regression',
                'title': 'Linear Regression',
                'desc': 'The workhorse of prediction: least squares, multiple predictors, and interpreting coefficients.',
                'dur': '55 min', 'diff': 'beginner', 'prereq': ['ML-04: The Python ML Stack'],
                'objs': [
                    'Fit linear regression with multiple features',
                    'Interpret coefficients as conditional effects',
                    'Diagnose residuals',
                    'Avoid common misuse with correlated features',
                ],
                'samples': [
                    'from sklearn.linear_model import LinearRegression\n\nX = [[1, 5], [2, 6], [3, 7], [4, 8]]\ny = [9, 14, 19, 24]\nm = LinearRegression().fit(X, y)\nprint("coefs:", m.coef_.round(2), "intercept:", round(m.intercept_, 2))',
                    'import numpy as np\n\n# Prediction and residual diagnosis\npred = m.predict(X)\nres = np.array(y) - pred\nprint("residual mean:", round(res.mean(), 6))\nprint("max |residual|:", round(np.abs(res).max(), 3))',
                    'from sklearn.linear_model import LinearRegression\n\n# Correlated features make individual coefficients unstable\nX = [[1, 2], [2, 4], [3, 6], [4, 8]]\ny = [3, 6, 9, 12]\nm = LinearRegression().fit(X, y)\nprint("unstable coefs:", m.coef_.round(2))',
                    'import numpy as np\n\n# Manually: closed-form normal equation for the slope\nx = np.array([1, 2, 3, 4])\ny = np.array([2, 4, 6, 8])\nslope = np.sum((x - x.mean()) * (y - y.mean())) / np.sum((x - x.mean()) ** 2)\nprint("slope:", slope)',
                ],
            },
            {
                'slug': 'ml-06-gradient-descent',
                'title': 'Gradient Descent',
                'desc': 'The optimization loop under every model: compute the gradient, step downhill, repeat.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['ML-05: Linear Regression'],
                'objs': [
                    'Explain the gradient as the direction of steepest increase',
                    'Implement gradient descent for a simple model',
                    'Tune the learning rate',
                    'Recognize convergence and divergence symptoms',
                ],
                'samples': [
                    'import numpy as np\n\n# f(x) = (x - 3)^2, gradient = 2(x - 3)\nx = 10.0\nfor i in range(10):\n    x = x - 0.1 * 2 * (x - 3)\nprint("converged to:", round(x, 3))',
                    'import numpy as np\n\nX = np.array([1, 2, 3, 4])\ny = np.array([2, 4, 6, 8])\nw = 0.0\nlr = 0.01\nfor _ in range(50):\n    grad = -2 * np.mean(X * (y - w * X))\n    w -= lr * grad\nprint("learned slope:", round(w, 3))',
                    'import numpy as np\n\nx = 10.0\nfor lr in [0.01, 0.5, 1.2]:\n    v = x\n    for _ in range(20):\n        v = v - lr * 2 * (v - 3)\n    print(f"lr={lr}: final x = {round(v, 2)}")',
                    'import numpy as np\n\n# Stochastic vs batch: noisy updates still converge\nX = np.arange(1, 101, dtype=float)\ny = 2 * X + 1\nw = 0.0\nfor epoch in range(20):\n    for i in range(0, len(X), 10):\n        batch = slice(i, i + 10)\n        grad = -2 * np.mean(X[batch] * (y[batch] - w * X[batch]))\n        w -= 0.0001 * grad\nprint("mini-batch slope:", round(w, 2))',
                ],
            },
            {
                'slug': 'ml-07-logistic-regression',
                'title': 'Logistic Regression',
                'desc': 'Probability for classification: the sigmoid, log loss, and decision boundaries that stay interpretable.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['ML-06: Gradient Descent'],
                'objs': [
                    'Explain why linear models need a sigmoid for classification',
                    'Interpret predicted probabilities',
                    'Read log-odds coefficients',
                    'Set decision thresholds by business cost',
                ],
                'samples': [
                    'import numpy as np\n\ndef sigmoid(z):\n    return 1 / (1 + np.exp(-z))\n\nfor z in [-3, 0, 3]:\n    print(f"z={z}: P = {sigmoid(z):.3f}")',
                    'from sklearn.linear_model import LogisticRegression\n\nX = [[1], [2], [3], [10], [11], [12]]\ny = [0, 0, 0, 1, 1, 1]\nm = LogisticRegression().fit(X, y)\nprint("coef:", round(m.coef_[0][0], 3), "intercept:", round(m.intercept_[0], 3))',
                    'import numpy as np\n\n# Threshold by cost: false negatives are 10x more expensive\nscores = np.array([0.3, 0.6, 0.8])\nfor t in [0.5, 0.7]:\n    preds = (scores >= t).astype(int)\n    print(f"t={t} -> {preds}")',
                    'from sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import log_loss\n\nX = [[1], [2], [3], [10], [11], [12]]\ny = [0, 0, 0, 1, 1, 1]\nm = LogisticRegression().fit(X, y)\nprint("log loss:", round(log_loss(y, m.predict_proba(X)), 3))',
                ],
            },
            {
                'slug': 'ml-08-decision-trees',
                'title': 'Decision Trees',
                'desc': 'Greedy splits, impurity, and why trees are the most interpretable nonlinear models.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['ML-07: Logistic Regression'],
                'objs': [
                    'Explain how trees choose splits with impurity',
                    'Read and interpret a fitted tree',
                    'Control depth to balance bias and variance',
                    'Extract feature importances',
                ],
                'samples': [
                    'from sklearn.tree import DecisionTreeClassifier\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\ntree = DecisionTreeClassifier(max_depth=3, random_state=0).fit(X, y)\nprint("accuracy:", round(tree.score(X, y), 3))',
                    'from sklearn.tree import DecisionTreeClassifier, export_text\n\nX = [[1, 1], [2, 2], [3, 3], [10, 10]]\ny = [0, 0, 1, 1]\ntree = DecisionTreeClassifier(max_depth=2, random_state=0).fit(X, y)\nprint(export_text(tree, feature_names=["a", "b"]))',
                    'from sklearn.tree import DecisionTreeClassifier\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\nfor depth in [1, 3, 20]:\n    t = DecisionTreeClassifier(max_depth=depth, random_state=0).fit(X, y)\n    print(f"depth={depth}: train acc {t.score(X, y):.3f}")',
                    'from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\nrf = RandomForestClassifier(random_state=0).fit(X, y)\nprint("importances:", rf.feature_importances_.round(3))',
                ],
            },
            {
                'slug': 'ml-09-ensemble-methods',
                'title': 'Ensemble Methods: Bagging & Random Forests',
                'desc': 'Combine many weak models into one strong predictor with bagging and random forests.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['ML-08: Decision Trees'],
                'objs': [
                    'Explain why averaging reduces variance',
                    'Fit a random forest and tune its key knobs',
                    'Compare single trees to forests',
                    'Use out-of-bag scores as a free validation set',
                ],
                'samples': [
                    'from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\nrf = RandomForestClassifier(n_estimators=100, random_state=0).fit(X, y)\nprint("forest accuracy:", round(rf.score(X, y), 3))',
                    'import numpy as np\n\n# Bagging: average of many bootstrap samples\nrng = np.random.default_rng(0)\nestimates = [rng.choice([3, 4, 5, 6, 7], size=10).mean() for _ in range(1000)]\nprint(f"mean of means: {np.mean(estimates):.2f} (vs single sample ~5)")\nprint(f"sd of means: {np.std(estimates):.2f}")',
                    'from sklearn.ensemble import RandomForestRegressor\n\nX = [[1], [2], [3], [4], [5], [6]]\ny = [1, 4, 9, 16, 25, 36]\nrf = RandomForestRegressor(n_estimators=50, random_state=0).fit(X, y)\nprint("prediction:", round(rf.predict([[7]])[0], 1))',
                    'from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\nrf = RandomForestClassifier(n_estimators=200, oob_score=True, random_state=0).fit(X, y)\nprint("OOB score:", round(rf.oob_score_, 3))',
                ],
            },
            {
                'slug': 'ml-10-gradient-boosting',
                'title': 'Gradient Boosting',
                'desc': 'Boosted trees — the tabular-data champion — fit sequentially to the mistakes of previous models.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['ML-09: Ensemble Methods: Bagging & Random Forests'],
                'objs': [
                    'Explain boosting versus bagging',
                    'Fit gradient-boosted trees with scikit-learn and XGBoost-style APIs',
                    'Tune learning rate versus tree count',
                    'Use early stopping to avoid overfitting',
                ],
                'samples': [
                    'from sklearn.ensemble import GradientBoostingClassifier\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\ngb = GradientBoostingClassifier(random_state=0).fit(X, y)\nprint("GB accuracy:", round(gb.score(X, y), 3))',
                    'from sklearn.ensemble import GradientBoostingRegressor\n\nX = [[i] for i in range(1, 21)]\ny = [v ** 2 for v in range(1, 21)]\ngb = GradientBoostingRegressor(learning_rate=0.1, n_estimators=100, random_state=0).fit(X, y)\nprint("pred(25):", round(gb.predict([[25]])[0], 1))',
                    'from sklearn.ensemble import GradientBoostingRegressor\n\nX = [[i] for i in range(50)]\ny = [v * 2 + (v % 3) for v in range(50)]\n# Lower learning rate needs more trees\nfor lr in [1.0, 0.05]:\n    gb = GradientBoostingRegressor(learning_rate=lr, n_estimators=200, random_state=0).fit(X, y)\n    print(f"lr={lr}: train R2 {gb.score(X, y):.3f}")',
                    'from sklearn.ensemble import GradientBoostingRegressor\n\nX = [[i] for i in range(100)]\ny = [v + (v % 7) for v in range(100)]\ngb = GradientBoostingRegressor(learning_rate=0.05, n_estimators=300, random_state=0)\ngb.fit(X, y)\nprint("staged best:", gb.n_estimators_, "trees")',
                ],
            },
            {
                'slug': 'ml-11-support-vector-machines',
                'title': 'Support Vector Machines',
                'desc': 'Max-margin classification, the kernel trick, and when SVMs beat other models.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['ML-07: Logistic Regression'],
                'objs': [
                    'Explain the maximum-margin idea',
                    'Use the kernel trick for nonlinear boundaries',
                    'Tune C and gamma',
                    'Prefer SVMs on small, high-dimensional datasets',
                ],
                'samples': [
                    'from sklearn.svm import SVC\n\nX = [[1, 1], [2, 2], [2, 0], [8, 8], [9, 9], [8, 10]]\ny = [0, 0, 0, 1, 1, 1]\nclf = SVC(kernel="linear").fit(X, y)\nprint("support vectors:", len(clf.support_vectors_))',
                    'from sklearn.svm import SVC\n\n# RBF kernel draws nonlinear boundaries\nclf = SVC(kernel="rbf", C=10, gamma="scale").fit(X, y)\nprint("rbf accuracy:", round(clf.score(X, y), 2))',
                    'from sklearn.svm import SVC\n\nfor C in [0.1, 10]:\n    clf = SVC(kernel="linear", C=C).fit(X, y)\n    print(f"C={C}: support vectors = {len(clf.support_vectors_)}")',
                    'from sklearn.svm import SVC\n\n# Margin intuition: distance from boundary to nearest point\nimport numpy as np\nX = np.array([[1, 1], [2, 2], [2, 0], [8, 8], [9, 9], [8, 10]])\ny = np.array([0, 0, 0, 1, 1, 1])\nclf = SVC(kernel="linear", C=1e6).fit(X, y)\nw = clf.coef_[0]\nmargin = 2 / np.linalg.norm(w)\nprint("margin width:", round(margin, 3))',
                ],
            },
            {
                'slug': 'ml-12-k-nearest-neighbors',
                'title': 'K-Nearest Neighbors',
                'desc': 'The simplest nonparametric model: predict by voting among the closest training points.',
                'dur': '45 min', 'diff': 'beginner', 'prereq': ['ML-04: The Python ML Stack'],
                'objs': [
                    'Explain how k-NN makes predictions',
                    'Tune k and distance metrics',
                    'Scale features for distance-based models',
                    'Describe the curse of dimensionality',
                ],
                'samples': [
                    'from sklearn.neighbors import KNeighborsClassifier\n\nX = [[0, 0], [0, 1], [5, 5], [6, 5]]\ny = [0, 0, 1, 1]\nclf = KNeighborsClassifier(n_neighbors=3).fit(X, y)\nprint("pred (2,2):", clf.predict([[2, 2]])[0])',
                    'from sklearn.neighbors import KNeighborsRegressor\n\nX = [[1], [2], [3], [4]]\ny = [10, 20, 30, 40]\nfor k in [1, 3]:\n    m = KNeighborsRegressor(n_neighbors=k).fit(X, y)\n    print(f"k={k}: pred(2.5) = {m.predict([[2.5]])[0]:.1f}")',
                    'from sklearn.preprocessing import StandardScaler\nfrom sklearn.neighbors import KNeighborsClassifier\n\nX = [[1, 1000], [2, 2000], [3, 3000]]\ny = [0, 1, 1]\nXs = StandardScaler().fit_transform(X)\nprint(KNeighborsClassifier(n_neighbors=1).fit(Xs, y).predict(StandardScaler().fit(X).transform([[2, 2100]])))',
                    'import numpy as np\n\n# Curse of dimensionality: distance flattens in high dims\nrng = np.random.default_rng(0)\nfor dim in [2, 20, 200]:\n    pts = rng.uniform(size=(1000, dim))\n    d = np.linalg.norm(pts - pts[0], axis=1)[1:]\n    print(f"dim={dim}: mean dist {d.mean():.2f}, min {d.min():.2f}")',
                ],
            },
            {
                'slug': 'ml-13-naive-bayes',
                'title': 'Naive Bayes',
                'desc': 'Bayes\' rule applied to text and beyond — fast, simple, and shockingly effective on the right problems.',
                'dur': '45 min', 'diff': 'intermediate', 'prereq': ['ML-07: Logistic Regression'],
                'objs': [
                    'State Bayes\' rule in plain terms',
                    'Explain the naive independence assumption',
                    'Fit a MultinomialNB text classifier',
                    'Know when Naive Bayes is a good first choice',
                ],
                'samples': [
                    'from sklearn.naive_bayes import MultinomialNB\n\nX = [[2, 1, 0], [1, 2, 0], [0, 1, 3], [0, 0, 4]]\ny = [0, 0, 1, 1]\nclf = MultinomialNB().fit(X, y)\nprint("pred:", clf.predict([[1, 1, 1]])[0])',
                    'from sklearn.feature_extraction.text import CountVectorizer\nfrom sklearn.naive_bayes import MultinomialNB\n\ntexts = ["cheap pills now", "free money", "meeting at noon", "lunch tomorrow"]\ny = [1, 1, 0, 0]\nX = CountVectorizer().fit_transform(texts)\nclf = MultinomialNB().fit(X, y)\nprint("spam prob:", clf.predict_proba(CountVectorizer().transform(["free money now"]))[0][1].round(3))',
                    'from sklearn.naive_bayes import GaussianNB\n\nX = [[1.0, 2.0], [1.2, 1.8], [5.0, 5.2], [5.5, 4.8]]\ny = [0, 0, 1, 1]\nclf = GaussianNB().fit(X, y)\nprint("pred:", clf.predict([[2.0, 2.0]])[0])',
                    'import numpy as np\n\n# Prior updates: P(A|B) = P(B|A) P(A) / P(B)\np_a = 0.01\ntest_sens = 0.99\ntest_spec = 0.95\np_b_given_a = test_sens\np_b = test_sens * p_a + (1 - test_spec) * (1 - p_a)\np_a_given_b = p_b_given_a * p_a / p_b\nprint("P(disease | positive):", round(p_a_given_b, 3))',
                ],
            },
            {
                'slug': 'ml-14-feature-scaling-and-selection',
                'title': 'Feature Scaling & Selection',
                'desc': 'Prepare features so models learn well: scaling, encoding, selection, and dropping noise.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['ML-08: Decision Trees'],
                'objs': [
                    'Scale features for distance and gradient models',
                    'Encode categoricals without leaking order',
                    'Select features with importance and statistical filters',
                    'Explain why removing noise features helps',
                ],
                'samples': [
                    'from sklearn.preprocessing import StandardScaler, MinMaxScaler\n\nX = [[0, 10], [1, 20], [2, 30]]\nprint("standard:", StandardScaler().fit_transform(X).round(2))\nprint("minmax:", MinMaxScaler().fit_transform(X).round(2))',
                    'from sklearn.preprocessing import OneHotEncoder\n\nenc = OneHotEncoder(sparse_output=False)\nprint(enc.fit_transform([["red"], ["green"], ["blue"]]))',
                    'from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.feature_selection import SelectFromModel\n\nX = [[1, 2, 100], [2, 3, 200], [3, 4, 300]]\ny = [0, 1, 1]\nrf = RandomForestClassifier(random_state=0).fit(X, y)\nselector = SelectFromModel(rf, max_features=2)\nprint("kept features:", selector.transform(X).shape[1])',
                    'import numpy as np\n\n# A useless feature (pure noise) should be dropped\nrng = np.random.default_rng(0)\nX = rng.normal(size=(200, 1))\nnoise = rng.normal(size=(200, 10))\nprint("variance of useful feature:", round(X.var(), 3))\nprint("mean variance of noise:", round(noise.var(), 3))',
                ],
            },
            {
                'slug': 'ml-15-regularization',
                'title': 'Regularization',
                'desc': 'Penalize complexity: L1 and L2 regularization, and the bias-variance trade-off made concrete.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['ML-06: Gradient Descent'],
                'objs': [
                    'Explain L1 and L2 penalties',
                    'Use Ridge and Lasso for shrinkage',
                    'Use L1 for automatic feature selection',
                    'Tune the regularization strength',
                ],
                'samples': [
                    'from sklearn.linear_model import Ridge, Lasso\n\nX = [[1, 1], [2, 2], [3, 3], [4, 4]]\ny = [2, 4, 6, 8]\nprint("ridge:", Ridge(alpha=1.0).fit(X, y).coef_.round(2))\nprint("lasso:", Lasso(alpha=0.5).fit(X, y).coef_.round(2))',
                    'import numpy as np\n\n# L2 penalty pulls weights toward zero\ndef ridge_step(w, grad, lr, alpha):\n    return w - lr * (grad + 2 * alpha * w)\n\nw = 2.0\nfor _ in range(50):\n    w = ridge_step(w, 2 * (w - 1), 0.1, 0.3)\nprint("shrunk weight:", round(w, 3))',
                    'from sklearn.linear_model import Lasso\n\nX = [[1, 0, 50], [2, 1, 60], [3, 0, 70]]\ny = [5, 8, 11]\nfor alpha in [0.001, 10]:\n    coefs = Lasso(alpha=alpha).fit(X, y).coef_\n    print(f"alpha={alpha}: coefs {coefs.round(2)}")',
                    'from sklearn.linear_model import RidgeCV\n\nX = [[1], [2], [3], [4]]\ny = [2, 4, 6, 8]\nbest = RidgeCV(alphas=[0.1, 1, 10]).fit(X, y)\nprint("chosen alpha:", best.alpha_)',
                ],
            },
            {
                'slug': 'ml-16-cross-validation',
                'title': 'Cross-Validation',
                'desc': 'k-fold cross-validation gives a more honest error estimate than a single split — and catches tuning leaks.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['ML-04: The Python ML Stack'],
                'objs': [
                    'Run k-fold cross-validation with scikit-learn',
                    'Explain why k-fold beats one train/test split',
                    'Use CV to tune hyperparameters without touching the test set',
                    'Stratify folds for imbalanced targets',
                ],
                'samples': [
                    'from sklearn.model_selection import cross_val_score\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\nscores = cross_val_score(RandomForestClassifier(random_state=0), X, y, cv=5)\nprint("fold scores:", scores.round(3))\nprint("mean:", round(scores.mean(), 3))',
                    'from sklearn.model_selection import cross_val_score\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\nfor C in [0.1, 1, 10]:\n    score = cross_val_score(LogisticRegression(C=C, max_iter=500), X, y, cv=5).mean()\n    print(f"C={C}: cv accuracy {score:.3f}")',
                    'from sklearn.model_selection import StratifiedKFold\n\nkf = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)\nprint("stratified folds keep class balance")',
                    'import numpy as np\n\n# Leave-one-out intuition for small datasets\nfrom sklearn.model_selection import LeaveOneOut\n\nX = np.arange(6).reshape(3, 2)\nloo = LeaveOneOut()\nprint("LOO folds:", sum(1 for _ in loo.split(X)))',
                ],
            },
            {
                'slug': 'ml-17-hyperparameter-tuning',
                'title': 'Hyperparameter Tuning',
                'desc': 'Search parameter space systematically with grid, random and Bayesian strategies — without leaking into the test set.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['ML-16: Cross-Validation'],
                'objs': [
                    'Distinguish parameters from hyperparameters',
                    'Run grid search with cross-validation',
                    'Use randomized search for large spaces',
                    'Avoid tuning on the test set',
                ],
                'samples': [
                    'from sklearn.model_selection import GridSearchCV\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\nsearch = GridSearchCV(\n    RandomForestClassifier(random_state=0),\n    {"n_estimators": [50, 200], "max_depth": [2, None]},\n    cv=5,\n)\nsearch.fit(X, y)\nprint("best params:", search.best_params_)',
                    'from sklearn.model_selection import RandomizedSearchCV\nfrom sklearn.ensemble import RandomForestClassifier\nfrom scipy.stats import randint\n\nsearch = RandomizedSearchCV(\n    RandomForestClassifier(random_state=0),\n    {"n_estimators": randint(50, 300), "max_depth": randint(2, 10)},\n    n_iter=10, cv=5, random_state=0,\n)\nprint("random search ready:", search.param_distributions.keys())',
                    'from sklearn.model_selection import GridSearchCV\nfrom sklearn.linear_model import LogisticRegression\n\nparam_grid = {"C": [0.01, 0.1, 1, 10, 100], "solver": ["lbfgs"]}\nsearch = GridSearchCV(LogisticRegression(max_iter=1000), param_grid, cv=5)\nprint("grid points:", len(param_grid["C"]), "x 1 solver")',
                    'import numpy as np\n\n# The tuning trap: the best CV model still needs a held-out check\nfrom sklearn.model_selection import train_test_split, cross_val_score\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.datasets import load_iris\n\nX, y = load_iris(return_X_y=True)\nX_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=0)\nbest = RandomForestClassifier(n_estimators=200, max_depth=3, random_state=0)\nprint("cv:", round(cross_val_score(best, X_tr, y_tr, cv=5).mean(), 3))\nprint("test:", round(best.fit(X_tr, y_tr).score(X_te, y_te), 3))',
                ],
            },
            {
                'slug': 'ml-18-classification-metrics',
                'title': 'Classification Metrics Deep Dive',
                'desc': 'Precision, recall, F1, ROC curves and calibration — choose the metric that matches the business cost.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['ML-16: Cross-Validation'],
                'objs': [
                    'Compute precision, recall, F1 and support',
                    'Read ROC curves and compare models with AUC',
                    'Explain calibration and reliability',
                    'Choose a metric from business costs',
                ],
                'samples': [
                    'from sklearn.metrics import classification_report\n\ny_true = [0, 1, 1, 0, 1, 0, 1]\ny_pred = [0, 1, 0, 0, 1, 1, 1]\nprint(classification_report(y_true, y_pred, target_names=["neg", "pos"]))',
                    'from sklearn.metrics import roc_curve, auc\nimport numpy as np\n\ny_true = np.array([0, 0, 1, 1])\ny_score = np.array([0.1, 0.4, 0.35, 0.8])\nfpr, tpr, _ = roc_curve(y_true, y_score)\nprint("AUC:", round(auc(fpr, tpr), 3))',
                    'from sklearn.calibration import calibration_curve\n\n# Calibration: does 70% probability mean 70% of the time?\ny_true = [0, 1, 0, 1, 1]\ny_prob = [0.3, 0.7, 0.6, 0.9, 0.8]\nfraction_positive, mean_predicted = calibration_curve(y_true, y_prob, n_bins=3)\nprint("mean predicted:", mean_predicted.round(2))\nprint("fraction positive:", fraction_positive.round(2))',
                    'import numpy as np\n\n# Cost-aware threshold: FP costs 1, FN costs 10\ncosts = {"fp": 1, "fn": 10}\nfor t in [0.5, 0.9]:\n    preds = (np.array([0.4, 0.6, 0.95]) >= t).astype(int)\n    print(f"t={t}: {preds}")',
                ],
            },
            {
                'slug': 'ml-19-kmeans-clustering',
                'title': 'K-Means & Clustering',
                'desc': 'Cluster unlabeled data with k-means, pick k responsibly, and interpret clusters as business segments.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['ML-08: Decision Trees'],
                'objs': [
                    'Explain the k-means objective and algorithm',
                    'Preprocess data before clustering',
                    'Choose k with inertia and silhouette',
                    'Validate clusters with domain knowledge',
                ],
                'samples': [
                    'from sklearn.cluster import KMeans\nimport numpy as np\n\nX = np.random.default_rng(0).normal(size=(300, 2))\nkm = KMeans(n_clusters=3, n_init=10, random_state=0).fit(X)\nprint("cluster sizes:", np.bincount(km.labels_))',
                    'from sklearn.cluster import KMeans\nfrom sklearn.preprocessing import StandardScaler\n\nX = [[1, 1000], [2, 900], [3, 1100], [60, 4000], [70, 4200]]\nXs = StandardScaler().fit_transform(X)\nprint(KMeans(n_clusters=2, n_init=10, random_state=0).fit_predict(Xs))',
                    'from sklearn.cluster import KMeans\nfrom sklearn.metrics import silhouette_score\nimport numpy as np\n\nX = np.random.default_rng(1).normal(size=(200, 2))\nbest_k, best_s = 2, -1\nfor k in range(2, 8):\n    labels = KMeans(n_clusters=k, n_init=10, random_state=0).fit_predict(X)\n    s = silhouette_score(X, labels)\n    if s > best_s:\n        best_k, best_s = k, s\nprint(f"best k={best_k}, silhouette={best_s:.3f}")',
                    'import numpy as np\nfrom sklearn.cluster import KMeans\n\n# Centroids become interpretable segments\nX = np.array([[1, 2], [1, 3], [2, 2], [8, 9], [9, 9]])\nkm = KMeans(n_clusters=2, n_init=10, random_state=0).fit(X)\nprint("centroids:", km.cluster_centers_.round(2))',
                ],
            },
            {
                'slug': 'ml-20-dimensionality-reduction',
                'title': 'Dimensionality Reduction with PCA',
                'desc': 'Project high-dimensional data onto its principal components — for visualization, denoising and speed.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['ML-19: K-Means & Clustering'],
                'objs': [
                    'Explain what principal components capture',
                    'Apply PCA and read explained variance',
                    'Use PCA before clustering or visualization',
                    'Know when PCA hurts',
                ],
                'samples': [
                    'from sklearn.decomposition import PCA\nfrom sklearn.datasets import load_digits\n\nX, _ = load_digits(return_X_y=True)\npca = PCA(n_components=2).fit(X)\nprint("explained variance:", pca.explained_variance_ratio_.round(3))',
                    'from sklearn.decomposition import PCA\nimport numpy as np\n\nX = np.random.default_rng(0).normal(size=(100, 50))\npca = PCA().fit(X)\ncum = np.cumsum(pca.explained_variance_ratio_)\nprint("components for 95%:", int(np.argmax(cum >= 0.95)) + 1)',
                    'from sklearn.decomposition import PCA\nfrom sklearn.cluster import KMeans\n\nX = [[1, 2, 3, 1], [2, 3, 4, 2], [10, 11, 12, 10], [11, 12, 13, 11]]\nX2 = PCA(n_components=2).fit_transform(X)\nprint("cluster on 2 dims:", KMeans(n_clusters=2, n_init=10, random_state=0).fit_predict(X2))',
                    'from sklearn.decomposition import PCA\n\n# PCA centers the data first; scale before use if units differ\nimport numpy as np\nX = np.array([[1, 1000], [2, 2000], [3, 1500]])\nprint(PCA(n_components=1).fit_transform(X).round(2).ravel())',
                ],
            },
            {
                'slug': 'ml-21-roadmap',
                'title': 'Machine Learning Roadmap',
                'desc': 'Synthesize the course, plan the next projects, and chart the path into deep learning and production ML.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['ML-20: Dimensionality Reduction with PCA'],
                'objs': [
                    'Map course concepts to a study plan',
                    'Pick portfolio projects that demonstrate depth',
                    'Bridge into deep learning and production systems',
                    'Join communities and stay current',
                ],
                'samples': [
                    'plan = {\n    1: "reimplement linear regression from scratch",\n    2: "next: Deep Learning course",\n    3: "ship one model end-to-end (API + monitoring)",\n    4: "read one paper per week",\n}\nfor k, v in plan.items():\n    print(f"{k}. {v}")',
                    'from sklearn.datasets import load_breast_cancer\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import cross_val_score\n\nX, y = load_breast_cancer(return_X_y=True)\nprint("practice score:", round(cross_val_score(RandomForestClassifier(random_state=0), X, y, cv=5).mean(), 3))',
                    'import numpy as np\n\n# A tiny deep-learning taste: a learned linear layer\nX = np.array([[0], [1]])\ny = np.array([[1], [0]])\nw = 0.0\nfor _ in range(200):\n    pred = X * w\n    w -= 0.1 * np.mean(X * (pred - y))\nprint("learned weight:", round(w, 2))',
                    'resources = ["scikit-learn docs", "Kaggle", "MLOps book", "papers with code"]\nprint("bookmark:", ", ".join(resources))',
                ],
            },
        ],
    },
]
