#!/usr/bin/env python3
"""Lesson specs for prolog, purescript, racket, scheme — real 21-lesson courses."""

# ────────────────────────────────────────────────────────────────────────────
# PROLOG
# ────────────────────────────────────────────────────────────────────────────
PROLOG = {
    'lang': 'prolog',
    'code_lang': 'prolog',
    'refs': [
        ('SWI-Prolog Documentation', 'https://www.swi-prolog.org/pldoc/', 'Official SWI-Prolog docs'),
        ('Learn Prolog Now!', 'https://www.learnprolognow.org/', 'The classic free textbook'),
        ('Prolog Wiki', 'https://en.wikipedia.org/wiki/Prolog', 'Overview article'),
    ],
    'lessons': [
        {'slug': 'prolog-01-getting-started', 'title': 'Getting Started with Prolog', 'desc': 'SWI-Prolog, facts, and queries.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install SWI-Prolog', 'Write facts', 'Ask queries', 'Run a .pl file'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '% facts.pl\nlikes(mary, pizza).\nlikes(john, sushi).',
             'swipl facts.pl\n?- likes(mary, pizza).\ntrue.',
             '?- likes(X, pizza).\nX = mary.',
             'writeln("Hello, World!").',
         ]},
        {'slug': 'prolog-02-facts-rules', 'title': 'Facts and Rules', 'desc': 'Build a knowledge base.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write multi-argument facts', 'Write rules', 'Use variables in rules', 'Query with variables'],
         'prereq': ['Prolog-01: Getting Started with Prolog'],
         'samples': [
             'parent(tom, bob).\nparent(bob, ann).',
             'grandparent(X, Z) :- parent(X, Y), parent(Y, Z).',
             '?- grandparent(tom, ann).\ntrue.',
             'sibling(X, Y) :- parent(P, X), parent(P, Y), X \\= Y.',
         ]},
        {'slug': 'prolog-03-unification', 'title': 'Unification', 'desc': 'The core of Prolog.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Understand unification', 'Match terms', 'Use variables', 'Distinguish = and is'],
         'prereq': ['Prolog-02: Facts and Rules'],
         'samples': [
             '?- X = 5.\nX = 5.',
             '?- f(X, a) = f(b, Y).\nX = b, Y = a.',
             '?- X = Y, Y = 42.\nX = Y, Y = 42.',
             '?- X is 3 + 4.\nX = 7.',
         ]},
        {'slug': 'prolog-04-recursion', 'title': 'Recursion', 'desc': 'Recursive rules for lists and trees.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write recursive rules', 'Use base cases', 'Use recursive cases', 'Trace recursion'],
         'prereq': ['Prolog-03: Unification'],
         'samples': [
             'descendant(X, Y) :- child(X, Y).\ndescendant(X, Y) :- child(X, Z), descendant(Z, Y).',
             'factorial(0, 1).\nfactorial(N, F) :-\n    N > 0,\n    N1 is N - 1,\n    factorial(N1, F1),\n    F is N * F1.',
             '?- factorial(5, F).\nF = 120.',
             'trace.\nfactorial(3, F).',
         ]},
        {'slug': 'prolog-05-lists', 'title': 'Lists', 'desc': 'Build and process lists.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use list syntax', 'Pattern match head/tail', 'Write list predicates', 'Use append'],
         'prereq': ['Prolog-04: Recursion'],
         'samples': [
             '?- [a, b, c] = [H | T].\nH = a, T = [b, c].',
             'member(X, [X | _]).\nmember(X, [_ | T]) :- member(X, T).',
             'len([], 0).\nlen([_ | T], N) :- len(T, N1), N is N1 + 1.',
             'append([], L, L).\nappend([H | T], L, [H | R]) :- append(T, L, R).',
         ]},
        {'slug': 'prolog-06-cutting', 'title': 'The Cut (!)', 'desc': 'Control backtracking.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Understand backtracking', 'Use cut to stop search', 'Use cut-fail', 'Use negation as failure'],
         'prereq': ['Prolog-05: Lists'],
         'samples': [
             'max(X, Y, X) :- X >= Y, !.\nmax(_, Y, Y).',
             'not(X) :- X, !, fail.\nnot(_).',
             'member_opt(X, [X | _]) :- !.\nmember_opt(X, [_ | T]) :- member_opt(X, T).',
             'positive(X) :- X > 0, !.\npositive(_) :- fail.',
         ]},
        {'slug': 'prolog-07-arithmetic', 'title': 'Arithmetic', 'desc': 'Numbers and arithmetic expressions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use is for evaluation', 'Compare numbers', 'Use arithmetic functions', 'Build calculators'],
         'prereq': ['Prolog-06: The Cut (!)'],
         'samples': [
             '?- X is 2 + 3 * 4.\nX = 14.',
             '?- 5 > 3.\ntrue.',
             'sum(List, Total) :-\n    sum_aux(List, 0, Total).\nsum_aux([], Acc, Acc).\nsum_aux([H | T], Acc, Total) :-\n    Acc1 is Acc + H,\n    sum_aux(T, Acc1, Total).',
             'X is mod(7, 3).',
         ]},
        {'slug': 'prolog-08-strings-atoms', 'title': 'Atoms, Strings, and Text', 'desc': 'Text data in Prolog.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Distinguish atoms and strings', 'Convert between them', 'Concatenate text', 'Compare text'],
         'prereq': ['Prolog-07: Arithmetic'],
         'samples': [
             'atom(hello).\nstring("hello").',
             'atom_string(hello, S).',
             'string_concat("Hello", " World", Full).',
             'atom_length(hello, L).',
         ]},
        {'slug': 'prolog-09-assert-retract', 'title': 'Assert and Retract', 'desc': 'Dynamic knowledge bases.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Assert facts dynamically', 'Retract facts', 'Use dynamic declarations', 'Build expert systems'],
         'prereq': ['Prolog-08: Atoms, Strings, and Text'],
         'samples': [
             ':- dynamic visited/1.\nassert(visited(mars)).',
             'visited(X).',
             'retract(visited(mars)).',
             'add_fact(P, C) :-\n    assertz(parent(P, C)).',
         ]},
        {'slug': 'prolog-10-findall', 'title': 'Findall and Setof', 'desc': 'Collect solutions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use findall', 'Use bagof', 'Use setof', 'Aggregate results'],
         'prereq': ['Prolog-09: Assert and Retract'],
         'samples': [
             'findall(X, likes(mary, X), L).',
             'findall(X, parent(tom, X), Children).',
             'setof(X, likes(_, X), Unique).',
             'aggregate_all(count, parent(_, _), Count).',
         ]},
        {'slug': 'prolog-11-io', 'title': 'Input/Output', 'desc': 'Read and write to the user.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write with write/1', 'Read with read/1', 'Read lines', 'Build interactive programs'],
         'prereq': ['Prolog-10: Findall and Setof'],
         'samples': [
             'write("hello"), nl.',
             'read(X),\nwrite(X).',
             'read_line_to_string(user_input, Line).',
             'loop :- write("> "),\n         read_line_to_string(user_input, Line),\n         write(Line), nl,\n         loop.',
         ]},
        {'slug': 'prolog-12-file-io', 'title': 'File I/O', 'desc': 'Read and write files.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Open files', 'Read file content', 'Write to files', 'Close streams'],
         'prereq': ['Prolog-11: Input/Output'],
         'samples': [
             'open("data.txt", read, Stream),\nread_string(Stream, _, Content),\nclose(Stream).',
             'open("out.txt", write, Stream),\nwrite(Stream, "hello"),\nnl(Stream),\nclose(Stream).',
             'setup_call_cleanup(open("f", read, S), read_line(S, L), close(S)).',
             'forall(\n    member(X, [1, 2, 3]),\n    (write(X), nl)).',
         ]},
        {'slug': 'prolog-13-grammar', 'title': 'DCG: Grammar Rules', 'desc': 'Parse with definite clause grammars.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write DCG rules', 'Parse sentences', 'Generate sentences', 'Build expression parsers'],
         'prereq': ['Prolog-12: File I/O'],
         'samples': [
             'sentence --> noun_phrase, verb_phrase.\nnoun_phrase --> determiner, noun.\ndeterminer --> [the].\n noun --> [cat].',
             'sentence --> [the, cat, eats].\n?- phrase(sentence, [the, cat, eats]).\ntrue.',
             'expr --> term, [+], term.\nterm --> [X], {number(X)}.',
             'phrase(sentence, L, []).',
         ]},
        {'slug': 'prolog-14-chatbot', 'title': 'Expert Systems and Chatbots', 'desc': 'Simple rule-based reasoning.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Design rule sets', 'Implement diagnosis', 'Handle unknown inputs', 'Extend knowledge'],
         'prereq': ['Prolog-13: DCG: Grammar Rules'],
         'samples': [
             'symptom(fever).\nsymptom(cough).',
             'disease(flu) :- symptom(fever), symptom(cough).',
             'diagnose(D) :- disease(D), write("Diagnosis: "), write(D), nl.',
             'ask(S) :-\n    format("Do you have ~w? ", [S]),\n    read(yes).',
         ]},
        {'slug': 'prolog-15-chr', 'title': 'Constraint Handling', 'desc': 'Constraint logic programming.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand constraints', 'Use CLP(FD)', 'Solve puzzles', 'Constrain variables'],
         'prereq': ['Prolog-14: Expert Systems and Chatbots'],
         'samples': [
             ':- use_module(library(clpfd)).',
             'X in 1..10.',
             'X #> 3, Y #< X.',
             'X + Y #= 10, X * Y #= 21,\nlabel([X, Y]).',
         ]},
        {'slug': 'prolog-16-sudoku', 'title': 'Sudoku Solver', 'desc': 'A classic CLP(FD) program.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Model a grid', 'Set up constraints', 'Run label search', 'Verify solutions'],
         'prereq': ['Prolog-15: Constraint Handling'],
         'samples': [
             'sudoku(Rows) :-\n    length(Rows, 9),\n    maplist(same_length(Rows), Rows),\n    append(Rows, Vs), Vs ins 1..9,\n    maplist(all_distinct, Rows),\n    transpose(Rows, Cols),\n    maplist(all_distinct, Cols),\n    Rows = [A, B, C, D, E, F, G, H, I],\n    blocks(A, B, C), blocks(D, E, F), blocks(G, H, I),\n    label(Vs).',
             'all_distinct([1, 2, 3]).',
             'X in 1..9, X #\\= 2.',
             'labeling([], Vs).',
         ]},
        {'slug': 'prolog-17-search', 'title': 'Search Algorithms', 'desc': 'Implement DFS and BFS.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Model graphs', 'Implement DFS', 'Implement BFS', 'Find paths'],
         'prereq': ['Prolog-16: Sudoku Solver'],
         'samples': [
             'edge(a, b).\nedge(b, c).\nedge(a, c).',
             'path(X, X, [X]).\npath(X, Y, [X | P]) :-\n    edge(X, Z),\n    path(Z, Y, P).',
             'bfs(Start, Goal) :-\n    bfs([[Start]], Goal, Path).',
             '?- path(a, c, P).',
         ]},
        {'slug': 'prolog-18-modules', 'title': 'Modules and Libraries', 'desc': 'Organize Prolog code.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Create modules', 'Export predicates', 'Import modules', 'Use SWI libraries'],
         'prereq': ['Prolog-17: Search Algorithms'],
         'samples': [
             ':- module(math_utils, [square/2]).\nsquare(X, Y) :- Y is X * X.',
             ':- use_module(math_utils).',
             'use_module(library(lists)).',
             'use_module(library(dcg/basics)).',
         ]},
        {'slug': 'prolog-19-debugging', 'title': 'Debugging Prolog', 'desc': 'Trace and inspect.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use trace', 'Set spy points', 'Use debug predicates', 'Profile queries'],
         'prereq': ['Prolog-18: Modules and Libraries'],
         'samples': [
             'trace.\nfactorial(5, F).',
             'spy(factorial/2).',
             'debug.',
             'statistics(runtime, [T, _]).',
         ]},
        {'slug': 'prolog-20-applications', 'title': 'Real-World Applications', 'desc': 'Where Prolog shines.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Understand NLP applications', 'Understand expert systems', 'Use knowledge graphs', 'Build planning systems'],
         'prereq': ['Prolog-19: Debugging Prolog'],
         'samples': [
             '% family tree knowledge base',
             '% route planning: find_path(Home, Work, Path)',
             '% semantic query: ancestor(X, Y)',
             ':- use_module(library(semweb/rdf_db)).',
         ]},
        {'slug': 'prolog-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Libraries and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Discover SWI-Prolog libraries', 'Use pack install', 'Find community resources', 'Learn more'],
         'prereq': ['Prolog-20: Real-World Applications'],
         'samples': [
             'pack_install(clpfd).',
             '?- pack_list_installed.',
             'help(findall).',
             '% community: SWI-Prolog discourse, /r/prolog',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# PURESCRIPT
# ────────────────────────────────────────────────────────────────────────────
PURESCRIPT = {
    'lang': 'purescript',
    'code_lang': 'purescript',
    'refs': [
        ('PureScript Documentation', 'https://pursuit.purescript.org/', 'Official package search'),
        ('PureScript by Example', 'https://book.purescript.org/', 'The official book'),
        ('PureScript Guide', 'https://github.com/JordanMartinez/purescript-jordans-reference', 'Community reference'),
    ],
    'lessons': [
        {'slug': 'purescript-01-getting-started', 'title': 'Getting Started with PureScript', 'desc': 'Install, spago, hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install PureScript and spago', 'Create a project', 'Write hello world', 'Run with node'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'module Main where\n\nimport Prelude\nimport Effect (Effect)\nimport Effect.Console (log)\n\nmain :: Effect Unit\nmain = log "Hello, World!"',
             'spago init\nspago run',
             'module Main where\n\nimport Prelude\nimport Effect.Console (log)\n\nmain = log "Hello, PureScript!"',
             'spago build\nnode .spago/output/Main/index.js',
         ]},
        {'slug': 'purescript-02-functions', 'title': 'Functions', 'desc': 'Pure functions and type annotations.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write pure functions', 'Annotate types', 'Use application', 'Use operator sections'],
         'prereq': ['PureScript-01: Getting Started with PureScript'],
         'samples': [
             'add :: Int -> Int -> Int\nadd a b = a + b',
             'square :: Int -> Int\nsquare x = x * x',
             'main = log (show (square 5))',
             'double :: Int -> Int\ndouble = (_ * 2)',
         ]},
        {'slug': 'purescript-03-types', 'title': 'Types', 'desc': 'Primitive types and aliases.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use Int, Number, String', 'Use Boolean', 'Define type aliases', 'Use unit'],
         'prereq': ['PureScript-02: Functions'],
         'samples': [
             'x :: Int\nx = 42',
             'pi :: Number\npi = 3.14159',
             'type Name = String\nname :: Name\nname = "Ada"',
             'type Point = { x :: Number, y :: Number }',
         ]},
        {'slug': 'purescript-04-let-where', 'title': 'Let and Where', 'desc': 'Local bindings.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use let bindings', 'Use where clauses', 'Shadow names', 'Structure helpers'],
         'prereq': ['PureScript-03: Types'],
         'samples': [
             'area :: Number -> Number\narea r =\n  let pi = 3.14159\n  in pi * r * r',
             'volume :: Number -> Number\nvolume r = area r * r\n  where\n  area r = pi * r * r\n  pi = 3.14159',
             'main = log (show (area 2.0))',
             'f x = a + b\n  where\n  a = x * 2\n  b = x + 1',
         ]},
        {'slug': 'purescript-05-arrays', 'title': 'Arrays', 'desc': 'Homogeneous collections.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create arrays', 'Use Data.Array functions', 'Map and filter', 'Fold arrays'],
         'prereq': ['PureScript-04: Let and Where'],
         'samples': [
             'import Data.Array (map, filter, foldl)',
             'nums :: Array Int\nnums = [1, 2, 3]',
             'doubled = map (_ * 2) nums',
             'sum = foldl (+) 0 nums',
         ]},
        {'slug': 'purescript-06-records', 'title': 'Records', 'desc': 'Named fields.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create records', 'Access fields', 'Update records', 'Use record puns'],
         'prereq': ['PureScript-05: Arrays'],
         'samples': [
             'type Person = { name :: String, age :: Int }\n\nada :: Person\nada = { name: "Ada", age: 36 }',
             'ada.name',
             'older = ada { age = 37 }',
             'describe :: Person -> String\ndescribe { name, age } = name <> " is " <> show age',
         ]},
        {'slug': 'purescript-07-maybe', 'title': 'Maybe', 'desc': 'Optional values.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use Maybe type', 'Pattern match Just/Nothing', 'Use map on Maybe', 'Use fromMaybe'],
         'prereq': ['PureScript-06: Records'],
         'samples': [
             'import Data.Maybe (Maybe(..))',
             'safeHead :: Array Int -> Maybe Int\nsafeHead [] = Nothing\nsafeHead (x : _) = Just x',
             'main = log (show (safeHead [1, 2]))',
             'import Data.Maybe (fromMaybe)\nvalue = fromMaybe 0 (safeHead [])',
         ]},
        {'slug': 'purescript-08-either', 'title': 'Either', 'desc': 'Typed errors.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use Either type', 'Pattern match Left/Right', 'Use Either as result', 'Map over Right'],
         'prereq': ['PureScript-07: Maybe'],
         'samples': [
             'import Data.Either (Either(..))',
             'divide :: Int -> Int -> Either String Int\ndivide _ 0 = Left "division by zero"\ndivide a b = Right (a / b)',
             'case divide 10 2 of\n  Right n -> log (show n)\n  Left e -> log e',
             'map (_ * 2) (Right 21)',
         ]},
        {'slug': 'purescript-09-pattern-matching', 'title': 'Pattern Matching', 'desc': 'Case expressions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write case expressions', 'Match constructors', 'Use guards', 'Match literals'],
         'prereq': ['PureScript-08: Either'],
         'samples': [
             'describe :: Int -> String\ndescribe n =\n  case n of\n    0 -> "zero"\n    1 -> "one"\n    _ -> "many"',
             'classify :: Int -> String\nclassify n\n  | n < 0 = "negative"\n  | n == 0 = "zero"\n  | otherwise = "positive"',
             'sumPair :: (Int, Int) -> Int\nsumPair (a, b) = a + b',
             'case pair of\n  (0, 0) -> "origin"\n  _ -> "elsewhere"',
         ]},
        {'slug': 'purescript-10-type-classes', 'title': 'Type Classes', 'desc': 'Polymorphic behavior.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Understand type classes', 'Use Show and Eq', 'Define instances', 'Use class constraints'],
         'prereq': ['PureScript-09: Pattern Matching'],
         'samples': [
             'import Prelude (class Show, show)',
             'show 42\nshow "hi"',
             'data Color = Red | Green | Blue\n\ninstance showColor :: Show Color where\n  show Red = "red"\n  show Green = "green"\n  show Blue = "blue"',
             'instance eqColor :: Eq Color where\n  eq Red Red = true\n  eq Green Green = true\n  eq Blue Blue = true\n  eq _ _ = false',
         ]},
        {'slug': 'purescript-11-data-types', 'title': 'Custom Data Types', 'desc': 'Algebraic data types.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define ADTs', 'Use constructors', 'Pattern match variants', 'Carry data in variants'],
         'prereq': ['PureScript-10: Type Classes'],
         'samples': [
             'data Shape = Circle Number | Square Number\n\narea :: Shape -> Number\narea (Circle r) = 3.14159 * r * r\narea (Square s) = s * s',
             'data Maybe a = Nothing | Just a',
             'data State = Loading | Loaded (Array String) | Failed String',
             'data Tree a = Leaf | Node (Tree a) a (Tree a)',
         ]},
        {'slug': 'purescript-12-effect', 'title': 'Effects', 'desc': 'Effect type for side effects.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Understand Effect', 'Run effects in main', 'Sequence effects', 'Use Effect.Console'],
         'prereq': ['PureScript-11: Custom Data Types'],
         'samples': [
             'import Effect (Effect)\nimport Effect.Console (log)',
             'main :: Effect Unit\nmain = do\n  log "line one"\n  log "line two"',
             'main = log (show (1 + 1))',
             'import Effect.Random (random)\nmain = do\n  r <- random\n  log (show r)',
         ]},
        {'slug': 'purescript-13-do-notation', 'title': 'Do Notation', 'desc': 'Sequence computations.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use do blocks', 'Bind with <-', 'Use let in do', 'Sequence IO'],
         'prereq': ['PureScript-12: Effects'],
         'samples': [
             'main = do\n  log "starting"\n  log "done"',
             'main = do\n  x <- pure 5\n  log (show (x * 2))',
             'main = do\n  let name = "Ada"\n  log ("Hello, " <> name)',
             'greet :: Effect Unit\ngreet = do\n  log "Hello!"\n  log "Again!"',
         ]},
        {'slug': 'purescript-14-foreign', 'title': 'Foreign Function Interface', 'desc': 'Call JavaScript.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write FFI files', 'Import JS functions', 'Export to JS', 'Handle unsafe values'],
         'prereq': ['PureScript-13: Do Notation'],
         'samples': [
             '-- src/Math.js\nexports.double = function(x) { return x * 2; };',
             'foreign import double :: Int -> Int',
             'main = log (show (double 21))',
             'foreign import data Date :: Type\nforeign import now :: Effect Date',
         ]},
        {'slug': 'purescript-15-lists', 'title': 'Lists and Folds', 'desc': 'Linked lists.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use Data.List', 'Build lists', 'Fold lists', 'Use list functions'],
         'prereq': ['PureScript-14: Foreign Function Interface'],
         'samples': [
             'import Data.List (List(..), (:))',
             'nums :: List Int\nnums = 1 : 2 : 3 : Nil',
             'sum = foldl (+) 0 nums',
             'map (_ * 2) nums',
         ]},
        {'slug': 'purescript-16-monads', 'title': 'Monads', 'desc': 'The Monad type class.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand Monad', 'Use bind and pure', 'Chain computations', 'Use do with Monads'],
         'prereq': ['PureScript-15: Lists and Folds'],
         'samples': [
             'import Prelude (bind, pure)',
             'compute :: Maybe Int\ncompute = do\n  a <- Just 5\n  b <- Just 3\n  pure (a * b)',
             'eitherCompute :: Either String Int\neitherCompute = do\n  a <- Right 5\n  b <- Right 3\n  pure (a + b)',
             'import Control.Monad.Except (ExceptT, lift)',
         ]},
        {'slug': 'purescript-17-aff', 'title': 'Asynchronous with Aff', 'desc': 'Async programming.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand Aff', 'Delay and timeouts', 'Run parallel effects', 'Handle errors'],
         'prereq': ['PureScript-16: Monads'],
         'samples': [
             'import Effect.Aff (Aff, delay, launchAff_)',
             'import Data.Time.Duration (Milliseconds(..))',
             'main = launchAff_ do\n  delay (Milliseconds 1000.0)\n  log "after 1s"',
             'import Effect.Aff (parallel)\nmain = launchAff_ do\n  result <- parallel (pure 42)\n  log (show result)',
         ]},
        {'slug': 'purescript-18-testing', 'title': 'Testing', 'desc': 'Unit tests with purescript-spec.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Set up purescript-spec', 'Write specs', 'Run tests', 'Test pure functions'],
         'prereq': ['PureScript-17: Asynchronous with Aff'],
         'samples': [
             'import Test.Spec (describe, it, Spec)\nimport Test.Spec.Assertions (shouldEqual)',
             'spec :: Spec Unit\nspec = describe "math" do\n  it "adds" do\n    (2 + 2) `shouldEqual` 4',
             'spago test',
             'it "works with strings" do\n  ("ab" <> "cd") `shouldEqual` "abcd"',
         ]},
        {'slug': 'purescript-19-halogen', 'title': 'UI with Halogen', 'desc': 'Type-safe React-like UI.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Set up Halogen', 'Define components', 'Handle actions', 'Render HTML'],
         'prereq': ['PureScript-18: Testing'],
         'samples': [
             'import Halogen as H\nimport Halogen.HTML as HH\nimport Halogen.HTML.Events as HE',
             'data Action = Increment | Decrement',
             'component :: forall q i o m. H.Component q i o m\ncomponent = H.mkComponent\n  { initialState: const 0\n  , render: render\n  , eval: H.mkEval H.defaultEval { handleAction = handleAction }\n  }',
             'render :: Int -> H.ComponentHTML Action () m\nrender count =\n  HH.div_\n    [ HH.text (show count)\n    , HH.button [ HE.onClick (const Increment) ] [ HH.text "+" ]\n    ]',
         ]},
        {'slug': 'purescript-20-node', 'title': 'Node.js Integration', 'desc': 'Build Node apps.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use node libraries', 'Read files', 'Write HTTP servers', 'Handle process args'],
         'prereq': ['PureScript-19: UI with Halogen'],
         'samples': [
             'import Node.FS.Async (readTextFile, writeTextFile)',
             'import Node.Encoding (Encoding(UTF8))',
             'main = launchAff_ do\n  text <- readTextFile UTF8 "data.txt"\n  log text',
             'import Node.HTTP as HTTP\nmain = HTTP.createServer handler >>= listen 8080',
         ]},
        {'slug': 'purescript-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Pursuit, packages, community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use spago packages', 'Publish packages', 'Discover Pursuit', 'Join the community'],
         'prereq': ['PureScript-20: Node.js Integration'],
         'samples': [
             'spago install halogen',
             'spago search effects',
             'pursuit.purescript.org',
             '// community: PureScript discord, discourse',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# RACKET
# ────────────────────────────────────────────────────────────────────────────
RACKET = {
    'lang': 'racket',
    'code_lang': 'racket',
    'refs': [
        ('Racket Documentation', 'https://docs.racket-lang.org/', 'Official docs'),
        ('How to Design Programs', 'https://htdp.org/', 'The classic textbook'),
        ('Racket Guide', 'https://docs.racket-lang.org/guide/', 'Official language guide'),
    ],
    'lessons': [
        {'slug': 'racket-01-getting-started', 'title': 'Getting Started with Racket', 'desc': 'Install, DrRacket, hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install Racket', 'Use DrRacket IDE', 'Write hello world', 'Run scripts'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '#lang racket\n\n(displayln "Hello, World!")',
             '#lang racket\n(displayln "Hello, ")\n(displayln "Racket!")',
             '#lang racket\n(displayln (+ 1 2))',
             '#lang racket\n(displayln "Racket is a language for making languages")',
         ]},
        {'slug': 'racket-02-forms', 'title': 'Expressions and Values', 'desc': 'S-expressions and evaluation.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Understand S-expressions', 'Evaluate expressions', 'Use literals', 'Quote data'],
         'prereq': ['Racket-01: Getting Started with Racket'],
         'samples': [
             '#lang racket\n(+ 1 2)\n(- 10 4)\n(* 3 4)\n(/ 10 2)',
             '(displayln "hi")\n(displayln 42)',
             "'(1 2 3)",
             '(quote hello)',
         ]},
        {'slug': 'racket-03-definitions', 'title': 'Definitions', 'desc': 'define and let.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Define variables', 'Use let', 'Nest bindings', 'Shadow names'],
         'prereq': ['Racket-02: Expressions and Values'],
         'samples': [
             '#lang racket\n(define name "Ada")\n(displayln name)',
             '(define x 10)\n(define y 20)\n(displayln (+ x y))',
             '(let ([x 10] [y 20])\n  (displayln (+ x y)))',
             '(define pi 3.14159)\n(displayln (* pi 2))',
         ]},
        {'slug': 'racket-04-functions', 'title': 'Functions', 'desc': 'define and lambda.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Define functions', 'Use lambda', 'Apply functions', 'Compose functions'],
         'prereq': ['Racket-03: Definitions'],
         'samples': [
             '#lang racket\n(define (square x) (* x x))\n(displayln (square 5))',
             '(define double (lambda (x) (* x 2)))\n(displayln (double 21))',
             '(map (lambda (x) (* x 2)) (list 1 2 3))',
             '(define (add a b) (+ a b))\n(displayln (add 2 3))',
         ]},
        {'slug': 'racket-05-lists', 'title': 'Lists', 'desc': 'Build and process lists.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create lists', 'Use cons/car/cdr', 'Map and filter', 'Fold lists'],
         'prereq': ['Racket-04: Functions'],
         'samples': [
             '#lang racket\n(define nums (list 1 2 3))\n(displayln nums)',
             '(cons 0 (list 1 2))',
             '(car (list 1 2 3))\n(cdr (list 1 2 3))',
             '(map (lambda (n) (* n 2)) (list 1 2 3))\n(filter odd? (list 1 2 3 4))',
         ]},
        {'slug': 'racket-06-conditionals', 'title': 'Conditionals', 'desc': 'if, cond, and cases.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use if', 'Use cond', 'Use case', 'Use boolean logic'],
         'prereq': ['Racket-05: Lists'],
         'samples': [
             '#lang racket\n(if (> 3 2) "yes" "no")',
             '(cond [(> x 0) "positive"]\n      [(< x 0) "negative"]\n      [else "zero"])',
             '(case 2\n  [(1) "one"]\n  [(2) "two"]\n  [else "other"])',
             '(and #t #f)\n(or #f #t)\n(not #t)',
         ]},
        {'slug': 'racket-07-iteration', 'title': 'Iteration', 'desc': 'for loops and recursion.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use for forms', 'Use recursion', 'Use for/list', 'Use named let'],
         'prereq': ['Racket-06: Conditionals'],
         'samples': [
             '#lang racket\n(for ([i (in-range 5)])\n  (displayln i))',
             '(for/list ([i (in-range 5)])\n  (* i i))',
             '(define (fact n)\n  (if (<= n 1)\n      1\n      (* n (fact (- n 1)))))',
             '(define (sum-list lst)\n  (let loop ([lst lst] [acc 0])\n    (if (null? lst)\n        acc\n        (loop (cdr lst) (+ acc (car lst))))))',
         ]},
        {'slug': 'racket-08-structs', 'title': 'Structs', 'desc': 'Custom data types.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define structs', 'Create instances', 'Access fields', 'Use struct predicates'],
         'prereq': ['Racket-07: Iteration'],
         'samples': [
             '#lang racket\n(struct person (name age))\n(define ada (person "Ada" 36))\n(displayln (person-name ada))',
             '(struct point (x y))\n(define p (point 1 2))',
             '(point? p)\n(person? p)',
             '(struct circle (radius) #:transparent)',
         ]},
        {'slug': 'racket-09-strings', 'title': 'Strings', 'desc': 'String functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Concatenate strings', 'Get length', 'Convert cases', 'Format output'],
         'prereq': ['Racket-08: Structs'],
         'samples': [
             '#lang racket\n(string-append "Hello" " " "World")',
             '(string-length "hello")',
             '(string-upcase "hi")\n(string-downcase "HI")',
             '(format "value: ~a" 42)',
         ]},
        {'slug': 'racket-10-higher-order', 'title': 'Higher-Order Functions', 'desc': 'Functions as values.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Pass functions', 'Return functions', 'Use curry', 'Use compose'],
         'prereq': ['Racket-09: Strings'],
         'samples': [
             '#lang racket\n(define (apply-twice f x) (f (f x)))\n(displayln (apply-twice add1 5))',
             '(define (adder n) (lambda (x) (+ x n)))\n(define add5 (adder 5))\n(displayln (add5 10))',
             '((compose add1 add1) 5)',
             '(curry + 5)',
         ]},
        {'slug': 'racket-11-hash-tables', 'title': 'Hash Tables', 'desc': 'Key-value storage.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create hash tables', 'Set and get', 'Iterate entries', 'Remove keys'],
         'prereq': ['Racket-10: Higher-Order Functions'],
         'samples': [
             '#lang racket\n(define ht (make-hash))\n(hash-set! ht "key" 42)\n(displayln (hash-ref ht "key"))',
             '(hash-ref ht "missing" 0)',
             '(hash-keys ht)',
             '(hash-remove! ht "key")',
         ]},
        {'slug': 'racket-12-exceptions', 'title': 'Exceptions', 'desc': 'Raise and handle errors.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Raise errors', 'Handle with with-handlers', 'Use error', 'Create custom errors'],
         'prereq': ['Racket-11: Hash Tables'],
         'samples': [
             '#lang racket\n(with-handlers ([exn:fail? (lambda (e) (displayln "caught"))])\n  (error "boom"))',
             '(raise "simple error")',
             '(with-handlers ([exn:fail:contract? (lambda (e) "contract error")])\n  (car 5))',
             '(error "custom message")',
         ]},
        {'slug': 'racket-13-io', 'title': 'Input/Output', 'desc': 'Read and write.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write to stdout', 'Read from stdin', 'Read files', 'Write files'],
         'prereq': ['Racket-12: Exceptions'],
         'samples': [
             '#lang racket\n(displayln "hello")\n(display "no newline")',
             '(define line (read-line))\n(displayln line)',
             '(define text (file->string "data.txt"))',
             '(call-with-output-file "out.txt"\n  (lambda (out) (displayln "hello" out)))',
         ]},
        {'slug': 'racket-14-macros', 'title': 'Macros', 'desc': 'Code generation.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write define-syntax-rule', 'Use syntax-parse', 'Generate code', 'Build DSLs'],
         'prereq': ['Racket-13: Input/Output'],
         'samples': [
             '#lang racket\n(define-syntax-rule (twice expr)\n  (begin expr expr))\n\n(twice (displayln "hi"))',
             '(define-syntax-rule (unless test body ...)\n  (when (not test) body ...))',
             '(require syntax/parse)\n(define-syntax (my-let stx)\n  (syntax-parse stx\n    [(_ (x val) body ...)\n     #\'(let ([x val]) body ...)]))',
             '(define-syntax-rule (defn name args body ...)\n  (define (name args) body ...))',
         ]},
        {'slug': 'racket-15-modules', 'title': 'Modules', 'desc': 'Organize Racket code.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Create modules', 'Require modules', 'Provide bindings', 'Use contracts'],
         'prereq': ['Racket-14: Macros'],
         'samples': [
             '#lang racket\n(provide square)\n(define (square x) (* x x))',
             '(require "math.rkt")\n(square 5)',
             '(provide (all-defined-out))',
             '(provide (contract-out\n           [square (-> number? number?)]))',
         ]},
        {'slug': 'racket-16-matching', 'title': 'Pattern Matching', 'desc': 'match expressions.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use match', 'Match structures', 'Use match-let', 'Bind with patterns'],
         'prereq': ['Racket-15: Modules'],
         'samples': [
             '#lang racket\n(match 5\n  [0 "zero"]\n  [n (format "number ~a" n)])',
             '(match (list 1 2 3)\n  [(list a b c) (+ a b c)])',
             '(match (struct point (1 2))\n  [(point x y) (+ x y)])',
             '(match-define (list a b) (list 1 2))\na',
         ]},
        {'slug': 'racket-17-oop', 'title': 'Objects and Classes', 'desc': 'Racket OOP.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Define classes', 'Create instances', 'Use methods', 'Use inheritance'],
         'prereq': ['Racket-16: Pattern Matching'],
         'samples': [
             '#lang racket\n(define animal%\n  (class object%\n    (super-new)\n    (define/public (speak) "...")))',
             '(define dog%\n  (class animal%\n    (super-new)\n    (define/override (speak) "Woof")))',
             '(define d (new dog%))\n(send d speak)',
             '(define counter%\n  (class object%\n    (super-new)\n    (define count 0)\n    (define/public (increment!) (set! count (add1 count)))\n    (define/public (get-count) count)))',
         ]},
        {'slug': 'racket-18-threads', 'title': 'Threads and Concurrency', 'desc': 'Parallel execution.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Spawn threads', 'Use semaphores', 'Synchronize access', 'Use channels'],
         'prereq': ['Racket-17: Objects and Classes'],
         'samples': [
             '#lang racket\n(thread (lambda () (displayln "in thread")))',
             '(define s (make-semaphore 1))\n(semaphore-wait s)\n; critical section\n(semaphore-post s)',
             '(define ch (make-channel))\n(thread (lambda () (channel-put ch 42)))\n(displayln (channel-get ch))',
             '(make-thread-pool 4)',
         ]},
        {'slug': 'racket-19-gui', 'title': 'GUI Programming', 'desc': 'Build interfaces with racket/gui.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create a frame', 'Add widgets', 'Handle events', 'Run the event loop'],
         'prereq': ['Racket-18: Threads and Concurrency'],
         'samples': [
             '#lang racket\n(require racket/gui/base)\n\n(define frame (new frame% [label "Hello"] [width 300] [height 200]))\n(send frame show #t)',
             '(define msg (new message% [parent frame] [label "Hello, World!"]))',
             '(define btn (new button% [parent frame] [label "Click"]\n                          [callback (lambda (b e) (displayln "clicked"))]))',
             '(require racket/gui/base)',
         ]},
        {'slug': 'racket-20-http', 'title': 'Web Servers', 'desc': 'Serve HTTP with Racket.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Start a web server', 'Serve responses', 'Define routes', 'Serve JSON'],
         'prereq': ['Racket-19: GUI Programming'],
         'samples': [
             '''#lang racket
(require web-server/servlet
         web-server/servlet-env)

(define (start request)
  (response/xexpr #:mime-type "text/html"
                  '(html (body (p "Hello, World!")))))

(run-web-server start)'''
             '(response/xexpr #:mime-type "application/json"\n                (jsexpr->xexpr (list "key" "value")))',
             '(serve/servlet start #:port 8080)',
             '(response/output #:mime-type "text/plain"\n                (lambda (out) (display "hello" out)))',
         ]},
        {'slug': 'racket-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Raco, packages, community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use raco', 'Install packages', 'Create packages', 'Join the community'],
         'prereq': ['Racket-20: Web Servers'],
         'samples': [
             'raco pkg install beautiful-racket',
             'raco pkg search json',
             'raco make main.rkt',
             '// community: racket.discourse.group, #racket on IRC',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# SCHEME
# ────────────────────────────────────────────────────────────────────────────
SCHEME = {
    'lang': 'scheme',
    'code_lang': 'scheme',
    'refs': [
        ('Scheme Reports', 'https://small.r7rs.org/', 'The R7RS specification'),
        ('Structure and Interpretation of Computer Programs', 'https://mitp-press.mit.edu/sites/default/files/sicp/full-text/book/book.html', 'SICP — the classic book'),
        ('The Scheme Programming Language', 'https://www.scheme.com/tspl4/', 'Dybvig\'s book'),
    ],
    'lessons': [
        {'slug': 'scheme-01-getting-started', 'title': 'Getting Started with Scheme', 'desc': 'Install a Scheme, hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install a Scheme implementation', 'Write hello world', 'Evaluate expressions', 'Run scripts'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '(display "Hello, World!")\n(newline)',
             '(displayln "Hello, World!")   ; some implementations',
             'guile -s hello.scm',
             '(display (+ 1 2))\n(newline)',
         ]},
        {'slug': 'scheme-02-expressions', 'title': 'Expressions and Values', 'desc': 'Prefix notation and evaluation.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use prefix notation', 'Evaluate arithmetic', 'Use literals', 'Quote expressions'],
         'prereq': ['Scheme-01: Getting Started with Scheme'],
         'samples': [
             '(+ 1 2)\n(- 10 4)\n(* 3 4)\n(/ 10 2)',
             '(sqrt 16)',
             "'(1 2 3)",
             '(display (* 2 (+ 3 4)))',
         ]},
        {'slug': 'scheme-03-definitions', 'title': 'Definitions and Binding', 'desc': 'define and let.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Define variables', 'Use let', 'Define functions', 'Nest bindings'],
         'prereq': ['Scheme-02: Expressions and Values'],
         'samples': [
             '(define name "Ada")\n(display name)',
             '(let ((x 10) (y 20)) (+ x y))',
             '(define (square x) (* x x))',
             '(define pi 3.14159)',
         ]},
        {'slug': 'scheme-04-functions', 'title': 'Functions', 'desc': 'define and lambda.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Define functions', 'Use lambda', 'Pass functions', 'Use variadic functions'],
         'prereq': ['Scheme-03: Definitions and Binding'],
         'samples': [
             '(define (add a b) (+ a b))\n(add 2 3)',
             '(define double (lambda (x) (* x 2)))\n(double 21)',
             '(map (lambda (x) (* x x)) (list 1 2 3))',
             '(define (sum . nums) (apply + nums))',
         ]},
        {'slug': 'scheme-05-lists', 'title': 'Lists', 'desc': 'The fundamental data structure.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create lists', 'Use car and cdr', 'Use cons', 'Process lists'],
         'prereq': ['Scheme-04: Functions'],
         'samples': [
             '(list 1 2 3)',
             '(cons 0 (list 1 2))',
             '(car (list 1 2 3))\n(cdr (list 1 2 3))',
             '(map (lambda (x) (* x 2)) (list 1 2 3))',
         ]},
        {'slug': 'scheme-06-conditionals', 'title': 'Conditionals', 'desc': 'if and cond.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use if', 'Use cond', 'Use boolean logic', 'Use predicates'],
         'prereq': ['Scheme-05: Lists'],
         'samples': [
             '(if (> 3 2) "yes" "no")',
             '(cond ((> x 0) "positive")\n      ((< x 0) "negative")\n      (else "zero"))',
             '(and #t #f)\n(or #t #f)\n(not #t)',
             '(number? 5)\n(string? "hi")',
         ]},
        {'slug': 'scheme-07-recursion', 'title': 'Recursion', 'desc': 'Recursive definitions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write recursive functions', 'Use tail recursion', 'Use named let', 'Process trees'],
         'prereq': ['Scheme-06: Conditionals'],
         'samples': [
             '(define (fact n)\n  (if (<= n 1)\n      1\n      (* n (fact (- n 1)))))',
             '(define (loop acc n)\n  (if (= n 0)\n      acc\n      (loop (+ acc n) (- n 1))))',
             '(define (length lst)\n  (if (null? lst)\n      0\n      (+ 1 (length (cdr lst)))))',
             '(define (even-count lst)\n  (let loop ((l lst) (acc 0))\n    (cond ((null? l) acc)\n          ((even? (car l)) (loop (cdr l) (+ acc 1)))\n          (else (loop (cdr l) acc)))))',
         ]},
        {'slug': 'scheme-08-higher-order', 'title': 'Higher-Order Functions', 'desc': 'Abstract over functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use map', 'Use filter', 'Use fold', 'Compose functions'],
         'prereq': ['Scheme-07: Recursion'],
         'samples': [
             '(map (lambda (x) (* x 2)) (list 1 2 3))',
             '(filter even? (list 1 2 3 4))',
             '(fold-left + 0 (list 1 2 3))',
             '(define (compose f g) (lambda (x) (f (g x))))',
         ]},
        {'slug': 'scheme-09-strings', 'title': 'Strings', 'desc': 'String operations.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Concatenate strings', 'Get string length', 'Convert cases', 'Format strings'],
         'prereq': ['Scheme-08: Higher-Order Functions'],
         'samples': [
             '(string-append "Hello" " " "World")',
             '(string-length "hello")',
             '(string-upcase "hi")',
             '(number->string 42)',
         ]},
        {'slug': 'scheme-10-vectors', 'title': 'Vectors', 'desc': 'Random-access arrays.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create vectors', 'Access elements', 'Update elements', 'Convert to lists'],
         'prereq': ['Scheme-09: Strings'],
         'samples': [
             '(vector 1 2 3)',
             '(vector-ref (vector 1 2 3) 1)',
             '(define v (make-vector 3 0))\n(vector-set! v 0 42)',
             '(vector->list (vector 1 2))',
         ]},
        {'slug': 'scheme-11-pairs', 'title': 'Pairs and Association Lists', 'desc': 'Key-value pairs.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create pairs', 'Use assoc', 'Use assq', 'Build association lists'],
         'prereq': ['Scheme-10: Vectors'],
         'samples': [
             '(cons "key" 42)',
             '(assoc "key" (list (cons "key" 42)))',
             '(assq \'a \'((a . 1) (b . 2)))',
             '(define al \'((a . 1) (b . 2)))\n(cdr (assq \'a al))',
         ]},
        {'slug': 'scheme-12-io', 'title': 'Input/Output', 'desc': 'Read and write.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Display output', 'Read input', 'Read files', 'Write files'],
         'prereq': ['Scheme-11: Pairs and Association Lists'],
         'samples': [
             '(display "hello")\n(newline)',
             '(define line (read-line))\n(display line)',
             '(call-with-input-file "data.txt" (lambda (in) (read-line in)))',
             '(call-with-output-file "out.txt" (lambda (out) (display "hello" out)))',
         ]},
        {'slug': 'scheme-13-macros', 'title': 'Macros', 'desc': 'define-syntax and hygiene.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write define-syntax-rule', 'Use syntax-rules', 'Generate code', 'Understand hygiene'],
         'prereq': ['Scheme-12: Input/Output'],
         'samples': [
             '(define-syntax-rule (twice expr)\n  (begin expr expr))\n\n(twice (display "hi"))',
             '(define-syntax my-when\n  (syntax-rules ()\n    [(_ test body ...)\n     (if test (begin body ...))]))',
             '(my-when (> 3 2) (display "yes"))',
             '(define-syntax-rule (unless test body ...)\n  (when (not test) body ...))',
         ]},
        {'slug': 'scheme-14-tail-calls', 'title': 'Tail Calls and CPS', 'desc': 'Efficient recursion.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand tail calls', 'Write accumulator style', 'Use call/cc', 'Understand continuations'],
         'prereq': ['Scheme-13: Macros'],
         'samples': [
             '(define (loop acc n)\n  (if (= n 0) acc (loop (+ acc n) (- n 1))))\n(loop 0 1000000)',
             '(define (fact n) (fact-iter n 1))\n(define (fact-iter n acc)\n  (if (= n 0) acc (fact-iter (- n 1) (* n acc))))',
             '(call/cc (lambda (k) (k 42)))',
             '(define (double k) (k 42))',
         ]},
        {'slug': 'scheme-15-delay', 'title': 'Lazy Evaluation', 'desc': 'delay and force.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use delay', 'Use force', 'Build lazy streams', 'Memoize values'],
         'prereq': ['Scheme-14: Tail Calls and CPS'],
         'samples': [
             '(define x (delay (* 3 4)))\n(force x)',
             '(define (stream-cons a b) (cons a (delay b)))',
             '(define (stream-car s) (car s))\n(define (stream-cdr s) (force (cdr s)))',
             '(define ones (cons 1 (delay ones)))',
         ]},
        {'slug': 'scheme-16-oop', 'title': 'OOP in Scheme', 'desc': 'Object patterns.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Build objects with closures', 'Encapsulate state', 'Create messages', 'Use dispatch'],
         'prereq': ['Scheme-15: Lazy Evaluation'],
         'samples': [
             '(define (make-counter)\n  (let ((count 0))\n    (lambda (msg)\n      (case msg\n        ((inc) (set! count (+ count 1)))\n        ((get) count)))))',
             '(define c (make-counter))\n(c \'inc)\n(c \'get)',
             '(define (make-point x y)\n  (lambda (op)\n    (cond ((eq? op \'x) x)\n          ((eq? op \'y) y))))',
             '(define (make-account balance)\n  (lambda (amount)\n    (set! balance (+ balance amount))\n    balance))',
         ]},
        {'slug': 'scheme-17-databases', 'title': 'Symbolic Computation', 'desc': 'Manipulate expressions.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Represent expressions as data', 'Differentiate symbolically', 'Simplify expressions', 'Build evaluators'],
         'prereq': ['Scheme-16: OOP in Scheme'],
         'samples': [
             "(define expr '(+ (* x x) (* 2 x) 1))",
             "(define (deriv exp var)\n  (cond ((number? exp) 0)\n        ((symbol? exp) (if (eq? exp var) 1 0))\n        ((eq? (car exp) '+) (list '+ (deriv (cadr exp) var) (deriv (caddr exp) var)))\n        (else 'unknown)))",
             "(deriv '(* x x) 'x)",
             "(define (eval-expr exp)\n  (cond ((number? exp) exp)\n        ((eq? (car exp) '+) (+ (eval-expr (cadr exp)) (eval-expr (caddr exp))))))",
         ]},
        {'slug': 'scheme-18-meta', 'title': 'Metacircular Evaluators', 'desc': 'Write an interpreter.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand eval and apply', 'Build a mini interpreter', 'Handle environments', 'Extend the language'],
         'prereq': ['Scheme-17: Symbolic Computation'],
         'samples': [
             '(define (my-eval exp env)\n  (cond ((number? exp) exp)\n        ((symbol? exp) (lookup exp env))\n        ((eq? (car exp) \'quote) (cadr exp))\n        ((eq? (car exp) \'if) (if (my-eval (cadr exp) env)\n                                 (my-eval (caddr exp) env)\n                                 (my-eval (cadddr exp) env)))\n        ((eq? (car exp) \'lambda) (list \'closure (cadr exp) (cddr exp) env))\n        (else (apply-proc (my-eval (car exp) env)\n                          (map (lambda (e) (my-eval e env)) (cdr exp))))))',
             '(define (apply-proc proc args) (car proc))  ; simplified',
             '(define env \'((x . 10)))',
             '(lookup \'x env)',
         ]},
        {'slug': 'scheme-19-ffi', 'title': 'Interfacing with C', 'desc': 'Call C from Scheme.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use FFI libraries', 'Call C functions', 'Pass numbers', 'Handle strings'],
         'prereq': ['Scheme-18: Metacircular Evaluators'],
         'samples': [
             ';; Guile:\n(use-modules (system foreign))',
             '''(define libc (dynamic-link "libc"))
(define strlen (pointer->procedure size_t (dynamic-func "strlen" libc) (list '*)))'''
             '(strlen (string->pointer "hello"))',
             ';; Racket: (require ffi/unsafe)',
         ]},
        {'slug': 'scheme-20-web', 'title': 'Web Development', 'desc': 'Serve web pages.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create HTTP servers', 'Serve HTML', 'Handle routes', 'Read request data'],
         'prereq': ['Scheme-19: Interfacing with C'],
         'samples': [
             ';; Guile:\n(use-modules (web server) (web response))',
             '(define (handler request body)\n  (values (build-response #:code 200)\n          (string->utf8 "Hello, World!")))',
             '(run-server handler)',
             '(define (handler req body)\n  (values (build-response #:content-type \'text/html)\n          (string->utf8 "<h1>Hello</h1>")))',
         ]},
        {'slug': 'scheme-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Implementations and resources.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Know Scheme implementations', 'Choose a REPL', 'Find learning resources', 'Explore R7RS'],
         'prereq': ['Scheme-20: Web Development'],
         'samples': [
             ';; Implementations: Guile, Chez, Racket (with #lang), Chicken, Gauche',
             'guile --interactive',
             'chezscheme --program hello.sps',
             ';; Read SICP for the definitive deep dive',
         ]},
    ],
}

SPECS = [PROLOG, PURESCRIPT, RACKET, SCHEME]
