#!/usr/bin/env python3
"""Lesson specs for gleam, haxe, labview, matlab — real 21-lesson courses."""

# ────────────────────────────────────────────────────────────────────────────
# GLEAM
# ────────────────────────────────────────────────────────────────────────────
GLEAM = {
    'lang': 'gleam',
    'code_lang': 'gleam',
    'refs': [
        ('Gleam Documentation', 'https://gleam.run/documentation/', 'Official docs'),
        ('Gleam Language Tour', 'https://tour.gleam.run/', 'Interactive tour'),
        ('Gleam Book', 'https://gleam.run/book/', 'The official book'),
    ],
    'lessons': [
        {'slug': 'gleam-01-getting-started', 'title': 'Getting Started with Gleam', 'desc': 'Install, project setup, hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install Gleam', 'Create a project', 'Write hello world', 'Run with gleam run'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'import gleam/io\n\npub fn main() {\n  io.println("Hello, World!")\n}',
             'gleam new hello\ncd hello && gleam run',
             'import gleam/io\n\npub fn main() {\n  io.println("Hello, " <> "Gleam!")\n}',
             'import gleam/io\n\npub fn main() {\n  let name = "Ada"\n  io.println("Hello, " <> name)\n}',
         ]},
        {'slug': 'gleam-02-values', 'title': 'Values and Types', 'desc': 'Integers, floats, strings, bools.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use integer and float types', 'Work with strings', 'Use booleans', 'Use type annotations'],
         'prereq': ['Gleam-01: Getting Started with Gleam'],
         'samples': [
             'pub fn main() {\n  let x = 42\n  let pi = 3.14\n  io.debug(x)\n  io.debug(pi)\n}',
             'let name: String = "Ada"\nlet age: Int = 36',
             'let ok = True\nlet not_ok = False',
             'io.debug(1 + 2)\nio.debug(1.5 + 2.5)',
         ]},
        {'slug': 'gleam-03-control-flow', 'title': 'Control Flow', 'desc': 'case expressions and pattern matching.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use case expressions', 'Pattern match values', 'Use guards', 'Handle multiple patterns'],
         'prereq': ['Gleam-02: Values and Types'],
         'samples': [
             'import gleam/io\n\npub fn describe(n: Int) -> String {\n  case n {\n    0 -> "zero"\n    1 -> "one"\n    _ -> "many"\n  }\n}\n\npub fn main() {\n  io.println(describe(2))\n}',
             'pub fn grade(score: Int) -> String {\n  case score {\n    s if s >= 90 -> "A"\n    s if s >= 80 -> "B"\n    _ -> "C"\n  }\n}',
             'case pair {\n  (0, 0) -> "origin"\n  _ -> "elsewhere"\n}',
             'case list {\n  [] -> "empty"\n  [first, ..rest] -> "has items"\n}',
         ]},
        {'slug': 'gleam-04-functions', 'title': 'Functions', 'desc': 'Typed functions and pipelines.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write typed functions', 'Use pipelines with |>', 'Use anonymous functions', 'Compose functions'],
         'prereq': ['Gleam-03: Control Flow'],
         'samples': [
             'pub fn add(a: Int, b: Int) -> Int {\n  a + b\n}',
             'pub fn double(x: Int) -> Int {\n  x * 2\n}\n\npub fn main() {\n  21 |> double |> io.debug\n}',
             'let square = fn(x) { x * x }\nio.debug(square(5))',
             'pub fn apply(f: fn(Int) -> Int, x: Int) -> Int {\n  f(x)\n}',
         ]},
        {'slug': 'gleam-05-lists', 'title': 'Lists', 'desc': 'Immutable lists and List functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Build lists', 'Use list.append', 'Map and filter', 'Fold lists'],
         'prereq': ['Gleam-04: Functions'],
         'samples': [
             'import gleam/list\n\npub fn main() {\n  let nums = [1, 2, 3]\n  io.debug(nums)\n}',
             'import gleam/list\n\nlet doubled = list.map([1, 2, 3], fn(n) { n * 2 })',
             'let evens = list.filter([1, 2, 3, 4], fn(n) { n % 2 == 0 })',
             'let sum = list.fold([1, 2, 3], 0, fn(acc, n) { acc + n })',
         ]},
        {'slug': 'gleam-06-result', 'title': 'Result and Error Handling', 'desc': 'Typed errors with Result.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use Result type', 'Pattern match Ok/Error', 'Use result.try', 'Map results'],
         'prereq': ['Gleam-05: Lists'],
         'samples': [
             'import gleam/result\n\npub fn divide(a: Int, b: Int) -> Result(Int, String) {\n  case b {\n    0 -> Error("division by zero")\n    _ -> Ok(a / b)\n  }\n}',
             'case divide(10, 2) {\n  Ok(n) -> io.debug(n)\n  Error(e) -> io.println(e)\n}',
             'import gleam/result\n\npub fn compute() -> Result(Int, String) {\n  use a <- result.try(divide(10, 2))\n  use b <- result.try(divide(a, 2))\n  Ok(b)\n}',
             'result.map(Ok(4), fn(n) { n * 2 })',
         ]},
        {'slug': 'gleam-07-option', 'title': 'Option Types', 'desc': 'Handle missing values.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use Option type', 'Pattern match Some/None', 'Use option.unwrap', 'Chain options'],
         'prereq': ['Gleam-06: Result and Error Handling'],
         'samples': [
             'import gleam/option\n\npub fn find(list: List(Int), target: Int) -> Option(Int) {\n  case list {\n    [] -> None\n    [x, ..rest] -> case x == target {\n      True -> Some(x)\n      False -> find(rest, target)\n    }\n  }\n}',
             'case find([1, 2, 3], 2) {\n  Some(v) -> io.debug(v)\n  None -> io.println("not found")\n}',
             'import gleam/option\n\nlet value = option.unwrap(find([1], 1), 0)',
             'option.map(Some(4), fn(n) { n * 2 })',
         ]},
        {'slug': 'gleam-08-custom-types', 'title': 'Custom Types', 'desc': 'Model data with tagged unions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define custom types', 'Create values', 'Pattern match variants', 'Carry data in variants'],
         'prereq': ['Gleam-07: Option Types'],
         'samples': [
             'pub type Colour {\n  Red\n  Green\n  Blue\n}',
             'pub type Shape {\n  Circle(Float)\n  Square(Float)\n}\n\npub fn area(s: Shape) -> Float {\n  case s {\n    Circle(r) -> 3.14159 *. r *. r\n    Square(side) -> side *. side\n  }\n}',
             'pub type State {\n  Loading\n  Loaded(List(String))\n  Failed(String)\n}',
             'let color = Red\nlet shape = Circle(2.0)',
         ]},
        {'slug': 'gleam-09-records', 'title': 'Records', 'desc': 'Named fields and updates.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define record types', 'Create records', 'Access fields', 'Update records'],
         'prereq': ['Gleam-08: Custom Types'],
         'samples': [
             'pub type Person {\n  Person(name: String, age: Int)\n}\n\nlet ada = Person("Ada", 36)',
             'io.debug(ada.name)',
             'let older = Person(..ada, age: 37)',
             'pub fn describe(p: Person) -> String {\n  p.name <> " is " <> int.to_string(p.age)\n}',
         ]},
        {'slug': 'gleam-10-modules', 'title': 'Modules', 'desc': 'Organize code with modules.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create modules', 'Import modules', 'Control exports', 'Use aliases'],
         'prereq': ['Gleam-09: Records'],
         'samples': [
             '// src/math.gleam\npub fn square(x: Int) -> Int {\n  x * x\n}',
             'import math\n\npub fn main() {\n  io.debug(math.square(5))\n}',
             'import gleam/string as str\n\npub fn main() {\n  io.println(str.uppercase("hi"))\n}',
             'pub fn public_fn() { "visible" }\nfn private_fn() { "hidden" }',
         ]},
        {'slug': 'gleam-11-strings', 'title': 'String Functions', 'desc': 'Manipulate text.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Concatenate strings', 'Split and join', 'Get length', 'Convert cases'],
         'prereq': ['Gleam-10: Modules'],
         'samples': [
             'import gleam/string\n\npub fn main() {\n  io.println(string.concat(["a", "b", "c"]))\n}',
             'let parts = string.split("a,b,c", ",")',
             'io.debug(string.length("hello"))',
             'io.println(string.uppercase("hello"))',
         ]},
        {'slug': 'gleam-12-map', 'title': 'Maps', 'desc': 'Key-value storage.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create maps', 'Insert and get', 'Iterate entries', 'Update values'],
         'prereq': ['Gleam-11: String Functions'],
         'samples': [
             'import gleam/map\n\npub fn main() {\n  let ages = map.new()\n  let ages = map.insert(ages, "Ada", 36)\n  io.debug(ages)\n}',
             'map.get(ages, "Ada")',
             'let ages = map.insert(ages, "Grace", 85)\nmap.keys(ages)',
             'map.values(ages)',
         ]},
        {'slug': 'gleam-13-io-ffi', 'title': 'IO and FFI', 'desc': 'Interact with the outside world.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Print and read input', 'Use external functions', 'Call Erlang or JS', 'Handle untrusted code'],
         'prereq': ['Gleam-12: Maps'],
         'samples': [
             'import gleam/io\n\npub fn main() {\n  io.println("hello")\n}',
             'pub external fn system_time() -> Int =\n  "erlang" "system_time"\n\n  "node" "Date.now"',
             '@external(javascript, "console", "log")\npub fn log(msg: String) -> Nil',
             'import gleam/dynamic\n\npub fn to_int(value: dynamic.Dynamic) -> Result(Int, String) {\n  dynamic.int(value)\n}',
         ]},
        {'slug': 'gleam-14-generics', 'title': 'Generics', 'desc': 'Type-parameterized code.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write generic types', 'Write generic functions', 'Use type variables', 'Build containers'],
         'prereq': ['Gleam-13: IO and FFI'],
         'samples': [
             'pub type Box(a) {\n  Box(value: a)\n}',
             'pub fn identity(value: a) -> a {\n  value\n}',
             'pub fn first(list: List(a)) -> Option(a) {\n  case list {\n    [x, ..] -> Some(x)\n    [] -> None\n  }\n}',
             'pub type Result(a, e) {\n  Ok(a)\n  Error(e)\n}',
         ]},
        {'slug': 'gleam-15-erlang', 'title': 'The Erlang Runtime', 'desc': 'BEAM VM and OTP.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand the BEAM', 'Use processes', 'Send messages', 'Leverage OTP'],
         'prereq': ['Gleam-14: Generics'],
         'samples': [
             'import gleam/erlang/process\n\npub fn main() {\n  let pid = process.new(fn() { io.println("hi") })\n  process.send(pid, 42)\n}',
             'let subject = process.new_subject()\nprocess.send(subject, "hello")',
             'let mailbox = process.new_mailbox()\nprocess.send(mailbox, 42)',
             '// run on BEAM: gleam run --target erlang',
         ]},
        {'slug': 'gleam-16-todo-app', 'title': 'Build a CLI Tool', 'desc': 'Parse args and build tools.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Parse command-line args', 'Structure a CLI', 'Handle options', 'Exit with codes'],
         'prereq': ['Gleam-15: The Erlang Runtime'],
         'samples': [
             'import gleam/argv\n\npub fn main() {\n  let args = argv.load()\n  io.debug(args)\n}',
             'pub fn main() {\n  case argv.load() {\n    [] -> io.println("usage: app NAME")\n    [name] -> io.println("Hello, " <> name)\n    _ -> io.println("too many args")\n  }\n}',
             'import gleam/erlang/process\n\nprocess.exit(0)',
             'io.println("done")',
         ]},
        {'slug': 'gleam-17-http-server', 'title': 'HTTP Servers', 'desc': 'Build web services.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create an HTTP server', 'Define routes', 'Return JSON', 'Handle requests'],
         'prereq': ['Gleam-16: Build a CLI Tool'],
         'samples': [
             'import gleam/erlang/process\nimport mist\n\npub fn main() {\n  let handler = fn(_req) {\n    mist.new_response(200)\n    |> mist.set_body("Hello, World!")\n  }\n  let _ = mist.new(handler)\n  |> mist.port(8080)\n  |> start\n}',
             '// routes via pattern matching on path',
             'import gleam/json\n\nlet body = json.object([#("name", json.string("Ada"))])\n|> json.to_string',
             'mist.set_header("Content-Type", "application/json")',
         ]},
        {'slug': 'gleam-18-json', 'title': 'JSON', 'desc': 'Encode and decode JSON.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Build JSON values', 'Encode to string', 'Decode with dynamic', 'Validate shapes'],
         'prereq': ['Gleam-17: HTTP Servers'],
         'samples': [
             'import gleam/json\n\nlet value = json.object([\n  #("name", json.string("Ada")),\n  #("age", json.int(36)),\n])\n\nlet text = json.to_string(value)',
             'let decoded = json.decode(text)',
             'import gleam/dynamic\n\ndynamic.field(decoded, "name") |> dynamic.string',
             'json.string("hello") |> json.to_string',
         ]},
        {'slug': 'gleam-19-testing', 'title': 'Testing', 'desc': 'Write unit tests with gleeunit.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Set up gleeunit', 'Write test functions', 'Run gleam test', 'Test pure functions'],
         'prereq': ['Gleam-18: JSON'],
         'samples': [
             'import gleeunit\nimport gleeunit/should\n\npub fn main() {\n  gleeunit.main()\n}\n\npub fn add(a: Int, b: Int) -> Int {\n  a + b\n}\n\npub fn add_test() {\n  should.equal(add(2, 3), 5)\n}',
             'gleam test',
             'pub fn square_test() {\n  should.equal(square(4), 16)\n}',
             'should.equal(string.uppercase("hi"), "HI")',
         ]},
        {'slug': 'gleam-20-project-structure', 'title': 'Project Structure', 'desc': 'Organize a real project.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Structure modules sensibly', 'Manage dependencies', 'Use gleam.toml', 'Document code'],
         'prereq': ['Gleam-19: Testing'],
         'samples': [
             'name = "hello"\nversion = "1.0.0"\n\n[dependencies]\ngleam_stdlib = "~> 0.34"\n',
             'gleam add mist\n# or: gleam add gleam/http',
             'gleam run\n# dev workflow',
             'pub fn documented_fn() { /* doc comments above */ }',
         ]},
        {'slug': 'gleam-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Packages and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Publish packages', 'Discover the ecosystem', 'Understand targets', 'Join the community'],
         'prereq': ['Gleam-20: Project Structure'],
         'samples': [
             'gleam publish',
             'gleam search http',
             '// targets: erlang (BEAM) and javascript (node/browser)',
             '// community: gleam.run, discord, GitHub',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# HAXE
# ────────────────────────────────────────────────────────────────────────────
HAXE = {
    'lang': 'haxe',
    'code_lang': 'haxe',
    'refs': [
        ('Haxe Documentation', 'https://haxe.org/documentation/', 'Official docs'),
        ('Haxe Manual', 'https://haxe.org/manual/introduction.html', 'The language manual'),
        ('Haxe Cookbook', 'https://code.haxe.org/', 'Community recipes'),
    ],
    'lessons': [
        {'slug': 'haxe-01-getting-started', 'title': 'Getting Started with Haxe', 'desc': 'Install, compile targets, hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install Haxe', 'Write hello world', 'Compile to multiple targets', 'Use the build tool'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'class Main {\n  static function main() {\n    trace("Hello, World!");\n  }\n}',
             'haxe -main Main -neko hello.n\nneko hello.n',
             'haxe -main Main -js hello.js\nnode hello.js',
             'haxe -main Main -cpp bin',
         ]},
        {'slug': 'haxe-02-types', 'title': 'Types and Variables', 'desc': 'Static typing with inference.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare typed variables', 'Use type inference', 'Use constants', 'Understand the type system'],
         'prereq': ['Haxe-01: Getting Started with Haxe'],
         'samples': [
             'var score:Int = 0;\nvar name:String = "Ada";\nvar speed:Float = 2.5;',
             'var x = 42;    // inferred Int',
             'var pi = 3.14; // inferred Float',
             'static inline var MAX = 100;',
         ]},
        {'slug': 'haxe-03-control-flow', 'title': 'Control Flow', 'desc': 'if, switch, and loops.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/else', 'Use switch with type patterns', 'Use for loops', 'Use while loops'],
         'prereq': ['Haxe-02: Types and Variables'],
         'samples': [
             'var grade = 85;\nif (grade >= 90) trace("A");\nelse if (grade >= 80) trace("B");\nelse trace("C");',
             'switch (n) {\n  case 1: trace("one");\n  case 2: trace("two");\n  default: trace("other");\n}',
             'for (i in 0...5) trace(i);',
             'var i = 0;\nwhile (i < 3) { trace(i); i++; }',
         ]},
        {'slug': 'haxe-04-functions', 'title': 'Functions', 'desc': 'Typed functions and lambdas.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write typed functions', 'Use default arguments', 'Use lambdas', 'Use optional args'],
         'prereq': ['Haxe-03: Control Flow'],
         'samples': [
             'function add(a:Int, b:Int):Int {\n  return a + b;\n}',
             'function greet(name:String, excited:Bool = false):String {\n  return excited ? "HI " + name : "hi " + name;\n}',
             'var square = function(x:Int) return x * x;\ntrace(square(5));',
             'function greet(?name:String) {\n  trace(name == null ? "no name" : name);\n}',
         ]},
        {'slug': 'haxe-05-arrays', 'title': 'Arrays and Maps', 'desc': 'Collections.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create arrays', 'Use array methods', 'Use maps', 'Iterate collections'],
         'prereq': ['Haxe-04: Functions'],
         'samples': [
             'var nums = [1, 2, 3];\nnums.push(4);\ntrace(nums.length);',
             'var doubled = nums.map(n -> n * 2);',
             'var ages = ["Ada" => 36];\nages["Grace"] = 85;\ntrace(ages["Ada"]);',
             'for (n in nums) trace(n);',
         ]},
        {'slug': 'haxe-06-strings', 'title': 'Strings', 'desc': 'String operations and interpolation.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Concatenate strings', 'Use string interpolation', 'Split and join', 'Use string methods'],
         'prereq': ['Haxe-05: Arrays and Maps'],
         'samples': [
             'var s = "Hello" + " " + "World";',
             'var name = "Ada";\nvar msg = "Hello, $name";   // interpolation',
             'var parts = "a,b,c".split(",");',
             'trace("hello".toUpperCase());',
         ]},
        {'slug': 'haxe-07-classes', 'title': 'Classes and OOP', 'desc': 'Classes, inheritance, and interfaces.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define classes', 'Use inheritance', 'Implement interfaces', 'Use abstract classes'],
         'prereq': ['Haxe-06: Strings'],
         'samples': [
             'class Person {\n  public var name:String;\n  public var age:Int;\n\n  public function new(name:String, age:Int) {\n    this.name = name;\n    this.age = age;\n  }\n}',
             'class Dog extends Animal {\n  override public function speak() { trace("Woof"); }\n}',
             'interface Shape {\n  public function area():Float;\n}',
             'class Square implements Shape {\n  public function area():Float return side * side;\n}',
         ]},
        {'slug': 'haxe-08-enums', 'title': 'Enums (ADTs)', 'desc': 'Algebraic data types.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define enums', 'Carry data in variants', 'Pattern match enums', 'Use enum constructors'],
         'prereq': ['Haxe-07: Classes and OOP'],
         'samples': [
             'enum Color { Red; Green; Blue; }',
             'enum Shape { Circle(r:Float); Square(side:Float); }\n\nfunction area(s:Shape):Float {\n  return switch (s) {\n    case Circle(r): 3.14159 * r * r;\n    case Square(side): side * side;\n  }\n}',
             'enum Maybe<T> { Some(v:T); None; }',
             'var c = Color.Red;\nswitch (c) { case Red: trace("red"); case _: }',
         ]},
        {'slug': 'haxe-09-abstracts', 'title': 'Abstract Types', 'desc': 'Type wrappers with zero cost.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Define abstract types', 'Wrap primitives', 'Add methods', 'Control conversions'],
         'prereq': ['Haxe-08: Enums (ADTs)'],
         'samples': [
             'abstract UserId(Int) {\n  public function new(id:Int) this = id;\n}',
             'abstract Celsius(Float) {\n  public inline function new(v:Float) this = v;\n\n  public var fahrenheit(get, never):Float;\n  function get_fahrenheit():Float return this * 9 / 5 + 32;\n}',
             'abstract Meters(Int) to Int {}',
             'abstract Percent(Int) from Int {}',
         ]},
        {'slug': 'haxe-10-generics', 'title': 'Generics', 'desc': 'Type-parameterized code.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write generic classes', 'Constrain type params', 'Use type parameters in functions', 'Build containers'],
         'prereq': ['Haxe-09: Abstract Types'],
         'samples': [
             'class Box<T> {\n  public var value:T;\n  public function new(v:T) value = v;\n}',
             'function identity<T>(x:T):T return x;',
             'class Stack<T> {\n  var items:Array<T> = [];\n  public function push(item:T) items.push(item);\n}',
             'function max<T:(Int, Float)>(a:T, b:T):T return a > b ? a : b;',
         ]},
        {'slug': 'haxe-11-typedefs', 'title': 'Typedefs', 'desc': 'Structural types.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define typedefs', 'Use structural typing', 'Compose typedefs', 'Use optional fields'],
         'prereq': ['Haxe-10: Generics'],
         'samples': [
             'typedef User = {\n  var name:String;\n  var age:Int;\n}',
             'typedef Point = { x:Float, y:Float };\nvar p:Point = { x: 0, y: 0 };',
             'typedef Config = {\n  ?verbose:Bool;\n  var port:Int;\n}',
             'typedef Callback = Int -> Void;',
         ]},
        {'slug': 'haxe-12-conditionals', 'title': 'Compile-Time Conditionals', 'desc': 'Platform and build flags.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use #if/#elseif/#end', 'Check targets', 'Define build flags', 'Write platform code'],
         'prereq': ['Haxe-11: Typedefs'],
         'samples': [
             '#if js\ntrace("running in JS");\n#end',
             '#if (cpp || neko)\ntrace("native target");\n#end',
             'haxe -main Main -js app.js -D debug',
             '#if debug\ntrace("debug build");\n#end',
         ]},
        {'slug': 'haxe-13-exceptions', 'title': 'Exceptions', 'desc': 'Throw and catch.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Throw exceptions', 'Catch exceptions', 'Use try/catch', 'Create custom errors'],
         'prereq': ['Haxe-12: Compile-Time Conditionals'],
         'samples': [
             'try {\n  throw "boom";\n} catch (e:String) {\n  trace(e);\n}',
             'try {\n  risky();\n} catch (e:Dynamic) {\n  trace("error: " + e);\n}',
             'class MyError extends haxe.Exception {\n  public function new(msg:String) super(msg);\n}',
             'if (b == 0) throw "division by zero";',
         ]},
        {'slug': 'haxe-14-iterators', 'title': 'Iterators', 'desc': 'Custom iteration.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Implement Iterator', 'Use iterator methods', 'Build lazy sequences', 'Use for with iterators'],
         'prereq': ['Haxe-13: Exceptions'],
         'samples': [
             'class Counter {\n  var max:Int;\n  public function new(m:Int) max = m;\n  public function iterator() return new CounterIter(max);\n}\n\nclass CounterIter {\n  var current:Int = 0;\n  var max:Int;\n  public function new(m:Int) max = m;\n  public function hasNext() return current < max;\n  public function next() return current++;\n}',
             'for (i in new Counter(3)) trace(i);',
             'class Doubler {\n  public function iterator() { ... }\n}',
             '// lambdas: [1,2,3].filter(n -> n > 1)',
         ]},
        {'slug': 'haxe-15-macros', 'title': 'Macros', 'desc': 'Compile-time metaprogramming.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write macro functions', 'Inspect AST', 'Generate code', 'Use build macros'],
         'prereq': ['Haxe-14: Iterators'],
         'samples': [
             'import haxe.macro.Context;\n\nmacro function hello() {\n  return macro trace("from macro");\n}',
             'macro function logMe(e:Expr) {\n  trace(e);\n  return e;\n}',
             '@:build(macro function build() { ... })\nclass Generated { }',
             'macro function twice(e:Expr) {\n  return macro { $e; $e; };\n}',
         ]},
        {'slug': 'haxe-16-openfl', 'title': 'Games with OpenFL', 'desc': 'Cross-platform game framework.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Set up OpenFL', 'Create a game project', 'Draw sprites', 'Handle input'],
         'prereq': ['Haxe-15: Macros'],
         'samples': [
             'lime create project MyGame\ncd MyGame',
             'import openfl.display.Sprite;\n\nclass Main extends Sprite {\n  public function new() {\n    super();\n    trace("OpenFL!");\n  }\n}',
             'lime test neko',
             'lime build html5\nlime build mac',
         ]},
        {'slug': 'haxe-17-heaps', 'title': 'Heaps Game Engine', 'desc': 'High-performance 2D/3D.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create a Heaps scene', 'Load sprites', 'Handle the game loop', 'Build for targets'],
         'prereq': ['Haxe-16: Games with OpenFL'],
         'samples': [
             'import hxd.App;\n\nclass Main extends hxd.App {\n  override function init() {\n    trace("Heaps!");\n  }\n}',
             'var tile = hxd.Res.mySprite.toTile();\nvar bmp = new h2d.Bitmap(tile, s2d);',
             'override function update(dt:Float) {\n  // game loop\n}',
             '// build with: heaps.io toolchain',
         ]},
        {'slug': 'haxe-18-hashlink', 'title': 'HashLink VM', 'desc': 'Native VM for Haxe.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Understand HashLink', 'Compile to HL', 'Use hxd for graphics', 'Run native code'],
         'prereq': ['Haxe-17: Heaps Game Engine'],
         'samples': [
             'haxe -main Main -hl out.hl\nhl out.hl',
             'haxe -main Main -hl out.c\n# then compile C to a native binary',
             '// HL has JIT and AOT modes',
             'hl --run out.hl',
         ]},
        {'slug': 'haxe-19-node', 'title': 'Haxe on Node.js', 'desc': 'Build Node applications.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Compile to JS for Node', 'Use Node modules', 'Build a CLI', 'Use NPM packages'],
         'prereq': ['Haxe-18: HashLink VM'],
         'samples': [
             'haxe -main Main -js app.js -D nodejs',
             'import js.node.Fs;\nFs.readFile("data.txt", (err, data) -> {\n  trace(data);\n});',
             'import js.node.Http;\n\nvar server = Http.createServer((req, res) -> {\n  res.writeHead(200);\n  res.end("Hello");\n});\nserver.listen(8080);',
             'import js.node.Path;\ntrace(Path.join("a", "b"));',
         ]},
        {'slug': 'haxe-20-testing', 'title': 'Testing', 'desc': 'Unit tests with munit.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Set up munit', 'Write tests', 'Run tests', 'Test across targets'],
         'prereq': ['Haxe-19: Haxe on Node.js'],
         'samples': [
             'haxelib install munit\nhaxelib run munit test',
             'class MyTest extends haxe.unit.TestCase {\n  public function testAdd() {\n    assertEquals(4, 2 + 2);\n  }\n}',
             'var runner = new haxe.unit.TestRunner();\nrunner.add(new MyTest());\nrunner.run();',
             'assertEquals("HI", "hi".toUpperCase());',
         ]},
        {'slug': 'haxe-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Haxelib and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use haxelib', 'Install libraries', 'Publish libraries', 'Join the community'],
         'prereq': ['Haxe-20: Testing'],
         'samples': [
             'haxelib install tink_core',
             'haxelib search http',
             'haxelib run flow -f',   # development server
             '// community: haxe.org, discord, GitHub',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# LABVIEW
# ────────────────────────────────────────────────────────────────────────────
LABVIEW = {
    'lang': 'labview',
    'code_lang': 'text',
    'refs': [
        ('LabVIEW Documentation', 'https://www.ni.com/docs/en-US/bundle/labview', 'Official NI documentation'),
        ('LabVIEW Tutorials', 'https://learn.ni.com/', 'NI learning center'),
        ('NI Community', 'https://forums.ni.com/t5/LabVIEW/bd-p/170', 'Community forum'),
    ],
    'lessons': [
        {'slug': 'labview-01-getting-started', 'title': 'Getting Started with LabVIEW', 'desc': 'Front panel, block diagram, hello world.', 'dur': '60 min', 'diff': 'beginner',
         'objs': ['Understand the front panel', 'Understand the block diagram', 'Create a VI', 'Run a simple program'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '# LabVIEW VI: place a Numeric Indicator on the front panel,\n# wire a Constant (e.g. 42) to it, and press Run.',
             '# Ctrl+E toggles front panel / block diagram.',
             '# Place a String Indicator; wire "Hello, World!" constant.',
             '# Press the Run button (white arrow) to execute.',
         ]},
        {'slug': 'labview-02-palettes', 'title': 'Controls and Palettes', 'desc': 'Find and place controls and indicators.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use the Controls palette', 'Use the Functions palette', 'Place numeric controls', 'Use indicators'],
         'prereq': ['LabVIEW-01: Getting Started with LabVIEW'],
         'samples': [
             '# Controls palette: Numeric > Numeric Control\n# Functions palette: Programming > Numeric',
             '# Right-click the front panel to open the Controls palette.',
             '# Place a Numeric Control and a Numeric Indicator.',
             '# Press Ctrl+E to see both panels.',
         ]},
        {'slug': 'labview-03-dataflow', 'title': 'Dataflow Programming', 'desc': 'Wires, terminals, and execution order.', 'dur': '60 min', 'diff': 'beginner',
         'objs': ['Understand dataflow model', 'Wire controls to functions', 'Trace execution order', 'Use tunnels'],
         'prereq': ['LabVIEW-02: Controls and Palettes'],
         'samples': [
             '# Wire a Numeric Control into the Add function; wire Add output to an indicator.',
             '# Dataflow: a node runs when all inputs are ready.',
             '# Use the Probe tool (right-click wire > Probe) to see values.',
             '# Highlight Execution (light bulb icon) animates data flow.',
         ]},
        {'slug': 'labview-04-arithmetic', 'title': 'Arithmetic Operations', 'desc': 'Add, subtract, multiply, divide.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use numeric functions', 'Combine operations', 'Use arithmetic palettes', 'Build expressions'],
         'prereq': ['LabVIEW-03: Dataflow Programming'],
         'samples': [
             '# Programming > Numeric > Add — wire two controls to it.',
             '# Chain Add blocks: ((a + b) * c).',
             '# Use Divide and check the "alternate" output for remainder.',
             '# Use Compound Arithmetic for multi-input sums.',
         ]},
        {'slug': 'labview-05-booleans', 'title': 'Booleans and Comparison', 'desc': 'Boolean logic and comparisons.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use boolean controls', 'Use And/Or/Not', 'Compare values', 'Drive logic with booleans'],
         'prereq': ['LabVIEW-04: Arithmetic Operations'],
         'samples': [
             '# Boolean > Boolean Control (push button).\n# Programming > Boolean > And.',
             '# Wire two boolean controls into And; indicator shows result.',
             '# Comparison: Greater Than (Programming > Comparison).',
             '# Select (switch) function routes based on a boolean.',
         ]},
        {'slug': 'labview-06-structures', 'title': 'Structures: While and For', 'desc': 'Loop structures.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Use While Loops', 'Use For Loops', 'Use shift registers', 'Control loop termination'],
         'prereq': ['LabVIEW-05: Booleans and Comparison'],
         'samples': [
             '# Functions > Structures > While Loop — drag around your code.',
             '# The conditional terminal (red dot) stops the loop when True.',
             '# For Loop: Functions > Structures > For Loop with N iterations.',
             '# Shift registers: right-click the loop border > Add Shift Register.',
         ]},
        {'slug': 'labview-07-case', 'title': 'Case Structures', 'desc': 'Conditional execution.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Create case structures', 'Add cases', 'Handle defaults', 'Use boolean selectors'],
         'prereq': ['LabVIEW-06: Structures: While and For'],
         'samples': [
             '# Functions > Structures > Case Structure — wire a boolean selector.',
             '# Add cases via the selector label dropdown.',
             '# Default case covers all unhandled values.',
             '# Use an enum selector for readable case names.',
         ]},
        {'slug': 'labview-08-arrays', 'title': 'Arrays', 'desc': 'Build and manipulate arrays.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Create array controls', 'Index arrays', 'Build arrays', 'Use array functions'],
         'prereq': ['LabVIEW-07: Case Structures'],
         'samples': [
             '# Front panel: right-click > Modern > Numeric > Numeric Array.\n# Resize to add elements.',
             '# Index Array (Programming > Array) extracts elements.',
             '# Build Array concatenates elements and arrays.',
             '# Array Size returns the number of elements.',
         ]},
        {'slug': 'labview-09-strings', 'title': 'Strings', 'desc': 'Text handling.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create string controls', 'Concatenate strings', 'Parse strings', 'Format values'],
         'prereq': ['LabVIEW-08: Arrays'],
         'samples': [
             '# String control on the front panel (Modern > String).',
             '# Concatenate Strings (Programming > String).',
             '# String Subset extracts part of a string.',
             '# Format Into String converts numbers to text.',
         ]},
        {'slug': 'labview-10-clusters', 'title': 'Clusters', 'desc': 'Group data together.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Create clusters', 'Bundle and unbundle', 'Use cluster constants', 'Pass clusters to subVIs'],
         'prereq': ['LabVIEW-09: Strings'],
         'samples': [
             '# Cluster control groups mixed data types together.',
             '# Bundle (Programming > Cluster) packs elements into a cluster.',
             '# Unbundle extracts named elements.',
             '# Cluster constants provide compile-time values.',
         ]},
        {'slug': 'labview-11-subvis', 'title': 'SubVIs', 'desc': 'Reusable components.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Create subVIs', 'Define connector panes', 'Set icons', 'Reuse across projects'],
         'prereq': ['LabVIEW-10: Clusters'],
         'samples': [
             '# Save a VI and place it as a subVI in another VI.',
             '# Edit the connector pane (top-right icon) to map terminals.',
             '# Right-click terminal > Create > Control/Indicator to define I/O.',
             '# Double-click a subVI to edit it; changes propagate.',
         ]},
        {'slug': 'labview-12-local-variables', 'title': 'Local Variables and Properties', 'desc': 'Share data within a VI.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create local variables', 'Use property nodes', 'Control UI remotely', 'Understand race conditions'],
         'prereq': ['LabVIEW-11: SubVIs'],
         'samples': [
             '# Right-click a control > Create > Local Variable.',
             '# Property Node (right-click > Create > Property Node) changes\n# control properties like Visible and Value.',
             '# Use Value property to read/write from the block diagram.',
             '# Be careful: locals can race; prefer wires.',
         ]},
        {'slug': 'labview-13-errors', 'title': 'Error Handling', 'desc': 'Error clusters and handling.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Use error clusters', 'Wire error in/out', 'Handle errors with case', 'Use Simple Error Handler'],
         'prereq': ['LabVIEW-12: Local Variables and Properties'],
         'samples': [
             '# Every VI has error in / error out terminals.\n# Wire the cluster through functions to propagate errors.',
             '# Simple Error Handler (Programming > Dialog) shows error dialogs.',
             '# Merge Errors combines multiple error wires.',
             '# Case structure on "error in" to branch on failure.',
         ]},
        {'slug': 'labview-14-file-io', 'title': 'File I/O', 'desc': 'Read and write files.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Open files', 'Write text files', 'Read text files', 'Use file dialogs'],
         'prereq': ['LabVIEW-13: Error Handling'],
         'samples': [
             '# Write to Text File (Programming > File I/O).\n# Wire a path constant and string to write.',
             '# Read from Text File returns file contents.',
             '# File Dialog (Programming > File I/O) lets the user pick a path.',
             '# Always close files and check error out.',
         ]},
        {'slug': 'labview-15-instrument-control', 'title': 'Instrument Control', 'desc': 'Talk to hardware (VISA/SCPI).', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand VISA', 'Write SCPI commands', 'Query instruments', 'Use Instrument I/O Assistant'],
         'prereq': ['LabVIEW-14: File I/O'],
         'samples': [
             '# Instrument I/O > VISA session.\n# VISA Write sends a command; VISA Read receives a response.',
             '# Typical SCPI: "*IDN?" queries the instrument identity.',
             '# Use property nodes to set baud rate on serial sessions.',
             '# Instrument I/O Assistant auto-generates code.',
         ]},
        {'slug': 'labview-16-daq', 'title': 'Data Acquisition (DAQ)', 'desc': 'Read sensors with DAQmx.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use DAQmx API', 'Configure analog input', 'Read samples', 'Handle sampling rates'],
         'prereq': ['LabVIEW-15: Instrument Control'],
         'samples': [
             '# DAQmx Create Virtual Channel > Analog Input > Voltage.',
             '# DAQmx Timing configures the sample clock.',
             '# DAQmx Read brings samples into LabVIEW.',
             '# DAQmx Start Task / Clear Task manage the lifecycle.',
         ]},
        {'slug': 'labview-17-data-logging', 'title': 'Data Logging', 'desc': 'Record and replay data.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Log to TDMS', 'Read TDMS files', 'Stream to disk', 'Use the Datalogging palette'],
         'prereq': ['LabVIEW-16: Data Acquisition (DAQ)'],
         'samples': [
             '# TDMS Write (Programming > File I/O > TDMS) streams data.',
             '# TDMS Read reloads logged data.',
             '# Open TDMS Reference first, then TDMS Write.',
             '# TDMS files are self-describing and fast.',
         ]},
        {'slug': 'labview-18-timers', 'title': 'Timing and Synchronization', 'desc': 'Precise timing in loops.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use Wait functions', 'Use timing sources', 'Synchronize loops', 'Measure elapsed time'],
         'prereq': ['LabVIEW-17: Data Logging'],
         'samples': [
             '# Wait (ms) (Programming > Timing) paces a loop.',
             '# Tick Count returns milliseconds since boot.',
             '# Elapsed Time function measures intervals.',
             '# Use a while loop with Wait to create a timed state machine.',
         ]},
        {'slug': 'labview-19-state-machines', 'title': 'State Machines', 'desc': 'The classic LabVIEW pattern.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Design a state machine', 'Use enums for states', 'Implement transitions', 'Handle user events'],
         'prereq': ['LabVIEW-18: Timing and Synchronization'],
         'samples': [
             '# Classic pattern: While Loop + Case Structure + Shift Register.',
             '# The shift register carries the current state enum.',
             '# Each case performs work and outputs the next state.',
             '# Add an initial state constant wired to the shift register.',
         ]},
        {'slug': 'labview-20-producer-consumer', 'title': 'Producer/Consumer Pattern', 'desc': 'Handle data at different rates.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use queues', 'Separate UI from processing', 'Prevent blocking', 'Implement the pattern'],
         'prereq': ['LabVIEW-19: State Machines'],
         'samples': [
             '# Queue Operations (Programming > Synchronization > Queue).',
             '# Producer loop enqueues data; consumer loop dequeues.',
             '# Use "Obtain Queue" to share the queue reference.',
             '# The pattern keeps UI responsive during heavy work.',
         ]},
        {'slug': 'labview-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Toolkits and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Discover toolkits', 'Use the VI Package Manager', 'Find examples', 'Join the community'],
         'prereq': ['LabVIEW-20: Producer/Consumer Pattern'],
         'samples': [
             '# NI Package Manager installs toolkits and drivers.',
             '# Help > Find Examples browses built-in examples.',
             '# vipm.io hosts community packages.',
             '# Community: forums.ni.com, LabVIEW wiki.',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# MATLAB
# ────────────────────────────────────────────────────────────────────────────
MATLAB = {
    'lang': 'matlab',
    'code_lang': 'matlab',
    'refs': [
        ('MATLAB Documentation', 'https://www.mathworks.com/help/matlab/', 'Official docs'),
        ('MATLAB Onramp', 'https://www.mathworks.com/learn/tutorials/matlab-onramp.html', 'Official intro course'),
        ('MATLAB Central', 'https://www.mathworks.com/matlabcentral/', 'Community Q&A'),
    ],
    'lessons': [
        {'slug': 'matlab-01-getting-started', 'title': 'Getting Started with MATLAB', 'desc': 'Desktop, command window, scripts.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Navigate the MATLAB desktop', 'Use the command window', 'Create scripts', 'Run code'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'disp("Hello, World!")',
             '% Run with F5 or the Run button in the editor',
             'x = 42;\ndisp(x)',
             'name = "Ada";\nfprintf("Hello, %s!\\n", name)',
         ]},
        {'slug': 'matlab-02-variables', 'title': 'Variables and Data Types', 'desc': 'Numbers, strings, and logicals.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create numeric variables', 'Create strings and char arrays', 'Use logical values', 'Use who and whos'],
         'prereq': ['Matlab-01: Getting Started with MATLAB'],
         'samples': [
             'x = 42;\ny = 3.14;',
             's = "hello";\nc = char("hello");',
             'flag = true;\nnotFlag = false;',
             'who\nexists("x")',
         ]},
        {'slug': 'matlab-03-arithmetic', 'title': 'Arithmetic Operations', 'desc': 'Matrix vs element-wise math.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use basic arithmetic', 'Understand matrix ops', 'Use element-wise .*', 'Use rounding functions'],
         'prereq': ['Matlab-02: Variables and Data Types'],
         'samples': [
             'a = 10; b = 3;\na + b\na - b\na * b\na / b',
             'A = [1 2; 3 4];\nB = [5 6; 7 8];\nA * B      % matrix multiply',
             'A .* B     % element-wise',
             'round(3.7)\nfloor(3.7)\nceil(3.2)',
         ]},
        {'slug': 'matlab-04-vectors', 'title': 'Vectors', 'desc': 'Row and column vectors.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create row vectors', 'Create column vectors', 'Use colon operator', 'Index vectors'],
         'prereq': ['Matlab-03: Arithmetic Operations'],
         'samples': [
             'v = [1 2 3];     % row',
             'v = [1; 2; 3];   % column',
             'x = 1:0.5:5;     % colon operator',
             'v(2)             % second element',
         ]},
        {'slug': 'matlab-05-matrices', 'title': 'Matrices', 'desc': 'Build and manipulate 2-D data.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create matrices', 'Index rows and columns', 'Transpose matrices', 'Get dimensions'],
         'prereq': ['Matlab-04: Vectors'],
         'samples': [
             'M = [1 2 3; 4 5 6];',
             'M(1, 2)          % row 1, col 2',
             'M.\'             % transpose',
             'size(M)\nnumel(M)',
         ]},
        {'slug': 'matlab-06-functions', 'title': 'Functions', 'desc': 'Write .m functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write function files', 'Use multiple outputs', 'Pass arguments', 'Use local functions'],
         'prereq': ['Matlab-05: Matrices'],
         'samples': [
             'function y = square(x)\n    y = x * x;\nend',
             'function [summ, prod] = stats(a, b)\n    summ = a + b;\n    prod = a * b;\nend',
             '[s, p] = stats(2, 3);',
             'function y = add(a, b)\n    y = a + b;\nend',
         ]},
        {'slug': 'matlab-07-control-flow', 'title': 'Control Flow', 'desc': 'if, for, and while.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write if/elseif/else', 'Use for loops', 'Use while loops', 'Use break and continue'],
         'prereq': ['Matlab-06: Functions'],
         'samples': [
             'score = 85;\nif score >= 90\n    disp("A")\nelseif score >= 80\n    disp("B")\nelse\n    disp("C")\nend',
             'for i = 1:5\n    disp(i)\nend',
             'n = 0;\nwhile n < 3\n    n = n + 1;\nend',
             'for i = 1:10\n    if mod(i, 2) == 0\n        continue\n    end\n    disp(i)\nend',
         ]},
        {'slug': 'matlab-08-scripts-vs-functions', 'title': 'Scripts vs Functions', 'desc': 'Choose the right file type.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write scripts', 'Write functions', 'Understand workspace sharing', 'Use functions for reuse'],
         'prereq': ['Matlab-07: Control Flow'],
         'samples': [
             '% script.m — shares the base workspace\nx = 5;\ny = x * 2;',
             '% function.m — has its own workspace\nfunction y = doubleIt(x)\n    y = x * 2;\nend',
             'clear all   % clears workspace',
             'help myFunction',
         ]},
        {'slug': 'matlab-09-strings', 'title': 'Strings and Text', 'desc': 'String manipulation.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Concatenate strings', 'Use string functions', 'Format with sprintf', 'Parse text'],
         'prereq': ['Matlab-08: Scripts vs Functions'],
         'samples': [
             's = "Hello" + " " + "World";',
             'strjoin(["a", "b", "c"], " | ")',
             'sprintf("value: %d", 42)',
             'split("a,b,c", ",")',
         ]},
        {'slug': 'matlab-10-cell-arrays', 'title': 'Cell Arrays and Structs', 'desc': 'Heterogeneous containers.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create cell arrays', 'Index cells', 'Create structs', 'Use struct arrays'],
         'prereq': ['Matlab-09: Strings and Text'],
         'samples': [
             'c = {"apple", 42, 3.14};',
             'c{2}              % content\nc(1)               % sub-cell',
             'p.name = "Ada";\np.age = 36;',
             'people(1).name = "Ada";\npeople(2).name = "Grace";',
         ]},
        {'slug': 'matlab-11-plotting', 'title': 'Plotting', 'desc': 'Visualize data.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Plot lines', 'Add labels', 'Create subplots', 'Customize style'],
         'prereq': ['Matlab-10: Cell Arrays and Structs'],
         'samples': [
             'x = 0:0.1:2*pi;\ny = sin(x);\nplot(x, y)',
             'xlabel("time")\nylabel("amplitude")\ntitle("Sine wave")',
             'hold on\nplot(x, cos(x))\nhold off',
             'subplot(2, 1, 1)\nplot(x, y)\nsubplot(2, 1, 2)\nplot(x, cos(x))',
         ]},
        {'slug': 'matlab-12-file-io', 'title': 'File I/O', 'desc': 'Read and write data files.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Read text files', 'Write text files', 'Load and save MAT files', 'Use readtable'],
         'prereq': ['Matlab-11: Plotting'],
         'samples': [
             'data = load("data.txt");',
             'data = readmatrix("data.csv");',
             'save("mydata.mat", "x", "y")\nload("mydata.mat")',
             'writematrix(M, "out.csv")',
         ]},
        {'slug': 'matlab-13-vectorization', 'title': 'Vectorization', 'desc': 'Faster code without loops.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Replace loops with vector ops', 'Use element-wise operations', 'Use logical indexing', 'Avoid loops in hot paths'],
         'prereq': ['Matlab-12: File I/O'],
         'samples': [
             'x = 1:100000;\ny = x .* 2;        % no loop',
             'v = [1 2 3 4 5];\nv(v > 2)          % logical indexing',
             'sum(x)\nmean(x)\nmax(x)',
             'tic; result = x.^2; toc',
         ]},
        {'slug': 'matlab-14-optimization', 'title': 'Optimization Toolbox', 'desc': 'Minimize and solve.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use fminbnd', 'Use fminsearch', 'Solve linear systems', 'Fit data'],
         'prereq': ['Matlab-13: Vectorization'],
         'samples': [
             'f = @(x) (x - 3).^2;\nxmin = fminbnd(f, -10, 10);',
             'g = @(v) (v(1) - 1)^2 + (v(2) - 2)^2;\nvmin = fminsearch(g, [0 0]);',
             'A = [2 1; 1 3];\nb = [5; 6];\nx = A \\ b;',
             'p = polyfit(xdata, ydata, 2);',
         ]},
        {'slug': 'matlab-15-signal-processing', 'title': 'Signal Processing', 'desc': 'Filter and analyze signals.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Generate signals', 'Compute FFT', 'Filter signals', 'Visualize spectra'],
         'prereq': ['Matlab-14: Optimization Toolbox'],
         'samples': [
             'fs = 1000;\nt = 0:1/fs:1;\nsignal = sin(2*pi*50*t);',
             'Y = fft(signal);\nf = (0:length(Y)-1) * fs / length(Y);\nplot(f, abs(Y))',
             'b = fir1(20, 0.1);\nfiltered = filter(b, 1, signal);',
             'plot(t, signal)\nhold on\nplot(t, filtered)',
         ]},
        {'slug': 'matlab-16-simulink', 'title': 'Simulink Basics', 'desc': 'Model-based design.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create a model', 'Add blocks', 'Run simulations', 'Add scopes'],
         'prereq': ['Matlab-15: Signal Processing'],
         'samples': [
             '% Simulink: open_system("simulink")\n% Drag blocks from the library browser.',
             'open_system("simulink")',
             'model = "my_model";\nnew_system(model);\nopen_system(model);',
             'sim(model);',
         ]},
        {'slug': 'matlab-17-app-designer', 'title': 'App Designer', 'desc': 'Build interactive apps.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create an app', 'Add components', 'Write callbacks', 'Run the app'],
         'prereq': ['Matlab-16: Simulink Basics'],
         'samples': [
             '% appdesigner opens the App Designer tool.',
             'appdesigner',
             '% Drag a Button, Edit Field, and Label onto the canvas.',
             '% Write a ButtonPushed callback in the code view.',
         ]},
        {'slug': 'matlab-18-databases', 'title': 'Working with Tables', 'desc': 'Tabular data analysis.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Create tables', 'Filter rows', 'Group and summarize', 'Merge tables'],
         'prereq': ['Matlab-17: App Designer'],
         'samples': [
             'T = table([1;2;3], ["a";"b";"c"], "VariableNames", ["ID", "Name"]);',
             'T(T.ID > 1, :)',
             'groupsummary(T, "Name")',
             'join(T1, T2)',
         ]},
        {'slug': 'matlab-19-machine-learning', 'title': 'Machine Learning', 'desc': 'Classification and regression.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Load sample data', 'Split train/test', 'Train a classifier', 'Evaluate accuracy'],
         'prereq': ['Matlab-18: Working with Tables'],
         'samples': [
             'load fisheriris\nX = meas;\ny = species;',
             'rng(1)\ncv = cvpartition(y, "HoldOut", 0.3);',
             'model = fitcknn(X(training(cv), :), y(training(cv)));',
             'pred = predict(model, X(test(cv), :));\naccuracy = sum(pred == y(test(cv))) / numel(pred)',
         ]},
        {'slug': 'matlab-20-performance', 'title': 'Code Performance', 'desc': 'Profile and accelerate.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use the profiler', 'Preallocate arrays', 'Use parfor', 'Benchmark with tic/toc'],
         'prereq': ['Matlab-19: Machine Learning'],
         'samples': [
             'profile on\nmyFunction()\nprofile viewer',
             'result = zeros(1, 10000);\nfor i = 1:10000\n    result(i) = i;\nend',
             'parfor i = 1:100\n    result(i) = heavyWork(i);\nend',
             'tic; ...; toc',
         ]},
        {'slug': 'matlab-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Toolboxes and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Discover toolboxes', 'Use File Exchange', 'Share code', 'Find learning resources'],
         'prereq': ['Matlab-20: Code Performance'],
         'samples': [
             'ver   % list installed toolboxes',
             '% MATLAB Central File Exchange hosts community code',
             'addpath("my_folder")',
             'doc <topic>   % built-in documentation',
         ]},
    ],
}

SPECS = [GLEAM, HAXE, LABVIEW, MATLAB]
