"""Curriculum specs for the LLM Engineering and AI Agents courses."""

SPECS = [
    # ────────────────────────────────────────────────────────────────
    # LLM ENGINEERING
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'llm-engineering',
        'code_lang': 'python',
        'refs': [
            ('OpenAI Platform Docs', 'https://platform.openai.com/docs', 'API reference for chat, embeddings, function calling and vision.'),
            ('Anthropic Documentation', 'https://docs.anthropic.com/', 'Claude API docs including prompt engineering guides.'),
            ('Hugging Face Transformers', 'https://huggingface.co/docs/transformers', 'Models, tokenizers and pipelines for LLM work.'),
            ('LangChain Documentation', 'https://python.langchain.com/docs', 'Frameworks for RAG, agents and LLM applications.'),
            ('vLLM Documentation', 'https://docs.vllm.ai/', 'High-throughput LLM serving and inference.'),
        ],
        'lessons': [
            {
                'slug': 'llm-01-what-is-llm-engineering',
                'title': 'What Is LLM Engineering?',
                'desc': 'The discipline of building systems on top of large language models — and where it differs from classic ML.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': ['GENAI-01: What Is Generative AI?'],
                'objs': [
                    'Define LLM engineering and its scope',
                    'Contrast LLM apps with traditional ML services',
                    'List the core building blocks (prompts, RAG, agents, evals)',
                    'Identify when an LLM is the right tool',
                ],
                'samples': [
                    'stack = ["models", "prompts", "retrieval", "agents", "evals", "guardrails"]\nfor s in stack:\n    print(f"- {s}")',
                    'print("LLM apps: mostly orchestration + evaluation, less training")',
                    'from openai import OpenAI\n\nclient = OpenAI()\nres = client.chat.completions.create(\n    model="gpt-4o-mini",\n    messages=[{"role": "user", "content": "hi"}],\n)\nprint("first call:", res.choices[0].message.content)',
                    'wrong_tools = ["precise math", "low latency at scale", "deterministic rules"]\nfor w in wrong_tools:\n    print(f"- avoid LLMs for: {w}")',
                ],
            },
            {
                'slug': 'llm-02-llm-architecture-review',
                'title': 'LLM Architecture Review',
                'desc': 'Decoder-only transformers, context windows, and what happens inside a single generation call.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['DL-17: Transformers'],
                'objs': [
                    'Describe the decoder-only stack',
                    'Explain context window mechanics',
                    'Trace a generation call end to end',
                    'Understand KV caching',
                ],
                'samples': [
                    'import torch.nn as nn\n\n# Decoder block: masked attention + MLP\nblock = nn.TransformerDecoderLayer(d_model=512, nhead=8, batch_first=True)\nprint(block)',
                    'print("context window = prompt + generated tokens")',
                    'import torch\n\n# KV cache: reuse past key/values for speed\nkv_cache = {"k": torch.randn(1, 8, 10, 64), "v": torch.randn(1, 8, 10, 64)}\nprint("cached keys:", kv_cache["k"].shape)',
                    'print("each new token attends to all cached positions")',
                ],
            },
            {
                'slug': 'llm-03-llm-apis',
                'title': 'Working with LLM APIs',
                'desc': 'Chat completions, parameters, streaming and structured outputs — the daily API toolkit.',
                'dur': '55 min', 'diff': 'beginner', 'prereq': ['LLM-01: What Is LLM Engineering?'],
                'objs': [
                    'Call chat completion APIs',
                    'Tune temperature, max tokens and top-p',
                    'Stream responses',
                    'Parse structured outputs',
                ],
                'samples': [
                    'from openai import OpenAI\n\nclient = OpenAI()\nres = client.chat.completions.create(\n    model="gpt-4o-mini",\n    messages=[{"role": "user", "content": "Say hello in one word"}],\n    max_tokens=10,\n)\nprint(res.choices[0].message.content)',
                    'from openai import OpenAI\n\nclient = OpenAI()\nstream = client.chat.completions.create(\n    model="gpt-4o-mini",\n    messages=[{"role": "user", "content": "Count 1 to 3"}],\n    stream=True,\n)\nfor chunk in stream:\n    print(chunk.choices[0].delta.content or "", end="")\nprint()',
                    'import json\n\n# Request JSON output\nprompt = \'Return JSON: {"city": string, "temp": number}\'\nprint(prompt)',
                    'from openai import OpenAI\n\nclient = OpenAI()\nres = client.chat.completions.create(\n    model="gpt-4o-mini",\n    messages=[{"role": "user", "content": "Summarize in one sentence: ML is hard"}],\n    temperature=0.2,\n)\nprint(res.choices[0].message.content)',
                ],
            },
            {
                'slug': 'llm-04-prompting-systems',
                'title': 'Prompting Systems at Scale',
                'desc': 'Turn prompts into versioned, testable system components — not strings in code.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['LLM-03: Working with LLM APIs'],
                'objs': [
                    'Separate system, user and assistant turns',
                    'Template prompts with variables',
                    'Version prompts like code',
                    'Measure prompt quality with evals',
                ],
                'samples': [
                    'from langchain_core.prompts import ChatPromptTemplate\n\nprompt = ChatPromptTemplate.from_messages([\n    ("system", "You are a {role} assistant."),\n    ("user", "{question}"),\n])\nprint(prompt.format(role="support", question="How do I refund?"))',
                    'system_prompt = "You are a concise technical writer."\nprint(system_prompt)',
                    'import hashlib\n\nprompt_text = "Answer concisely."\nprint("prompt version:", hashlib.sha256(prompt_text.encode()).hexdigest()[:8])',
                    'print("evals gate prompt changes: same eval set, compare scores")',
                ],
            },
            {
                'slug': 'llm-05-tokenization-and-context',
                'title': 'Tokenization & Context Management',
                'desc': 'Budget tokens, count costs, and fit big context into small windows.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['LLM-03: Working with LLM APIs'],
                'objs': [
                    'Count tokens with tiktoken',
                    'Estimate cost per request',
                    'Chunk content to fit context',
                    'Use token budgets defensively',
                ],
                'samples': [
                    'import tiktoken\n\nenc = tiktoken.get_encoding("cl100k_base")\ntext = "The quick brown fox jumps over the lazy dog" * 5\nprint("tokens:", len(enc.encode(text)))',
                    'import tiktoken\n\nenc = tiktoken.get_encoding("cl100k_base")\ncost_per_1k = 0.00015\nn = len(enc.encode("some prompt"))\nprint("cost:", round(n / 1000 * cost_per_1k, 6))',
                    'def fit_to_window(text, max_tokens, enc):\n    tokens = enc.encode(text)\n    return enc.decode(tokens[:max_tokens])\n\nprint("truncated:", fit_to_window("a" * 100, 50, enc)[:20])',
                    'print("budget: reserve room for the answer in the window")',
                ],
            },
            {
                'slug': 'llm-06-embeddings-and-semantic-search',
                'title': 'Embeddings & Semantic Search',
                'desc': 'Turn text into vectors and search by meaning — the retrieval backbone of LLM apps.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['LLM-05: Tokenization & Context Management'],
                'objs': [
                    'Generate text embeddings',
                    'Measure semantic similarity',
                    'Index and query vectors',
                    'Evaluate retrieval quality',
                ],
                'samples': [
                    'from openai import OpenAI\n\nclient = OpenAI()\nvec = client.embeddings.create(model="text-embedding-3-small", input=["deep learning rocks"])\nprint("dim:", len(vec.data[0].embedding))',
                    'import numpy as np\n\ndef cosine(a, b):\n    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))\n\nprint("similarity:", round(cosine(np.array([1, 0]), np.array([0.99, 0.1])), 3))',
                    'import faiss\n\nindex = faiss.IndexFlatIP(384)\nprint("vector index ready")',
                    'print("evaluate: does the top-5 contain the right document?")',
                ],
            },
            {
                'slug': 'llm-07-rag-engineering',
                'title': 'RAG Engineering',
                'desc': 'Design retrieval-augmented generation that is reliable: chunking, indexing and prompting.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['LLM-06: Embeddings & Semantic Search'],
                'objs': [
                    'Design a RAG pipeline',
                    'Chunk documents with strategy',
                    'Build a retrieval-augmented chat',
                    'Debug retrieval failures',
                ],
                'samples': [
                    'from langchain.text_splitter import RecursiveCharacterTextSplitter\n\nsplitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)\nchunks = splitter.split_text("long document " * 50)\nprint("chunks:", len(chunks))',
                    'rag = {\n    1: "chunk", 2: "embed", 3: "store", 4: "retrieve", 5: "generate",\n}\nprint(rag)',
                    'from langchain_community.vectorstores import FAISS\n\nprint("vector store ready")',
                    'print("no results? fix chunking or embeddings, not the prompt")',
                ],
            },
            {
                'slug': 'llm-08-advanced-rag',
                'title': 'Advanced RAG',
                'desc': 'Hybrid search, reranking, query rewriting and contextual compression for better answers.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['LLM-07: RAG Engineering'],
                'objs': [
                    'Combine keyword and vector search (hybrid)',
                    'Rerank candidates with cross-encoders',
                    'Rewrite queries before retrieval',
                    'Compress retrieved context',
                ],
                'samples': [
                    'import numpy as np\n\n# Hybrid: blend BM25 + vector scores\nbm25 = np.array([0.6, 0.2, 0.1])\nvector = np.array([0.4, 0.8, 0.3])\nhybrid = 0.5 * bm25 + 0.5 * vector\nprint("hybrid scores:", hybrid.round(2))',
                    'from sentence_transformers import CrossEncoder\n\nreranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")\nprint("reranker ready")',
                    'print("query rewriting: turn a vague question into a searchable one")',
                    'print("compression: keep only the sentences that answer the question")',
                ],
            },
            {
                'slug': 'llm-09-fine-tuning-practice',
                'title': 'Fine-Tuning LLMs in Practice',
                'desc': 'LoRA, QLoRA and instruction tuning — adapt open models when prompting is not enough.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['GENAI-08: Fine-Tuning LLMs'],
                'objs': [
                    'Prepare an instruction dataset',
                    'Fine-tune with LoRA',
                    'Evaluate the fine-tuned model',
                    'Decide when fine-tuning is worth it',
                ],
                'samples': [
                    'data = [\n    {"prompt": "Define ML", "completion": "Machine learning is..."},\n    {"prompt": "Define DL", "completion": "Deep learning is..."},\n]\nprint("instruction pairs:", len(data))',
                    'from peft import LoraConfig, get_peft_model\n\nconfig = LoraConfig(r=8, lora_alpha=16, target_modules=["q_proj", "v_proj"])\nprint("LoRA config ready")',
                    'import torch\n\n# QLoRA: 4-bit base + LoRA adapters on top\nprint("4-bit quantization keeps memory low")',
                    'print("fine-tune to match a style/format, not to add facts")',
                ],
            },
            {
                'slug': 'llm-10-function-calling',
                'title': 'Function Calling & Structured Outputs',
                'desc': 'Let the model call your tools with typed arguments — reliably.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['LLM-03: Working with LLM APIs'],
                'objs': [
                    'Define tools with JSON schemas',
                    'Handle tool-call responses',
                    'Validate arguments before executing',
                    'Use structured output modes',
                ],
                'samples': [
                    'from openai import OpenAI\n\nclient = OpenAI()\nres = client.chat.completions.create(\n    model="gpt-4o-mini",\n    messages=[{"role": "user", "content": "Weather in Paris?"}],\n    tools=[{\n        "type": "function",\n        "function": {\n            "name": "get_weather",\n            "parameters": {"type": "object", "properties": {"city": {"type": "string"}}, "required": ["city"]},\n        },\n    }],\n)\ntool_calls = res.choices[0].message.tool_calls\nprint("tool call:", tool_calls[0].function.name if tool_calls else None)',
                    'import json\n\nargs = json.loads(\'{"city": "Paris"}\')\nassert isinstance(args["city"], str)\nprint("validated args:", args)',
                    'print("execute the tool, then return the result as a message")',
                    'print("structured output: force JSON schema conformance")',
                ],
            },
            {
                'slug': 'llm-11-llm-agents',
                'title': 'Building LLM Agents',
                'desc': 'Connect models to tools and loops: the agent pattern in production.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['LLM-10: Function Calling & Structured Outputs'],
                'objs': [
                    'Define the agent loop',
                    'Give agents tools and constraints',
                    'Cap iterations for safety',
                    'Trace agent behavior',
                ],
                'samples': [
                    'def agent_loop(task, tools, max_steps=5):\n    messages = [{"role": "user", "content": task}]\n    for step in range(max_steps):\n        reply = call_model(messages, tools)\n        if reply.finished:\n            return reply.answer\n        messages.append(reply.as_message())\n        messages.append(run_tool(reply.tool_call))\n    return "reached step limit"\n\nprint(agent_loop)',
                    'import time\n\nfor step in range(3):\n    print(f"step {step}: model -> tool -> observe")\n    time.sleep(0.05)',
                    'guardrails = {"max_steps": 5, "tool_allowlist": ["search"], "timeout": 30}\nprint(guardrails)',
                    'print("log every step: reasoning, tool call, result")',
                ],
            },
            {
                'slug': 'llm-12-context-engineering',
                'title': 'Context Engineering & Memory',
                'desc': 'Manage what the model sees: conversation memory, summarization and caching.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['LLM-05: Tokenization & Context Management'],
                'objs': [
                    'Design conversation memory',
                    'Summarize long histories',
                    'Cache prompts and completions',
                    'Keep context relevant',
                ],
                'samples': [
                    'messages = [\n    {"role": "user", "content": "I want a refund"}, \n    {"role": "assistant", "content": "Order number?"},\n]\nprint("rolling window:", len(messages), "messages")',
                    'print("summarize old turns when the window fills")',
                    'import hashlib\n\ncache_key = hashlib.sha256(b"same-prompt").hexdigest()\nprint("cache key:", cache_key[:10])',
                    'print("retrieval + memory = context that stays on-topic")',
                ],
            },
            {
                'slug': 'llm-13-evaluating-llm-systems',
                'title': 'Evaluating LLM Systems',
                'desc': 'Build evals that catch regressions: golden sets, LLM-as-judge and human review.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['LLM-04: Prompting Systems at Scale'],
                'objs': [
                    'Build a golden eval set',
                    'Use LLM-as-judge for open-ended outputs',
                    'Measure correctness, faithfulness and safety',
                    'Run evals in CI',
                ],
                'samples': [
                    'evals = [\n    {"prompt": "What is the capital of France?", "expected": "Paris"},\n    {"prompt": "2+2?", "expected": "4"},\n]\nprint("golden set:", len(evals))',
                    'def exact_match(pred, expected):\n    return pred.strip().lower() == expected.strip().lower()\n\nprint("EM:", exact_match("Paris", "Paris"))',
                    'print("LLM-as-judge: score helpfulness, faithfulness, tone")',
                    'print("CI gate: block merges that lower eval scores")',
                ],
            },
            {
                'slug': 'llm-14-guardrails-and-safety',
                'title': 'Guardrails & Safety for LLM Apps',
                'desc': 'Prompt injection, moderation, PII redaction and output filtering.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['LLM-10: Function Calling & Structured Outputs'],
                'objs': [
                    'Understand prompt injection attacks',
                    'Apply input and output moderation',
                    'Redact PII',
                    'Sandbox tool execution',
                ],
                'samples': [
                    'from openai import OpenAI\n\nclient = OpenAI()\nres = client.moderations.create(input="user content here")\nprint("flagged:", res.results[0].flagged)',
                    'import re\n\ntext = "email: john@example.com"\nredacted = re.sub(r"[\\w.+-]+@[\\w-]+\\.[\\w.]+", "[REDACTED]", text)\nprint(redacted)',
                    'print("instruction hierarchy: system > user > tool")',
                    'print("run tools in sandboxes with timeouts and allowlists")',
                ],
            },
            {
                'slug': 'llm-15-llm-serving',
                'title': 'LLM Serving & Inference',
                'desc': 'Serve open models: vLLM, quantization, batching and GPU memory management.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['LLM-09: Fine-Tuning LLMs in Practice'],
                'objs': [
                    'Serve models with vLLM',
                    'Quantize for lower memory',
                    'Batch requests for throughput',
                    'Measure tokens per second',
                ],
                'samples': [
                    'from vllm import LLM\n\nllm = LLM(model="meta-llama/Llama-3.2-1B-Instruct")\nprint("vLLM engine ready")',
                    'from vllm import SamplingParams\n\nparams = SamplingParams(temperature=0.7, max_tokens=100)\nprint("sampling params set")',
                    'import torch\n\n# Quantization: 4-bit weights cut memory ~4x\nprint("bitsandbytes 4-bit config")',
                    'print("continuous batching raises GPU utilization")',
                ],
            },
            {
                'slug': 'llm-16-cost-optimization',
                'title': 'Cost Optimization for LLM Apps',
                'desc': 'Cut spend without cutting quality: caching, smaller models, and smart routing.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['LLM-05: Tokenization & Context Management'],
                'objs': [
                    'Model cost per request',
                    'Use prompt and completion caching',
                    'Route simple queries to small models',
                    'Budget by feature',
                ],
                'samples': [
                    'import tiktoken\n\nenc = tiktoken.get_encoding("cl100k_base")\nin_tok = len(enc.encode("prompt " * 100))\nout_tok = 200\ncost = in_tok / 1000 * 0.00015 + out_tok / 1000 * 0.0006\nprint("cost per request:", round(cost, 5))',
                    'print("cache exact prompt matches -> 90% cost cut")',
                    'print("router: small model for intents, big model for hard cases")',
                    'print("streaming and trimming inputs also saves tokens")',
                ],
            },
            {
                'slug': 'llm-17-observability',
                'title': 'Prompt Versioning & Observability',
                'desc': 'Trace every request: prompt, tokens, latency, cost and outcome.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['LLM-13: Evaluating LLM Systems'],
                'objs': [
                    'Log full request traces',
                    'Tag prompts and model versions',
                    'Monitor cost and latency',
                    'Correlate feedback with versions',
                ],
                'samples': [
                    'import time\n\ntrace = {\n    "prompt_version": "v3",\n    "model": "gpt-4o-mini",\n    "tokens_in": 120,\n    "tokens_out": 40,\n    "latency_ms": 412,\n}\nprint(trace)',
                    'print("every request is replayable for debugging")',
                    'print("dashboards: cost, latency, error rate by prompt version")',
                    'print("user feedback attaches to the exact version served")',
                ],
            },
            {
                'slug': 'llm-18-building-a-copilot',
                'title': 'Building a Production Copilot',
                'desc': 'Assemble everything into a real product: an assistant grounded in your data.',
                'dur': '75 min', 'diff': 'advanced', 'prereq': ['LLM-11: Building LLM Agents'],
                'objs': [
                    'Design a copilot architecture',
                    'Wire RAG, tools and memory',
                    'Add guardrails and evals',
                    'Ship, monitor and iterate',
                ],
                'samples': [
                    'arch = {\n    "frontend": "chat UI",\n    "backend": "RAG + tools + guardrails",\n    "data": "vector store + docs",\n    "ops": "evals + observability",\n}\nprint(arch)',
                    'from openai import OpenAI\n\nclient = OpenAI()\nres = client.chat.completions.create(\n    model="gpt-4o-mini",\n    messages=[{"role": "user", "content": "How do I reset my password?"}],\n)\nprint("assistant:", res.choices[0].message.content[:60])',
                    'print("answers cite sources -> trust")',
                    'print("feedback loop: thumbs up/down feed the eval set")',
                ],
            },
            {
                'slug': 'llm-19-production-case-studies',
                'title': 'LLM Production Case Studies',
                'desc': 'Learn from real systems: search copilots, support agents and coding assistants.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['LLM-18: Building a Production Copilot'],
                'objs': [
                    'Analyze real LLM product architectures',
                    'Identify the eval strategy in each',
                    'Spot the guardrails they use',
                    'Extract reusable patterns',
                ],
                'samples': [
                    'cases = {\n    "support copilot": "RAG + escalation",\n    "coding assistant": "code index + agents",\n    "search": "hybrid retrieval + rerank",\n}\nprint(cases)',
                    'print("every case: eval-gated releases")',
                    'print("guardrails: human escalation when confidence is low")',
                    'patterns = ["cite sources", "stream", "fallback to human", "rate limits"]\nprint(patterns)',
                ],
            },
            {
                'slug': 'llm-20-llmops-tooling',
                'title': 'The LLMOps Tooling Landscape',
                'desc': 'Survey the ecosystem: frameworks, eval platforms, observability and serving.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['LLM-01: What Is LLM Engineering?'],
                'objs': [
                    'Compare LLM frameworks (LangChain, LlamaIndex)',
                    'Choose an eval platform',
                    'Pick observability tooling',
                    'Match tools to team size',
                ],
                'samples': [
                    'frameworks = {"langchain": "chains & agents", "llamaindex": "data & RAG"}\nprint(frameworks)',
                    'print("start with plain API calls; add frameworks when they pay for themselves")',
                    'print("eval platforms: run golden sets on every commit")',
                    'print("observability: traces, cost, latency, feedback")',
                ],
            },
            {
                'slug': 'llm-21-roadmap',
                'title': 'LLM Engineering Roadmap',
                'desc': 'Synthesize the course into a plan: build, ship and scale LLM products.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['LLM-20: The LLMOps Tooling Landscape'],
                'objs': [
                    'Design a personal LLM engineering plan',
                    'Pick flagship projects (RAG, agent, fine-tune)',
                    'Connect to GenAI, agents and MLOps courses',
                    'Stay current with the field',
                ],
                'samples': [
                    'plan = {\n    1: "ship a RAG knowledge assistant",\n    2: "build an agent with tools",\n    3: "fine-tune a small model with LoRA",\n    4: "add evals + guardrails in CI",\n}\nprint(plan)',
                    'print("next: AI Agents course for agent patterns")',
                    'print("next: MLOps course for production discipline")',
                    'sources = ["OpenAI blog", "Anthropic docs", "Hugging Face", "Latent Space podcast"]\nprint("follow:", ", ".join(sources))',
                ],
            },
        ],
    },

    # ────────────────────────────────────────────────────────────────
    # AI AGENTS
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'ai-agents',
        'code_lang': 'python',
        'refs': [
            ('LangChain Agents', 'https://python.langchain.com/docs/how_to/#agents', 'Agent frameworks, tools and memory patterns.'),
            ('OpenAI Agents Documentation', 'https://platform.openai.com/docs/guides/agents', 'Function calling and agent loop patterns.'),
            ('ReAct: Synergizing Reasoning and Acting', 'https://arxiv.org/abs/2210.03629', 'The paper behind reasoning-acting agent loops.'),
            ('Anthropic — Building Effective Agents', 'https://www.anthropic.com/research/building-effective-agents', 'A practical guide to agent architecture.'),
            ('CrewAI Documentation', 'https://docs.crewai.com/', 'Multi-agent orchestration framework.'),
        ],
        'lessons': [
            {
                'slug': 'agents-01-what-are-ai-agents',
                'title': 'What Are AI Agents?',
                'desc': 'Autonomous systems that perceive, reason, act and observe — the agent loop explained.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': ['LLM-01: What Is LLM Engineering?'],
                'objs': [
                    'Define an AI agent',
                    'Describe the perceive-reason-act loop',
                    'Contrast agents with plain LLM calls',
                    'List where agents add real value',
                ],
                'samples': [
                    'agent = {\n    "perceive": "observe the environment",\n    "reason": "decide the next action",\n    "act": "call a tool or respond",\n    "observe": "read the result and loop",\n}\nprint(agent)',
                    'print("LLM call: one-shot. Agent: a loop with tools.")',
                    'use_cases = ["research", "data analysis", "support triage", "coding"]\nfor u in use_cases:\n    print(f"- {u}")',
                    'print("agents are only as reliable as their tools + evals")',
                ],
            },
            {
                'slug': 'agents-02-agent-architecture',
                'title': 'Agent Architecture',
                'desc': 'The anatomy of an agent: model, tools, memory, planner and executor.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['AGENTS-01: What Are AI Agents?'],
                'objs': [
                    'Decompose an agent into components',
                    'Describe the controller pattern',
                    'Explain tool registries',
                    'Choose when to use simple vs complex architectures',
                ],
                'samples': [
                    'components = {\n    "model": "decides actions",\n    "tools": "capabilities",\n    "memory": "state across steps",\n    "planner": "breaks down goals",\n}\nprint(components)',
                    'import json\n\n# Tool registry: name -> function\ntools = {"search": search_fn, "calc": calc_fn}\nprint("registered:", list(tools))',
                    'print("start simple: one model + few tools")',
                    'print("controller: the model decides, the code executes")',
                ],
            },
            {
                'slug': 'agents-03-tool-use',
                'title': 'Tool Use & Function Calling',
                'desc': 'Give agents real capabilities with typed tools and safe execution.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['LLM-10: Function Calling & Structured Outputs'],
                'objs': [
                    'Define tools with schemas',
                    'Execute tool calls safely',
                    'Handle errors and retries',
                    'Restrict tools by allowlist',
                ],
                'samples': [
                    'def get_weather(city: str) -> str:\n    return f"Weather for {city}: sunny"\n\ntool_schema = {\n    "name": "get_weather",\n    "parameters": {"type": "object", "properties": {"city": {"type": "string"}}},\n}\nprint(tool_schema)',
                    'import json\n\nargs = json.loads(\'{"city": "Paris"}\')\nresult = get_weather(**args)\nprint("tool result:", result)',
                    'print("wrap tools: try/except, timeout, and a clear error message")',
                    'print("allowlist: agents may only call approved tools")',
                ],
            },
            {
                'slug': 'agents-04-reasoning-and-planning',
                'title': 'Reasoning & Planning (ReAct)',
                'desc': 'Interleave thought, action and observation — the ReAct pattern that powers modern agents.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['AGENTS-03: Tool Use & Function Calling'],
                'objs': [
                    'Explain the ReAct loop',
                    'Write reasoning prompts',
                    'Implement a ReAct-style agent',
                    'Plan multi-step tasks',
                ],
                'samples': [
                    'react = ["Thought", "Action", "Observation", "Thought", "Action", "Final"]\nprint(react)',
                    'prompt = """You answer questions using tools.\\n\\nThought: what do I need?\\nAction: search[query]\\nObservation: result\\nAnswer: ...\\n"""\nprint(prompt)',
                    'import time\n\nstate = "need current price"\nfor step in range(3):\n    print(f"Thought -> Action -> Observation (step {step})")\n    time.sleep(0.05)',
                    'print("plan-then-execute: decompose a big task into steps")',
                ],
            },
            {
                'slug': 'agents-05-memory-systems',
                'title': 'Agent Memory Systems',
                'desc': 'Working memory, long-term memory and retrieval — state that persists across turns.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['AGENTS-04: Reasoning & Planning (ReAct)'],
                'objs': [
                    'Distinguish short-term and long-term memory',
                    'Store conversation state',
                    'Retrieve relevant memories',
                    'Compress and summarize history',
                ],
                'samples': [
                    'memory = {\n    "working": "current task context",\n    "episodic": "past conversations",\n    "semantic": "facts about the user",\n}\nprint(memory)',
                    'import redis\n\nr = redis.Redis()\nr.set("agent:42:preferences", "prefers concise answers")\nprint("stored:", r.get("agent:42:preferences"))',
                    'print("retrieve memories semantically, not by recency alone")',
                    'print("summarize old turns to keep the window small")',
                ],
            },
            {
                'slug': 'agents-06-multi-agent-systems',
                'title': 'Multi-Agent Systems',
                'desc': 'Specialized agents that collaborate: orchestrators, workers and handoffs.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['AGENTS-05: Agent Memory Systems'],
                'objs': [
                    'Design an orchestrator-worker pattern',
                    'Implement handoffs between agents',
                    'Coordinate shared state',
                    'Avoid over-engineering with many agents',
                ],
                'samples': [
                    'roles = {\n    "orchestrator": "routes work",\n    "researcher": "gathers facts",\n    "writer": "produces output",\n}\nprint(roles)',
                    'from crewai import Agent, Task, Crew\n\nresearcher = Agent(role="researcher", goal="find facts", backstory="curious")\ncrew = Crew(agents=[researcher], tasks=[Task(description="research X", agent=researcher)])\nprint("crew ready")',
                    'print("handoff: one agent delegates to another with context")',
                    'print("more agents = more failure modes; start with one")',
                ],
            },
            {
                'slug': 'agents-07-langchain-agents',
                'title': 'Building Agents with LangChain',
                'desc': 'Compose agents with the LangChain ecosystem: tools, memory and executors.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['AGENTS-03: Tool Use & Function Calling'],
                'objs': [
                    'Create tools with @tool',
                    'Bind tools to a chat model',
                    'Run an agent loop',
                    'Stream agent steps',
                ],
                'samples': [
                    'from langchain_core.tools import tool\n\n@tool\ndef multiply(a: float, b: float) -> float:\n    """Multiply two numbers."""\n    return a * b\n\nprint(multiply.name, "|", multiply.description[:40])',
                    'from langchain_openai import ChatOpenAI\n\nmodel = ChatOpenAI(model="gpt-4o-mini", temperature=0)\nprint("model ready")',
                    'tools = [multiply]\nprint("bound tools:", len(tools))',
                    'print("run: model decides tool calls, loop executes them")',
                ],
            },
            {
                'slug': 'agents-08-research-agents',
                'title': 'Building a Research Agent',
                'desc': 'A practical build: gather sources, synthesize findings, cite everything.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['AGENTS-07: Building Agents with LangChain'],
                'objs': [
                    'Plan a research workflow',
                    'Query search and fetch pages',
                    'Synthesize with citations',
                    'Handle unreliable sources',
                ],
                'samples': [
                    'workflow = ["query", "fetch", "extract", "synthesize", "cite"]\nprint(workflow)',
                    'def search(query: str) -> list[str]:\n    return ["https://example.com/1", "https://example.com/2"]\n\nprint("results:", search("llm agents"))',
                    'import re\n\n# Strip HTML before summarizing\nclean = re.sub(r"<[^>]+>", "", "<p>Hello</p>")\nprint(clean)',
                    'print("cite sources: every claim links back to a fetched page")',
                ],
            },
            {
                'slug': 'agents-09-browser-agents',
                'title': 'Browser Automation Agents',
                'desc': 'Agents that browse the web: navigation, form filling and screenshots.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['AGENTS-08: Building a Research Agent'],
                'objs': [
                    'Explain the browser agent pattern',
                    'Navigate and extract page content',
                    'Interact with forms',
                    'Handle login walls and captchas safely',
                ],
                'samples': [
                    'from playwright.sync_api import sync_playwright\n\nwith sync_playwright() as p:\n    browser = p.chromium.launch()\n    page = browser.new_page()\n    page.goto("https://example.com")\n    print("title:", page.title())\n    browser.close()',
                    'import requests\n\nhtml = requests.get("https://example.com").text\nprint("fetched", len(html), "chars")',
                    'print("act: click, type, submit — then observe the result")',
                    'print("rate limits and consent matter; respect robots.txt")',
                ],
            },
            {
                'slug': 'agents-10-coding-agents',
                'title': 'Coding Agents',
                'desc': 'Agents that read, edit and run code: repo context, patch generation and verification.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['AGENTS-08: Building a Research Agent'],
                'objs': [
                    'Describe the coding agent loop',
                    'Provide repo context via retrieval',
                    'Generate and apply patches',
                    'Verify with tests and lint',
                ],
                'samples': [
                    'import subprocess\n\nout = subprocess.run(["git", "diff"], capture_output=True, text=True)\nprint("diff lines:", len(out.stdout.splitlines()))',
                    'print("retrieve relevant files before suggesting edits")',
                    'def apply_patch(patch: str):\n    return f"applied {len(patch.splitlines())} lines"\n\nprint(apply_patch("+def foo(): pass"))',
                    'print("verify: run tests + linter before accepting the change")',
                ],
            },
            {
                'slug': 'agents-11-rag-agents',
                'title': 'RAG Agents',
                'desc': 'Agents that decide when and what to retrieve — retrieval as a tool, not a fixed step.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['LLM-08: Advanced RAG'],
                'objs': [
                    'Expose retrieval as an agent tool',
                    'Let the agent plan searches',
                    'Iterate on queries',
                    'Ground answers in retrieved content',
                ],
                'samples': [
                    'def retrieve(query: str) -> list[dict]:\n    return [{"title": "doc1", "text": "..."}]\n\nprint("retrieval tool ready")',
                    'print("agent asks: do I need to search? what should I search for?")',
                    'print("multiple searches beat one big query")',
                    'print("final answer cites retrieved chunks")',
                ],
            },
            {
                'slug': 'agents-12-evaluating-agents',
                'title': 'Evaluating Agents',
                'desc': 'Measure agent quality: task success, trajectory quality and cost.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['AGENTS-07: Building Agents with LangChain'],
                'objs': [
                    'Define task success metrics',
                    'Evaluate trajectories, not just outcomes',
                    'Build a task suite',
                    'Track cost per task',
                ],
                'samples': [
                    'import numpy as np\n\nsuccess = np.array([1, 1, 0, 1, 0])\nprint("task success rate:", success.mean())',
                    'print("a successful task can still waste 10x the steps")',
                    'tasks = [\n    {"goal": "find the CEO of OpenAI", "expected": "Sam Altman"},\n    {"goal": "sum 2 and 3", "expected": "5"},\n]\nprint("task suite:", len(tasks))',
                    'print("cost budget: tokens + tool calls per task")',
                ],
            },
            {
                'slug': 'agents-13-safety-and-control',
                'title': 'Agent Safety & Control',
                'desc': 'Constrain autonomy: limits, approvals, sandboxes and fail-safes.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['AGENTS-06: Multi-Agent Systems'],
                'objs': [
                    'Design autonomy limits',
                    'Require human approval for risky actions',
                    'Sandbox tool execution',
                    'Add circuit breakers',
                ],
                'samples': [
                    'limits = {"max_steps": 10, "max_cost": 1.0, "approval_required": ["send_email", "delete"]}\nprint(limits)',
                    'print("risky tools: pause and ask the human")',
                    'print("sandbox: agents run in isolated environments")',
                    'print("circuit breaker: stop the loop after repeated failures")',
                ],
            },
            {
                'slug': 'agents-14-human-in-the-loop',
                'title': 'Human-in-the-Loop Patterns',
                'desc': 'Design agents that escalate and collaborate with people instead of acting alone.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['AGENTS-13: Agent Safety & Control'],
                'objs': [
                    'Design escalation triggers',
                    'Support approval workflows',
                    'Collect corrections',
                    'Learn from human feedback',
                ],
                'samples': [
                    'def maybe_escalate(confidence):\n    return "human" if confidence < 0.7 else "agent"\n\nprint(maybe_escalate(0.5))',
                    'print("corrections become training data and eval cases")',
                    'print("approval: agent proposes, human disposes")',
                    'print("feedback loop: every escalation is a reviewable event")',
                ],
            },
            {
                'slug': 'agents-15-agent-observability',
                'title': 'Agent Observability',
                'desc': 'Trace every thought, tool call and step — because agents fail in the middle, not the end.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['AGENTS-12: Evaluating Agents'],
                'objs': [
                    'Log complete agent traces',
                    'Visualize trajectories',
                    'Alert on stuck loops',
                    'Replay failures',
                ],
                'samples': [
                    'trace = {\n    "steps": [\n        {"thought": "...", "tool": "search", "args": "x", "result": "..."},\n    ],\n    "cost": 0.02,\n    "duration_ms": 1800,\n}\nprint(trace)',
                    'import time\n\nfor i in range(3):\n    print(f"[trace] step {i}")\n    time.sleep(0.01)',
                    'print("alert: no progress after N steps")',
                    'print("replay: same task, same version, same failure")',
                ],
            },
            {
                'slug': 'agents-16-deploying-agents',
                'title': 'Deploying Agents',
                'desc': 'Run agents as services: queues, timeouts, scaling and versioning.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['AGENTS-15: Agent Observability'],
                'objs': [
                    'Serve agents via APIs',
                    'Use task queues for long runs',
                    'Set timeouts and retries',
                    'Version agents with prompts and tools',
                ],
                'samples': [
                    'from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.post("/agent")\ndef run_agent(task: str):\n    return {"status": "queued", "task": task}\n\nprint("agent API ready")',
                    'import asyncio\n\n# Long tasks belong in a queue, not a request\nprint("worker: consume tasks -> run agent -> store result")',
                    'import time\n\n# Hard timeout beats an infinite loop\nstart = time.perf_counter()\nwhile time.perf_counter() - start < 30:\n    pass\nprint("timeout enforced")',
                    'print("version: prompt + tools + model = the agent artifact")',
                ],
            },
            {
                'slug': 'agents-17-agent-design-patterns',
                'title': 'Agent Design Patterns',
                'desc': 'Reusable blueprints: reflection, tool use, planning, multi-agent collaboration.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['AGENTS-06: Multi-Agent Systems'],
                'objs': [
                    'Identify the core agent patterns',
                    'Apply reflection for self-improvement',
                    'Use planner-executor separation',
                    'Choose a pattern by task type',
                ],
                'samples': [
                    'patterns = ["reflection", "tool use", "planning", "multi-agent", "evaluator-optimizer"]\nfor p in patterns:\n    print(f"- {p}")',
                    'print("reflection: generate, critique, regenerate")',
                    'print("planner: plan steps, executor: run them")',
                    'print("match the pattern to the task\'s uncertainty")',
                ],
            },
            {
                'slug': 'agents-18-enterprise-agents',
                'title': 'Enterprise Agent Applications',
                'desc': 'Support, HR, finance and knowledge agents inside real organizations.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['AGENTS-14: Human-in-the-Loop Patterns'],
                'objs': [
                    'Design a support agent with escalation',
                    'Integrate with enterprise systems',
                    'Handle permissions and access control',
                    'Measure business outcomes',
                ],
                'samples': [
                    'support_flow = ["classify intent", "retrieve KB", "answer or escalate"]\nprint(support_flow)',
                    'print("permissions: the agent can only see what the user can see")',
                    'print("integrations: ticketing, CRM, docs, knowledge bases")',
                    'print("outcomes: resolution time, CSAT, cost per ticket")',
                ],
            },
            {
                'slug': 'agents-19-agent-cost-and-scale',
                'title': 'Agent Cost & Scale',
                'desc': 'Make agents affordable: token budgets, model routing and parallel workers.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['AGENTS-12: Evaluating Agents'],
                'objs': [
                    'Model agent token cost',
                    'Route steps to cheaper models',
                    'Parallelize independent tasks',
                    'Budget per user or task',
                ],
                'samples': [
                    'steps = 8\ntokens_per_step = 800\ncost = steps * tokens_per_step / 1000 * 0.00015\nprint("cost per task:", round(cost, 4))',
                    'print("simple steps: small model. hard steps: big model.")',
                    'import asyncio\n\nasync def run_many(tasks):\n    return await asyncio.gather(*[run_agent(t) for t in tasks])\n\nprint("parallel workers ready")',
                    'print("per-user budget caps runaway spend")',
                ],
            },
            {
                'slug': 'agents-20-future-of-agents',
                'title': 'The Future of Agents',
                'desc': 'Long-horizon tasks, self-improvement and the research frontier.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['AGENTS-17: Agent Design Patterns'],
                'objs': [
                    'Describe long-horizon agent challenges',
                    'Discuss self-improvement loops',
                    'Understand agent benchmarks',
                    'Identify open problems',
                ],
                'samples': [
                    'open_problems = ["reliability", "planning depth", "world models", "long memory"]\nfor p in open_problems:\n    print(f"- {p}")',
                    'print("benchmarks: agent tasks measured like games")',
                    'print("self-improvement: learn from outcomes across tasks")',
                    'print("the gap: perception of the world beyond text")',
                ],
            },
            {
                'slug': 'agents-21-roadmap',
                'title': 'AI Agents Roadmap',
                'desc': 'Synthesize the course into a build plan: ship agents, measure them, iterate.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['AGENTS-20: The Future of Agents'],
                'objs': [
                    'Design a personal agent plan',
                    'Pick flagship agent projects',
                    'Connect agents to LLM engineering and MLOps',
                    'Keep building with evals first',
                ],
                'samples': [
                    'plan = {\n    1: "build a single-tool agent",\n    2: "add memory and retrieval",\n    3: "multi-agent research crew",\n    4: "deploy with guardrails + evals",\n}\nprint(plan)',
                    'print("evals before scale: measure task success first")',
                    'print("next: LLM Engineering for RAG and serving depth")',
                    'print("next: MLOps for production discipline")',
                ],
            },
        ],
    },
]
