#!/usr/bin/env python3
"""Lesson specs for solidity, nim, crystal, d — real 21-lesson courses."""

# ────────────────────────────────────────────────────────────────────────────
# SOLIDITY
# ────────────────────────────────────────────────────────────────────────────
SOLIDITY = {
    'lang': 'solidity',
    'code_lang': 'solidity',
    'refs': [
        ('Solidity Documentation', 'https://docs.soliditylang.org/', 'Official language docs'),
        ('Solidity by Example', 'https://solidity-by-example.org/', 'Learn by working examples'),
        ('CryptoZombies', 'https://cryptozombies.io/', 'Interactive Solidity tutorial'),
        ('Ethereum Development Docs', 'https://ethereum.org/en/developers/docs/', 'Ethereum developer docs'),
    ],
    'lessons': [
        {'slug': 'solidity-01-getting-started', 'title': 'Getting Started with Solidity', 'desc': 'Remix IDE, contracts, and first deploy.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Understand what smart contracts are', 'Use Remix IDE', 'Write a first contract', 'Compile and deploy to a testnet'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\ncontract Hello {\n    string public greeting = "Hello, World!";\n}',
             '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\ncontract Counter {\n    uint256 public count;\n\n    function increment() public {\n        count += 1;\n    }\n}',
             '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\ncontract Owner {\n    address public owner;\n\n    constructor() {\n        owner = msg.sender;\n    }\n}',
             '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\ncontract Greeting {\n    string private message = "hi";\n\n    function setMessage(string calldata m) public {\n        message = m;\n    }\n\n    function getMessage() public view returns (string memory) {\n        return message;\n    }\n}',
         ]},
        {'slug': 'solidity-02-types', 'title': 'Value Types', 'desc': 'uint, int, address, bool, and bytes.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use unsigned and signed integers', 'Work with addresses', 'Use bool and bytes', 'Understand type conversion'],
         'prereq': ['Solidity-01: Getting Started with Solidity'],
         'samples': [
             'uint256 public big = 1e18;\nuint8 public small = 255;',
             'address public wallet = 0x5B38Da6a701c568545dCfcB03FcB875f56beddC4;',
             'bool public active = true;\nbytes32 public hash = keccak256(abi.encodePacked("data"));',
             'uint8 a = 200;\nuint16 b = uint16(a) * 2;   // explicit widening',
         ]},
        {'slug': 'solidity-03-state-variables', 'title': 'State Variables and Storage', 'desc': 'Storage, memory, and calldata.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare state variables', 'Understand storage locations', 'Use memory in functions', 'Distinguish calldata'],
         'prereq': ['Solidity-02: Value Types'],
         'samples': [
             'contract Storage {\n    uint256 public storedData;  // persisted on-chain\n\n    function set(uint256 x) public {\n        storedData = x;\n    }\n}',
             'function f(uint[] memory arr) public pure returns (uint) {\n    return arr.length;\n}',
             'function g(string calldata s) external pure returns (uint) {\n    return bytes(s).length;\n}',
             'uint256 public constant MAX = 1000;\naddress public immutable owner;',
         ]},
        {'slug': 'solidity-04-functions', 'title': 'Functions and Modifiers', 'desc': 'Visibility, view/pure, and custom modifiers.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Set function visibility', 'Use view and pure', 'Write custom modifiers', 'Understand function overloading'],
         'prereq': ['Solidity-03: State Variables and Storage'],
         'samples': [
             'function add(uint a, uint b) public pure returns (uint) {\n    return a + b;\n}',
             'function getBalance() public view returns (uint) {\n    return address(this).balance;\n}',
             'modifier onlyOwner() {\n    require(msg.sender == owner, "not owner");\n    _;\n}\n\nfunction adminAction() public onlyOwner {}',
             'function over(uint a) public pure returns (uint) { return a; }\nfunction over(uint a, uint b) public pure returns (uint) { return a + b; }',
         ]},
        {'slug': 'solidity-05-events', 'title': 'Events and Logging', 'desc': 'Emit events for off-chain listeners.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare events', 'Emit events on state change', 'Index event parameters', 'Query logs from clients'],
         'prereq': ['Solidity-04: Functions and Modifiers'],
         'samples': [
             'event Transfer(address indexed from, address indexed to, uint256 value);\n\nfunction transfer(address to, uint256 value) public {\n    emit Transfer(msg.sender, to, value);\n}',
             'event PriceSet(uint256 price);\n\nfunction setPrice(uint256 p) public {\n    price = p;\n    emit PriceSet(p);\n}',
             'event Log(string message);\n\nfunction logIt() public {\n    emit Log("action performed");\n}',
             'event Deposit(address indexed who, uint256 amount);\n\nreceive() external payable {\n    emit Deposit(msg.sender, msg.value);\n}',
         ]},
        {'slug': 'solidity-06-errors', 'title': 'Errors and Require', 'desc': 'require, revert, assert, and custom errors.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Validate with require', 'Revert with custom errors', 'Use assert for invariants', 'Save gas with error strings'],
         'prereq': ['Solidity-05: Events and Logging'],
         'samples': [
             'function withdraw(uint amount) public {\n    require(balances[msg.sender] >= amount, "insufficient balance");\n    balances[msg.sender] -= amount;\n}',
             'error InsufficientBalance(uint available, uint required);\n\nfunction withdraw(uint amount) public {\n    if (balances[msg.sender] < amount) {\n        revert InsufficientBalance(balances[msg.sender], amount);\n    }\n}',
             'assert(totalSupply >= 0);   // internal invariant',
             'function safeDiv(uint a, uint b) public pure returns (uint) {\n    require(b > 0, "division by zero");\n    return a / b;\n}',
         ]},
        {'slug': 'solidity-07-mappings', 'title': 'Mappings and Structs', 'desc': 'Key-value storage and structured data.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use mapping types', 'Define structs', 'Combine mappings with structs', 'Iterate with arrays'],
         'prereq': ['Solidity-06: Errors and Require'],
         'samples': [
             'mapping(address => uint256) public balances;',
             'struct User {\n    string name;\n    uint256 age;\n}\n\nmapping(address => User) public users;',
             'mapping(address => uint256[]) public payments;',
             'mapping(address => mapping(address => uint256)) public allowances;',
         ]},
        {'slug': 'solidity-08-constructor', 'title': 'Constructors and Inheritance', 'desc': 'Initialize contracts and build hierarchies.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write constructors', 'Pass initial parameters', 'Inherit contracts', 'Call parent constructors'],
         'prereq': ['Solidity-07: Mappings and Structs'],
         'samples': [
             'contract Token {\n    string public name;\n\n    constructor(string memory _name) {\n        name = _name;\n    }\n}',
             'contract Child is Parent {\n    constructor() Parent("arg") {}\n}',
             'contract A { function f() public pure virtual returns (string memory) { return "A"; } }\ncontract B is A { function f() public pure override returns (string memory) { return "B"; } }',
             'abstract contract Base {\n    function doWork() public virtual;\n}\n\ncontract Impl is Base {\n    function doWork() public override {}\n}',
         ]},
        {'slug': 'solidity-09-ether', 'title': 'Ether and Payable Functions', 'desc': 'Send, receive, and track ether.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Send ether with transfer/send/call', 'Receive ether with receive()', 'Track balances', 'Handle refunds safely'],
         'prereq': ['Solidity-08: Constructors and Inheritance'],
         'samples': [
             'function pay() public payable {}\n\nfunction balance() public view returns (uint) {\n    return address(this).balance;\n}',
             'receive() external payable {}\nfallback() external payable {}',
             '(bool ok, ) = to.call{value: amount}("");\nrequire(ok, "send failed");',
             'function withdrawAll() public onlyOwner {\n    (bool ok, ) = payable(owner).call{value: address(this).balance}("");\n    require(ok, "withdraw failed");\n}',
         ]},
        {'slug': 'solidity-10-erc20', 'title': 'ERC-20 Token Standard', 'desc': 'Build a standard fungible token.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Implement totalSupply and balances', 'Implement transfer and approve', 'Implement transferFrom', 'Deploy a real token'],
         'prereq': ['Solidity-09: Ether and Payable Functions'],
         'samples': [
             'contract MyToken {\n    string public name = "MyToken";\n    string public symbol = "MTK";\n    uint8 public decimals = 18;\n    uint256 public totalSupply;\n    mapping(address => uint256) public balanceOf;\n}',
             'function transfer(address to, uint256 value) public returns (bool) {\n    require(balanceOf[msg.sender] >= value, "insufficient");\n    balanceOf[msg.sender] -= value;\n    balanceOf[to] += value;\n    return true;\n}',
             'mapping(address => mapping(address => uint256)) public allowance;\n\nfunction approve(address spender, uint256 value) public returns (bool) {\n    allowance[msg.sender][spender] = value;\n    return true;\n}',
             'function transferFrom(address from, address to, uint256 value) public returns (bool) {\n    require(allowance[from][msg.sender] >= value, "not allowed");\n    allowance[from][msg.sender] -= value;\n    balanceOf[from] -= value;\n    balanceOf[to] += value;\n    return true;\n}',
         ]},
        {'slug': 'solidity-11-erc721', 'title': 'ERC-721 NFTs', 'desc': 'Non-fungible tokens and ownership.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Understand NFT uniqueness', 'Implement minting', 'Transfer ownership', 'Handle metadata'],
         'prereq': ['Solidity-10: ERC-20 Token Standard'],
         'samples': [
             'contract MyNFT {\n    mapping(uint256 => address) public ownerOf;\n    mapping(address => uint256) public balanceOf;\n    uint256 public nextTokenId;\n}',
             'function mint(address to) public returns (uint256) {\n    uint256 id = nextTokenId++;\n    ownerOf[id] = to;\n    balanceOf[to] += 1;\n    return id;\n}',
             'function transfer(address from, address to, uint256 id) public {\n    require(ownerOf[id] == msg.sender, "not owner");\n    ownerOf[id] = to;\n    balanceOf[from] -= 1;\n    balanceOf[to] += 1;\n}',
             'string public baseURI = "https://api.example.com/nft/";\n\nfunction tokenURI(uint256 id) public view returns (string memory) {\n    return string(abi.encodePacked(baseURI, id));\n}',
         ]},
        {'slug': 'solidity-12-dex', 'title': 'DeFi and DEX Patterns', 'desc': 'Liquidity pools and swap mechanics.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand automated market makers', 'Implement a liquidity pool', 'Compute swap amounts', 'Handle fees'],
         'prereq': ['Solidity-11: ERC-721 NFTs'],
         'samples': [
             'contract Pool {\n    uint256 public reserveA;\n    uint256 public reserveB;\n\n    function addLiquidity(uint a, uint b) public {\n        reserveA += a;\n        reserveB += b;\n    }\n}',
             'function swapAtoB(uint amountA) public returns (uint) {\n    uint amountB = (reserveB * amountA) / (reserveA + amountA);\n    reserveA += amountA;\n    reserveB -= amountB;\n    return amountB;\n}',
             'uint256 public constant FEE = 997;  // 0.3%\n\nfunction swapWithFee(uint amountIn) public view returns (uint) {\n    uint amountInWithFee = amountIn * FEE;\n    return (amountInWithFee) / (reserveA * 1000 + amountInWithFee) * reserveB;\n}',
             'function getAmountOut(uint amountIn, uint reserveIn, uint reserveOut) public pure returns (uint) {\n    uint amountInWithFee = amountIn * 997;\n    uint numerator = amountInWithFee * reserveOut;\n    uint denominator = reserveIn * 1000 + amountInWithFee;\n    return numerator / denominator;\n}',
         ]},
        {'slug': 'solidity-13-security', 'title': 'Security: Reentrancy', 'desc': 'Reentrancy attacks and checks-effects-interactions.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand reentrancy attacks', 'Apply checks-effects-interactions', 'Use reentrancy guards', 'Audit withdrawal functions'],
         'prereq': ['Solidity-12: DeFi and DEX Patterns'],
         'samples': [
             '// VULNERABLE: external call before state update\nfunction withdraw(uint amount) public {\n    require(balances[msg.sender] >= amount, "insufficient");\n    (bool ok, ) = msg.sender.call{value: amount}("");\n    require(ok);\n    balances[msg.sender] -= amount;   // too late\n}',
             '// SAFE: state first, then call\nfunction withdraw(uint amount) public {\n    require(balances[msg.sender] >= amount, "insufficient");\n    balances[msg.sender] -= amount;\n    (bool ok, ) = msg.sender.call{value: amount}("");\n    require(ok);\n}',
             'bool private locked;\nmodifier noReentrant() {\n    require(!locked, "reentrant");\n    locked = true;\n    _;\n    locked = false;\n}',
             'function withdraw(uint amount) public noReentrant {\n    require(balances[msg.sender] >= amount);\n    balances[msg.sender] -= amount;\n    (bool ok, ) = msg.sender.call{value: amount}("");\n    require(ok);\n}',
         ]},
        {'slug': 'solidity-14-other-attacks', 'title': 'Security: Overflows and Front-running', 'desc': 'Arithmetic safety and MEV awareness.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Prevent integer overflows', 'Use SafeMath patterns', 'Understand front-running', 'Mitigate oracle manipulation'],
         'prereq': ['Solidity-13: Security: Reentrancy'],
         'samples': [
             '// Solidity 0.8+ checks overflow automatically\nuint256 a = type(uint256).max;\nuint256 b = a + 1;   // reverts in 0.8+',
             'unchecked {\n    uint256 c = a + 1;   // wraps silently — use with care\n}',
             'function commitReveal(bytes32 commit) public {}  // commit phase\nfunction reveal(uint secret) public {}                      // reveal phase',
             'require(block.timestamp <= deadline, "expired");\nrequire(b >= minAmountOut, "slippage too high");',
         ]},
        {'slug': 'solidity-15-gas', 'title': 'Gas Optimization', 'desc': 'Reduce deployment and execution costs.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Optimize storage usage', 'Use calldata over memory', 'Pack variables tightly', 'Avoid expensive operations'],
         'prereq': ['Solidity-14: Security: Overflows and Front-running'],
         'samples': [
             '// Packed: 1 slot\nstruct Packed {\n    uint128 a;\n    uint128 b;\n}\n// Unpacked: 2 slots\nstruct Unpacked {\n    uint256 a;\n    uint256 b;\n}',
             'function read(string calldata s) external pure returns (uint) {\n    return bytes(s).length;\n}',
             'uint256 private immutable deployedAt;\nconstructor() {\n    deployedAt = block.timestamp;\n}',
             'require(gasleft() > 2300, "not enough gas");',
         ]},
        {'slug': 'solidity-16-libraries', 'title': 'Libraries and Interfaces', 'desc': 'Reusable library code and contract interfaces.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write libraries', 'Use library functions', 'Define interfaces', 'Interact with external contracts'],
         'prereq': ['Solidity-15: Gas Optimization'],
         'samples': [
             'library Math {\n    function sqrt(uint256 x) internal pure returns (uint256) {\n        return x ** 0.5;\n    }\n}',
             'library SafeMath {\n    function add(uint a, uint b) internal pure returns (uint) {\n        require(a + b >= a, "overflow");\n        return a + b;\n    }\n}',
             'interface IERC20 {\n    function transfer(address to, uint256 amount) external returns (bool);\n}',
             'function payWithToken(IERC20 token, address to, uint256 amount) public {\n    token.transfer(to, amount);\n}',
         ]},
        {'slug': 'solidity-17-upgrades', 'title': 'Upgradeable Contracts', 'desc': 'Proxy patterns and upgradeability.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand proxy pattern', 'Use delegatecall', 'Deploy with OpenZeppelin', 'Manage storage layouts'],
         'prereq': ['Solidity-16: Libraries and Interfaces'],
         'samples': [
             '// Proxy forwards all calls to an implementation\ncontract Proxy {\n    address public implementation;\n\n    fallback() external payable {\n        (bool ok, ) = implementation.delegatecall(msg.data);\n        require(ok);\n    }\n}',
             'contract Logic {\n    uint256 public value;\n    function setValue(uint256 v) public {\n        value = v;\n    }\n}',
             'function upgrade(address newImpl) public onlyOwner {\n    implementation = newImpl;\n}',
             '// Warning: preserve storage layout across upgrades',
         ]},
        {'slug': 'solidity-18-testing', 'title': 'Testing Smart Contracts', 'desc': 'Write tests with Foundry and Hardhat.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write Foundry tests', 'Use test modifiers', 'Test with cheats', 'Measure coverage'],
         'prereq': ['Solidity-17: Upgradeable Contracts'],
         'samples': [
             '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.20;\n\nimport {Test} from "forge-std/Test.sol";\n\ncontract CounterTest is Test {\n    function testIncrement() public {\n        // arrange, act, assert\n    }\n}',
             'function testCounter() public {\n    Counter c = new Counter();\n    c.increment();\n    assertEq(c.count(), 1);\n}',
             'function testFuzz(uint256 n) public {\n    vm.assume(n < 100);\n    assertTrue(n > 0 || n < 100);\n}',
             'function testRevert() public {\n    vm.expectRevert("insufficient");\n    c.withdraw(1 ether);\n}',
         ]},
        {'slug': 'solidity-19-hardhat', 'title': 'Hardhat Development Workflow', 'desc': 'Deploy, verify, and interact from scripts.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Set up a Hardhat project', 'Write deploy scripts', 'Verify contracts', 'Interact via console'],
         'prereq': ['Solidity-18: Testing Smart Contracts'],
         'samples': [
             'npx hardhat init\nnpx hardhat compile',
             'const { ethers } = require("hardhat");\nasync function main() {\n  const Token = await ethers.getContractFactory("MyToken");\n  const token = await Token.deploy();\n  await token.waitForDeployment();\n  console.log("Deployed:", await token.getAddress());\n}',
             'npx hardhat run scripts/deploy.js --network sepolia',
             'npx hardhat verify --network sepolia DEPLOYED_ADDRESS',
         ]},
        {'slug': 'solidity-20-chainlink', 'title': 'Oracles and Real-World Data', 'desc': 'Bring off-chain data on-chain.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand oracle problem', 'Use Chainlink price feeds', 'Get randomness with VRF', 'Call external APIs'],
         'prereq': ['Solidity-19: Hardhat Development Workflow'],
         'samples': [
             'import {AggregatorV3Interface} from "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";\n\ncontract PriceFeed {\n    AggregatorV3Interface internal feed;\n    constructor() {\n        feed = AggregatorV3Interface(0x694AA1769357215DE4FAC081bf1f309aDC325306);\n    }\n}',
             'function latestPrice() public view returns (int256) {\n    (, int256 price, , , ) = feed.latestRoundData();\n    return price;\n}',
             'function requestRandom() public returns (uint256 requestId) {\n    requestId = vrfCoordinator.requestRandomWords(\n        keyHash, s_subscriptionId, 3, 1, 1\n    );\n}',
             'require(timestamp > lastUpdate + interval, "too soon");\nlastUpdate = timestamp;',
         ]},
        {'slug': 'solidity-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Mainnets, DAOs, and production readiness.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Deploy to mainnet safely', 'Understand DAO patterns', 'Use OpenZeppelin contracts', 'Follow audit best practices'],
         'prereq': ['Solidity-20: Oracles and Real-World Data'],
         'samples': [
             'npm install @openzeppelin/contracts',
             'import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";\n\ncontract MyToken is ERC20 {\n    constructor() ERC20("MyToken", "MTK") {\n        _mint(msg.sender, 1_000_000 * 10 ** 18);\n    }\n}',
             '// Pre-deploy checklist: audit, tests, fuzzing, timelock',
             '// Next: layer-2 deployments, account abstraction, cross-chain',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# NIM
# ────────────────────────────────────────────────────────────────────────────
NIM = {
    'lang': 'nim',
    'code_lang': 'nim',
    'refs': [
        ('Nim Manual', 'https://nim-lang.org/docs/manual.html', 'Official language manual'),
        ('Nim by Example', 'https://nim-by-example.github.io/', 'Practical Nim examples'),
        ('Nim Tutorial', 'https://nim-lang.org/docs/tut1.html', 'Official tutorial'),
        ('Nim Forum', 'https://forum.nim-lang.org/', 'Community discussions'),
    ],
    'lessons': [
        {'slug': 'nim-01-getting-started', 'title': 'Getting Started with Nim', 'desc': 'Install, compile, and run your first program.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install Nim via choosenim', 'Compile with nim c', 'Write hello world', 'Understand nimble packages'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'echo "Hello, World!"',
             'nim c -r hello.nim',
             'import std/strutils\n\necho "Hello, " & "Nim!"',
             'const version = "1.0.0"\necho "Nim version: ", NimVersion',
         ]},
        {'slug': 'nim-02-variables', 'title': 'Variables and Types', 'desc': 'var, let, const, and built-in types.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use var, let, and const', 'Work with integer types', 'Use floats and strings', 'Understand type inference'],
         'prereq': ['Nim-01: Getting Started with Nim'],
         'samples': [
             'var x = 10\nlet y = 20        # immutable\nconst z = 30      # compile-time\n\necho x, " ", y, " ", z',
             'var count: int = 0\ncount += 1',
             'let pi = 3.14159\nlet name = "Nim"',
             'var a = 5\nvar b = 2\necho a div b, " ", a mod b',
         ]},
        {'slug': 'nim-03-control-flow', 'title': 'Control Flow', 'desc': 'if, case, and loops.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/elif/else', 'Use case statements', 'Write for and while loops', 'Use break and continue'],
         'prereq': ['Nim-02: Variables and Types'],
         'samples': [
             'let score = 85\nif score >= 90:\n  echo "A"\nelif score >= 80:\n  echo "B"\nelse:\n  echo "C"',
             'let n = 2\ncase n\nof 1: echo "one"\nof 2: echo "two"\nelse: echo "other"',
             'for i in 1..5:\n  echo i',
             'var i = 0\nwhile i < 3:\n  inc i\necho i',
         ]},
        {'slug': 'nim-04-collections', 'title': 'Sequences and Arrays', 'desc': 'Dynamic sequences and fixed arrays.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create sequences', 'Index and iterate', 'Use array literals', 'Slice collections'],
         'prereq': ['Nim-03: Control Flow'],
         'samples': [
             'var nums = @[1, 2, 3]\nnums.add(4)\necho nums',
             'let fixed = [10, 20, 30]\necho fixed[1]',
             'for n in nums:\n  echo n',
             'let a = @[1, 2, 3, 4, 5]\necho a[1..3]   # @[2, 3, 4]',
         ]},
        {'slug': 'nim-05-strings', 'title': 'Strings', 'desc': 'String operations and formatting.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Concatenate strings', 'Format with & and fmt', 'Split and join', 'Convert between types'],
         'prereq': ['Nim-04: Sequences and Arrays'],
         'samples': [
             'import std/strutils\n\nlet a = "Hello"\nlet b = a & " " & "World"\necho b',
             'let name = "Ada"\necho "Hi, ", name, "!"',
             'import std/strformat\nlet x = 42\necho fmt"value = {x}"',
             'let parts = "a,b,c".split(",")\necho parts.join(" | ")',
         ]},
        {'slug': 'nim-06-procs', 'title': 'Procedures', 'desc': 'Write typed procedures with defaults.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write procedures', 'Use return types', 'Provide default args', 'Use named arguments'],
         'prereq': ['Nim-05: Strings'],
         'samples': [
             'proc add(a, b: int): int =\n  result = a + b\n\necho add(2, 3)',
             'proc greet(name: string, excited = false) =\n  if excited:\n    echo name, "!!"\n  else:\n    echo name\n\ngreet("Ada", excited = true)',
             'proc double(x: int): int = x * 2',
             'proc swapInts(a, b: var int) =\n  let tmp = a\n  a = b\n  b = tmp',
         ]},
        {'slug': 'nim-07-objects', 'title': 'Objects and References', 'desc': 'Define and use object types.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define object types', 'Create object instances', 'Access fields', 'Use default field values'],
         'prereq': ['Nim-06: Procedures'],
         'samples': [
             'type\n  Person = object\n    name: string\n    age: int\n\nlet p = Person(name: "Ada", age: 36)\necho p.name',
             'type\n  Point = object\n    x, y: float\n\nlet origin = Point(x: 0.0, y: 0.0)',
             'var p: Person\np.name = "Grace"\np.age = 85',
             'type\n  Account = object\n    balance: float = 0.0',
         ]},
        {'slug': 'nim-08-enums', 'title': 'Enums and Case Objects', 'desc': 'Enumerations and variant objects.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define enums', 'Use case with enums', 'Use case objects', 'Convert enums to strings'],
         'prereq': ['Nim-07: Objects and References'],
         'samples': [
             'type\n  Color = enum\n    Red, Green, Blue\n\nlet c = Green\necho c',
             'type\n  ShapeKind = enum\n    Circle, Square\n  Shape = object\n    case kind: ShapeKind\n    of Circle:\n      radius: float\n    of Square:\n      side: float',
             'case c\nof Red: echo "red"\nof Green: echo "green"\nof Blue: echo "blue"',
             'echo ord(Green), " ", $Green',
         ]},
        {'slug': 'nim-09-generics', 'title': 'Generics', 'desc': 'Type-parameterized code.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write generic procs', 'Use generic types', 'Constrain type params', 'Build generic collections'],
         'prereq': ['Nim-08: Enums and Case Objects'],
         'samples': [
             'proc identity[T](x: T): T = x\n\necho identity(42)\necho identity("hi")',
             'proc first[T](s: seq[T]): T = s[0]',
             'proc max[T](a, b: T): T =\n  if a > b: a else: b',
             'type\n  Stack[T] = object\n    items: seq[T]',
         ]},
        {'slug': 'nim-10-exceptions', 'title': 'Exceptions and Error Handling', 'desc': 'try/except and raise.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Raise exceptions', 'Catch with try/except', 'Use finally', 'Define custom exceptions'],
         'prereq': ['Nim-09: Generics'],
         'samples': [
             'try:\n  let x = parseInt("abc")\nexcept ValueError:\n  echo "bad number"',
             'proc check(n: int) =\n  if n < 0:\n    raise newException(ValueError, "negative")\n\ntry:\n  check(-1)\nexcept ValueError as e:\n  echo e.msg',
             'try:\n  risky()\nfinally:\n  echo "always runs"',
             'type\n  MyError = object of CatchableError\n\nraise newException(MyError, "custom failure")',
         ]},
        {'slug': 'nim-11-tables', 'title': 'Tables and Sets', 'desc': 'Hash tables and sets from stdlib.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create tables', 'Insert and lookup', 'Iterate key-value pairs', 'Use sets'],
         'prereq': ['Nim-10: Exceptions and Error Handling'],
         'samples': [
             'import std/tables\n\nvar ages = initTable[string, int]()\nages["ada"] = 36\necho ages["ada"]',
             'let caps = {"us": "DC", "uk": "London"}.toTable\necho caps["us"]',
             'for k, v in ages:\n  echo k, ": ", v',
             'import std/sets\nvar s = toHashSet([1, 2, 3])\nif 2 in s: echo "yes"',
         ]},
        {'slug': 'nim-12-file-io', 'title': 'File Input/Output', 'desc': 'Read and write files.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Read whole files', 'Write files', 'Read line by line', 'Handle file errors'],
         'prereq': ['Nim-11: Tables and Sets'],
         'samples': [
             'let content = readFile("data.txt")\necho content',
             'writeFile("out.txt", "hello")',
             'for line in lines("data.txt"):\n  echo line',
             'import std/os\nif fileExists("data.txt"):\n  echo "exists"',
         ]},
        {'slug': 'nim-13-io-streams', 'title': 'Streams and stdin/stdout', 'desc': 'Stream processing and user input.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Read from stdin', 'Write to stdout', 'Use streams', 'Format output'],
         'prereq': ['Nim-12: File Input/Output'],
         'samples': [
             'import std/strutils\n\nlet input = readLine(stdin)\necho "You said: ", input',
             'stdout.write("no newline")\nstdout.flushFile()',
             'import std/streams\nlet s = newStringStream("hello")\necho s.readAll()',
             'echo "done"  # writes to stdout with newline',
         ]},
        {'slug': 'nim-14-iterators', 'title': 'Iterators', 'desc': 'Custom iteration logic.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write iterator procs', 'Use yield', 'Chain iterators', 'Build lazy sequences'],
         'prereq': ['Nim-13: Streams and stdin/stdout'],
         'samples': [
             'iterator countdownFrom(n: int): int =\n  var i = n\n  while i >= 0:\n    yield i\n    dec i\n\nfor x in countdownFrom(3):\n  echo x',
             'iterator doubles(s: seq[int]): int =\n  for x in s:\n    yield x * 2',
             'iterator fib(n: int): int =\n  var a, b = 1\n  for _ in 1..n:\n    yield a\n    (a, b) = (b, a + b)',
             'for even in filterIt(toSeq(1..10), it mod 2 == 0):\n  echo even',
         ]},
        {'slug': 'nim-15-concurrency', 'title': 'Concurrency with Threads', 'desc': 'Threads, channels, and locks.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Spawn threads', 'Communicate with channels', 'Protect shared state', 'Join threads'],
         'prereq': ['Nim-14: Iterators'],
         'samples': [
             'import std/threadpool\n\nproc work(i: int) =\n  echo "task ", i\n\nparallel:\n  for i in 1..4:\n    spawn work(i)',
             'import std/os\n\ntry:\n  doWork()\nexcept:\n  echo getCurrentExceptionMsg()',
             'var ch = newChannel[int](4)\nch.send(42)\necho ch.recv()',
             'import std/locks\nvar L: Lock\ninitLock(L)\nwithLock L:\n  counter += 1',
         ]},
        {'slug': 'nim-16-macros', 'title': 'Macros and Metaprogramming', 'desc': 'Compile-time code generation.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand AST concepts', 'Write simple macros', 'Use quote and parseExpr', 'Generate code at compile time'],
         'prereq': ['Nim-15: Concurrency with Threads'],
         'samples': [
             'import std/macros\n\nmacro hello(): untyped =\n  result = newLit("hello from macro")\n\necho hello()',
             'macro twice(x: untyped): untyped =\n  result = quote do:\n    `x`\n    `x`',
             'import std/macros\necho treeRepr(parseExpr("1 + 2 * 3"))',
             'const val = block:\n  var s = 0\n  for i in 1..10: s += i\n  s\necho val',
         ]},
        {'slug': 'nim-17-templates', 'title': 'Templates', 'desc': 'Inline code substitution.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write templates', 'Use template parameters', 'Avoid common pitfalls', 'Compare with macros'],
         'prereq': ['Nim-16: Macros and Metaprogramming'],
         'samples': [
             'template twice(statement: untyped) =\n  statement\n  statement\n\ntwice:\n  echo "hello"',
             'template withRetry(body: untyped) =\n  var attempts = 0\n  while true:\n    try:\n      body\n      break\n    except:\n      inc attempts\n      if attempts > 3: raise',
             'template assertMsg(cond: bool, msg: string) =\n  if not cond:\n    echo "assert failed: ", msg',
             'echo "templates run at compile time"',
         ]},
        {'slug': 'nim-18-ffi', 'title': 'Foreign Function Interface', 'desc': 'Call C libraries from Nim.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Import C functions', 'Pass pointers and structs', 'Use pragma importc', 'Call libc functions'],
         'prereq': ['Nim-17: Templates'],
         'samples': [
             'proc printf(fmt: cstring): cint {.importc, header: "<stdio.h>", varargs.}\n\nprintf("hello %s\\n", "world")',
             'proc strlen(s: cstring): csize_t {.importc, header: "<string.h>".}\n\necho strlen("hello")',
             'proc malloc(size: csize_t): pointer {.importc, header: "<stdlib.h>".}',
             'type\n  CFile {.importc: "FILE", header: "<stdio.h>".} = object',
         ]},
        {'slug': 'nim-19-nimscript', 'title': 'NimScript and Build Tooling', 'desc': 'Scripting, nimble, and configs.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Run NimScript files', 'Use nimble packages', 'Configure build flags', 'Write simple scripts'],
         'prereq': ['Nim-18: Foreign Function Interface'],
         'samples': [
             'nim script.nims',
             'import std/os\n\necho getCurrentDir()',
             'nimble init my_pkg\nnimble build',
             'switch("opt", "speed")\nswitch("define", "release")',
         ]},
        {'slug': 'nim-20-testing', 'title': 'Testing with unittest', 'desc': 'Write and run unit tests.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write test suites', 'Use check statements', 'Group tests', 'Run tests with nimble'],
         'prereq': ['Nim-19: NimScript and Build Tooling'],
         'samples': [
             'import std/unittest\n\nsuite "math":\n  test "addition":\n    check(2 + 2 == 4)',
             'test "string ops":\n  check("abc".len == 3)\n  check("a" & "b" == "ab")',
             'test "tables":\n  var t = initTable[string, int]()\n  t["k"] = 1\n  check(t["k"] == 1)',
             'require(1 > 0)   # abort on failure',
         ]},
        {'slug': 'nim-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Libraries, web dev, and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Discover popular Nim libraries', 'Build web servers', 'Use Nim for scripting', 'Join the community'],
         'prereq': ['Nim-20: Testing with unittest'],
         'samples': [
             'import std/httpclient\n\nlet client = newHttpClient()\necho client.getContent("https://example.com")',
             'import std/asynchttpserver\n\nvar server = newAsyncHttpServer()\nproc cb(req: Request) {.async.} =\n  await req.respond(Http200, "Hello")\n\nwaitFor server.serve(Port(8080), cb)',
             'nimble search json',
             'import std/json\nlet data = parseJson("""{"a": 1}""")\necho data["a"]',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# CRYSTAL
# ────────────────────────────────────────────────────────────────────────────
CRYSTAL = {
    'lang': 'crystal',
    'code_lang': 'crystal',
    'refs': [
        ('Crystal Language Reference', 'https://crystal-lang.org/reference/', 'Official docs'),
        ('Crystal for Rubyists', 'https://crystal-lang.org/reference/guides/faq.html', 'Migration guide'),
        ('Crystal Book', 'https://crystal-lang.org/reference/', 'Official reference book'),
        ('Crystal Forum', 'https://forum.crystal-lang.org/', 'Community'),
    ],
    'lessons': [
        {'slug': 'crystal-01-getting-started', 'title': 'Getting Started with Crystal', 'desc': 'Install, compile, and run Crystal.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install Crystal', 'Compile with crystal build', 'Write hello world', 'Run with crystal run'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'puts "Hello, World!"',
             'crystal run hello.cr',
             'crystal build hello.cr -o hello\n./hello',
             'puts "Hello, " + ARGV[0]? || "World"',
         ]},
        {'slug': 'crystal-02-variables', 'title': 'Variables and Types', 'desc': 'Type inference, unions, and constants.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use type inference', 'Declare explicit types', 'Use unions', 'Define constants'],
         'prereq': ['Crystal-01: Getting Started with Crystal'],
         'samples': [
             'x = 42\nputs x.class',
             'y : Int32 = 10\nputs y',
             'value = "hello"\nvalue = 42   # union of String | Int32\nputs value',
             'MAX = 100\nputs MAX',
         ]},
        {'slug': 'crystal-03-control-flow', 'title': 'Control Flow', 'desc': 'if, unless, case, and loops.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/elsif/else', 'Use unless', 'Use case/when', 'Iterate with loops'],
         'prereq': ['Crystal-02: Variables and Types'],
         'samples': [
             'score = 85\nif score >= 90\n  puts "A"\nelsif score >= 80\n  puts "B"\nelse\n  puts "C"\nend',
             'unless score < 60\n  puts "passed"\nend',
             'case score\nwhen 90..100 then puts "A"\nwhen 80...90 then puts "B"\nelse puts "C"\nend',
             '3.times { puts "hi" }\n(1..3).each { |i| puts i }',
         ]},
        {'slug': 'crystal-04-strings', 'title': 'Strings and Interpolation', 'desc': 'String ops, interpolation, and heredocs.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Interpolate strings', 'Concatenate and transform', 'Use string methods', 'Work with heredocs'],
         'prereq': ['Crystal-03: Control Flow'],
         'samples': [
             'name = "Ada"\nputs "Hello, #{name}!"',
             'puts "hello".upcase\nputs "  hi  ".strip',
             'puts "a,b,c".split(",").join(" | ")',
             'text = <<-EOF\n  multi-line\n  heredoc\nEOF\nputs text',
         ]},
        {'slug': 'crystal-05-arrays', 'title': 'Arrays and Tuples', 'desc': 'Collections and tuple types.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create arrays', 'Use array methods', 'Index and slice', 'Use tuples'],
         'prereq': ['Crystal-04: Strings and Interpolation'],
         'samples': [
             'nums = [1, 2, 3]\nnums << 4\nputs nums.sum',
             'arr = [1, 2, 3, 4]\nputs arr.select { |n| n.even? }',
             'puts arr[0]\nputs arr[1..2]',
             't = {1, "two", 3.0}\nputs t[1]',
         ]},
        {'slug': 'crystal-06-hashes', 'title': 'Hashes and Sets', 'desc': 'Key-value storage.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create hashes', 'Insert and fetch', 'Iterate entries', 'Use default values'],
         'prereq': ['Crystal-05: Arrays and Tuples'],
         'samples': [
             'ages = {"ada" => 36, "grace" => 85}\nputs ages["ada"]',
             'ages["alan"] = 41\nputs ages',
             'ages.each { |k, v| puts "#{k}: #{v}" }',
             'counts = Hash(String, Int32).new(0)\ncounts["x"] += 1',
         ]},
        {'slug': 'crystal-07-methods', 'title': 'Methods', 'desc': 'Define methods with args and returns.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write methods', 'Use default arguments', 'Use named arguments', 'Return values'],
         'prereq': ['Crystal-06: Hashes and Sets'],
         'samples': [
             'def add(a, b)\n  a + b\nend\n\nputs add(2, 3)',
             'def greet(name, excited = false)\n  excited ? "HI #{name.upcase}!" : "hi #{name}"\nend',
             'def pow(base, exp)\n  base ** exp\nend\n\nputs pow(base: 2, exp: 8)',
             'def describe(x : Int32 | String)\n  case x\n  when Int32 then "number #{x}"\n  else "string #{x}"\n  end\nend',
         ]},
        {'slug': 'crystal-08-classes', 'title': 'Classes', 'desc': 'OOP with classes and accessors.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define classes', 'Add getters/setters', 'Use initialize', 'Write instance methods'],
         'prereq': ['Crystal-07: Methods'],
         'samples': [
             'class Person\n  getter name : String\n  getter age : Int32\n\n  def initialize(@name, @age)\n  end\n\n  def greet\n    "Hi, I am #{@name}"\n  end\nend\n\np = Person.new("Ada", 36)\nputs p.greet',
             'class Counter\n  property count = 0\n\n  def increment!\n    @count += 1\n  end\nend',
             'class Point\n  def initialize(@x : Int32, @y : Int32)\n  end\n\n  def +(other : Point)\n    Point.new(@x + other.x, @y + other.y)\n  end\nend',
             'class Config\n  @@instances = 0\n\n  def self.count\n    @@instances\n  end\nend',
         ]},
        {'slug': 'crystal-09-modules', 'title': 'Modules and Mixins', 'desc': 'Code reuse with modules.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define modules', 'Include modules', 'Extend modules', 'Use namespaces'],
         'prereq': ['Crystal-08: Classes'],
         'samples': [
             'module Greetings\n  def hello\n    "hello"\n  end\nend\n\nclass Person\n  include Greetings\nend\n\nputs Person.new.hello',
             'module MathUtils\n  def self.square(x)\n    x * x\n  end\nend\n\nputs MathUtils.square(4)',
             'module A\n  def f\n    "A"\n  end\nend\n\nmodule B\n  def f\n    "B"\n  end\nend\n\nclass C\n  include A\n  include B\nend',
             'module Geometry\n  VERSION = "1.0"\nend',
         ]},
        {'slug': 'crystal-10-enums', 'title': 'Enums', 'desc': 'Typed enumerations.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define enums', 'Use enum values', 'Iterate enums', 'Convert to strings'],
         'prereq': ['Crystal-09: Modules and Mixins'],
         'samples': [
             'enum Color\n  Red\n  Green\n  Blue\nend\n\nc = Color::Green\nputs c',
             'enum Direction\n  North\n  East\n  South\n  West\nend\n\nDirection.each { |d| puts d }',
             'case Color::Red\nwhen Color::Red   then puts "red"\nwhen Color::Green then puts "green"\nend',
             'puts Color::Blue.to_s\nputs Color.parse("Red")',
         ]},
        {'slug': 'crystal-11-exceptions', 'title': 'Exceptions', 'desc': 'Raise and rescue errors.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Raise exceptions', 'Rescue errors', 'Use ensure', 'Create custom exceptions'],
         'prereq': ['Crystal-10: Enums'],
         'samples': [
             'def check(n)\n  raise "negative" if n < 0\nend\n\nbegin\n  check(-1)\nrescue e\n  puts e.message\nend',
             'begin\n  risky\nrescue ArgumentError\n  puts "bad arg"\nrescue\n  puts "other"\nend',
             'begin\n  work\nensure\n  cleanup\nend',
             'class MyError < Exception\nend\n\nraise MyError.new("custom")',
         ]},
        {'slug': 'crystal-12-blocks', 'title': 'Blocks and Procs', 'desc': 'Higher-order functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Pass blocks to methods', 'Use yield', 'Capture blocks as procs', 'Build with blocks'],
         'prereq': ['Crystal-11: Exceptions'],
         'samples': [
             'def repeat(n)\n  n.times { yield }\nend\n\nrepeat(3) { puts "hi" }',
             'def each_with_log(items)\n  items.each do |item|\n    puts "processing #{item}"\n    yield item\n  end\nend',
             'square = ->(x : Int32) { x * x }\nputs square.call(5)',
             'def apply(items, &block : Int32 -> Int32)\n  items.map { |i| block.call(i) }\nend\n\nputs apply([1, 2, 3]) { |i| i + 1 }',
         ]},
        {'slug': 'crystal-13-io', 'title': 'File and Standard IO', 'desc': 'Read and write files.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Read files', 'Write files', 'Read stdin', 'Handle paths'],
         'prereq': ['Crystal-12: Blocks and Procs'],
         'samples': [
             'puts File.read("data.txt")',
             'File.write("out.txt", "hello")',
             'input = gets\nputs "You said: #{input}"',
             'File.open("log.txt", "a") do |f|\n  f.puts "new line"\nend',
         ]},
        {'slug': 'crystal-14-generics', 'title': 'Generics', 'desc': 'Type-parameterized code.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write generic classes', 'Constrain type params', 'Use generic methods', 'Build containers'],
         'prereq': ['Crystal-13: File and Standard IO'],
         'samples': [
             'class Box(T)\n  getter value : T\n\n  def initialize(@value)\n  end\nend\n\nb = Box(Int32).new(42)\nputs b.value',
             'def first(t : Array(T)) forall T\n  t.first\nend',
             'class Pair(A, B)\n  getter a : A\n  getter b : B\n\n  def initialize(@a, @b)\n  end\nend',
             'class Stack(T)\n  @items = [] of T\n\n  def push(item : T)\n    @items << item\n  end\nend',
         ]},
        {'slug': 'crystal-15-concurrency', 'title': 'Fibers and Channels', 'desc': 'Green threads and CSP.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Spawn fibers', 'Use channels', 'Coordinate with select', 'Understand Crystal scheduling'],
         'prereq': ['Crystal-14: Generics'],
         'samples': [
             'spawn do\n  puts "in fiber"\nend\n\nFiber.yield\nputs "main"',
             'ch = Channel(Int32).new\nspawn do\n  ch.send(42)\nend\n\nputs ch.receive',
             'ch = Channel(Int32).new\n10.times do |i|\n  spawn { ch.send(i) }\nend\n\n10.times { puts ch.receive }',
             'select\nwhen msg = ch1.receive\n  puts "from ch1: #{msg}"\nwhen msg = ch2.receive\n  puts "from ch2: #{msg}"\nend',
         ]},
        {'slug': 'crystal-16-macros', 'title': 'Macros', 'desc': 'Compile-time metaprogramming.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write macros', 'Use macro methods', 'Generate code', 'Inspect types'],
         'prereq': ['Crystal-15: Fibers and Channels'],
         'samples': [
             'macro define_getter(name)\n  def {{name.id}}\n    @{{name.id}}\n  end\nend\n\nclass Person\n  @name = "Ada"\n  define_getter(name)\nend\n\nputs Person.new.name',
             'macro hello\n  "hello from macro"\nend\n\nputs hello',
             'macro assert_not_nil(expr)\n  {% if expr.is_a?(NilLiteral) %}\n    raise "nil detected"\n  {% end %}\nend',
             'macro list_methods(klass)\n  {{ klass.methods.map(&.name.stringify) }}\nend',
         ]},
        {'slug': 'crystal-17-web', 'title': 'Web Servers with Kemal', 'desc': 'Build HTTP services.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Set up Kemal', 'Define routes', 'Handle JSON', 'Serve requests'],
         'prereq': ['Crystal-16: Macros'],
         'samples': [
             'require "kemal"\n\nget "/" do\n  "Hello, World!"\nend\n\nKemal.run',
             'get "/hello/:name" do |env|\n  name = env.params.url["name"]\n  "Hello, #{name}!"\nend',
             'require "json"\n\nget "/api/user" do |env|\n  user = {name: "Ada", age: 36}.to_json\n  user\nend',
             'post "/echo" do |env|\n  env.request.body.try(&.gets_to_end)\nend',
         ]},
        {'slug': 'crystal-18-http-client', 'title': 'HTTP Clients and JSON', 'desc': 'Consume APIs from Crystal.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Make HTTP requests', 'Parse JSON', 'Use typed JSON', 'Handle errors'],
         'prereq': ['Crystal-17: Web Servers with Kemal'],
         'samples': [
             'require "http/client"\n\nresponse = HTTP::Client.get("https://example.com")\nputs response.body',
             'require "json"\n\ndata = JSON.parse(response.body)\nputs data["title"]',
             'struct User\n  include JSON::Serializable\n  property name : String\n  property age : Int32\nend\n\nuser = User.from_json(response.body)\nputs user.name',
             'HTTP::Client.get("https://api.example.com") do |res|\n  puts res.status_code\nend',
         ]},
        {'slug': 'crystal-19-db', 'title': 'Database Access', 'desc': 'SQLite and Postgres with Crystal.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Connect to databases', 'Run queries', 'Use prepared statements', 'Map rows'],
         'prereq': ['Crystal-18: HTTP Clients and JSON'],
         'samples': [
             'require "sqlite3"\n\ndb = DB.open("sqlite3://./test.db")\ndb.exec("CREATE TABLE IF NOT EXISTS users (name TEXT)")',
             'db.exec("INSERT INTO users (name) VALUES (?)", "Ada")',
             'db.query("SELECT name FROM users") do |rs|\n  rs.each do\n    puts rs.read(String)\n  end\nend',
             'db.exec("DELETE FROM users WHERE name = ?", "Ada")',
         ]},
        {'slug': 'crystal-20-testing', 'title': 'Testing with Spec', 'desc': 'Unit and integration tests.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write specs', 'Use matchers', 'Run crystal spec', 'Test web endpoints'],
         'prereq': ['Crystal-19: Database Access'],
         'samples': [
             'require "spec"\n\ndescribe "math" do\n  it "adds" do\n    (2 + 2).should eq(4)\n  end\nend',
             'it "works with strings" do\n  "hello".should contain("ell")\nend',
             'crystal spec',
             'describe "counter" do\n  it "increments" do\n    c = Counter.new\n    c.increment!\n    c.count.should eq(1)\n  end\nend',
         ]},
        {'slug': 'crystal-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Shards, community, and production use.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use shards package manager', 'Discover popular shards', 'Build production services', 'Join the community'],
         'prereq': ['Crystal-20: Testing with Spec'],
         'samples': [
             'shards init my_app\nshards install',
             'dependencies:\n  kemal:\n    github: kemalcr/kemal',
             'shards search http',
             'puts "Crystal compiles to native binaries — great for CLIs"',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# D
# ────────────────────────────────────────────────────────────────────────────
D = {
    'lang': 'd',
    'code_lang': 'd',
    'refs': [
        ('D Language Reference', 'https://dlang.org/spec/spec.html', 'Official language spec'),
        ('D Programming Tour', 'https://tour.dlang.org/', 'Interactive language tour'),
        ('D Wiki', 'https://wiki.dlang.org/', 'Community wiki'),
        ('DUB Package Manager', 'https://code.dlang.org/', 'Package registry'),
    ],
    'lessons': [
        {'slug': 'd-01-getting-started', 'title': 'Getting Started with D', 'desc': 'Install DMD/LDC, compile, and run.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install a D compiler', 'Compile with dmd', 'Write hello world', 'Use rdmd for scripts'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'import std.stdio;\n\nvoid main() {\n    writeln("Hello, World!");\n}',
             'dmd hello.d -of=hello\n./hello',
             'import std.stdio;\n\nvoid main(string[] args) {\n    foreach (arg; args) {\n        writeln(arg);\n    }\n}',
             'import std.stdio;\n\nvoid main() {\n    write("no newline");\n    writeln(" with newline");\n}',
         ]},
        {'slug': 'd-02-types', 'title': 'Types and Variables', 'desc': 'Built-in types and declarations.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use integer types', 'Use floating point', 'Declare variables with auto', 'Use immutable and const'],
         'prereq': ['D-01: Getting Started with D'],
         'samples': [
             'import std.stdio;\n\nvoid main() {\n    int i = 10;\n    double d = 3.14;\n    string s = "D";\n    bool b = true;\n    writeln(i, " ", d, " ", s, " ", b);\n}',
             'auto x = 42;       // int\nauto y = 3.14;     // double\nwriteln(typeof(x), " ", typeof(y));',
             'immutable int MAX = 100;\nconst int MIN = 0;',
             'ulong big = 1_000_000_000_000;   // underscores for readability',
         ]},
        {'slug': 'd-03-operators', 'title': 'Operators and Expressions', 'desc': 'Arithmetic, bitwise, and ternary.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use arithmetic operators', 'Use bitwise operators', 'Use the ternary operator', 'Handle integer division'],
         'prereq': ['D-02: Types and Variables'],
         'samples': [
             'writeln(7 / 2);   // 3 — integer division\nwriteln(7.0 / 2); // 3.5',
             'writeln(0b1100 & 0b1010);  // 8\nwriteln(0b1100 | 0b1010);  // 14',
             'int a = 10;\nwriteln(a > 5 ? "big" : "small");',
             'writeln(2 ^^ 10);  // 1024 — power operator',
         ]},
        {'slug': 'd-04-strings', 'title': 'Strings', 'desc': 'UTF-8 strings and text processing.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Work with string literals', 'Concatenate strings', 'Format with format', 'Iterate characters'],
         'prereq': ['D-03: Operators and Expressions'],
         'samples': [
             'import std.stdio;\n\nvoid main() {\n    string a = "Hello";\n    string b = a ~ " World";\n    writeln(b);\n}',
             'import std.format;\nwriteln(format("%d + %d = %d", 2, 3, 5));',
             'import std.algorithm, std.array;\nauto upper = "hello".toUpper();\nwriteln(upper);',
             'foreach (c; "ABC") {\n    write(c, " ");\n}',
         ]},
        {'slug': 'd-05-arrays', 'title': 'Arrays and Slices', 'desc': 'Dynamic arrays and slice semantics.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create dynamic arrays', 'Slice arrays', 'Append elements', 'Iterate arrays'],
         'prereq': ['D-04: Strings'],
         'samples': [
             'import std.stdio;\n\nvoid main() {\n    int[] nums = [1, 2, 3];\n    nums ~= 4;\n    writeln(nums);\n}',
             'int[] a = [1, 2, 3, 4, 5];\nint[] b = a[1..3];\nwriteln(b);   // [2, 3]',
             'foreach (i, n; nums) {\n    writeln(i, ": ", n);\n}',
             'int[] arr = new int[100];\narr[] = 5;   // fill all',
         ]},
        {'slug': 'd-06-control-flow', 'title': 'Control Flow', 'desc': 'if, switch, and loops.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/else chains', 'Use switch statements', 'Use foreach loops', 'Use while loops'],
         'prereq': ['D-05: Arrays and Slices'],
         'samples': [
             'int score = 85;\nif (score >= 90) {\n    writeln("A");\n} else if (score >= 80) {\n    writeln("B");\n} else {\n    writeln("C");\n}',
             'switch (n) {\n    case 1: writeln("one"); break;\n    case 2: writeln("two"); break;\n    default: writeln("other");\n}',
             'foreach (i; 0..5) {\n    writeln(i);\n}',
             'int i = 0;\nwhile (i < 3) {\n    writeln(i);\n    i++;\n}',
         ]},
        {'slug': 'd-07-functions', 'title': 'Functions', 'desc': 'Write typed functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write functions', 'Use default parameters', 'Use overloads', 'Return tuples'],
         'prereq': ['D-06: Control Flow'],
         'samples': [
             'import std.stdio;\n\nint add(int a, int b) {\n    return a + b;\n}\n\nvoid main() {\n    writeln(add(2, 3));\n}',
             'string greet(string name, string title = "Mr") {\n    return title ~ " " ~ name;\n}\n\nwriteln(greet("Ada"));\nwriteln(greet("Ada", "Dr"));',
             'import std.typecons;\nauto divmod(int a, int b) {\n    return tuple(a / b, a % b);\n}\n\nauto r = divmod(7, 2);\nwriteln(r[0], " ", r[1]);',
             'int add(int a, int b) => a + b;  // short syntax',
         ]},
        {'slug': 'd-08-structs', 'title': 'Structs', 'desc': 'Value types and methods.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define structs', 'Add methods', 'Use constructors', 'Define operators'],
         'prereq': ['D-07: Functions'],
         'samples': [
             'import std.stdio;\n\nstruct Point {\n    int x, y;\n\n    this(int x, int y) {\n        this.x = x;\n        this.y = y;\n    }\n\n    int magnitude() {\n        return x * x + y * y;\n    }\n}\n\nvoid main() {\n    auto p = Point(3, 4);\n    writeln(p.magnitude());\n}',
             'struct Counter {\n    int count;\n\n    void increment() {\n        count++;\n    }\n}',
             'struct Vec2 {\n    float x, y;\n\n    Vec2 opBinary(string op)(Vec2 other) if (op == "+") {\n        return Vec2(x + other.x, y + other.y);\n    }\n}',
             'struct Temperature {\n    double celsius;\n    double fahrenheit() const {\n        return celsius * 9 / 5 + 32;\n    }\n}',
         ]},
        {'slug': 'd-09-classes', 'title': 'Classes and OOP', 'desc': 'Reference types with inheritance.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define classes', 'Use inheritance', 'Override methods', 'Use abstract classes'],
         'prereq': ['D-08: Structs'],
         'samples': [
             'import std.stdio;\n\nclass Animal {\n    string name;\n    this(string name) { this.name = name; }\n    void speak() { writeln("..."); }\n}\n\nclass Dog : Animal {\n    this(string name) { super(name); }\n    override void speak() { writeln("Woof"); }\n}\n\nvoid main() {\n    auto d = new Dog("Rex");\n    d.speak();\n}',
             'class Shape {\n    abstract double area();\n}\n\nclass Circle : Shape {\n    double radius;\n    override double area() { return 3.14159 * radius * radius; }\n}',
             'class Point {\n    private int x, y;\n\n    int getX() const { return x; }\n    void setX(int v) { x = v; }\n}',
             'class Singleton {\n    private static Singleton instance;\n    static Singleton getInstance() {\n        if (instance is null) instance = new Singleton();\n        return instance;\n    }\n}',
         ]},
        {'slug': 'd-10-interfaces', 'title': 'Interfaces', 'desc': 'Abstract contracts.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define interfaces', 'Implement interfaces', 'Use interface references', 'Compose behaviors'],
         'prereq': ['D-09: Classes and OOP'],
         'samples': [
             'import std.stdio;\n\ninterface Shape {\n    double area();\n}\n\nclass Square : Shape {\n    double side;\n    override double area() { return side * side; }\n}\n\nvoid main() {\n    Shape s = new Square();\n    writeln(s.area());\n}',
             'interface Logger {\n    void log(string msg);\n}\n\nclass ConsoleLogger : Logger {\n    override void log(string msg) { writeln(msg); }\n}',
             'interface Drawable { void draw(); }\ninterface Resizable { void resize(double f); }\n\nclass Widget : Drawable, Resizable {\n    override void draw() {}\n    override void resize(double f) {}\n}',
             'interface Comparable { int compare(Comparable other); }',
         ]},
        {'slug': 'd-11-exceptions', 'title': 'Exceptions', 'desc': 'Try, catch, and custom errors.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Throw exceptions', 'Catch exceptions', 'Use finally', 'Define custom exceptions'],
         'prereq': ['D-10: Interfaces'],
         'samples': [
             'import std.stdio;\n\nvoid main() {\n    try {\n        throw new Exception("boom");\n    } catch (Exception e) {\n        writeln(e.msg);\n    }\n}',
             'try {\n    risky();\n} catch (FileException e) {\n    writeln("file error");\n} catch (Exception e) {\n    writeln("other");\n}',
             'class MyError : Exception {\n    this(string msg) { super(msg); }\n}\n\nthrow new MyError("custom failure");',
             'try {\n    work();\n} finally {\n    cleanup();\n}',
         ]},
        {'slug': 'd-12-ranges', 'title': 'Ranges and Algorithms', 'desc': 'Lazy iteration and std.algorithm.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand range concept', 'Chain algorithms', 'Use filter and map', 'Build lazy pipelines'],
         'prereq': ['D-11: Exceptions'],
         'samples': [
             'import std.stdio;\nimport std.algorithm;\nimport std.range;\n\nvoid main() {\n    auto r = iota(1, 11).filter!(n => n % 2 == 0).map!(n => n * n);\n    writeln(r);\n}',
             'auto sum = iota(1, 101).sum;\nwriteln(sum);',
             'int[] arr = [3, 1, 4, 1, 5];\narr.sort();\nwriteln(arr);',
             'auto first3 = iota(1, 100).take(3);\nwriteln(first3);',
         ]},
        {'slug': 'd-13-generics', 'title': 'Templates and Generics', 'desc': 'Compile-time code reuse.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write template functions', 'Use template structs', 'Constrain with is', 'Use CTFE'],
         'prereq': ['D-12: Ranges and Algorithms'],
         'samples': [
             'import std.stdio;\n\nT identity(T)(T value) {\n    return value;\n}\n\nvoid main() {\n    writeln(identity(42));\n    writeln(identity("hi"));\n}',
             'struct Box(T) {\n    T value;\n}\n\nauto b = Box!int(42);\nwriteln(b.value);',
             'T maxOf(T)(T a, T b) if (is(typeof(a > b))) {\n    return a > b ? a : b;\n}',
             'enum square(int n) { return n * n; }   // compile-time\nwriteln(square(5));',
         ]},
        {'slug': 'd-14-concurrency', 'title': 'Concurrency', 'desc': 'Threads, messages, and shared data.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Spawn threads', 'Use synchronized', 'Pass messages', 'Use shared memory'],
         'prereq': ['D-13: Templates and Generics'],
         'samples': [
             'import std.stdio;\nimport core.thread;\n\nvoid work() {\n    writeln("in thread");\n}\n\nvoid main() {\n    auto t = new Thread(&work);\n    t.start();\n    t.join();\n}',
             'import std.concurrency;\n\nauto tid = spawn(() => 42);\nwriteln(receiveOnly!int);',
             'int counter;\nsynchronized void inc() {\n    counter++;\n}',
             'shared int x;\n// use with care — D keeps shared memory explicit',
         ]},
        {'slug': 'd-15-io', 'title': 'File and Stream IO', 'desc': 'Read and write files.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Read files', 'Write files', 'Read line by line', 'Handle binary data'],
         'prereq': ['D-14: Concurrency'],
         'samples': [
             'import std.stdio;\n\nvoid main() {\n    auto data = readText("data.txt");\n    writeln(data);\n}',
             'import std.file;\nwrite("out.txt", "hello");',
             'foreach (line; File("data.txt").byLine) {\n    writeln(line);\n}',
             'import std.stdio;\n\nauto f = File("out.txt", "w");\nf.writeln("line one");\nf.writeln("line two");\nf.close();',
         ]},
        {'slug': 'd-16-ufcs', 'title': 'UFCS and Function Composition', 'desc': 'Unified function call syntax.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use UFCS chains', 'Compose functions', 'Build readable pipelines', 'Extend built-in types'],
         'prereq': ['D-15: File and Stream IO'],
         'samples': [
             'import std.stdio;\nimport std.algorithm;\n\nvoid main() {\n    "hello".toUpper().writeln;\n}',
             'auto result = [1, 2, 3, 4]\n    .map!(n => n * 2)\n    .filter!(n => n > 3)\n    .array;\nwriteln(result);',
             'string shout(string s) { return s.toUpper() ~ "!"; }\nwriteln("hi".shout);',
             'auto words = "a b c".split;\nwriteln(words.length);',
         ]},
        {'slug': 'd-17-mixins', 'title': 'Mixins and Code Generation', 'desc': 'Compile-time string mixins.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use string mixins', 'Generate code with CTFE', 'Use template mixins', 'Build DSLs'],
         'prereq': ['D-16: UFCS and Function Composition'],
         'samples': [
             'import std.stdio;\n\nvoid main() {\n    mixin("writeln(\\"from mixin\\");");\n}',
             'enum code = "int x = 42;";\nmixin(code);\nwriteln(x);',
             'template mixin Example(T) {\n    mixin("T " ~ T.stringof ~ "Field;");\n}\n\nstruct S { mixin Example!int; }',
             'string gen(string name) {\n    return "int " ~ name ~ " = 0;";\n}\nmixin(gen("counter"));',
         ]},
        {'slug': 'd-18-testing', 'title': 'Unit Testing with unittest', 'desc': 'Embedded tests in D code.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write unittest blocks', 'Use assert in tests', 'Run with -unittest', 'Test templates'],
         'prereq': ['D-17: Mixins and Code Generation'],
         'samples': [
             'import std.stdio;\n\nint add(int a, int b) {\n    return a + b;\n}\n\nunittest {\n    assert(add(2, 3) == 5);\n}\n\nvoid main() {}',
             'dmd -unittest -main app.d -of=test && ./test',
             'unittest {\n    assert([1, 2, 3].sum == 6);\n    assert("abc".length == 3);\n}',
             'T square(T)(T x) { return x * x; }\n\nunittest {\n    assert(square(4) == 16);\n    assert(square(2.5) == 6.25);\n}',
         ]},
        {'slug': 'd-19-dub', 'title': 'DUB and Packaging', 'desc': 'Package management and builds.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Create a DUB project', 'Add dependencies', 'Build and run', 'Publish packages'],
         'prereq': ['D-18: Unit Testing with unittest'],
         'samples': [
             'dub init myapp\ncd myapp && dub run',
             '{\n  "name": "myapp",\n  "dependencies": {\n    "vibe-d": "~>0.9"\n  }\n}',
             'dub add deimos-openssl\n// or edit dub.json',
             'dub build -b release',
         ]},
        {'slug': 'd-20-web', 'title': 'Web Development with vibe.d', 'desc': 'Async HTTP servers.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create a vibe.d server', 'Define REST routes', 'Serve JSON', 'Handle requests'],
         'prereq': ['D-19: DUB and Packaging'],
         'samples': [
             'import vibe.d;\n\nvoid main() {\n    auto settings = new HTTPServerSettings;\n    settings.port = 8080;\n    listenHTTP(settings, &requestHandler);\n    runEventLoop();\n}\n\nvoid requestHandler(HTTPServerRequest req, HTTPServerResponse res) {\n    res.writeBody("Hello, World!");\n}',
             'router.get("/hello/:name", (req, res) {\n    res.writeBody("Hello, " ~ req.params["name"]);\n});',
             'import std.json;\nres.writeBody(JSONValue(["name": "Ada", "age": 36]).toJSON());',
             'router.post("/api/user", (req, res) {\n    auto body = req.bodyReader.readAll().toUTF8;\n    res.writeBody(body);\n});',
         ]},
        {'slug': 'd-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Libraries and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Discover D libraries', 'Understand D in systems programming', 'Use D for CLIs', 'Join the community'],
         'prereq': ['D-20: Web Development with vibe.d'],
         'samples': [
             'dub search json',
             'import std.getopt;\n\nstring file;\nbool verbose;\n\nvoid main(string[] args) {\n    getopt(args, "file", &file, "verbose", &verbose);\n}',
             'import std.process;\nwriteln(executeShell("ls -la"));',
             'writeln("D compiles to fast native code — great for tools");',
         ]},
    ],
}

SPECS = [SOLIDITY, NIM, CRYSTAL, D]
