#!/usr/bin/env python3
"""Lesson specs for assembly, autohotkey, common-lisp, gdscript — real 21-lesson courses."""

# ────────────────────────────────────────────────────────────────────────────
# ASSEMBLY (x86-64, NASM)
# ────────────────────────────────────────────────────────────────────────────
ASSEMBLY = {
    'lang': 'assembly',
    'code_lang': 'nasm',
    'refs': [
        ('NASM Documentation', 'https://www.nasm.us/doc/', 'Official NASM manual'),
        ('x86-64 Assembly Reference', 'https://www.felixcloutier.com/x86/', 'Complete instruction set reference'),
        ('Programming from the Ground Up', 'https://download-mirror.savannah.gnu.org/releases/pgubook/', 'Classic introduction'),
    ],
    'lessons': [
        {'slug': 'assembly-01-getting-started', 'title': 'Getting Started with Assembly', 'desc': 'Registers, syscalls, and hello world in NASM.', 'dur': '60 min', 'diff': 'beginner',
         'objs': ['Understand CPU registers', 'Write a hello world syscall', 'Assemble with nasm', 'Link with ld'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'section .data\n    msg db "Hello, World!", 0xa\n    len equ $ - msg\n\nsection .text\n    global _start\n\n_start:\n    mov rax, 1          ; write syscall\n    mov rdi, 1          ; stdout\n    mov rsi, msg\n    mov rdx, len\n    syscall\n\n    mov rax, 60         ; exit syscall\n    xor rdi, rdi\n    syscall',
             'nasm -f elf64 hello.asm\nld -o hello hello.o\n./hello',
             'section .data\n    msg db "Assembly!", 0xa\n    len equ $ - msg',
             'section .text\n    global _start\n_start:\n    mov rax, 60\n    mov rdi, 0\n    syscall',
         ]},
        {'slug': 'assembly-02-registers', 'title': 'Registers and Data Sizes', 'desc': 'General-purpose, sizes, and moves.', 'dur': '60 min', 'diff': 'beginner',
         'objs': ['Name the general-purpose registers', 'Use 8/16/32/64-bit registers', 'Use mov variants', 'Understand zero/sign extension'],
         'prereq': ['Assembly-01: Getting Started with Assembly'],
         'samples': [
             'mov rax, 10      ; 64-bit\nmov eax, 10      ; 32-bit (zero-extends)\nmov ax, 10       ; 16-bit\nmov al, 10       ; 8-bit',
             'mov rax, rbx    ; register to register',
             'mov rbx, 0      ; clear\nmov rcx, -1     ; all ones',
             'movzx eax, al   ; zero extend\nmovsx rax, eax  ; sign extend',
         ]},
        {'slug': 'assembly-03-memory', 'title': 'Memory Addressing', 'desc': 'Effective addresses and addressing modes.', 'dur': '60 min', 'diff': 'beginner',
         'objs': ['Load from memory', 'Store to memory', 'Use base+index addressing', 'Use displacement'],
         'prereq': ['Assembly-02: Registers and Data Sizes'],
         'samples': [
             'section .data\n    value dq 42\n\nsection .text\n    mov rax, [value]   ; load',
             'section .bss\n    buffer resb 64\n\nsection .text\n    mov byte [buffer], 65',
             'mov rax, [rbx + 8]       ; base + displacement\nmov rax, [rbx + rcx*4]    ; base + index*scale',
             'mov [rsp + 16], rax      ; stack access',
         ]},
        {'slug': 'assembly-04-arithmetic', 'title': 'Arithmetic Instructions', 'desc': 'add, sub, imul, and idiv.', 'dur': '60 min', 'diff': 'beginner',
         'objs': ['Add and subtract', 'Multiply with imul', 'Divide with idiv', 'Use inc and dec'],
         'prereq': ['Assembly-03: Memory Addressing'],
         'samples': [
             'add rax, 5\nsub rax, 3',
             'mov rax, 6\nmov rbx, 7\nimul rax, rbx      ; rax = 42',
             'mov rax, 42\nmov rbx, 6\nxor rdx, rdx\nidiv rbx          ; rax = 7, rdx = 0',
             'inc rax\ndec rbx',
         ]},
        {'slug': 'assembly-05-logical', 'title': 'Logical and Bit Operations', 'desc': 'and, or, xor, shifts.', 'dur': '60 min', 'diff': 'beginner',
         'objs': ['Use and/or/xor', 'Shift left and right', 'Test bits', 'Use not'],
         'prereq': ['Assembly-04: Arithmetic Instructions'],
         'samples': [
             'and rax, rbx\nor rax, rbx\nxor rax, rbx',
             'shl rax, 2      ; multiply by 4\nshr rax, 1      ; divide by 2',
             'test rax, 1\njz even        ; jump if zero',
             'mov rax, 0b1010\nand rax, 0b1100  ; rax = 0b1000',
         ]},
        {'slug': 'assembly-06-control-flow', 'title': 'Control Flow', 'desc': 'cmp, jumps, and loops.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Compare values with cmp', 'Use conditional jumps', 'Build if/else', 'Write loops'],
         'prereq': ['Assembly-05: Logical and Bit Operations'],
         'samples': [
             'cmp rax, rbx\nje equal\njg greater\njl less',
             'mov rax, 10\ncmp rax, 5\njge at_least_five\n    ; else path\nat_least_five:',
             'mov rcx, 5\nloop_start:\n    ; body\n    dec rcx\n    jnz loop_start',
             'cmp rax, 0\njne not_zero\n    ; zero path\nnot_zero:',
         ]},
        {'slug': 'assembly-07-stack', 'title': 'The Stack', 'desc': 'push, pop, and calling conventions.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Push and pop', 'Understand stack growth', 'Save and restore registers', 'Use the frame pointer'],
         'prereq': ['Assembly-06: Control Flow'],
         'samples': [
             'push rax\n; ... work ...\npop rax',
             'push rbx\npush rcx\n; ...\npop rcx\npop rbx',
             'call func\n; returns here\n\nfunc:\n    push rbp\n    mov rbp, rsp\n    ; ...\n    pop rbp\n    ret',
             'sub rsp, 32   ; reserve 32 bytes\n; ...\nadd rsp, 32',
         ]},
        {'slug': 'assembly-08-call-convention', 'title': 'SysV Calling Convention', 'desc': 'Function arguments and System V ABI.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Pass args in rdi/rsi/rdx', 'Return in rax', 'Align the stack', 'Call C functions'],
         'prereq': ['Assembly-07: The Stack'],
         'samples': [
             '; int add(int a, int b)\nadd:\n    mov rax, rdi\n    add rax, rsi\n    ret',
             'global add\nadd:\n    lea rax, [rdi + rsi]\n    ret',
             '; call printf\nmov rdi, fmt\nmov rsi, 42\nxor eax, eax\ncall printf',
             'extern printf\n\nsection .data\n    fmt db "val: %d", 0xa, 0',
         ]},
        {'slug': 'assembly-09-data-directives', 'title': 'Data Directives', 'desc': 'db, dw, dd, dq, resb, equ.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Declare data with directives', 'Use resb for BSS', 'Use equ constants', 'Build arrays'],
         'prereq': ['Assembly-08: SysV Calling Convention'],
         'samples': [
             'section .data\n    b db 1       ; byte\n    w dw 2       ; word\n    d dd 3       ; dword\n    q dq 4       ; qword',
             'section .bss\n    buffer resb 256\n    array resq 10',
             'section .data\n    SIZE equ 100\n    buf times SIZE db 0',
             'section .data\n    arr dd 1, 2, 3, 4, 5\n    arr_len equ ($ - arr) / 4',
         ]},
        {'slug': 'assembly-10-strings', 'title': 'String Operations', 'desc': 'String instructions and length.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Compute string length', 'Use rep movsb', 'Use cld/std', 'Compare strings'],
         'prereq': ['Assembly-09: Data Directives'],
         'samples': [
             'strlen:\n    xor rax, rax\n.loop:\n    cmp byte [rdi + rax], 0\n    je .done\n    inc rax\n    jmp .loop\n.done:\n    ret',
             'cld\nmov rsi, src\nmov rdi, dst\nmov rcx, len\nrep movsb',
             'mov al, byte [rdi]\ninc rdi',
             'cld\nmov rsi, s1\nmov rdi, s2\nmov rcx, len\nrepe cmpsb\nje strings_equal',
         ]},
        {'slug': 'assembly-11-arrays', 'title': 'Arrays and Indexing', 'desc': 'Index arithmetic and iteration.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Index arrays', 'Iterate with pointers', 'Compute element offsets', 'Sum an array'],
         'prereq': ['Assembly-10: String Operations'],
         'samples': [
             'section .data\n    arr dq 10, 20, 30, 40\n\n; load arr[2]\nmov rbx, arr\nmov rax, [rbx + 2*8]',
             'xor rax, rax\nxor rcx, rcx\n.loop:\n    add rax, [rbx + rcx*8]\n    inc rcx\n    cmp rcx, 4\n    jl .loop',
             'lea rbx, [arr]\nmov rax, [rbx]     ; first element\nadd rbx, 8          ; advance',
             'mov rdx, 8\nimul rdx, rcx       ; offset = index * 8\nmov rax, [rbx + rdx]',
         ]},
        {'slug': 'assembly-12-io', 'title': 'Input/Output', 'desc': 'Read and write with syscalls.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Write to stdout', 'Read from stdin', 'Handle buffer sizes', 'Convert integers to text'],
         'prereq': ['Assembly-11: Arrays and Indexing'],
         'samples': [
             'mov rax, 1      ; write\nmov rdi, 1      ; stdout\nmov rsi, msg\nmov rdx, len\nsyscall',
             'mov rax, 0      ; read\nmov rdi, 0      ; stdin\nmov rsi, buffer\nmov rdx, 255\nsyscall',
             'section .bss\n    buffer resb 256',
             '; print integer in rax\n; (manual conversion to decimal string)',
         ]},
        {'slug': 'assembly-13-fpu', 'title': 'Floating Point', 'desc': 'SSE and scalar float ops.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Use xmm registers', 'Add and multiply floats', 'Convert int to float', 'Use divss'],
         'prereq': ['Assembly-12: Input/Output'],
         'samples': [
             'movss xmm0, [val]\nmovss xmm1, [val2]\naddss xmm0, xmm1',
             'mulss xmm0, xmm0    ; square',
             'cvtsi2ss xmm0, eax  ; int -> float',
             'divss xmm0, xmm1    ; float divide',
         ]},
        {'slug': 'assembly-14-interrupts', 'title': 'Syscalls and Interrupts', 'desc': 'Linux syscall interface.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Understand syscall numbers', 'Use rax for syscall number', 'Use syscall instruction', 'Map common syscalls'],
         'prereq': ['Assembly-13: Floating Point'],
         'samples': [
             '; exit\nmov rax, 60\nmov rdi, 0\nsyscall',
             '; write\nmov rax, 1\nmov rdi, 1\nmov rsi, msg\nmov rdx, len\nsyscall',
             '; read\nmov rax, 0\nmov rdi, 0\nmov rsi, buf\nmov rdx, 100\nsyscall',
             '; open\nmov rax, 2\nmov rdi, path\nmov rsi, 0\nsyscall',
         ]},
        {'slug': 'assembly-15-files', 'title': 'File Operations', 'desc': 'Open, read, write, close files.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Open files with syscalls', 'Read file contents', 'Write to files', 'Close descriptors'],
         'prereq': ['Assembly-14: Syscalls and Interrupts'],
         'samples': [
             '; open("data.txt", O_RDONLY)\nmov rax, 2\nlea rdi, [path]\nmov rsi, 0\nsyscall\nmov r12, rax    ; fd',
             '; read(fd, buf, 100)\nmov rax, 0\nmov rdi, r12\nlea rsi, [buf]\nmov rdx, 100\nsyscall',
             '; write(fd, msg, len)\nmov rax, 1\nmov rdi, r12\nlea rsi, [msg]\nmov rdx, len\nsyscall',
             '; close(fd)\nmov rax, 3\nmov rdi, r12\nsyscall',
         ]},
        {'slug': 'assembly-16-bit-manipulation', 'title': 'Bit Manipulation', 'desc': 'popcnt, bsf, and efficient tricks.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Count set bits', 'Find lowest set bit', 'Use bts/btr', 'Optimize with bit tricks'],
         'prereq': ['Assembly-15: File Operations'],
         'samples': [
             'popcnt rax, rax    ; count 1 bits',
             'bsf rax, rbx       ; lowest set bit index\njnz found',
             'bts rax, 3         ; set bit 3\nbtr rax, 3         ; reset bit 3',
             'xor eax, eax       ; fast zero (better than mov)',
         ]},
        {'slug': 'assembly-17-debugging', 'title': 'Debugging Assembly', 'desc': 'GDB, breakpoints, and single-stepping.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Run under GDB', 'Set breakpoints', 'Inspect registers', 'Single-step'],
         'prereq': ['Assembly-16: Bit Manipulation'],
         'samples': [
             'gdb ./program\nbreak _start\nrun\ninfo registers',
             'x/10gx &arr   ; examine memory',
             'si           ; step one instruction',
             'print $rax   ; inspect register',
         ]},
        {'slug': 'assembly-18-performance', 'title': 'Performance Optimization', 'desc': 'Pipeline, alignment, and SIMD.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Avoid stalls', 'Align hot loops', 'Use SIMD instructions', 'Reduce dependencies'],
         'prereq': ['Assembly-17: Debugging Assembly'],
         'samples': [
             'align 16\n.loop:\n    ; hot loop body',
             'movdqu xmm0, [rax]\nmovdqu xmm1, [rbx]\npaddd xmm0, xmm1\nmovdqu [rcx], xmm0',
             'pxor xmm0, xmm0   ; zero without dependency',
             '; unroll loops to reduce branch overhead',
         ]},
        {'slug': 'assembly-19-c-interop', 'title': 'Interfacing with C', 'desc': 'Call C from assembly and vice versa.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Export functions to C', 'Call libc from asm', 'Use C structs', 'Link with gcc'],
         'prereq': ['Assembly-18: Performance Optimization'],
         'samples': [
             'global my_add\nmy_add:\n    mov rax, rdi\n    add rax, rsi\n    ret\n\n; C: extern int my_add(int, int);',
             '; assemble with gcc\ngcc -c my_add.asm -o my_add.o\ngcc main.c my_add.o -o app',
             'extern strlen\nmov rdi, msg\ncall strlen',
             '; struct access: first field at [rdi], second at [rdi+8]',
         ]},
        {'slug': 'assembly-20-shellcode', 'title': 'Shellcode Basics', 'desc': 'Position-independent code.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write position-independent code', 'Avoid null bytes', 'Extract shellcode bytes', 'Understand exploitation context'],
         'prereq': ['Assembly-19: Interfacing with C'],
         'samples': [
             'xor rax, rax\nmov al, 60\nxor rdi, rdi\nsyscall',
             '; avoid absolute addresses — use RIP-relative\nlea rsi, [rel msg]',
             '; objcopy -O binary --only-section=.text in.o out.bin',
             '; use push to build values without null bytes',
         ]},
        {'slug': 'assembly-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'NASM vs GAS, ARM, and tools.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Understand NASM vs GAS syntax', 'Compare x86 vs ARM', 'Use objdump', 'Find further resources'],
         'prereq': ['Assembly-20: Shellcode Basics'],
         'samples': [
             'objdump -d ./program | head -30',
             'gcc -S -masm=intel source.c   # view generated asm',
             '; ARM uses different register names: r0-r12, sp, lr',
             '; tools: gdb, objdump, radare2, Ghidra',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# AUTOHOTKEY
# ────────────────────────────────────────────────────────────────────────────
AUTOHOTKEY = {
    'lang': 'autohotkey',
    'code_lang': 'autohotkey',
    'refs': [
        ('AutoHotkey Documentation', 'https://www.autohotkey.com/docs/', 'Official docs'),
        ('AutoHotkey v2 Changes', 'https://www.autohotkey.com/docs/v2/', 'Version 2 documentation'),
        ('AutoHotkey Forum', 'https://www.autohotkey.com/boards/', 'Community forum'),
    ],
    'lessons': [
        {'slug': 'autohotkey-01-getting-started', 'title': 'Getting Started with AutoHotkey', 'desc': 'Install, hotkeys, and scripts.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install AutoHotkey', 'Write a first script', 'Use hotkeys', 'Run scripts'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '^j::\n{\n    MsgBox "Hello, World!"\n}',
             '#n::\n{\n    Run "notepad.exe"\n}',
             '^!t::\n{\n    MsgBox "Ctrl+Alt+T pressed"\n}',
             'F2::Send "Hello{Enter}"',
         ]},
        {'slug': 'autohotkey-02-hotkeys', 'title': 'Hotkeys and Hotstrings', 'desc': 'Modifiers, triggers, and expansions.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use modifier keys', 'Define hotstrings', 'Send keystrokes', 'Use remapping'],
         'prereq': ['AutoHotkey-01: Getting Started with AutoHotkey'],
         'samples': [
             '^s::Send "^s"   ; pass through',
             '::btw::by the way',
             '!f::Send "file"',
             'CapsLock::Ctrl     ; remap key',
         ]},
        {'slug': 'autohotkey-03-variables', 'title': 'Variables and Expressions', 'desc': 'Store and manipulate data.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare variables', 'Concatenate strings', 'Do arithmetic', 'Use ternary'],
         'prereq': ['AutoHotkey-02: Hotkeys and Hotstrings'],
         'samples': [
             'name := "Ada"\nage := 36\nMsgBox "Hello, " name',
             'x := 5\ny := 10\nMsgBox x + y',
             'greeting := "Hello" . " " . "World"',
             'result := (x > 5) ? "big" : "small"',
         ]},
        {'slug': 'autohotkey-04-control-flow', 'title': 'Control Flow', 'desc': 'if, else, switch.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use if/else', 'Use switch', 'Compare values', 'Check conditions'],
         'prereq': ['AutoHotkey-03: Variables and Expressions'],
         'samples': [
             'score := 85\nif (score >= 90)\n    MsgBox "A"\nelse if (score >= 80)\n    MsgBox "B"\nelse\n    MsgBox "C"',
             'x := 2\nswitch x\n{\n    case 1: MsgBox "one"\n    case 2: MsgBox "two"\n    default: MsgBox "other"\n}',
             'if WinExist("Untitled - Notepad")\n    MsgBox "Notepad is open"',
             'if (FileExist("data.txt"))\n    MsgBox "File exists"',
         ]},
        {'slug': 'autohotkey-05-loops', 'title': 'Loops', 'desc': 'Iteration and repetition.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use Loop count', 'Use While', 'Use For over objects', 'Break and continue'],
         'prereq': ['AutoHotkey-04: Control Flow'],
         'samples': [
             'Loop 5\n{\n    MsgBox "Iteration " A_Index\n}',
             'i := 0\nwhile (i < 5)\n{\n    i++\n    MsgBox i\n}',
             'for fruit in ["apple", "banana"]\n    MsgBox fruit',
             'Loop 10\n{\n    if (A_Index = 5)\n        break\n    if (A_Index = 3)\n        continue\n}',
         ]},
        {'slug': 'autohotkey-06-functions', 'title': 'Functions', 'desc': 'Define and call functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define functions', 'Pass parameters', 'Return values', 'Use defaults'],
         'prereq': ['AutoHotkey-05: Loops'],
         'samples': [
             'Add(a, b)\n{\n    return a + b\n}\n\nMsgBox Add(2, 3)',
             'Greet(name, excited := false)\n{\n    return excited ? "HI " name : "hi " name\n}',
             'IsEven(n)\n{\n    return Mod(n, 2) = 0\n}',
             'GetConfig(key, def := "")\n{\n    return IniRead("config.ini", "main", key, def)\n}',
         ]},
        {'slug': 'autohotkey-07-windows', 'title': 'Window Management', 'desc': 'Activate, close, and manipulate windows.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Activate windows', 'Close windows', 'Move and resize', 'Wait for windows'],
         'prereq': ['AutoHotkey-06: Functions'],
         'samples': [
             'WinActivate "Untitled - Notepad"',
             'WinClose "Untitled - Notepad"',
             'WinMove 100, 100, 800, 600, "Untitled"',
             'WinWait "Notepad"\nWinActivate',
         ]},
        {'slug': 'autohotkey-08-send', 'title': 'Sending Keystrokes', 'desc': 'Send commands and input modes.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Send text', 'Send key combos', 'Use SendInput', 'Use special keys'],
         'prereq': ['AutoHotkey-07: Window Management'],
         'samples': [
             'Send "Hello, World!"',
             'Send "^c"        ; copy\nSend "^v"        ; paste',
             'SendInput "fast typing{Enter}"',
             'Send "{Enter}{Tab}{Shift down}{Shift up}"',
         ]},
        {'slug': 'autohotkey-09-clipboard', 'title': 'Clipboard Manipulation', 'desc': 'Read, write, and transform clipboard.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Read clipboard', 'Write clipboard', 'Transform text', 'Use clipboard history'],
         'prereq': ['AutoHotkey-08: Sending Keystrokes'],
         'samples': [
             '^c\nSleep 50\nMsgBox A_Clipboard',
             'A_Clipboard := "new content"',
             '^c\nSleep 50\nA_Clipboard := StrReplace(A_Clipboard, "old", "new")',
             'A_Clipboard := FormatTime(, "yyyy-MM-dd")',
         ]},
        {'slug': 'autohotkey-10-files', 'title': 'File Operations', 'desc': 'Read, write, and manage files.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Read files', 'Write files', 'List files', 'Check existence'],
         'prereq': ['AutoHotkey-09: Clipboard Manipulation'],
         'samples': [
             'content := FileRead("data.txt")\nMsgBox content',
             'FileAppend "new line`n", "log.txt"',
             'Loop Files "*.txt"\n    MsgBox A_LoopFileName',
             'if (FileExist("config.ini"))\n    MsgBox "exists"',
         ]},
        {'slug': 'autohotkey-11-gui', 'title': 'GUIs', 'desc': 'Build simple interfaces.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Create a GUI', 'Add controls', 'Handle events', 'Show dialogs'],
         'prereq': ['AutoHotkey-10: File Operations'],
         'samples': [
             'myGui := Gui()\nmyGui.Add("Text", , "Hello!")\nmyGui.Show()',
             'myGui := Gui()\nmyGui.Add("Edit", "vInput w200")\nmyGui.Add("Button", "gSubmit", "OK")\nmyGui.Show()\n\nSubmit(*)\n{\n    saved := myGui.Submit()\n    MsgBox saved.Input\n}',
             'MsgBox "Simple dialog"',
             'result := MsgBox("Continue?", "Question", "YesNo")\nif (result = "Yes")\n    MsgBox "Continuing"',
         ]},
        {'slug': 'autohotkey-12-arrays-objects', 'title': 'Arrays and Objects', 'desc': 'Collections in v2.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create arrays', 'Access elements', 'Use maps', 'Iterate objects'],
         'prereq': ['AutoHotkey-11: GUIs'],
         'samples': [
             'colors := ["red", "green", "blue"]\nMsgBox colors[1]',
             'colors.Push("yellow")\nMsgBox colors.Length',
             'person := Map("name", "Ada", "age", 36)\nMsgBox person["name"]',
             'for key, value in person\n    MsgBox key ": " value',
         ]},
        {'slug': 'autohotkey-13-string-functions', 'title': 'String Functions', 'desc': 'Manipulate and transform text.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use StrSplit', 'Use StrReplace', 'Use SubStr', 'Use RegExMatch'],
         'prereq': ['AutoHotkey-12: Arrays and Objects'],
         'samples': [
             'parts := StrSplit("a,b,c", ",")\nMsgBox parts[2]',
             'MsgBox StrReplace("hello world", "o", "0")',
             'MsgBox SubStr("Hello", 2, 3)',
             'match := RegExMatch("hello 123", "\\d+", &found)\nif (match)\n    MsgBox found[]',
         ]},
        {'slug': 'autohotkey-14-timers', 'title': 'Timers', 'desc': 'Scheduled actions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Set timers', 'Repeat actions', 'Cancel timers', 'Use SetTimer'],
         'prereq': ['AutoHotkey-13: String Functions'],
         'samples': [
             'SetTimer Check, 5000\n\nCheck()\n{\n    MsgBox "5 seconds passed"\n}',
             'SetTimer Flash, 1000\n\nFlash()\n{\n    MsgBox "tick"\n}',
             'SetTimer Check, 0   ; disable',
             'SetTimer () => MsgBox "periodic", 3000',
         ]},
        {'slug': 'autohotkey-15-hotkeys-advanced', 'title': 'Advanced Hotkeys', 'desc': 'Context-sensitive hotkeys and modes.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use #IfWinActive', 'Create mode toggles', 'Use key-up triggers', 'Chain hotkeys'],
         'prereq': ['AutoHotkey-14: Timers'],
         'samples': [
             '#HotIf WinActive("ahk_class Notepad")\n^d::MsgBox "in notepad"\n#HotIf',
             'capsToggled := false\nCapsLock::\n{\n    capsToggled := !capsToggled\n    if (capsToggled)\n        MsgBox "mode on"\n    else\n        MsgBox "mode off"\n}',
             'a & b::MsgBox "a then b"',
             '^!+s::MsgBox "Ctrl+Alt+Shift+S"',
         ]},
        {'slug': 'autohotkey-16-imagesearch', 'title': 'Image and Pixel Search', 'desc': 'Find on-screen images and colors.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use ImageSearch', 'Use PixelSearch', 'Click found locations', 'Build automation loops'],
         'prereq': ['AutoHotkey-15: Advanced Hotkeys'],
         'samples': [
             'ImageSearch &x, &y, 0, 0, A_ScreenWidth, A_ScreenHeight, "button.png"\nif (ErrorLevel = 0)\n    Click x, y',
             'PixelSearch &px, &py, 0, 0, 100, 100, 0xFF0000\nif (ErrorLevel = 0)\n    MsgBox "found red at " px "," py',
             'loop\n{\n    ImageSearch &x, &y, 0, 0, 1000, 800, "target.png"\n    if (ErrorLevel = 0)\n        break\n    Sleep 200\n}',
             'CoordMode "Mouse", "Screen"',
         ]},
        {'slug': 'autohotkey-17-json-ini', 'title': 'Configuration and JSON', 'desc': 'Persist settings.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Read/write INI files', 'Parse JSON', 'Save settings', 'Use registry'],
         'prereq': ['AutoHotkey-16: Image and Pixel Search'],
         'samples': [
             'IniWrite "value", "config.ini", "section", "key"\nvalue := IniRead("config.ini", "section", "key")',
             'import json\n\n; via external JSON lib\nparsed := JSON.parse(text)',
             'RegWrite "value", "REG_SZ", "HKCU\\Software\\MyApp", "Setting"\nval := RegRead("HKCU\\Software\\MyApp", "Setting")',
             'A_WorkingDir := "C:\\Users\\me"',
         ]},
        {'slug': 'autohotkey-18-error-handling', 'title': 'Error Handling', 'desc': 'Try, catch, and validation.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use try/catch', 'Throw errors', 'Check ErrorLevel', 'Validate inputs'],
         'prereq': ['AutoHotkey-17: Configuration and JSON'],
         'samples': [
             'try\n{\n    value := FileRead("missing.txt")\n}\ncatch Error as e\n{\n    MsgBox "Error: " e.Message\n}',
             'throw ValueError("Bad input")',
             'FileRead "data.txt"\nif (ErrorLevel)\n    MsgBox "read failed"',
             'if not IsNumber(input)\n    MsgBox "not a number"',
         ]},
        {'slug': 'autohotkey-19-running-programs', 'title': 'Running Programs', 'desc': 'Launch apps and control processes.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Run programs', 'Run with args', 'Check processes', 'Wait for processes'],
         'prereq': ['AutoHotkey-18: Error Handling'],
         'samples': [
             'Run "notepad.exe"',
             'Run "python.exe script.py arg1"',
             'if ProcessExist("notepad.exe")\n    MsgBox "running"',
             'RunWait "cmd.exe /c dir > out.txt"',
         ]},
        {'slug': 'autohotkey-20-ahk2', 'title': 'AutoHotkey v2 Best Practices', 'desc': 'Modern idioms and structure.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Structure scripts well', 'Use classes', 'Write clean v2 code', 'Use Strict mode'],
         'prereq': ['AutoHotkey-19: Running Programs'],
         'samples': [
             'class Calculator\n{\n    static Add(a, b) => a + b\n}\n\nMsgBox Calculator.Add(2, 3)',
             '#Requires AutoHotkey v2.0',
             'MyApp()\n{\n    ; main entry\n}\n\nMyApp()',
             'const APP_NAME := "My Tool"\n#Requires AutoHotkey v2.0',
         ]},
        {'slug': 'autohotkey-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Libraries and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Find community libraries', 'Use the package ecosystem', 'Automate workflows', 'Learn from examples'],
         'prereq': ['AutoHotkey-20: AutoHotkey v2 Best Practices'],
         'samples': [
             '; check autohotkey.com/boards for libraries',
             'Include "lib\\my_lib.ahk"',
             'Run "https://www.autohotkey.com/docs/"',
             '; community: discord, reddit r/AutoHotkey',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# COMMON LISP
# ────────────────────────────────────────────────────────────────────────────
COMMON_LISP = {
    'lang': 'common-lisp',
    'code_lang': 'lisp',
    'refs': [
        ('Practical Common Lisp', 'https://gigamonkeys.com/book/', 'The classic online book'),
        ('Common Lisp HyperSpec', 'http://www.lispworks.com/documentation/HyperSpec/Front/Contents.htm', 'Official standard reference'),
        ('Common Lisp Cookbook', 'https://lispcookbook.github.io/cl-cookbook/', 'Community cookbook'),
    ],
    'lessons': [
        {'slug': 'common-lisp-01-getting-started', 'title': 'Getting Started with Common Lisp', 'desc': 'SBCL, REPL, and hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install SBCL', 'Use the REPL', 'Evaluate expressions', 'Write a first file'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '(format t "Hello, World!~%")',
             'sbcl\n* (+ 1 2)\n3',
             '(defun hello () (format t "Hello!~%"))\n(hello)',
             '(format t "Hello, ~a!~%" "Ada")',
         ]},
        {'slug': 'common-lisp-02-forms', 'title': 'S-expressions and Forms', 'desc': 'Parentheses, symbols, and evaluation.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Understand S-expressions', 'Quote data with quote', 'Distinguish code and data', 'Use symbols'],
         'prereq': ['Common Lisp-01: Getting Started with Common Lisp'],
         'samples': [
             '(+ 1 2)       ; 3\n(- 10 4)      ; 6\n(* 3 4)        ; 12',
             "'(a b c)      ; quoted list",
             "'symbol       ; the symbol itself",
             '(list 1 2 3)  ; (1 2 3)',
         ]},
        {'slug': 'common-lisp-03-variables', 'title': 'Variables and Bindings', 'desc': 'defvar, let, and scope.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Define global variables', 'Bind with let', 'Use setf to mutate', 'Understand dynamic scope'],
         'prereq': ['Common Lisp-02: S-expressions and Forms'],
         'samples': [
             '(defvar *name* "Ada")\n*name*',
             '(let ((x 10) (y 20)) (+ x y))',
             '(defvar *count* 0)\n(setf *count* (+ *count* 1))',
             '(let ((x 5))\n  (setf x 10)\n  x)',
         ]},
        {'slug': 'common-lisp-04-functions', 'title': 'Functions', 'desc': 'defun, lambdas, and higher-order.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Define functions with defun', 'Write lambdas', 'Pass functions', 'Use apply and funcall'],
         'prereq': ['Common Lisp-03: Variables and Bindings'],
         'samples': [
             '(defun square (x) (* x x))\n(square 5)',
             '(mapcar (lambda (x) (* x 2)) \'(1 2 3))',
             '(funcall #\'square 4)\n(apply #\'+ \'(1 2 3))',
             '(defun add (a b) (+ a b))',
         ]},
        {'slug': 'common-lisp-05-cons', 'title': 'Cons Cells and Lists', 'desc': 'The building blocks of Lisp data.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Build cons cells', 'Use car and cdr', 'Build lists', 'Destructure lists'],
         'prereq': ['Common Lisp-04: Functions'],
         'samples': [
             '(cons 1 2)      ; (1 . 2)\n(car \'(1 2 3))   ; 1\n(cdr \'(1 2 3))   ; (2 3)',
             '(list 1 2 3)    ; (1 2 3)',
             '(cons 1 \'(2 3)) ; (1 2 3)',
             '(cadr \'(1 2 3)) ; 2\n(caddr \'(1 2 3)) ; 3',
         ]},
        {'slug': 'common-lisp-06-conditionals', 'title': 'Conditionals', 'desc': 'if, cond, and when.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use if', 'Use cond', 'Use when and unless', 'Combine conditions'],
         'prereq': ['Common Lisp-05: Cons Cells and Lists'],
         'samples': [
             '(if (> 3 2) "yes" "no")',
             '(cond ((> x 0) "positive")\n      ((< x 0) "negative")\n      (t "zero"))',
             '(when (> x 0) (format t "positive~%"))',
             '(unless (= x 0) (format t "not zero~%"))',
         ]},
        {'slug': 'common-lisp-07-loops', 'title': 'Loops', 'desc': 'do, loop, and iteration.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use loop macro', 'Use dolist', 'Use dotimes', 'Use do'],
         'prereq': ['Common Lisp-06: Conditionals'],
         'samples': [
             '(loop for i from 1 to 5 do (format t "~a " i))',
             '(dolist (item \'(a b c)) (format t "~a " item))',
             '(dotimes (i 3) (format t "~a " i))',
             '(loop for i from 1 to 10\n      when (evenp i)\n      collect i)',
         ]},
        {'slug': 'common-lisp-08-strings', 'title': 'Strings', 'desc': 'String operations.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Concatenate strings', 'Get length', 'Search strings', 'Format output'],
         'prereq': ['Common Lisp-07: Loops'],
         'samples': [
             '(concatenate \'string "Hello" " " "World")',
             '(length "hello")',
             '(search "world" "hello world")',
             '(format nil "value: ~d" 42)',
         ]},
        {'slug': 'common-lisp-09-lists-advanced', 'title': 'List Manipulation', 'desc': 'mapcar, remove, and sorting.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use mapcar', 'Filter with remove-if', 'Sort lists', 'Use reduce'],
         'prereq': ['Common Lisp-08: Strings'],
         'samples': [
             '(mapcar #\'1+ \'(1 2 3))',
             '(remove-if #\'oddp \'(1 2 3 4 5))',
             '(sort \'(3 1 2) #\'<)',
             '(reduce #\'+ \'(1 2 3 4))',
         ]},
        {'slug': 'common-lisp-10-clos', 'title': 'CLOS: Classes and Objects', 'desc': 'defclass, defmethod, and generics.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Define classes', 'Create instances', 'Define methods', 'Use inheritance'],
         'prereq': ['Common Lisp-09: List Manipulation'],
         'samples': [
             '(defclass person ()\n  ((name :initarg :name :accessor person-name)\n   (age :initarg :age :accessor person-age)))',
             '(make-instance \'person :name "Ada" :age 36)',
             '(defmethod greet ((p person))\n  (format t "Hi, ~a~%" (person-name p)))',
             '(defclass developer (person)\n  ((language :initarg :language :accessor dev-language)))',
         ]},
        {'slug': 'common-lisp-11-macros', 'title': 'Macros', 'desc': 'Code generation and DSLs.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write defmacro', 'Use backquote', 'Manage variable capture', 'Build DSLs'],
         'prereq': ['Common Lisp-10: CLOS: Classes and Objects'],
         'samples': [
             '(defmacro twice (expr)\n  \'(progn ,expr ,expr))',
             '(defmacro my-when (test &body body)\n  \`(if ,test (progn ,@body)))',
             '(defmacro incf2 (var) \`(setf ,var (+ ,var 2)))',
             '(defmacro unless (test &body body)\n  \`(if (not ,test) (progn ,@body)))',
         ]},
        {'slug': 'common-lisp-12-conditions', 'title': 'Conditions and Restarts', 'desc': 'Signals and handlers.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Signal conditions', 'Handle with handler-case', 'Use restarts', 'Write custom conditions'],
         'prereq': ['Common Lisp-11: Macros'],
         'samples': [
             '(handler-case (/ 10 0)\n  (division-by-zero () "caught"))',
             '(define-condition my-error (error)\n  ((message :initarg :message :reader err-msg)))',
             '(signal (make-condition \'my-error :message "boom"))',
             '(restart-case (error "fail")\n  (retry () "retried"))',
         ]},
        {'slug': 'common-lisp-13-io', 'title': 'Input/Output', 'desc': 'Read and write streams.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write to stdout', 'Read from stdin', 'Open files', 'Format streams'],
         'prereq': ['Common Lisp-12: Conditions and Restarts'],
         'samples': [
             '(format t "hello~%")',
             '(read-line)',
             '(with-open-file (s "data.txt" :direction :output)\n  (format s "hello~%"))',
             '(with-open-file (s "data.txt" :direction :input)\n  (read-line s))',
         ]},
        {'slug': 'common-lisp-14-packages', 'title': 'Packages', 'desc': 'Namespaces and symbols.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Define packages', 'Export symbols', 'Use package qualifiers', 'Manage imports'],
         'prereq': ['Common Lisp-13: Input/Output'],
         'samples': [
             '(defpackage :my-app\n  (:use :cl)\n  (:export :main))',
             '(in-package :my-app)',
             '(defun main () (format t "hello~%"))',
             'my-app:main',
         ]},
        {'slug': 'common-lisp-15-hash-tables', 'title': 'Hash Tables', 'desc': 'Key-value storage.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Create hash tables', 'Set and get values', 'Iterate entries', 'Remove entries'],
         'prereq': ['Common Lisp-14: Packages'],
         'samples': [
             '(setf *ht* (make-hash-table :test #\'equal))',
             '(setf (gethash "key" *ht*) 42)\n(gethash "key" *ht*)',
             '(maphash (lambda (k v) (format t "~a: ~a~%" k v)) *ht*)',
             '(remhash "key" *ht*)',
         ]},
        {'slug': 'common-lisp-16-sequences', 'title': 'Sequence Functions', 'desc': 'find, position, count, subseq.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Find elements', 'Get positions', 'Count occurrences', 'Slice sequences'],
         'prereq': ['Common Lisp-15: Hash Tables'],
         'samples': [
             '(find 3 \'(1 2 3 4))',
             '(position #\\o "hello")',
             '(count #\\l "hello")',
             '(subseq "hello world" 0 5)',
         ]},
        {'slug': 'common-lisp-17-optional-keywords', 'title': 'Optional and Keyword Arguments', 'desc': 'Flexible function signatures.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use &optional', 'Use &rest', 'Use &key', 'Use &aux'],
         'prereq': ['Common Lisp-16: Sequence Functions'],
         'samples': [
             '(defun f (a &optional (b 10)) (+ a b))',
             '(defun sum (&rest nums) (reduce #\'+ nums))',
             '(defun configure (&key host (port 80)) (list host port))',
             '(defun g (&optional (x 0) &rest rest) ...)',
         ]},
        {'slug': 'common-lisp-18-multiple-values', 'title': 'Multiple Values', 'desc': 'Return and bind several values.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Return multiple values', 'Bind with multiple-value-bind', 'Use values-list', 'Capture all values'],
         'prereq': ['Common Lisp-17: Optional and Keyword Arguments'],
         'samples': [
             '(defun divmod (a b) (values (floor a b) (mod a b)))',
             '(multiple-value-bind (q r) (divmod 7 2)\n  (list q r))',
             '(values 1 2 3)',
             '(multiple-value-list (divmod 7 2))',
         ]},
        {'slug': 'common-lisp-19-debugging', 'title': 'Debugging Tools', 'desc': 'trace, step, and inspect.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Trace functions', 'Step through code', 'Inspect values', 'Use describe'],
         'prereq': ['Common Lisp-18: Multiple Values'],
         'samples': [
             '(trace square)\n(square 5)\n(untrace square)',
             '(step (square 5))',
             '(inspect \'(1 2 3))',
             '(describe #\'square)',
         ]},
        {'slug': 'common-lisp-20-tests', 'title': 'Testing with FiveAM', 'desc': 'Unit testing library.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Set up FiveAM', 'Write tests', 'Run suites', 'Use assertions'],
         'prereq': ['Common Lisp-19: Debugging Tools'],
         'samples': [
             '(def-suite my-suite)',
             '(in-suite my-suite)\n(test addition\n  (is (= 4 (+ 2 2))))',
             '(test string\n  (is (string= "AB" (concatenate \'string "A" "B"))))',
             '(run! \'my-suite)',
         ]},
        {'slug': 'common-lisp-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Quicklisp, libraries, and tools.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use Quicklisp', 'Install libraries', 'Build web apps', 'Find community resources'],
         'prereq': ['Common Lisp-20: Testing with FiveAM'],
         'samples': [
             '(ql:quickload :alexandria)',
             '(ql:quickload :hunchentoot)',
             '(asdf:load-system :my-system)',
             '; community: lispforum, #lisp on IRC',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# GBSCRIPT
# ────────────────────────────────────────────────────────────────────────────
GDSCRIPT = {
    'lang': 'gdscript',
    'code_lang': 'gdscript',
    'refs': [
        ('Godot Docs: GDScript', 'https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/index.html', 'Official documentation'),
        ('GDScript Reference', 'https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html', 'Language reference'),
        ('Godot Community', 'https://godotengine.org/community/', 'Community links'),
    ],
    'lessons': [
        {'slug': 'gdscript-01-getting-started', 'title': 'Getting Started with GDScript', 'desc': 'Godot editor, scripts, and hello.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create a Godot project', 'Attach scripts to nodes', 'Print output', 'Run the scene'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'extends Node\n\nfunc _ready():\n    print("Hello, World!")',
             'extends Node\n\nfunc _ready():\n    print("Hello, ", "Godot!")',
             'extends Node\n\nfunc _ready():\n    var greeting = "Hello"\n    print(greeting)',
             'extends Node\n\nfunc _ready():\n    print(1 + 2)\n    print("num: ", 42)',
         ]},
        {'slug': 'gdscript-02-variables', 'title': 'Variables and Types', 'desc': 'Typed and untyped declarations.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare variables', 'Use explicit types', 'Use constants', 'Understand inference'],
         'prereq': ['GDScript-01: Getting Started with GDScript'],
         'samples': [
             'var score = 0\nvar name = "Ada"\nvar speed = 2.5',
             'var health: int = 100\nvar title: String = "Hero"',
             'const MAX_HP = 100\nconst PI = 3.14159',
             'var alive: bool = true\nvar items: Array = []',
         ]},
        {'slug': 'gdscript-03-control-flow', 'title': 'Control Flow', 'desc': 'if, match, and loops.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/elif/else', 'Use match statements', 'Use for loops', 'Use while loops'],
         'prereq': ['GDScript-02: Variables and Types'],
         'samples': [
             'var hp = 30\nif hp > 75:\n    print("healthy")\nelif hp > 25:\n    print("wounded")\nelse:\n    print("critical")',
             'match state:\n    "idle":\n        print("standing")\n    "run":\n        print("running")\n    _:\n        print("unknown")',
             'for i in range(3):\n    print(i)',
             'var i = 0\nwhile i < 3:\n    print(i)\n    i += 1',
         ]},
        {'slug': 'gdscript-04-functions', 'title': 'Functions', 'desc': 'Define and call functions.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write functions', 'Pass arguments', 'Return values', 'Use default params'],
         'prereq': ['GDScript-03: Control Flow'],
         'samples': [
             'func add(a, b):\n    return a + b\n\nfunc _ready():\n    print(add(2, 3))',
             'func greet(name: String) -> String:\n    return "Hello, " + name',
             'func move(dx := 0.0, dy := 0.0) -> void:\n    position.x += dx\n    position.y += dy',
             'func is_even(n: int) -> bool:\n    return n % 2 == 0',
         ]},
        {'slug': 'gdscript-05-arrays', 'title': 'Arrays and Dictionaries', 'desc': 'Collections in GDScript.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create arrays', 'Access elements', 'Use dictionaries', 'Iterate collections'],
         'prereq': ['GDScript-04: Functions'],
         'samples': [
             'var items = ["sword", "shield"]\nitems.append("potion")\nprint(items[0])',
             'var scores = [10, 20, 30]\nfor s in scores:\n    print(s)',
             'var player = {"name": "Ada", "hp": 100}\nprint(player["name"])',
             'for key in player:\n    print(key, ": ", player[key])',
         ]},
        {'slug': 'gdscript-06-signals', 'title': 'Signals', 'desc': 'Event-driven communication.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Declare signals', 'Emit signals', 'Connect signals', 'Disconnect signals'],
         'prereq': ['GDScript-05: Arrays and Dictionaries'],
         'samples': [
             'signal health_changed(new_hp)\n\nfunc take_damage(amount):\n    hp -= amount\n    health_changed.emit(hp)',
             'func _ready():\n    button.pressed.connect(_on_button_pressed)\n\nfunc _on_button_pressed():\n    print("clicked")',
             'signal died\nfunc _ready():\n    died.connect(queue_free)',
             'if not node.connected:\n    node.connect("pressed", Callable(self, "_on_pressed"))',
         ]},
        {'slug': 'gdscript-07-scenes', 'title': 'Scenes and Nodes', 'desc': 'Compose games with the scene tree.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Understand the scene tree', 'Get child nodes', 'Add children', 'Use groups'],
         'prereq': ['GDScript-06: Signals'],
         'samples': [
             'extends Node2D\n\nfunc _ready():\n    var child = get_node("Sprite2D")\n    print(child)',
             'var sprite = $Sprite2D   # shorthand',
             'var new_node = Label.new()\nadd_child(new_node)',
             'func _ready():\n    for node in get_tree().get_nodes_in_group("enemies"):\n        print(node)',
         ]},
        {'slug': 'gdscript-08-physics', 'title': 'Physics and Movement', 'desc': 'Move and collide in 2D.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use process and physics frames', 'Move with velocity', 'Detect collisions', 'Use delta time'],
         'prereq': ['GDScript-07: Scenes and Nodes'],
         'samples': [
             'extends CharacterBody2D\n\nvar speed = 300.0\n\nfunc _physics_process(delta):\n    var input = Input.get_vector("left", "right", "up", "down")\n    velocity = input * speed\n    move_and_slide()',
             'func _process(delta):\n    position.x += 100 * delta',
             'func _physics_process(delta):\n    velocity.y += 980 * delta   # gravity\n    move_and_slide()',
             'func _on_body_entered(body):\n    print(body.name, " entered")',
         ]},
        {'slug': 'gdscript-09-input', 'title': 'Input Handling', 'desc': 'Keyboard, mouse, and actions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Poll input', 'Use Input.is_action_pressed', 'Handle mouse events', 'Map input actions'],
         'prereq': ['GDScript-08: Physics and Movement'],
         'samples': [
             'func _process(delta):\n    if Input.is_action_pressed("ui_right"):\n        position.x += 10 * delta',
             'func _input(event):\n    if event is InputEventKey and event.pressed:\n        print(event.keycode)',
             'func _unhandled_input(event):\n    if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:\n        print("clicked at ", event.position)',
             'Input.action_press("jump")',
         ]},
        {'slug': 'gdscript-10-classes', 'title': 'Custom Classes and Inheritance', 'desc': 'Extend nodes and structure code.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create class_name', 'Extend built-in types', 'Override methods', 'Use super'],
         'prereq': ['GDScript-09: Input Handling'],
         'samples': [
             'class_name Player\n\nextends CharacterBody2D\n\nvar hp = 100',
             'class_name Enemy\nextends CharacterBody2D\n\nfunc take_damage(d):\n    hp -= d\n    if hp <= 0:\n        queue_free()',
             'func _ready():\n    super()\n    print("player ready")',
             'var e: Enemy = Enemy.new()',
         ]},
        {'slug': 'gdscript-11-animation', 'title': 'Animations', 'desc': 'Animate sprites and properties.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Play animations', 'Use AnimationPlayer', 'Tween properties', 'Sync animations'],
         'prereq': ['GDScript-10: Custom Classes and Inheritance'],
         'samples': [
             'func _ready():\n    $AnimationPlayer.play("walk")',
             'var tween = create_tween()\ntween.tween_property(self, "position", Vector2(100, 100), 1.0)',
             'func _ready():\n    $AnimationPlayer.play("idle")',
             'var tween = create_tween()\ntween.tween_property($Sprite2D, "modulate:a", 0.0, 0.5)',
         ]},
        {'slug': 'gdscript-12-export', 'title': 'Exporting Variables', 'desc': 'Configure nodes in the editor.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use @export', 'Expose typed ranges', 'Use @export_group', 'Tune values from editor'],
         'prereq': ['GDScript-11: Animation'],
         'samples': [
             'extends Node2D\n\n@export var speed = 100.0\n@export var color: Color = Color.WHITE',
             '@export_range(0, 10, 0.5) var volume = 1.0',
             '@export var items: Array[String] = []',
             '@export_group("Combat")\n@export var damage = 10\n@export var cooldown = 0.5',
         ]},
        {'slug': 'gdscript-13-areas', 'title': 'Areas and Collisions', 'desc': 'Overlap detection.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create Area2D', 'Detect overlaps', 'Use layers and masks', 'Handle area signals'],
         'prereq': ['GDScript-12: Exporting Variables'],
         'samples': [
             'func _ready():\n    $Area2D.area_entered.connect(_on_area_entered)\n\nfunc _on_area_entered(area):\n    print("entered ", area.name)',
             'func _ready():\n    $Area2D.body_entered.connect(_on_body_entered)',
             'func _on_area_entered(area):\n    if area.is_in_group("pickups"):\n        area.queue_free()',
             'func _physics_process(delta):\n    var overlaps = $Area2D.get_overlapping_bodies()\n    print(overlaps.size())',
         ]},
        {'slug': 'gdscript-14-ui', 'title': 'UI and HUDs', 'desc': 'Labels, buttons, and layouts.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create UI nodes', 'Update labels', 'Connect buttons', 'Build HUDs'],
         'prereq': ['GDScript-13: Areas and Collisions'],
         'samples': [
             'func _ready():\n    $HUD/HealthLabel.text = "HP: " + str(hp)',
             'func _ready():\n    $Button.pressed.connect(_on_clicked)\n\nfunc _on_clicked():\n    print("clicked")',
             'func update_score(points):\n    score += points\n    $HUD/ScoreLabel.text = str(score)',
             'var label = Label.new()\nlabel.text = "hello"\nadd_child(label)',
         ]},
        {'slug': 'gdscript-15-save', 'title': 'Saving and Loading', 'desc': 'Persist game state.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write save files', 'Read save files', 'Serialize data', 'Load game state'],
         'prereq': ['GDScript-14: UI and HUDs'],
         'samples': [
             'var data = {"score": score, "hp": hp}\nvar file = FileAccess.open("user://save.json", FileAccess.WRITE)\nfile.store_string(JSON.stringify(data))\nfile.close()',
             'if FileAccess.file_exists("user://save.json"):\n    var file = FileAccess.open("user://save.json", FileAccess.READ)\n    var data = JSON.parse_string(file.get_as_text())\n    file.close()',
             'var dir = DirAccess.open("user://")\nif not dir.dir_exists("saves"):\n    dir.make_dir("saves")',
             'DirAccess.remove_absolute("user://save.json")',
         ]},
        {'slug': 'gdscript-16-groups', 'title': 'Groups and Communication', 'desc': 'Broadcast to many nodes.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Add nodes to groups', 'Call group methods', 'Get group lists', 'Use groups for systems'],
         'prereq': ['GDScript-15: Saving and Loading'],
         'samples': [
             'func _ready():\n    add_to_group("enemies")',
             'get_tree().call_group("enemies", "take_damage", 10)',
             'for enemy in get_tree().get_nodes_in_group("enemies"):\n    enemy.take_damage(10)',
             'if is_in_group("player"):\n    print("I am the player")',
         ]},
        {'slug': 'gdscript-17-multithreading', 'title': 'Threads and Async', 'desc': 'Parallel work with signals.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Spawn threads', 'Use async functions', 'Use await', 'Communicate between threads'],
         'prereq': ['GDScript-16: Groups and Communication'],
         'samples': [
             'var thread = Thread.new()\nthread.start(_work)\n\nfunc _work():\n    print("in thread")',
             'func load_data():\n    var result = await get_tree().create_timer(1.0).timeout\n    print("done")',
             'var worker = WorkerThreadPool.add_task(_process_chunk)\nawait worker.wait_for_completion',
             'await signal_completed\nprint("after signal")',
         ]},
        {'slug': 'gdscript-18-autoloads', 'title': 'Autoload Singletons', 'desc': 'Global game state.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Create autoloads', 'Access global state', 'Manage singletons', 'Persist between scenes'],
         'prereq': ['GDScript-17: Threads and Async'],
         'samples': [
             'extends Node\n\nvar score = 0\nvar player_name = "Ada"',
             'func _ready():\n    Game.score = 10\n    print(Game.score)',
             'extends Node\n\nsignal game_over\n\nfunc end_game():\n    game_over.emit()',
             'Game.player_name = "Grace"\nprint(Game.player_name)',
         ]},
        {'slug': 'gdscript-19-export-game', 'title': 'Exporting Games', 'desc': 'Build for platforms.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Configure export presets', 'Export for desktop', 'Export for web', 'Optimize builds'],
         'prereq': ['GDScript-18: Autoload Singletons'],
         'samples': [
             'project.godot\n[application]\nconfig/name="My Game"',
             'godot --headless --export-release "Windows Desktop" build/game.exe',
             'godot --headless --export-release "Web" build/index.html',
             '--optimize: enable texture compression in export settings',
         ]},
        {'slug': 'gdscript-20-optimization', 'title': 'Performance Tips', 'desc': 'Keep games running fast.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Avoid per-frame allocations', 'Use pools', 'Limit draw calls', 'Profile performance'],
         'prereq': ['GDScript-19: Exporting Games'],
         'samples': [
             'var reused_array = []\n\nfunc _physics_process(delta):\n    reused_array.clear()\n    reused_array.append(1)',
             'preload("res://scene.tscn")   # compile-time load',
             'get_tree().debug_collisions_hint = false',
             'var profiler = Engine.get_frames_per_second()\nprint(profiler)',
         ]},
        {'slug': 'gdscript-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Asset libraries and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Find assets', 'Use addons', 'Publish games', 'Join the community'],
         'prereq': ['GDScript-20: Performance Tips'],
         'samples': [
             'godot --headless --import',
             'AssetLib available in the editor',
             '// community: godotengine.org, discord',
             'print("Ship your game!")',
         ]},
    ],
}

SPECS = [ASSEMBLY, AUTOHOTKEY, COMMON_LISP, GDSCRIPT]
