#!/usr/bin/env python3
"""Lesson specs for elm, fsharp, ocaml, groovy — real 21-lesson courses."""

# ────────────────────────────────────────────────────────────────────────────
# ELM
# ────────────────────────────────────────────────────────────────────────────
ELM = {
    'lang': 'elm',
    'code_lang': 'elm',
    'refs': [
        ('Elm Guide', 'https://guide.elm-lang.org/', 'Official guide — the best way to start'),
        ('Elm Packages', 'https://package.elm-lang.org/', 'Package registry'),
        ('Elm Syntax', 'https://elm-lang.org/docs/syntax', 'Language syntax reference'),
        ('Elm Discourse', 'https://discourse.elm-lang.org/', 'Community forum'),
    ],
    'lessons': [
        {'slug': 'elm-01-getting-started', 'title': 'Getting Started with Elm', 'desc': 'Install the compiler and build a first app.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install Elm', 'Write hello world with Html', 'Compile with elm make', 'Run elm reactor'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'module Main exposing (main)\n\nimport Html\n\nmain =\n    Html.text "Hello, World!"',
             'elm make src/Main.elm --output=main.js',
             'module Main exposing (main)\n\nimport Html exposing (text)\n\nmain = text "hello"',
             'elm reactor   # open http://localhost:8000',
         ]},
        {'slug': 'elm-02-values', 'title': 'Values and Functions', 'desc': 'Immutability, functions, and types.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write pure functions', 'Use type annotations', 'Apply functions with |>', 'Understand immutability'],
         'prereq': ['Elm-01: Getting Started with Elm'],
         'samples': [
             'add : Int -> Int -> Int\nadd a b =\n    a + b',
             'greet : String -> String\ngreet name =\n    "Hello, " ++ name ++ "!"',
             'double : Int -> Int\ndouble x = x * 2\n\nmain =\n    text (String.fromInt (double 21))',
             '4 |> double |> String.fromInt |> text',
         ]},
        {'slug': 'elm-03-numbers-strings', 'title': 'Numbers and Strings', 'desc': 'Basic types and conversions.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use Int and Float', 'Convert between numbers', 'Manipulate strings', 'Use String module functions'],
         'prereq': ['Elm-02: Values and Functions'],
         'samples': [
             'add : Float -> Float -> Float\nadd a b = a + b',
             'String.fromInt 42\nString.fromFloat 3.14',
             'String.length "hello"\nString.toUpper "hi"',
             'String.split "," "a,b,c"',
         ]},
        {'slug': 'elm-04-lists', 'title': 'Lists', 'desc': 'Immutable lists and List module.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create lists', 'Cons with ::', 'Use List.map and filter', 'Fold with foldl'],
         'prereq': ['Elm-03: Numbers and Strings'],
         'samples': [
             'nums = [1, 2, 3]\nfirst = 0 :: nums',
             'List.map (\\n -> n * 2) [1, 2, 3]',
             'List.filter (\\n -> n > 2) [1, 2, 3, 4]',
             'List.foldl (+) 0 [1, 2, 3]',
         ]},
        {'slug': 'elm-05-maybe', 'title': 'Maybe and Result', 'desc': 'Handle missing values safely.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Understand Maybe', 'Pattern match on Maybe', 'Use Result for errors', 'Chain with andThen'],
         'prereq': ['Elm-04: Lists'],
         'samples': [
             'parse : String -> Maybe Int\nparse s =\n    String.toInt s',
             'case parse "42" of\n    Just n -> text ("number: " ++ String.fromInt n)\n    Nothing -> text "not a number"',
             'divide : Float -> Float -> Result String Float\ndivide _ 0 =\n    Err "divide by zero"\ndivide a b =\n    Ok (a / b)',
             'String.toInt "5"\n    |> Maybe.andThen (\\n -> String.toInt (String.fromInt (n * 2)))',
         ]},
        {'slug': 'elm-06-records', 'title': 'Records', 'desc': 'Structured data with named fields.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create records', 'Access and update fields', 'Use record types', 'Pattern match records'],
         'prereq': ['Elm-05: Maybe and Result'],
         'samples': [
             'type alias Person =\n    { name : String, age : Int }\n\nada = { name = "Ada", age = 36 }',
             'ada.name\n{ ada | age = 37 }',
             'type alias Point = { x : Float, y : Float }\norigin : Point\norigin = { x = 0, y = 0 }',
             'describe : Person -> String\ndescribe p =\n    p.name ++ " is " ++ String.fromInt p.age',
         ]},
        {'slug': 'elm-07-union-types', 'title': 'Custom Types', 'desc': 'Enums and tagged unions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define custom types', 'Pattern match variants', 'Carry data in variants', 'Model states with types'],
         'prereq': ['Elm-06: Records'],
         'samples': [
             'type Color\n    = Red\n    | Green\n    | Blue',
             'type Shape\n    = Circle Float\n    | Square Float\n\narea : Shape -> Float\narea shape =\n    case shape of\n        Circle r -> 3.14159 * r * r\n        Square s -> s * s',
             'type State\n    = Loading\n    | Loaded (List String)\n    | Failed String',
             'type Direction = North | South | East | West\n\nturn : Direction -> Direction\nturn d =\n    case d of\n        North -> East\n        East -> South\n        South -> West\n        West -> North',
         ]},
        {'slug': 'elm-08-architecture', 'title': 'The Elm Architecture', 'desc': 'Model, update, and view.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Define the Model', 'Write update with messages', 'Render with view', 'Wire up init'],
         'prereq': ['Elm-07: Custom Types'],
         'samples': [
             'type Msg = Increment | Decrement\n\ntype alias Model = Int\n\nupdate : Msg -> Model -> Model\nupdate msg model =\n    case msg of\n        Increment -> model + 1\n        Decrement -> model - 1',
             'view : Model -> Html Msg\nview model =\n    div []\n        [ button [ onClick Decrement ] [ text "-" ]\n        , text (String.fromInt model)\n        , button [ onClick Increment ] [ text "+" ]\n        ]',
             'main : Program () Model Msg\nmain =\n    Browser.sandbox\n        { init = 0\n        , update = update\n        , view = view\n        }',
             'init : Model\ninit = 0',
         ]},
        {'slug': 'elm-09-cmd-sub', 'title': 'Commands and Subscriptions', 'desc': 'Side effects handled by the runtime.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Understand Cmd', 'Understand Sub', 'Use Time subscriptions', 'Fetch data'],
         'prereq': ['Elm-08: The Elm Architecture'],
         'samples': [
             'import Browser\nimport Html\nimport Html.Events exposing (onClick)\nimport Random',
             'type Msg = NewRandom Int\n\nupdate : Msg -> Model -> ( Model, Cmd Msg )\nupdate msg model =\n    case msg of\n        NewRandom n ->\n            ( n, Cmd.none )',
             'type Msg = Tick Float\n\nsubscriptions : Model -> Sub Msg\nsubscriptions _ =\n    Time.every 1000 Tick',
             'rollDice : Cmd Msg\nrollDice =\n    Random.generate NewRandom (Random.int 1 6)',
         ]},
        {'slug': 'elm-10-http', 'title': 'HTTP Requests', 'desc': 'Fetch data from APIs.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Use Http module', 'Decode JSON', 'Handle loading states', 'Show errors'],
         'prereq': ['Elm-09: Commands and Subscriptions'],
         'samples': [
             'import Http\nimport Json.Decode as Decode',
             'getUser : Cmd Msg\ngetUser =\n    Http.get\n        { url = "https://api.example.com/user"\n        , expect = Http.expectJson GotUser userDecoder\n        }',
             'userDecoder : Decode.Decoder User\nuserDecoder =\n    Decode.map2 User\n        (Decode.field "name" Decode.string)\n        (Decode.field "age" Decode.int)',
             'type Msg = GotUser (Result Http.Error User)',
         ]},
        {'slug': 'elm-11-json', 'title': 'JSON Decoding', 'desc': 'Compose decoders for complex data.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Decode primitives', 'Use mapN combinators', 'Decode lists', 'Handle optional fields'],
         'prereq': ['Elm-10: HTTP Requests'],
         'samples': [
             'import Json.Decode as D\n\nD.string\nD.int\nD.bool',
             'D.map2 (\\a b -> ( a, b ))\n    (D.field "x" D.int)\n    (D.field "y" D.int)',
             'D.list D.string',
             'D.maybe (D.field "nickname" D.string)',
         ]},
        {'slug': 'elm-12-forms', 'title': 'Forms and User Input', 'desc': 'Text fields, checkboxes, and validation.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Handle text input', 'Use checkbox events', 'Validate form data', 'Show field errors'],
         'prereq': ['Elm-11: JSON Decoding'],
         'samples': [
             'input [ type_ "text", value model.name, onInput NameChanged ] []',
             'input [ type_ "checkbox", checked model.agree, onCheck AgreeChanged ] []',
             'type Msg = NameChanged String\n\nupdate (NameChanged name) model =\n    { model | name = name }',
             'validate : Model -> Result String Model\nvalidate m =\n    if String.length m.name < 2 then\n        Err "name too short"\n    else\n        Ok m',
         ]},
        {'slug': 'elm-13-routing', 'title': 'Routing', 'desc': 'Hash routing and page navigation.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Set up Browser.application', 'Define route types', 'Parse URLs', 'Navigate with links'],
         'prereq': ['Elm-12: Forms and User Input'],
         'samples': [
             'type Route\n    = Home\n    | About\n    | User String',
             'fromUrl : Url -> Maybe Route\nfromUrl url =\n    case url.path of\n        "/" -> Just Home\n        "/about" -> Just About\n        _ -> Nothing',
             'a [ href "/about" ] [ text "About" ]',
             'Browser.application\n    { init = init, update = update, subscriptions = subscriptions, view = view, onUrlRequest = LinkClicked, onUrlChange = UrlChanged }',
         ]},
        {'slug': 'elm-14-performance', 'title': 'Performance', 'desc': 'Virtual DOM and optimization.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Understand virtual DOM', 'Use keys in lists', 'Avoid expensive computations', 'Use Html.Lazy'],
         'prereq': ['Elm-13: Routing'],
         'samples': [
             'Html.Lazy.lazy viewItem item',
             'List.indexedMap (\\i item -> Html.Keyed.node "li" [ (String.fromInt i, viewItem item) ]) items',
             'view : Model -> Html Msg\nview model =\n    Html.Lazy.lazy2 viewFor model.filters model.items',
             '-- measure with elm/browser Debug.todo or performance tools',
         ]},
        {'slug': 'elm-15-reusable', 'title': 'Reusable Components', 'desc': 'Compose modules and components.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Split code into modules', 'Pass callbacks down', 'Lift state up', 'Build reusable views'],
         'prereq': ['Elm-14: Performance'],
         'samples': [
             'module Counter exposing (Msg, view, update)',
             'type Msg = Increment | Decrement',
             'view : Int -> (Msg -> parentMsg) -> Html parentMsg\nview count toParent =\n    button [ onClick (toParent Increment) ] [ text (String.fromInt count) ]',
             'type alias ParentMsg = ChildMsg | Reset',
         ]},
        {'slug': 'elm-16-testing', 'title': 'Testing with elm-test', 'desc': 'Unit and fuzz tests.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Set up elm-test', 'Write unit tests', 'Use fuzzers', 'Test the update function'],
         'prereq': ['Elm-15: Reusable Components'],
         'samples': [
             'elm-test init',
             'import Expect\nimport Test exposing (Test, test)\n\nsuite : Test\nsuite =\n    test "addition" <|\\_ ->\n        Expect.equal (1 + 1) 2',
             'test "increment" <|\\_ ->\n    Expect.equal (update Increment 0) 1',
             'fuzz (Fuzz.intRange 0 100) "double is even" <|\\n ->\n    Expect.equal (modBy 2 (n * 2)) 0',
         ]},
        {'slug': 'elm-17-interop', 'title': 'JavaScript Interop', 'desc': 'Ports and custom elements.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use ports', 'Send data to JS', 'Receive data from JS', 'Build custom elements'],
         'prereq': ['Elm-16: Testing with elm-test'],
         'samples': [
             'port sendMessage : String -> Cmd msg\nport receiveMessage : (String -> msg) -> Sub msg',
             'module Main exposing (..)\nimport Html\n\nport module Main exposing (main)',
             'sendMessage "hello from elm"',
             'app.ports.receiveMessage.subscribe(function (msg) { console.log(msg); });',
         ]},
        {'slug': 'elm-18-architecture-advanced', 'title': 'Advanced Architecture Patterns', 'desc': 'OutMsg and parent-child flows.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use the OutMsg pattern', 'Manage complex updates', 'Structure large apps', 'Decouple modules'],
         'prereq': ['Elm-17: JavaScript Interop'],
         'samples': [
             'type OutMsg = SaveRequested String',
             'update : Msg -> Model -> ( Model, Cmd Msg, List OutMsg )',
             'case childResult of\n    Just out ->\n        case out of\n            SaveRequested d -> ( { m | saved = True }, Cmd.none, [] )',
             '-- keep modules small and message flows explicit',
         ]},
        {'slug': 'elm-19-optimization', 'title': 'Optimizing Elm Apps', 'desc': 'Bundle size and asset strategy.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Build with elm make --optimize', 'Minify output', 'Measure bundle size', 'Load assets lazily'],
         'prereq': ['Elm-18: Advanced Architecture Patterns'],
         'samples': [
             'elm make src/Main.elm --optimize --output=main.js',
             'uglifyjs main.js -c -m -o main.min.js',
             'ls -lh main.min.js',
             '-- use Browser.Navigation.load for heavy pages',
         ]},
        {'slug': 'elm-20-style', 'title': 'Styling Elm Apps', 'desc': 'CSS strategies and elm-ui.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use plain CSS classes', 'Use elm-ui layout', 'Build responsive layouts', 'Theme applications'],
         'prereq': ['Elm-19: Optimizing Elm Apps'],
         'samples': [
             'div [ class "card" ] [ text "content" ]',
             'import Element as E\n\nview : Model -> E.Element Msg\nview model =\n    E.layout [] (E.text "hello")',
             'E.row [ E.spacing 10 ] [ E.text "a", E.text "b" ]',
             'E.column [ E.padding 20 ] [ header, body ]',
         ]},
        {'slug': 'elm-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Packages, tooling, and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Publish packages', 'Use elm-format', 'Discover community tooling', 'Find help'],
         'prereq': ['Elm-20: Styling Elm Apps'],
         'samples': [
             'elm-format src/Main.elm --yes',
             'elm publish   # after package.elm-lang.org login',
             'elm-analyse --watch',
             '-- check elm packages: package.elm-lang.org',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# FSHARP
# ────────────────────────────────────────────────────────────────────────────
FSHARP = {
    'lang': 'fsharp',
    'code_lang': 'fsharp',
    'refs': [
        ('F# Documentation', 'https://learn.microsoft.com/en-us/dotnet/fsharp/', 'Official Microsoft docs'),
        ('F# for Fun and Profit', 'https://fsharpforfunandprofit.com/', 'Excellent learning resource'),
        ('FSharp.org', 'https://fsharp.org/', 'Community portal'),
    ],
    'lessons': [
        {'slug': 'fsharp-01-getting-started', 'title': 'Getting Started with F#', 'desc': 'Dotnet SDK, hello world, and F# Interactive.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install the .NET SDK', 'Create an F# project', 'Run F# Interactive', 'Write hello world'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'printfn "Hello, World!"',
             'dotnet new console -lang F# -o hello\ncd hello && dotnet run',
             'printfn "Hello, %s!" "Ada"',
             'let square x = x * x\nprintfn "%d" (square 21)',
         ]},
        {'slug': 'fsharp-02-values', 'title': 'Values and Types', 'desc': 'let bindings, immutability, and types.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Bind values with let', 'Use built-in types', 'Understand immutability', 'Use type inference'],
         'prereq': ['FSharp-01: Getting Started with F#'],
         'samples': [
             'let name = "Ada"\nlet age = 36\nprintfn "%s %d" name age',
             'let pi = 3.14159\nlet active = true',
             'let add a b = a + b   // inferred int -> int -> int',
             'let mutable counter = 0\ncounter <- counter + 1',
         ]},
        {'slug': 'fsharp-03-functions', 'title': 'Functions', 'desc': 'First-class functions and composition.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write functions', 'Use pipe operator |>', 'Compose with >>', 'Use lambda expressions'],
         'prereq': ['FSharp-02: Values and Types'],
         'samples': [
             'let double x = x * 2\nlet result = double 21',
             '5 |> double |> string |> printfn "%s"',
             'let addThenDouble = double << (fun x -> x + 1)',
             'let apply f x = f x\napply (fun n -> n + 1) 41',
         ]},
        {'slug': 'fsharp-04-collections', 'title': 'Collections', 'desc': 'Lists, arrays, and sequences.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create lists', 'Map and filter', 'Fold collections', 'Use arrays and seq'],
         'prereq': ['FSharp-03: Functions'],
         'samples': [
             'let nums = [1; 2; 3]\nlet doubled = List.map (fun n -> n * 2) nums',
             'List.filter (fun n -> n > 2) [1; 2; 3; 4]',
             'List.fold (+) 0 [1; 2; 3]',
             'let arr = [|1; 2; 3|]\nlet s = seq { 1..10 }',
         ]},
        {'slug': 'fsharp-05-strings', 'title': 'Strings', 'desc': 'String operations and interpolation.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Interpolate strings', 'Split and join', 'Use StringBuilder', 'Work with characters'],
         'prereq': ['FSharp-04: Collections'],
         'samples': [
             'let name = "Ada"\nlet msg = $"Hello, {name}!"',
             'let parts = "a,b,c".Split(',')\nlet joined = String.concat " | " parts',
             'let upper = "hello".ToUpper()',
             'let sb = System.Text.StringBuilder()\nsb.Append("hi") |> ignore',
         ]},
        {'slug': 'fsharp-06-options', 'title': 'Option and Result', 'desc': 'Handle absence and errors safely.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use Option type', 'Pattern match options', 'Use Result type', 'Chain computations'],
         'prereq': ['FSharp-05: Strings'],
         'samples': [
             'let parse (s: string) : int option =\n    match System.Int32.TryParse s with\n    | true, n -> Some n\n    | false, _ -> None',
             'let div a b =\n    if b = 0 then None else Some (a / b)',
             "type Result<'T, 'E> = Ok of 'T | Error of 'E",
             'Option.map (fun n -> n * 2) (parse "42")',
         ]},
        {'slug': 'fsharp-07-records', 'title': 'Records and Tuples', 'desc': 'Structured data types.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define records', 'Create and update records', 'Use tuples', 'Pattern match records'],
         'prereq': ['FSharp-06: Option and Result'],
         'samples': [
             'type Person = { Name: string; Age: int }\n\nlet ada = { Name = "Ada"; Age = 36 }',
             'let older = { ada with Age = 37 }',
             'let pair = (1, "one")\nfst pair',
             'let describe p =\n    match p with\n    | { Name = n; Age = a } -> sprintf "%s is %d" n a',
         ]},
        {'slug': 'fsharp-08-discriminated-unions', 'title': 'Discriminated Unions', 'desc': 'Model complex states with types.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define DUs', 'Pattern match variants', 'Carry data in cases', 'Model states safely'],
         'prereq': ['FSharp-07: Records and Tuples'],
         'samples': [
             'type Shape =\n    | Circle of float\n    | Square of float\n\nlet area s =\n    match s with\n    | Circle r -> 3.14159 * r * r\n    | Square side -> side * side',
             "type Option<'T> = Some of 'T | None",
             'type Color = Red | Green | Blue\n\nlet name c =\n    match c with\n    | Red -> "red"\n    | Green -> "green"\n    | Blue -> "blue"',
             'type State =\n    | Loading\n    | Loaded of string list\n    | Failed of string',
         ]},
        {'slug': 'fsharp-09-pattern-matching', 'title': 'Pattern Matching', 'desc': 'Powerful destructuring.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Match constants', 'Match with guards', 'Destructure tuples and lists', 'Use wildcards'],
         'prereq': ['FSharp-08: Discriminated Unions'],
         'samples': [
             'let describe n =\n    match n with\n    | 0 -> "zero"\n    | 1 -> "one"\n    | _ -> "many"',
             'let classify n =\n    match n with\n    | n when n < 0 -> "negative"\n    | 0 -> "zero"\n    | _ -> "positive"',
             'let sum (a, b) = a + b',
             'let rec length lst =\n    match lst with\n    | [] -> 0\n    | _ :: rest -> 1 + length rest',
         ]},
        {'slug': 'fsharp-10-recursion', 'title': 'Recursion', 'desc': 'Recursive functions and tail calls.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write recursive functions', 'Use tail recursion', 'Understand accumulator pattern', 'Use List recursion'],
         'prereq': ['FSharp-09: Pattern Matching'],
         'samples': [
             'let rec fact n =\n    if n <= 1 then 1 else n * fact (n - 1)',
             'let rec sumList lst =\n    match lst with\n    | [] -> 0\n    | x :: rest -> x + sumList rest',
             'let rec loop acc n =\n    if n <= 0 then acc else loop (acc + n) (n - 1)',
             'let rec map f lst =\n    match lst with\n    | [] -> []\n    | x :: rest -> f x :: map f rest',
         ]},
        {'slug': 'fsharp-11-modules', 'title': 'Modules and Namespaces', 'desc': 'Organize code with modules.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create modules', 'Use module functions', 'Nest modules', 'Control visibility'],
         'prereq': ['FSharp-10: Recursion'],
         'samples': [
             'module Math =\n    let square x = x * x\n\nMath.square 5',
             'module Geometry =\n    module Circle =\n        let area r = 3.14159 * r * r',
             'module private Helpers =\n    let secret () = 42',
             'module StringUtils =\n    let reverse (s: string) =\n        s |> Seq.rev |> System.String.Concat',
         ]},
        {'slug': 'fsharp-12-classes', 'title': 'Classes and OOP', 'desc': 'Interop with the .NET object model.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define classes', 'Use properties and methods', 'Use inheritance', 'Implement interfaces'],
         'prereq': ['FSharp-11: Modules and Namespaces'],
         'samples': [
             'type Person(name: string, age: int) =\n    member _.Name = name\n    member _.Age = age\n\nlet ada = Person("Ada", 36)',
             'type Counter() =\n    let mutable count = 0\n    member _.Increment() = count <- count + 1\n    member _.Count = count',
             'type Animal() =\n    abstract member Speak : unit -> string\n    default _.Speak() = "..."\n\ntype Dog() =\n    inherit Animal()\n    override _.Speak() = "Woof"',
             'type ILogger =\n    abstract member Log : string -> unit',
         ]},
        {'slug': 'fsharp-13-computation-expressions', 'title': 'Computation Expressions', 'desc': 'Workflows like option and async.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use option workflows', 'Use async workflows', 'Write let! and return', 'Build custom expressions'],
         'prereq': ['FSharp-12: Classes and OOP'],
         'samples': [
             'let tryDiv a b =\n    option {\n        if b = 0 then return! None\n        else return a / b\n    }',
             'let fetch url =\n    async {\n        let! html = System.Net.Http.HttpClient().GetStringAsync(url) |> Async.AwaitTask\n        return html.Length\n    }',
             'let compute =\n    async {\n        let! a = task1\n        let! b = task2\n        return a + b\n    }',
             'let result = option { let! x = parse "42"; return x * 2 }',
         ]},
        {'slug': 'fsharp-14-async', 'title': 'Async and Parallel', 'desc': 'Asynchronous programming.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create async workflows', 'Run in parallel', 'Use Async.Parallel', 'Cancel operations'],
         'prereq': ['FSharp-13: Computation Expressions'],
         'samples': [
             'let slow () = async { return 42 }\nlet result = slow () |> Async.RunSynchronously',
             'let tasks = [1..10] |> List.map (fun i -> async { return i * i })\nlet all = tasks |> Async.Parallel |> Async.RunSynchronously',
             'async {\n    do! Async.Sleep 100\n    return "done"\n} |> Async.RunSynchronously',
             'Async.StartAsTask (async { return 1 })',
         ]},
        {'slug': 'fsharp-15-io', 'title': 'File I/O', 'desc': 'Read and write files.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Read files', 'Write files', 'Read lines', 'Use paths'],
         'prereq': ['FSharp-14: Async and Parallel'],
         'samples': [
             'let content = System.IO.File.ReadAllText("data.txt")',
             'System.IO.File.WriteAllText("out.txt", "hello")',
             'System.IO.File.ReadLines("data.txt") |> Seq.iter (printfn "%s")',
             'System.IO.Directory.GetFiles(".")',
         ]},
        {'slug': 'fsharp-16-tests', 'title': 'Testing with xUnit', 'desc': 'Unit testing in F#.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Create a test project', 'Write xUnit tests', 'Use assertions', 'Run dotnet test'],
         'prereq': ['FSharp-15: File I/O'],
         'samples': [
             'dotnet new xunit -lang F# -o tests',
             'module Tests\n\nopen Xunit\n\n[<Fact>]\nlet ``addition works`` () =\n    Assert.Equal(4, 2 + 2)',
             '[<Theory>]\n[<InlineData(1, 1, 2)>]\n[<InlineData(2, 3, 5)>]\nlet ``add works`` (a, b, expected) =\n    Assert.Equal(expected, a + b)',
             'Assert.True(5 > 3)',
         ]},
        {'slug': 'fsharp-17-fscheck', 'title': 'Property Testing with FsCheck', 'desc': 'Automated property-based testing.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Define properties', 'Run FsCheck', 'Use generators', 'Test with FsCheck.Xunit'],
         'prereq': ['FSharp-16: Testing with xUnit'],
         'samples': [
             'open FsCheck\nopen FsCheck.Xunit\n\n[<Property>]\nlet ``double is even`` (n: int) =\n    (n * 2) % 2 = 0',
             'Check.Quick (fun n -> n + 0 = n)',
             'Gen.choose (0, 100)\n|> Gen.sample 0 5\n|> printfn "%A"',
             '[<Property>]\nlet ``reverse reverse`` (s: string) =\n    s |> Seq.rev |> Seq.rev |> Seq.toArray |> System.String = s',
         ]},
        {'slug': 'fsharp-18-fable', 'title': 'Fable: F# in the Browser', 'desc': 'Compile F# to JavaScript.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Set up Fable', 'Build a web app', 'Interop with JS', 'Use Elmish'],
         'prereq': ['FSharp-17: Property Testing with FsCheck'],
         'samples': [
             'dotnet new fable -lang F#',
             "module App\n\nopen Fable.Core.JsInterop\n\nlet main () =\n    emitJsStatement () \"document.body.textContent = 'Hello from F#';\"",
             'importAll "bootstrap/dist/css/bootstrap.min.css"',
             'open Elmish\nopen Elmish.React',
         ]},
        {'slug': 'fsharp-19-dsl', 'title': 'DSLs and Type Providers', 'desc': 'Domain-specific languages.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Build embedded DSLs', 'Use type providers', 'Write fluent APIs', 'Compose computations'],
         'prereq': ['FSharp-18: Fable: F# in the Browser'],
         'samples': [
             'let andAlso = (&&)\nlet orElse = (||)',
             'type csv = CsvProvider<"sample.csv">',
             'type json = JsonProvider<"https://api.example.com/data">',
             'let builder =\n    { Config.empty with\n        Host = "localhost"\n        Port = 8080 }',
         ]},
        {'slug': 'fsharp-20-performance', 'title': 'Performance', 'desc': 'Structs, arrays, and optimization.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use struct records', 'Avoid allocations', 'Use arrays for hot paths', 'Profile with dotnet'],
         'prereq': ['FSharp-19: DSLs and Type Providers'],
         'samples': [
             '[<Struct>]\ntype Point = { X: float; Y: float }',
             'let arr = Array.zeroCreate<int> 1000000',
             '// use Arrays over Lists in hot loops',
             'dotnet trace collect -- dotnet run',
         ]},
        {'slug': 'fsharp-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Libraries and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Discover F# libraries', 'Use Paket', 'Join the community', 'Explore FAKE build tools'],
         'prereq': ['FSharp-20: Performance'],
         'samples': [
             'dotnet add package FSharp.Data',
             'dotnet tool install --global dotnet-fake\nfake build',
             'dotnet paket add FSharp.Control.AsyncSeq',
             '// community: fsharp.org, F# Software Foundation',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# OCAML
# ────────────────────────────────────────────────────────────────────────────
OCAML = {
    'lang': 'ocaml',
    'code_lang': 'ocaml',
    'refs': [
        ('OCaml Manual', 'https://ocaml.org/manual/', 'Official language manual'),
        ('OCaml Tutorials', 'https://ocaml.org/docs', 'Official documentation'),
        ('Real World OCaml', 'https://dev.realworldocaml.org/', 'Comprehensive book'),
    ],
    'lessons': [
        {'slug': 'ocaml-01-getting-started', 'title': 'Getting Started with OCaml', 'desc': 'OPAM, utop, and hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install OCaml with OPAM', 'Use utop REPL', 'Compile with ocamlopt', 'Write hello world'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'print_endline "Hello, World!"',
             'ocaml\n# print_endline "hello";;',
             'ocamlopt -o hello hello.ml\n./hello',
             'let () = print_endline "Hello, " ^ "OCaml!"',
         ]},
        {'slug': 'ocaml-02-values', 'title': 'Values and Types', 'desc': 'let bindings and basic types.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Bind values with let', 'Use int, float, and string', 'Use bool and char', 'Understand type inference'],
         'prereq': ['Ocaml-01: Getting Started with OCaml'],
         'samples': [
             'let name = "Ada"\nlet age = 36',
             'let pi = 3.14159\nlet active = true',
             'let add a b = a + b',
             'let greet name = "Hello, " ^ name ^ "!"',
         ]},
        {'slug': 'ocaml-03-functions', 'title': 'Functions', 'desc': 'Higher-order functions and currying.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write functions', 'Understand currying', 'Use lambda functions', 'Compose functions'],
         'prereq': ['Ocaml-02: Values and Types'],
         'samples': [
             'let square x = x * x',
             'let add a b = a + b\nlet addFive = add 5',
             'let doubled = List.map (fun x -> x * 2) [1; 2; 3]',
             'let compose f g x = f (g x)',
         ]},
        {'slug': 'ocaml-04-lists', 'title': 'Lists', 'desc': 'Immutable linked lists.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Build lists', 'Cons with ::', 'Use List functions', 'Fold lists'],
         'prereq': ['Ocaml-03: Functions'],
         'samples': [
             'let nums = [1; 2; 3]\nlet more = 0 :: nums',
             'List.map (fun n -> n * 2) [1; 2; 3]',
             'List.filter (fun n -> n > 2) [1; 2; 3; 4]',
             'List.fold_left (+) 0 [1; 2; 3]',
         ]},
        {'slug': 'ocaml-05-pattern-matching', 'title': 'Pattern Matching', 'desc': 'Destructure data safely.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Match on values', 'Match lists', 'Use wildcards', 'Match tuples'],
         'prereq': ['Ocaml-04: Lists'],
         'samples': [
             'let describe n =\n  match n with\n  | 0 -> "zero"\n  | 1 -> "one"\n  | _ -> "many"',
             'let rec length lst =\n  match lst with\n  | [] -> 0\n  | _ :: rest -> 1 + length rest',
             'let classify n =\n  match n with\n  | n when n < 0 -> "neg"\n  | 0 -> "zero"\n  | _ -> "pos"',
             'let sum (a, b) = a + b',
         ]},
        {'slug': 'ocaml-06-options', 'title': 'Option Types', 'desc': 'Represent optional values.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use option type', 'Pattern match Some/None', 'Use Option module', 'Avoid null patterns'],
         'prereq': ['Ocaml-05: Pattern Matching'],
         'samples': [
             'let safe_div a b =\n  if b = 0 then None else Some (a / b)',
             'match safe_div 10 2 with\n| Some n -> Printf.printf "%d\n" n\n| None -> print_endline "div by zero"',
             'Option.map (fun n -> n * 2) (Some 21)',
             'let lookup key tbl = Hashtbl.find_opt tbl key',
         ]},
        {'slug': 'ocaml-07-records', 'title': 'Records', 'desc': 'Named field structures.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define record types', 'Create and access records', 'Copy records', 'Use record patterns'],
         'prereq': ['Ocaml-06: Option Types'],
         'samples': [
             'type person = { name : string; age : int }\n\nlet ada = { name = "Ada"; age = 36 }',
             'let name = ada.name',
             'let older = { ada with age = 37 }',
             'let describe { name; age } = Printf.sprintf "%s %d" name age',
         ]},
        {'slug': 'ocaml-08-variants', 'title': 'Variants', 'desc': 'Sum types for data modeling.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define variant types', 'Carry data in variants', 'Match variants', 'Model states'],
         'prereq': ['Ocaml-07: Records'],
         'samples': [
             'type color = Red | Green | Blue',
             'type shape =\n  | Circle of float\n  | Square of float\n\nlet area s =\n  match s with\n  | Circle r -> 3.14159 *. r *. r\n  | Square side -> side *. side',
             'type state =\n  | Loading\n  | Loaded of string list\n  | Failed of string',
             'let name c =\n  match c with\n  | Red -> "red" | Green -> "green" | Blue -> "blue"',
         ]},
        {'slug': 'ocaml-09-modules', 'title': 'Modules and Signatures', 'desc': 'Encapsulate code with modules.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create modules', 'Define signatures', 'Hide implementations', 'Use module functors'],
         'prereq': ['Ocaml-08: Variants'],
         'samples': [
             'module Math = struct\n  let square x = x * x\nend\n\nlet () = print_int (Math.square 5)',
             'module type COUNTER = sig\n  val inc : unit -> unit\n  val get : unit -> int\nend',
             'module Counter : COUNTER = struct\n  let count = ref 0\n  let inc () = incr count\n  let get () = !count\nend',
             'module StringMap = Map.Make(String)',
         ]},
        {'slug': 'ocaml-10-recursion', 'title': 'Recursion and Tail Calls', 'desc': 'Recursive definitions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write recursive functions', 'Ensure tail recursion', 'Use accumulator patterns', 'Define recursive types'],
         'prereq': ['Ocaml-09: Modules and Signatures'],
         'samples': [
             'let rec fact n =\n  if n <= 1 then 1 else n * fact (n - 1)',
             'let rec loop acc n =\n  if n <= 0 then acc else loop (acc + n) (n - 1)',
             'type intlist = Nil | Cons of int * intlist',
             'let rec map f = function\n  | [] -> []\n  | x :: rest -> f x :: map f rest',
         ]},
        {'slug': 'ocaml-11-imperative', 'title': 'Imperative Features', 'desc': 'Refs, arrays, and mutable state.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use ref cells', 'Use arrays', 'Understand aliasing', 'Use while loops'],
         'prereq': ['Ocaml-10: Recursion and Tail Calls'],
         'samples': [
             'let counter = ref 0\ncounter := !counter + 1',
             'let arr = [|1; 2; 3|]\narr.(0) <- 10',
             'let total = ref 0\nlet () =\n  for i = 1 to 10 do\n    total := !total + i\n  done',
             'while !counter < 3 do incr counter done',
         ]},
        {'slug': 'ocaml-12-exceptions', 'title': 'Exceptions', 'desc': 'Raise and handle errors.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Raise exceptions', 'Catch with try/with', 'Define custom exceptions', 'Clean up with finally'],
         'prereq': ['Ocaml-11: Imperative Features'],
         'samples': [
             'let () =\n  try\n    failwith "boom"\n  with\n  | Failure msg -> print_endline msg',
             'exception Empty_list',
             'let safe_head = function\n  | [] -> raise Empty_list\n  | x :: _ -> x',
             'let read () =\n  try\n    Some (input_line stdin)\n  with End_of_file -> None',
         ]},
        {'slug': 'ocaml-13-functors', 'title': 'Functors', 'desc': 'Modules parameterized by modules.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Define functors', 'Apply functors', 'Use Set.Make', 'Use Map.Make'],
         'prereq': ['Ocaml-12: Exceptions'],
         'samples': [
             'module type ORDERED = sig\n  type t\n  val compare : t -> t -> int\nend',
             'module MakeSet (X : ORDERED) = struct\n  type t = X.t list\n  let empty = []\n  let mem x s = List.exists (fun y -> X.compare x y = 0) s\nend',
             'module IntSet = MakeSet(struct type t = int let compare = compare end)',
             'module S = Set.Make(Int)',
         ]},
        {'slug': 'ocaml-14-gadt', 'title': 'Advanced Types', 'desc': 'GADTs and polymorphic variants.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use polymorphic variants', 'Understand GADTs', 'Write type-safe DSLs', 'Use first-class modules'],
         'prereq': ['Ocaml-13: Functors'],
         'samples': [
             'let f = function `Int n -> n | `Str s -> String.length s',
             'type _ expr =\n  | Int : int -> int expr\n  | Bool : bool -> bool expr\n  | Add : int expr * int expr -> int expr',
             'let rec eval : type a. a expr -> a = function\n  | Int n -> n\n  | Bool b -> b\n  | Add (x, y) -> eval x + eval y',
             'module type S = sig val x : int end\nmodule M = struct let x = 42 end\nlet v = (module M : S)',
         ]},
        {'slug': 'ocaml-15-io', 'title': 'Input/Output', 'desc': 'File and console IO.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Read from stdin', 'Read files', 'Write files', 'Format output'],
         'prereq': ['Ocaml-14: Advanced Types'],
         'samples': [
             'let () = print_endline "hello"',
             'let () =\n  let ic = open_in "data.txt" in\n  let content = really_input_string ic (in_channel_length ic) in\n  close_in ic',
             'let () =\n  let oc = open_out "out.txt" in\n  output_string oc "hello";\n  close_out oc',
             'Printf.printf "value: %d\n" 42',
         ]},
        {'slug': 'ocaml-16-mutable-state', 'title': 'Objects and Classes', 'desc': 'OCaml object system.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Define classes', 'Use inheritance', 'Use object types', 'Mix OOP with FP'],
         'prereq': ['Ocaml-15: Input/Output'],
         'samples': [
             'class counter =\n  object\n    val mutable count = 0\n    method increment = count <- count + 1\n    method get = count\n  end\n\nlet c = new counter',
             'class animal =\n  object\n    method speak = "..."\n  end\n\nclass dog =\n  object\n    inherit animal\n    method! speak = "Woof"\n  end',
             'let o = object method x = 1 end\n(o#x)',
             'let s = new counter\nlet () = s#increment',
         ]},
        {'slug': 'ocaml-17-lwt', 'title': 'Concurrency with Lwt', 'desc': 'Cooperative threads for IO.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create Lwt promises', 'Bind with >>=', 'Use Lwt_main.run', 'Handle async errors'],
         'prereq': ['Ocaml-16: Objects and Classes'],
         'samples': [
             'let () =\n  Lwt_main.run (Lwt_io.printl "hello")',
             'let () =\n  Lwt_main.run (Lwt.return 42 >>= fun n -> Lwt_io.printlf "%d" n)',
             'let fetch url =\n  Cohttp_lwt_unix.Client.get (Uri.of_string url)',
             'let both = Lwt.both p1 p2',
         ]},
        {'slug': 'ocaml-18-ppx', 'title': 'PPX and Metaprogramming', 'desc': 'Syntax extensions.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand PPX', 'Use ppx_deriving', 'Write annotations', 'Extend syntax'],
         'prereq': ['Ocaml-17: Concurrency with Lwt'],
         'samples': [
             'type point = { x : int; y : int } [@@deriving show]',
             'let () = print_endline (show_point { x = 1; y = 2 })',
             'type t = A | B [@@deriving sexp]',
             '[@@@warning "-27"]',
         ]},
        {'slug': 'ocaml-19-tests', 'title': 'Testing with Alcotest', 'desc': 'Unit and property tests.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write Alcotest tests', 'Use check functions', 'Group tests', 'Run test binaries'],
         'prereq': ['Ocaml-18: PPX and Metaprogramming'],
         'samples': [
             'let test_add () = Alcotest.(check int) "same" 4 (2 + 2)',
             'let suite = [ ("math", [ Alcotest.test_case "add" `Quick test_add ]) ]',
             'let () = Alcotest.run "my tests" [ suite ]',
             'Alcotest.(check string) "msg" "hi" (String.lowercase_ascii "HI")',
         ]},
        {'slug': 'ocaml-20-dune', 'title': 'Dune Build System', 'desc': 'Build and manage OCaml projects.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Create a dune project', 'Define libraries', 'Run executables', 'Use dune test'],
         'prereq': ['Ocaml-19: Testing with Alcotest'],
         'samples': [
             'dune init project hello\ncd hello && dune build',
             '(executable\n (name main)\n (libraries unix))',
             '(library\n (name mylib)\n (modules mylib))',
             'dune test\n dune utop src',
         ]},
        {'slug': 'ocaml-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Libraries, tooling, and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Discover OCaml libraries', 'Use opam packages', 'Build real projects', 'Join the community'],
         'prereq': ['Ocaml-20: Dune Build System'],
         'samples': [
             'opam install lwt cohttp',
             'opam search json',
             'opam exec -- dune utop',
             '// community: ocaml.org, discuss.ocaml.org',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# GROOVY
# ────────────────────────────────────────────────────────────────────────────
GROOVY = {
    'lang': 'groovy',
    'code_lang': 'groovy',
    'refs': [
        ('Groovy Documentation', 'https://groovy-lang.org/documentation.html', 'Official docs'),
        ('Groovy Tutorial (Groovy-lang)', 'https://groovy-lang.org/single-page-documentation.html', 'Official reference'),
        ('Groovy in Action', 'https://www.manning.com/books/groovy-in-action-second-edition', 'Book'),
    ],
    'lessons': [
        {'slug': 'groovy-01-getting-started', 'title': 'Getting Started with Groovy', 'desc': 'Install, run scripts, and hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install Groovy', 'Run scripts with groovy', 'Use the REPL', 'Write hello world'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'println "Hello, World!"',
             'groovy hello.groovy',
             'groovy -e \'println "hello"\'',
             'def name = "Ada"\nprintln "Hello, ${name}!"',
         ]},
        {'slug': 'groovy-02-variables', 'title': 'Variables and Types', 'desc': 'Dynamic typing and type inference.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use def for dynamic typing', 'Declare typed variables', 'Use strings and numbers', 'Understand GStrings'],
         'prereq': ['Groovy-01: Getting Started with Groovy'],
         'samples': [
             'def x = 42\ndef name = "Ada"\ndef pi = 3.14',
             'int count = 10\nString message = "hello"',
             'def greeting = "Hello, $name!"   // GString',
             'println x.class',
         ]},
        {'slug': 'groovy-03-control-flow', 'title': 'Control Flow', 'desc': 'Conditionals and loops.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/else', 'Use switch', 'Use for loops', 'Use each closures'],
         'prereq': ['Groovy-02: Variables and Types'],
         'samples': [
             'def score = 85\nif (score >= 90) {\n  println "A"\n} else if (score >= 80) {\n  println "B"\n} else {\n  println "C"\n}',
             'switch (n) {\n  case 1: println "one"; break\n  default: println "other"\n}',
             'for (i in 1..5) { println i }',
             '[1, 2, 3].each { println it }',
         ]},
        {'slug': 'groovy-04-lists', 'title': 'Lists and Maps', 'desc': 'Groovy collection literals.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create lists', 'Use list methods', 'Create maps', 'Iterate collections'],
         'prereq': ['Groovy-03: Control Flow'],
         'samples': [
             'def nums = [1, 2, 3]\nnums << 4\nprintln nums',
             'def doubled = nums.collect { it * 2 }',
             'def person = [name: "Ada", age: 36]\nprintln person.name',
             'person.each { k, v -> println "$k: $v" }',
         ]},
        {'slug': 'groovy-05-closures', 'title': 'Closures', 'desc': 'First-class functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write closures', 'Pass closures', 'Capture variables', 'Use closure methods'],
         'prereq': ['Groovy-04: Lists and Maps'],
         'samples': [
             'def square = { it * it }\nprintln square(5)',
             'def apply = { f, x -> f(x) }\napply({ n -> n + 1 }, 41)',
             'def counter = 0\ndef inc = { counter++ }\ninc(); inc()\nprintln counter',
             '[1, 2, 3].findAll { it > 1 }.each { println it }',
         ]},
        {'slug': 'groovy-06-strings', 'title': 'String Handling', 'desc': 'String methods and templates.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use string methods', 'Interpolate GStrings', 'Split and join', 'Use regex operators'],
         'prereq': ['Groovy-05: Closures'],
         'samples': [
             'def s = "hello world"\nprintln s.length()\nprintln s.toUpperCase()',
             'def name = "Ada"\nprintln "Hi $name"',
             'println "a,b,c".split(",").join(" | ")',
             'def text = "hello 123"\nassert text ==~ /.*\\d+.*/',
         ]},
        {'slug': 'groovy-07-classes', 'title': 'Classes and Traits', 'desc': 'OOP in Groovy.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define classes', 'Use properties', 'Write constructors', 'Use traits'],
         'prereq': ['Groovy-06: String Handling'],
         'samples': [
             'class Person {\n  String name\n  int age\n}\n\ndef p = new Person(name: "Ada", age: 36)\nprintln p.name',
             'class Counter {\n  int count = 0\n  void increment() { count++ }\n}',
             'class Point {\n  int x, y\n  Point(int x, int y) { this.x = x; this.y = y }\n}',
             'trait Greeter {\n  String greeting() { "hello" }\n}\n\nclass Person implements Greeter {}',
         ]},
        {'slug': 'groovy-08-optional-dot', 'title': 'Safe Navigation and Null Handling', 'desc': 'Null-safe operators.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use ?. operator', 'Use elvis operator', 'Use ?: default', 'Handle nulls safely'],
         'prereq': ['Groovy-07: Classes and Traits'],
         'samples': [
             'def name = user?.name   // null-safe',
             'def city = user?.address?.city ?: "unknown"',
             'def count = list?.size() ?: 0',
             'def value = map.key ?: "default"',
         ]},
        {'slug': 'groovy-09-metaprogramming', 'title': 'Metaprogramming', 'desc': 'Runtime method magic.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use methodMissing', 'Use propertyMissing', 'Add dynamic methods', 'Use Expando'],
         'prereq': ['Groovy-08: Safe Navigation and Null Handling'],
         'samples': [
             'class Dynamic {\n  def methodMissing(String name, args) {\n    "called $name with $args"\n  }\n}\n\nprintln new Dynamic().anything(1, 2)',
             'class Flex {\n  def propertyMissing(String name) { "missing: $name" }\n}\nprintln new Flex().someProp',
             'def e = new Expando()\ne.dynamicMethod = { println "hi" }\ne.dynamicMethod()',
             'String.metaClass.shout = { delegate.toUpperCase() }\nprintln "hello".shout()',
         ]},
        {'slug': 'groovy-10-gpars', 'title': 'Concurrency with GPars', 'desc': 'Parallel and async programming.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use parallel collections', 'Create async tasks', 'Use dataflow', 'Coordinate actors'],
         'prereq': ['Groovy-09: Metaprogramming'],
         'samples': [
             '@Grab(group="org.codehaus.gpars", module="gpars", version="1.2.1")\nimport groovyx.gpars.GParsPool\n\ndef result = GParsPool.withPool {\n  (1..100).collectParallel { it * 2 }\n}',
             'def future = GParsPool.withPool { async { 42 } }\nprintln future.get()',
             'def ch = new groovyx.gpars.dataflow.DataflowQueue()\nch << 42\nprintln ch.val',
             'GParsPool.withPool(4) { (1..10).eachParallel { println it } }',
         ]},
        {'slug': 'groovy-11-io', 'title': 'File I/O', 'desc': 'Groovy file helpers.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Read files', 'Write files', 'Read lines', 'Use new File'],
         'prereq': ['Groovy-10: Concurrency with GPars'],
         'samples': [
             'def text = new File("data.txt").text',
             'new File("out.txt").text = "hello"',
             'new File("data.txt").eachLine { println it }',
             'new File("data.txt").withReader { reader -> println reader.readLine() }',
         ]},
        {'slug': 'groovy-12-json', 'title': 'JSON and XML', 'desc': 'Data interchange.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Parse JSON', 'Generate JSON', 'Parse XML', 'Slurp structures'],
         'prereq': ['Groovy-11: File I/O'],
         'samples': [
             'import groovy.json.JsonSlurper\ndef data = new JsonSlurper().parseText(\'{"name": "Ada"}\')\nprintln data.name',
             'import groovy.json.JsonOutput\nprintln JsonOutput.toJson([name: "Ada", age: 36])',
             'import groovy.xml.XmlSlurper\ndef xml = new XmlSlurper().parseText("<a><b>x</b></a>")\nprintln xml.b.text()',
             'import groovy.json.JsonBuilder\ndef json = new JsonBuilder()\njson.person { name "Ada" }\nprintln json',
         ]},
        {'slug': 'groovy-13-groovysh', 'title': 'Scripting and groovysh', 'desc': 'REPL and script tools.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use groovysh', 'Write scripts', 'Use CLI args', 'Use groovyConsole'],
         'prereq': ['Groovy-12: JSON and XML'],
         'samples': [
             'groovysh',
             'def args = this.args\nprintln args',
             'println "Hello, ${args[0]}"',
             'groovyConsole',
         ]},
        {'slug': 'groovy-14-templates', 'title': 'Templates', 'desc': 'Text and HTML generation.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use SimpleTemplateEngine', 'Use GString templates', 'Build HTML', 'Render views'],
         'prereq': ['Groovy-13: Scripting and groovysh'],
         'samples': [
             'import groovy.text.SimpleTemplateEngine\n\ndef engine = new SimpleTemplateEngine()\ndef template = engine.createTemplate("Hello, \\$name").make([name: "Ada"])\nprintln template',
             'def tpl = "Hi $name, you are $age"\ndef out = new SimpleTemplateEngine().createTemplate(tpl).make(name: "Ada", age: 36)\nprintln out',
             'def html = "<ul>${items.collect { "<li>$it</li>" }.join()}</ul>"',
             'engine.createTemplate(file).make(binding)',
         ]},
        {'slug': 'groovy-15-gradle', 'title': 'Gradle Builds', 'desc': 'Build automation with Groovy DSL.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand Gradle projects', 'Write build.gradle', 'Define tasks', 'Run builds'],
         'prereq': ['Groovy-14: Templates'],
         'samples': [
             'plugins {\n  id "java"\n}',
             'task hello {\n  doLast {\n    println "Hello from Gradle"\n  }\n}',
             'dependencies {\n  implementation "org.codehaus.groovy:groovy:3.0.9"\n}',
             './gradlew hello',
         ]},
        {'slug': 'groovy-16-spock', 'title': 'Testing with Spock', 'desc': 'BDD-style testing framework.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Write Spock specs', 'Use given/when/then', 'Use where blocks', 'Mock collaborators'],
         'prereq': ['Groovy-15: Gradle Builds'],
         'samples': [
             'import spock.lang.Specification\n\nclass MathSpec extends Specification {\n  def "addition works"() {\n    expect:\n    2 + 2 == 4\n  }\n}',
             'def "max returns larger"() {\n  given:\n  def a = 3\n  def b = 5\n\n  expect:\n  Math.max(a, b) == 5\n}',
             'def "sum of range"() {\n  expect:\n  (1..n).sum() == expected\n\n  where:\n  n  | expected\n  1  | 1\n  2  | 3\n  3  | 6\n}',
             'def "uses mocks"() {\n  given:\n  def service = Mock(Service)\n  1 * service.call(_) >> "mocked"\n}',
         ]},
        {'slug': 'groovy-17-grails', 'title': 'Web Development with Grails', 'desc': 'Full-stack web framework.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create Grails apps', 'Define controllers', 'Define domain classes', 'Render views'],
         'prereq': ['Groovy-16: Testing with Spock'],
         'samples': [
             'grails create-app myapp',
             'class PersonController {\n  def index() {\n    [people: Person.list()]\n  }\n}',
             'class Person {\n  String name\n  Integer age\n  static constraints = {\n    name blank: false\n  }\n}',
             'grails run-app',
         ]},
        {'slug': 'groovy-18-ratpack', 'title': 'Ratpack and Microservices', 'desc': 'Lightweight web services.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Set up Ratpack', 'Define routes', 'Handle JSON', 'Build APIs'],
         'prereq': ['Groovy-17: Web Development with Grails'],
         'samples': [
             'import ratpack.groovy.Groovy\n\ndef app = Groovy.ratpack {\n  handlers {\n    get { render "Hello, World!" }\n  }\n}',
             'handlers {\n  get("hello/:name") {\n    render "Hello, ${pathTokens.name}!"\n  }\n}',
             'get("api/data") {\n  render json([name: "Ada"])\n}',
             'post("api/user") {\n  def body = request.body.text\n  render body\n}',
         ]},
        {'slug': 'groovy-19-categories', 'title': 'Categories', 'desc': 'Scoped method injection.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Define categories', 'Use @Category', 'Use withCategory', 'Scope extensions'],
         'prereq': ['Groovy-18: Ratpack and Microservices'],
         'samples': [
             '@Category(String)\nclass StringCategory {\n  String shout() { this.toUpperCase() + "!" }\n}\n\nuse(StringCategory) {\n  println "hello".shout()\n}',
             'class MathCategory {\n  static Integer triple(Integer self) { self * 3 }\n}\nuse(MathCategory) { println 4.triple() }',
             '@Category(List)\nclass ListCategory {\n  Number sum() { this.sum() }\n}',
             'use(StringCategory) { assert "hi".shout() == "HI!" }',
         ]},
        {'slug': 'groovy-20-ast', 'title': 'AST Transformations', 'desc': 'Compile-time code generation.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use @ToString', 'Use @Canonical', 'Use @Builder', 'Write custom transforms'],
         'prereq': ['Groovy-19: Categories'],
         'samples': [
             'import groovy.transform.*\n\n@Canonical\nclass Person {\n  String name\n  int age\n}\n\nprintln new Person("Ada", 36)',
             '@ToString\nclass Point { int x, y }',
             '@Builder\nclass Widget {\n  String name\n  int size\n}\n\ndef w = Widget.builder().name("w").size(5).build()',
             '@TupleConstructor\nclass Pair { int a; int b }',
         ]},
        {'slug': 'groovy-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Libraries and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Discover Groovy libraries', 'Use Grapes @Grab', 'Integrate with Java', 'Join the community'],
         'prereq': ['Groovy-20: AST Transformations'],
         'samples': [
             '@Grab("org.apache.commons:commons-lang3:3.12.0")\nimport org.apache.commons.lang3.StringUtils\nprintln StringUtils.capitalize("hello")',
             '@Grab(group="com.fasterxml.jackson.core", module="jackson-databind", version="2.14.0")',
             'groovy -cp . script.groovy',
             '// community: groovy-lang.org, mailing lists',
         ]},
    ],
}

SPECS = [ELM, FSHARP, OCAML, GROOVY]
