#!/usr/bin/env python3
"""Lesson specs for shell, ada, cobol, fortran — real 21-lesson courses."""

# ────────────────────────────────────────────────────────────────────────────
# SHELL (POSIX/Bash)
# ────────────────────────────────────────────────────────────────────────────
SHELL = {
    'lang': 'shell',
    'code_lang': 'bash',
    'refs': [
        ('GNU Bash Reference Manual', 'https://www.gnu.org/software/bash/manual/bash.html', 'The authoritative Bash reference'),
        ('ShellCheck', 'https://www.shellcheck.net/', 'Static analysis for shell scripts'),
        ('BashGuide (Bash Hackers Wiki)', 'https://wiki.bash-hackers.org/', 'Practical Bash wiki'),
        ('Explain Shell', 'https://explainshell.com/', 'Break down any command line'),
    ],
    'lessons': [
        {'slug': 'shell-01-getting-started', 'title': 'Getting Started with Shell Scripting', 'desc': 'Shebang, echo, permissions, and your first script.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write a script with a proper shebang', 'Make a script executable with chmod', 'Use echo and comments effectively', 'Run a script from any directory'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '#!/usr/bin/env bash\n# Hello from 100X Systems!\necho "Hello, World!"',
             '#!/usr/bin/env bash\n# run with: bash hello.sh\necho "Hello, $USER!"',
             'chmod +x hello.sh\n./hello.sh   # execute directly',
             '#!/usr/bin/env bash\necho "Date: $(date)"\necho "Shell: $SHELL"',
         ]},
        {'slug': 'shell-02-variables', 'title': 'Variables and Expansion', 'desc': 'Assignment, quoting, parameter expansion, and special variables.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Assign and reference variables', 'Quote with single, double, and backticks', 'Use special parameters $0 $# $@', 'Apply parameter expansion patterns'],
         'prereq': ['Shell-01: Getting Started with Shell Scripting'],
         'samples': [
             'name="Ada"\necho "Hello, $name"',
             'echo "Double quotes: $HOME"\necho \'Single quotes: $HOME\'',
             '#!/usr/bin/env bash\necho "Script: $0"\necho "Args: $#"\necho "All: $@"',
             'file="report.pdf"\necho "${file%.pdf}.txt"   # strip suffix',
         ]},
        {'slug': 'shell-03-arithmetic', 'title': 'Arithmetic and Exit Status', 'desc': 'Integer math, command substitution, and exit codes.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Perform arithmetic with $(( ))', 'Capture command output with $( )', 'Check and use exit statuses', 'Chain commands with && and ||'],
         'prereq': ['Shell-02: Variables and Expansion'],
         'samples': [
             'a=10\nb=3\necho $((a + b)) $((a * b)) $((a / b))',
             'files=$(ls | wc -l)\necho "Files: $files"',
             'grep "error" app.log && echo "Found" || echo "Clean"',
             'command_that_fails; echo "exit: $?"',
         ]},
        {'slug': 'shell-04-conditionals', 'title': 'Conditionals and test', 'desc': 'if/elif/else, test brackets [ ], and compound conditions.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/elif/else branches', 'Use [ ] and [[ ]] test expressions', 'Test files, strings, and numbers', 'Combine conditions with && || !'],
         'prereq': ['Shell-03: Arithmetic and Exit Status'],
         'samples': [
             'if [ "$1" = "start" ]; then\n  echo "Starting..."\nelif [ "$1" = "stop" ]; then\n  echo "Stopping..."\nelse\n  echo "Usage: $0 start|stop"\nfi',
             'if [ -f "config.yml" ]; then\n  echo "Config exists"\nfi',
             'if [[ "$name" == A* ]]; then\n  echo "Matches A*"\nfi',
             'if [ "$x" -gt 10 ] && [ "$x" -lt 20 ]; then\n  echo "Between 10 and 20"\nfi',
         ]},
        {'slug': 'shell-05-loops', 'title': 'Loops: for, while, until', 'desc': 'Iteration over lists, reading files, and loop control.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Iterate with for loops', 'Use while and until loops', 'Read files line by line', 'Control loops with break and continue'],
         'prereq': ['Shell-04: Conditionals and test'],
         'samples': [
             'for file in *.txt; do\n  echo "Processing $file"\ndone',
             'for i in {1..5}; do\n  echo "Iteration $i"\ndone',
             'while read -r line; do\n  echo "$line"\ndone < data.txt',
             'for i in {1..10}; do\n  [ $((i % 2)) -eq 0 ] && continue\n  echo "$i"\ndone',
         ]},
        {'slug': 'shell-06-functions', 'title': 'Functions', 'desc': 'Define, call, and scope functions with arguments.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Define and call functions', 'Pass arguments with $1 $2', 'Return values and use local vars', 'Structure scripts with helpers'],
         'prereq': ['Shell-05: Loops: for, while, until'],
         'samples': [
             'greet() {\n  echo "Hello, $1!"\n}\ngreet "World"',
             'add() {\n  local sum=$(( $1 + $2 ))\n  echo "$sum"\n}\nresult=$(add 4 5)\necho "Sum: $result"',
             'is_file() {\n  [ -f "$1" ]\n}\nif is_file "notes.md"; then\n  echo "It exists"\nfi',
             'main() {\n  local who="${1:-stranger}"\n  echo "Hi, $who"\n}\nmain "Ada"',
         ]},
        {'slug': 'shell-07-globbing', 'title': 'Globbing and Pattern Matching', 'desc': 'Filename expansion, wildcards, and extglob patterns.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use *, ?, and [] wildcards', 'Prevent expansion with quoting', 'Use extglob patterns', 'Work with nullglob and dotglob'],
         'prereq': ['Shell-06: Functions'],
         'samples': [
             'echo *.log            # all .log files\nls -d dir*            # dirs starting with dir',
             'echo "*.log"          # literal asterisk',
             'shopt -s extglob\nrm !(*.txt)        # everything except .txt',
             'shopt -s nullglob\nfiles=(*.nomatch)\necho "Count: ${#files[@]}"',
         ]},
        {'slug': 'shell-08-string-manipulation', 'title': 'String Manipulation', 'desc': 'Substring, length, replacement, and case conversion.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Get string length and substrings', 'Strip and replace patterns', 'Split strings into arrays', 'Convert case and trim whitespace'],
         'prereq': ['Shell-07: Globbing and Pattern Matching'],
         'samples': [
             's="hello world"\necho "${#s}"           # 11\necho "${s:0:5}"        # hello',
             'path="/usr/local/bin"\necho "${path#/usr/}"   # local/bin\necho "${path%/*}"      # /usr/local',
             's="a,b,c"\nIFS=, read -ra parts <<< "$s"\necho "${parts[1]}"',
             's="Hello"\necho "${s,,}"          # lowercase\necho "${s^^}"          # UPPERCASE',
         ]},
        {'slug': 'shell-09-arrays', 'title': 'Arrays', 'desc': 'Indexed and associative arrays for structured data.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Declare and index arrays', 'Iterate and slice arrays', 'Use associative arrays (Bash 4+)', 'Apply arrays in real scripts'],
         'prereq': ['Shell-08: String Manipulation'],
         'samples': [
             'colors=(red green blue)\necho "${colors[1]}"',
             'colors=(red green blue)\nfor c in "${colors[@]}"; do\n  echo "$c"\ndone',
             'declare -A caps\ncaps[us]="Washington"\ncaps[uk]="London"\necho "${caps[us]}"',
             'nums=(1 2 3 4 5)\necho "${#nums[@]}"      # length\nunset nums[0]         # remove element',
         ]},
        {'slug': 'shell-10-io-redirection', 'title': 'Input/Output Redirection', 'desc': 'Redirect stdin/stdout/stderr, pipes, and heredocs.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Redirect output with > and >>', 'Feed input with < and heredocs', 'Separate stderr with 2>', 'Build pipelines with |'],
         'prereq': ['Shell-09: Arrays'],
         'samples': [
             'echo "log line" >> app.log',
             'sort < names.txt > sorted.txt',
             'command 2> error.log 1> output.log',
             'cat <<EOF > config.ini\nhost=localhost\nport=8080\nEOF',
         ]},
        {'slug': 'shell-11-job-control', 'title': 'Job Control and Processes', 'desc': 'Background jobs, signals, and process management.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Run jobs in the background', 'List and kill processes', 'Handle signals with trap', 'Wait for background jobs'],
         'prereq': ['Shell-10: Input/Output Redirection'],
         'samples': [
             'sleep 10 &\necho "PID: $!"\nwait $!',
             'kill -TERM 1234     # send signal\nkill -9 1234        # force kill',
             'trap "echo Cleaning up; exit" INT\nwhile true; do sleep 1; done',
             'jobs -l\nfg %1     # bring job 1 to foreground',
         ]},
        {'slug': 'shell-12-sed', 'title': 'Text Processing with sed', 'desc': 'Stream editing: substitution, deletion, and ranges.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Substitute text with s///', 'Delete and print lines', 'Apply sed to line ranges', 'Edit files in place'],
         'prereq': ['Shell-11: Job Control and Processes'],
         'samples': [
             'echo "hello" | sed \'s/hello/hi/\'',
             'sed -n \'2,5p\' file.txt     # print lines 2-5',
             'sed \'/^#/d\' config.ini    # drop comments',
             'sed -i \'s/old/new/g\' file.txt',
         ]},
        {'slug': 'shell-13-awk', 'title': 'Text Processing with awk', 'desc': 'Column extraction, conditions, and summary reports.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Print selected columns', 'Filter rows with conditions', 'Use BEGIN/END blocks', 'Accumulate sums and counts'],
         'prereq': ['Shell-12: Text Processing with sed'],
         'samples': [
             'echo "alice 90" | awk \'{print $1}\'',
             'awk \'$2 > 80 {print $1}\' grades.txt',
             'awk \'BEGIN {print "Report"} {print} END {print "Done"}\' file.txt',
             'awk \'{sum += $2; n++} END {print "avg:", sum/n}\' data.txt',
         ]},
        {'slug': 'shell-14-regex', 'title': 'Regular Expressions with grep', 'desc': 'grep patterns, extended regex, and ripgrep alternatives.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Search with grep and egrep', 'Use character classes and anchors', 'Extract matches with -o', 'Count and invert matches'],
         'prereq': ['Shell-13: Text Processing with awk'],
         'samples': [
             'grep "error" app.log',
             'grep -E "^[0-9]{3}-" phones.txt',
             'grep -oE "[a-z]+@[a-z]+\\\\.com" emails.txt',
             'grep -c "TODO" *.py && grep -L "TODO" *.py',
         ]},
        {'slug': 'shell-15-parameter-expansion', 'title': 'Advanced Parameter Expansion', 'desc': 'Defaults, indirection, and case modification.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Provide default values ${var:-x}', 'Use indirection ${!name}', 'Handle unset variables strictly', 'Transform with ${var^} and friends'],
         'prereq': ['Shell-14: Regular Expressions with grep'],
         'samples': [
             'echo "${PORT:-8080}"     # default when unset',
             'name="PORT"\necho "${!name}"   # indirection',
             'set -u\necho "$UNDEFINED"   # errors on unset',
             'word="hello"\necho "${word^}"   # Hello\necho "${word^^}"  # HELLO',
         ]},
        {'slug': 'shell-16-debugging', 'title': 'Debugging and Error Handling', 'desc': 'set -euxo, tracing, and defensive scripting.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Trace execution with set -x', 'Exit on errors with set -e', 'Use set -u and pipefail', 'Write fail-fast scripts'],
         'prereq': ['Shell-15: Advanced Parameter Expansion'],
         'samples': [
             '#!/usr/bin/env bash\nset -euo pipefail\necho "Safe script starts"',
             'bash -x script.sh    # trace every command',
             'set -e\nfalse\necho "never reached"',
             'trap \'echo "Failed at $LINENO"\' ERR',
         ]},
        {'slug': 'shell-17-environment', 'title': 'Environment and Configuration', 'desc': 'ENV vars, exports, and config file patterns.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Export environment variables', 'Load .env files safely', 'Use positional default patterns', 'Pass secrets via environment'],
         'prereq': ['Shell-16: Debugging and Error Handling'],
         'samples': [
             'export DB_HOST="localhost"\n./app',
             'set -a\nsource .env\nset +a',
             'env | grep -i "PORT"',
             'run() {\n  local api_key="${API_KEY:?missing}"\n  curl -H "Authorization: Bearer $api_key" https://api.example.com\n}',
         ]},
        {'slug': 'shell-18-commands-find-xargs', 'title': 'find and xargs', 'desc': 'Find files, execute commands, and parallel processing.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Search files with find criteria', 'Execute commands with -exec', 'Chain with xargs safely', 'Handle spaces and special chars'],
         'prereq': ['Shell-17: Environment and Configuration'],
         'samples': [
             'find . -name "*.py" -type f',
             'find . -name "*.log" -mtime +7 -delete',
             'find . -name "*.txt" -print0 | xargs -0 wc -l',
             'find . -name "*.js" -exec grep -l "console.log" {} \\\\;',
         ]},
        {'slug': 'shell-19-scripts-in-practice', 'title': 'Shell Scripts in Practice', 'desc': 'Real CLI tools: argument parsing and help text.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Parse flags with getopts', 'Write help and usage text', 'Validate inputs robustly', 'Structure a production script'],
         'prereq': ['Shell-18: find and xargs'],
         'samples': [
             'while getopts "hv" opt; do\n  case $opt in\n    h) echo "Help!" ;;\n    v) echo "v1.0.0" ;;\n  esac\ndone',
             'usage() {\n  echo "Usage: $0 [-v] file"\n  exit 1\n}\n[ $# -lt 1 ] && usage',
             '[[ "$1" =~ ^- ]] && { echo "Bad flag: $1"; exit 1; }',
             'log() { echo "[$(date +%T)] $*"; }\nlog "started deploy"',
         ]},
        {'slug': 'shell-20-performance', 'title': 'Performance and Best Practices', 'desc': 'Avoid subshells, optimize loops, and follow style guides.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Avoid unnecessary subshells', 'Use printf over echo for safety', 'Apply Bash best practices', 'Profile slow scripts'],
         'prereq': ['Shell-19: Shell Scripts in Practice'],
         'samples': [
             'if grep -q error file; then :; fi   # no subshell',
             'printf "%s\\\\n" "safe output"',
             'result=$(( ${result:-0} + 1 ))  # fast integer math',
             'time bash big_script.sh       # profile',
         ]},
        {'slug': 'shell-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Bash alternatives, tools, and where to go next.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Know when to use bash vs Python', 'Discover jq, yq, and modern tools', 'Explore shellcheck and CI integration', 'Find community best practices'],
         'prereq': ['Shell-20: Performance and Best Practices'],
         'samples': [
             'curl -s https://api.github.com/repos/octocat/Hello-World | jq \'.stargazers_count\'',
             'yq eval \'.services.app.port\' docker-compose.yml',
             'brew install shellcheck && shellcheck script.sh',
             'echo "$RANDOM"   # next: learn advanced tools',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# ADA
# ────────────────────────────────────────────────────────────────────────────
ADA = {
    'lang': 'ada',
    'code_lang': 'ada',
    'refs': [
        ('Ada Reference Manual', 'https://www.adaic.org/resources/add_content/standards/', 'The official language standard'),
        ('Learn Ada', 'https://learn.adacore.com/', 'AdaCore official interactive course'),
        ('Ada Programming (Wikibooks)', 'https://en.wikibooks.org/wiki/Ada_Programming', 'Community textbook'),
    ],
    'lessons': [
        {'slug': 'ada-01-getting-started', 'title': 'Getting Started with Ada', 'desc': 'GNAT toolchain, hello world, and the Ada model.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install the GNAT toolchain', 'Write and compile a hello world', 'Understand program structure', 'Use Ada.Text_IO for output'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'with Ada.Text_IO;\n\nprocedure Hello is\nbegin\n   Ada.Text_IO.Put_Line (\"Hello, World!\");\nend Hello;',
             'gnatmake hello.adb\n./hello',
             'with Ada.Text_IO;\n\nprocedure Greet is\nbegin\n   Ada.Text_IO.Put_Line (\"Hello, \" & Ada.Command_Line.Argument (1));\nend Greet;',
             'with Ada.Text_IO;\n\nprocedure Basics is\nbegin\n   Ada.Text_IO.Put (\"No newline\");\n   Ada.Text_IO.New_Line;\nend Basics;',
         ]},
        {'slug': 'ada-02-types', 'title': 'Types and Subtypes', 'desc': 'Ada\'s strong typing, ranges, and derived types.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare scalar types with ranges', 'Create subtypes and derived types', 'Use type qualification', 'Understand strong typing benefits'],
         'prereq': ['Ada-01: Getting Started with Ada'],
         'samples': [
             'type Day is range 1 .. 31;\ntoday : Day := 15;',
             'type Percent is range 0 .. 100;\nsubtype Grade is Percent range 0 .. 100;',
             'type Celsius is digits 7 range -273.15 .. 1.0e10;\ntemp : Celsius := 21.5;',
             'type Colors is (Red, Green, Blue);\nc : Colors := Green;',
         ]},
        {'slug': 'ada-03-declarations', 'title': 'Variables and Constants', 'desc': 'Object declaration, initialization, and constants.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare typed variables', 'Initialize values safely', 'Use constants for safety', 'Rename with renames'],
         'prereq': ['Ada-02: Types and Subtypes'],
         'samples': [
             'count : Integer := 0;\ncount := count + 1;',
             'Pi : constant := 3.14159;',
             'Name : constant String := \"Ada\";\n-- String length known at compile time',
             'Full_Name : String renames Name;',
         ]},
        {'slug': 'ada-04-expressions', 'title': 'Operators and Expressions', 'desc': 'Arithmetic, relational, and logical operators.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use arithmetic operators', 'Compare with relational operators', 'Combine with logical operators', 'Control evaluation with parentheses'],
         'prereq': ['Ada-03: Variables and Constants'],
         'samples': [
             'x : Integer := 2 + 3 * 4;   -- 14\n\nprocedure Show is\nbegin\n   null;\nend Show;',
             'if a > b and c < d then\n   null;\nend if;',
             'odd_number : Boolean := (n mod 2) = 1;',
             'z : Integer := x / y;  -- integer division\ndivide_error : exception;',
         ]},
        {'slug': 'ada-05-control-flow', 'title': 'Control Flow: if, case, loops', 'desc': 'Conditionals, case statements, and loop forms.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/elsif/else branches', 'Use case statements', 'Write all loop forms', 'Use exit and loop labels'],
         'prereq': ['Ada-04: Operators and Expressions'],
         'samples': [
             'if score >= 90 then\n   Ada.Text_IO.Put_Line (\"A\");\nelsif score >= 80 then\n   Ada.Text_IO.Put_Line (\"B\");\nelse\n   Ada.Text_IO.Put_Line (\"C\");\nend if;',
             'case Direction is\n   when North => Put (\"N\");\n   when East  => Put (\"E\");\n   when others => Put (\"?\");\nend case;',
             "for i in 1 .. 10 loop\n   Put (Integer'Image (i));\nend loop;",
             'loop\n   Get (Command);\n   exit when Command = \"quit\";\nend loop;',
         ]},
        {'slug': 'ada-06-strings', 'title': 'Strings', 'desc': 'Fixed, bounded, and unbounded strings.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use fixed-length strings', 'Work with Ada.Strings.Unbounded', 'Concatenate and compare', 'Convert between string types'],
         'prereq': ['Ada-05: Control Flow: if, case, loops'],
         'samples': [
             'Greeting : String (1 .. 13) := \"Hello, World!\";',
             'with Ada.Strings.Unbounded;\nuse Ada.Strings.Unbounded;\nS : Unbounded_String := To_Unbounded_String (\"Hi\");',
             'Full : String := \"Ada\" & \" \" & \"Lovelace\";',
             'with Ada.Strings.Fixed;\nPosition := Ada.Strings.Fixed.Index (S, \"World\");',
         ]},
        {'slug': 'ada-07-arrays', 'title': 'Arrays', 'desc': 'Indexed and multi-dimensional arrays with bounds.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Declare array types', 'Use array slices', 'Iterate with attributes', 'Build multi-dimensional arrays'],
         'prereq': ['Ada-06: Strings'],
         'samples': [
             'type Vector is array (1 .. 10) of Integer;\nv : Vector := (others => 0);',
             'Matrix : array (1 .. 3, 1 .. 3) of Integer := (others => (others => 0));',
             'scores : array (1 .. 5) of Integer := (10, 20, 30, 40, 50);\nslice : array (1 .. 2) of Integer := scores (2 .. 3);',
             "for i in v'Range loop\n   Put (Integer'Image (v (i)));\nend loop;",
         ]},
        {'slug': 'ada-08-records', 'title': 'Records and Variants', 'desc': 'Record types, discriminants, and variant records.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define record types', 'Access record components', 'Use discriminants', 'Model with variant records'],
         'prereq': ['Ada-07: Arrays'],
         'samples': [
             'type Point is record\n   X, Y : Integer;\nend record;\np : Point := (X => 1, Y => 2);',
             'p.X := 10;  -- mutate component',
             'type Square (Side : Positive) is record\n   Area : Integer;\nend record;',
             'type Shape (Kind : Shape_Kind) is record\n   case Kind is\n      when Circle => Radius : Float;\n      when Square => Side   : Float;\n   end case;\nend record;',
         ]},
        {'slug': 'ada-09-procedures', 'title': 'Procedures and Functions', 'desc': 'Subprograms, parameters, and modes.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write functions and procedures', 'Use parameter modes in/out/in out', 'Pass by reference safely', 'Overload subprogram names'],
         'prereq': ['Ada-08: Records and Variants'],
         'samples': [
             'function Add (A, B : Integer) return Integer is\nbegin\n   return A + B;\nend Add;',
             'procedure Swap (A, B : in out Integer) is\n   Tmp : Integer := A;\nbegin\n   A := B;\n   B := Tmp;\nend Swap;',
             'procedure Log (Msg : in String) is\nbegin\n   Ada.Text_IO.Put_Line (Msg);\nend Log;',
             'function Max (A, B : Integer) return Integer is\nbegin\n   return (if A > B then A else B);\nend Max;',
         ]},
        {'slug': 'ada-10-exceptions', 'title': 'Exceptions', 'desc': 'Raise, handle, and propagate exceptions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Declare exception types', 'Raise exceptions', 'Handle with exception blocks', 'Use standard exceptions'],
         'prereq': ['Ada-09: Procedures and Functions'],
         'samples': [
             'Divide_By_Zero : exception;',
             'if B = 0 then\n   raise Divide_By_Zero;\nend if;',
             'begin\n   Compute;\nexception\n   when Divide_By_Zero =>\n      Ada.Text_IO.Put_Line (\"Caught division by zero\");\nend;',
             'begin\n   Danger;\nexception\n   when Constraint_Error => Put (\"Range check failed\");\n   when others => Put (\"Something else\");\nend;',
         ]},
        {'slug': 'ada-11-packages', 'title': 'Packages and Visibility', 'desc': 'Spec/body separation and encapsulation.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write package specifications', 'Write package bodies', 'Control visibility with private', 'Use child packages'],
         'prereq': ['Ada-10: Exceptions'],
         'samples': [
             'package Greetings is\n   procedure Hello;\nend Greetings;',
             'package body Greetings is\n   procedure Hello is\n   begin\n      Ada.Text_IO.Put_Line (\"Hello!\");\n   end Hello;\nend Greetings;',
             'package Counter is\nprivate\n   Value : Integer := 0;\nend Counter;',
             'package Greetings.Friendly is\n   procedure Hi;\nend Greetings.Friendly;',
         ]},
        {'slug': 'ada-12-generics', 'title': 'Generics', 'desc': 'Generic subprograms and packages for reuse.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write generic functions', 'Write generic packages', 'Instantiate generics', 'Constrain with generic formal types'],
         'prereq': ['Ada-11: Packages and Visibility'],
         'samples': [
             'generic\n   type T is private;\nfunction Identity (X : T) return T;',
             'function Identity is new Identity (Integer);',
             'generic\n   type Element is private;\npackage Stack is\n   procedure Push (E : Element);\nend Stack;',
             'generic\n   type Index is (<>);\n   type Vector is array (Index range <>) of Integer;\npackage Stats is\n   function Sum (V : Vector) return Integer;\nend Stats;',
         ]},
        {'slug': 'ada-13-access-types', 'title': 'Access Types and Pointers', 'desc': 'Pointers, allocation, and controlled types.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Declare access types', 'Allocate with new', 'Dereference safely', 'Use access parameters'],
         'prereq': ['Ada-12: Generics'],
         'samples': [
             'type Node;\ntype Node_Access is access Node;\ntype Node is record\n   Value : Integer;\n   Next  : Node_Access;\nend record;',
             "Head : Node_Access := new Node'(Value => 1, Next => null);",
             "Head.Next := new Node'(Value => 2, Next => null);",
             'procedure Show (N : not null Node_Access) is begin null; end Show;',
         ]},
        {'slug': 'ada-14-tagged-types', 'title': 'Tagged Types and OOP', 'desc': 'Object-oriented programming in Ada.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Define tagged types', 'Implement inheritance', 'Use dispatching calls', 'Write abstract types'],
         'prereq': ['Ada-13: Access Types and Pointers'],
         'samples': [
             'type Animal is tagged record\n   Name : String (1 .. 20);\nend record;',
             'type Dog is new Animal with record\n   Breed : String (1 .. 20);\nend record;',
             'function Sound (A : Animal) return String is\nbegin\n   return \"...\";\nend Sound;',
             'type Shape is abstract tagged null record;\nprocedure Draw (S : Shape) is abstract;',
         ]},
        {'slug': 'ada-15-file-io', 'title': 'File Input/Output', 'desc': 'Text and binary file handling.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Open and close text files', 'Read and write text', 'Handle end of file', 'Work with binary files'],
         'prereq': ['Ada-14: Tagged Types and OOP'],
         'samples': [
             'with Ada.Text_IO;\nuse Ada.Text_IO;\nF : File_Type;',
             'Open (F, In_File, \"data.txt\");',
             'while not End_Of_File (F) loop\n   Get_Line (F, Line);\n   Put_Line (Line);\nend loop;',
             'Create (F, Out_File, \"out.txt\");\nPut_Line (F, \"written line\");\nClose (F);',
         ]},
        {'slug': 'ada-16-tasking', 'title': 'Tasking and Concurrency', 'desc': 'Ada\'s native tasking model.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create task types', 'Use entries and accepts', 'Synchronize with protected objects', 'Avoid race conditions'],
         'prereq': ['Ada-15: File Input/Output'],
         'samples': [
             'task Worker is\n   entry Start;\nend Worker;\n\ntask body Worker is\nbegin\n   accept Start;\n   Put_Line (\"Working\");\nend Worker;',
             'task type Printer;\nP : Printer;',
             'protected Counter is\n   procedure Inc;\n   function Get return Integer;\nprivate\n   Value : Integer := 0;\nend Counter;',
             'select\n   accept Stop;\nelse\n   delay 1.0;\nend select;',
         ]},
        {'slug': 'ada-17-command-line', 'title': 'Command-Line Interfaces', 'desc': 'Parse arguments and build tools.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Read command-line arguments', 'Parse options', 'Return exit codes', 'Build a small CLI tool'],
         'prereq': ['Ada-16: Tasking and Concurrency'],
         'samples': [
             'with Ada.Command_Line;\nuse Ada.Command_Line;\nif Argument_Count = 0 then\n   Put_Line (\"Usage: tool FILE\");\nend if;',
             'Arg := Argument (1);',
             'Set_Exit_Status (1);',
             "for i in 1 .. Argument_Count loop\n   Put_Line (i'Image & \": \" & Argument (i));\nend loop;",
         ]},
        {'slug': 'ada-18-pragmas', 'title': 'Pragmas and Preconditions', 'desc': 'Compiler directives and contracts.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use common pragmas', 'Write preconditions', 'Write postconditions', 'Enable contract checking'],
         'prereq': ['Ada-17: Command-Line Interfaces'],
         'samples': [
             'pragma Assert (X > 0);',
             "procedure Deposit (Amount : in Integer)\n   with Pre => Amount > 0,\n        Post => Balance'Old + Amount = Balance;",
             'pragma Restrictions (No_Recursion);',
             'pragma Pure (Math_Utils);',
         ]},
        {'slug': 'ada-19-spark', 'title': 'SPARK and Formal Methods', 'desc': 'High-integrity subset with proof tools.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand SPARK subset rules', 'Annotate with contracts', 'Run proof tools', 'Write provable code'],
         'prereq': ['Ada-18: Pragmas and Preconditions'],
         'samples': [
             'pragma SPARK_Mode (On);',
             "procedure Increment (X : in out Integer)\n   with Pre  => X < Integer'Last,\n        Post => X = X'Old + 1;",
             'pragma Assert (X >= 0);',
             "function Max (A, B : Integer) return Integer\n   with Post => Max'Result >= A and Max'Result >= B;",
         ]},
        {'slug': 'ada-20-embedded', 'title': 'Embedded and Real-Time Ada', 'desc': 'Ravenscar profile and low-level control.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand Ravenscar profile', 'Use representation clauses', 'Map to hardware registers', 'Write interrupt handlers'],
         'prereq': ['Ada-19: SPARK and Formal Methods'],
         'samples': [
             'type Register is mod 2**32;\nReg : Register;',
             "for Reg'Address use System'To_Address (16#4000_0000#);",
             'pragma Restrictions (Max_Entries => 0);\n-- Ravenscar-style constraints',
             'procedure Handler is\nbegin\n   null;\nend Handler;\n-- attached via interrupt pragma',
         ]},
        {'slug': 'ada-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Alire, libraries, and production Ada.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use Alire package manager', 'Discover key libraries', 'Understand certification contexts', 'Find community resources'],
         'prereq': ['Ada-20: Embedded and Real-Time Ada'],
         'samples': [
             'alr init --bin my_project\ncd my_project && alr build',
             'alr search json   # find JSON libraries',
             'alr with libadalang --only',
             'gnatmake -gnatwa main.adb   # all warnings on',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# COBOL
# ────────────────────────────────────────────────────────────────────────────
COBOL = {
    'lang': 'cobol',
    'code_lang': 'cobol',
    'refs': [
        ('GnuCOBOL Manual', 'https://www.ibm.com/docs/en/cobol-zos/', 'IBM Enterprise COBOL documentation'),
        ('GnuCOBOL Documentation', 'https://gnucobol.sourceforge.io/', 'Open-source COBOL compiler'),
        ('COBOL Tutorial (TutorialsPoint)', 'https://www.tutorialspoint.com/cobol/index.htm', 'Beginner COBOL guide'),
    ],
    'lessons': [
        {'slug': 'cobol-01-getting-started', 'title': 'Getting Started with COBOL', 'desc': 'Divisions, identification, and hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Understand the four divisions', 'Write a hello world program', 'Compile with GnuCOBOL', 'Read simple COBOL output'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '       IDENTIFICATION DIVISION.\n       PROGRAM-ID. HELLO.\n       PROCEDURE DIVISION.\n           DISPLAY \"Hello, World!\".\n           STOP RUN.',
             'cobc -x hello.cob\n./hello',
             '       IDENTIFICATION DIVISION.\n       PROGRAM-ID. GREET.\n       PROCEDURE DIVISION.\n           DISPLAY \"Hello, \" WITH NO ADVANCING.\n           DISPLAY \"User!\".\n           STOP RUN.',
             '       IDENTIFICATION DIVISION.\n       PROGRAM-ID. FACTS.\n       PROCEDURE DIVISION.\n           DISPLAY \"COBOL: Common Business Oriented Language\".\n           STOP RUN.',
         ]},
        {'slug': 'cobol-02-divisions', 'title': 'The Four Divisions', 'desc': 'Identification, Environment, Data, and Procedure.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Structure the identification division', 'Set up the environment division', 'Declare the data division', 'Write the procedure division'],
         'prereq': ['COBOL-01: Getting Started with COBOL'],
         'samples': [
             '       IDENTIFICATION DIVISION.\n       PROGRAM-ID. DEMO.\n       ENVIRONMENT DIVISION.\n       DATA DIVISION.\n       PROCEDURE DIVISION.\n           STOP RUN.',
             '       DATA DIVISION.\n       WORKING-STORAGE SECTION.\n       01 WS-NAME PIC X(20).',
             '       PROCEDURE DIVISION.\n       MAIN-PARA.\n           DISPLAY \"Running\".\n           STOP RUN.',
             '       IDENTIFICATION DIVISION.\n       PROGRAM-ID. VERSION.\n       REMARKS. Sample program with comments.',
         ]},
        {'slug': 'cobol-03-data-types', 'title': 'Data Types and Pictures', 'desc': 'PIC clauses, USAGE, and level numbers.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Define PIC X and PIC 9 fields', 'Use USAGE clauses', 'Structure level numbers', 'Declare group items'],
         'prereq': ['COBOL-02: The Four Divisions'],
         'samples': [
             '       01 WS-NAME PIC X(30).\n       01 WS-AGE PIC 9(3).',
             '       01 WS-SALARY PIC 9(7)V99.\n       01 WS-RATE PIC S9(3)V99 COMP-3.',
             '       01 WS-EMPLOYEE.\n          05 WS-ID PIC 9(5).\n          05 WS-DEPT PIC X(10).',
             '       01 WS-FLAG PIC X VALUE \"N\".',
         ]},
        {'slug': 'cobol-04-move', 'title': 'MOVE and DISPLAY', 'desc': 'Data movement and output formatting.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Move values between fields', 'Display formatted output', 'Understand elementary moves', 'Initialize data with MOVE'],
         'prereq': ['COBOL-03: Data Types and Pictures'],
         'samples': [
             '           MOVE 25 TO WS-AGE.\n           DISPLAY \"Age: \" WS-AGE.',
             '           MOVE \"Hello\" TO WS-NAME.\n           DISPLAY WS-NAME.',
             '           MOVE SPACES TO WS-NAME.\n           MOVE ZEROES TO WS-COUNT.',
             '           MOVE WS-A TO WS-B.\n           DISPLAY WS-B.',
         ]},
        {'slug': 'cobol-05-arithmetic', 'title': 'Arithmetic Operations', 'desc': 'ADD, SUBTRACT, MULTIPLY, DIVIDE, COMPUTE.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use ADD and SUBTRACT', 'Use MULTIPLY and DIVIDE', 'Compute with COMPUTE', 'Handle ROUNDED and ON SIZE ERROR'],
         'prereq': ['COBOL-04: MOVE and DISPLAY'],
         'samples': [
             '           ADD 10 TO WS-TOTAL.\n           SUBTRACT 5 FROM WS-TOTAL.',
             '           MULTIPLY WS-A BY WS-B GIVING WS-C.',
             '           COMPUTE WS-TOTAL = WS-A + WS-B * 2.',
             '           ADD WS-A TO WS-B ROUNDED\n              ON SIZE ERROR DISPLAY \"Overflow\" END-ADD.',
         ]},
        {'slug': 'cobol-06-conditionals', 'title': 'IF and Evaluate', 'desc': 'Conditional logic and structured decisions.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write IF/ELSE branches', 'Use nested conditions', 'Use EVALUATE statements', 'Test conditions properly'],
         'prereq': ['COBOL-05: Arithmetic Operations'],
         'samples': [
             '           IF WS-AGE >= 18\n              DISPLAY \"Adult\"\n           ELSE\n              DISPLAY \"Minor\"\n           END-IF.',
             '           IF WS-GRADE = \"A\" AND WS-PASS = \"Y\"\n              DISPLAY \"Excellent\"\n           END-IF.',
             '           EVALUATE WS-OPTION\n              WHEN \"1\" DISPLAY \"One\"\n              WHEN \"2\" DISPLAY \"Two\"\n              WHEN OTHER DISPLAY \"Other\"\n           END-EVALUATE.',
             '           IF WS-NUM > 0\n              DISPLAY \"Positive\"\n           END-IF.',
         ]},
        {'slug': 'cobol-07-perform', 'title': 'PERFORM and Paragraphs', 'desc': 'Structured control flow and paragraphs.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Call paragraphs with PERFORM', 'Use PERFORM ... TIMES', 'Use PERFORM UNTIL', 'Structure program flow'],
         'prereq': ['COBOL-06: IF and Evaluate'],
         'samples': [
             '           PERFORM INIT-PARA.\n           PERFORM PROCESS-PARA.\n           STOP RUN.\n       INIT-PARA.\n           MOVE 0 TO WS-COUNT.',
             '           PERFORM DISPLAY-STEP 5 TIMES.',
             '           PERFORM UNTIL WS-DONE = \"Y\"\n              ADD 1 TO WS-COUNT\n           END-PERFORM.',
             '       MAIN-PARA.\n           PERFORM 1000-INIT\n           PERFORM 2000-PROCESS\n           PERFORM 9000-EXIT.\n           STOP RUN.',
         ]},
        {'slug': 'cobol-08-tables', 'title': 'Tables and Arrays', 'desc': 'OCCURS clauses and table processing.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define tables with OCCURS', 'Index and access elements', 'Iterate over tables', 'Use subscripting safely'],
         'prereq': ['COBOL-07: PERFORM and Paragraphs'],
         'samples': [
             '       01 WS-TABLE.\n          05 WS-ENTRY PIC 9(3) OCCURS 10 TIMES.',
             '           MOVE 5 TO WS-ENTRY(1).\n           DISPLAY WS-ENTRY(1).',
             '           PERFORM VARYING I FROM 1 BY 1 UNTIL I > 10\n              DISPLAY WS-ENTRY(I)\n           END-PERFORM.',
             '       01 WS-MATRIX.\n          05 WS-ROW OCCURS 3 TIMES.\n             10 WS-CELL PIC 9 OCCURS 3 TIMES.',
         ]},
        {'slug': 'cobol-09-strings', 'title': 'String Handling', 'desc': 'STRING, UNSTRING, and character manipulation.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Concatenate with STRING', 'Split with UNSTRING', 'Inspect characters', 'Handle delimiters'],
         'prereq': ['COBOL-08: Tables and Arrays'],
         'samples': [
             '           STRING WS-FIRST DELIMITED BY SPACE\n                  \" \" DELIMITED BY SIZE\n                  WS-LAST DELIMITED BY SPACE\n                  INTO WS-FULL END-STRING.',
             '           UNSTRING WS-DATA DELIMITED BY \",\"\n              INTO WS-A WS-B WS-C END-UNSTRING.',
             '           INSPECT WS-NAME TALLYING WS-CNT FOR CHARACTERS.',
             '           INSPECT WS-DATA REPLACING ALL \" \" BY \"-\".',
         ]},
        {'slug': 'cobol-10-file-io', 'title': 'Sequential File I/O', 'desc': 'Open, read, write, and close sequential files.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Declare file records in FD', 'Open files in modes', 'Read and write records', 'Detect end of file'],
         'prereq': ['COBOL-09: String Handling'],
         'samples': [
             '       FD WS-FILE.\n       01 WS-REC PIC X(80).',
             '           OPEN INPUT WS-FILE.\n           OPEN OUTPUT WS-OUTFILE.',
             '           READ WS-FILE\n              AT END SET WS-EOF TO TRUE\n           END-READ.',
             '           WRITE WS-OUTREC.\n           CLOSE WS-FILE.',
         ]},
        {'slug': 'cobol-11-sort', 'title': 'Sorting Data', 'desc': 'SORT verb and file sorting.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use the SORT verb', 'Define sort keys', 'Merge with MERGE', 'Process sorted output'],
         'prereq': ['COBOL-10: Sequential File I/O'],
         'samples': [
             '           SORT WS-SORTFILE ON ASCENDING KEY WS-KEY\n              USING WS-INPUT GIVING WS-OUTPUT.',
             '           SORT WS-FILE ON DESCENDING KEY WS-SALARY.',
             '           MERGE WS-MERGE-FILE ON ASCENDING KEY WS-ID\n              USING WS-FILE1 WS-FILE2\n              GIVING WS-OUT.',
             '       SORT-FILE-PARA.\n           SORT WS-SORTFILE ON ASCENDING KEY WS-NAME\n              INPUT PROCEDURE IN-PARA\n              OUTPUT PROCEDURE OUT-PARA.',
         ]},
        {'slug': 'cobol-12-copybooks', 'title': 'Copybooks and Modularity', 'desc': 'COPY statements and shared data definitions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use COPY statements', 'Structure copybooks', 'Replace text with REPLACING', 'Share record layouts'],
         'prereq': ['COBOL-11: Sorting Data'],
         'samples': [
             '           COPY CUST-RECORD.',
             '           COPY CUST-RECORD REPLACING CUSTOMER BY VENDOR.',
             '       *  COPYBOOK: CUST-RECORD\n       01 CUSTOMER.\n          05 CUST-ID PIC 9(6).',
             '       DATA DIVISION.\n       WORKING-STORAGE SECTION.\n           COPY CUST-RECORD.',
         ]},
        {'slug': 'cobol-13-subprograms', 'title': 'Subprograms and CALL', 'desc': 'CALL statements and linkage sections.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write called subprograms', 'Pass data via LINKAGE', 'Use CALL and USING', 'Return control properly'],
         'prereq': ['COBOL-12: Copybooks and Modularity'],
         'samples': [
             '       IDENTIFICATION DIVISION.\n       PROGRAM-ID. UTILITY.\n       DATA DIVISION.\n       LINKAGE SECTION.\n       01 LS-NUM PIC 9(3).',
             '           CALL \"UTILITY\" USING WS-NUM.',
             '           CALL \"UTILITY\" USING BY REFERENCE WS-NUM,\n                BY CONTENT WS-OTHER.',
             '       PROCEDURE DIVISION USING LS-NUM.\n           ADD 1 TO LS-NUM.\n           GOBACK.',
         ]},
        {'slug': 'cobol-14-indexed-files', 'title': 'Indexed and Relative Files', 'desc': 'Random access file organizations.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Declare indexed files', 'Read by key', 'Write and rewrite records', 'Handle record status'],
         'prereq': ['COBOL-13: Subprograms and CALL'],
         'samples': [
             '       SELECT WS-FILE ASSIGN TO \"data.dat\"\n              ORGANIZATION IS INDEXED\n              ACCESS MODE IS DYNAMIC\n              RECORD KEY IS WS-KEY.',
             '           READ WS-FILE KEY IS WS-KEY\n              INVALID KEY DISPLAY \"Not found\"\n           END-READ.',
             '           WRITE WS-REC\n              INVALID KEY DISPLAY \"Duplicate\"\n           END-WRITE.',
             '           REWRITE WS-REC.',
         ]},
        {'slug': 'cobol-15-reporting', 'title': 'Report Writing', 'desc': 'REPORT SECTION and report generation.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Define report groups', 'Generate headers and footers', 'Accumulate control totals', 'Produce formatted reports'],
         'prereq': ['COBOL-14: Indexed and Relative Files'],
         'samples': [
             '       FD WS-REPORT.\n       REPORT SECTION.\n       RD WS-RPT.\n       01 HEADING-LINE.\n          05 PIC X(30) VALUE \"SALES REPORT\".',
             '       REPORT SECTION.\n       RD WS-RPT CONTROL IS WS-DEPT.\n       01 DETAIL-LINE.\n          05 WS-DEPT-COL PIC X(10).',
             '       INITIATE WS-RPT.\n       GENERATE DETAIL-LINE.\n       TERMINATE WS-RPT.',
             '       01 FOOTING-LINE.\n          05 PIC X(10) VALUE \"TOTAL:\".\n          05 WS-TOTAL-COL PIC Z(9).',
         ]},
        {'slug': 'cobol-16-database', 'title': 'Database Access (SQL/DB2)', 'desc': 'Embedded SQL in COBOL.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Embed SQL statements', 'Declare host variables', 'Process query results', 'Handle SQL errors'],
         'prereq': ['COBOL-15: Report Writing'],
         'samples': [
             '       EXEC SQL\n          SELECT NAME INTO :WS-NAME FROM EMP\n          WHERE ID = :WS-ID\n       END-EXEC.',
             '           EXEC SQL\n              INSERT INTO EMP (ID, NAME)\n              VALUES (:WS-ID, :WS-NAME)\n           END-EXEC.',
             '       EXEC SQL\n          DECLARE C1 CURSOR FOR SELECT * FROM EMP\n       END-EXEC.',
             '           EXEC SQL WHENEVER SQLERROR\n              PERFORM SQL-ERROR-PARA\n           END-EXEC.',
         ]},
        {'slug': 'cobol-17-debugging', 'title': 'Debugging COBOL', 'desc': 'DISPLAY tracing and testing strategies.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Trace with DISPLAY statements', 'Use DEBUG clauses', 'Write test programs', 'Diagnose numeric issues'],
         'prereq': ['COBOL-16: Database Access (SQL/DB2)'],
         'samples': [
             '           DISPLAY \"VALUE: \" WS-NUM UPON CONSOLE.',
             '       PROCEDURE DIVISION.\n       DEBUG-SECTION.\n           USE FOR DEBUGGING ON WS-FIELD.',
             '           IF WS-NUM = 0\n              DISPLAY \"DIVISION BY ZERO GUARD\"\n           END-IF.',
             '           DISPLAY WS-EMP-ID \" \" WS-NAME.',
         ]},
        {'slug': 'cobol-18-performance', 'title': 'Performance and Optimization', 'desc': 'Efficient table and file processing.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Optimize table searches', 'Use binary search', 'Minimize I/O', 'Use compiler options'],
         'prereq': ['COBOL-17: Debugging COBOL'],
         'samples': [
             '           SEARCH ALL WS-TABLE\n              AT END DISPLAY \"Not found\"\n              WHEN WS-KEY(WS-IDX) = WS-TARGET\n                 DISPLAY \"Found\"\n           END-SEARCH.',
             '           PERFORM VARYING I FROM 1 BY 1\n              UNTIL I > WS-MAX OR WS-FOUND = \"Y\"\n           END-PERFORM.',
             '           MOVE 0 TO WS-COUNTER.\n           PERFORM UNTIL WS-COUNTER > 1000\n              ADD 1 TO WS-COUNTER\n           END-PERFORM.',
             '       *  compiler: cobc -O2 program.cob',
         ]},
        {'slug': 'cobol-19-y2k-era', 'title': 'Modern COBOL Practices', 'desc': 'Date handling and modern standards.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Handle dates with proper formats', 'Use modern standards', 'Integrate with JSON/XML', 'Write maintainable COBOL'],
         'prereq': ['COBOL-18: Performance and Optimization'],
         'samples': [
             '       01 WS-DATE PIC 9(8).\n           MOVE FUNCTION CURRENT-DATE TO WS-DATE.',
             '       01 WS-TODAY.\n          05 WS-YEAR PIC 9(4).\n          05 WS-MONTH PIC 99.\n          05 WS-DAY PIC 99.',
             '           MOVE FUNCTION CURRENT-DATE(1:8) TO WS-DATE.',
             '       *  keep comments and structure clear',
         ]},
        {'slug': 'cobol-20-mainframe', 'title': 'Mainframe and z/OS COBOL', 'desc': 'JCL, datasets, and enterprise integration.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand JCL structure', 'Compile on z/OS', 'Use VSAM datasets', 'Integrate with CICS'],
         'prereq': ['COBOL-19: Modern COBOL Practices'],
         'samples': [
             '//JOB1 JOB (ACCT),CLASS=A,MSGCLASS=H\n//STEP1 EXEC PGM=MYPROG',
             '//DD1 DD DSN=MY.DATA.SET,DISP=SHR',
             '       EXEC CICS\n          SEND TEXT FROM(WS-MSG)\n       END-EXEC.',
             '//STEP1 EXEC PGM=IGYCRCTL\n//SYSIN DD DSN=SRC.COBOL(MYPROG),DISP=SHR',
         ]},
        {'slug': 'cobol-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Legacy modernization and career paths.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Understand modernization options', 'Know COBOL market demand', 'Interop with modern languages', 'Find community resources'],
         'prereq': ['COBOL-20: Mainframe and z/OS COBOL'],
         'samples': [
             '       CALL \"MODERNIZER\" USING WS-DATA.',
             '       *  wrap legacy logic behind modern APIs',
             '       *  convert: COBOL -> Java via transpilers',
             '       DISPLAY \"COBOL still runs 70% of transactions\".',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# FORTRAN
# ────────────────────────────────────────────────────────────────────────────
FORTRAN = {
    'lang': 'fortran',
    'code_lang': 'fortran',
    'refs': [
        ('Fortran 90/95 Standard', 'https://wg5-fortran.org/', 'The official standards committee'),
        ('Fortran Best Practices', 'https://fortran-lang.org/en/learn/', 'fortran-lang.org learning resources'),
        ('Modern Fortran Explained', 'https://www.oxford.universitypressscholarship.com/', 'Metcalf, Reid & Cohen textbook'),
    ],
    'lessons': [
        {'slug': 'fortran-01-getting-started', 'title': 'Getting Started with Fortran', 'desc': 'Modern Fortran, compiler setup, hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install a Fortran compiler', 'Write free-form Fortran', 'Compile and run programs', 'Use print and read'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'program hello\n  print *, "Hello, World!"\nend program hello',
             'gfortran hello.f90 -o hello\n./hello',
             'program greet\n  character(len=20) :: name\n  print *, "Enter your name:"\n  read *, name\n  print *, "Hello, ", trim(name)\nend program greet',
             'program math\n  print *, 2 + 3, " is the answer"\nend program math',
         ]},
        {'slug': 'fortran-02-declarations', 'title': 'Variables and Declarations', 'desc': 'Implicit typing, kinds, and declarations.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare variables with types', 'Use integer and real kinds', 'Declare parameters with parameter', 'Turn off implicit typing'],
         'prereq': ['Fortran-01: Getting Started with Fortran'],
         'samples': [
             'program vars\n  implicit none\n  integer :: i\n  real :: x\nend program vars',
             'program kinds\n  implicit none\n  integer, parameter :: dp = selected_real_kind(15, 307)\n  real(kind=dp) :: pi\nend program kinds',
             'program consts\n  implicit none\n  real, parameter :: pi = 3.14159265\n  print *, pi\nend program consts',
             'program init\n  implicit none\n  integer :: count = 0\n  real :: total = 0.0\nend program init',
         ]},
        {'slug': 'fortran-03-operators', 'title': 'Operators and Expressions', 'desc': 'Arithmetic, relational, and logical operators.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use arithmetic operators', 'Compare values relationally', 'Combine logical expressions', 'Handle integer division'],
         'prereq': ['Fortran-02: Variables and Declarations'],
         'samples': [
             'program arith\n  implicit none\n  integer :: a, b\n  a = 7; b = 2\n  print *, a + b, a - b, a * b, a / b, mod(a, b)\nend program arith',
             'program realdiv\n  implicit none\n  print *, 7.0 / 2.0\nend program realdiv',
             'program compare\n  implicit none\n  integer :: x = 5\n  print *, x > 3, x <= 5\nend program compare',
             'program logic\n  implicit none\n  logical :: flag = .true.\n  print *, flag .and. .not. flag\nend program logic',
         ]},
        {'slug': 'fortran-04-control', 'title': 'Control Flow', 'desc': 'if, select case, and structured flow.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/else if/else blocks', 'Use select case', 'Use named constructs', 'Guard with logical conditions'],
         'prereq': ['Fortran-03: Operators and Expressions'],
         'samples': [
             'program grade\n  implicit none\n  integer :: score\n  score = 85\n  if (score >= 90) then\n    print *, "A"\n  else if (score >= 80) then\n    print *, "B"\n  else\n    print *, "C"\n  end if\nend program grade',
             'program select\n  implicit none\n  integer :: n\n  n = 2\n  select case (n)\n  case (1)\n    print *, "one"\n  case (2)\n    print *, "two"\n  case default\n    print *, "other"\n  end select\nend program select',
             'if (x > 0 .and. y > 0) then\n  print *, "both positive"\nend if',
             'named: if (flag) then\n  print *, "flagged"\nend if named',
         ]},
        {'slug': 'fortran-05-loops', 'title': 'Loops', 'desc': 'do loops, while forms, and iteration control.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write do loops with ranges', 'Use implied loops', 'Control with exit and cycle', 'Loop over arrays'],
         'prereq': ['Fortran-04: Control Flow'],
         'samples': [
             'program sum\n  implicit none\n  integer :: i, total\n  total = 0\n  do i = 1, 10\n    total = total + i\n  end do\n  print *, total\nend program sum',
             'do i = 10, 1, -1\n  print *, i\nend do',
             'do\n  if (done) exit\nend do',
             'do i = 1, 10\n  if (mod(i, 2) == 0) cycle\n  print *, i\nend do',
         ]},
        {'slug': 'fortran-06-arrays', 'title': 'Arrays', 'desc': 'Array declaration, slicing, and array operations.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Declare 1-D and 2-D arrays', 'Slice array sections', 'Use array constructors', 'Apply whole-array operations'],
         'prereq': ['Fortran-05: Loops'],
         'samples': [
             'program arr\n  implicit none\n  integer, dimension(5) :: v\n  v = (/ 1, 2, 3, 4, 5 /)\n  print *, v\nend program arr',
             'real, dimension(3, 3) :: m\nm = 0.0',
             'integer :: a(10)\na(1:5) = 1\na(6:10) = 2',
             'print *, sum(v), maxval(v), minval(v)',
         ]},
        {'slug': 'fortran-07-strings', 'title': 'Character Strings', 'desc': 'Character variables, concatenation, and intrinsics.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Declare character variables', 'Concatenate with //', 'Use trim, len, adjustl', 'Compare strings'],
         'prereq': ['Fortran-06: Arrays'],
         'samples': [
             'program str\n  implicit none\n  character(len=20) :: name = "Ada"\n  print *, name\nend program str',
             'character(len=50) :: full\nfull = "Hello" // " " // "World"',
             'print *, trim("  padded  ")\nprint *, len("hello")',
             'if (trim(a) == trim(b)) then\n  print *, "equal"\nend if',
         ]},
        {'slug': 'fortran-08-functions', 'title': 'Functions', 'desc': 'Write and call functions with intent.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write functions', 'Use intent(in) arguments', 'Return values properly', 'Call intrinsic functions'],
         'prereq': ['Fortran-07: Character Strings'],
         'samples': [
             'program use_f\n  implicit none\n  print *, add(2, 3)\ncontains\n  integer function add(a, b)\n    integer, intent(in) :: a, b\n    add = a + b\n  end function add\nend program use_f',
             'real function area(r)\n  real, intent(in) :: r\n  real, parameter :: pi = 3.14159\n  area = pi * r * r\nend function area',
             'integer function fact(n)\n  integer, intent(in) :: n\n  integer :: i\n  fact = 1\n  do i = 2, n\n    fact = fact * i\n  end do\nend function fact',
             'print *, abs(-5), sqrt(16.0), nint(3.7)',
         ]},
        {'slug': 'fortran-09-subroutines', 'title': 'Subroutines', 'desc': 'Procedures with multiple outputs.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write subroutines', 'Use intent(inout) arguments', 'Call by reference semantics', 'Structure programs with procedures'],
         'prereq': ['Fortran-08: Functions'],
         'samples': [
             'program use_s\n  implicit none\n  integer :: x, y\n  x = 1; y = 2\n  call swap(x, y)\n  print *, x, y\ncontains\n  subroutine swap(a, b)\n    integer, intent(inout) :: a, b\n    integer :: t\n    t = a; a = b; b = t\n  end subroutine swap\nend program use_s',
             'subroutine stats(v, n, mean, std)\n  integer, intent(in) :: n\n  real, intent(in) :: v(n)\n  real, intent(out) :: mean, std\n  mean = sum(v) / n\n  std = sqrt(sum((v - mean)**2) / n)\nend subroutine stats',
             'call init(data)\ncall process(data)\ncall finalize(data)',
             'subroutine report(x, y)\n  integer, intent(in) :: x\n  integer, intent(out) :: y\n  y = x * 2\nend subroutine report',
         ]},
        {'slug': 'fortran-10-modules', 'title': 'Modules', 'desc': 'Module encapsulation and interfaces.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Write modules', 'Use public/private access', 'Import with use', 'Share constants'],
         'prereq': ['Fortran-09: Subroutines'],
         'samples': [
             'module math_utils\n  implicit none\n  real, parameter :: pi = 3.14159\ncontains\n  real function area(r)\n    real, intent(in) :: r\n    area = pi * r * r\n  end function area\nend module math_utils\n\nprogram main\n  use math_utils\n  implicit none\n  print *, area(2.0)\nend program main',
             'module config\n  implicit none\n  integer, parameter :: max_size = 1000\n  private\n  public :: max_size\nend module config',
             'module types\n  implicit none\n  type :: point\n    real :: x, y\n  end type point\nend module types',
             'use math_utils, only: pi',
         ]},
        {'slug': 'fortran-11-derived-types', 'title': 'Derived Types', 'desc': 'Structures and user-defined data.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define derived types', 'Access components', 'Initialize derived values', 'Pass derived types to procedures'],
         'prereq': ['Fortran-10: Modules'],
         'samples': [
             'type :: person\n  character(len=30) :: name\n  integer :: age\nend type person',
             'type(person) :: p\np%name = "Ada"\np%age = 36',
             'type(point) :: origin = point(0.0, 0.0)',
             'subroutine show(p)\n  type(person), intent(in) :: p\n  print *, p%name, p%age\nend subroutine show',
         ]},
        {'slug': 'fortran-12-io', 'title': 'File Input/Output', 'desc': 'Read and write files with formatting.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Open files with open', 'Read and write formatted data', 'Use format statements', 'Handle iostat errors'],
         'prereq': ['Fortran-11: Derived Types'],
         'samples': [
             'program fileio\n  implicit none\n  integer :: unit, ios\n  open(newunit=unit, file="data.txt", status="old", action="read", iostat=ios)\n  if (ios /= 0) print *, "Error opening"\n  close(unit)\nend program fileio',
             'write(unit, *) "hello"\nwrite(unit, "(I5)") 42',
             'read(unit, *, iostat=ios) x\nif (ios /= 0) print *, "Read failed"',
             'open(10, file="out.txt")\nwrite(10, "(A, I3)") "count=", 7\nclose(10)',
         ]},
        {'slug': 'fortran-13-intrinsics', 'title': 'Intrinsic Functions', 'desc': 'Mathematical and array intrinsics.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use math intrinsics', 'Use array reduction intrinsics', 'Use dot_product and matmul', 'Find array locations'],
         'prereq': ['Fortran-12: File Input/Output'],
         'samples': [
             'print *, exp(1.0), log(2.0), sin(0.5)',
             'print *, sum(a), product(a), maxval(a), minval(a)',
             'dot = dot_product(u, v)\nmat = matmul(a, b)',
             'idx = maxloc(a, 1)\nprint *, "max at", idx',
         ]},
        {'slug': 'fortran-14-allocation', 'title': 'Dynamic Allocation', 'desc': 'allocatable arrays and pointers.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Declare allocatable arrays', 'Allocate and deallocate', 'Use move_alloc', 'Check allocation status'],
         'prereq': ['Fortran-13: Intrinsic Functions'],
         'samples': [
             'integer, allocatable :: a(:)\nallocate(a(10))\na = 0\ndeallocate(a)',
             'integer, allocatable :: m(:,:)\nallocate(m(3, 3))',
             'if (allocated(a)) then\n  deallocate(a)\nend if',
             'allocate(a(100))\nallocate(b(200))\nb = a\ncall move_alloc(b, a)',
         ]},
        {'slug': 'fortran-15-pointers', 'title': 'Pointers', 'desc': 'Pointer association and targets.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Declare pointers', 'Associate with targets', 'Use pointer arrays', 'Nullify pointers'],
         'prereq': ['Fortran-14: Dynamic Allocation'],
         'samples': [
             'integer, target :: x\ninteger, pointer :: p\np => x',
             'p => null()\nif (associated(p)) then\n  print *, "associated"\nend if',
             'integer, pointer :: row(:)\nrow => matrix(:, 2)',
             'real, pointer :: list(:)\nallocate(list(10))',
         ]},
        {'slug': 'fortran-16-oop', 'title': 'Object-Oriented Fortran', 'desc': 'Type-bound procedures and inheritance.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Bind procedures to types', 'Use inheritance', 'Write generic interfaces', 'Use class polymorphism'],
         'prereq': ['Fortran-15: Pointers'],
         'samples': [
             'type :: shape\n  real :: area\ncontains\n  procedure :: compute => shape_compute\nend type shape',
             'type, extends(shape) :: circle\n  real :: radius\nend type circle',
             'interface area\n  module procedure area_circle, area_square\nend interface',
             'class(shape), allocatable :: s\nallocate(circle :: s)',
         ]},
        {'slug': 'fortran-17-parallel', 'title': 'Parallel Programming with OpenMP', 'desc': 'OpenMP directives for shared-memory parallelism.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use omp parallel regions', 'Parallelize loops', 'Use reduction clauses', 'Manage shared/private vars'],
         'prereq': ['Fortran-16: Object-Oriented Fortran'],
         'samples': [
             'program par\n  use omp_lib\n  implicit none\n  !$omp parallel\n  print *, "hello from thread", omp_get_thread_num()\n  !$omp end parallel\nend program par',
             '!$omp parallel do\n  do i = 1, 1000\n    a(i) = i * i\n  end do\n!$omp end parallel do',
             '!$omp parallel do reduction(+:total)\n  do i = 1, 100\n    total = total + a(i)\n  end do\n!$omp end parallel do',
             '!$omp critical\n  counter = counter + 1\n!$omp end critical',
         ]},
        {'slug': 'fortran-18-mpi', 'title': 'MPI for Distributed Computing', 'desc': 'Message passing for clusters.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Initialize MPI', 'Rank and size basics', 'Send and receive messages', 'Use collective operations'],
         'prereq': ['Fortran-17: Parallel Programming with OpenMP'],
         'samples': [
             'program mpi_hello\n  use mpi\n  implicit none\n  integer :: ierr, rank, size\n  call MPI_INIT(ierr)\n  call MPI_COMM_RANK(MPI_COMM_WORLD, rank, ierr)\n  call MPI_COMM_SIZE(MPI_COMM_WORLD, size, ierr)\n  print *, "rank", rank, "of", size\n  call MPI_FINALIZE(ierr)\nend program mpi_hello',
             'call MPI_SEND(data, n, MPI_DOUBLE_PRECISION, 1, 0, MPI_COMM_WORLD, ierr)',
             'call MPI_RECV(data, n, MPI_DOUBLE_PRECISION, 0, 0, MPI_COMM_WORLD, status, ierr)',
             'call MPI_BARRIER(MPI_COMM_WORLD, ierr)\ncall MPI_BCAST(x, 1, MPI_INTEGER, 0, MPI_COMM_WORLD, ierr)',
         ]},
        {'slug': 'fortran-19-performance', 'title': 'Performance and Optimization', 'desc': 'Vectorization, alignment, and profiling.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Enable compiler optimizations', 'Write vectorizable loops', 'Use contiguous arrays', 'Profile and benchmark'],
         'prereq': ['Fortran-18: MPI for Distributed Computing'],
         'samples': [
             '! compile: gfortran -O3 -march=native app.f90',
             'real, dimension(:), contiguous :: v\n! contiguous guarantees tight layout',
             'do i = 1, n\n  a(i) = b(i) * c(i)   ! vectorizable\nend do',
             'call system_clock(t1)\n! ... work ...\ncall system_clock(t2)\nprint *, "time:", (t2 - t1) / 1000.0',
         ]},
        {'slug': 'fortran-20-scientific', 'title': 'Scientific Computing Patterns', 'desc': 'Linear algebra, numerics, and LAPACK.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use LAPACK routines', 'Solve linear systems', 'Compute eigenvalues', 'Handle precision issues'],
         'prereq': ['Fortran-19: Performance and Optimization'],
         'samples': [
             'call dgesv(n, nrhs, a, lda, ipiv, b, ldb, info)',
             'call dgemm(\'N\', \'N\', m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)',
             'call dsyev(\'V\', \'U\', n, a, lda, w, work, lwork, info)',
             'real(kind=dp), parameter :: eps = 1.0e-15_dp\nif (abs(x) < eps) print *, "near zero"',
         ]},
        {'slug': 'fortran-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Modern tooling and the Fortran community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use fpm package manager', 'Discover modern libraries', 'Use Fortran stdlib', 'Contribute to the community'],
         'prereq': ['Fortran-20: Scientific Computing Patterns'],
         'samples': [
             'fpm new my_project\ncd my_project && fpm run',
             'fpm add stdlib',
             'use stdlib_strings, only: to_string\nprint *, "n=" // to_string(42)',
             'fpm test   # run the test suite',
         ]},
    ],
}

SPECS = [SHELL, ADA, COBOL, FORTRAN]
