#!/usr/bin/env python3
"""Lesson specs for scratch, v, webassembly, wolfram-language — real 21-lesson courses."""

# ────────────────────────────────────────────────────────────────────────────
# SCRATCH
# ────────────────────────────────────────────────────────────────────────────
SCRATCH = {
    'lang': 'scratch',
    'code_lang': 'text',
    'refs': [
        ('Scratch Wiki', 'https://en.scratch-wiki.info/', 'The official wiki'),
        ('Scratch Documentation', 'https://scratch.mit.edu/', 'Official site'),
        ('Scratch Forums', 'https://scratch.mit.edu/discuss/', 'Community forum'),
    ],
    'lessons': [
        {'slug': 'scratch-01-getting-started', 'title': 'Getting Started with Scratch', 'desc': 'The editor, sprites, and your first project.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Navigate the Scratch editor', 'Understand the stage', 'Add sprites', 'Run a project'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '# Blocks: Events > When green flag clicked\n# Motion > Move 10 steps\n# Run: press the green flag',
             '# Motion > glide 1 secs to x: 0 y: 0',
             '# Looks > say Hello! for 2 seconds',
             '# Control > wait 1 seconds',
         ]},
        {'slug': 'scratch-02-motion', 'title': 'Motion Blocks', 'desc': 'Move sprites on the stage.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Move sprites', 'Point in directions', 'Use glide blocks', 'Change x and y'],
         'prereq': ['Scratch-01: Getting Started with Scratch'],
         'samples': [
             '# Motion > move 10 steps\n# Motion > turn clockwise 15 degrees',
             '# Motion > go to x: 0 y: 0',
             '# Motion > glide 1 secs to random position',
             '# Motion > change x by 10\n# Motion > change y by -10',
         ]},
        {'slug': 'scratch-03-looks', 'title': 'Looks and Costumes', 'desc': 'Appearance and animations.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Switch costumes', 'Say and think', 'Change effects', 'Show and hide'],
         'prereq': ['Scratch-02: Motion Blocks'],
         'samples': [
             '# Looks > switch costume to costume2\n# Looks > next costume',
             '# Looks > say Hello! for 2 seconds',
             '# Looks > change color effect by 25',
             '# Looks > show\n# Looks > hide',
         ]},
        {'slug': 'scratch-04-events', 'title': 'Events', 'desc': 'Trigger scripts with events.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use event blocks', 'Broadcast messages', 'Receive broadcasts', 'Trigger on keys'],
         'prereq': ['Scratch-03: Looks and Costumes'],
         'samples': [
             '# Events > when green flag clicked',
             '# Events > broadcast message1',
             '# Events > when I receive message1',
             '# Events > when space key pressed',
         ]},
        {'slug': 'scratch-05-control', 'title': 'Control Blocks', 'desc': 'Loops and conditionals.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use forever loops', 'Use repeat loops', 'Use if blocks', 'Use wait blocks'],
         'prereq': ['Scratch-04: Events'],
         'samples': [
             '# Control > forever\n# Motion > move 10 steps',
             '# Control > repeat 10\n# Motion > move 10 steps',
             '# Control > if <touching edge?> then\n# Motion > bounce if on edge',
             '# Control > wait 1 seconds',
         ]},
        {'slug': 'scratch-06-sensing', 'title': 'Sensing Blocks', 'desc': 'Detect input and collisions.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Sense touching', 'Use key pressed', 'Ask and answer', 'Detect distance'],
         'prereq': ['Scratch-05: Control Blocks'],
         'samples': [
             '# Sensing > touching sprite1?',
             '# Sensing > key space pressed?',
             '# Sensing > ask What is your name? and wait\n# Sensing > answer',
             '# Sensing > distance to mouse-pointer',
         ]},
        {'slug': 'scratch-07-operators', 'title': 'Operators', 'desc': 'Math and logic blocks.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use arithmetic operators', 'Use comparison operators', 'Combine with and/or', 'Use random numbers'],
         'prereq': ['Scratch-06: Sensing Blocks'],
         'samples': [
             '# Operators > () + ()\n# Operators > () * ()',
             '# Operators > () > ()\n# Operators > () = ()',
             '# Operators > <(a) and (b)>',
             '# Operators > pick random 1 to 10',
         ]},
        {'slug': 'scratch-08-variables', 'title': 'Variables', 'desc': 'Store and change data.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create variables', 'Change variables', 'Show variables', 'Use variable conditions'],
         'prereq': ['Scratch-07: Operators'],
         'samples': [
             '# Variables > make a variable: score\n# Variables > set score to 0',
             '# Variables > change score by 1',
             '# Show the variable on stage (checkbox)',
             '# Control > if <(score) > (10)> then',
         ]},
        {'slug': 'scratch-09-lists', 'title': 'Lists', 'desc': 'Store collections of data.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create lists', 'Add items', 'Delete items', 'Read items'],
         'prereq': ['Scratch-08: Variables'],
         'samples': [
             '# Variables > make a list: inventory\n# Variables > add apple to inventory',
             '# Variables > delete 1 of inventory',
             '# Variables > item 1 of inventory',
             '# Variables > length of inventory',
         ]},
        {'slug': 'scratch-10-sound', 'title': 'Sound Blocks', 'desc': 'Play sounds and music.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Play sounds', 'Use drum beats', 'Use note blocks', 'Control volume'],
         'prereq': ['Scratch-09: Lists'],
         'samples': [
             '# Sound > play sound meow until done',
             '# Sound > play drum (1) Snare Drum for 0.25 beats',
             '# Sound > play note 60 for 0.5 beats',
             '# Sound > change volume by -10',
         ]},
        {'slug': 'scratch-11-pen', 'title': 'Pen and Drawing', 'desc': 'Draw on the stage.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use pen blocks', 'Change pen color', 'Clear the stage', 'Draw shapes'],
         'prereq': ['Scratch-10: Sound Blocks'],
         'samples': [
             '# Pen > pen down\n# Motion > move 100 steps',
             '# Pen > set pen color to ()',
             '# Pen > clear',
             '# Repeat 4: move 100 steps, turn 90 degrees — draws a square',
         ]},
        {'slug': 'scratch-12-custom-blocks', 'title': 'Custom Blocks', 'desc': 'Build reusable procedures.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create custom blocks', 'Pass inputs', 'Use block definitions', 'Organize code'],
         'prereq': ['Scratch-11: Pen and Drawing'],
         'samples': [
             '# My Blocks > Make a Block: jump\n# Define jump: repeat 2: change y by 10, change y by -10',
             '# Call jump in other scripts',
             '# Make a Block: draw square with side length\n# Use input in the definition',
             '# Run without screen refresh for instant execution',
         ]},
        {'slug': 'scratch-13-clones', 'title': 'Clones', 'desc': 'Duplicate sprites dynamically.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Create clones', 'Start as clone', 'Delete clones', 'Use clone events'],
         'prereq': ['Scratch-12: Custom Blocks'],
         'samples': [
             '# Control > create clone of myself',
             '# Control > when I start as a clone',
             '# Control > delete this clone',
             '# Make a clone for every bullet fired',
         ]},
        {'slug': 'scratch-14-games', 'title': 'Build a Game: Catcher', 'desc': 'A complete catch game.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Design a game loop', 'Control a paddle', 'Spawn falling items', 'Track score'],
         'prereq': ['Scratch-13: Clones'],
         'samples': [
             '# Player: follow mouse-pointer with paddle sprite',
             '# Items: repeat forever, create clone, move down',
             '# Clones: if touching player, add 1 to score, delete clone',
             '# Game over: if lives = 0, stop all',
         ]},
        {'slug': 'scratch-15-platformer', 'title': 'Build a Platformer', 'desc': 'Jumping and scrolling.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Implement gravity', 'Detect ground', 'Add jumping', 'Handle scroll'],
         'prereq': ['Scratch-14: Build a Game: Catcher'],
         'samples': [
             '# Gravity: forever change y by -5',
             '# Jump: if space pressed and on ground, set jump velocity',
             '# Ground check: if touching platform, stop falling',
             '# Camera: move the world sprites, not the player',
         ]},
        {'slug': 'scratch-16-quiz', 'title': 'Build a Quiz App', 'desc': 'Interactive quizzes.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Ask questions', 'Check answers', 'Keep score', 'Provide feedback'],
         'prereq': ['Scratch-15: Build a Platformer'],
         'samples': [
             '# Ask: ask "What is 2+2?" and wait',
             '# Check: if answer = 4 then say Correct else say Try again',
             '# Score: change score by 1 when correct',
             '# Repeat questions from a list',
         ]},
        {'slug': 'scratch-17-extensions', 'title': 'Extensions', 'desc': 'Video, text-to-speech, and more.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Add extensions', 'Use text-to-speech', 'Use video sensing', 'Use translate'],
         'prereq': ['Scratch-16: Build a Quiz App'],
         'samples': [
             '# Extensions > Text to Speech\n# TTS > speak Hello',
             '# Extensions > Video Sensing\n# Video > video motion on sprite1?',
             '# Extensions > Translate\n# Translate > translate Hello to Spanish',
             '# Extensions > Music — play instruments',
         ]},
        {'slug': 'scratch-18-debugging', 'title': 'Debugging', 'desc': 'Find and fix bugs.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Single-step with wait blocks', 'Show variables', 'Test edge cases', 'Isolate problems'],
         'prereq': ['Scratch-17: Extensions'],
         'samples': [
             '# Add wait 0.1 seconds in forever loops to slow execution',
             '# Check variable values with show (checkbox)',
             '# Test: what happens at the edges of the stage?',
             '# Comment blocks (# add comment) to document intent',
         ]},
        {'slug': 'scratch-19-remix', 'title': 'Remixing and Sharing', 'desc': 'Collaborate on the Scratch site.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Remix projects', 'Share projects', 'Follow the community rules', 'Credit remixes'],
         'prereq': ['Scratch-18: Debugging'],
         'samples': [
             '# Click See inside on any project to remix it',
             '# Click Share to publish your project',
             '# Add notes and credits in the instructions box',
             '# Respect: remix with attribution',
         ]},
        {'slug': 'scratch-20-advanced-projects', 'title': 'Advanced Project Ideas', 'desc': 'Push Scratch further.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Build simulations', 'Create art generators', 'Build music tools', 'Make complex games'],
         'prereq': ['Scratch-19: Remixing and Sharing'],
         'samples': [
             '# Gravity simulator: balls with velocity and bounce',
             '# Art: pen drawing with random colors on keypress',
             '# Music: sequence notes from a list',
             '# RPG: sprites, hp variables, battles, and story',
         ]},
        {'slug': 'scratch-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Beyond Scratch.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Understand Scratch extensions', 'Try Scratch 3.0 features', 'Move to text languages', 'Find community resources'],
         'prereq': ['Scratch-20: Advanced Project Ideas'],
         'samples': [
             '# Try Snap! or Blockly for more advanced blocks',
             '# Transition: Python — print() is like say',
             '# Scratch helps you think like a programmer',
             '# Community: Scratch forums, Scratch Wiki',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# V
# ────────────────────────────────────────────────────────────────────────────
V = {
    'lang': 'v',
    'code_lang': 'v',
    'refs': [
        ('V Documentation', 'https://docs.vlang.io/', 'Official docs'),
        ('V Manual', 'https://docs.vlang.io/introduction.html', 'Language manual'),
        ('V Language GitHub', 'https://github.com/vlang/v', 'Source code'),
    ],
    'lessons': [
        {'slug': 'v-01-getting-started', 'title': 'Getting Started with V', 'desc': 'Install, compile, and hello world.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Install V', 'Compile with v run', 'Write hello world', 'Build executables'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'fn main() {\n\tprintln("Hello, World!")\n}',
             'v run hello.v',
             'v hello.v -o hello\n./hello',
             'fn main() {\n\tprintln("Hello, " + "V!")\n}',
         ]},
        {'slug': 'v-02-variables', 'title': 'Variables and Types', 'desc': 'immutable, mut, and built-in types.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare immutable vars', 'Use mut variables', 'Use built-in types', 'Use string interpolation'],
         'prereq': ['V-01: Getting Started with V'],
         'samples': [
             'fn main() {\n\tname := "Ada"\n\tage := 36\n\tprintln(name)\n}',
             'mut count := 0\ncount++\nprintln(count)',
             'x := 42\ny := 3.14\nb := true',
             'println("Hello, ${name}!")',
         ]},
        {'slug': 'v-03-control-flow', 'title': 'Control Flow', 'desc': 'if, match, and loops.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write if/else', 'Use match', 'Use for loops', 'Use loops over ranges'],
         'prereq': ['V-02: Variables and Types'],
         'samples': [
             'score := 85\nif score >= 90 {\n\tprintln("A")\n} else if score >= 80 {\n\tprintln("B")\n} else {\n\tprintln("C")\n}',
             'n := 2\nmatch n {\n\t1 { println("one") }\n\t2 { println("two") }\n\telse { println("other") }\n}',
             'for i in 0..5 {\n\tprintln(i)\n}',
             'for i := 0; i < 5; i++ {\n\tprintln(i)\n}',
         ]},
        {'slug': 'v-04-functions', 'title': 'Functions', 'desc': 'Typed functions and multiple returns.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Write functions', 'Use return types', 'Return multiple values', 'Use default params'],
         'prereq': ['V-03: Control Flow'],
         'samples': [
             'fn add(a int, b int) int {\n\treturn a + b\n}\n\nfn main() {\n\tprintln(add(2, 3))\n}',
             'fn divmod(a int, b int) (int, int) {\n\treturn a / b, a % b\n}\n\nq, r := divmod(7, 2)',
             'fn greet(name string) string {\n\treturn "Hello, " + name\n}',
             'fn apply(f fn (int) int, x int) int {\n\treturn f(x)\n}',
         ]},
        {'slug': 'v-05-arrays', 'title': 'Arrays', 'desc': 'Dynamic arrays.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create arrays', 'Append elements', 'Iterate arrays', 'Use array methods'],
         'prereq': ['V-04: Functions'],
         'samples': [
             'mut nums := [1, 2, 3]\nnums << 4\nprintln(nums)',
             'nums := [1, 2, 3, 4]\nprintln(nums.filter(fn (n int) bool { return n % 2 == 0 }))',
             'for n in nums {\n\tprintln(n)\n}',
             'println(nums.len)\nprintln(nums[1..3])',
         ]},
        {'slug': 'v-06-maps', 'title': 'Maps', 'desc': 'Key-value storage.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create maps', 'Insert and get', 'Iterate entries', 'Check existence'],
         'prereq': ['V-05: Arrays'],
         'samples': [
             'mut ages := map[string]int{}\nages["Ada"] = 36\nprintln(ages["Ada"])',
             'ages := {"Ada": 36, "Grace": 85}\nprintln(ages.keys())',
             'for name, age in ages {\n\tprintln("$name: $age")\n}',
             'if "Ada" in ages {\n\tprintln("found")\n}',
         ]},
        {'slug': 'v-07-strings', 'title': 'Strings', 'desc': 'String operations.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Concatenate strings', 'Interpolate values', 'Split and join', 'Use string methods'],
         'prereq': ['V-06: Maps'],
         'samples': [
             's := "Hello" + " " + "World"\nprintln(s)',
             'name := "Ada"\nprintln("Hello, $name!")',
             'println("a,b,c".split(",").join(" | "))',
             'println("hello".to_upper())',
         ]},
        {'slug': 'v-08-structs', 'title': 'Structs', 'desc': 'User-defined types.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define structs', 'Create instances', 'Access fields', 'Use struct methods'],
         'prereq': ['V-07: Strings'],
         'samples': [
             'struct Person {\n\tname string\n\tage int\n}\n\nada := Person{\n\tname: "Ada"\n\tage: 36\n}\nprintln(ada.name)',
             'mut p := Person{}\np.name = "Grace"\np.age = 85',
             'struct Point {\n\tx int\n\ty int\n}\n\np := Point{1, 2}',
             'fn (p Person) greet() string {\n\treturn "Hi, I am ${p.name}"\n}\n\nprintln(ada.greet())',
         ]},
        {'slug': 'v-09-enums', 'title': 'Enums', 'desc': 'Typed enumerations.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define enums', 'Use enum values', 'Match enums', 'Convert to strings'],
         'prereq': ['V-08: Structs'],
         'samples': [
             'enum Color {\n\tred\n\tgreen\n\tblue\n}\n\nc := Color.green\nprintln(c)',
             'match c {\n\t.red { println("red") }\n\t.green { println("green") }\n\t.blue { println("blue") }\n}',
             'println(Color.values())',
             'c := Color.from_string("blue") or { Color.red }',
         ]},
        {'slug': 'v-10-optionals', 'title': 'Optionals and Results', 'desc': 'Error handling with or.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use ? types', 'Handle with or', 'Use or block', 'Propagate errors'],
         'prereq': ['V-09: Enums'],
         'samples': [
             'fn safe_div(a int, b int) ?int {\n\tif b == 0 {\n\t\treturn error("div by zero")\n\t}\n\treturn a / b\n}\n\nresult := safe_div(10, 2) or { 0 }\nprintln(result)',
             'fn read_file(path string) ?string {\n\treturn os.read_file(path) or { return err }\n}',
             'value := risky() or {\n\tprintln("fallback")\n\t-1\n}',
             'if r := safe_div(10, 0) {\n\tprintln(r)\n} else {\n\tprintln("failed")\n}',
         ]},
        {'slug': 'v-11-interfaces', 'title': 'Interfaces and Sum Types', 'desc': 'Polymorphism.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Define interfaces', 'Implement interfaces', 'Use sum types', 'Use type switches'],
         'prereq': ['V-10: Optionals and Results'],
         'samples': [
             'interface Shape {\n\tarea() f64\n}\n\nstruct Circle {\n\tradius f64\n}\n\nfn (c Circle) area() f64 {\n\treturn 3.14159 * c.radius * c.radius\n}',
             'fn print_area(s Shape) {\n\tprintln(s.area())\n}',
             'type Expr = Num | Add | Mul\nstruct Num {\n\tvalue int\n}\nstruct Add {\n\ta Expr\n\tb Expr\n}',
             'match e {\n\tNum { println("num: ${e.value}") }\n\tAdd { println("add") }\n}',
         ]},
        {'slug': 'v-12-generics', 'title': 'Generics', 'desc': 'Type-parameterized code.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write generic functions', 'Use generic structs', 'Constrain types', 'Build containers'],
         'prereq': ['V-11: Interfaces and Sum Types'],
         'samples': [
             'fn identity[T](x T) T {\n\treturn x\n}\n\nprintln(identity(42))\nprintln(identity("hi"))',
             'struct Box[T] {\n\tvalue T\n}\n\nb := Box[int]{value: 42}',
             'fn max[T](a T, b T) T {\n\treturn if a > b { a } else { b }\n}',
             'fn first[T](arr []T) T {\n\treturn arr[0]\n}',
         ]},
        {'slug': 'v-13-file-io', 'title': 'File I/O', 'desc': 'Read and write files.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Read files', 'Write files', 'Read lines', 'Handle paths'],
         'prereq': ['V-12: Generics'],
         'samples': [
             'import os\n\ncontent := os.read_file("data.txt") or { panic(err) }\nprintln(content)',
             'os.write_file("out.txt", "hello") or { panic(err) }',
             'for line in os.read_lines("data.txt") or { [] } {\n\tprintln(line)\n}',
             'println(os.exists("data.txt"))',
         ]},
        {'slug': 'v-14-concurrency', 'title': 'Concurrency', 'desc': 'Threads and channels.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Spawn threads', 'Use channels', 'Share data safely', 'Sync threads'],
         'prereq': ['V-13: File I/O'],
         'samples': [
             'import sync\n\nfn worker(id int) {\n\tprintln("worker $id")\n}\n\nmut wg := sync.new_waitgroup()\nfor i in 0..4 {\n\twg.add(1)\n\tgo worker(i)\n}\nwg.wait()',
             'import sync\n\nmut ch := sync.new_channel[int](1)\nch.push(42)\nprintln(ch.pop() or { 0 })',
             'spawn fn() {\n\tprintln("in goroutine")\n}()',
             'mut shared := 0\nlock {\n\tshared++\n}',
         ]},
        {'slug': 'v-15-web', 'title': 'Web Development with vweb', 'desc': 'Build HTTP apps.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create a vweb app', 'Define routes', 'Serve HTML', 'Handle POST'],
         'prereq': ['V-14: Concurrency'],
         'samples': [
             'import vweb\n\nstruct App {\n\tvweb.Context\n}\n\nfn main() {\n\tvweb.run(App{}, 8080)\n}\n\nfn (app &App) index() vweb.Result {\n\treturn app.text("Hello, World!")\n}',
             'fn (app &App) hello(name string) vweb.Result {\n\treturn app.text("Hello, " + name)\n}',
             'v run .\ncurl http://localhost:8080',
             'fn (mut app App) submit() vweb.Result {\n\tname := app.form["name"]\n\treturn app.text("hi " + name)\n}',
         ]},
        {'slug': 'v-16-json', 'title': 'JSON', 'desc': 'Encode and decode JSON.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Encode structs to JSON', 'Decode JSON to structs', 'Handle optional fields', 'Work with raw JSON'],
         'prereq': ['V-15: Web Development with vweb'],
         'samples': [
             'import json\n\nstruct User {\n\tname string\n\tage int\n}\n\nu := User{"Ada", 36}\nprintln(json.encode(u))',
             'data := json.decode(User, \'{"name": "Ada", "age": 36}\') or { panic(err) }\nprintln(data.name)',
             'struct Config {\n\tverbose bool\n\tport int\n}',
             'raw := json.raw_decode(\'{"a": 1}\') or { panic(err) }\nprintln(raw)',
         ]},
        {'slug': 'v-17-testing', 'title': 'Testing', 'desc': 'Unit tests in V.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Write test functions', 'Use assert', 'Run v test', 'Test structs'],
         'prereq': ['V-16: JSON'],
         'samples': [
             'fn add(a int, b int) int {\n\treturn a + b\n}\n\nfn test_add() {\n\tassert add(2, 3) == 5\n}',
             'v test .',
             'fn test_strings() {\n\tassert "ab" + "cd" == "abcd"\n}',
             'fn test_struct() {\n\tp := Person{"Ada", 36}\n\tassert p.age == 36\n}',
         ]},
        {'slug': 'v-18-cli', 'title': 'CLI Applications', 'desc': 'Build command-line tools.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Parse arguments', 'Use flag package', 'Read stdin', 'Build a CLI tool'],
         'prereq': ['V-17: Testing'],
         'samples': [
             'import os\n\nfn main() {\n\targs := os.args\n\tprintln(args)\n}',
             'import flag\n\nmut fp := flag.new_flag_parser(os.args)\nname := fp.string("name", `n`, "", "your name")\nfp.finalize() or { panic(err) }\nprintln("Hello, $name")',
             'import os\n\nfor line in os.stdin.read_lines() {\n\tprintln(line)\n}',
             'println("Usage: app [options]")',
         ]},
        {'slug': 'v-19-sqlite', 'title': 'Database Access', 'desc': 'SQLite in V.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Open databases', 'Create tables', 'Run queries', 'Use prepared statements'],
         'prereq': ['V-18: CLI Applications'],
         'samples': [
             'import sqlite\n\nmut db := sqlite.connect("test.db") or { panic(err) }',
             'db.exec("create table if not exists users (id integer primary key, name text)") or { panic(err) }',
             'db.exec("insert into users (name) values (?)", "Ada") or { panic(err) }',
             'rows := db.exec("select name from users") or { panic(err) }\nprintln(rows)',
         ]},
        {'slug': 'v-20-performance', 'title': 'Performance', 'desc': 'V compiles to fast native code.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use -prod builds', 'Avoid allocations', 'Use fixed arrays', 'Profile code'],
         'prereq': ['V-19: Database Access'],
         'samples': [
             'v -prod -o app app.v',
             'import time\n\nstart := time.now()\n// work\nprintln(time.now() - start)',
             'mut arr := [0]!1000   // fixed array',
             'for i in 0..1000000 { _ = i }',
         ]},
        {'slug': 'v-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'V modules and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use vpm', 'Install modules', 'Publish modules', 'Join the community'],
         'prereq': ['V-20: Performance'],
         'samples': [
             'v install https://github.com/vlang/vpm',
             'v search json',
             'v mod init\nv mod publish',
             '// community: vlang.io, discord',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# WEBASSEMBLY
# ────────────────────────────────────────────────────────────────────────────
WEBASSEMBLY = {
    'lang': 'webassembly',
    'code_lang': 'wast',
    'refs': [
        ('WebAssembly Specification', 'https://webassembly.github.io/spec/core/', 'The official spec'),
        ('MDN WebAssembly Docs', 'https://developer.mozilla.org/en-US/docs/WebAssembly', 'Mozilla reference'),
        ('WebAssembly.org', 'https://webassembly.org/', 'Official site'),
    ],
    'lessons': [
        {'slug': 'webassembly-01-getting-started', 'title': 'Getting Started with WebAssembly', 'desc': 'What WASM is and your first module.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Understand what WASM is', 'Write a WAT module', 'Compile with wat2wasm', 'Run in a browser'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             '(module\n  (func (export "add") (param i32 i32) (result i32)\n    local.get 0\n    local.get 1\n    i32.add))',
             'wat2wasm math.wat -o math.wasm',
             'WebAssembly.instantiateStreaming(fetch("math.wasm"))\n  .then(({ instance }) => {\n    console.log(instance.exports.add(2, 3));\n  });',
             '(module (func $main (export "main")))',
         ]},
        {'slug': 'webassembly-02-values', 'title': 'Value Types', 'desc': 'i32, i64, f32, f64.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use integer types', 'Use float types', 'Understand v128', 'Use type annotations'],
         'prereq': ['WebAssembly-01: Getting Started with WebAssembly'],
         'samples': [
             '(module\n  (func (export "int_const") (result i32)\n    i32.const 42))',
             '(func (export "float_const") (result f64)\n    f64.const 3.14)',
             '(func (export "big") (result i64)\n    i64.const 9223372036854775807)',
             '(module (global $g (mut i32) (i32.const 0)))',
         ]},
        {'slug': 'webassembly-03-variables', 'title': 'Locals and Globals', 'desc': 'Function locals and module globals.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Declare locals', 'Use get_local and set_local', 'Declare globals', 'Export globals'],
         'prereq': ['WebAssembly-02: Value Types'],
         'samples': [
             '(func (export "use_local") (param i32) (result i32)\n  (local i32)\n  local.get 0\n  local.set 1\n  local.get 1)',
             '(module\n  (global $counter (mut i32) (i32.const 0))\n  (func (export "inc")\n    global.get $counter\n    i32.const 1\n    i32.add\n    global.set $counter))',
             '(global $exported (export "version") i32 (i32.const 1))',
             '(func (param $x i32) (param $y i32) (result i32)\n  local.get $x\n  local.get $y\n  i32.add)',
         ]},
        {'slug': 'webassembly-04-arithmetic', 'title': 'Arithmetic Instructions', 'desc': 'Integer and float math.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Add and subtract', 'Multiply and divide', 'Handle overflow', 'Use float math'],
         'prereq': ['WebAssembly-03: Locals and Globals'],
         'samples': [
             '(func (export "add") (param i32 i32) (result i32)\n  local.get 0\n  local.get 1\n  i32.add)',
             '(func (export "mul") (param i32 i32) (result i32)\n  local.get 0\n  local.get 1\n  i32.mul)',
             '(func (export "div") (param i32 i32) (result i32)\n  local.get 0\n  local.get 1\n  i32.div_s)',
             '(func (export "fadd") (param f64 f64) (result f64)\n  local.get 0\n  local.get 1\n  f64.add)',
         ]},
        {'slug': 'webassembly-05-memory', 'title': 'Linear Memory', 'desc': 'The memory model.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Declare memory', 'Load from memory', 'Store to memory', 'Grow memory'],
         'prereq': ['WebAssembly-04: Arithmetic Instructions'],
         'samples': [
             '(module\n  (memory (export "memory") 1)\n  (func (export "store") (param i32 i32)\n    local.get 0\n    local.get 1\n    i32.store))',
             '(func (export "load") (param i32) (result i32)\n  local.get 0\n  i32.load)',
             '(func (export "init")\n  i32.const 0\n  i32.const 42\n  i32.store)',
             '(memory 1 4)   ; 1 page initial, 4 pages max',
         ]},
        {'slug': 'webassembly-06-memory-ops', 'title': 'Memory Operations', 'desc': 'Loads and stores with offsets.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Use load/store offsets', 'Handle alignment', 'Store byte arrays', 'Read strings'],
         'prereq': ['WebAssembly-05: Linear Memory'],
         'samples': [
             '(func (export "store_at") (param i32 i32)\n  local.get 0\n  i32.const 0\n  local.get 1\n  i32.store offset=0)',
             '(func (export "load8") (param i32) (result i32)\n  local.get 0\n  i32.load8_u)',
             '(func (export "write_byte") (param $addr i32) (param $val i32)\n  local.get $addr\n  local.get $val\n  i32.store8)',
             '(func (export "read") (param $addr i32) (result i32)\n  local.get $addr\n  i32.load align=4)',
         ]},
        {'slug': 'webassembly-07-control-flow', 'title': 'Control Flow', 'desc': 'branch and block structures.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Use block and end', 'Use if/else', 'Use br and br_if', 'Use loop'],
         'prereq': ['WebAssembly-06: Memory Operations'],
         'samples': [
             '(func (export "max") (param i32 i32) (result i32)\n  local.get 0\n  local.get 1\n  i32.gt_s\n  if (result i32)\n    local.get 0\n  else\n    local.get 1\n  end)',
             '(func (export "sum") (param i32) (result i32)\n  (local i32)\n  block\n    loop\n      local.get 0\n      i32.eqz\n      br_if 1\n      local.get 1\n      local.get 0\n      i32.add\n      local.set 1\n      local.get 0\n      i32.const 1\n      i32.sub\n      local.set 0\n      br 0\n    end\n  end\n  local.get 1)',
             '(func (export "abs") (param i32) (result i32)\n  local.get 0\n  i32.const 0\n  i32.lt_s\n  if (result i32)\n    local.get 0\n    i32.const -1\n    i32.mul\n  else\n    local.get 0\n  end)',
             '(func (export "fib") (param i32) (result i32)\n  ...)',
         ]},
        {'slug': 'webassembly-08-tables', 'title': 'Tables and call_indirect', 'desc': 'Function pointers.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Declare tables', 'Use call_indirect', 'Store function refs', 'Implement dispatch'],
         'prereq': ['WebAssembly-07: Control Flow'],
         'samples': [
             '(module\n  (type $binop (func (param i32 i32) (result i32)))\n  (table 2 funcref)\n  (elem (i32.const 0) $add $mul)\n  (func $add (type $binop) (param i32 i32) (result i32)\n    local.get 0\n    local.get 1\n    i32.add)\n  (func $mul (type $binop) (param i32 i32) (result i32)\n    local.get 0\n    local.get 1\n    i32.mul)\n  (func (export "apply") (param i32 i32 i32) (result i32)\n    local.get 0\n    local.get 1\n    local.get 2\n    call_indirect (type $binop)))',
             '(type $void (func))',
             '(table (export "table") 10 funcref)',
             'call_indirect (param i32) (result i32)',
         ]},
        {'slug': 'webassembly-09-imports-exports', 'title': 'Imports and Exports', 'desc': 'The module interface.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Export functions', 'Import functions', 'Import memory', 'Use wasm-bindgen'],
         'prereq': ['WebAssembly-08: Tables and call_indirect'],
         'samples': [
             '(module\n  (func (export "hello") (result i32)\n    i32.const 42))',
             '(module\n  (import "env" "log" (func $log (param i32)))\n  (func (export "run")\n    i32.const 42\n    call $log))',
             '(import "env" "memory" (memory 1))',
             '(export "run" (func $run))',
         ]},
        {'slug': 'webassembly-10-text-format', 'title': 'Text Format Deep Dive', 'desc': 'WAT syntax details.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Read folded expressions', 'Use s-expressions', 'Annotate modules', 'Convert to binary'],
         'prereq': ['WebAssembly-09: Imports and Exports'],
         'samples': [
             '(module\n  (func $add (param i32 i32) (result i32)\n    (i32.add (local.get 0) (local.get 1))))',
             '(func (export "main") (result i32)\n  (i32.const 2)\n  (i32.const 3)\n  (i32.mul))',
             '(module $m\n  (func $f))',
             '(;; comment ;;)',
         ]},
        {'slug': 'webassembly-11-js-api', 'title': 'The JavaScript API', 'desc': 'Interact with WASM from JS.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Use WebAssembly.instantiate', 'Pass parameters', 'Share memory', 'Handle exceptions'],
         'prereq': ['WebAssembly-10: Text Format Deep Dive'],
         'samples': [
             'const { instance } = await WebAssembly.instantiateStreaming(\n  fetch("math.wasm")\n);\nconsole.log(instance.exports.add(2, 3));',
             'const { module, instance } = await WebAssembly.instantiate(bytes, imports);',
             'WebAssembly.validate(bytes);',
             'new WebAssembly.Instance(module, { env: { log } });',
         ]},
        {'slug': 'webassembly-12-strings', 'title': 'Strings in WASM', 'desc': 'Pass strings across the boundary.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Encode strings', 'Pass from JS to WASM', 'Read strings in JS', 'Use TextEncoder'],
         'prereq': ['WebAssembly-11: The JavaScript API'],
         'samples': [
             'const encoder = new TextEncoder();\nconst bytes = encoder.encode("Hello");\nnew Uint8Array(memory.buffer, offset, bytes.length).set(bytes);',
             '(func (export "len") (param i32) (result i32)\n  local.get 0\n  i32.load8_u)',
             'const decoder = new TextDecoder();\nconst str = decoder.decode(new Uint8Array(memory.buffer, offset, len));',
             'instance.exports.write(offset, len);',
         ]},
        {'slug': 'webassembly-13-rust-wasm', 'title': 'Rust and wasm-bindgen', 'desc': 'Compile Rust to WASM.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Set up wasm-pack', 'Write Rust functions', 'Use wasm-bindgen', 'Publish to npm'],
         'prereq': ['WebAssembly-12: Strings in WASM'],
         'samples': [
             'wasm-pack new myapp\ncd myapp',
             'use wasm_bindgen::prelude::*;\n\n#[wasm_bindgen]\npub fn add(a: u32, b: u32) -> u32 {\n    a + b\n}',
             'wasm-pack build --target web',
             'import { add } from "./pkg/myapp.js";\nconsole.log(add(2, 3));',
         ]},
        {'slug': 'webassembly-14-wat-compilers', 'title': 'WAT and AssemblyScript', 'desc': 'Compile TypeScript-like code.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use AssemblyScript', 'Compile ASC', 'Use asc CLI', 'Interop with JS'],
         'prereq': ['WebAssembly-13: Rust and wasm-bindgen'],
         'samples': [
             'npm install -D assemblyscript\nnpx asc assembly/index.ts -o build/index.wasm',
             'export function add(a: i32, b: i32): i32 {\n  return a + b;\n}',
             'export function fib(n: i32): i32 {\n  return n < 2 ? n : fib(n - 1) + fib(n - 2);\n}',
             'import { add } from "./build/index.js";',
         ]},
        {'slug': 'webassembly-15-performance', 'title': 'Performance Patterns', 'desc': 'Write fast WASM.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Avoid boundary crossings', 'Batch memory ops', 'Use typed arrays', 'Benchmark'],
         'prereq': ['WebAssembly-14: WAT and AssemblyScript'],
         'samples': [
             '// Prefer: pass a batch to WASM once, not many small calls',
             'const arr = new Uint32Array(memory.buffer, 0, 1024);',
             '// Process large arrays entirely in WASM',
             'performance.now() to measure',
         ]},
        {'slug': 'webassembly-16-threads', 'title': 'Threads and Shared Memory', 'desc': 'WebAssembly threads.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create workers', 'Share memory', 'Use atomics', 'Synchronize threads'],
         'prereq': ['WebAssembly-15: Performance Patterns'],
         'samples': [
             'new Worker("worker.js");',
             'const shared = new SharedArrayBuffer(1024);',
             'const memory = new WebAssembly.Memory({ initial: 1, maximum: 10, shared: true });',
             'Atomics.add(new Int32Array(shared), 0, 1);',
         ]},
        {'slug': 'webassembly-17-simd', 'title': 'SIMD', 'desc': 'Vectorized computation.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Use v128 instructions', 'Load vectors', 'Add vectors', 'Speed up math'],
         'prereq': ['WebAssembly-16: Threads and Shared Memory'],
         'samples': [
             '(func (export "vadd") (param v128 v128) (result v128)\n  local.get 0\n  local.get 1\n  i32x4.add)',
             '(func (export "load_v") (param i32) (result v128)\n  local.get 0\n  v128.load)',
             'i32x4.mul',
             'v128.store',
         ]},
        {'slug': 'webassembly-18-wasi', 'title': 'WASI: Server-Side WASM', 'desc': 'Run WASM outside the browser.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand WASI', 'Use wasmtime', 'Access files', 'Run CLI tools'],
         'prereq': ['WebAssembly-17: SIMD'],
         'samples': [
             'wasmtime run hello.wasm',
             'rustup target add wasm32-wasip1',
             'wasmtime --dir=. app.wasm',
             'cargo build --target wasm32-wasip1',
         ]},
        {'slug': 'webassembly-19-containerless', 'title': 'Edge Computing and Serverless', 'desc': 'WASM at the edge.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Understand edge WASM', 'Use Fastly Compute', 'Use Cloudflare Workers', 'Deploy functions'],
         'prereq': ['WebAssembly-18: WASI: Server-Side WASM'],
         'samples': [
             '// Cloudflare Workers: compile Rust to WASM',
             'wrangler publish',
             '// Fastly: fastly compute serve',
             'module.exports = { fetch(req) { return new Response("hi"); } };',
         ]},
        {'slug': 'webassembly-20-debugging', 'title': 'Debugging WASM', 'desc': 'Source maps and tools.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Generate source maps', 'Use DevTools', 'Inspect modules', 'Use wat2wasm round-trip'],
         'prereq': ['WebAssembly-19: Edge Computing and Serverless'],
         'samples': [
             'wasm-pack build --dev',
             '// DevTools Sources panel shows .wat',
             'wasm2wat math.wasm -o math.wat',
             'wasm-objdump -d math.wasm',
         ]},
        {'slug': 'webassembly-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Tools and community.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use wabt tools', 'Discover the component model', 'Understand future directions', 'Join the community'],
         'prereq': ['WebAssembly-20: Debugging WASM'],
         'samples': [
             'wat2wasm\nwasm2wat\nwasm-objdump',
             '// The Component Model unifies modules',
             '// WASI 0.2 adds rich host APIs',
             '// community: WebAssembly discourse, GitHub',
         ]},
    ],
}

# ────────────────────────────────────────────────────────────────────────────
# WOLFRAM LANGUAGE
# ────────────────────────────────────────────────────────────────────────────
WOLFRAM = {
    'lang': 'wolfram-language',
    'code_lang': 'wolfram',
    'refs': [
        ('Wolfram Language Documentation', 'https://reference.wolfram.com/language/', 'Official reference'),
        ('Wolfram Language Fast Introduction', 'https://www.wolfram.com/language/fast-introduction-for-programmers/en/', 'Fast intro'),
        ('Wolfram Language Guide', 'https://reference.wolfram.com/language/guide/LanguageOverview.html', 'Language guide'),
    ],
    'lessons': [
        {'slug': 'wolfram-01-getting-started', 'title': 'Getting Started with Wolfram Language', 'desc': 'Notebooks, evaluation, hello.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Open a notebook', 'Evaluate expressions', 'Use the Wolfram Cloud', 'Write hello world'],
         'prereq': ['None — this is the entry point'],
         'samples': [
             'Print["Hello, World!"]',
             '1 + 1',
             '2^10',
             'Print["Hello, ", "Wolfram!"]',
         ]},
        {'slug': 'wolfram-02-values', 'title': 'Numbers and Arithmetic', 'desc': 'Exact and approximate math.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Use exact arithmetic', 'Use approximate reals', 'Compute powers and roots', 'Use constants'],
         'prereq': ['Wolfram-01: Getting Started with Wolfram Language'],
         'samples': [
             '1/3 + 1/6',
             '0.5 + 0.25',
             'Sqrt[2]',
             'Pi\nE',
         ]},
        {'slug': 'wolfram-03-variables', 'title': 'Assignments', 'desc': 'Set and SetDelayed.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Assign values with =', 'Use := delayed assignment', 'Clear variables', 'Use symbols'],
         'prereq': ['Wolfram-02: Numbers and Arithmetic'],
         'samples': [
             'x = 10\nx + 5',
             'y = RandomInteger[{1, 10}]\ny',
             'y := RandomInteger[{1, 10}]\ny\ny',
             'Clear[x]',
         ]},
        {'slug': 'wolfram-04-lists', 'title': 'Lists', 'desc': 'The core data structure.', 'dur': '45 min', 'diff': 'beginner',
         'objs': ['Create lists', 'Access elements', 'Map functions', 'Use list functions'],
         'prereq': ['Wolfram-03: Assignments'],
         'samples': [
             'list = {1, 2, 3, 4, 5}',
             'list[[2]]\nFirst[list]\nLast[list]',
             'Map[#^2 &, list]\nlist^2',
             'Total[list]\nLength[list]\nSort[list]',
         ]},
        {'slug': 'wolfram-05-functions', 'title': 'Functions', 'desc': 'Define and use functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Define pure functions', 'Use # and &', 'Define named functions', 'Use function options'],
         'prereq': ['Wolfram-04: Lists'],
         'samples': [
             'square[x_] := x^2\nsquare[5]',
             '#^2 &[5]',
             'Map[# * 2 &, {1, 2, 3}]',
             'f[x_, y_] := x^2 + y^2\nf[3, 4]',
         ]},
        {'slug': 'wolfram-06-plotting', 'title': 'Plotting', 'desc': 'Visualize functions.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Plot functions', 'Use Plot options', 'Plot lists', 'Make 3D plots'],
         'prereq': ['Wolfram-05: Functions'],
         'samples': [
             'Plot[Sin[x], {x, 0, 2 Pi}]',
             'Plot[x^2, {x, -3, 3}, PlotStyle -> Red]',
             'ListPlot[{1, 4, 9, 16}]',
             'Plot3D[Sin[x] Cos[y], {x, -3, 3}, {y, -3, 3}]',
         ]},
        {'slug': 'wolfram-07-strings', 'title': 'Strings', 'desc': 'Text manipulation.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Concatenate strings', 'Split strings', 'Use string functions', 'Format output'],
         'prereq': ['Wolfram-06: Plotting'],
         'samples': [
             '"Hello" <> " " <> "World"',
             'StringSplit["a,b,c", ","]',
             'StringLength["hello"]\nToUpperCase["hi"]',
             'StringJoin[{"a", "b", "c"}]',
         ]},
        {'slug': 'wolfram-08-conditions', 'title': 'Conditionals', 'desc': 'If, Which, and patterns.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use If', 'Use Which', 'Use Switch', 'Use patterns in conditions'],
         'prereq': ['Wolfram-07: Strings'],
         'samples': [
             'If[x > 0, "positive", "non-positive"]',
             'Which[x > 0, "pos", x == 0, "zero", True, "neg"]',
             'Switch[x, 1, "one", 2, "two", _, "other"]',
             'x_ /; x > 0',
         ]},
        {'slug': 'wolfram-09-loops', 'title': 'Iteration', 'desc': 'Do, Table, and functional loops.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use Do loops', 'Use Table', 'Use Fold and Nest', 'Avoid explicit loops'],
         'prereq': ['Wolfram-08: Conditionals'],
         'samples': [
             'Do[Print[i], {i, 1, 5}]',
             'Table[i^2, {i, 1, 5}]',
             'Fold[Plus, 0, {1, 2, 3}]',
             'Nest[#^2 &, 2, 3]',
         ]},
        {'slug': 'wolfram-10-patterns', 'title': 'Pattern Matching', 'desc': 'The heart of the language.', 'dur': '60 min', 'diff': 'intermediate',
         'objs': ['Use blank patterns', 'Use pattern rules', 'Define replacements', 'Use ReplaceAll'],
         'prereq': ['Wolfram-09: Iteration'],
         'samples': [
             'f[x_] := x^2',
             'expr = x^2 + 2 x + 1\nexpr /. x -> 3',
             '{1, 2, 3} /. x_Integer -> x^2',
             'MatchQ[5, _Integer]',
         ]},
        {'slug': 'wolfram-11-associations', 'title': 'Associations', 'desc': 'Key-value data.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Create associations', 'Access keys', 'Add entries', 'Use association functions'],
         'prereq': ['Wolfram-10: Pattern Matching'],
         'samples': [
             'person = <|"name" -> "Ada", "age" -> 36|>',
             'person["name"]',
             'person["city"] = "London"\nperson',
             'Keys[person]\nValues[person]',
         ]},
        {'slug': 'wolfram-12-graphics', 'title': 'Graphics', 'desc': 'Draw primitives.', 'dur': '45 min', 'diff': 'intermediate',
         'objs': ['Use graphics primitives', 'Style shapes', 'Compose scenes', 'Export images'],
         'prereq': ['Wolfram-11: Associations'],
         'samples': [
             'Graphics[{Circle[], Rectangle[]}]',
             'Graphics[{Red, Disk[{0, 0}, 1]}]',
             'Graphics[{Line[{{0, 0}, {1, 1}}]}]',
             'Export["circle.png", Graphics[Circle[]]]',
         ]},
        {'slug': 'wolfram-13-data', 'title': 'Data Frames and Datasets', 'desc': 'Work with tabular data.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create datasets', 'Query datasets', 'Filter rows', 'Aggregate data'],
         'prereq': ['Wolfram-12: Graphics'],
         'samples': [
             'data = Dataset[{<|"a" -> 1, "b" -> 2|>, <|"a" -> 3, "b" -> 4|>}]',
             'data[All, "a"]',
             'data[Select[#a > 1 &]]',
             'data[Total, "b"]',
         ]},
        {'slug': 'wolfram-14-import-export', 'title': 'Import and Export', 'desc': 'Read and write data.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Import files', 'Export data', 'Handle CSV', 'Import images'],
         'prereq': ['Wolfram-13: Data Frames and Datasets'],
         'samples': [
             'Import["data.csv"]',
             'Export["out.csv", {{1, 2}, {3, 4}}]',
             'Import["image.png"]',
             'ImportString["1,2,3", "CSV"]',
         ]},
        {'slug': 'wolfram-15-solving', 'title': 'Symbolic Solving', 'desc': 'Solve equations.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Solve equations', 'Use Reduce', 'Solve systems', 'Use DSolve'],
         'prereq': ['Wolfram-14: Import and Export'],
         'samples': [
             'Solve[x^2 - 5 x + 6 == 0, x]',
             'Solve[{x + y == 10, x - y == 4}, {x, y}]',
             'Reduce[x^2 < 4, x]',
             'DSolve[y\'[x] == y[x], y[x], x]',
         ]},
        {'slug': 'wolfram-16-calculus', 'title': 'Calculus', 'desc': 'Differentiation and integration.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Differentiate', 'Integrate', 'Compute limits', 'Find extrema'],
         'prereq': ['Wolfram-15: Symbolic Solving'],
         'samples': [
             'D[x^3, x]',
             'Integrate[x^2, x]',
             'Limit[Sin[x]/x, x -> 0]',
             'Maximize[-x^2 + 4 x, x]',
         ]},
        {'slug': 'wolfram-17-linear-algebra', 'title': 'Linear Algebra', 'desc': 'Matrices and vectors.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create matrices', 'Multiply matrices', 'Solve systems', 'Find eigenvalues'],
         'prereq': ['Wolfram-16: Calculus'],
         'samples': [
             'm = {{1, 2}, {3, 4}}',
             'm . {5, 6}',
             'Inverse[m]',
             'Eigenvalues[m]',
         ]},
        {'slug': 'wolfram-18-statistics', 'title': 'Statistics', 'desc': 'Descriptive statistics.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Compute means', 'Compute variances', 'Create histograms', 'Fit distributions'],
         'prereq': ['Wolfram-17: Linear Algebra'],
         'samples': [
             'Mean[{1, 2, 3, 4, 5}]',
             'Variance[{1, 2, 3, 4, 5}]',
             'Histogram[RandomReal[1, 100]]',
             'StandardDeviation[{1, 2, 3}]',
         ]},
        {'slug': 'wolfram-19-machine-learning', 'title': 'Machine Learning', 'desc': 'Classify and predict.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Create classifiers', 'Train models', 'Evaluate accuracy', 'Use neural nets'],
         'prereq': ['Wolfram-18: Statistics'],
         'samples': [
             'data = {1 -> "low", 2 -> "low", 10 -> "high", 11 -> "high"}\nc = Classify[data]\nc[5]',
             'c[5, "Probabilities"]',
             'Classify[{1 -> "a", 2 -> "b"}, Method -> "LogisticRegression"]',
             'NetChain[{LinearLayer[5], Ramp, LinearLayer[1]}]',
         ]},
        {'slug': 'wolfram-20-parallel', 'title': 'Parallel Computing', 'desc': 'Speed up computations.', 'dur': '60 min', 'diff': 'advanced',
         'objs': ['Launch kernels', 'Use ParallelTable', 'Use ParallelMap', 'Distribute definitions'],
         'prereq': ['Wolfram-19: Machine Learning'],
         'samples': [
             'LaunchKernels[]',
             'ParallelTable[i^2, {i, 1, 100}]',
             'ParallelMap[Sqrt, {1, 2, 3}]',
             'ParallelCombine[Total, Range[1000]]',
         ]},
        {'slug': 'wolfram-21-ecosystem', 'title': 'Ecosystem and Next Steps', 'desc': 'Wolfram Cloud and resources.', 'dur': '45 min', 'diff': 'advanced',
         'objs': ['Use the Wolfram Cloud', 'Deploy APIs', 'Use Wolfram Alpha', 'Join the community'],
         'prereq': ['Wolfram-20: Parallel Computing'],
         'samples': [
             'CloudDeploy[APIFunction[{}, 42 &]]',
             'WolframAlpha["population of France"]',
             'Entity["Country", "France"]',
             '// community: Wolfram Community forum',
         ]},
    ],
}

SPECS = [SCRATCH, V, WEBASSEMBLY, WOLFRAM]
