"""Curriculum specs for the Reinforcement Learning and MLOps AI courses."""

SPECS = [
    # ────────────────────────────────────────────────────────────────
    # REINFORCEMENT LEARNING
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'reinforcement-learning',
        'code_lang': 'python',
        'refs': [
            ('Reinforcement Learning: An Introduction — Sutton & Barto', 'http://incompleteideas.net/book/the-book-2nd.html', 'The canonical RL textbook (free PDF).'),
            ('Spinning Up in Deep RL — OpenAI', 'https://spinningup.openai.com/en/latest/', 'A practitioner-focused deep RL resource with clean implementations.'),
            ('Stable-Baselines3 Documentation', 'https://stable-baselines3.readthedocs.io/', 'Reliable RL algorithm implementations in PyTorch.'),
            ('Gymnasium Documentation', 'https://gymnasium.farama.org/', 'The standard API for RL environments.'),
            ('RL Course by David Silver', 'https://www.davidsilver.uk/teaching/', 'The classic lecture series on RL fundamentals.'),
        ],
        'lessons': [
            {
                'slug': 'rl-01-what-is-reinforcement-learning',
                'title': 'What Is Reinforcement Learning?',
                'desc': 'Agents, environments, rewards and the trial-and-error loop that powers RL.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': ['ML-01: What Is Machine Learning?'],
                'objs': [
                    'Define the agent-environment-reward loop',
                    'Contrast RL with supervised and unsupervised learning',
                    'Name the core RL problems and applications',
                    'Describe the exploration-exploitation tension',
                ],
                'samples': [
                    'loop = {\n    "agent": "takes actions",\n    "environment": "responds with next state + reward",\n    "goal": "maximize cumulative reward",\n}\nprint(loop)',
                    'import gymnasium as gym\n\nenv = gym.make("CartPole-v1")\nobs, info = env.reset()\nprint("observation:", obs)',
                    'import numpy as np\n\n# Reward signal drives learning\nr = np.array([0.0, 0.0, 0.0, 1.0, 0.0])\nprint("total return:", r.sum())',
                    'print("supervised: learn from labels. RL: learn from outcomes.")',
                ],
            },
            {
                'slug': 'rl-02-markov-decision-processes',
                'title': 'Markov Decision Processes',
                'desc': 'The formal framework: states, actions, transitions, rewards and the Markov property.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['RL-01: What Is Reinforcement Learning?'],
                'objs': [
                    'Define an MDP formally (S, A, P, R, gamma)',
                    'Explain the Markov property',
                    'Define policies, returns and discounting',
                    'Write the Bellman expectation equation',
                ],
                'samples': [
                    'mdp = {\n    "states": ["s0", "s1", "s2"],\n    "actions": ["left", "right"],\n    "discount": 0.9,\n}\nprint(mdp)',
                    'import numpy as np\n\n# Return with discounting: sum of gamma^t * r_t\nrewards = np.array([1.0, 1.0, 1.0])\ngamma = 0.9\nt = np.arange(len(rewards))\nprint("discounted return:", round((gamma ** t * rewards).sum(), 3))',
                    'import numpy as np\n\n# Policy: probability of each action per state\npolicy = {"s0": {"left": 0.5, "right": 0.5}}\nprint(policy)',
                    'import numpy as np\n\n# Bellman expectation: V = R + gamma * P * V\nP = np.array([[0.7, 0.3], [0.2, 0.8]])\nR = np.array([1.0, 2.0])\nV = np.linalg.solve(np.eye(2) - 0.9 * P, R)\nprint("state values:", V.round(3))',
                ],
            },
            {
                'slug': 'rl-03-dynamic-programming',
                'title': 'Dynamic Programming',
                'desc': 'Solve MDPs exactly with policy evaluation, policy iteration and value iteration.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['RL-02: Markov Decision Processes'],
                'objs': [
                    'Perform policy evaluation',
                    'Improve policies with greedy selection',
                    'Run value iteration',
                    'Understand DP limits with large state spaces',
                ],
                'samples': [
                    'import numpy as np\n\n# Policy evaluation: iterative Bellman backup\nV = np.zeros(3)\nP = np.array([[0.5, 0.5, 0], [0, 0.5, 0.5], [0, 0, 1]])\nR = np.array([0, 0, 1.0])\nfor _ in range(100):\n    V = R + 0.9 * P @ V\nprint("values:", V.round(3))',
                    'import numpy as np\n\n# Greedy improvement: act optimally under current values\nV = np.array([0.1, 0.5, 1.0])\nbest = int(np.argmax(V))\nprint("best state:", best)',
                    'import numpy as np\n\n# Value iteration: V <- max over actions of backup\nV = np.zeros(4)\nrewards = np.array([0, 0, 0, 1.0])\nfor _ in range(100):\n    V = np.maximum(rewards + 0.9 * np.roll(V, 1), rewards + 0.9 * V)\nprint("value iteration done:", V.round(2))',
                    'import numpy as np\n\n# Curse of dimensionality: 10^state_dim grows fast\nfor d in [4, 8, 12]:\n    print(f"states in {d}-dim grid:", 10 ** d)',
                ],
            },
            {
                'slug': 'rl-04-monte-carlo-methods',
                'title': 'Monte Carlo Methods',
                'desc': 'Learn from complete episodes: average returns to estimate state values without a model.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['RL-03: Dynamic Programming'],
                'objs': [
                    'Explain episode-based learning',
                    'Estimate values with first-visit and every-visit MC',
                    'Implement MC prediction',
                    'Understand variance of MC returns',
                ],
                'samples': [
                    'import numpy as np\n\n# One episode: (state, reward) pairs\nepisode = [("s0", 0.0), ("s1", 0.0), ("s2", 1.0)]\nreturns = 0.0\nfor s, r in reversed(episode):\n    returns = r + 0.9 * returns\n    print(s, "return so far:", round(returns, 2))',
                    'import numpy as np\n\n# MC value estimate: average of sampled returns\nreturns_s0 = np.array([1.0, 0.9, 1.1])\nprint("V(s0) ~", round(returns_s0.mean(), 3))',
                    'import numpy as np\n\n# First-visit vs every-visit\nvisits = [1.0, 0.9, 1.1, 0.8]\nfirst = visits[0]\nprint("first-visit return:", first, "| every-visit mean:", round(np.mean(visits), 3))',
                    'import numpy as np\n\n# High variance: many episodes needed for stable estimates\nrng = np.random.default_rng(0)\nsamples = rng.normal(1.0, 2.0, 1000)\nprint("MC mean:", round(samples.mean(), 3), "+-", round(samples.std(ddof=1) / np.sqrt(1000), 3))',
                ],
            },
            {
                'slug': 'rl-05-temporal-difference-learning',
                'title': 'Temporal Difference Learning',
                'desc': 'Learn from partial episodes with bootstrapping — the idea at the heart of modern RL.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['RL-04: Monte Carlo Methods'],
                'objs': [
                    'Explain TD(0) bootstrapping',
                    'Update values incrementally after each step',
                    'Compare TD to MC (bias-variance)',
                    'Use TD for prediction',
                ],
                'samples': [
                    'import numpy as np\n\n# TD(0): V(s) <- V(s) + alpha * (r + gamma*V(s\') - V(s))\nV = np.zeros(3)\nalpha, gamma = 0.1, 0.9\nr, s_next = 0.0, 1\nV[0] += alpha * (r + gamma * V[s_next] - V[0])\nprint("updated V(s0):", V[0])',
                    'import numpy as np\n\n# TD error: the surprise signal\nr, gamma, V_next, V_now = 1.0, 0.9, 0.5, 0.3\ntd_error = r + gamma * V_next - V_now\nprint("TD error:", td_error)',
                    'import numpy as np\n\n# TD learns online, MC waits for episode end\nprint("TD: update every step. MC: update at episode end.")',
                    'import numpy as np\n\n# TD: lower variance than MC, biased by bootstrap\nprint("bias-variance trade-off: TD wins in practice")',
                ],
            },
            {
                'slug': 'rl-06-q-learning',
                'title': 'Q-Learning',
                'desc': 'Off-policy control: learn action values with Q-learning and watch agents improve from scratch.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['RL-05: Temporal Difference Learning'],
                'objs': [
                    'Define the Q-function',
                    'Explain the Q-learning update',
                    'Implement a tabular Q-learning agent',
                    'Describe off-policy learning',
                ],
                'samples': [
                    'import numpy as np\n\n# Q-learning update\nQ = np.zeros((4, 2))\nalpha, gamma = 0.1, 0.9\ns, a, r, s_next = 0, 0, 0.0, 1\nQ[s, a] += alpha * (r + gamma * Q[s_next].max() - Q[s, a])\nprint("Q table:", Q)',
                    'import numpy as np\n\n# Greedy action from Q\nQ = np.array([[0.1, 0.9], [0.5, 0.2]])\naction = int(np.argmax(Q[0]))\nprint("best action in s0:", action)',
                    'import numpy as np\n\n# Epsilon-greedy: explore with prob epsilon\nrng = np.random.default_rng(0)\neps = 0.1\nchosen = rng.choice(2) if rng.random() < eps else int(np.argmax(Q[0]))\nprint("chosen action:", chosen)',
                    'import numpy as np\n\n# Learning rate decay: big steps early, fine later\nfor t in range(100):\n    alpha = 1.0 / (1 + t)\nprint("final alpha:", round(alpha, 4))',
                ],
            },
            {
                'slug': 'rl-07-exploration-vs-exploitation',
                'title': 'Exploration vs Exploitation',
                'desc': 'Balance trying new things with using what works: epsilon-greedy, UCB and optimism.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['RL-06: Q-Learning'],
                'objs': [
                    'Explain the exploration-exploitation trade-off',
                    'Implement epsilon-greedy scheduling',
                    'Use UCB for principled exploration',
                    'Measure regret',
                ],
                'samples': [
                    'import numpy as np\n\n# Decaying epsilon: explore early, exploit later\nfor episode in range(10):\n    eps = max(0.05, 0.5 * (0.9 ** episode))\n    print(f"episode {episode}: eps={eps:.3f}")',
                    'import numpy as np\n\n# UCB: optimistic bonus for under-explored arms\ncounts = np.array([10, 2, 7])\nmeans = np.array([0.6, 0.9, 0.7])\nt = 19\nucb = means + np.sqrt(2 * np.log(t) / counts)\nprint("UCB scores:", ucb.round(3))',
                    'import numpy as np\n\n# Regret: what you lose by not always picking the best arm\nbest = 1.0\nchosen = np.array([0.6, 0.8, 0.9])\nprint("cumulative regret:", round((best - chosen).sum(), 3))',
                    'import numpy as np\n\n# Optimistic initialization encourages exploration\nQ = np.full((4, 2), 5.0)  # start optimistic\nprint("optimistic Q:", Q[0])',
                ],
            },
            {
                'slug': 'rl-08-function-approximation',
                'title': 'Function Approximation',
                'desc': 'Scale RL beyond tables: approximate Q-values with linear and neural models.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['RL-06: Q-Learning'],
                'objs': [
                    'Explain why tabular methods do not scale',
                    'Approximate Q with a linear model',
                    'Describe the deadly triad',
                    'Use features for generalization',
                ],
                'samples': [
                    'import numpy as np\n\n# Linear Q-approximation: Q(s,a) = w . phi(s,a)\nphi = np.array([1.0, 0.5, -0.2])\nw = np.array([0.3, 0.1, 0.4])\nprint("Q estimate:", round(phi @ w, 3))',
                    'import numpy as np\n\n# Gradient update toward the TD target\nw = np.zeros(3)\nphi = np.array([1.0, 0.0, 0.0])\ntarget = 1.0\nalpha = 0.1\nw += alpha * (target - phi @ w) * phi\nprint("updated weights:", w.round(3))',
                    'import torch\n\n# Neural Q: MLP mapping state to action values\nimport torch.nn as nn\nq_net = nn.Sequential(nn.Linear(4, 64), nn.ReLU(), nn.Linear(64, 2))\nprint(q_net(torch.randn(1, 4)))',
                    'import numpy as np\n\n# Deadly triad: function approx + bootstrapping + off-policy\nprint("combination can diverge; handled with target nets + replay")',
                ],
            },
            {
                'slug': 'rl-09-deep-q-networks',
                'title': 'Deep Q-Networks (DQN)',
                'desc': 'Play Atari from pixels: experience replay, target networks and the tricks that made DQN work.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['RL-08: Function Approximation'],
                'objs': [
                    'Explain experience replay',
                    'Use target networks to stabilize training',
                    'Implement a DQN training loop',
                    'Describe the DQN architecture',
                ],
                'samples': [
                    'import collections\nimport random\n\nreplay = collections.deque(maxlen=10000)\nreplay.append((s, a, r, s_next, done))\nprint("experience replay buffer ready")',
                    'import torch\nimport torch.nn as nn\n\nclass DQN(nn.Module):\n    def __init__(self, n_obs, n_act):\n        super().__init__()\n        self.net = nn.Sequential(nn.Linear(n_obs, 128), nn.ReLU(), nn.Linear(128, n_act))\n    def forward(self, x):\n        return self.net(x)\n\nprint(DQN(4, 2))',
                    'import torch\n\n# Target network: slow copy of the online net\nonline = DQN(4, 2)\ntarget = DQN(4, 2)\ntarget.load_state_dict(online.state_dict())\nprint("target net frozen copy")',
                    'import torch\n\n# Loss: (r + gamma * max_a Q_target(s\') - Q_online(s, a))^2\nprint("bellman residual squared")',
                ],
            },
            {
                'slug': 'rl-10-policy-gradient-methods',
                'title': 'Policy Gradient Methods',
                'desc': 'Optimize the policy directly — REINFORCE and the log-probability trick.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['RL-08: Function Approximation'],
                'objs': [
                    'Explain policy parameterization',
                    'Derive the REINFORCE update',
                    'Implement a policy-gradient loop',
                    'Reduce variance with baselines',
                ],
                'samples': [
                    'import torch\nimport torch.nn as nn\n\nclass Policy(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Sequential(nn.Linear(4, 32), nn.ReLU(), nn.Linear(32, 2))\n    def forward(self, x):\n        return torch.softmax(self.net(x), dim=-1)\n\nprint(Policy())',
                    'import torch\n\n# REINFORCE: grad = return * grad log pi(a|s)\nlog_prob = torch.tensor(-0.5, requires_grad=True)\nret = 1.2\nloss = -(ret * log_prob)\nloss.backward()\nprint("gradient:", log_prob.grad)',
                    'import torch\n\n# Baseline reduces variance: grad = (return - b) * log pi\nret, baseline = 1.2, 0.8\nprint("advantage:", ret - baseline)',
                    'import numpy as np\n\n# Policy is stochastic: better exploration than greedy Q\nprint("samples actions from a distribution")',
                ],
            },
            {
                'slug': 'rl-11-actor-critic',
                'title': 'Actor-Critic Methods',
                'desc': 'Two networks in harmony: the actor picks actions, the critic judges them with bootstrapped values.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['RL-10: Policy Gradient Methods'],
                'objs': [
                    'Explain the actor-critic split',
                    'Use the critic as a value baseline',
                    'Implement a simple actor-critic',
                    'Understand A2C and A3C',
                ],
                'samples': [
                    'import torch.nn as nn\n\nclass ActorCritic(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.shared = nn.Sequential(nn.Linear(4, 64), nn.ReLU())\n        self.actor = nn.Linear(64, 2)\n        self.critic = nn.Linear(64, 1)\n    def forward(self, x):\n        h = self.shared(x)\n        return torch.softmax(self.actor(h), -1), self.critic(h)\n\nprint(ActorCritic())',
                    'import torch\n\n# Advantage: r + gamma*V(s\') - V(s) — critic bootstraps\nr, gamma, v_next, v_now = 1.0, 0.9, 0.5, 0.3\nadvantage = r + gamma * v_next - v_now\nprint("advantage:", advantage)',
                    'import torch\n\n# Actor loss: -log pi * advantage. Critic loss: MSE of V\nprint("two losses, one shared network")',
                    'import torch\n\n# A2C: multiple parallel workers synchronize gradients\nprint("A2C uses N parallel environments")',
                ],
            },
            {
                'slug': 'rl-12-proximal-policy-optimization',
                'title': 'PPO & Modern Policy Optimization',
                'desc': 'Stable, sample-efficient updates with clipping — the default choice in modern RL.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['RL-11: Actor-Critic Methods'],
                'objs': [
                    'Explain the PPO clipped objective',
                    'Use importance sampling ratios',
                    'Run PPO with Stable-Baselines3',
                    'Tune PPO hyperparameters',
                ],
                'samples': [
                    'import torch\n\n# Importance ratio: how likely under new vs old policy\nratio = torch.tensor([1.1, 0.9, 1.2])\nprint("ratios:", ratio)',
                    'import torch\n\n# Clipping limits the update: min(ratio*A, clip(ratio, 0.8, 1.2)*A)\nadvantage = torch.tensor([1.0, 0.5, 0.2])\nclipped = torch.clamp(ratio, 0.8, 1.2)\nobj = torch.min(ratio * advantage, clipped * advantage)\nprint("objective:", obj)',
                    'from stable_baselines3 import PPO\n\nmodel = PPO("MlpPolicy", "CartPole-v1", verbose=0)\nmodel.learn(total_timesteps=50_000)\nprint("PPO trained")',
                    'from stable_baselines3 import PPO\n\nmodel = PPO("MlpPolicy", "CartPole-v1", learning_rate=3e-4, n_steps=2048, verbose=0)\nprint("defaults are sensible; tune lr and batch carefully")',
                ],
            },
            {
                'slug': 'rl-13-reward-design',
                'title': 'Reward Design',
                'desc': 'Rewards shape everything: sparse vs dense, shaping and the specification problem.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['RL-01: What Is Reinforcement Learning?'],
                'objs': [
                    'Design rewards that express the true goal',
                    'Handle sparse rewards with shaping',
                    'Avoid reward hacking',
                    'Use reward shaping theorems safely',
                ],
                'samples': [
                    'import numpy as np\n\n# Sparse: reward only at the goal\nsparse = np.zeros(100)\nsparse[-1] = 1.0\nprint("sparse returns nonzero only at end")',
                    'import numpy as np\n\n# Dense shaping: small progress rewards at every step\nprogress = np.linspace(0, 1, 100) * 0.01\nprint("shaped reward example:", progress[:3])',
                    'hacks = ["agent finds loopholes", "exploits simulator bugs", "games the metric"]\nfor h in hacks:\n    print(f"- {h}")',
                    'import numpy as np\n\n# Shaping must not change the optimal policy (potential-based)\nPhi = np.array([0.0, 0.5, 1.0])  # potential per state\ngamma = 0.9\nshaping = gamma * np.roll(Phi, -1) - Phi\nprint("potential shaping:", shaping.round(2))',
                ],
            },
            {
                'slug': 'rl-14-offline-rl',
                'title': 'Offline Reinforcement Learning',
                'desc': 'Learn policies from logged data without a live environment — conservative and practical.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['RL-12: PPO & Modern Policy Optimization'],
                'objs': [
                    'Explain the offline RL setting',
                    'Describe distribution shift',
                    'Use conservative methods (CQL)',
                    'Evaluate offline policies safely',
                ],
                'samples': [
                    'import numpy as np\n\n# Offline dataset: (s, a, r, s\', done) tuples, no new interaction\nN = 1000\ns = np.random.default_rng(0).normal(size=(N, 4))\nprint("offline dataset:", s.shape)',
                    'print("risk: policy sees states it never visited -> unreliable")',
                    'import numpy as np\n\n# Conservative Q: penalize unseen actions\nQ = np.array([0.5, 0.8])\npenalty = 0.1\nprint("conservative Q:", Q - penalty)',
                    'print("evaluate via off-policy evaluation or safe rollout")',
                ],
            },
            {
                'slug': 'rl-15-imitation-learning',
                'title': 'Imitation Learning',
                'desc': 'Learn from demonstrations: behavioral cloning and DAgger for expert-like behavior.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['RL-10: Policy Gradient Methods'],
                'objs': [
                    'Explain behavioral cloning',
                    'Describe the covariate shift problem',
                    'Use DAgger to correct drift',
                    'Combine imitation with RL',
                ],
                'samples': [
                    'import numpy as np\n\n# Behavioral cloning: supervised learning on (obs, action)\nobs = np.random.default_rng(0).normal(size=(500, 4))\nactions = np.random.default_rng(1).randint(0, 2, size=500)\nprint("demo dataset:", obs.shape, actions.shape)',
                    'from sklearn.linear_model import LogisticRegression\n\nclf = LogisticRegression().fit(obs, actions)\nprint("clone accuracy:", round(clf.score(obs, actions), 3))',
                    'print("drift: small errors compound as the agent leaves the demo distribution")',
                    'import numpy as np\n\n# DAgger: query the expert on visited states\nprint("aggregate: add expert labels for states the learner visits")',
                ],
            },
            {
                'slug': 'rl-16-multi-agent-rl',
                'title': 'Multi-Agent Reinforcement Learning',
                'desc': 'Multiple learners interacting: cooperation, competition, and the games they create.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['RL-12: PPO & Modern Policy Optimization'],
                'objs': [
                    'Describe multi-agent settings (cooperative, competitive, mixed)',
                    'Explain non-stationarity',
                    'Use independent learners',
                    'Discuss centralized training, decentralized execution',
                ],
                'samples': [
                    'settings = {\n    "cooperative": "shared reward",\n    "competitive": "zero-sum",\n    "mixed": "social dilemmas",\n}\nprint(settings)',
                    'print("non-stationary: the environment changes as others learn")',
                    'import numpy as np\n\n# Independent Q-learners: each learns its own table\nQ_a = np.zeros((4, 2))\nQ_b = np.zeros((4, 2))\nprint("independent learners")',
                    'print("CTDE: train together centrally, act with local info")',
                ],
            },
            {
                'slug': 'rl-17-rl-in-games',
                'title': 'RL in Games',
                'desc': 'From Atari to AlphaGo: self-play, Monte Carlo tree search, and superhuman play.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['RL-09: Deep Q-Networks (DQN)'],
                'objs': [
                    'Explain self-play',
                    'Describe Monte Carlo tree search (MCTS)',
                    'Combine MCTS with neural nets (AlphaGo)',
                    'Understand why games are ideal testbeds',
                ],
                'samples': [
                    'import numpy as np\n\n# MCTS: select, expand, simulate, backpropagate\nfor _ in range(100):\n    print("node: select -> expand -> rollout -> backup")',
                    'import numpy as np\n\n# UCB in MCTS balances exploration\nN = np.array([10, 5])\nW = np.array([8, 4])\nucb = W / N + np.sqrt(2 * np.log(N.sum()) / N)\nprint("MCTS UCB:", ucb.round(3))',
                    'print("self-play: train against yourself to keep improving")',
                    'import numpy as np\n\n# Value + policy network guides the search\nvalue = 0.7\nprior = np.array([0.6, 0.4])\nprint("neural MCTS blends value and policy priors")',
                ],
            },
            {
                'slug': 'rl-18-rl-for-robotics',
                'title': 'RL for Robotics',
                'desc': 'Physical agents learning motor skills: sim-to-real, reward shaping and safety in the real world.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['RL-12: PPO & Modern Policy Optimization'],
                'objs': [
                    'Describe the challenges of learning on real hardware',
                    'Use simulation with domain randomization',
                    'Explain sim-to-real transfer',
                    'Apply safety constraints in control',
                ],
                'samples': [
                    'import numpy as np\n\n# Domain randomization: randomize physics in sim\nmass = np.random.default_rng(0).uniform(0.8, 1.2)\nfriction = np.random.default_rng(0).uniform(0.5, 1.0)\nprint("randomized mass:", round(mass, 2), "friction:", round(friction, 2))',
                    'print("safety: constraint satisfaction before pure reward")',
                    'import numpy as np\n\n# Action limits keep the robot stable\naction = np.clip(0.9, -1.0, 1.0)\nprint("clipped action:", action)',
                    'print("sim-to-real: train in sim, transfer with randomization")',
                ],
            },
            {
                'slug': 'rl-19-rl-for-recommendation',
                'title': 'RL for Recommender Systems',
                'desc': 'Ranking as sequential decisions: contextual bandits and long-term user value.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['RL-07: Exploration vs Exploitation'],
                'objs': [
                    'Frame recommendation as a bandit problem',
                    'Explain contextual bandits',
                    'Balance short-term engagement with long-term value',
                    'Deploy bandits safely with policies',
                ],
                'samples': [
                    'import numpy as np\n\n# Contextual bandit: choose item given user context\ncontext = np.array([0.3, 0.7, 0.2])\nitem_values = np.array([0.5, 0.9, 0.4])\nprint("recommend item:", int(np.argmax(item_values)))',
                    'import numpy as np\n\n# Explore: try new items for some users\nrng = np.random.default_rng(0)\nif rng.random() < 0.1:\n    print("explore: random item")\nelse:\n    print("exploit: best item")',
                    'import numpy as np\n\n# Long-term value via discounting\nrewards = np.array([1.0, 0.5, 0.8])\nprint("discounted value:", round((0.9 ** np.arange(3) * rewards).sum(), 3))',
                    'print("offline evaluation on logged interactions")',
                ],
            },
            {
                'slug': 'rl-20-evaluating-rl-agents',
                'title': 'Evaluating RL Agents',
                'desc': 'Measures beyond total reward: returns curves, sample efficiency and robustness.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['RL-12: PPO & Modern Policy Optimization'],
                'objs': [
                    'Read learning curves correctly',
                    'Report mean and variance across seeds',
                    'Measure sample efficiency',
                    'Test robustness to environment changes',
                ],
                'samples': [
                    'import numpy as np\n\n# Learning curves: mean + std band over seeds\nseeds = np.random.default_rng(0).normal(size=(5, 100))\nmean = seeds.mean(axis=0)\nstd = seeds.std(axis=0)\nprint("final mean:", round(mean[-1], 2), "+-", round(std[-1], 2))',
                    'import numpy as np\n\n# Sample efficiency: return per timestep\nreturn_per_step = 0.01\nprint("after 1M steps:", int(1_000_000 * return_per_step))',
                    'import numpy as np\n\n# Robustness: perturb the environment\nfor noise in [0.0, 0.1, 0.5]:\n    print(f"noise {noise}: perturbed reward {round(1.0 - noise * 0.5, 2)}")',
                    'print("always report multiple seeds, not one lucky run")',
                ],
            },
            {
                'slug': 'rl-21-roadmap',
                'title': 'Reinforcement Learning Roadmap',
                'desc': 'Synthesize the course, pick a domain, and plan RL projects that build real skill.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['RL-20: Evaluating RL Agents'],
                'objs': [
                    'Map RL concepts to a study plan',
                    'Pick RL projects (games, control, bandits)',
                    'Connect RL to MLOps and production',
                    'Follow research responsibly',
                ],
                'samples': [
                    'plan = {\n    1: "solve CartPole with tabular Q-learning",\n    2: "implement DQN from scratch",\n    3: "train PPO with Stable-Baselines3",\n    4: "run a contextual bandit A/B test",\n}\nprint(plan)',
                    'import gymnasium as gym\n\nenvs = ["CartPole-v1", "LunarLander-v2", "Pendulum-v1"]\nfor e in envs:\n    print("-", e)',
                    'print("RL systems in production need the MLOps course")',
                    'sources = ["Spinning Up", "Stable-Baselines3 docs", "Sutton & Barto", "ICML/NeurIPS RL papers"]\nprint("follow:", ", ".join(sources))',
                ],
            },
        ],
    },

    # ────────────────────────────────────────────────────────────────
    # MLOPS
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'mlops',
        'code_lang': 'python',
        'refs': [
            ('MLflow Documentation', 'https://mlflow.org/docs/latest/index.html', 'Tracking, registries and serving for the ML lifecycle.'),
            ('Kubeflow Documentation', 'https://www.kubeflow.org/docs/', 'Kubernetes-native ML workflows.'),
            ('DVC Documentation', 'https://dvc.org/doc', 'Data version control for reproducible ML pipelines.'),
            ('The ML Engineer — Chip Huyen', 'https://www.oreilly.com/library/view/introduction-to-machine/9781098119478/', 'The reference book on building ML systems in production.'),
            ('Google MLOps Whitepaper', 'https://cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning', 'The canonical description of MLOps levels and practices.'),
        ],
        'lessons': [
            {
                'slug': 'mlops-01-what-is-mlops',
                'title': 'What Is MLOps?',
                'desc': 'The discipline of operationalizing machine learning: people, pipelines, and platforms.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': ['ML-01: What Is Machine Learning?'],
                'objs': [
                    'Define MLOps and why it emerged',
                    'Contrast ML development with ML operations',
                    'Describe the three MLOps maturity levels',
                    'Identify the pillars of production ML systems',
                ],
                'samples': [
                    'pillars = ["data", "models", "code", "deployment", "monitoring"]\nfor p in pillars:\n    print(f"- {p}")',
                    'levels = {\n    1: "manual process",\n    2: "automated pipelines",\n    3: "continuous delivery + monitoring",\n}\nprint(levels)',
                    'print("models decay: data drift makes today\'s model tomorrow\'s liability")',
                    'components = ["training", "serving", "monitoring", "governance", "retraining"]\nprint(components)',
                ],
            },
            {
                'slug': 'mlops-02-the-ml-lifecycle',
                'title': 'The ML Lifecycle',
                'desc': 'From problem definition to retirement: every stage a model passes through.',
                'dur': '50 min', 'diff': 'beginner', 'prereq': ['MLOPS-01: What Is MLOps?'],
                'objs': [
                    'Map the end-to-end ML lifecycle',
                    'Identify where ML projects fail',
                    'Define staging environments (dev/staging/prod)',
                    'Describe the retraining loop',
                ],
                'samples': [
                    'lifecycle = ["define", "collect", "prepare", "train", "evaluate", "deploy", "monitor", "retrain"]\nfor s in lifecycle:\n    print(f"-> {s}")',
                    'risks = ["data mismatch", "no eval set", "serving skew", "no monitoring"]\nfor r in risks:\n    print(f"- {r}")',
                    'envs = {"dev": "experiment", "staging": "validate", "prod": "serve"}\nprint(envs)',
                    'print("the loop: monitor drift -> trigger retraining -> redeploy")',
                ],
            },
            {
                'slug': 'mlops-03-reproducibility-and-versioning',
                'title': 'Reproducibility & Versioning',
                'desc': 'Version code, data and models together — the foundation of trustworthy ML.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['MLOPS-02: The ML Lifecycle'],
                'objs': [
                    'Version data with DVC',
                    'Lock dependencies and environments',
                    'Record model lineage',
                    'Reproduce any historical experiment',
                ],
                'samples': [
                    'import dvc.api\n\n# DVC: data versioned like code\nparams = dvc.api.params_show()\nprint("dvc params:", params)',
                    'import hashlib\n\n# Content hash: the same data hash means the same data\ndef data_hash(path):\n    return hashlib.sha256(open(path, "rb").read()).hexdigest()[:12]\n\nprint("data hash:", data_hash("train.csv"))',
                    'import yaml\n\nenv = {"python": "3.11", "packages": {"torch": "2.2.0", "sklearn": "1.4.0"}}\nprint(env)',
                    'print("lineage: code + data + config -> model artifact")',
                ],
            },
            {
                'slug': 'mlops-04-data-pipelines',
                'title': 'Data Pipelines',
                'desc': 'Reliable, repeatable data flow: ingestion, validation, cleaning and feature preparation.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['MLOPS-02: The ML Lifecycle'],
                'objs': [
                    'Design a data ingestion pipeline',
                    'Validate data with expectations',
                    'Handle incremental updates',
                    'Use orchestration tools (Airflow, Prefect)',
                ],
                'samples': [
                    'import pandas as pd\n\n# Validate: fail fast on bad data\nrequired = ["user_id", "event_time"]\ndf = pd.DataFrame({"user_id": [1, 2], "event_time": ["2024-01-01", None]})\nmissing = [c for c in required if df[c].isna().any()]\nprint("missing required:", missing)',
                    'from airflow import DAG\n\n# DAG: define task dependencies declaratively\nprint("extract -> validate -> transform -> load")',
                    'import pandas as pd\n\n# Incremental: only new rows\ndef load_new(last_id, source):\n    return source[source["id"] > last_id]\n\nprint("incremental load ready")',
                    'import pandera as pa\n\nschema = pa.DataFrameSchema({\n    "price": pa.Column(float, pa.Check.ge(0)),\n})\nprint("schema validation ready")',
                ],
            },
            {
                'slug': 'mlops-05-feature-stores',
                'title': 'Feature Stores',
                'desc': 'One source of truth for features: consistent online and offline features.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['MLOPS-04: Data Pipelines'],
                'objs': [
                    'Explain the feature store concept',
                    'Describe online vs offline features',
                    'Avoid train-serve skew',
                    'Register and reuse features',
                ],
                'samples': [
                    'feature = {\n    "name": "user_7d_spend",\n    "offline": "batch job",\n    "online": "redis lookup",\n}\nprint(feature)',
                    'import redis\n\nr = redis.Redis()\nr.set("user:42:7d_spend", "129.5")\nprint("online feature:", r.get("user:42:7d_spend"))',
                    'print("same code computes offline and online features -> no skew")',
                    'import feast\n\nstore = feast.FeatureStore("feature_repo")\nprint("feature store ready")',
                ],
            },
            {
                'slug': 'mlops-06-experiment-tracking',
                'title': 'Experiment Tracking',
                'desc': 'Log every run: metrics, hyperparameters and artifacts with MLflow.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['MLOPS-03: Reproducibility & Versioning'],
                'objs': [
                    'Log runs with MLflow',
                    'Compare experiments',
                    'Track hyperparameters and metrics',
                    'Search and organize runs',
                ],
                'samples': [
                    'import mlflow\n\nwith mlflow.start_run():\n    mlflow.log_param("lr", 0.01)\n    mlflow.log_metric("accuracy", 0.93)\nprint("run logged")',
                    'import mlflow\n\n# Nested structure: params, metrics, tags\nmlflow.set_tag("team", "fraud")\nprint("tags set")',
                    'import mlflow\n\n# Log artifacts: model files, plots\nmlflow.log_artifact("confusion_matrix.png")\nprint("artifact logged")',
                    'import mlflow\n\nruns = mlflow.search_runs(experiment_names=["default"])\nprint("runs found:", len(runs))',
                ],
            },
            {
                'slug': 'mlops-07-model-registry',
                'title': 'Model Registry',
                'desc': 'Stage models through lifecycles and keep production versions audit-ready.',
                'dur': '45 min', 'diff': 'intermediate', 'prereq': ['MLOPS-06: Experiment Tracking'],
                'objs': [
                    'Register models with MLflow',
                    'Use lifecycle stages (staging, production)',
                    'Version models explicitly',
                    'Enforce promotion gates',
                ],
                'samples': [
                    'import mlflow\n\nmlflow.register_model("runs:/<run_id>/model", "churn_model")\nprint("model registered")',
                    'from mlflow.tracking import MlflowClient\n\nclient = MlflowClient()\nclient.transition_model_version_stage("churn_model", "2", "Production")\nprint("promoted to Production")',
                    'print("every promotion is a reviewable event")',
                    'import mlflow\n\nmodel = mlflow.pyfunc.load_model("models:/churn_model/2")\nprint("loaded production model")',
                ],
            },
            {
                'slug': 'mlops-08-training-at-scale',
                'title': 'Training at Scale',
                'desc': 'Move from notebooks to managed training jobs with reproducible configs.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['MLOPS-06: Experiment Tracking'],
                'objs': [
                    'Package training as a script with configs',
                    'Use distributed training',
                    'Leverage managed training platforms',
                    'Track resource usage and cost',
                ],
                'samples': [
                    'import torch\nimport torch.nn as nn\n\ntorch.distributed.init_process_group(backend="nccl")\nprint("distributed init done")',
                    'import dataclasses\n\n@dataclasses.dataclass\nclass TrainConfig:\n    lr: float = 1e-3\n    epochs: int = 10\n    batch_size: int = 64\n\ncfg = TrainConfig()\nprint(cfg)',
                    'import torch\n\nmodel = nn.DataParallel(nn.Linear(64, 10))\nprint("data-parallel training")',
                    'print("config files in git -> reproducible training runs")',
                ],
            },
            {
                'slug': 'mlops-09-model-packaging',
                'title': 'Model Packaging & Serialization',
                'desc': 'Wrap models into portable artifacts: pickle, ONNX, and MLflow models.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['MLOPS-07: Model Registry'],
                'objs': [
                    'Serialize models safely',
                    'Export to ONNX for portability',
                    'Define a serving signature',
                    'Avoid pickle pitfalls',
                ],
                'samples': [
                    'import pickle\n\nmodel = {"type": "linear", "weights": [0.5, -0.2]}\nwith open("model.pkl", "wb") as fh:\n    pickle.dump(model, fh)\nprint("pickled")',
                    'import torch\nimport torch.onnx\n\nmodel = torch.nn.Linear(4, 2)\ntorch.onnx.export(model, torch.randn(1, 4), "model.onnx")\nprint("exported to ONNX")',
                    'import mlflow\n\nmlflow.sklearn.save_model(model, "model_dir", input_example=[1.0, 2.0])\nprint("mlflow model with signature")',
                    'import numpy as np\n\nprint("pickle runs arbitrary code on load: only trust your own artifacts")',
                ],
            },
            {
                'slug': 'mlops-10-model-serving',
                'title': 'Model Serving APIs',
                'desc': 'Expose models over HTTP with FastAPI and MLflow serving — with proper request validation.',
                'dur': '60 min', 'diff': 'intermediate', 'prereq': ['MLOPS-09: Model Packaging & Serialization'],
                'objs': [
                    'Build a FastAPI inference endpoint',
                    'Define request and response schemas',
                    'Handle batching and timeouts',
                    'Measure latency correctly',
                ],
                'samples': [
                    'from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI()\n\nclass PredictRequest(BaseModel):\n    features: list[float]\n\n@app.post("/predict")\ndef predict(req: PredictRequest):\n    return {"score": sum(req.features) * 0.5}\n\nprint("endpoint ready")',
                    'import numpy as np\n\n# Batch: process many requests in one model call\nbatch = np.array([[1.0, 2.0], [3.0, 4.0]])\nprint("batch shape:", batch.shape)',
                    'import time\n\n# Latency percentiles matter more than the mean\nlat = [10, 12, 90, 11, 13]\nprint("p50:", sorted(lat)[len(lat) // 2], "p95:", sorted(lat)[int(0.95 * len(lat))])',
                    'print("timeout + retry logic protects the service")',
                ],
            },
            {
                'slug': 'mlops-11-containerization',
                'title': 'Containerization with Docker',
                'desc': 'Package the model, code and dependencies into one portable image.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['MLOPS-10: Model Serving APIs'],
                'objs': [
                    'Write a production Dockerfile',
                    'Keep images small and layered',
                    'Run containers locally',
                    'Understand security basics',
                ],
                'samples': [
                    'dockerfile = """FROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD ["uvicorn", "app.main:app", "--host", "0.0.0.0"]\n"""\nprint(dockerfile)',
                    'import subprocess\n\nprint("docker build -t my-model .")',
                    'print("slim base + pinned deps = smaller, reproducible image")',
                    'print("never bake secrets into images")',
                ],
            },
            {
                'slug': 'mlops-12-kubernetes-basics',
                'title': 'Kubernetes Basics for ML',
                'desc': 'Orchestrate containers: pods, deployments, services and autoscaling.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['MLOPS-11: Containerization with Docker'],
                'objs': [
                    'Describe pods, deployments and services',
                    'Deploy a model service',
                    'Autoscale based on load',
                    'Manage GPU resources',
                ],
                'samples': [
                    'manifest = {\n    "kind": "Deployment",\n    "spec": {"replicas": 2, "image": "my-model:1.2"},\n}\nprint(manifest)',
                    'import yaml\n\nservice = {"kind": "Service", "spec": {"selector": {"app": "model"}, "ports": [{"port": 80}]}}\nprint(service)',
                    'print("HorizontalPodAutoscaler scales replicas by CPU")',
                    'print("nodeSelector + limits: pin pods to GPU nodes")',
                ],
            },
            {
                'slug': 'mlops-13-deployment-strategies',
                'title': 'Model Deployment Strategies',
                'desc': 'Ship models safely: shadow, canary and blue-green deployments with rollbacks.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['MLOPS-12: Kubernetes Basics for ML'],
                'objs': [
                    'Compare shadow, canary and blue-green deploys',
                    'Route traffic progressively',
                    'Define rollback criteria',
                    'Avoid duplicated inference cost',
                ],
                'samples': [
                    'strategies = {\n    "shadow": "mirror traffic, no impact",\n    "canary": "5% -> 50% -> 100%",\n    "blue-green": "switch whole fleet at once",\n}\nprint(strategies)',
                    'import random\n\n# Canary: send a fraction of traffic to the new model\nrng = random.Random(0)\nfor req in range(1000):\n    if rng.random() < 0.05:\n        new_model(req)\n    else:\n        old_model(req)\nprint("canary traffic split")',
                    'print("rollback: revert to previous version on metric drop")',
                    'import numpy as np\n\n# Compare old vs new on the same request\nprint("shadow mode logs both predictions for offline diffing")',
                ],
            },
            {
                'slug': 'mlops-14-monitoring-and-drift',
                'title': 'Monitoring & Drift Detection',
                'desc': 'Watch predictions and features: data drift, concept drift and model performance decay.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['MLOPS-13: Model Deployment Strategies'],
                'objs': [
                    'Monitor feature distributions',
                    'Detect data and concept drift',
                    'Track prediction drift',
                    'Set alert thresholds deliberately',
                ],
                'samples': [
                    'import numpy as np\nfrom scipy import stats\n\n# KS test: did the feature distribution change?\nbaseline = np.random.default_rng(0).normal(0, 1, 1000)\ncurrent = np.random.default_rng(1).normal(0.5, 1, 1000)\nprint("KS p-value:", round(stats.ks_2samp(baseline, current).pvalue, 4))',
                    'import numpy as np\n\n# PSI: population stability index\nbins = np.linspace(0, 1, 11)\nactual = np.histogram(np.random.default_rng(0).uniform(size=1000), bins=bins)[0]\nexpected = np.histogram(np.random.default_rng(1).uniform(size=1000), bins=bins)[0]\npsi = ((actual / actual.sum()) - (expected / expected.sum())) * np.log((actual / actual.sum()) / (expected / expected.sum()))\nprint("PSI:", round(psi.sum(), 3))',
                    'import numpy as np\n\n# Concept drift: the relationship changed, not just inputs\nprint("accuracy drops even when features look the same")',
                    'alerts = {"psi > 0.25", "accuracy -5pp", "empty predictions"}\nprint(alerts)',
                ],
            },
            {
                'slug': 'mlops-15-production-evaluation',
                'title': 'Evaluation in Production',
                'desc': 'Estimate quality without labels: sampling, human review, and proxy metrics.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['MLOPS-14: Monitoring & Drift Detection'],
                'objs': [
                    'Design label sampling strategies',
                    'Use human review pipelines',
                    'Define proxy metrics',
                    'Close the feedback loop',
                ],
                'samples': [
                    'import numpy as np\n\n# Sample predictions for labeling\npreds = np.arange(100)\nstratum = preds % 10\nsample = np.random.default_rng(0).choice(preds, size=20, replace=False)\nprint("sampled for review:", sample)',
                    'print("route low-confidence predictions to humans first")',
                    'import numpy as np\n\n# Proxy: clicks approximate quality\nclicks = np.array([1, 0, 1, 1, 0])\nprint("click-through rate:", clicks.mean())',
                    'print("labeled production data becomes the next training set")',
                ],
            },
            {
                'slug': 'mlops-16-cicd-for-ml',
                'title': 'CI/CD for Machine Learning',
                'desc': 'Automate testing, training and deployment in pipelines that run on every change.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['MLOPS-07: Model Registry'],
                'objs': [
                    'Define CI and CD for ML',
                    'Run unit tests on data and code',
                    'Trigger training on data or code changes',
                    'Gate deployments on eval thresholds',
                ],
                'samples': [
                    'import yaml\n\nworkflow = {\n    "name": "train",\n    "on": ["push"],\n    "jobs": {"train": {"steps": ["checkout", "test", "train", "register"]}},\n}\nprint(workflow)',
                    'def test_pipeline():\n    assert sum([1, 2, 3]) == 6\n    return "tests pass"\n\nprint(test_pipeline())',
                    'print("data change -> retrain. code change -> retrain. both audited")',
                    'print("gate: only promote if eval metric beats the champion")',
                ],
            },
            {
                'slug': 'mlops-17-testing-ml-systems',
                'title': 'Testing ML Systems',
                'desc': 'Test data, features, models and infrastructure — because ML code is only part of the system.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['MLOPS-16: CI/CD for Machine Learning'],
                'objs': [
                    'Write data and schema tests',
                    'Test model invariants',
                    'Write golden tests for features',
                    'Load-test the serving path',
                ],
                'samples': [
                    'import pandas as pd\n\ndef test_no_nulls(df):\n    assert not df.isna().any().any()\n\nprint("data test ready")',
                    'def test_probability_range(probs):\n    assert ((probs >= 0) & (probs <= 1)).all()\n\nprint("model invariant test ready")',
                    'import numpy as np\n\n# Golden test: known input -> known output\nknown = np.array([0.0, 1.0, 0.0])\nassert np.allclose(known, [0.0, 1.0, 0.0])\nprint("golden test passes")',
                    'import time\n\n# Load test: requests per second under target latency\nstart = time.perf_counter()\nfor _ in range(100):\n    predict([1.0, 2.0])\nprint("100 calls in", round(time.perf_counter() - start, 3), "s")',
                ],
            },
            {
                'slug': 'mlops-18-governance',
                'title': 'Data & Model Governance',
                'desc': 'Auditability, access control and compliance for ML assets.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['MLOPS-03: Reproducibility & Versioning'],
                'objs': [
                    'Record model cards and lineage',
                    'Control access to data and models',
                    'Meet audit requirements',
                    'Document decisions',
                ],
                'samples': [
                    'model_card = {\n    "owner": "fraud-team",\n    "intended_use": "transaction scoring",\n    "limitations": "trained on EU data",\n    "version": "2.1.0",\n}\nprint(model_card)',
                    'print("every prediction traceable to a model version")',
                    'print("role-based access: analysts read, engineers deploy")',
                    'print("audit log: who changed what, when, why")',
                ],
            },
            {
                'slug': 'mlops-19-cost-and-performance',
                'title': 'Cost & Performance Optimization',
                'desc': 'Balance accuracy against inference cost, latency and carbon.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['MLOPS-13: Model Deployment Strategies'],
                'objs': [
                    'Profile inference latency',
                    'Quantize and distill models',
                    'Right-size infrastructure',
                    'Track cost per prediction',
                ],
                'samples': [
                    'import time\n\n# Profile: find the slow stage\nstart = time.perf_counter()\npredict([1.0] * 10)\nprint("inference ms:", round((time.perf_counter() - start) * 1000, 2))',
                    'import torch\n\n# Quantization: fp32 -> int8, ~4x smaller\nprint("torch.quantization ready")',
                    'import numpy as np\n\n# Cost per prediction\ndaily_cost = 120.0\npredictions = 1_000_000\nprint("cost per prediction:", daily_cost / predictions)',
                    'print("batch requests to amortize GPU cost")',
                ],
            },
            {
                'slug': 'mlops-20-llmops',
                'title': 'LLMOps',
                'desc': 'Operationalize generative AI: prompt management, evals, guardrails and LLM monitoring.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['MLOPS-14: Monitoring & Drift Detection'],
                'objs': [
                    'Track prompts and versions',
                    'Evaluate LLM outputs automatically',
                    'Add guardrails in production',
                    'Monitor tokens, cost and quality',
                ],
                'samples': [
                    'import hashlib\n\n# Version prompts like code\nprompt_v3 = "You are a helpful assistant. Answer concisely."\nprint("prompt hash:", hashlib.sha256(prompt_v3.encode()).hexdigest()[:10])',
                    'import numpy as np\n\n# Auto-eval: LLM-as-judge on a fixed eval set\nscores = np.array([4, 5, 3, 5, 4])\nprint("mean judge score:", scores.mean())',
                    'print("guardrails: block prompt injection and harmful outputs")',
                    'metrics = {"tokens", "cost", "latency", "eval_score", "user_feedback"}\nprint(metrics)',
                ],
            },
            {
                'slug': 'mlops-21-roadmap',
                'title': 'MLOps Roadmap',
                'desc': 'Synthesize the course into a plan: build a production ML system and keep improving it.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['MLOPS-20: LLMOps'],
                'objs': [
                    'Design an end-to-end production project',
                    'Choose tooling that fits the team',
                    'Plan for monitoring from day one',
                    'Bridge into LLMOps and platform engineering',
                ],
                'samples': [
                    'plan = {\n    1: "track experiments with MLflow",\n    2: "package and serve a model with FastAPI",\n    3: "deploy with Docker + Kubernetes",\n    4: "monitor drift and set alerts",\n}\nprint(plan)',
                    'tools = {"tracking": "MLflow", "orchestration": "Airflow", "serving": "FastAPI", "monitoring": "Prometheus + Grafana"}\nprint(tools)',
                    'print("start monitoring before launch, not after an incident")',
                    'print("next: LLM systems need LLMOps discipline too")',
                ],
            },
        ],
    },
]
