"""Curriculum specs for the NLP and Generative AI courses."""

SPECS = [
    # ────────────────────────────────────────────────────────────────
    # NLP
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'nlp',
        'code_lang': 'python',
        'refs': [
            ('Hugging Face NLP Course', 'https://huggingface.co/learn/nlp-course', 'The hands-on course for transformers and modern NLP.'),
            ('Speech and Language Processing — Jurafsky & Martin', 'https://web.stanford.edu/~jurafsky/slp3/', 'The standard textbook for NLP (free draft).'),
            ('Stanford CS224n', 'https://web.stanford.edu/class/cs224n/', 'Natural Language Processing with Deep Learning.'),
            ('NLTK Book', 'https://www.nltk.org/book/', 'Natural Language Processing with Python — classic fundamentals.'),
            ('spaCy Documentation', 'https://spacy.io/usage', 'Industrial-strength NLP library docs.'),
        ],
        'lessons': [
            {
                'slug': 'nlp-01-what-is-nlp',
                'title': 'What Is NLP?',
                'desc': 'The field, the tasks, and the deep-learning revolution that reshaped how machines read language.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': ['DL-01: What Is Deep Learning?'],
                'objs': [
                    'Define natural language processing and its scope',
                    'List the core NLP tasks',
                    'Contrast rule-based and learned approaches',
                    'Identify modern production NLP use cases',
                ],
                'samples': [
                    'tasks = {\n    "classification": "spam, sentiment, topic",\n    "extraction": "entities, relations, keywords",\n    "generation": "summaries, translations, dialogue",\n}\nfor group, examples in tasks.items():\n    print(f"{group:14} {examples}")',
                    'import spacy\n\nnlp = spacy.load("en_core_web_sm")\nprint("spaCy pipeline:", nlp.pipe_names)',
                    'apps = ["search", "chatbots", "translators", "voice assistants", "document search"]\nfor a in apps:\n    print(f"- {a}")',
                    'print("rule-based: brittle. learned: flexible.")',
                ],
            },
            {
                'slug': 'nlp-02-text-representation',
                'title': 'Text Representation: From Tokens to Vectors',
                'desc': 'Tokenization, bag-of-words and TF-IDF — how raw text becomes numbers a model can use.',
                'dur': '55 min', 'diff': 'beginner', 'prereq': ['NLP-01: What Is NLP?'],
                'objs': [
                    'Tokenize text into words and subwords',
                    'Build a bag-of-words representation',
                    'Weight terms with TF-IDF',
                    'Explain sparsity and vocabulary growth',
                ],
                'samples': [
                    'from sklearn.feature_extraction.text import CountVectorizer\n\ncorpus = ["the cat sat", "the dog ran", "cat and dog"]\nvec = CountVectorizer()\nX = vec.fit_transform(corpus)\nprint("vocab:", vec.get_feature_names_out())\nprint("matrix:", X.toarray())',
                    'from sklearn.feature_extraction.text import TfidfVectorizer\n\nvec = TfidfVectorizer()\nX = vec.fit_transform(corpus)\nprint("tfidf:", X.toarray().round(2))',
                    'import nltk\nnltk.download("punkt", quiet=True)\nfrom nltk.tokenize import word_tokenize\n\nprint(word_tokenize("Don\'t stop believing!"))',
                    'from sklearn.feature_extraction.text import CountVectorizer\n\nvec = CountVectorizer(ngram_range=(1, 2))\nprint("with bigrams:", vec.fit_transform(corpus).shape[1], "features")',
                ],
            },
            {
                'slug': 'nlp-03-text-preprocessing',
                'title': 'Text Preprocessing',
                'desc': 'Lowercasing, stop words, stemming and lemmatization — clean text without destroying meaning.',
                'dur': '50 min', 'diff': 'beginner', 'prereq': ['NLP-02: Text Representation: From Tokens to Vectors'],
                'objs': [
                    'Normalize case and punctuation',
                    'Remove stop words judiciously',
                    'Stem and lemmatize words',
                    'Know when preprocessing hurts modern models',
                ],
                'samples': [
                    'import nltk\nfrom nltk.corpus import stopwords\nfrom nltk.tokenize import word_tokenize\n\nnltk.download("stopwords", quiet=True)\nwords = [w.lower() for w in word_tokenize("The quick brown fox jumps over the lazy dog")]\nclean = [w for w in words if w not in stopwords.words("english")]\nprint(clean)',
                    'from nltk.stem import PorterStemmer\n\nstemmer = PorterStemmer()\nprint([stemmer.stem(w) for w in ["running", "runner", "runs"]])',
                    'import nltk\nfrom nltk.stem import WordNetLemmatizer\nnltk.download("wordnet", quiet=True)\n\nlemmatizer = WordNetLemmatizer()\nprint(lemmatizer.lemmatize("running", pos="v"))',
                    'import re\n\nraw = "  Hello,   WORLD!!  "\ncleaned = re.sub(r"[^a-zA-Z0-9\\s]", "", raw).lower().split()\nprint(cleaned)',
                ],
            },
            {
                'slug': 'nlp-04-regular-expressions',
                'title': 'Regular Expressions for Text',
                'desc': 'Pattern matching for extraction, validation and cleaning — the precision tool in every NLP workflow.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['NLP-03: Text Preprocessing'],
                'objs': [
                    'Write regex patterns for common text shapes',
                    'Extract emails, dates and numbers',
                    'Use capture groups and lookarounds',
                    'Clean text at scale with re.sub',
                ],
                'samples': [
                    r"""import re

text = "Contact support@example.com or sales@corp.io by 2024-12-31."
emails = re.findall(r"[\w.+-]+@[\w-]+\.[\w.]+", text)
print(emails)""",
                    r"""import re

dates = re.findall(r"\d{4}-\d{2}-\d{2}", "Due 2024-12-31, reviewed 2025-01-05")
print(dates)""",
                    r"""import re

text = "Order #12345 and #A-999"
ids = re.findall(r"#([A-Za-z0-9-]+)", text)
print(ids)""",
                    r"""import re

messy = "call   me!! maybe??"
clean = re.sub(r"[!?]+", "", messy)
clean = re.sub(r"\s+", " ", clean).strip()
print(clean)""",
                ],
            },
            {
                'slug': 'nlp-05-ngrams-and-language-models',
                'title': 'N-grams & Language Models',
                'desc': 'Model word sequences with Markov assumptions, estimate probabilities, and generate text the old way.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['NLP-03: Text Preprocessing'],
                'objs': [
                    'Explain n-gram counts and conditional probability',
                    'Build a bigram model',
                    'Smooth probabilities to avoid zeros',
                    'Generate text by sampling from the model',
                ],
                'samples': [
                    'from collections import Counter\nfrom nltk import bigrams\n\ntokens = ["i", "love", "nlp", "i", "love", "coffee"]\ncounts = Counter(bigrams(tokens))\nprint(counts)',
                    'import numpy as np\n\n# P(w2 | w1) = count(w1 w2) / count(w1)\ncount_w1 = 2   # "i" appears twice\ncount_w1w2 = 2  # "i love" appears twice\nprint("P(love | i) =", count_w1w2 / count_w1)',
                    'import numpy as np\n\n# Add-one (Laplace) smoothing: no zero probabilities\nV = 1000\nsmooth = (count_w1w2 + 1) / (count_w1 + V)\nprint("smoothed:", round(smooth, 6))',
                    'import random\n\nbigram = {("i", "love"): ["nlp", "coffee"], ("love", "nlp"): ["a", "and"]}\nstart = "i"\nfor _ in range(5):\n    nxt = random.choice(bigram.get((start, None), [\"nlp\"]))\n    print(start, end=" ")\n    start = nxt\nprint()',
                ],
            },
            {
                'slug': 'nlp-06-word-embeddings',
                'title': 'Word Embeddings',
                'desc': 'Dense vectors that capture meaning: word2vec, GloVe, and using embeddings in models.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['NLP-02: Text Representation: From Tokens to Vectors'],
                'objs': [
                    'Explain why dense embeddings beat one-hot vectors',
                    'Describe the word2vec objective',
                    'Load pretrained embeddings',
                    'Use embedding similarity for search and features',
                ],
                'samples': [
                    'import torch\nimport torch.nn as nn\n\nemb = nn.Embedding(1000, 128)\nids = torch.tensor([5, 42, 7])\nprint("embedding shape:", emb(ids).shape)',
                    'import numpy as np\n\n# Semantic arithmetic: king - man + woman ≈ queen\nking = np.array([1.0, 0.9])\nman = np.array([1.0, 0.1])\nwoman = np.array([0.1, 0.9])\nqueen = king - man + woman\nprint("target vector:", queen)',
                    'import gensim.downloader as api\n\n# Pretrained GloVe vectors\nwv = api.load("glove-twitter-25")\nprint("similar:", wv.most_similar("computer")[:3])',
                    'import torch.nn as nn\n\n# Embedding + average pooling as a text feature\nemb = nn.Embedding(100, 64)\ntokens = torch.randint(0, 100, (8, 12))\nfeat = emb(tokens).mean(dim=1)\nprint("doc vector:", feat.shape)',
                ],
            },
            {
                'slug': 'nlp-07-text-classification',
                'title': 'Text Classification',
                'desc': 'Spam, topics, intent: logistic regression and linear models on TF-IDF — fast and often enough.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['NLP-02: Text Representation: From Tokens to Vectors'],
                'objs': [
                    'Frame text classification as a supervised task',
                    'Build a TF-IDF + logistic regression pipeline',
                    'Evaluate with precision/recall per class',
                    'Explain when linear models beat deep ones',
                ],
                'samples': [
                    'from sklearn.pipeline import make_pipeline\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.linear_model import LogisticRegression\n\ntexts = ["cheap pills now", "free money", "meeting at noon", "lunch tomorrow"]\ny = [1, 1, 0, 0]\npipe = make_pipeline(TfidfVectorizer(), LogisticRegression())\npipe.fit(texts, y)\nprint("pred:", pipe.predict(["win a free ipad"])[0])',
                    'from sklearn.model_selection import cross_val_score\n\nscores = cross_val_score(pipe, texts, y, cv=2)\nprint("cv accuracy:", scores.mean().round(2))',
                    'from sklearn.metrics import classification_report\n\nprint(classification_report(y, pipe.predict(texts), target_names=["ham", "spam"]))',
                    'import numpy as np\n\n# Imbalanced data: stratify or weight classes\nfrom sklearn.utils.class_weight import compute_class_weight\nprint("class weights:", compute_class_weight("balanced", classes=np.array([0, 1]), y=np.array(y)))',
                ],
            },
            {
                'slug': 'nlp-08-sentiment-analysis',
                'title': 'Sentiment Analysis',
                'desc': 'Detect opinion and emotion in text — from lexicon scores to fine-tuned transformers.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['NLP-07: Text Classification'],
                'objs': [
                    'Score sentiment with lexicons',
                    'Train a classifier on labeled reviews',
                    'Use a pretrained sentiment model',
                    'Handle negation and domain shift',
                ],
                'samples': [
                    'from textblob import TextBlob\n\nprint(TextBlob("This movie was amazing!").sentiment)\nprint(TextBlob("Waste of time.").sentiment)',
                    'from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer\n\nanalyzer = SentimentIntensityAnalyzer()\nprint(analyzer.polarity_scores("Not bad at all, actually good!"))',
                    'from transformers import pipeline\n\nclassifier = pipeline("sentiment-analysis")\nprint(classifier("I absolutely loved this film"))',
                    'import re\n\n# Negation flips meaning: "not good" != "good"\ntext = "the food was not good"\nprint("flipped" if "not" in text.split() else "same")',
                ],
            },
            {
                'slug': 'nlp-09-named-entity-recognition',
                'title': 'Named Entity Recognition',
                'desc': 'Find people, places, organizations and dates — the extraction workhorse of document AI.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['NLP-02: Text Representation: From Tokens to Vectors'],
                'objs': [
                    'Define NER and common entity types',
                    'Extract entities with spaCy',
                    'Explain BIO tagging',
                    'Fine-tune or use pretrained NER',
                ],
                'samples': [
                    'import spacy\n\nnlp = spacy.load("en_core_web_sm")\ndoc = nlp("Elon Musk founded SpaceX in Hawthorne, California.")\nfor ent in doc.ents:\n    print(ent.text, "->", ent.label_)',
                    'import spacy\n\n# NER as token classification (BIO scheme)\nprint("B-PER I-PER O O B-ORG ...")',
                    'from transformers import pipeline\n\nner = pipeline("ner", aggregation_strategy="simple")\nprint(ner("Apple is looking to buy a startup in London"))',
                    'import spacy\n\n# Custom entities: train with a few hundred labeled examples\nprint("spaCy supports training custom entity types")',
                ],
            },
            {
                'slug': 'nlp-10-pos-tagging',
                'title': 'Part-of-Speech Tagging',
                'desc': 'Tag every token with its grammatical role — the classic sequence-labeling task.',
                'dur': '45 min', 'diff': 'intermediate', 'prereq': ['NLP-03: Text Preprocessing'],
                'objs': [
                    'Explain POS tags and why they matter',
                    'Tag text with NLTK and spaCy',
                    'Use POS tags as features',
                    'Describe sequence labeling formally',
                ],
                'samples': [
                    'import nltk\nnltk.download("averaged_perceptron_tagger_eng", quiet=True)\nfrom nltk import pos_tag, word_tokenize\n\nprint(pos_tag(word_tokenize("The quick brown fox jumps")))',
                    'import spacy\n\nnlp = spacy.load("en_core_web_sm")\ndoc = nlp("They are running late")\nprint([(t.text, t.pos_) for t in doc])',
                    'import spacy\n\n# POS features feed higher-level parsers\nprint("tags: NOUN, VERB, ADJ, ADP, DET ...")',
                    'import spacy\n\n# Disambiguation: "book" as noun vs verb\nfor d in [nlp("read the book"), nlp("book a flight")]:\n    print([(t.text, t.pos_) for t in d])',
                ],
            },
            {
                'slug': 'nlp-11-topic-modeling',
                'title': 'Topic Modeling with LDA',
                'desc': 'Discover latent themes in a corpus with Latent Dirichlet Allocation.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['NLP-02: Text Representation: From Tokens to Vectors'],
                'objs': [
                    'Explain the LDA generative story',
                    'Fit an LDA model with gensim or scikit-learn',
                    'Interpret topic-word distributions',
                    'Choose the number of topics',
                ],
                'samples': [
                    'from sklearn.feature_extraction.text import CountVectorizer\nfrom sklearn.decomposition import LatentDirichletAllocation\n\ndocs = ["cats and dogs and cats", "dogs chase cats", "stocks rally on earnings", "market rally"]\nX = CountVectorizer().fit_transform(docs)\nlda = LatentDirichletAllocation(n_components=2, random_state=0).fit(X)\nprint("topics:", lda.components_.shape)',
                    'import numpy as np\n\n# Top words per topic\nfor t in lda.components_:\n    top = np.argsort(t)[-5:]\n    print([X_feature_names[i] for i in top])',
                    'from sklearn.feature_extraction.text import CountVectorizer\n\nX_feature_names = CountVectorizer().fit(docs).get_feature_names_out()\nprint("vocab size:", len(X_feature_names))',
                    'import numpy as np\n\n# Document-topic mixture: each doc is a blend of topics\nprint(lda.transform(X).round(2))',
                ],
            },
            {
                'slug': 'nlp-12-sequence-models',
                'title': 'Sequence Models for Text',
                'desc': 'Process text as a sequence with RNNs — the pre-transformer era of deep NLP.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-16: LSTM & GRU'],
                'objs': [
                    'Represent text as sequences of token ids',
                    'Build an RNN text classifier',
                    'Understand hidden states as context',
                    'Know why attention replaced recurrence',
                ],
                'samples': [
                    'import torch\nimport torch.nn as nn\n\nclass RNNTextClassifier(nn.Module):\n    def __init__(self, vocab, emb_dim, hid, n_cls):\n        super().__init__()\n        self.emb = nn.Embedding(vocab, emb_dim)\n        self.rnn = nn.LSTM(emb_dim, hid, batch_first=True)\n        self.head = nn.Linear(hid, n_cls)\n    def forward(self, ids):\n        out, _ = self.rnn(self.emb(ids))\n        return self.head(out[:, -1])\n\nprint(RNNTextClassifier(1000, 64, 128, 2))',
                    'import torch\n\nids = torch.randint(0, 1000, (4, 20))\nprint("token ids:", ids.shape)',
                    'import torch.nn as nn\n\n# Padding makes batches rectangular\npad = nn.utils.rnn.pad_sequence([torch.tensor([1, 2]), torch.tensor([3, 4, 5])], batch_first=True)\nprint("padded:", pad)',
                    'print("context carried left-to-right; long-range info fades")',
                ],
            },
            {
                'slug': 'nlp-13-lstm-for-text',
                'title': 'LSTMs for Text',
                'desc': 'Gated memory for language: LSTMs and GRUs that actually hold context over long sequences.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['NLP-12: Sequence Models for Text'],
                'objs': [
                    'Use LSTM cells for text modeling',
                    'Bidirectional context',
                    'Train an LSTM classifier',
                    'Understand the limits that transformers fixed',
                ],
                'samples': [
                    'import torch.nn as nn\n\nlstm = nn.LSTM(64, 128, num_layers=2, batch_first=True)\nprint("2-layer LSTM")',
                    'import torch.nn as nn\n\nbi = nn.LSTM(64, 128, bidirectional=True, batch_first=True)\nout, _ = bi(torch.randn(4, 20, 64))\nprint("bidirectional out:", out.shape)',
                    'import torch\n\n# Packing sequences skips padding for speed/correctness\nprint("pack_padded_sequence handles variable lengths")',
                    'import torch.nn as nn\n\nclass LSTMAgent(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.emb = nn.Embedding(500, 64)\n        self.lstm = nn.LSTM(64, 128, batch_first=True)\n        self.head = nn.Linear(128, 500)\n    def forward(self, ids):\n        out, _ = self.lstm(self.emb(ids))\n        return self.head(out)\n\nprint("next-token LSTM ready")',
                ],
            },
            {
                'slug': 'nlp-14-seq2seq',
                'title': 'Seq2Seq Models & Machine Translation',
                'desc': 'Encoder-decoder architectures that map one sequence to another — the basis of translation.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['NLP-13: LSTMs for Text'],
                'objs': [
                    'Explain the encoder-decoder split',
                    'Decode with greedy and beam search',
                    'Use teacher forcing in training',
                    'Describe how attention improved seq2seq',
                ],
                'samples': [
                    'import torch.nn as nn\n\nclass Encoder(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.emb = nn.Embedding(1000, 64)\n        self.rnn = nn.GRU(64, 128, batch_first=True)\n    def forward(self, ids):\n        _, h = self.rnn(self.emb(ids))\n        return h\n\nprint(Encoder())',
                    'import torch.nn as nn\n\nclass Decoder(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.emb = nn.Embedding(1000, 64)\n        self.rnn = nn.GRU(64, 128, batch_first=True)\n        self.head = nn.Linear(128, 1000)\n    def forward(self, ids, hidden):\n        out, h = self.rnn(self.emb(ids), hidden)\n        return self.head(out), h\n\nprint(Decoder())',
                    'import torch\n\n# Greedy decoding: pick the argmax token at each step\nlogits = torch.randn(1, 5, 1000)\ntok = logits[:, -1].argmax(-1)\nprint("next token id:", tok.item())',
                    'import torch\n\n# Teacher forcing: feed the true token during training\nprint("train with ground truth; decode with own predictions")',
                ],
            },
            {
                'slug': 'nlp-15-attention-and-transformers',
                'title': 'Attention & Transformers for NLP',
                'desc': 'Self-attention makes every token reach every other — the shift that unlocked modern NLP.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['DL-18: Attention Mechanisms'],
                'objs': [
                    'Explain self-attention for text',
                    'Positional encoding for order',
                    'Use transformer encoder and decoder stacks',
                    'Describe the scaling path to LLMs',
                ],
                'samples': [
                    'import torch\nimport torch.nn.functional as F\n\nQ = torch.randn(8, 32)   # 8 tokens\nK = torch.randn(8, 32)\nV = torch.randn(8, 32)\nattn = F.softmax(Q @ K.T / (32 ** 0.5), dim=-1)\nout = attn @ V\nprint("attention out:", out.shape)',
                    'import torch.nn as nn\n\nenc = nn.TransformerEncoderLayer(d_model=64, nhead=8, batch_first=True)\nprint("encoder layer")',
                    'import torch\n\n# Positional encoding gives the model token order\npe = torch.zeros(20, 64)\nfor pos in range(20):\n    for i in range(0, 64, 2):\n        pe[pos, i] = torch.sin(torch.tensor(pos / 10000 ** (i / 64)))\n        pe[pos, i + 1] = torch.cos(torch.tensor(pos / 10000 ** (i / 64)))\nprint("positional encoding:", pe.shape)',
                    'print("all-pairs attention -> parallel, long-range, powerful")',
                ],
            },
            {
                'slug': 'nlp-16-bert-and-pretraining',
                'title': 'BERT & Pretrained Language Models',
                'desc': 'Masked language modeling and the pretrain-then-fine-tune recipe that powers NLP.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['NLP-15: Attention & Transformers for NLP'],
                'objs': [
                    'Explain masked language modeling',
                    'Describe BERT\'s bidirectional encoder',
                    'Load BERT from Hugging Face',
                    'Use embeddings for downstream tasks',
                ],
                'samples': [
                    'from transformers import BertTokenizer, BertModel\n\ntokenizer = BertTokenizer.from_pretrained("bert-base-uncased")\nmodel = BertModel.from_pretrained("bert-base-uncased")\nprint("BERT loaded")',
                    'from transformers import BertTokenizer\n\ninputs = tokenizer("the quick brown fox", return_tensors="pt")\nprint("token ids:", inputs["input_ids"])',
                    'import torch\n\nwith torch.no_grad():\n    out = model(**inputs)\nprint("cls embedding:", out.last_hidden_state[:, 0].shape)',
                    'print("pretrain: learn language. fine-tune: learn the task.")',
                ],
            },
            {
                'slug': 'nlp-17-finetuning-transformers',
                'title': 'Fine-Tuning Transformers',
                'desc': 'Adapt a pretrained model to your task with the Hugging Face Trainer — clean and reproducible.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['NLP-16: BERT & Pretrained Language Models'],
                'objs': [
                    'Tokenize a custom dataset',
                    'Fine-tune a classifier with the Trainer',
                    'Evaluate on a held-out split',
                    'Export and run inference',
                ],
                'samples': [
                    'from datasets import Dataset\n\ndata = Dataset.from_dict({\n    "text": ["great service", "rude staff", "fast delivery"],\n    "label": [1, 0, 1],\n})\nprint(data)',
                    'from transformers import AutoTokenizer\n\ntokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")\n\ndef tokenize(batch):\n    return tokenizer(batch["text"], truncation=True, padding=True)\n\ntokenized = data.map(tokenize, batched=True)\nprint(tokenized)',
                    'from transformers import AutoModelForSequenceClassification, Trainer, TrainingArguments\n\nmodel = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=2)\nargs = TrainingArguments(output_dir="./out", num_train_epochs=2, evaluation_strategy="epoch")\ntrainer = Trainer(model=model, args=args, train_dataset=tokenized, eval_dataset=tokenized)\nprint("trainer ready")',
                    'from transformers import pipeline\n\npipe = pipeline("text-classification", model=model, tokenizer=tokenizer)\nprint(pipe("the product broke on day one"))',
                ],
            },
            {
                'slug': 'nlp-18-question-answering',
                'title': 'Question Answering',
                'desc': 'Extractive and generative QA — from span prediction to retrieval-augmented answers.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['NLP-17: Fine-Tuning Transformers'],
                'objs': [
                    'Distinguish extractive and generative QA',
                    'Run a pretrained extractive QA model',
                    'Pair QA with retrieval (open-domain)',
                    'Evaluate with exact match and F1',
                ],
                'samples': [
                    'from transformers import pipeline\n\nqa = pipeline("question-answering")\nctx = "100xSystems is a developer education platform."\nprint(qa(question="What is 100xSystems?", context=ctx))',
                    'import torch\n\n# Extractive: predict start and end span positions\nstart_logits = torch.randn(50)\nend_logits = torch.randn(50)\nprint("span:", start_logits.argmax().item(), end_logits.argmax().item())',
                    'import numpy as np\n\ndef exact_match(pred, truth):\n    return int(pred.strip().lower() == truth.strip().lower())\n\nprint("EM:", exact_match("Paris", " Paris "))',
                    'print("open-domain QA = retriever + reader")',
                ],
            },
            {
                'slug': 'nlp-19-summarization',
                'title': 'Text Summarization',
                'desc': 'Extractive and abstractive summaries with pretrained sequence-to-sequence models.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['NLP-17: Fine-Tuning Transformers'],
                'objs': [
                    'Compare extractive and abstractive summarization',
                    'Summarize with a pretrained BART/T5 model',
                    'Control summary length',
                    'Evaluate with ROUGE',
                ],
                'samples': [
                    'from transformers import pipeline\n\nsummarizer = pipeline("summarization", model="facebook/bart-large-cnn")\nprint(summarizer("Long article text here...", max_length=50, min_length=10)[0]["summary_text"])',
                    'from transformers import pipeline\n\n# T5 style: task prefix controls behavior\nprint("summarize: <text>")',
                    'from transformers import pipeline\n\nsummarizer = pipeline("summarization")\nout = summarizer("text", max_length=30, min_length=5, do_sample=False)\nprint(out[0]["summary_text"])',
                    'import numpy as np\n\n# ROUGE-N: n-gram overlap between summary and reference\nref = "the cat sat on the mat"\npred = "the cat sat"\nprint("ROUGE-1 precision:", len(set(pred.split()) & set(ref.split())) / len(pred.split()))',
                ],
            },
            {
                'slug': 'nlp-20-evaluation-metrics',
                'title': 'NLP Evaluation Metrics',
                'desc': 'Perplexity, BLEU, ROUGE and human judgment — measuring language models honestly.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['NLP-19: Text Summarization'],
                'objs': [
                    'Compute perplexity for language models',
                    'Use BLEU for translation',
                    'Use ROUGE for summarization',
                    'Know when human evaluation is essential',
                ],
                'samples': [
                    'import torch\nimport torch.nn.functional as F\n\n# Perplexity = exp(cross-entropy)\nlogits = torch.randn(1, 20, 1000)\ntarget = torch.randint(0, 1000, (1, 20))\nce = F.cross_entropy(logits.view(-1, 1000), target.view(-1))\nprint("perplexity:", round(torch.exp(ce).item(), 2))',
                    'from nltk.translate.bleu_score import sentence_bleu\n\nref = [["the", "cat", "sat"]]\ncand = ["the", "cat", "sat"]\nprint("BLEU:", round(sentence_bleu(ref, cand), 3))',
                    'from rouge_score import rouge_scorer\n\nscorer = rouge_scorer.RougeScorer(["rouge1", "rougeL"])\nprint(scorer.score("the cat sat", "the cat sat down"))',
                    'print("automatic metrics correlate, but humans decide quality")',
                ],
            },
            {
                'slug': 'nlp-21-roadmap',
                'title': 'NLP Roadmap',
                'desc': 'Synthesize the course, pick a specialization, and connect NLP to generative AI and LLM engineering.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['NLP-20: NLP Evaluation Metrics'],
                'objs': [
                    'Choose an NLP specialization (search, chatbots, extraction)',
                    'Plan portfolio projects',
                    'Bridge into LLMs and generative AI',
                    'Keep current with the research cycle',
                ],
                'samples': [
                    'plan = {\n    1: "ship a document search app (embeddings + rerank)",\n    2: "fine-tune a model on your own data",\n    3: "next: Generative AI course for LLM systems",\n}\nprint(plan)',
                    'projects = ["review classifier", "FAQ bot with RAG", "meeting summarizer"]\nprint("portfolio:", ", ".join(projects))',
                    'import spacy\n\nprint("spacy", spacy.__version__)',
                    'sources = ["Hugging Face blog", "ACL/EMNLP", "Jay Alammar visualizations"]\nprint("follow:", ", ".join(sources))',
                ],
            },
        ],
    },

    # ────────────────────────────────────────────────────────────────
    # GENERATIVE AI
    # ────────────────────────────────────────────────────────────────
    {
        'lang': 'generative-ai',
        'code_lang': 'python',
        'refs': [
            ('Hugging Face NLP Course', 'https://huggingface.co/learn/nlp-course', 'Transformers, fine-tuning and LLM fundamentals with hands-on code.'),
            ('OpenAI Documentation', 'https://platform.openai.com/docs', 'API reference for GPT models, embeddings and function calling.'),
            ('Attention Is All You Need', 'https://arxiv.org/abs/1706.03762', 'The Transformer paper that made generative AI possible.'),
            ('LangChain Documentation', 'https://python.langchain.com/docs', 'Frameworks for RAG, agents and LLM applications.'),
            ('DeepLearning.AI Short Courses', 'https://www.deeplearning.ai/short-courses/', 'Practical AI courses from industry experts.'),
        ],
        'lessons': [
            {
                'slug': 'genai-01-what-is-generative-ai',
                'title': 'What Is Generative AI?',
                'desc': 'The field that creates text, images, audio and code — and the system stack behind it.',
                'dur': '40 min', 'diff': 'beginner', 'prereq': ['DL-17: Transformers'],
                'objs': [
                    'Define generative AI and contrast it with discriminative models',
                    'List the modalities generative models create',
                    'Describe the modern GenAI stack',
                    'Identify risks and opportunities in production',
                ],
                'samples': [
                    'modalities = {\n    "text": "LLMs",\n    "image": "diffusion, GANs",\n    "audio": "TTS, music",\n    "code": "code models",\n    "video": "diffusion",\n}\nfor m, tech in modalities.items():\n    print(f"{m:8} -> {tech}")',
                    'stack = ["models", "prompt layer", "retrieval", "guardrails", "apps"]\nfor layer in stack:\n    print(f"- {layer}")',
                    'print("discriminative: P(label | x). generative: P(x)")',
                    'risks = ["hallucination", "bias", "prompt injection", "misuse"]\nfor r in risks:\n    print(f"- {r}")',
                ],
            },
            {
                'slug': 'genai-02-probabilistic-generation',
                'title': 'The Mathematics of Generation',
                'desc': 'Generation is sampling from a probability distribution over tokens — conditioned on context.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['GENAI-01: What Is Generative AI?'],
                'objs': [
                    'Model text generation as next-token sampling',
                    'Explain conditional probability chains',
                    'Sample from a categorical distribution',
                    'Control randomness with temperature',
                ],
                'samples': [
                    'import numpy as np\n\n# Next-token distribution\nlogits = np.array([2.0, 1.0, 0.1])\nprobs = np.exp(logits - logits.max())\nprobs = probs / probs.sum()\nprint("probs:", probs.round(3))',
                    'import numpy as np\n\nrng = np.random.default_rng(0)\nprobs = np.array([0.7, 0.2, 0.1])\ntoken = rng.choice(3, p=probs)\nprint("sampled token:", token)',
                    'import numpy as np\n\n# P("cat sat") = P("cat") * P("sat" | "cat")\np_cat = 0.2\np_sat_given_cat = 0.5\nprint("P(cat sat):", p_cat * p_sat_given_cat)',
                    'import numpy as np\n\n# Temperature sharpens or flattens the distribution\nlogits = np.array([2.0, 1.0, 0.1])\nfor t in [0.2, 1.0, 2.0]:\n    p = np.exp(logits / t - (logits / t).max())\n    print(f"T={t}: {np.round(p / p.sum(), 3)}")',
                ],
            },
            {
                'slug': 'genai-03-text-generation-basics',
                'title': 'Text Generation Fundamentals',
                'desc': 'Generate text with pretrained models: sampling strategies, decoding, and the tokens that come out.',
                'dur': '55 min', 'diff': 'intermediate', 'prereq': ['GENAI-02: The Mathematics of Generation'],
                'objs': [
                    'Run a pretrained generation model',
                    'Use greedy and sampling decoding',
                    'Apply top-k and top-p (nucleus) sampling',
                    'Set generation hyperparameters deliberately',
                ],
                'samples': [
                    'from transformers import pipeline\n\npipe = pipeline("text-generation", model="gpt2")\nprint(pipe("Once upon a time,", max_new_tokens=20)[0]["generated_text"])',
                    'from transformers import pipeline\n\npipe = pipeline("text-generation", model="gpt2")\nout = pipe("The future of AI is", max_new_tokens=15, do_sample=True, temperature=0.9)\nprint(out[0]["generated_text"])',
                    'import numpy as np\n\n# Top-k: restrict sampling to the k most likely tokens\nprobs = np.array([0.5, 0.3, 0.15, 0.05])\nk = 2\nmasked = np.where(np.argsort(probs)[::-1] < k, probs, 0)\nprint("top-k probs:", masked / masked.sum())',
                    'import numpy as np\n\n# Top-p: keep the smallest set whose cumulative prob >= p\nprobs = np.array([0.5, 0.3, 0.15, 0.05])\norder = np.argsort(probs)[::-1]\nkeep = np.cumsum(probs[order]) <= 0.8\nprint("nucleus keeps:", order[keep])',
                ],
            },
            {
                'slug': 'genai-04-prompt-engineering',
                'title': 'Prompt Engineering',
                'desc': 'Design instructions that get reliable outputs: roles, structure, few-shot examples and constraints.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['GENAI-03: Text Generation Fundamentals'],
                'objs': [
                    'Structure prompts with roles and tasks',
                    'Use few-shot examples effectively',
                    'Constrain output format (JSON, bullet, length)',
                    'Iterate on prompts systematically',
                ],
                'samples': [
                    'system = "You are a senior backend engineer."\nuser = "Review this code for race conditions: ..."\nprint(system, "|", user)',
                    'from openai import OpenAI\n\nclient = OpenAI()\nres = client.chat.completions.create(\n    model="gpt-4o-mini",\n    messages=[{"role": "user", "content": "Summarize in one sentence: ..."}],\n)\nprint(res.choices[0].message.content)',
                    'prompt = """Extract into JSON: {"name": ..., "price": ...}\nItem: "Wireless mouse, $29"\nAnswer: {"name": "Wireless mouse", "price": 29}\n"""\nprint(prompt)',
                    'print("evaluate prompts on a fixed eval set, not vibes")',
                ],
            },
            {
                'slug': 'genai-05-in-context-learning',
                'title': 'In-Context Learning',
                'desc': 'Teach new tasks with examples in the prompt — no weight updates required.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['GENAI-04: Prompt Engineering'],
                'objs': [
                    'Explain in-context learning (ICL)',
                    'Show zero-shot vs few-shot differences',
                    'Understand context window limits',
                    'Use ICL with structured examples',
                ],
                'samples': [
                    'zero_shot = "Is this review positive or negative? \\"terrible product\\""\nprint(zero_shot)',
                    'few_shot = """Classify sentiment.\\n\\"love it\\" -> positive\\n\\"hate it\\" -> negative\\n\\"it was okay\\" -> neutral\\n\\"amazing\\" ->"""\nprint(few_shot)',
                    'import tiktoken\n\nenc = tiktoken.get_encoding("cl100k_base")\nprint("tokens in prompt:", len(enc.encode("the quick brown fox")))',
                    'print("context window: model sees only what fits in the prompt")',
                ],
            },
            {
                'slug': 'genai-06-llm-architecture',
                'title': 'LLM Architecture & Scaling',
                'desc': 'Decoder-only transformers, scaling laws, and why bigger models behave differently.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['DL-17: Transformers'],
                'objs': [
                    'Describe the decoder-only architecture',
                    'Explain scaling laws (loss vs compute/data)',
                    'Understand pretraining objectives (next-token)',
                    'Discuss capabilities that emerge with scale',
                ],
                'samples': [
                    'import torch.nn as nn\n\n# Decoder-only: causal masked self-attention stack\ndecoder = nn.TransformerDecoderLayer(d_model=512, nhead=8, batch_first=True)\nprint("decoder layer")',
                    'import numpy as np\n\n# Scaling law sketch: loss ~ C^(-alpha)\nC = np.array([1e17, 1e18, 1e19, 1e20])\nloss = 2.5 * C ** -0.05\nfor c, l in zip(C, loss):\n    print(f"compute {c:.0e}: loss {l:.3f}")',
                    'print("objective: maximize P(next_token | context) over trillions of tokens")',
                    'capabilities = ["few-shot", "reasoning", "tool use", "coding"]\nprint(capabilities)',
                ],
            },
            {
                'slug': 'genai-07-tokenization',
                'title': 'Tokenization & the Vocabulary',
                'desc': 'Subword tokens (BPE) — the hidden layer between characters and embeddings.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['GENAI-03: Text Generation Fundamentals'],
                'objs': [
                    'Explain byte-pair encoding (BPE)',
                    'Inspect tokenizers with tiktoken/Hugging Face',
                    'Understand token cost for APIs',
                    'Handle edge cases in tokenization',
                ],
                'samples': [
                    'import tiktoken\n\nenc = tiktoken.get_encoding("cl100k_base")\ntokens = enc.encode("hello world")\nprint("tokens:", tokens, "->", [enc.decode([t]) for t in tokens])',
                    'from transformers import AutoTokenizer\n\ntok = AutoTokenizer.from_pretrained("gpt2")\nprint(tok.tokenize("unhappiness"))',
                    'import tiktoken\n\nenc = tiktoken.get_encoding("cl100k_base")\nprint("1 char:", len(enc.encode("a")))\nprint("10 words:", len(enc.encode("the quick brown fox jumps over the lazy dog")))',
                    'print("tokenization is invisible but drives cost and behavior")',
                ],
            },
            {
                'slug': 'genai-08-fine-tuning-llms',
                'title': 'Fine-Tuning LLMs',
                'desc': 'Adapt a foundation model to a domain with supervised fine-tuning and parameter-efficient methods (LoRA).',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['GENAI-06: LLM Architecture & Scaling'],
                'objs': [
                    'Explain supervised fine-tuning (SFT)',
                    'Prepare instruction datasets',
                    'Use LoRA for efficient fine-tuning',
                    'Know when fine-tuning beats prompting',
                ],
                'samples': [
                    'dataset = [\n    {"instruction": "Translate to French", "input": "hello", "output": "bonjour"},\n    {"instruction": "Translate to French", "input": "goodbye", "output": "au revoir"},\n]\nprint(dataset)',
                    'from transformers import AutoModelForCausalLM\n\nmodel = AutoModelForCausalLM.from_pretrained("gpt2")\nprint("loaded for SFT")',
                    'from peft import LoraConfig, get_peft_model\n\nconfig = LoraConfig(r=8, lora_alpha=16, target_modules=["c_attn"])\npeft_model = get_peft_model(model, config)\nprint("trainable params:", sum(p.numel() for p in peft_model.parameters() if p.requires_grad))',
                    'print("prompt first; RAG second; fine-tune only when needed")',
                ],
            },
            {
                'slug': 'genai-09-rlhf-and-alignment',
                'title': 'RLHF & Alignment',
                'desc': 'Train models to be helpful and harmless: reward models, RLHF and constitutional methods.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['GENAI-08: Fine-Tuning LLMs'],
                'objs': [
                    'Explain the RLHF pipeline (SFT → RM → RL)',
                    'Define reward modeling',
                    'Describe preference optimization (DPO)',
                    'Discuss alignment trade-offs',
                ],
                'samples': [
                    'pipeline = {\n    1: "supervised fine-tuning",\n    2: "reward model from human preferences",\n    3: "reinforcement learning to optimize the reward",\n}\nfor step, stage in pipeline.items():\n    print(f"{step}. {stage}")',
                    'prefs = [\n    ("helpful response A", "unhelpful response B"),\n    ("harmless response A", "harmful response B"),\n]\nprint("preference pairs:", len(prefs))',
                    'print("DPO: optimize preferences directly, no RL loop")',
                    'tradeoffs = ["helpfulness vs harmlessness", "creativity vs factuality"]\nprint(tradeoffs)',
                ],
            },
            {
                'slug': 'genai-10-rag',
                'title': 'Retrieval-Augmented Generation (RAG)',
                'desc': 'Ground answers in your own data: retrieve relevant chunks, stuff the context, generate.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['GENAI-04: Prompt Engineering'],
                'objs': [
                    'Explain the RAG pipeline',
                    'Chunk documents thoughtfully',
                    'Retrieve with embeddings and keyword search',
                    'Build a RAG chain with LangChain',
                ],
                'samples': [
                    'rag = {\n    1: "chunk documents",\n    2: "embed chunks",\n    3: "retrieve top-k for a question",\n    4: "generate with the context",\n}\nprint(rag)',
                    'from langchain_community.vectorstores import FAISS\n\nprint("vector store ready")',
                    'from langchain.text_splitter import RecursiveCharacterTextSplitter\n\nsplitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)\nprint("chunker ready")',
                    'from langchain_core.prompts import ChatPromptTemplate\n\nprompt = ChatPromptTemplate.from_template(\n    "Answer from the context.\\nContext: {context}\\nQuestion: {question}"\n)\nprint(prompt)',
                ],
            },
            {
                'slug': 'genai-11-embeddings-and-vector-databases',
                'title': 'Embeddings & Vector Databases',
                'desc': 'Semantic search at scale: embedding models, vector indexes, and ANN search.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['GENAI-10: Retrieval-Augmented Generation (RAG)'],
                'objs': [
                    'Generate text embeddings',
                    'Measure semantic similarity',
                    'Index vectors with ANN (HNSW, FAISS)',
                    'Evaluate retrieval quality',
                ],
                'samples': [
                    'from openai import OpenAI\n\nclient = OpenAI()\nvec = client.embeddings.create(model="text-embedding-3-small", input=["hello world"])\nprint("embedding dim:", len(vec.data[0].embedding))',
                    'import numpy as np\n\ndef cos(a, b):\n    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))\n\nprint("similarity:", round(cos(np.array([1, 0]), np.array([0.9, 0.1])), 3))',
                    'import faiss\n\nindex = faiss.IndexFlatL2(384)\nindex.add(np.random.default_rng(0).normal(size=(1000, 384)).astype("float32"))\ndists, idxs = index.search(np.random.default_rng(1).normal(size=(1, 384)).astype("float32"), k=5)\nprint("top-5 ids:", idxs[0])',
                    'import numpy as np\n\n# Retrieval quality: hits@k on labeled queries\nqueries = np.random.default_rng(0).normal(size=(10, 384)).astype("float32")\nprint("evaluate hits@k on a labeled set")',
                ],
            },
            {
                'slug': 'genai-12-agents-and-tool-use',
                'title': 'Agents & Tool Use',
                'desc': 'Let models call functions, use tools, and loop until the job is done.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['GENAI-04: Prompt Engineering'],
                'objs': [
                    'Explain function calling',
                    'Define an agent loop (reason → act → observe)',
                    'Build a simple tool-using agent',
                    'Manage loops and error cases safely',
                ],
                'samples': [
                    'from openai import OpenAI\n\nclient = OpenAI()\nres = client.chat.completions.create(\n    model="gpt-4o-mini",\n    messages=[{"role": "user", "content": "What is the weather in Paris?"}],\n    tools=[{\n        "type": "function",\n        "function": {\n            "name": "get_weather",\n            "parameters": {"type": "object", "properties": {"city": {"type": "string"}}},\n        },\n    }],\n)\nprint(res.choices[0].message.tool_calls)',
                    'tools = {"search": search_fn, "calculator": calc_fn}\nprint("registered tools:", list(tools))',
                    'import time\n\n# Agent loop: while task not done -> call model -> call tool\nfor step in range(3):\n    print(f"step {step}: reason -> act -> observe")\n    time.sleep(0.1)',
                    'safety = ["max iterations", "timeouts", "tool allow-list", "human approval"]\nprint(safety)',
                ],
            },
            {
                'slug': 'genai-13-diffusion-models',
                'title': 'Diffusion Models for Images',
                'desc': 'Generate images by learning to denoise: forward noise, reverse denoising, and text conditioning.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['DL-12: Convolutional Networks'],
                'objs': [
                    'Explain the diffusion process (noise → denoise)',
                    'Describe the U-Net denoiser',
                    'Use a pretrained text-to-image model',
                    'Control generation with prompts and seeds',
                ],
                'samples': [
                    'import numpy as np\n\n# Forward: add noise gradually\nimg = np.zeros((4, 4))\nnoisy = img + np.random.default_rng(0).normal(0, 0.5, img.shape)\nprint("noised sample")',
                    'from diffusers import StableDiffusionPipeline\n\npipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5")\nprint("diffusion pipeline loaded")',
                    'image = pipe("a cozy cabin in snowy mountains", num_inference_steps=30, seed=42).images[0]\nprint("generated image:", image.size)',
                    'import torch\n\n# Denoising loop: predict noise, remove a step\nprint("reverse process: iterate t from T down to 0")',
                ],
            },
            {
                'slug': 'genai-14-gans',
                'title': 'Generative Adversarial Networks',
                'desc': 'Two networks in a zero-sum game: the generator fools the discriminator, and both improve.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['DL-12: Convolutional Networks'],
                'objs': [
                    'Explain the generator-discriminator game',
                    'Train a simple GAN',
                    'Handle mode collapse and instability',
                    'Compare GANs to diffusion',
                ],
                'samples': [
                    'import torch.nn as nn\n\nclass Generator(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Sequential(nn.Linear(100, 256), nn.ReLU(), nn.Linear(256, 784), nn.Tanh())\n    def forward(self, z):\n        return self.net(z)\n\nprint(Generator())',
                    'import torch.nn as nn\n\nclass Discriminator(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.net = nn.Sequential(nn.Linear(784, 256), nn.LeakyReLU(0.2), nn.Linear(256, 1), nn.Sigmoid())\n    def forward(self, x):\n        return self.net(x)\n\nprint(Discriminator())',
                    'import torch\n\nz = torch.randn(8, 100)  # latent noise\nfake = Generator()(z)\nprint("fake images:", fake.shape)',
                    'import torch.nn as nn\n\n# GAN loss: binary cross-entropy on real vs fake\nloss = nn.BCELoss()\nprint("adversarial objective ready")',
                ],
            },
            {
                'slug': 'genai-15-vision-language-models',
                'title': 'Vision-Language Models',
                'desc': 'Bridge images and text: CLIP, captioning, and multimodal chat (LLaVA, GPT-4V).',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['GENAI-13: Diffusion Models for Images'],
                'objs': [
                    'Explain contrastive image-text learning (CLIP)',
                    'Generate captions with a pretrained VLM',
                    'Do zero-shot classification with CLIP',
                    'Use multimodal chat models',
                ],
                'samples': [
                    'import torch\n\n# CLIP aligns image and text embeddings in one space\nimage_emb = torch.randn(512)\ntext_emb = torch.randn(512)\nsim = torch.nn.functional.cosine_similarity(image_emb, text_emb, dim=0)\nprint("similarity:", round(sim.item(), 3))',
                    'from transformers import pipeline\n\ncaptioner = pipeline("image-to-text", model="Salesforce/blip-image-captioning-base")\nprint(captioner("photo.png"))',
                    'import torch\n\n# Zero-shot classification: pick the label text with highest similarity\nlabels = ["a dog", "a cat", "a car"]\nscores = torch.rand(3)\nprint("predicted:", labels[scores.argmax()])',
                    'print("multimodal chat: images + text in, text out")',
                ],
            },
            {
                'slug': 'genai-16-audio-and-speech',
                'title': 'Generative Audio & Speech',
                'desc': 'Text-to-speech, voice cloning and music generation with modern neural audio models.',
                'dur': '50 min', 'diff': 'advanced', 'prereq': ['GENAI-03: Text Generation Fundamentals'],
                'objs': [
                    'Explain the TTS pipeline (text → tokens → waveform)',
                    'Run a pretrained TTS model',
                    'Understand audio tokenization',
                    'Discuss voice-cloning ethics',
                ],
                'samples': [
                    'import torch\n\n# Audio as waveforms and spectrograms\nwave = torch.randn(16000)\nprint("1 second at 16kHz:", wave.shape)',
                    'from transformers import pipeline\n\ntts = pipeline("text-to-speech", model="facebook/mms-tts-eng")\nout = tts("Hello world")\nprint("sample rate:", out["sampling_rate"])',
                    'import numpy as np\n\n# Spectrogram: frequency content over time\nsr = 16000\nfreqs = np.fft.rfftfreq(1024, 1 / sr)\nprint("spectrogram bins:", len(freqs))',
                    'print("voice cloning requires consent")',
                ],
            },
            {
                'slug': 'genai-17-evaluating-llms',
                'title': 'Evaluating LLMs',
                'desc': 'Benchmarks, evals and human review — measuring quality, safety and reliability.',
                'dur': '55 min', 'diff': 'advanced', 'prereq': ['GENAI-08: Fine-Tuning LLMs'],
                'objs': [
                    'Use standard benchmarks (MMLU, HumanEval)',
                    'Build task-specific eval sets',
                    'Measure hallucination and grounding',
                    'Track evals in CI',
                ],
                'samples': [
                    'benchmarks = {\n    "MMLU": "knowledge across 57 subjects",\n    "HumanEval": "code generation",\n    "GSM8K": "math reasoning",\n}\nprint(benchmarks)',
                    'eval_set = [\n    {"question": "What is 2+2?", "expected": "4"},\n    {"question": "Capital of France?", "expected": "Paris"},\n]\nprint("task evals:", len(eval_set))',
                    'import numpy as np\n\n# Grounding: does the answer cite the provided context?\nanswer = "Paris (source: doc 3)"\ngrounded = "doc 3" in answer\nprint("grounded:", grounded)',
                    'print("regression: run evals on every prompt change")',
                ],
            },
            {
                'slug': 'genai-18-llmops',
                'title': 'LLMOps: Running GenAI in Production',
                'desc': 'Prompt management, caching, guardrails, monitoring and cost control for LLM apps.',
                'dur': '60 min', 'diff': 'advanced', 'prereq': ['GENAI-10: Retrieval-Augmented Generation (RAG)'],
                'objs': [
                    'Version prompts and evals',
                    'Cache completions and embeddings',
                    'Apply guardrails and moderation',
                    'Monitor latency, cost and quality',
                ],
                'samples': [
                    'import hashlib\n\n# Semantic-ish cache key from the prompt\ndef cache_key(prompt: str) -> str:\n    return hashlib.sha256(prompt.encode()).hexdigest()\n\nprint(cache_key("summarize this article"))',
                    'from openai import OpenAI\n\nclient = OpenAI()\nres = client.moderations.create(input="some user text")\nprint("flagged:", res.results[0].flagged)',
                    'import time\n\n# Track cost: tokens in/out per request\ncost = {\n    "prompt_tokens": 120,\n    "completion_tokens": 40,\n    "price_per_1k": 0.00015,\n}\nest = (cost["prompt_tokens"] + cost["completion_tokens"]) / 1000 * cost["price_per_1k"]\nprint("estimated cost:", est)',
                    'metrics = ["latency", "tokens", "cost", "hallucination rate", "user feedback"]\nprint(metrics)',
                ],
            },
            {
                'slug': 'genai-19-ethical-ai-and-safety',
                'title': 'Ethical AI & Safety',
                'desc': 'Bias, privacy, transparency and misuse — the responsibilities that come with generative models.',
                'dur': '50 min', 'diff': 'intermediate', 'prereq': ['GENAI-01: What Is Generative AI?'],
                'objs': [
                    'Identify bias sources in training data',
                    'Explain privacy risks (PII, memorization)',
                    'Design for transparency and auditability',
                    'Build safeguards against misuse',
                ],
                'samples': [
                    'concerns = {\n    "bias": "skewed training data -> skewed outputs",\n    "privacy": "models can memorize training data",\n    "misuse": "fraud, disinformation, impersonation",\n}\nprint(concerns)',
                    'import re\n\n# Never log raw PII from prompts\nprompt = "my email is john@example.com"\nsanitized = re.sub(r"[\\w.+-]+@[\\w-]+\\.[\\w.]+", "[EMAIL]", prompt)\nprint(sanitized)',
                    'print("disclose: tell users when content is AI-generated")',
                    'guardrails = ["input filtering", "output moderation", "rate limits", "human review"]\nprint(guardrails)',
                ],
            },
            {
                'slug': 'genai-20-building-genai-applications',
                'title': 'Building a GenAI Application',
                'desc': 'Assemble the stack: model, retrieval, guardrails and a clean interface — end to end.',
                'dur': '75 min', 'diff': 'advanced', 'prereq': ['GENAI-18: LLMOps: Running GenAI in Production'],
                'objs': [
                    'Design an LLM application architecture',
                    'Wire RAG + guardrails into a chat loop',
                    'Stream responses to the UI',
                    'Deploy and monitor the app',
                ],
                'samples': [
                    'arch = {\n    "frontend": "chat UI with streaming",\n    "backend": "RAG chain + guardrails",\n    "data": "vector store + documents",\n    "ops": "evals, caching, monitoring",\n}\nfor layer, role in arch.items():\n    print(f"{layer:8} {role}")',
                    'from openai import OpenAI\n\nclient = OpenAI()\nstream = client.chat.completions.create(\n    model="gpt-4o-mini",\n    messages=[{"role": "user", "content": "hi"}],\n    stream=True,\n)\nfor chunk in stream:\n    print(chunk.choices[0].delta.content or "", end="")\nprint()',
                    'print("guardrails in, quality checks out")',
                    'deploy = ["docker", "load balancer", "evals in CI", "dashboards"]\nprint(deploy)',
                ],
            },
            {
                'slug': 'genai-21-roadmap',
                'title': 'Generative AI Roadmap',
                'desc': 'Synthesize everything into a career and project plan — and keep up as the field accelerates.',
                'dur': '40 min', 'diff': 'advanced', 'prereq': ['GENAI-20: Building a GenAI Application'],
                'objs': [
                    'Design a personal GenAI specialization plan',
                    'Pick flagship projects (RAG app, fine-tune, agent)',
                    'Connect to data science, ML and deep learning courses',
                    'Follow research and practice responsibly',
                ],
                'samples': [
                    'plan = {\n    1: "ship a RAG knowledge-base app",\n    2: "build a tool-using agent",\n    3: "fine-tune a small model with LoRA",\n}\nprint(plan)',
                    'foundations = {\n    "math": "data-science course",\n    "core": "machine-learning course",\n    "depth": "deep-learning course",\n}\nprint(foundations)',
                    'stack = ["prompts", "RAG", "agents", "evals", "guardrails"]\nfor s in stack:\n    print(f"- {s}")',
                    'sources = ["arXiv", "Hugging Face", "OpenAI blog", "DeepLearning.AI"]\nprint("follow:", ", ".join(sources))',
                ],
            },
        ],
    },
]
